SIAM-Keldysh-mfRG: InterpolatorLinOrSloppy.hpp File Reference
InterpolatorLinOrSloppy.hpp File Reference
#include <cmath>
#include <functional>
#include "../grids/frequency_grid.hpp"
#include "../symmetries/symmetry_transformations.hpp"
Functions
template<typename Q , typename Grid >
static auto interpolate_nearest1D (const double &x, const Grid &frequencies, const std::function< Q(const int &)> val) -> Q
TODO: improve performance, allow more inlining.
template<typename Q , typename Grid >
static auto interpolate_nearest2D (const double &x, const double &y, const Grid &xfrequencies, const Grid &yfrequencies, const std::function< Q(const int &, const int &)> val) -> Q
template<typename Q , typename Grid >
static auto interpolate_nearest3D (const double &x, const double &y, const double &z, const Grid &xfrequencies, const Grid &yfrequencies, const Grid &zfrequencies, const std::function< Q(const int &, const int &, const int &)> val) -> Q
template<typename Q , typename Grid >
static auto interpolate_lin1D (const double &x, const Grid &frequencies, const std::function< Q(const int &)> val) -> Q
template<typename Q , typename Grid >
static auto interpolate_lin2D (const double &x, const double &y, const Grid &xfrequencies, const Grid &yfrequencies, const std::function< Q(const int &, const int &)> val) -> Q
template<typename Q , typename Grid >
static auto interpolate_lin3D (const double &x, const double &y, const double &z, const Grid &xfrequencies, const Grid &yfrequencies, const Grid &zfrequencies, const std::function< Q(const int &, const int &, const int &)> val) -> Q
template<typename Q , typename Grid >
auto interpolate_lin_on_aux1D (const double &x, const Grid &frequencies, const std::function< Q(const int &)> &val) -> Q
template<typename Q , typename Grid >
auto interpolate_lin_on_aux2D (const double &x, const double &y, const Grid &xfrequencies, const Grid &yfrequencies, const std::function< Q(const int &, const int &)> &val) -> Q
template<typename Q , typename Grid >
auto interpolate_lin_on_aux3D (const double &x, const double &y, const double &z, const Grid &xfrequencies, const Grid &yfrequencies, const Grid &zfrequencies, const std::function< Q(const int &, const int &, const int &)> &val) -> Q
template<typename Q , typename Grid >
auto interpolate_sloppycubic1D (const double &x, const Grid &xfrequencies, const std::function< Q(const int &)> &val) -> Q
template<typename Q , typename Grid >
auto interpolate_sloppycubic2D (const double x, const double y, const Grid &xfrequencies, const Grid &yfrequencies, const std::function< Q(const int &, const int &)> &val) -> Q
template<typename Q , typename Grid >
auto interpolate_sloppycubic3D (const double &x, const double &y, const double &z, const Grid &xfrequencies, const Grid &yfrequencies, const Grid &zfrequencies, const std::function< Q(const int &, const int &, const int &)> &val) -> Q
Function Documentation
interpolate_lin1D()
template<typename Q , typename Grid > static auto interpolate_lin1D (const double & x, const Grid & frequencies, const std::function< Q(const int &)> val) -> Q static
Interpolates linearly in 1D (on linear, auxiliary frequency grid) ATTENTION!: all
Template Parameters
Q double or comp
Parameters
x
frequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
val any function that takes one integer and returns a value of type Q
Returns
Definition at line 105 of file InterpolatorLinOrSloppy.hpp.
{
    int index = frequencies.get_grid_index(x);
    double x1 = frequencies.get_frequency(index);
    double x2 = frequencies.get_frequency(index + 1);
    double xd = (x - x1) / (x2 - x1);
    Q f1 = val(index);
    Q f2 = val(index + 1);
    Q result = ((1. - xd) * f1 + xd * f2);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_lin2D()
template<typename Q , typename Grid > static auto interpolate_lin2D (const double & x, const double & y, const Grid & xfrequencies, const Grid & yfrequencies, const std::function< Q(const int &, const int &)> val) -> Q static
Interpolates linearly in 2D (on linear, auxiliary frequency grid)
Template Parameters
Q double or comp
Parameters
x
y
xfrequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
yfrequencies frequencyGrid with the functions get_grid_index and with y-values in vector all_frequencies
val any function f(i,j) that takes two integers and returns a value of type Q where integer i belongs to x and integer j belongs to y
Returns
Definition at line 134 of file InterpolatorLinOrSloppy.hpp.
{
    int index = xfrequencies.get_grid_index(x);
    double x1 = xfrequencies.get_frequency(index);
    double x2 = xfrequencies.get_frequency(index + 1);
    double xd = (x - x1) / (x2 - x1);
    Q f1 = interpolate_lin1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index  , i);});
    Q f2 = interpolate_lin1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index+1, i);});
    Q result = ((1. - xd) * f1 + xd * f2);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_lin3D()
template<typename Q , typename Grid > static auto interpolate_lin3D (const double & x, const double & y, const double & z, const Grid & xfrequencies, const Grid & yfrequencies, const Grid & zfrequencies, const std::function< Q(const int &, const int &, const int &)> val) -> Q static
Interpolates linearly in 3D (on linear, auxiliary frequency grid)
Template Parameters
Q double or comp
Parameters
x
y
z
xfrequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
yfrequencies frequencyGrid with the functions get_grid_index and with y-values in vector all_frequencies
zfrequencies frequencyGrid with the functions get_grid_index and with z-values in vector all_frequencies
val any function f(i,j,k) that takes three integers and returns a value of type Q where integer i belongs to x and integer j belongs to y and integer k belongs to z
Returns
Definition at line 168 of file InterpolatorLinOrSloppy.hpp.
{
    int index = xfrequencies.get_grid_index(x);
    double x1 = xfrequencies.get_frequency(index);
    double x2 = xfrequencies.get_frequency(index + 1);
    double xd = (x - x1) / (x2 - x1);
    Q f1 = interpolate_lin2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index  , i, j);});
    Q f2 = interpolate_lin2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index+1, i, j);});
    Q result = ((1. - xd) * f1 + xd * f2);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_lin_on_aux1D()
template<typename Q , typename Grid > auto interpolate_lin_on_aux1D (const double & x, const Grid & frequencies, const std::function< Q(const int &)> & val) -> Q inline
Interpolates linearly in 1D (on linear, auxiliary frequency grid) ATTENTION!: all
Template Parameters
Q double or comp
Parameters
x
frequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
val any function that takes one integer and returns a value of type Q
Returns
Definition at line 198 of file InterpolatorLinOrSloppy.hpp.
{
    double t;
    const int index = frequencies.get_grid_index(t, x);
    const double x1 = frequencies.get_auxiliary_gridpoint(index);
    const double x2 = frequencies.get_auxiliary_gridpoint(index + 1);
    const double xd = (t - x1) / (x2 - x1);
    const Q f1 = val(index);
    const Q f2 = val(index + 1);
    const Q result = ((1. - xd) * f1 + xd * f2);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_lin_on_aux2D()
template<typename Q , typename Grid > auto interpolate_lin_on_aux2D (const double & x, const double & y, const Grid & xfrequencies, const Grid & yfrequencies, const std::function< Q(const int &, const int &)> & val) -> Q inline
Interpolates linearly in 2D (on linear, auxiliary frequency grid)
Template Parameters
Q double or comp
Parameters
x
y
xfrequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
yfrequencies frequencyGrid with the functions get_grid_index and with y-values in vector all_frequencies
val any function f(i,j) that takes two integers and returns a value of type Q where integer i belongs to x and integer j belongs to y
Returns
Definition at line 228 of file InterpolatorLinOrSloppy.hpp.
{
    double t;
    int index = xfrequencies.get_grid_index(t, x);
    double x1 = xfrequencies.get_auxiliary_gridpoint(index);
    double x2 = xfrequencies.get_auxiliary_gridpoint(index + 1);
    double xd = (t - x1) / (x2 - x1);
    Q f1 = interpolate_lin_on_aux1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index  , i);});
    Q f2 = interpolate_lin_on_aux1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index+1, i);});
    Q result = ((1. - xd) * f1 + xd * f2);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_lin_on_aux3D()
template<typename Q , typename Grid > auto interpolate_lin_on_aux3D (const double & x, const double & y, const double & z, const Grid & xfrequencies, const Grid & yfrequencies, const Grid & zfrequencies, const std::function< Q(const int &, const int &, const int &)> & val) -> Q inline
Interpolates linearly in 3D (on linear, auxiliary frequency grid)
Template Parameters
Q double or comp
Parameters
x
y
z
xfrequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
yfrequencies frequencyGrid with the functions get_grid_index and with y-values in vector all_frequencies
zfrequencies frequencyGrid with the functions get_grid_index and with z-values in vector all_frequencies
val any function f(i,j,k) that takes three integers and returns a value of type Q where integer i belongs to x and integer j belongs to y and integer k belongs to z
Returns
Definition at line 263 of file InterpolatorLinOrSloppy.hpp.
{
    double t;
    int index = xfrequencies.get_grid_index(t, x);
    double x1 = xfrequencies.get_auxiliary_gridpoint(index);
    double x2 = xfrequencies.get_auxiliary_gridpoint(index + 1);
    double xd = (t - x1) / (x2 - x1);
    Q f1 = interpolate_lin_on_aux2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index  , i, j);});
    Q f2 = interpolate_lin_on_aux2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index+1, i, j);});
    Q result = ((1. - xd) * f1 + xd * f2);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_nearest1D()
template<typename Q , typename Grid > static auto interpolate_nearest1D (const double & x, const Grid & frequencies, const std::function< Q(const int &)> val) -> Q static
TODO: improve performance, allow more inlining.
Interpolation functions: --> linear interpolation --> linear interpolation on auxiliary (linear) frequency grid --> sloppy cubic interpolation (constructs Lagrange polynomial with points at positions i-1, i, i+1 and i+2 for the interval between i and i+1) Interpolates in 0th order in 1D (on linear, auxiliary frequency grid) ATTENTION!: all
Template Parameters
Q double or comp
Parameters
x
frequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
val any function that takes one integer and returns a value of type Q
Returns
Definition at line 31 of file InterpolatorLinOrSloppy.hpp.
{
    int index = frequencies.get_grid_index(x);
    Q result = val(index);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_nearest2D()
template<typename Q , typename Grid > static auto interpolate_nearest2D (const double & x, const double & y, const Grid & xfrequencies, const Grid & yfrequencies, const std::function< Q(const int &, const int &)> val) -> Q static
Interpolates in 0th order in 2D (on linear, auxiliary frequency grid)
Template Parameters
Q double or comp
Parameters
x
y
xfrequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
yfrequencies frequencyGrid with the functions get_grid_index and with y-values in vector all_frequencies
val any function f(i,j) that takes two integers and returns a value of type Q where integer i belongs to x and integer j belongs to y
Returns
Definition at line 53 of file InterpolatorLinOrSloppy.hpp.
{
    int index = xfrequencies.get_grid_index(x);
    Q result = interpolate_nearest1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index  , i);});
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_nearest3D()
template<typename Q , typename Grid > static auto interpolate_nearest3D (const double & x, const double & y, const double & z, const Grid & xfrequencies, const Grid & yfrequencies, const Grid & zfrequencies, const std::function< Q(const int &, const int &, const int &)> val) -> Q static
Interpolates in 0th order in 3D (on linear, auxiliary frequency grid)
Template Parameters
Q double or comp
Parameters
x
y
z
xfrequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
yfrequencies frequencyGrid with the functions get_grid_index and with y-values in vector all_frequencies
zfrequencies frequencyGrid with the functions get_grid_index and with z-values in vector all_frequencies
val any function f(i,j,k) that takes three integers and returns a value of type Q where integer i belongs to x and integer j belongs to y and integer k belongs to z
Returns
Definition at line 81 of file InterpolatorLinOrSloppy.hpp.
{
    int index = xfrequencies.get_grid_index(x);
    Q result = interpolate_nearest2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index  , i, j);});
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_sloppycubic1D()
template<typename Q , typename Grid > auto interpolate_sloppycubic1D (const double & x, const Grid & xfrequencies, const std::function< Q(const int &)> & val) -> Q inline
Interpolates cubically in 1D (on linear, auxiliary frequency grid) ATTENTION!: all
Template Parameters
Q double or comp
Parameters
x
frequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
val any function that takes one integer and returns a value of type Q
Returns
Definition at line 293 of file InterpolatorLinOrSloppy.hpp.
{
    double t;
    int index = xfrequencies.get_grid_index(t, x);
    double x0 = xfrequencies.get_auxiliary_gridpoint(index - 1);
    double x1 = xfrequencies.get_auxiliary_gridpoint(index    );
    double x2 = xfrequencies.get_auxiliary_gridpoint(index + 1);
    double x3 = xfrequencies.get_auxiliary_gridpoint(index + 2);
    auto f0 = val(index - 1);
    auto f1 = val(index    );
    auto f2 = val(index + 1);
    auto f3 = val(index + 2);
    Q result = ((t - x1)*(t - x2)*(t - x3)/((x0-x1)*(x0-x2)*(x0-x3)) * f0
                +(t - x0)*(t - x2)*(t - x3)/((x1-x0)*(x1-x2)*(x1-x3)) * f1
                +(t - x0)*(t - x1)*(t - x3)/((x2-x0)*(x2-x1)*(x2-x3)) * f2
                +(t - x0)*(t - x1)*(t - x2)/((x3-x0)*(x3-x1)*(x3-x2)) * f3);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_sloppycubic2D()
template<typename Q , typename Grid > auto interpolate_sloppycubic2D (const double x, const double y, const Grid & xfrequencies, const Grid & yfrequencies, const std::function< Q(const int &, const int &)> & val) -> Q inline
Interpolates cubically in 1D (on linear, auxiliary frequency grid) ATTENTION!: all
Template Parameters
Q double or comp
Parameters
x
frequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
val any function that takes one integer and returns a value of type Q
Returns
Definition at line 330 of file InterpolatorLinOrSloppy.hpp.
{
    double t;
    int index = xfrequencies.get_grid_index(t, x);
    double x0 = xfrequencies.get_auxiliary_gridpoint(index - 1);
    double x1 = xfrequencies.get_auxiliary_gridpoint(index    );
    double x2 = xfrequencies.get_auxiliary_gridpoint(index + 1);
    double x3 = xfrequencies.get_auxiliary_gridpoint(index + 2);
    auto f0 = interpolate_sloppycubic1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index - 1, i);});
    auto f1 = interpolate_sloppycubic1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index    , i);});
    auto f2 = interpolate_sloppycubic1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index + 1, i);});
    auto f3 = interpolate_sloppycubic1D<Q>(y, yfrequencies, [&index, &val](int i) -> Q {return val(index + 2, i);});
    Q result = ((t - x1)*(t - x2)*(t - x3)/((x0-x1)*(x0-x2)*(x0-x3)) * f0
                +(t - x0)*(t - x2)*(t - x3)/((x1-x0)*(x1-x2)*(x1-x3)) * f1
                +(t - x0)*(t - x1)*(t - x3)/((x2-x0)*(x2-x1)*(x2-x3)) * f2
                +(t - x0)*(t - x1)*(t - x2)/((x3-x0)*(x3-x1)*(x3-x2)) * f3);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
interpolate_sloppycubic3D()
template<typename Q , typename Grid > auto interpolate_sloppycubic3D (const double & x, const double & y, const double & z, const Grid & xfrequencies, const Grid & yfrequencies, const Grid & zfrequencies, const std::function< Q(const int &, const int &, const int &)> & val) -> Q inline
Interpolates cubically in 1D (on linear, auxiliary frequency grid) ATTENTION!: all
Template Parameters
Q double or comp
Parameters
x
frequencies frequencyGrid with the functions get_grid_index and with x-values in vector all_frequencies
val any function that takes one integer and returns a value of type Q
Returns
Definition at line 366 of file InterpolatorLinOrSloppy.hpp.
{
    double t;
    int index = xfrequencies.get_grid_index(t, x);
    double x0 = xfrequencies.get_auxiliary_gridpoint(index - 1);
    double x1 = xfrequencies.get_auxiliary_gridpoint(index    );
    double x2 = xfrequencies.get_auxiliary_gridpoint(index + 1);
    double x3 = xfrequencies.get_auxiliary_gridpoint(index + 2);
    auto f0 = interpolate_sloppycubic2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index - 1, i, j);});
    auto f1 = interpolate_sloppycubic2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index    , i, j);});
    auto f2 = interpolate_sloppycubic2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index + 1, i, j);});
    auto f3 = interpolate_sloppycubic2D<Q>(y, z, yfrequencies, zfrequencies, [&index, &val](int i, int j) -> Q {return val(index + 2, i, j);});
    Q result = ((t - x1)*(t - x2)*(t - x3)/((x0-x1)*(x0-x2)*(x0-x3)) * f0
                +(t - x0)*(t - x2)*(t - x3)/((x1-x0)*(x1-x2)*(x1-x3)) * f1
                +(t - x0)*(t - x1)*(t - x3)/((x2-x0)*(x2-x1)*(x2-x3)) * f2
                +(t - x0)*(t - x1)*(t - x2)/((x3-x0)*(x3-x1)*(x3-x2)) * f3);
    assert(my_isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().