#!/bin/bash
#SBATCH --output=/gpfs/scratch/uh3o1/ri26yad/Ex_DATA_lrz_scratch/QPC_finite_tmp_lrz_no_lr_extrapolation_with_additional_freq_in_px/AA_LOG/mpi-out.%j
#SBATCH --error=/gpfs/scratch/uh3o1/ri26yad/Ex_DATA_lrz_scratch/QPC_finite_tmp_lrz_no_lr_extrapolation_with_additional_freq_in_px/AA_LOG/mpi-err.%j
#SBATCH -J MPI_job
#SBATCH --get-user-env
#SBATCH --clusters=mpp2
#SBATCH --nodes=4
#SBATCH --ntasks=4
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=28
#SBATCH --time=05:59:59
export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
source /etc/profile.d/modules.sh
cd /gpfs/scratch/uh3o1/ri26yad/Ex_DATA_lrz_scratch/QPC_finite_tmp_lrz_no_lr_extrapolation_with_additional_freq_in_px/
mpiexec /home/hpc/uh3o1/ri26yad/bin/ex_dsfRG_production -L 5 -Lu 3 -N 30 -Nff 1500 -NfbP 1500 -NfbX 1500 -num_freq_pre 30000 -NL_full 0 -Vg 0.25 -h 0.0 -mu -1.40 -T 0.0025 -U0 0.5 -U1 0.3 -Xi 5.0 -accp 0.0001 -accx 0.0001 -accs 0.0001 -tol 0.000001 -Lambda_ini 100000.0 -Lambda_fin 0.000000002
