SIAM-Keldysh-mfRG: oneBubble< Q > Class Template Reference
oneBubble< Q > Class Template Reference
#include <right_hand_sides.hpp>
Public Member Functions
oneBubble (const Propagator< Q > &g_in)
auto value (int iK, double v1, double v2, int i_in) const -> Q
template<char ch_bubble>
Q value_Matsubara (const double w, const double vpp, int i_in) const
auto value (int iK, double w, double vpp, int i_in, char channel) const -> Q
template<char ch_bubble>
auto convert_to_fermionic_frequencies_1 (double vpp, double w) const -> double
template<char ch_bubble>
auto convert_to_fermionic_frequencies_2 (double vpp, double w) const -> double
template<char ch_bubble>
auto value_vectorized (const double w, const double vpp, const int i_in) const
Public Attributes
const Propagator< Q > & g
bool diff = false
Detailed Description
template<typename Q>
class oneBubble< Q >
Definition at line 667 of file right_hand_sides.hpp.
Constructor & Destructor Documentation
oneBubble()
template<typename Q > oneBubble< Q >::oneBubble (const Propagator< Q > & g_in) inline
Constructor:
Parameters
propagatorG : first propagator (always a standard one)
propagatorS : second propagator (standard or single-scale/differentiated, depending on "diff_in")
diff_in : whether to compute standard (false) or differentiated (true) bubble
Definition at line 678 of file right_hand_sides.hpp.
: g(g_in) {};
Member Function Documentation
convert_to_fermionic_frequencies_1()
template<typename Q > template<char ch_bubble> auto oneBubble< Q >::convert_to_fermionic_frequencies_1 (double vpp, double w) const -> double inline
Definition at line 711 of file right_hand_sides.hpp.
{
        if constexpr(KELDYSH || ZERO_T) {
            if constexpr(ch_bubble == 'p') return vpp + w * 0.5;
            else return vpp - w * 0.5;
        }
        else { // Matsubata zeroT
            if constexpr(ch_bubble == 'p') return vpp + ceil2bfreq(w * 0.5);
            else return vpp - floor2bfreq(w * 0.5);
        }
    }
References ceil2bfreq(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), floor2bfreq(), KELDYSH, and ZERO_T.
convert_to_fermionic_frequencies_2()
template<typename Q > template<char ch_bubble> auto oneBubble< Q >::convert_to_fermionic_frequencies_2 (double vpp, double w) const -> double inline
Definition at line 722 of file right_hand_sides.hpp.
{
        if constexpr(KELDYSH || ZERO_T) {
            if constexpr(ch_bubble == 'p') return w * 0.5 - vpp;
            else return vpp + w * 0.5;
        }
        else { // Matsubata zeroT
            if constexpr(ch_bubble == 'p') return floor2bfreq(w * 0.5) - vpp;
            else return vpp + ceil2bfreq(w * 0.5);
        }
    }
References ceil2bfreq(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), floor2bfreq(), KELDYSH, and ZERO_T.
value() [1/2]
template<typename Q > auto oneBubble< Q >::value (int iK, double v1, double v2, int i_in) const -> Q inline
Call operator:
Parameters
iK : Keldysh index of combined bubble object (0 <= iK <= 15)
v1 : frequency of first propagator
v2 : frequency of second propagator
i_in : internal structure index
Returns
comp : value of the bubble evaluated at (iK, v1, v2)
Definition at line 688 of file right_hand_sides.hpp.
{
        return 1.;
    }
value() [2/2]
template<typename Q > auto oneBubble< Q >::value (int iK, double w, double vpp, int i_in, char channel) const -> Q inline
Wrapper for value function above, providing the natural arguments for evaluation of the bubble in each channel:
Parameters
iK : Keldysh index of combined bubble object (0 <= iK <= 15)
w : bubble transfer frequency of the corresponding channel
vpp : bubble integration frequency of the corresponding channel
i_in : internal structure index
channel : channel to which the bubble belongs
Returns
Q : value of the bubble evaluated at the arguments described above (usually comp)
Definition at line 706 of file right_hand_sides.hpp.
{
        return 1.;
    }
value_Matsubara()
template<typename Q > template<char ch_bubble> Q oneBubble< Q >::value_Matsubara (const double w, const double vpp, int i_in) const inline
Definition at line 693 of file right_hand_sides.hpp.
{
        return 1.;
    }
value_vectorized()
template<typename Q > template<char ch_bubble> auto oneBubble< Q >::value_vectorized (const double w, const double vpp, const int i_in) const inline
Definition at line 735 of file right_hand_sides.hpp.
{
        return 1.;
    }
Member Data Documentation
diff
template<typename Q > bool oneBubble< Q >::diff = false
Definition at line 671 of file right_hand_sides.hpp.
g
template<typename Q > const Propagator<Q>& oneBubble< Q >::g
Definition at line 670 of file right_hand_sides.hpp.
The documentation for this class was generated from the following file:
right_hand_sides.hpp