SIAM-Keldysh-mfRG: data_structures.hpp File Reference
data_structures.hpp File Reference
#include <complex>
#include <cmath>
#include <vector>
#include <initializer_list>
#include <functional>
#include <cassert>
#include <numeric>
#include "parameters/master_parameters.hpp"
#include "Eigen/Dense"
Classes
class vec< T >
DECLARATIONS ///.
struct VertexInput
struct IndicesSymmetryTransformations
struct fRG_config
Namespaces
namespace my_defs
namespace my_defs::SE
namespace my_defs::K1
namespace my_defs::K2
namespace my_defs::K2b
namespace my_defs::K3
Typedefs
typedef std::complex< double > comp
using state_datatype = comp
typedef vec< double > rvec
typedef vec< comp > cvec
using my_index_t = std::size_t
Keldysh index parameters ///.
using my_defs::SE::index_type = std::array<my_index_t, rank>
using my_defs::SE::dimensions_type = std::array<my_index_t, rank>
using my_defs::SE::frequencies_type = std::array<freqType, 1>
using my_defs::K1::index_type = std::array<my_index_t, rank>
using my_defs::K1::dimensions_type = std::array<my_index_t, rank>
using my_defs::K1::frequencies_type = std::array<freqType, 1>
using my_defs::K2::index_type = std::array<my_index_t, rank>
using my_defs::K2::dimensions_type = std::array<my_index_t, rank>
using my_defs::K2::frequencies_type = std::array<freqType, 2>
using my_defs::K2b::index_type = std::array<my_index_t, rank>
using my_defs::K2b::dimensions_type = std::array<my_index_t, rank>
using my_defs::K2b::frequencies_type = std::array<freqType, 2>
using my_defs::K3::index_type = std::array<my_index_t, rank>
using my_defs::K3::dimensions_type = std::array<my_index_t, rank>
using my_defs::K3::frequencies_type = std::array<freqType, 3>
Enumerations
enum K_class {
selfenergy = -1 , k1 =0 , k2 =1 , k2b =2 ,
k3 =3 , k3_sbe =4
}
enum vertexType { symmetric_full , symmetric_r_irred , non_symmetric_diffleft , non_symmetric_diffright }
enum my_defs::SE::names { my_defs::SE::keldysh , my_defs::SE::nu , my_defs::SE::internal }
enum my_defs::K1::names { my_defs::K1::spin , my_defs::K1::omega , my_defs::K1::keldysh , my_defs::K1::internal }
enum my_defs::K2::names {
my_defs::K2::spin , my_defs::K2::omega , my_defs::K2::nu , my_defs::K2::keldysh ,
my_defs::K2::internal
}
enum my_defs::K2b::names {
my_defs::K2b::spin , my_defs::K2b::omega , my_defs::K2b::nup , my_defs::K2b::keldysh ,
my_defs::K2b::internal
}
enum my_defs::K3::names {
my_defs::K3::spin , my_defs::K3::omega , my_defs::K3::nu , my_defs::K3::nup ,
my_defs::K3::keldysh , my_defs::K3::internal
}
Functions
constexpr comp glb_i (0., 1.)
template<typename T >
double myabs (const T &x)
template<typename T >
T myzero ()
template<typename T >
constexpr T get_Id_Matrix_4x4 ()
template<typename T >
T myIdentity ()
template<typename T >
constexpr int myRowsAtCompileTime ()
template<typename T >
constexpr int myColsAtCompileTime ()
template<typename Q >
auto myreal (const Q x) -> double
template<>
auto myreal< double > (const double x) -> double
template<typename Q >
auto myimag (const Q x) -> double
template<>
auto myimag< double > (const double x) -> double
template<typename Q >
auto myconj (const Q x) -> Q
template<>
auto myconj< double > (const double x) -> double
auto my_isfinite (comp z) -> bool
template<typename T , typename std::enable_if< std::is_floating_point< T >::value >::type * = nullptr>
auto my_isfinite (T z) -> bool
template<typename Q , typename L , typename R >
auto scalar_map (const Q &op, const vec< L > &lhs, const R &rhs)
template<typename binaryOp , typename L , typename R >
auto elementwise (const binaryOp &op, const vec< L > &lhs, const vec< R > &rhs)
template<typename T , typename O >
auto transform_vec (const std::function< O(T)> &op, const vec< T > &vect)
template<typename T , typename R >
void convert_vec_to_type (const vec< T > &vect, R &res)
template<typename L , typename R >
auto operator+ (const vec< L > &lhs, const vec< R > &rhs)
template<typename L , typename R >
auto operator+ (const vec< L > &lhs, const R &rhs)
template<typename L , typename R >
auto operator+ (const L &lhs, const vec< R > &rhs)
template<typename L , typename R >
auto operator- (const vec< L > &lhs, const vec< R > &rhs)
template<typename L , typename R >
auto operator- (const vec< L > &lhs, const R &rhs)
template<typename L , typename R >
auto operator- (const L &lhs, const vec< R > &rhs)
template<typename L , typename R >
auto operator* (const vec< L > lhs, const vec< R > &rhs)
template<typename L , typename R >
auto operator* (const vec< L > lhs, const R &rhs)
template<typename L , typename R >
auto operator* (const L &lhs, const vec< R > rhs)
template<typename L , typename R >
auto operator/ (const vec< L > lhs, const vec< R > &rhs)
template<typename T >
vec< T > operator+= (vec< T > &lhs, const double &rhs)
NON-MEMBER FUNCTIONS ///.
template<typename T >
vec< T > operator+ (vec< T > lhs, const double &rhs)
template<typename T >
vec< T > operator+ (const double &rhs, vec< T > lhs)
template<typename T >
vec< T > operator-= (vec< T > &lhs, const double &rhs)
template<typename T >
vec< T > operator- (vec< T > lhs, const double &rhs)
template<typename T >
vec< comp > operator* (vec< T > lhs, const comp &rhs)
std::ostream & operator<< (std::ostream &out, K_class k)
std::ostream & operator<< (std::ostream &out, vertexType symmtype)
Variables
constexpr size_t rank_SE = 3
constexpr size_t rank_K1 = 4
constexpr size_t rank_K2 = 5
constexpr size_t rank_K3 = 6
constexpr my_index_t my_defs::SE::rank = 3
constexpr my_index_t my_defs::K1::rank = 4
constexpr my_index_t my_defs::K2::rank = 5
constexpr my_index_t my_defs::K2b::rank = 5
constexpr my_index_t my_defs::K3::rank = 6
Typedef Documentation
comp
typedef std::complex<double> comp
Definition at line 25 of file data_structures.hpp.
cvec
typedef vec<comp> cvec
Definition at line 239 of file data_structures.hpp.
my_index_t
using my_index_t = std::size_t
Keldysh index parameters ///.
Definition at line 479 of file data_structures.hpp.
rvec
typedef vec<double> rvec
Definition at line 238 of file data_structures.hpp.
state_datatype
using state_datatype = comp
Definition at line 91 of file data_structures.hpp.
Enumeration Type Documentation
K_class
enum K_class
Enumerator
selfenergy
k1
k2
k2b
k3
k3_sbe
Definition at line 480 of file data_structures.hpp.
{selfenergy = -1, k1=0, k2=1, k2b=2, k3=3, k3_sbe=4};
vertexType
enum vertexType
Enumerator
symmetric_full
symmetric_r_irred
non_symmetric_diffleft
non_symmetric_diffright
Definition at line 482 of file data_structures.hpp.
{symmetric_full, symmetric_r_irred, non_symmetric_diffleft, non_symmetric_diffright};
Function Documentation
convert_vec_to_type()
template<typename T , typename R > void convert_vec_to_type (const vec< T > & vect, R & res)
Definition at line 227 of file data_structures.hpp.
{
    for (size_t i = 0; i < vect.size(); i++)
    {
        res[i] = vect[i];
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
elementwise()
template<typename binaryOp , typename L , typename R > auto elementwise (const binaryOp & op, const vec< L > & lhs, const vec< R > & rhs)
Definition at line 201 of file data_structures.hpp.
{
    if (lhs.size() != rhs.size())
    {
        throw std::length_error("Cannot perform pairwise operations on vectors of different size.");
    }
    vec<decltype(op(std::declval<L>(), std::declval<R>()))> res(lhs.size());
    for (size_t i = 0; i < res.size(); i++)
    {
        res[i] = op(lhs[i], rhs[i]);
    }
    assert(res.size() == lhs.size());
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by operator*(), operator+(), operator-(), and operator/().
get_Id_Matrix_4x4()
template<typename T > constexpr T get_Id_Matrix_4x4 () constexpr
Definition at line 51 of file data_structures.hpp.
{
    T res;
    res << 1, 0, 0, 0,
           0, 1, 0, 0,
           0, 0, 1, 0,
           0, 0, 0, 1;
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
glb_i()
constexpr comp glb_i (0. , 1.) constexpr
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::bubble_value_prefactor(), check_FDTs_K1(), check_FDTs_selfenergy(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), correctionFunctionBubble_REG3_Matsubara_PHS_nondiff(), correctionFunctionBubbleAT_REG2_Keldysh(), correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(), correctionFunctionBubbleP_REG2_Keldysh(), correctionFunctionBubbleP_REG2_Matsubara_NoPHS(), correctionFunctionSelfEnergy_Keldysh(), correctionFunctionSelfEnergy_Matsubara_NoPHS(), Propagator< Q >::diff_Sigma_K_REG5(), Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::G0R_inv_SIAM(), Propagator< Q >::GK(), Propagator< Q >::GM_REG2(), Propagator< Q >::GR_REG2(), Propagator< Q >::GR_REG3(), integrator_gsl(), integrator_gsl(), integrator_gsl_qag_tails(), integrator_gsl_qag_v2(), integrator_gsl_qagp_v2(), LoopCalculator< Q, vertType, all_spins, version >::Keldysh_prefactor(), Hartree_Solver::operator()(), IntegrandBubble< Q >::operator()(), Propagator< Q >::SK(), Propagator< Q >::SM_REG2(), Propagator< Q >::SR_REG2(), Propagator< Q >::SR_REG3(), and test_read_write_data_hdf().
my_isfinite() [1/2]
auto my_isfinite (comp z) -> bool
Definition at line 3 of file data_structures.c++.
{
    return std::isfinite(real(z)) and std::isfinite(imag(z));
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by asymp_corrections_bubble(), correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(), correctionFunctionBubbleAT_REG2_Matsubara_PHS(), correctionFunctionBubbleAT_REG3_Matsubara_PHS(), correctionFunctionBubbleAT_REG4_Matsubara_PHS(), Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::GM_REG2(), Propagator< Q >::GR_REG3(), FrequencyGrid< eliasGrid >::initialize_grid(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl(), interpolate_lin1D(), interpolate_lin2D(), interpolate_lin3D(), interpolate_lin_on_aux1D(), interpolate_lin_on_aux2D(), interpolate_lin_on_aux3D(), interpolate_nearest1D(), interpolate_nearest2D(), interpolate_nearest3D(), interpolate_sloppycubic1D(), interpolate_sloppycubic2D(), interpolate_sloppycubic3D(), fullvert< Q >::left_diff_bare(), fullvert< Q >::left_diff_bare(), fullvert< Q >::left_diff_bare_symmetry_expanded(), fullvert< Q >::left_same_bare(), fullvert< Q >::left_same_bare(), rvert< Q >::read_symmetryreduced_rvert(), fullvert< Q >::right_diff_bare(), fullvert< Q >::right_diff_bare(), fullvert< Q >::right_diff_bare_symmetry_expanded(), fullvert< Q >::right_same_bare(), fullvert< Q >::right_same_bare(), Propagator< Q >::SM_REG4(), Bubble< Q >::value(), Bubble< Q >::value(), and Bubble< Q >::value_Matsubara().
my_isfinite() [2/2]
template<typename T , typename std::enable_if< std::is_floating_point< T >::value >::type * = nullptr> auto my_isfinite (T z) -> bool
Definition at line 109 of file data_structures.hpp.
{
    return std::isfinite(z);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
myabs()
template<typename T > double myabs (const T & x)
Definition at line 29 of file data_structures.hpp.
{
    if constexpr(std::is_same_v<T, comp> or std::is_same_v<T, double>) {
        return std::abs(x);
    }
    else if constexpr(std::is_same_v<T, State<comp,false>> or std::is_same_v<T, State<double,false>>) {
        return x.abs();
    }
    else {
        return x.template lpNorm<Eigen::Infinity>();
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Adapt< Integrand, Q >::integrate(), and Adapt< Integrand, Q >::integrate().
myColsAtCompileTime()
template<typename T > constexpr int myColsAtCompileTime () constexpr
Definition at line 79 of file data_structures.hpp.
{
    if constexpr(std::is_same_v<T,double> || std::is_same_v<T,comp>) {
        return 1;
    }
    else {
        return T::ColsAtCompileTime;
    }
}
myconj()
template<typename Q > auto myconj (const Q x) -> Q inline
Definition at line 102 of file data_structures.hpp.
{return conj(x);};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by SelfEnergy< Q >::check_symmetries(), compute_components_through_FDTs(), IntegrandSE< Q, vertType, all_spins, return_type, version >::evaluate_propagator(), Propagator< Q >::Katanin_K(), rvert< Q >::read_symmetryreduced_rvert(), and Bubble< Q >::value().
myconj< double >()
template<> auto myconj< double > (const double x) -> double inline
Definition at line 104 of file data_structures.hpp.
{return x;};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
myIdentity()
template<typename T > T myIdentity ()
Definition at line 60 of file data_structures.hpp.
{
    if constexpr(std::is_same_v<T, comp> or std::is_same_v<T, double> or std::is_same_v<T, int>) {
        return (T)1;
    }
    else {
        const T id = get_Id_Matrix_4x4<T>();
        return id;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
myimag()
template<typename Q > auto myimag (const Q x) -> double inline
Definition at line 98 of file data_structures.hpp.
{return x.imag();};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by check_FDTs_K1(), check_FDTs_selfenergy(), check_SE_causality(), Propagator< Q >::diff_Sigma_K_REG5(), f_imag(), Propagator< Q >::GK(), Integrand_sum_rule_spectrum::operator()(), Integrand_Ward_id_integrated< gridType >::operator()(), and Propagator< Q >::SK().
myimag< double >()
template<> auto myimag< double > (const double x) -> double inline
Definition at line 100 of file data_structures.hpp.
{return x;};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
myreal()
template<typename Q > auto myreal (const Q x) -> double inline
Definition at line 94 of file data_structures.hpp.
{return x.real();};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by compute_components_through_FDTs(), f_real(), and State< Q, differentiated >::update_grid().
myreal< double >()
template<> auto myreal< double > (const double x) -> double inline
Definition at line 96 of file data_structures.hpp.
{return x;};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
myRowsAtCompileTime()
template<typename T > constexpr int myRowsAtCompileTime () constexpr
Definition at line 70 of file data_structures.hpp.
{
    if constexpr(std::is_same_v<T,double> || std::is_same_v<T,comp>) {
        return 1;
    }
    else {
        return T::RowsAtCompileTime;
    }
}
myzero()
template<typename T > T myzero ()
Definition at line 41 of file data_structures.hpp.
{
    if constexpr(std::is_same_v<T, comp> or std::is_same_v<T, double> or std::is_same_v<T, int>) {
        return (T)0.;
    }
    else {
        return T::Zero();
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*() [1/4]
template<typename L , typename R > auto operator* (const L & lhs, const vec< R > rhs)
Definition at line 331 of file data_structures.hpp.
                                                {      // scalar multiplication with a constant from the left
    return scalar_map([](const R &r, const L &l) { return l * r; }, rhs, lhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator*() [2/4]
template<typename L , typename R > auto operator* (const vec< L > lhs, const R & rhs)
Definition at line 327 of file data_structures.hpp.
                                                {      // scalar multiplication with a constant from the right
    return scalar_map([](const L &l, const R &r) { return l * r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator*() [3/4]
template<typename L , typename R > auto operator* (const vec< L > lhs, const vec< R > & rhs)
Definition at line 323 of file data_structures.hpp.
                                                     { // element-wise multiplication of two vectors
    return elementwise([](const L &l, const R &r) { return l * r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator*() [4/4]
template<typename T > vec< comp > operator* (vec< T > lhs, const comp & rhs)
Definition at line 459 of file data_structures.hpp.
{
    size_t size = lhs.size();
    vec<comp> result(size);
#pragma omp parallel for
    for (int i=0; i<lhs.size(); ++i) {
        result[i] *= lhs[i] * rhs;
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+() [1/5]
template<typename T > vec< T > operator+ (const double & rhs, vec< T > lhs)
Definition at line 419 of file data_structures.hpp.
{
    lhs += rhs; return lhs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+() [2/5]
template<typename L , typename R > auto operator+ (const L & lhs, const vec< R > & rhs)
Definition at line 307 of file data_structures.hpp.
                                                 {      // addition of a constant from the left (commutative)
    return scalar_map([](const R &r, const L &l) { return l + r; }, rhs, lhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator+() [3/5]
template<typename L , typename R > auto operator+ (const vec< L > & lhs, const R & rhs)
Definition at line 303 of file data_structures.hpp.
                                                 {      // addition of a constant
    return scalar_map([](const L &l, const R &r) { return l + r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator+() [4/5]
template<typename L , typename R > auto operator+ (const vec< L > & lhs, const vec< R > & rhs)
Definition at line 299 of file data_structures.hpp.
                                                      { // element-wise addition of two vectors
    return elementwise([](const L &l, const R &r) { return l + r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator+() [5/5]
template<typename T > vec< T > operator+ (vec< T > lhs, const double & rhs)
Definition at line 415 of file data_structures.hpp.
{
    lhs += rhs; return lhs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+=()
template<typename T > vec< T > operator+= (vec< T > & lhs, const double & rhs)
NON-MEMBER FUNCTIONS ///.
Definition at line 407 of file data_structures.hpp.
{
#pragma omp parallel for
    for (unsigned int i=0; i<lhs.size(); ++i) {
        lhs[i] += rhs;
    }
    return lhs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-() [1/4]
template<typename L , typename R > auto operator- (const L & lhs, const vec< R > & rhs)
Definition at line 319 of file data_structures.hpp.
                                                 {      // subtraction of a constant from the left
    return scalar_map([](const R &r, const L &l) { return l - r; }, rhs, lhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator-() [2/4]
template<typename L , typename R > auto operator- (const vec< L > & lhs, const R & rhs)
Definition at line 315 of file data_structures.hpp.
                                                 {      // subtraction of a constant
    return scalar_map([](const L &l, const R &r) { return l - r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator-() [3/4]
template<typename L , typename R > auto operator- (const vec< L > & lhs, const vec< R > & rhs)
Definition at line 311 of file data_structures.hpp.
                                                      { // element-wise subtraction of two vectors
    return elementwise([](const L &l, const R &r) { return l - r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator-() [4/4]
template<typename T > vec< T > operator- (vec< T > lhs, const double & rhs)
Definition at line 433 of file data_structures.hpp.
{
    lhs -= rhs; return lhs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-=()
template<typename T > vec< T > operator-= (vec< T > & lhs, const double & rhs)
Definition at line 425 of file data_structures.hpp.
{
//#pragma omp parallel for
    for (size_t i=0; i<lhs.size(); ++i) {
        lhs[i] -= rhs;
    }
    return lhs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/()
template<typename L , typename R > auto operator/ (const vec< L > lhs, const vec< R > & rhs)
Definition at line 335 of file data_structures.hpp.
                                                     { // element-wise division of two vectors
    return elementwise([](const L &l, const R &r) { return l / r; }, lhs, rhs);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & out, K_class k)
Definition at line 8 of file data_structures.c++.
{
    if (k == k1 or k == k2) {out << "K" << static_cast<int>(k+1);}
    else if(k == k3) {out << "K" << static_cast<int>(k);}
    else if(k == k2b) {out << "K" << static_cast<int>(k) << "'";}
    else  {out << "selfenergy";}
    return out;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2, k2b, and k3.
operator<<() [2/2]
std::ostream & operator<< (std::ostream & out, vertexType symmtype)
Definition at line 16 of file data_structures.c++.
{
    if (symmtype == symmetric_full) {out << "symmetric_full";}
    else if (symmtype == symmetric_r_irred) {out << "symmetric_r_irred";}
    else if (symmtype == non_symmetric_diffleft) {out << "non_symmetric_diffleft";}
    else if (symmtype == non_symmetric_diffright) {out << "non_symmetric_diffright";}
    else {assert(false);}
    return out;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, symmetric_full, and symmetric_r_irred.
scalar_map()
template<typename Q , typename L , typename R > auto scalar_map (const Q & op, const vec< L > & lhs, const R & rhs)
Definition at line 189 of file data_structures.hpp.
{
    vec<decltype(op(std::declval<L>(), std::declval<R>()))> res(lhs.size());
    for (size_t i = 0; i < lhs.size(); i++)
    {
        res[i] = op(lhs[i], rhs);
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by operator*(), operator*(), operator+(), operator+(), operator-(), and operator-().
transform_vec()
template<typename T , typename O > auto transform_vec (const std::function< O(T)> & op, const vec< T > & vect)
Definition at line 216 of file data_structures.hpp.
{
    vec<O> res(vect.size());
    for (size_t i = 0; i < vect.size(); i++)
    {
        res[i] = op(vect[i]);
    }
    assert(res.size() == vect.size());
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Variable Documentation
rank_K1
constexpr size_t rank_K1 = 4 constexpr
Definition at line 486 of file data_structures.hpp.
rank_K2
constexpr size_t rank_K2 = 5 constexpr
Definition at line 487 of file data_structures.hpp.
rank_K3
constexpr size_t rank_K3 = 6 constexpr
Definition at line 488 of file data_structures.hpp.
rank_SE
constexpr size_t rank_SE = 3 constexpr
Definition at line 485 of file data_structures.hpp.