SIAM-Keldysh-mfRG: integrator_NR.hpp File Reference
integrator_NR.hpp File Reference
#include <limits>
#include "../data_structures.hpp"
Classes
struct Adapt< Integrand, Q >
class adaptive_integrator_detail::integrand_reparametrized_Upper< Integrand >
class adaptive_integrator_detail::integrand_reparametrized_Lower< Integrand >
class Adapt_semiInfinitUpper< Integrand >
class Adapt_semiInfinitLower< Integrand >
Namespaces
namespace adaptive_integrator_detail
Functions
template<typename Q >
auto Gauss_Lobatto_4 (double h, Q f1, Q f2, Q f3, Q f4) -> Q
template<typename Q >
auto Gauss_Kronrod_7 (double h, Q f1, Q f2, Q f3, Q f4, Q f5, Q f6, Q f7) -> Q
template<typename Q >
auto Gauss_Kronrod_13 (double h, Q f1, Q f2, Q f3, Q f4, Q f5, Q f6, Q f7, Q f8, Q f9, Q f10, Q f11, Q f12, Q f13) -> Q
Function Documentation
Gauss_Kronrod_13()
template<typename Q > auto Gauss_Kronrod_13 (double h, Q f1, Q f2, Q f3, Q f4, Q f5, Q f6, Q f7, Q f8, Q f9, Q f10, Q f11, Q f12, Q f13) -> Q inline
13-point Gauss-Kronrod rule
Definition at line 47 of file integrator_NR.hpp.
{
    return h * (0.0158271919734802 * (f1 + f13)
              + 0.0942738402188500 * (f2 + f12)
              + 0.155071987336585  * (f3 + f11)
              + 0.188821573960182  * (f4 + f10)
              + 0.199773405226859  * (f5 + f9)
              + 0.224926465333340  * (f6 + f8)
              + 0.242611071901408  *  f7);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Adapt< Integrand, Q >::integrate().
Gauss_Kronrod_7()
template<typename Q > auto Gauss_Kronrod_7 (double h, Q f1, Q f2, Q f3, Q f4, Q f5, Q f6, Q f7) -> Q inline
7-point Gauss-Kronrod rule
Definition at line 39 of file integrator_NR.hpp.
{
    return (h / 1470.0) * (77.0 * (f1 + f7)
                        + 432.0 * (f2 + f6)
                        + 625.0 * (f3 + f5)
                        + 672.0 *  f4);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Adapt< Integrand, Q >::integrate(), and Adapt< Integrand, Q >::integrate().
Gauss_Lobatto_4()
template<typename Q > auto Gauss_Lobatto_4 (double h, Q f1, Q f2, Q f3, Q f4) -> Q inline
4-point Gauss-Lobatto rule
Definition at line 34 of file integrator_NR.hpp.
{
    return (h / 6.0) * (f1 + f4 + 5.0 * (f2 + f3));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Adapt< Integrand, Q >::integrate(), and Adapt< Integrand, Q >::integrate().