SIAM-Keldysh-mfRG: flowgrid::exp_parametrization Class Reference
flowgrid::exp_parametrization Class Reference
#include <flow_grid.hpp>
Static Public Member Functions
static double lambda_from_t (double t)
static double t_from_lambda (double Lambda)
static double dlambda_dt (double t)
Detailed Description
Definition at line 35 of file flow_grid.hpp.
Member Function Documentation
dlambda_dt()
static double flowgrid::exp_parametrization::dlambda_dt (double t) inline static
Definition at line 52 of file flow_grid.hpp.
        {
            return std::exp(t*log(10)) * log(10);//lambda_from_t(t); // -1.;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and log().
lambda_from_t()
static double flowgrid::exp_parametrization::lambda_from_t (double t) inline static
Definition at line 38 of file flow_grid.hpp.
        {
            double value = std::exp(t*log(10));
            assert (isfinite(value));
            return value; // -t;//
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and log().
t_from_lambda()
static double flowgrid::exp_parametrization::t_from_lambda (double Lambda) inline static
Definition at line 45 of file flow_grid.hpp.
        {
            double value = std::log(Lambda)/log(10);
            assert (isfinite(value));
            return value; // -Lambda;//
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and log().
The documentation for this class was generated from the following file:
flow_grid.hpp