#!/bin/bash
#SBATCH --output=/naslx/projects/uh3o1/ri26yad/LOG/Ex_Compute_rpa/mpi-out.%j
#SBATCH --error=/naslx/projects/uh3o1/ri26yad/LOG/Ex_Compute_rpa/mpi-err.%j
#SBATCH -J MPI_job 
#SBATCH --get-user-env 
#SBATCH --clusters=mpp2
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --export=NONE  
#SBATCH --time=00:05:00

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
cd /naslx/projects/uh3o1/ri26yad/DATA/Unit_tests/Ex_Compute_rpa
srun /home/hpc/uh3o1/ri26yad/bin/Ex_Compute_rpa
