SIAM-Keldysh-mfRG: utils Namespace Reference
utils Namespace Reference
Functions
void print_time_stamp ()
double get_time ()
void get_time (double t0)
void get_cpu_hours (double t0)
void get_time (double t0, std::string prec)
void makedir (const std::string &dir_str)
void check_input (const fRG_config &config)
std::string generate_data_directory (std::string &job)
std::string generate_filename (const fRG_config &config)
void print_job_info (const fRG_config &config)
void hello_world ()
template<typename T >
void print (T s, bool endline)
template<typename T >
void print_add (T s, bool endline)
template<typename T , typename U >
void print (T t, U u, bool endline)
template<typename ... Args>
void print (Args ... args)
template<typename T , typename U >
void print_add (T t, U u, bool endline)
template<typename T , typename U , typename V >
void print (T t, U u, V v, bool endline)
template<typename T , typename U , typename V >
void print_add (T t, U u, V v, bool endline)
template<typename T >
void print (T s)
template<typename T , typename U >
void print (T t, U u)
template<typename T , typename U , typename V >
void print (T t, U u, V v)
template<typename T , typename... Args>
constexpr std::array< T, sizeof...(Args)> to_array (const Args &... args)
template<typename Head , typename ... Args>
bool is_all_finite (Head head, Args ... args)
Function Documentation
check_input()
void utils::check_input (const fRG_config & config)
Definition at line 115 of file util.c++.
{
        static_assert(!(VECTORIZED_INTEGRATION and !KELDYSH and ZERO_TEMP), "No vectorized integration for zero-T MF (for now).");
    #ifdef STATIC_FEEDBACK
        assert(MAX_DIAG_CLASS == 1);
    #endif
        if (MAX_DIAG_CLASS<2) assert(config.nloops < 2);
    #ifdef ROTATEK2
        assert (nBOS2 == nFER2);
    #endif
    #if GRID==2
        static_assert(INTERPOLATION!=linear, "Linear interpolation not possible for polar coordinates.");
    #endif
    #if not KELDYSH_FORMALISM
        static_assert(nFER % 2 == 0, "nFER must be an even number.");
    #endif
        if (BOSONIC_PARAM_FOR_K3) {
            assert(nBOS3 == nFER3); // Frequency grids must be equal in all three dimensions
        }
    #if not KELDYSH_FORMALISM and not ZERO_TEMP
        static_assert(nBOS %2 == 1, "Number of frequency points inconsistent for Matsubara T>0");
        static_assert(nBOS2%2 == 1, "Number of frequency points inconsistent for Matsubara T>0");
        static_assert(nBOS3%2 == 1, "Number of frequency points inconsistent for Matsubara T>0");
        static_assert(nFER %2 == 0, "Number of frequency points inconsistent for Matsubara T>0");
        static_assert(nFER2%2 == 0, "Number of frequency points inconsistent for Matsubara T>0");
        static_assert(nFER3%2 == 0, "Number of frequency points inconsistent for Matsubara T>0");
    #endif
    #if SBE_DECOMPOSITION
    static_assert(SWITCH_SUM_N_INTEGRAL, "SBE requires preprocessing of vertex data.");
    #endif
        #if ZERO_TEMP
            assert(config.T < 1e-10);
        #endif
        #if PARTICLE_HOLE_SYMM
            assert(std::abs(config.epsilon + config.U * 0.5) < 1e-10);
        #endif
        if (EQUILIBRIUM) {
            assert(std::abs(glb_V) < 1e-10);
        }
    }
References BOSONIC_PARAM_FOR_K3, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::epsilon, EQUILIBRIUM, glb_V, INTERPOLATION, KELDYSH, linear, MAX_DIAG_CLASS, nBOS, nBOS2, nBOS3, nFER, nFER2, nFER3, fRG_config::nloops, SWITCH_SUM_N_INTEGRAL, fRG_config::T, fRG_config::U, VECTORIZED_INTEGRATION, and ZERO_TEMP.
Referenced by main().
generate_data_directory()
std::string utils::generate_data_directory (std::string & job)
Definition at line 161 of file util.c++.
{
    #if KELDYSH_FORMALISM
    #if DEBUG_SYMMETRIES
        std::string data_directory = "../Data_KF_debug";
    #else
        std::string data_directory = "../Data_KF" + job + "_REG=" + std::to_string(REG);
    #endif
    #else
        #if DEBUG_SYMMETRIES
        std::string data_directory = "../Data_MF_debug";
    #else
        std::string data_directory = "../Data_MF"+ job;
    #endif
    #endif
    #if SBE_DECOMPOSITION
        data_directory += "_SBE";
    #endif
        data_directory += "/";
        makedir(data_directory);
        return data_directory;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), makedir(), and REG.
Referenced by main().
generate_filename()
std::string utils::generate_filename (const fRG_config & config)
Definition at line 188 of file util.c++.
{
        std::string klass = "K" + std::to_string(MAX_DIAG_CLASS) + "_";
        std::string loops = std::to_string(config.nloops) + "LF_";
        std::string n1 = "n1=" + std::to_string(nBOS) + "_";
        std::string n2 = "n2=" + std::to_string(nBOS2) + "_";
        std::string n3 = "n3=" + std::to_string(nBOS3) + "_";
        std::string gamma = "Gamma=" + std::to_string(config.Gamma) + "_";
        std::string gate = "eVg=" + std::to_string(config.epsilon + config.U*0.5) + "_";
        std::string voltage = "V=" + std::to_string(glb_V) + "_";
        std::string temp = "T=" + std::to_string(config.T) + "_";
        std::string lambda = "L_ini=" + std::to_string((int)Lambda_ini)+"_";
        std::string ode = "nODE=" + std::to_string(config.nODE_);
        std::string withSEcorrections = SELF_ENERGY_FLOW_CORRECTIONS == 0 ? "" : "_wSEcorr" + std::to_string(SELF_ENERGY_FLOW_CORRECTIONS);
        std::string extension = ".h5";
        std::string filename = klass + loops + n1;
        if (MAX_DIAG_CLASS >= 2) filename += n2;
    #if defined(STATIC_FEEDBACK)
        filename += "static_";
    #endif
        if (MAX_DIAG_CLASS >= 3) filename += n3;
        filename += gamma;
        if (not PARTICLE_HOLE_SYMMETRY) filename += gate;
        if(glb_V != 0.) filename += voltage;
        filename += temp;
        filename += lambda + ode + extension;
        return filename;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::epsilon, fRG_config::Gamma, glb_V, Lambda_ini, MAX_DIAG_CLASS, nBOS, nBOS2, nBOS3, fRG_config::nloops, fRG_config::nODE_, PARTICLE_HOLE_SYMMETRY, SELF_ENERGY_FLOW_CORRECTIONS, fRG_config::T, and fRG_config::U.
Referenced by main().
get_cpu_hours()
void utils::get_cpu_hours (double t0)
Definition at line 48 of file util.c++.
{
        struct timeval tp;
        gettimeofday(&tp, NULL);
        const long int ms = tp.tv_sec * 1000 + tp.tv_usec / 1000;
        const double t = ms / 1000.;
        const int nodes = mpi_world_size();
        const int threads = omp_get_num_threads();
        if (mpi_world_rank() == 0) {
            std::cout << "CPU hours elapsed: ";
            printf("%.3f", (t - t0)/3600.*nodes*threads);
            std::cout << "hours" << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), mpi_world_rank(), and mpi_world_size().
Referenced by main(), and run_parquet().
get_time() [1/3]
double utils::get_time ()
Definition at line 21 of file util.c++.
                      {
        struct timeval tp;
        gettimeofday(&tp, NULL);
        long int ms = tp.tv_sec * 1000 + tp.tv_usec / 1000;
        double t = ms/1000.;
        return t;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by main(), parquet_solver(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::perform_computation(), rhs_n_loop_flow(), old_ode_solvers::RK4_step(), run_parquet(), and GeneralVertex< Q, symmtype, differentiated >::symmetry_expand().
get_time() [2/3]
void utils::get_time (double t0)
Definition at line 29 of file util.c++.
{
        struct timeval tp;
        gettimeofday(&tp, NULL);
        long int ms = tp.tv_sec * 1000 + tp.tv_usec / 1000;
        double t = ms / 1000.;
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                std::cout << "time elapsed: ";
                printf("%.3f", t - t0);
                std::cout << "s" << std::endl;
            }
        }
        else {
            std::cout << "time elapsed: ";
            printf("%.3f", t-t0);
            std::cout << "s" << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, and mpi_world_rank().
get_time() [3/3]
void utils::get_time (double t0, std::string prec)
Definition at line 63 of file util.c++.
{
        struct timeval tp;
        gettimeofday(&tp, NULL);
        if (prec == "us") {
            long int us = tp.tv_sec * 1000000 + tp.tv_usec;
            double t = us / 1000000.;
            if (MPI_FLAG) {
                if (mpi_world_rank() == 0) {
                    std::cout << "time elapsed: ";
                    printf("%.6f", t - t0);
                    std::cout << "s" << std::endl;
                }
            }
            else {
                std::cout << "time elapsed: ";
                printf("%.6f", t - t0);
                std::cout << "s" << std::endl;
            }
        }
        else {
            long int ms = tp.tv_sec * 1000 + tp.tv_usec / 1000;
            double t = ms / 1000.;
            if (MPI_FLAG) {
                if (mpi_world_rank() == 0) {
                    std::cout << "time elapsed: ";
                    printf("%.3f", t - t0);
                    std::cout << "s" << std::endl;
                }
            }
            else {
                std::cout << "time elapsed: ";
                printf("%.3f", t - t0);
                std::cout << "s" << std::endl;
            }
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, and mpi_world_rank().
hello_world()
void utils::hello_world ()
Definition at line 247 of file util.c++.
                       {
        print("Hello world \n");
    #ifdef __linux__
        print("on linux.\n");
    #elif __APPLE__
        print("on apple.\n");
        print("on apple.\n");
    #endif
    }
References print().
Referenced by main().
is_all_finite()
template<typename Head , typename ... Args> bool utils::is_all_finite (Head head, Args ... args)
Definition at line 184 of file util.hpp.
{
        if constexpr (sizeof... (Args) == 0) {
            return std::isfinite(head);
        }
        else {
            return std::isfinite(head) and is_all_finite(args...);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and is_all_finite().
Referenced by is_all_finite().
makedir()
void utils::makedir (const std::string & dir_str)
Definition at line 100 of file util.c++.
{
    #ifdef USE_MPI
        if (mpi_world_rank() == 0 or not MPI_FLAG)  // only the process with ID 0 writes into file to avoid collisions
    #endif
        {
            const char *dir = dir_str.c_str();
            // Creating Data directory
            if (mkdir(dir, 0777) == -1)
                std::cerr << "Error when creating directory " << dir << " :  " << strerror(errno) << std::endl;
            else
                std::cout << "Directory " << dir << " created \n";
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, and mpi_world_rank().
Referenced by generate_data_directory(), and rhs_n_loop_flow().
print() [1/7]
template<typename ... Args> void utils::print (Args ... args)
Definition at line 73 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                print_time_stamp();
                (std::cout << ... << args);
            }
        } else {
            print_time_stamp();
            (std::cout << ... << args);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, mpi_world_rank(), and print_time_stamp().
print() [2/7]
template<typename T > void utils::print (T s)
Definition at line 134 of file util.hpp.
                    {
        print(s, false);
    }
References print().
print() [3/7]
template<typename T > void utils::print (T s, bool endline)
Definition at line 25 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                print_time_stamp();
                std::cout << s;
                if (endline) std::cout << std::endl;
            }
        }
        else {
            print_time_stamp();
            std::cout << s;
            if (endline) std::cout << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, mpi_world_rank(), and print_time_stamp().
Referenced by SelfEnergy< Q >::acc(), add_state_to_hdf(), anderson_update(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_bubble_function(), check_FDTs_K1(), check_FDTs_selfenergy(), check_SE_causality(), SelfEnergy< Q >::check_symmetries(), rvert< Q >::check_symmetries(), compare_with_FDTs(), compute_BSE(), Hartree_Solver::compute_Hartree_term(), Hartree_Solver::compute_Hartree_term_bracketing(), compute_SDE_v2(), compute_SDE_v3(), correctionFunctionBubbleAT_REG2_Keldysh(), correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(), correctionFunctionBubbleP_REG2_Keldysh(), correctionFunctionBubbleP_REG2_Matsubara_NoPHS(), correctionFunctionSelfEnergy_Keldysh(), correctionFunctionSelfEnergy_Matsubara_NoPHS(), SelfEnergy< Q >::direct_set(), fopt_state(), Hartree_Solver::friedel_sum_rule_check(), fullvert< Q >::gammaRb(), fullvert< Q >::gammaRb(), Propagator< Q >::GK(), Propagator< Q >::GM(), Propagator< Q >::GR(), hello_world(), boost::numeric::odeint::detail::integrate_adaptive_check(), boost::numeric::odeint::detail::integrate_nonadaptive(), main(), minimizer(), ode_solver(), IntegrandBubble< Q >::operator()(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::optimize_grid(), parquet_checks(), parquet_iteration(), parquet_solver(), print(), print(), print(), print_job_info(), rhs_n_loop_flow(), old_ode_solvers::RK4_step(), ode_solver_impl::rk_step(), ode_solver_impl::rkqs(), run_parquet(), IntegrandSE< Q, vertType, all_spins, return_type, version >::save_integrand(), Propagator< Q >::SK(), Propagator< Q >::SM(), sopt_state(), sopt_state_impl(), Propagator< Q >::SR(), test_read_write_data_hdf(), test_read_write_state_hdf(), Ti(), topt_state(), irreducible< Q >::val(), Propagator< Q >::valsmooth(), Propagator< Q >::valsmooth_vectorized(), vertexInSOPT(), and write_state_to_hdf().
print() [4/7]
template<typename T , typename U > void utils::print (T t, U u)
Definition at line 140 of file util.hpp.
{
        print(t, u, false);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and print().
print() [5/7]
template<typename T , typename U > void utils::print (T t, U u, bool endline)
Definition at line 57 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                print_time_stamp();
                std::cout << t << u;
                if (endline) std::cout << std::endl;
            }
        }
        else {
            print_time_stamp();
            std::cout << t << u;
            if (endline) std::cout << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, mpi_world_rank(), and print_time_stamp().
print() [6/7]
template<typename T , typename U , typename V > void utils::print (T t, U u, V v)
Definition at line 146 of file util.hpp.
{
        print(t, u, v, false);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and print().
print() [7/7]
template<typename T , typename U , typename V > void utils::print (T t, U u, V v, bool endline)
Definition at line 102 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                print_time_stamp();
                std::cout << t << u << v;
                if (endline) std::cout << std::endl;
            }
        }
        else {
            print_time_stamp();
            std::cout << t << u << v;
            if (endline) std::cout << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, mpi_world_rank(), and print_time_stamp().
print_add() [1/3]
template<typename T > void utils::print_add (T s, bool endline)
Definition at line 42 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                std::cout << s;
                if (endline) std::cout << std::endl;
            }
        }
        else {
        std::cout << s;
        if (endline) std::cout << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, and mpi_world_rank().
Referenced by add_state_to_hdf(), Hartree_Solver::compute_Hartree_term(), Hartree_Solver::compute_Hartree_term_bracketing(), fopt_state(), parquet_checks(), print_job_info(), sopt_state(), sopt_state_impl(), topt_state(), vertexInSOPT(), and write_state_to_hdf().
print_add() [2/3]
template<typename T , typename U > void utils::print_add (T t, U u, bool endline)
Definition at line 87 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                std::cout << t << u;
                if (endline) std::cout << std::endl;
            }
        }
        else {
            std::cout << t << u;
            if (endline) std::cout << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, and mpi_world_rank().
print_add() [3/3]
template<typename T , typename U , typename V > void utils::print_add (T t, U u, V v, bool endline)
Definition at line 119 of file util.hpp.
{
        if (MPI_FLAG) {
            if (mpi_world_rank() == 0) {
                std::cout << t << u << v;
                if (endline) std::cout << std::endl;
            }
        }
        else {
            std::cout << t << u << v;
            if (endline) std::cout << std::endl;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MPI_FLAG, and mpi_world_rank().
print_job_info()
void utils::print_job_info (const fRG_config & config)
Definition at line 218 of file util.c++.
{
        if (KELDYSH) print("SIAM in Keldysh formalism: \n");
        else print("SIAM in Matsubara formalism: \n");
        if (PARTICLE_HOLE_SYMMETRY) print("Using PARTICLE HOLE Symmetry\n");
        print("U for this run is: ", config.U, true);
        if constexpr (REG!=5) print("T for this run is: ", config.T, true);
        print("Lambda flows from ", Lambda_ini);
        print_add(" to ", Lambda_fin, true);
        print("nODE for this run: ", config.nODE_, true);
        if constexpr (MPI_FLAG) print("MPI World Size = " + std::to_string(mpi_world_size()), true);
    #pragma omp parallel default(none)
        {
    #pragma omp master
            print("OMP Threads = " + std::to_string(omp_get_num_threads()), true);
        }
        print("nBOS1 = ", nBOS, true);
        print("nFER1 = ", nFER, true);
        if(MAX_DIAG_CLASS > 1) {
            print("nBOS2 = ", nBOS2, true);
            print("nFER2 = ", nFER2, true);
        }
        if(MAX_DIAG_CLASS > 2) {
            print("nBOS3 = ", nBOS3, true);
            print("nFER3 = ", nFER3, true);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, Lambda_fin, Lambda_ini, MAX_DIAG_CLASS, MPI_FLAG, mpi_world_size(), nBOS, nBOS2, nBOS3, nFER, nFER2, nFER3, fRG_config::nODE_, PARTICLE_HOLE_SYMMETRY, print(), print_add(), REG, fRG_config::T, and fRG_config::U.
Referenced by main().
print_time_stamp()
void utils::print_time_stamp ()
Definition at line 6 of file util.c++.
{
        time_t tt = std::chrono::system_clock::to_time_t(std::chrono::system_clock::now()); // get time stamp
        tm loc = *localtime(&tt);                                            // convert time stamp to readable format
        // get elements of time stamp: Y, M, D, h, m, s
        int tms [6] {loc.tm_year + 1900, loc.tm_mon + 1, loc.tm_mday, loc.tm_hour, loc.tm_min, loc.tm_sec};
        // separators for readable time stamp format
        std::string separators [6] {"-", "-", " | ", ":", ":", " | "};
        for (int i=0; i<6; ++i) {
            if (tms[i] < 10) std::cout << "0";     // make sure to use two-digit format: add zero if necessary
            std::cout << tms[i] << separators[i];  // print time organized by separators
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by print(), print(), print(), and print().
to_array()
template<typename T , typename... Args> constexpr std::array< T, sizeof...(Args)> utils::to_array (const Args &... args) constexpr
Definition at line 180 of file util.hpp.
    { return {{ static_cast<T>(args)... } }; }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by getFlatIndex(), and getFlatIndex().