SIAM-Keldysh-mfRG: frequency_grid.hpp File Reference
frequency_grid.hpp File Reference
#include <cmath>
#include "../data_structures.hpp"
#include "../utilities/util.hpp"
#include "../parameters/master_parameters.hpp"
#include "../utilities/math_utils.hpp"
#include "../symmetries/Keldysh_symmetries.hpp"
#include <cassert>
#include "H5Cpp.h"
Classes
class FrequencyGrid< freqGridType >
class FrequencyGrid< eliasGrid >
class FrequencyGrid< hybridGrid >
class FrequencyGrid< angularGrid >
class bufferFrequencyGrid< k >
Namespaces
namespace hdf5_impl
Macros
#define PARAMETRIZED_GRID
#define HYBRID_GRID_OPTION 0
Enumerations
enum frequencyGridType { eliasGrid , hybridGrid , angularGrid }
Functions
template<typename gridType >
void hdf5_impl::init_freqgrid_from_hdf_LambdaLayer (H5::Group &group, gridType &freqgrid, const int Lambda_it, const double Lambda)
template<typename gridType >
void hdf5_impl::write_freqparams_to_hdf_LambdaLayer (H5::Group &group, const gridType &freqgrid, const int Lambda_it, const int numberLambdaLayers, const bool file_exists, const bool verbose)
double grid_transf_lin (double w, double W_scale)
double grid_transf_v1 (double w, double W_scale, double w_center)
double grid_transf_v2 (double w, double W_scale, double w_center)
double grid_transf_v3 (double w, double W_scale, double w_center)
double grid_transf_v4 (double w, double W_scale, double w_center)
double grid_transf_log (double w, double W_scale)
freqType grid_transf_inv_lin (freqType W, freqType W_scale)
double grid_transf_inv_v1 (double t, double W_scale, double w_center)
double grid_transf_inv_v2 (double t, double W_scale, double w_center)
double grid_transf_inv_v3 (double t, double W_scale, double w_center)
double grid_transf_inv_v4 (double t, double W_scale, double w_center)
double grid_transf_inv_log (double t, double W_scale)
freqType wscale_from_wmax_v1 (freqType &Wscale, freqType w1, freqType wmax, int N)
freqType wscale_from_wmax_v2 (freqType &Wscale, freqType w1, freqType wmax, int N)
freqType wscale_from_wmax_v3 (freqType &Wscale, freqType w1, freqType wmax, int N)
freqType wscale_from_wmax_lin (freqType &Wscale, freqType w1, freqType wmax, int N)
Variables
const bool dense = false
Macro Definition Documentation
HYBRID_GRID_OPTION
#define HYBRID_GRID_OPTION 0
Definition at line 56 of file frequency_grid.hpp.
PARAMETRIZED_GRID
#define PARAMETRIZED_GRID
Definition at line 46 of file frequency_grid.hpp.
Enumeration Type Documentation
frequencyGridType
enum frequencyGridType
Enumerator
eliasGrid
hybridGrid
angularGrid
Definition at line 64 of file frequency_grid.hpp.
{eliasGrid, hybridGrid, angularGrid};
Function Documentation
grid_transf_inv_lin()
freqType grid_transf_inv_lin (freqType W, freqType W_scale)
Definition at line 361 of file frequency_grid.c++.
{
    return W * W_scale;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::frequency_from_t().
grid_transf_inv_log()
double grid_transf_inv_log (double t, double W_scale)
grid_transf_inv_v1()
double grid_transf_inv_v1 (double t, double W_scale, double w_center)
Definition at line 289 of file frequency_grid.c++.
{
    // Version 1: linear around w=0, good for w^(-2) tails
    return w_center + W_scale*t/sqrt(1.-t*t);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
grid_transf_inv_v2()
double grid_transf_inv_v2 (double t, double W_scale, double w_center)
Definition at line 307 of file frequency_grid.c++.
{
    // Version 2: quadratic around w=0, good for w^(-2) tails
    return w_center + W_scale * t * std::abs(t) / sqrt(1. - t * t);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::frequency_from_t().
grid_transf_inv_v3()
double grid_transf_inv_v3 (double t, double W_scale, double w_center)
Definition at line 328 of file frequency_grid.c++.
{
    // Version 3: linear around w=0, good for w^(-1) tails
    return w_center + W_scale * t / (1.-t*t);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::frequency_from_t().
grid_transf_inv_v4()
double grid_transf_inv_v4 (double t, double W_scale, double w_center)
Definition at line 343 of file frequency_grid.c++.
{
    // Version 4: quadratic around w=0, good for w^(-1) tails
    return w_center + W_scale * sgn(t) * t*t /(1.-t*t);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sgn().
Referenced by FrequencyGrid< eliasGrid >::frequency_from_t().
grid_transf_lin()
double grid_transf_lin (double w, double W_scale)
Definition at line 355 of file frequency_grid.c++.
{
    return w / W_scale;
}
Referenced by FrequencyGrid< eliasGrid >::t_from_frequency().
grid_transf_log()
double grid_transf_log (double w, double W_scale)
grid_transf_v1()
double grid_transf_v1 (const double w, const double W_scale, const double w_center)
Here are several functions which map the real axis to the compact interval [-1,1] W_scale: sets the scale separating small frequencies (containing interesting structures) and tails
Definition at line 284 of file frequency_grid.c++.
{
    // Version 1: linear around w=0, good for w^(-2) tails
    const double w_dev = w - w_center;
    return w_dev/sqrt(W_scale*W_scale + w_dev*w_dev);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
grid_transf_v2()
double grid_transf_v2 (double w, double W_scale, double w_center)
Definition at line 299 of file frequency_grid.c++.
{
    // Version 2: quadratic around w=0, good for w^(-2) tails
    const double w_dev = w - w_center;
    const double w2 = w_dev * w_dev;
    const double res = sgn(w_dev) * sqrt((sqrt(w2*w2 + 4 * w2 * W_scale * W_scale) - w2) / 2.) / W_scale;
    assert(isfinite(res));
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sgn().
Referenced by FrequencyGrid< eliasGrid >::t_from_frequency().
grid_transf_v3()
double grid_transf_v3 (double w, double W_scale, double w_center)
Definition at line 322 of file frequency_grid.c++.
{
    // Version 3: linear around w=0, good for w^(-1) tails
    const double almost_zero = 1e-12;
    const double w_dev = w - w_center;
    return (std::abs(w_dev) < almost_zero) ? 0. : (-W_scale + sqrt(4*w_dev*w_dev + W_scale*W_scale))/2/w_dev;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::t_from_frequency().
grid_transf_v4()
double grid_transf_v4 (double w, double W_scale, double w_center)
Definition at line 337 of file frequency_grid.c++.
{
    // Version 4: quadratic around w=0, good for w^(-1) tails
    const double w_dev = w - w_center;
    const double abs_w = std::abs(w_dev);
    return sgn(w_dev) * sqrt(abs_w/(abs_w + W_scale));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sgn().
Referenced by FrequencyGrid< eliasGrid >::t_from_frequency().
wscale_from_wmax_lin()
freqType wscale_from_wmax_lin (freqType & Wscale, freqType w1, freqType wmax, int N)
wscale_from_wmax_v1()
freqType wscale_from_wmax_v1 (freqType & Wscale, const freqType w1, const freqType wmax, const int N)
Makes sure that lower bound for W_scale fulfilled Wscale: current value for W_scale w1: smallest positive Matsubara frequency (for bosons: 2*M_PI*T, for fermions: M_PI*T) wmax: maximal frequency N: relates tmax to t1 by t1=tmax/N (for bosons: (nBOS-1)/2; for fermions: nFER-1)
Definition at line 372 of file frequency_grid.c++.
{
    freqType Wscale_candidate;
    // Version 1: linear around w=0, good for w^(-2) tails
    Wscale_candidate = wmax * sqrt( (N*N -1*2) / (pow(wmax/w1, 2) - N*N));
    return std::max(Wscale, Wscale_candidate);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::wscale_from_wmax().
wscale_from_wmax_v2()
freqType wscale_from_wmax_v2 (freqType & Wscale, freqType w1, freqType wmax, int N)
Definition at line 379 of file frequency_grid.c++.
{
    freqType Wscale_candidate;
    // Version 2: quaadratic around w=0, good for w^(-2) tails
    assert(w1 / wmax < 1./(N*N));       // if this fails, then change wmax or use Version 1
    Wscale_candidate = w1 * wmax * N * sqrt(N*N - 1) *sqrt(wmax*wmax - N*N*w1*w1) / std::abs(wmax*wmax - w1*w1*N*N*N*N);
    return std::max(Wscale, Wscale_candidate);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
wscale_from_wmax_v3()
freqType wscale_from_wmax_v3 (freqType & Wscale, freqType w1, freqType wmax, int N)
Definition at line 388 of file frequency_grid.c++.
{
    freqType Wscale_candidate;
    // Version 3: quadratic around w=0, good for w^(-1) tails
    Wscale_candidate = w1 * wmax * (N*N - 1*2.) / sqrt(N * (N * (wmax*wmax + w1*w1) - N*N*w1*wmax - w1*wmax));
    return std::max(Wscale, Wscale_candidate);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::wscale_from_wmax().
Variable Documentation
dense
const bool dense = false
Definition at line 53 of file frequency_grid.hpp.