#!/bin/bash
#SBATCH -o /home/hpc/uh3o1/ri26yad/LOG/LOG_old/OMP_job.%j.%N.out
#SBATCH -D /home/hpc/uh3o1/ri26yad/RUN
#SBATCH -J OMP_job
#SBATCH --get-user-env
#SBATCH --clusters=lmu_asc
#SBATCH --partition=lmu_asc_shm8
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=15000
#SBATCH --mail-type=end
#SBATCH --mail-user=lukas.weidinger@physik.uni-muenchen.de
#SBATCH --export=NONE
#SBATCH --time=72:00:00

. /etc/profile
. $HOME/.bashrc

export MKL_NUM_THREADS=1
export OMP_NUM_THREADS=8
