SIAM-Keldysh-mfRG: loop_corrections.c++ File Reference
loop_corrections.c++ File Reference
#include "loop_corrections.hpp"
Functions
template<>
auto correctionFunctionSelfEnergy_Keldysh (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
template<>
auto correctionFunctionSelfEnergy_Matsubara_NoPHS (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
Function Documentation
correctionFunctionSelfEnergy_Keldysh()
template<> auto correctionFunctionSelfEnergy_Keldysh (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
Definition at line 4 of file loop_corrections.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
correctionFunctionSelfEnergy_Matsubara_NoPHS()
template<> auto correctionFunctionSelfEnergy_Matsubara_NoPHS (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
Definition at line 11 of file loop_corrections.c++.
{
    utils::print("Error! Computations without particle hole symmetry require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().