SIAM-Keldysh-mfRG: Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter > Class Template Reference
Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter > Class Template Reference
#include <data_buffer.hpp>
Public Types
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
Public Member Functions
Interpolator ()
Interpolator (double Lambda, dimensions_type dims, const fRG_config &config)
void initInterpolator () const
void set_initializedInterpol (const bool is) const
Eigen::Matrix< double, numSamples(), 1 > get_weights (const frequencies_type &frequencies, index_type &idx_low) const
template<typename result_type = Q, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true>
auto interpolate_impl (const frequencies_type &frequencies, index_type indices) const -> result_type
Public Attributes
bool initialized = false
Private Types
using base_class = dataContainer_type
using this_class = Interpolator
using frequencies_type = std::array<freqType, numberFrequencyDims>
Static Private Member Functions
static constexpr my_index_t numSamples ()
static constexpr my_index_t numSamples_half ()
template<typename result_type >
static constexpr my_index_t get_vecsize ()
Detailed Description
template<typename Q, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type, interpolMethod inter>
class Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >
TODO: Profile and improve:
get_weights()
get_values()
handling of frequency-/index-arrays (avoid copies)
Definition at line 18 of file data_buffer.hpp.
Member Typedef Documentation
base_class
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::base_class = dataContainer_type private
Definition at line 19 of file data_buffer.hpp.
dimensions_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::dimensions_type = typename base_class::dimensions_type
Definition at line 37 of file data_buffer.hpp.
frequencies_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::frequencies_type = std::array<freqType, numberFrequencyDims> private
Definition at line 22 of file data_buffer.hpp.
index_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::index_type = typename base_class::index_type
Definition at line 36 of file data_buffer.hpp.
this_class
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::this_class = Interpolator private
Definition at line 20 of file data_buffer.hpp.
Constructor & Destructor Documentation
Interpolator() [1/2]
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::Interpolator () inline
Definition at line 40 of file data_buffer.hpp.
: initialized(false) {};
Interpolator() [2/2]
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::Interpolator (double Lambda, dimensions_type dims, const fRG_config & config) inline explicit
Definition at line 41 of file data_buffer.hpp.
: base_class(Lambda, dims, config) {};
Member Function Documentation
get_vecsize()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> template<typename result_type > static constexpr my_index_t Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::get_vecsize () inline static constexpr private
Definition at line 31 of file data_buffer.hpp.
{
        if constexpr(std::is_same_v<result_type, Q>) return 1;
        else { return result_type::RowsAtCompileTime; }
    }
get_weights()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> Eigen::Matrix< double, numSamples(), 1 > Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::get_weights (const frequencies_type & frequencies, index_type & idx_low) const inline
Definition at line 46 of file data_buffer.hpp.
{
        Eigen::Matrix<double, numSamples(), 1> weights;
        std::array<my_index_t,numberFrequencyDims> freq_idx;
        std::array<double,numberFrequencyDims> dw_normalized;
        if constexpr(inter == linear) base_class::frequencies.get_grid_index(freq_idx, dw_normalized, frequencies);
        else if constexpr(inter == linear_on_aux) base_class::frequencies.get_auxgrid_index(freq_idx, dw_normalized, frequencies);
        else assert(false);
        for (my_index_t i = 0; i < numberFrequencyDims; i++) {
            idx_low[pos_first_freqpoint+i] = freq_idx[i];
            assert(freq_idx[i] < 10000);
        }
        for (my_index_t j = 0; j < numSamples_half(); j++) {
            weights[j  ] = 1-dw_normalized[0];
            weights[numSamples_half()+j] = dw_normalized[0];
        }
        if constexpr (numberFrequencyDims == 2) {
            for (my_index_t j = 0; j < numSamples_half(); j++) {
                weights[2*j  ] *= 1-dw_normalized[1];
                weights[2*j+1] *= dw_normalized[1];
            }
        }
        if constexpr(numberFrequencyDims == 3) {
            for (my_index_t j = 0; j < 2; j++) {
                for (my_index_t i = 0; i < 2; i++) {
                    weights[4*j+i]   *= 1-dw_normalized[1];
                    weights[4*j+i+2] *= dw_normalized[1];
                }
            }
            for (my_index_t j = 0; j < numSamples_half(); j++) {
                weights[j*2]   *= 1-dw_normalized[2];
                weights[1+j*2] *= dw_normalized[2];
            }
        }
        return weights;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), linear, linear_on_aux, Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples(), and Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples_half().
Referenced by Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl().
initInterpolator()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> void Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initInterpolator () const inline
Definition at line 42 of file data_buffer.hpp.
{initialized = true;};
References Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initialized.
Referenced by check_SE_causality(), Hartree_Solver::Hartree_Solver(), and Hartree_Solver::Hartree_Solver().
interpolate_impl()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> template<typename result_type = Q, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl (const frequencies_type & frequencies, index_type indices) const -> result_type inline
Definition at line 179 of file data_buffer.hpp.
{
        constexpr my_index_t vecsize = get_vecsize<result_type>();
        using weights_type = Eigen::Matrix<double, numSamples(), 1>;
        using values_type = Eigen::Matrix<Q, vecsize, numSamples()>;
        // Check if the frequency runs out of the box; if yes: return asymptotic value
        if (base_class::frequencies.is_in_box(frequencies))
        {
#ifdef DENSEGRID
            result_type result;
            if constexpr (std::is_same_v<result_type,Q>)
            {
                if constexpr(numberFrequencyDims == 1)
                {
                    result = interpolate_nearest1D<result_type>(frequencies[0],
                                                                base_class::get_VertexFreqGrid().primary_grid,
                                                                [&](int i) -> result_type {
                                                                    indices[pos_first_freqpoint] = i;
                                                                    return base_class::val(indices);
                                                                });
                }
                else if constexpr(numberFrequencyDims == 2)
                {
                    result = interpolate_nearest2D<result_type>(frequencies[0], frequencies[1],
                                                                base_class::get_VertexFreqGrid().primary_grid,
                                                                base_class::get_VertexFreqGrid().secondary_grid,
                                                                [&](int i, int j) -> result_type {
                                                                    indices[pos_first_freqpoint] = i;
                                                                    indices[pos_first_freqpoint + 1] = j;
                                                                    return base_class::val(indices);
                                                                });
                }
                else if constexpr(numberFrequencyDims == 3)
                {
                    result = interpolate_nearest3D<result_type>(frequencies[0], frequencies[1], frequencies[2],
                                                                base_class::get_VertexFreqGrid().primary_grid,
                                                                base_class::get_VertexFreqGrid().secondary_grid,
                                                                base_class::get_VertexFreqGrid().tertiary_grid,
                                                                [&](int i, int j, int l) -> result_type {
                                                                    indices[pos_first_freqpoint] = i;
                                                                    indices[pos_first_freqpoint + 1] = j;
                                                                    indices[pos_first_freqpoint + 2] = l;
                                                                    return base_class::val(indices);
                                                                });
                }
            }
            else {
                if constexpr(numberFrequencyDims == 1)
                {
                    result << interpolate_nearest1D<Q>(frequencies[0],
                                                                base_class::get_VertexFreqGrid().primary_grid,
                                                                [&](int i) -> Q {
                                                                    indices[pos_first_freqpoint] = i;
                                                                    return base_class::val(indices);
                                                                });
                }
                else if constexpr(numberFrequencyDims == 2)
                {
                    result << interpolate_nearest2D<Q>(frequencies[0], frequencies[1],
                                                                base_class::get_VertexFreqGrid().primary_grid,
                                                                base_class::get_VertexFreqGrid().secondary_grid,
                                                                [&](int i, int j) -> Q {
                                                                    indices[pos_first_freqpoint] = i;
                                                                    indices[pos_first_freqpoint + 1] = j;
                                                                    return base_class::val(indices);
                                                                });
                }
                else if constexpr(numberFrequencyDims == 3)
                {
                    result << interpolate_nearest3D<Q>(frequencies[0], frequencies[1], frequencies[2],
                                                                base_class::get_VertexFreqGrid().primary_grid,
                                                                base_class::get_VertexFreqGrid().secondary_grid,
                                                                base_class::get_VertexFreqGrid().tertiary_grid,
                                                                [&](int i, int j, int l) -> Q {
                                                                    indices[pos_first_freqpoint] = i;
                                                                    indices[pos_first_freqpoint + 1] = j;
                                                                    indices[pos_first_freqpoint + 2] = l;
                                                                    return base_class::val(indices);
                                                                });
                }
            }
            return result;
#else
            // get weights from frequency Grid
            const weights_type weights = get_weights(frequencies, indices);
            // fetch vertex values
            const values_type values = base_class::template get_values<numberFrequencyDims, pos_first_freqpoint, vecsize, 2>(indices);
            assert(weights.allFinite());
            assert(values.allFinite());
            if constexpr(std::is_same_v<result_type, Q>) {
                const Q result = values * weights;
                assert(my_isfinite(result));
                return result;
            }
            else if constexpr(std::is_same_v<result_type,Eigen::Matrix<Q,result_type::RowsAtCompileTime,1>>){
                const Eigen::Matrix<Q, vecsize,1> result = values * weights;
                assert(result.allFinite());
                return result;
            }
            else {
                assert(false);
                const result_type result;
                return result;
            }
#endif
            //assert(my_isfinite(result));
            //return result;
        } else { //asymptotic value
            if constexpr (KELDYSH or ZERO_T) {
                if constexpr (std::is_same_v<result_type, Q>) return result_type{};
                else return result_type::Zero();
            }
            else { // finite T Matsubara: extrapolate with w^-2 tail
                if constexpr (numberFrequencyDims == 1) {
                    if constexpr (rank == SE_config.rank) {
                        const double wmax = base_class::frequencies.primary_grid.w_upper;
                        const double w = frequencies[0];
                        const double wabs = std::abs(w);
                        if (w <= 0.) {
                            indices[pos_first_freqpoint] = 0;
                        }
                        else {
                            indices[pos_first_freqpoint] = base_class::frequencies.primary_grid.number_of_gridpoints - 1;
                        }
                        if constexpr (std::is_same_v<result_type, Q>) {
                            const result_type result = wmax / (wabs) * base_class::val(indices);
                            return result;
                        } else {
                            const result_type result = wmax / (wabs) *
                                                       base_class::template get_values<numberFrequencyDims, pos_first_freqpoint, vecsize, 1>(
                                                               indices);
                            return result;
                        }
                    }
                    else {
                        const double wmax = base_class::frequencies.primary_grid.w_upper;
                        const double wabs = std::abs(frequencies[0]);
                        indices[pos_first_freqpoint] = 0;
                        if constexpr (std::is_same_v<result_type, Q>) {
                            const result_type result = wmax * wmax / (wabs * wabs) * base_class::val(indices);
                            return result;
                        } else {
                            const result_type result = wmax * wmax / (wabs * wabs) *
                                                       base_class::template get_values<numberFrequencyDims, pos_first_freqpoint, vecsize, 1>(
                                                               indices);
                            return result;
                        }
                    }
                }
                else if constexpr (numberFrequencyDims > 1) {
                    const double wmax = base_class::frequencies.primary_grid.w_upper;
                    const double vmax = base_class::frequencies.secondary_grid.w_upper;
                    const double wabs = std::abs(frequencies[0]);
                    if (wabs > wmax) {
                        return result_type{};
                    }
                    else if constexpr (numberFrequencyDims == 2) {
                        const double w = frequencies[0];
                        const double v = frequencies[1];
                        const int index = base_class::frequencies.primary_grid.get_grid_index(w);
                        indices[pos_first_freqpoint] = index;
                        if (v <= -vmax) {
                            indices[pos_first_freqpoint + 1] = 0;
                        }
                        else {
                            indices[pos_first_freqpoint + 1] = base_class::frequencies.secondary_grid.number_of_gridpoints - 1 + signFlipCorrection_MF_int(w);
                        }
                        if constexpr (std::is_same_v<result_type,Q>) {
                            const result_type result = (vmax * vmax) / (v * v) * base_class::val(indices);
                            return result;
                        } else {
                            const result_type result = (vmax * vmax) / (v * v) * base_class::template get_values<numberFrequencyDims, pos_first_freqpoint, vecsize, 1>(indices);
                            return result;
                        }
                    }
                    else if constexpr (numberFrequencyDims == 3) {
                        const double w = frequencies[0];
                        const double v = frequencies[1];
                        const double vp= frequencies[2];
                        const int index = base_class::frequencies.primary_grid.get_grid_index(w);
                        indices[pos_first_freqpoint] = index;
                        Q result = 1.;
                        if (v <= -vmax) {
                            indices[pos_first_freqpoint + 1] = 0;
                            result *= vmax * vmax / (v * v);
                        }
                        else if (v >= vmax){
                            indices[pos_first_freqpoint + 1] = base_class::frequencies.secondary_grid.number_of_gridpoints - 1 + signFlipCorrection_MF_int(w) ;
                            result *= vmax * vmax / (v * v);
                        }
                        else {
                            const int index_v = base_class::frequencies.secondary_grid.get_grid_index(v);
                            indices[pos_first_freqpoint + 1] = index_v;
                        }
                        if (vp <= -vmax) {
                            indices[pos_first_freqpoint + 2] = 0;
                            result *= vmax * vmax / (vp * vp);
                        }
                        else if (vp >= vmax){
                            indices[pos_first_freqpoint + 2] = base_class::frequencies.secondary_grid.number_of_gridpoints - 1 + signFlipCorrection_MF_int(w) ;
                            result *= vmax * vmax / (vp * vp);
                        }
                        else {
                            const int index_vp = base_class::frequencies.secondary_grid.get_grid_index(vp);
                            indices[pos_first_freqpoint + 2] = index_vp;
                        }
                        if constexpr (std::is_same_v<result_type,Q>) {
                            result *= base_class::val(indices);
                        } else {
                            result *= base_class::template get_values<numberFrequencyDims, pos_first_freqpoint, vecsize, 1>(indices);
                        }
                        return result;
                    }
                }
                else {
                    return result_type{};
                }
                //else {assert(false);}
            }
        }
    };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::get_weights(), KELDYSH, my_isfinite(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples(), SE_config, signFlipCorrection_MF_int(), and ZERO_T.
numSamples()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> static constexpr my_index_t Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples () inline static constexpr private
Definition at line 24 of file data_buffer.hpp.
{
        return my_integer_pow<numberFrequencyDims>(my_index_t(2));
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::get_weights(), and Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl().
numSamples_half()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> static constexpr my_index_t Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples_half () inline static constexpr private
Definition at line 27 of file data_buffer.hpp.
{
        return my_integer_pow<numberFrequencyDims-1>(my_index_t(2));
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_integer_pow().
Referenced by Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::get_weights().
set_initializedInterpol()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> void Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::set_initializedInterpol (const bool is) const inline
Definition at line 43 of file data_buffer.hpp.
{initialized = is;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initialized.
Member Data Documentation
initialized
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type , interpolMethod inter> bool Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initialized = false mutable
Definition at line 39 of file data_buffer.hpp.
Referenced by Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initInterpolator(), and Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::set_initializedInterpol().
The documentation for this class was generated from the following file:
data_buffer.hpp