SIAM-Keldysh-mfRG: multidimensional::BlockView< T, depth > Class Template Reference
multidimensional::BlockView< T, depth > Class Template Reference
#include <ranged_view.hpp>
Public Member Functions
BlockView (const multiarray< T, depth > &data, const index_type &start, const index_type length)
const T & at (const index_type &index) const
vec< T > get_vec () const
Private Types
using index_type = std::array<std::size_t,depth>
Private Member Functions
bool check_bounds (const index_type &index) const
size_t flat_index (const index_type &index) const noexcept
Private Attributes
const index_type m_start
const index_type m_length
const index_type m_stride
const multidimensional::multiarray< T, depth > & m_data
Detailed Description
template<typename T, size_t depth>
class multidimensional::BlockView< T, depth >
Definition at line 50 of file ranged_view.hpp.
Member Typedef Documentation
index_type
template<typename T , size_t depth> using multidimensional::BlockView< T, depth >::index_type = std::array<std::size_t,depth> private
Definition at line 52 of file ranged_view.hpp.
Constructor & Destructor Documentation
BlockView()
template<typename T , size_t depth> multidimensional::BlockView< T, depth >::BlockView (const multiarray< T, depth > & data, const index_type & start, const index_type length) inline
Definition at line 54 of file ranged_view.hpp.
                : m_data(data), m_start(start), m_length(length), m_stride(data.length()) {
            // check lengths
            const index_type& length_base = data.length();
            bool is_sensible = true;
            for (int i = 0; i < depth; i++) {
                if (m_start[i] + m_length[i] > length_base[i]) is_sensible = false;
            }
            assert(is_sensible);
        };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::length(), multidimensional::BlockView< T, depth >::m_length, and multidimensional::BlockView< T, depth >::m_start.
Member Function Documentation
at()
template<typename T , size_t depth> const T & multidimensional::BlockView< T, depth >::at (const index_type & index) const inline
Definition at line 101 of file ranged_view.hpp.
{
            if (check_bounds(index))
            {
                const size_t flat_idx = flat_index(index);
                return m_data.flat_at(flat_idx);
            }
            else
            {
                assert(false);
                throw std::out_of_range("Attempted to access multiarray element at invalid index.");
            }
        }
References multidimensional::BlockView< T, depth >::check_bounds(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::BlockView< T, depth >::flat_index(), and multidimensional::BlockView< T, depth >::m_data.
Referenced by multidimensional::BlockView< T, depth >::get_vec().
check_bounds()
template<typename T , size_t depth> bool multidimensional::BlockView< T, depth >::check_bounds (const index_type & index) const inline private
Definition at line 74 of file ranged_view.hpp.
        {
#ifdef MULTIARRAY_CHECK_BOUNDS
            for (size_t i = 0; i < depth; i++)
            {
                if (index[i] >= m_length[i] || index[i] < 0)
                {
                    return false;
                }
            }
#endif
            return true;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::BlockView< T, depth >::m_length.
Referenced by multidimensional::BlockView< T, depth >::at().
flat_index()
template<typename T , size_t depth> size_t multidimensional::BlockView< T, depth >::flat_index (const index_type & index) const inline private noexcept
Definition at line 88 of file ranged_view.hpp.
        {
            size_t res = m_start[0] + index[0];
            for (size_t i = 1; i < depth; i++)
            {
                res *= m_stride[i];
                res += m_start[i] + index[i];
            }
            return res;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::BlockView< T, depth >::m_start, and multidimensional::BlockView< T, depth >::m_stride.
Referenced by multidimensional::BlockView< T, depth >::at().
get_vec()
template<typename T , size_t depth> vec< T > multidimensional::BlockView< T, depth >::get_vec () const inline
Definition at line 115 of file ranged_view.hpp.
{
            const size_t flat_size = getFlatSize(m_length);
            vec<T> res(flat_size);
            for (size_t i = 0; i < flat_size; i++) {
                index_type idx;
                getMultIndex<depth>(idx, i, m_length);
                res[i] = at(idx);
            }
            return res;
        }
References multidimensional::BlockView< T, depth >::at(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), getFlatSize(), and multidimensional::BlockView< T, depth >::m_length.
Member Data Documentation
m_data
template<typename T , size_t depth> const multidimensional::multiarray<T,depth>& multidimensional::BlockView< T, depth >::m_data private
Definition at line 69 of file ranged_view.hpp.
Referenced by multidimensional::BlockView< T, depth >::at().
m_length
template<typename T , size_t depth> const index_type multidimensional::BlockView< T, depth >::m_length private
Definition at line 67 of file ranged_view.hpp.
Referenced by multidimensional::BlockView< T, depth >::BlockView(), multidimensional::BlockView< T, depth >::check_bounds(), and multidimensional::BlockView< T, depth >::get_vec().
m_start
template<typename T , size_t depth> const index_type multidimensional::BlockView< T, depth >::m_start private
Definition at line 66 of file ranged_view.hpp.
Referenced by multidimensional::BlockView< T, depth >::BlockView(), and multidimensional::BlockView< T, depth >::flat_index().
m_stride
template<typename T , size_t depth> const index_type multidimensional::BlockView< T, depth >::m_stride private
Definition at line 68 of file ranged_view.hpp.
Referenced by multidimensional::BlockView< T, depth >::flat_index().
The documentation for this class was generated from the following file:
ranged_view.hpp