SIAM-Keldysh-mfRG: symmetry_transformations.hpp File Reference
symmetry_transformations.hpp File Reference
#include "../parameters/master_parameters.hpp"
#include "../utilities/math_utils.hpp"
#include "Keldysh_symmetries.hpp"
#include "../data_structures.hpp"
Functions
void switch_channel (IndicesSymmetryTransformations &indices)
template<bool is_SBE_lambda>
void T1 (IndicesSymmetryTransformations &indices)
exchange incoming legs
template<bool is_SBE_lambda>
void T2 (IndicesSymmetryTransformations &indices)
exchange outgoing lines
template<bool is_SBE_lambda>
void T3 (IndicesSymmetryTransformations &indices)
template<bool is_SBE_lambda>
void TC (IndicesSymmetryTransformations &indices)
template<bool is_SBE_lambda>
void Tph (IndicesSymmetryTransformations &indices)
template<bool is_SBE_lambda>
void TR (IndicesSymmetryTransformations &indices)
template<bool is_SBE_lambda>
void Ti (IndicesSymmetryTransformations &indices, int i)
Function Documentation
switch_channel()
void switch_channel (IndicesSymmetryTransformations & indices)
Definition at line 3 of file symmetry_transformations.c++.
{
    switch (indices.channel_rvert) {
        case 'a':
            indices.channel_rvert = 't';
            break;
        case 't':
            indices.channel_rvert = 'a';
            break;
        default:;
    }
    if (INTERPOL2D_FOR_K3) {
        switch (indices.channel_bubble) {
            case 'a':
                indices.channel_bubble = 't';
                break;
            case 't':
                indices.channel_bubble = 'a';
                break;
            default: ;
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and INTERPOL2D_FOR_K3.
Referenced by T1(), and T2().
T1()
template<bool is_SBE_lambda> void T1 (IndicesSymmetryTransformations & indices)
exchange incoming legs
Definition at line 17 of file symmetry_transformations.hpp.
{
    if constexpr (KELDYSH_FORMALISM) {
        std::array<int,4> alphas_tmp = iK_to_alphas(indices.iK);
        std::swap(alphas_tmp[2],alphas_tmp[3]);
        indices.iK = alphas_to_iK(alphas_tmp);
    }
    if constexpr(!is_SBE_lambda)
    {
        indices.prefactor *= -1.;
    }
    //else {
    //    if (indices.channel_rvert == 'p') indices.prefactor *= -1.;
    //}
    indices.conjugate ^= false;
    if(indices.channel_rvert == 'p'){
        indices.w  *= 1.;
        if (MAX_DIAG_CLASS > 1) {
            indices.v1 *= 1.;
            indices.v2 *= -1.;
            if (!KELDYSH && !ZERO_T){
                freqType rounding_correction = signFlipCorrection_MF(indices.w);  // correction due to rounding towards Matsubara frequencies
                indices.v2 += rounding_correction;
                // correction due to rounding towards Matsubara frequencies
            }
        }
    }
    else {
        indices.asymmetry_transform ^= true;
        indices.w  *= -1.;
        if (MAX_DIAG_CLASS > 1) {
            freqType temp = indices.v1;
            indices.v1 = indices.v2;
            indices.v2 = temp;
        }
    }
    if (INTERPOL2D_FOR_K3) {
        if(indices.channel_bubble != 'p'){
            indices.iw_r = nBOS3 - 1 - indices.iw_r; // corresponds to "w *= -1"
        }
    }
    switch_channel(indices);
    indices.spin = 1 - indices.spin;
}
References alphas_to_iK(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), iK_to_alphas(), INTERPOL2D_FOR_K3, KELDYSH, KELDYSH_FORMALISM, MAX_DIAG_CLASS, nBOS3, signFlipCorrection_MF(), switch_channel(), and ZERO_T.
T2()
template<bool is_SBE_lambda> void T2 (IndicesSymmetryTransformations & indices)
exchange outgoing lines
Definition at line 66 of file symmetry_transformations.hpp.
{
    if constexpr (KELDYSH_FORMALISM) {
        std::array<int,4> alphas_tmp = iK_to_alphas(indices.iK);
        std::swap(alphas_tmp[0],alphas_tmp[1]);
        indices.iK = alphas_to_iK(alphas_tmp);
    }
    if constexpr(!is_SBE_lambda)
    {
        indices.prefactor *= -1.;
    }
    //else {
    //    if (indices.channel_rvert == 'p') indices.prefactor *= -1.;
    //}
    indices.conjugate ^= false;
    if(indices.channel_rvert == 'p'){
        indices.w  *= 1.;
        if (MAX_DIAG_CLASS > 1) {
            indices.v1 *= -1.;
            indices.v2 *= 1.;
            if (!KELDYSH && !ZERO_T) {
                double rounding_correction = signFlipCorrection_MF(indices.w);  // correction due to rounding towards Matsubara frequencies
                indices.v1 += rounding_correction;
                // correction due to rounding towards Matsubara frequencies
            }
        }
    }
    else {
//        indices.w  *= 1.;
//        indices.v1 *= 1.;
//        indices.v2 *= 1.;
    }
    switch_channel(indices);
    indices.spin = 1 - indices.spin;
}
References alphas_to_iK(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), iK_to_alphas(), KELDYSH, KELDYSH_FORMALISM, MAX_DIAG_CLASS, signFlipCorrection_MF(), switch_channel(), and ZERO_T.
T3()
template<bool is_SBE_lambda> void T3 (IndicesSymmetryTransformations & indices)
Definition at line 101 of file symmetry_transformations.hpp.
{
    T1<is_SBE_lambda>(indices);
    T2<is_SBE_lambda>(indices);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
TC()
template<bool is_SBE_lambda> void TC (IndicesSymmetryTransformations & indices)
Definition at line 105 of file symmetry_transformations.hpp.
{
    if constexpr (KELDYSH_FORMALISM) {
        std::array<int,4> alphas_tmp = iK_to_alphas(indices.iK);
        std::swap(alphas_tmp[0],alphas_tmp[2]);
        std::swap(alphas_tmp[1],alphas_tmp[3]);
        indices.iK = alphas_to_iK(alphas_tmp);
    }
    indices.conjugate ^= true;
    //if constexpr(SBE_DECOMPOSITION) {
    //    if (indices.channel_rvert == 'p') {
    //        indices.prefactor *= -1;
    //    }
    //}
    if (indices.channel_rvert == 't'){ //TC acts differently on t, not on p!!
        indices.w  *= -1.;
//        indices.v1 *= 1.;
//        indices.v2 *= 1.;
    }
    else{
        indices.asymmetry_transform ^= true;
        indices.w  *= 1.;
        if (MAX_DIAG_CLASS > 1) {
            double temp = indices.v1;
            indices.v1 = indices.v2;
            indices.v2 = temp;
        }
    }
    if constexpr(INTERPOL2D_FOR_K3) {
        if (indices.channel_bubble == 't') {
            indices.iw_r = nBOS3 - 1 - indices.iw_r; // corresponds to "w *= -1"
        }
    }
    if constexpr(KELDYSH and CONTOUR_BASIS != 1)
    {
        if constexpr(is_SBE_lambda) {
            if ( isInList(indices.iK, odd_Keldysh)) indices.prefactor *= -1.;
        }
        else  {
            if (!isInList(indices.iK, odd_Keldysh)) indices.prefactor *= -1.;
        }
    }
    else if constexpr(KELDYSH and CONTOUR_BASIS == 1)
    {
        if constexpr(!is_SBE_lambda) {indices.prefactor *= -1;}
    }
    else{
        indices.w *= -1;
        indices.v1 *= -1;
        indices.v2 *= -1;
        indices.iw_r = nBOS3 - 1 - indices.iw_r; // corresponds to "w *= -1"
        if (!ZERO_T){// Matsubara T>0
            double rounding_correction = signFlipCorrection_MF(indices.w);  // correction due to rounding towards Matsubara frequencies
            indices.v1 += rounding_correction;
            indices.v2 += rounding_correction;
        }
    }
}
References alphas_to_iK(), CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), iK_to_alphas(), INTERPOL2D_FOR_K3, isInList(), KELDYSH, KELDYSH_FORMALISM, MAX_DIAG_CLASS, nBOS3, odd_Keldysh(), signFlipCorrection_MF(), and ZERO_T.
Ti()
template<bool is_SBE_lambda> void Ti (IndicesSymmetryTransformations & indices, int i)
Definition at line 215 of file symmetry_transformations.hpp.
{
    if (i == 0) return;
    switch (i) {
        case 1:
            T1<is_SBE_lambda>(indices);
            break;
        case 2:
            T2<is_SBE_lambda>(indices);
            break;
        case 3:
            T3<is_SBE_lambda>(indices);
            break;
        case 4:
            TC<is_SBE_lambda>(indices);
            break;
        case 14:
            T1<is_SBE_lambda>(indices);
            TC<is_SBE_lambda>(indices);
            break;
        case 24:
            T2<is_SBE_lambda>(indices);
            TC<is_SBE_lambda>(indices);
            break;
        case 41:
            TC<is_SBE_lambda>(indices);
            T1<is_SBE_lambda>(indices);
            break;
        case 43:
            TC<is_SBE_lambda>(indices);
            T3<is_SBE_lambda>(indices);
            break;
        case 34:
            TC<is_SBE_lambda>(indices);
            T3<is_SBE_lambda>(indices);
            break;
#if KELDYSH_FORMALISM and PARTICLE_HOLE_SYMM
                case 6:
                    Tph<is_SBE_lambda>(indices);
                break;
                case 16:
                    T1<is_SBE_lambda>(indices);
                Tph<is_SBE_lambda>(indices);
                break;
                case 26:
                    T2<is_SBE_lambda>(indices);
                Tph<is_SBE_lambda>(indices);
                break;
                case 36:
                    T3<is_SBE_lambda>(indices);
                Tph<is_SBE_lambda>(indices);
                break;
                case 46:
                    TC<is_SBE_lambda>(indices);
                Tph<is_SBE_lambda>(indices);
                break;
                case 146:
                    T1<is_SBE_lambda>(indices);
                TC<is_SBE_lambda>(indices);
                Tph<is_SBE_lambda>(indices);
                break;
                case 246:
                    T2<is_SBE_lambda>(indices);
                TC<is_SBE_lambda>(indices);
                Tph<is_SBE_lambda>(indices);
                break;
                case 346:
                    Tph<is_SBE_lambda>(indices);
                TC<is_SBE_lambda>(indices);
                T3<is_SBE_lambda>(indices);
                break;
#endif
            if (!KELDYSH) {
                case 7:
                    TR<is_SBE_lambda>(indices);
                break;
                case 37:
                    TR<is_SBE_lambda>(indices);
                T3<is_SBE_lambda>(indices);
                break;
                case 47:
                    TC<is_SBE_lambda>(indices);
                TR<is_SBE_lambda>(indices);
                break;
                case 347:
                    TR<is_SBE_lambda>(indices);
                TC<is_SBE_lambda>(indices);
                T3<is_SBE_lambda>(indices);
                break;
            }
        default:
            utils::print("The Transformation ", i, " in the symmetry table is not covered in Ti! Abort."); assert(false);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, and utils::print().
Tph()
template<bool is_SBE_lambda> void Tph (IndicesSymmetryTransformations & indices)
Definition at line 168 of file symmetry_transformations.hpp.
{
    if (KELDYSH && PARTICLE_HOLE_SYMMETRY){ // Used only for Keldysh calculations with particle-hole symmetry
        indices.conjugate ^= true;
            if constexpr(CONTOUR_BASIS != 1)
            {
                if constexpr(is_SBE_lambda) {
                    if ( isInList(indices.iK, odd_Keldysh)) indices.prefactor *= -1.;
                }
                else  {
                    if (!isInList(indices.iK, odd_Keldysh)) indices.prefactor *= -1.;
                }
            }
            else {
                if constexpr(!is_SBE_lambda) {indices.prefactor *= -1.;}
            }
        indices.w *= -1;
        if (MAX_DIAG_CLASS > 1) {
            indices.v1 *= -1;
            indices.v2 *= -1;
        }
        if (INTERPOL2D_FOR_K3) {
            indices.iw_r = nBOS3 - 1 - indices.iw_r; // corresponds to "w *= -1"
        }
    }
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), INTERPOL2D_FOR_K3, isInList(), KELDYSH, MAX_DIAG_CLASS, nBOS3, odd_Keldysh(), and PARTICLE_HOLE_SYMMETRY.
TR()
template<bool is_SBE_lambda> void TR (IndicesSymmetryTransformations & indices)
Definition at line 197 of file symmetry_transformations.hpp.
{
    if (!KELDYSH){ // used only for Matsubara calculations
        indices.conjugate ^= true;
        indices.w *= -1;
        if (INTERPOL2D_FOR_K3) {
            indices.iw_r = nBOS3 - 1 - indices.iw_r; // corresponds to "w *= -1"
        }
        if (MAX_DIAG_CLASS > 1) {
            indices.v1 *= -1;
            indices.v2 *= -1;
            if (!ZERO_T) { // Matsubara T>0
                double rounding_correction = signFlipCorrection_MF(indices.w);
                indices.v1 += rounding_correction;
                indices.v2 += rounding_correction;
            }
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), INTERPOL2D_FOR_K3, KELDYSH, MAX_DIAG_CLASS, nBOS3, signFlipCorrection_MF(), and ZERO_T.