SIAM-Keldysh-mfRG: Keldysh_symmetries.hpp File Reference
Keldysh_symmetries.hpp File Reference
#include <vector>
#include <algorithm>
#include "../data_structures.hpp"
#include "../utilities/util.hpp"
#include "../grids/frequency_grid.hpp"
Classes
struct buffer_config< _rank >
Keldysh index parameters ///.
Functions
const std::vector< int > glb_non_zero_Keldysh_bubble ({3, 6, 7, 9, 11, 12, 13, 14, 15})
const std::vector< int > odd_Keldysh ({1, 2, 4, 7, 8, 11, 13, 14})
template<typename T >
auto isInList (T val, const std::vector< T > &list) -> bool
auto convertToIndepIndex (int iK) -> int
auto iK_to_alphas (int index) -> std::array< int, 4 >
auto alphas_to_iK (const std::array< int, 4 > &alphas) -> int
template<char channel_bubble, typename I >
void get_i0_left_right (const my_index_t iK, I &i0_left, I &i0_right)
template<char channel_bubble, bool is_left_vertex>
auto rotate_Keldysh_matrix (const my_index_t iK) -> my_index_t
template<char channel_bubble, bool is_left_vertex>
auto unrotate_Keldysh_matrix (const my_index_t iK) -> my_index_t
auto indices_sum (int i0, int i2, const char channel) -> std::vector< int >
Variables
constexpr buffer_config< 3 > SE_config
constexpr buffer_config< 4 > K1at_config
constexpr buffer_config< 4 > K1p_config
constexpr buffer_config< 5 > K2at_config
constexpr buffer_config< 5 > K2p_config
constexpr buffer_config< 6 > K3_config
constexpr buffer_config< 3 > SE_expanded_config
constexpr buffer_config< 4 > K1_expanded_config
constexpr buffer_config< 5 > K2_expanded_config
constexpr buffer_config< 6 > K3_SBE_expanded_config
constexpr buffer_config< 6 > K3_expanded_config
constexpr unsigned int pos_first_freq = 1
constexpr int glb_number_of_Keldysh_components_bubble = 9
Function Documentation
alphas_to_iK()
auto alphas_to_iK (const std::array< int, 4 > & alphas) -> int
Definition at line 20 of file Keldysh_symmetries.c++.
{
    int base = 1;
    int iK = 0;
    for (int i = 0; i < 4; i++) {
        iK += (alphas[3-i] - 1) * base;
        base *= 2;
    }
    //alphas[0] = (index % 16)/8 + 1;
    //alphas[1] = (index % 8)/4 + 1;
    //alphas[2] = (index % 4)/2 + 1;
    //alphas[3] = (index % 2) + 1;
    assert(iK>=0);
    return iK;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by T1(), T2(), and TC().
convertToIndepIndex()
auto convertToIndepIndex (int iK) -> int
get_i0_left_right()
template<char channel_bubble, typename I > void get_i0_left_right (const my_index_t iK, I & i0_left, I & i0_right)
Definition at line 254 of file Keldysh_symmetries.hpp.
{
    constexpr std::array<I, 4> Keldysh4pointdims = {2,2,2,2};
    std::array<I ,4> alpha;
    getMultIndex(alpha, iK, Keldysh4pointdims);
    if constexpr(channel_bubble == 'a') {
        i0_left = alpha[0]*2 + alpha[3];
        i0_right= alpha[2]*2 + alpha[1];
    }
    else if constexpr(channel_bubble == 'p') {
        i0_left = alpha[0]*2 + alpha[1];
        i0_right= alpha[2]*2 + alpha[3];
    }
    else {
        static_assert(channel_bubble=='t', "Please use a, p or t for the channels.");
        i0_left = alpha[1]*2 + alpha[3];
        i0_right= alpha[2]*2 + alpha[0];
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and getMultIndex().
glb_non_zero_Keldysh_bubble()
const std::vector< int > glb_non_zero_Keldysh_bubble ({3, 6, 7, 9, 11, 12, 13, 14, 15})
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value().
iK_to_alphas()
auto iK_to_alphas (int index) -> std::array< int, 4 >
Definition at line 4 of file Keldysh_symmetries.c++.
{
    std::array<int,4> alphas;
    int base = 8;
    for (int i = 0; i < 4; i++) {
        alphas[i] = index / base;
        index -= alphas[i]*base;
        base /=2;
        alphas[i]++;
    }
    //alphas[0] = (index % 16)/8 + 1;
    //alphas[1] = (index % 8)/4 + 1;
    //alphas[2] = (index % 4)/2 + 1;
    //alphas[3] = (index % 2) + 1;
    return alphas;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by indices_sum(), T1(), T2(), and TC().
indices_sum()
auto indices_sum (int i0, int i2, const char channel) -> std::vector< int >
Function that returns, for an input i0, i2 in 0...15, the two Keldysh indices of the left [0] and right [1] vertices of a bubble in a given channel.
Parameters
i0 : Keldysh index of the lhs of a derivative equation for the vertex
i2 : Keldysh index of the non-zero components of the bubble propagators (takes values in a set of size 9)
channel : channel of the bubble
Returns
: Vector of two Keldysh indices for the left [0] and right [1] vertex in a bubble
Definition at line 35 of file Keldysh_symmetries.c++.
{
    std::vector<int> indices ({0, 0});           // Return std::vector, already correct for Matsubara
    if (KELDYSH){
        std::array<int,4> alphas_i0 = iK_to_alphas(i0);   // Calculate the alphas of each input. Refer to these alphas as (1'2'|12)
        std::array<int,4> alphas_i2 = iK_to_alphas(i2);   // Calculate the alphas of each input. Refer to these alphas as (34|3'4')
        //Distribute the alphas of indices i0 and i2 into i1 and i3
        switch (channel) {
            case 'a':
                indices[0] = 8*(alphas_i0[0]-1) + 4*(alphas_i2[3]-1) + 2*(alphas_i2[0]-1) + 1*(alphas_i0[3]-1);  // i1 = (1'4'|32)
                indices[1] = 8*(alphas_i2[2]-1) + 4*(alphas_i0[1]-1) + 2*(alphas_i0[2]-1) + 1*(alphas_i2[1]-1);  // i3 = (3'2'|14)
                break;
            case 'p':
                indices[0] = 8*(alphas_i0[0]-1) + 4*(alphas_i0[1]-1) + 2*(alphas_i2[0]-1) + 1*(alphas_i2[1]-1);  // i1 = (1'2'|34)
                indices[1] = 8*(alphas_i2[2]-1) + 4*(alphas_i2[3]-1) + 2*(alphas_i0[2]-1) + 1*(alphas_i0[3]-1);  // i3 = (3'4'|12)
                break;
            case 't':
                indices[0] = 8*(alphas_i2[3]-1) + 4*(alphas_i0[1]-1) + 2*(alphas_i2[0]-1) + 1*(alphas_i0[3]-1);  // i1 = (4'2'|32)
                indices[1] = 8*(alphas_i0[0]-1) + 4*(alphas_i2[2]-1) + 2*(alphas_i0[2]-1) + 1*(alphas_i2[1]-1);  // i3 = (1'3'|14)
                break;
            default:;
        }
    }
    return indices;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), iK_to_alphas(), and KELDYSH.
Referenced by asymp_corrections_bubble(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::compute_vertices(), and Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::precompute_vertices().
isInList()
template<typename T > auto isInList (T val, const std::vector< T > & list) -> bool
Definition at line 239 of file Keldysh_symmetries.hpp.
{
    return (std::find(list.begin(), list.end(), val) != list.end());
}
Referenced by TC(), and Tph().
odd_Keldysh()
const std::vector< int > odd_Keldysh ({1, 2, 4, 7, 8, 11, 13, 14})
Referenced by irreducible< Q >::initialize(), TC(), and Tph().
rotate_Keldysh_matrix()
template<char channel_bubble, bool is_left_vertex> auto rotate_Keldysh_matrix (const my_index_t iK) -> my_index_t
Definition at line 275 of file Keldysh_symmetries.hpp.
{
    constexpr std::array<my_index_t, 4> Keldysh4pointdims = {2,2,2,2};
    std::array<my_index_t ,4> alpha;
    getMultIndex(alpha, iK, Keldysh4pointdims);
    my_index_t i0_left, i0_right;
    if constexpr(channel_bubble == 'a') {
        if constexpr(is_left_vertex) {
            i0_left  = alpha[0] * 2 + alpha[3];
            i0_right = alpha[2] * 2 + alpha[1];
        }
        else {
            i0_left  = alpha[2] * 2 + alpha[1];
            i0_right = alpha[0] * 2 + alpha[3];
        }
    }
    else if constexpr(channel_bubble == 'p') {
        if constexpr(is_left_vertex) {
            i0_left = alpha[0]*2 + alpha[1];
            i0_right= alpha[2]*2 + alpha[3];
        }
        else {
            i0_left = alpha[2]*2 + alpha[3];
            i0_right= alpha[0]*2 + alpha[1];
        }
    }
    else {
        static_assert(channel_bubble=='t', "Please use a, p or t for the channels.");
        if constexpr(is_left_vertex) {
            i0_left  = alpha[3] * 2 + alpha[0];
            i0_right = alpha[2] * 2 + alpha[1];
        }
        else {
            i0_left  = alpha[1] * 2 + alpha[2];
            i0_right = alpha[0] * 2 + alpha[3];
        }
    }
    const my_index_t iK_read = i0_left * 4 + i0_right;
    assert(iK_read < 16);
    return iK_read;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and getMultIndex().
unrotate_Keldysh_matrix()
template<char channel_bubble, bool is_left_vertex> auto unrotate_Keldysh_matrix (const my_index_t iK) -> my_index_t
Definition at line 322 of file Keldysh_symmetries.hpp.
{
    constexpr std::array<my_index_t, 4> Keldysh4pointdims = {2,2,2,2};
    std::array<my_index_t ,4> alpha;
    getMultIndex(alpha, iK, Keldysh4pointdims);
    my_index_t i0_left, i0_right;
    if constexpr(channel_bubble == 'a') {
        if constexpr(is_left_vertex) {
            i0_left  = alpha[0] * 2 + alpha[3];
            i0_right = alpha[2] * 2 + alpha[1];
        }
        else {
            i0_left  = alpha[2] * 2 + alpha[1];
            i0_right = alpha[0] * 2 + alpha[3];
        }
    }
    else if constexpr(channel_bubble == 'p') {
        if constexpr(is_left_vertex) {
            i0_left = alpha[0]*2 + alpha[1];
            i0_right= alpha[2]*2 + alpha[3];
        }
        else {
            i0_left = alpha[2]*2 + alpha[3];
            i0_right= alpha[0]*2 + alpha[1];
        }
    }
    else {
        static_assert(channel_bubble=='t', "Please use a, p or t for the channels.");
        if constexpr(is_left_vertex) {
            i0_left  = alpha[1] * 2 + alpha[3];
            i0_right = alpha[2] * 2 + alpha[0];
        }
        else {
            i0_left  = alpha[2] * 2 + alpha[0];
            i0_right = alpha[1] * 2 + alpha[3];
        }
    }
    const my_index_t iK_read = i0_left * 4 + i0_right;
    assert(iK_read < 16);
    return iK_read;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and getMultIndex().
Variable Documentation
glb_number_of_Keldysh_components_bubble
constexpr int glb_number_of_Keldysh_components_bubble = 9 constexpr
Definition at line 178 of file Keldysh_symmetries.hpp.
K1_expanded_config
constexpr buffer_config<4> K1_expanded_config constexpr
Initial value:
{
    std::array<size_t,4>({1, nBOS, KELDYSH ?  16 : 1, n_in})
    , 1
    , 1}
Definition at line 144 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,4>({1, nBOS, KELDYSH ?  16 : 1, n_in})
    , 1  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by rvert< Q >::symmetry_expand().
K1at_config
constexpr buffer_config<4> K1at_config constexpr
Initial value:
{
    std::array<size_t,4>({n_spin, nBOS, KELDYSH ? 16 : 1, n_in})
    , 1
    , 1}
Definition at line 39 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,4>({n_spin, nBOS, KELDYSH ? 16 : 1, n_in})
    , 1  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by check_FDTs_K1(), and rvert< Q >::rvert().
K1p_config
constexpr buffer_config<4> K1p_config constexpr
Initial value:
{
    std::array<size_t,4>({n_spin, nBOS, KELDYSH ? 16 : 1, n_in})
    , 1
    , 1}
Definition at line 43 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,4>({n_spin, nBOS, KELDYSH ? 16 : 1, n_in})
    , 1  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by rvert< Q >::rvert().
K2_expanded_config
constexpr buffer_config<5> K2_expanded_config constexpr
Initial value:
{
    std::array<size_t,5>({1, nBOS2, nFER2, KELDYSH ?  16 : 1, n_in})
    , 2
    , 1}
Definition at line 148 of file Keldysh_symmetries.hpp.
{
#if MAX_DIAG_CLASS >=2
    std::array<size_t,5>({1, nBOS2, nFER2, KELDYSH ?  16 : 1, n_in})
#else
    std::array<size_t,5>({1, 0, 0, KELDYSH ?  16 : 1, n_in_K2})
#endif
    , 2  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by rvert< Q >::symmetry_expand().
K2at_config
constexpr buffer_config<5> K2at_config constexpr
Initial value:
{
    std::array<size_t,5>({n_spin, nBOS2, nFER2, KELDYSH ? 16 : 1, n_in})
    , 2
    , 1}
Definition at line 47 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,5>({n_spin, nBOS2, nFER2, KELDYSH ? 16 : 1, n_in})
    , 2  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by rvert< Q >::rvert().
K2p_config
constexpr buffer_config<5> K2p_config constexpr
Initial value:
{
    std::array<size_t,5>({n_spin, nBOS2, nFER2, KELDYSH ? 16 : 1, n_in})
    , 2
    , 1}
Definition at line 51 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,5>({n_spin, nBOS2, nFER2, KELDYSH ? 16 : 1, n_in})
    , 2  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by rvert< Q >::rvert().
K3_config
constexpr buffer_config<6> K3_config constexpr
Initial value:
{
    std::array<size_t,6>({n_spin, nBOS3, nFER3, GRID!=2 ? nFER3 : (nFER3-1)/2+1, KELDYSH ? 16 : 1, n_in})
    , 3
    , 1}
Definition at line 55 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,6>({n_spin, nBOS3, nFER3, GRID!=2 ? nFER3 : (nFER3-1)/2+1, KELDYSH ? 16 : 1, n_in})
    , 3  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by FrequencyGrid< angularGrid >::guess_essential_parameters(), and rvert< Q >::rvert().
K3_expanded_config
constexpr buffer_config<6> K3_expanded_config constexpr
Initial value:
{
    std::array<size_t,6>({1, nBOS3, nFER3, GRID!=2 ? nFER3 : (nFER3-1)/2+1, KELDYSH ?  16 : 1, n_in})
    , 3
    , 1}
Definition at line 164 of file Keldysh_symmetries.hpp.
{
#if MAX_DIAG_CLASS == 3
    std::array<size_t,6>({1, nBOS3, nFER3, GRID!=2 ? nFER3 : (nFER3-1)/2+1, KELDYSH ?  16 : 1, n_in})
#else
    std::array<size_t,6>({1, 0, 0, 0, KELDYSH ? 16 : 1, n_in_K3})
#endif
    , 3  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by rvert< Q >::symmetry_expand().
K3_SBE_expanded_config
constexpr buffer_config<6> K3_SBE_expanded_config constexpr
Initial value:
{
        std::array<size_t,6>({1, nBOS2, nFER2, GRID!=2 ? nFER2 : (nFER2-1)/2+1, KELDYSH ?  16 : 1, n_in})
        , 3
        , 1}
Definition at line 156 of file Keldysh_symmetries.hpp.
{
#if MAX_DIAG_CLASS >= 2
        std::array<size_t,6>({1, nBOS2, nFER2, GRID!=2 ? nFER2 : (nFER2-1)/2+1, KELDYSH ?  16 : 1, n_in})
#else
        std::array<size_t,6>({1, 0, 0, 0, KELDYSH ? 16 : 1, n_in_K3})
#endif
        , 3  // number of frequency dimensions
        , 1};// position of first frequency index
Referenced by rvert< Q >::combine_SBE_to_K3_SBE().
pos_first_freq
constexpr unsigned int pos_first_freq = 1 constexpr
Definition at line 173 of file Keldysh_symmetries.hpp.
SE_config
constexpr buffer_config<3> SE_config constexpr
Initial value:
{
    std::array<size_t,3>({KELDYSH ? 4 : 1, nFER, n_in})
    , 1
    , 1}
Definition at line 35 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,3>({KELDYSH ? 4 : 1, nFER, n_in})
    , 1  // number of frequency dimensions
    , 1};// position of first frequency index
Referenced by check_FDTs_selfenergy(), and Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl().
SE_expanded_config
constexpr buffer_config<3> SE_expanded_config constexpr
Initial value:
{
    std::array<size_t,3>({ KELDYSH ?  4 : 1, nFER, n_in})
    , 1
    , 1}
Definition at line 140 of file Keldysh_symmetries.hpp.
{
    std::array<size_t,3>({ KELDYSH ?  4 : 1, nFER, n_in})
    , 1  // number of frequency dimensions
    , 1};// position of first frequency index