SIAM-Keldysh-mfRG: IndicesSymmetryTransformations Struct Reference
IndicesSymmetryTransformations Struct Reference
#include <data_structures.hpp>
Public Member Functions
IndicesSymmetryTransformations (int iK_in, my_index_t spin_in, double w_in, double v1_in, double v2_in, my_index_t i_in_in, char channel_rvert_in, K_class k_in, my_index_t iw_in, char channel_bubble_in)
IndicesSymmetryTransformations (VertexInput input, char channel_in)
IndicesSymmetryTransformations (VertexInput &&input, char channel_in)
Public Member Functions inherited from VertexInput
VertexInput (int iK_in, my_index_t spin_in, freqType w_in, freqType v1_in, freqType v2_in, my_index_t i_in_in, char channel_in, K_class k_in=k1, my_index_t iw_in=0)
template<K_class k>
auto get_freqs () const
template<K_class k>
auto get_indices () const
Public Attributes
double prefactor = 1.
bool conjugate = false
bool asymmetry_transform = false
char channel_rvert
Public Attributes inherited from VertexInput
int iK
freqType w
freqType v1
freqType v2
my_index_t i_in
my_index_t spin
char channel_bubble
K_class kClass_aim
my_index_t iw_r
Detailed Description
specifies the diagrammatic contribution (+ modifications by prefactor, complex conjugation)
Definition at line 621 of file data_structures.hpp.
Constructor & Destructor Documentation
IndicesSymmetryTransformations() [1/3]
IndicesSymmetryTransformations::IndicesSymmetryTransformations (int iK_in, my_index_t spin_in, double w_in, double v1_in, double v2_in, my_index_t i_in_in, char channel_rvert_in, K_class k_in, my_index_t iw_in, char channel_bubble_in) inline
Definition at line 632 of file data_structures.hpp.
            : VertexInput(iK_in, spin_in, w_in, v1_in, v2_in, i_in_in, channel_bubble_in, k_in, iw_in), channel_rvert(channel_rvert_in)
    {assert(iK < 16);}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and VertexInput::iK.
IndicesSymmetryTransformations() [2/3]
IndicesSymmetryTransformations::IndicesSymmetryTransformations (VertexInput input, char channel_in) inline
Definition at line 636 of file data_structures.hpp.
            : VertexInput(input), channel_rvert(channel_in)
    {assert(iK < 16);}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and VertexInput::iK.
IndicesSymmetryTransformations() [3/3]
IndicesSymmetryTransformations::IndicesSymmetryTransformations (VertexInput && input, char channel_in) inline
Definition at line 639 of file data_structures.hpp.
            : VertexInput(input), channel_rvert(channel_in)
    {assert(iK < 16);}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and VertexInput::iK.
Member Data Documentation
asymmetry_transform
bool IndicesSymmetryTransformations::asymmetry_transform = false
Definition at line 625 of file data_structures.hpp.
channel_rvert
char IndicesSymmetryTransformations::channel_rvert
Definition at line 630 of file data_structures.hpp.
conjugate
bool IndicesSymmetryTransformations::conjugate = false
Definition at line 624 of file data_structures.hpp.
prefactor
double IndicesSymmetryTransformations::prefactor = 1.
Definition at line 623 of file data_structures.hpp.
The documentation for this struct was generated from the following file:
data_structures.hpp