SIAM-Keldysh-mfRG: IntegrandBubble< Q > Class Template Reference
IntegrandBubble< Q > Class Template Reference
#include <integrand.hpp>
Public Member Functions
IntegrandBubble (const Propagator< Q > &g1_in, const Propagator< Q > &g2_in, bool diff_in, freqType w_in, int iK_in, char channel_in)
auto operator() (freqType vpp) const -> Q
Private Attributes
const Propagator< Q > & g1
const Propagator< Q > & g2
bool diff
freqType w
int iK
const char channel
Detailed Description
template<typename Q>
class IntegrandBubble< Q >
TODO: write move constructor (necessary for move in PAID integrator) TODO: write vectorized variant of integrand Possible (unit-)tests for operations: move, call [MISSING] copy integrand, perform move and compare with copy [IMPLEMENTED in test_PT_state()] compute bubble and compare with known result check combination of vertices and propagators and internal sum over indices [IMPLEMENTED in integrand_tets/...] load vertices and selfenergies from file and output integrands to hdf5 file [MISSING] output integrand without and with internal sum, then compare the output (are they identical?)
Definition at line 31 of file integrand.hpp.
Constructor & Destructor Documentation
IntegrandBubble()
template<typename Q > IntegrandBubble< Q >::IntegrandBubble (const Propagator< Q > & g1_in, const Propagator< Q > & g2_in, bool diff_in, freqType w_in, int iK_in, char channel_in) inline
Constructor for the IntegrandBubble
Parameters
g1_in : Propagator object for the lower (right) leg
g2_in : Propagator object for the upper (left) leg
diff_in : Boolean defining whether bubble is differentiated or not
w_in : Transfer frequency at which the bubble should be integrated
iK_in : Keldysh index to be taken
channel_in Char indicating the channel in which the bubble should be calculated and which determines the frequency transformations
Definition at line 49 of file integrand.hpp.
            : g1(g1_in), g2(g2_in), diff(diff_in), w(w_in), iK(iK_in), channel(channel_in) {};
Member Function Documentation
operator()()
template<typename Q > auto IntegrandBubble< Q >::operator() (freqType vpp) const -> Q inline
Call operator
Parameters
vpp : v'', the frequency over which is being integrated
Returns
The value g1(v1)*g2(v2), where v1 and v2 are calculated according to the channel. The components of the propagators taken depend on the Keldysh component
Definition at line 58 of file integrand.hpp.
{
        Q ans;
        freqType v1, v2;
        Bubble<Q> Pi(g1, g2, diff);
        switch(channel){
            case 'p':
                v1 = w/2.+vpp;
                v2 = w/2.-vpp;
                break;
            case 'a': case 't':
                v1 = vpp-w/2.;
                v2 = vpp+w/2.;
                break;
            default:
                v1 = 0.;
                v2 = 0.;
                utils::print("Error in IntegrandBubble! Abort.");
                assert(false);
        }
        //Make reference to the Bubble object of the actual code, making this into a useful test of code correctnes and compliance
        return Pi.value(iK, v1, v2, 0)/(2.*M_PI*glb_i);
    }
References IntegrandBubble< Q >::channel, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), IntegrandBubble< Q >::diff, IntegrandBubble< Q >::g1, IntegrandBubble< Q >::g2, glb_i(), IntegrandBubble< Q >::iK, utils::print(), Bubble< Q >::value(), and IntegrandBubble< Q >::w.
Member Data Documentation
channel
template<typename Q > const char IntegrandBubble< Q >::channel private
Definition at line 37 of file integrand.hpp.
Referenced by IntegrandBubble< Q >::operator()().
diff
template<typename Q > bool IntegrandBubble< Q >::diff private
Definition at line 34 of file integrand.hpp.
Referenced by IntegrandBubble< Q >::operator()().
g1
template<typename Q > const Propagator<Q>& IntegrandBubble< Q >::g1 private
Definition at line 32 of file integrand.hpp.
Referenced by IntegrandBubble< Q >::operator()().
g2
template<typename Q > const Propagator<Q>& IntegrandBubble< Q >::g2 private
Definition at line 33 of file integrand.hpp.
Referenced by IntegrandBubble< Q >::operator()().
iK
template<typename Q > int IntegrandBubble< Q >::iK private
Definition at line 36 of file integrand.hpp.
Referenced by IntegrandBubble< Q >::operator()().
w
template<typename Q > freqType IntegrandBubble< Q >::w private
Definition at line 35 of file integrand.hpp.
Referenced by IntegrandBubble< Q >::operator()().
The documentation for this class was generated from the following file:
integrand.hpp