SIAM-Keldysh-mfRG: SelfEnergy< Q > Class Template Reference
SelfEnergy< Q > Class Template Reference
TODO: Use Vertex buffer for self-energy.
#include <selfenergy.hpp>
Public Types
using freqGrid_type = bufferFrequencyGrid<selfenergy>
using buffer_type = dataBuffer<Q, selfenergy, SE_config.rank, SE_config.num_freqs, SE_config.position_first_freq_index, freqGrid_type, INTERPOLATION>
using frequencies_type = std::array<double,1>
using index_type = std::array<my_index_t, SE_config.rank>
Public Member Functions
SelfEnergy (double Lambda, const fRG_config &config)
SelfEnergy (const freqGrid_type &frequencies_in)
void initialize (Q valR, Q valK)
auto val (int iK, int iv, int i_in) const -> Q
auto valsmooth (int iK, double v, int i_in) const -> Q
void setself (int iK, int iv, int i_in, Q val)
void addself (int iK, int iv, int i_in, Q val)
auto acc (int i) const -> Q
void direct_set (int i, Q val)
void set_frequency_grid (const SelfEnergy< Q > selfEnergy)
auto norm (int p) const -> double
auto norm () const -> double
auto rel_deviation_to (const SelfEnergy< Q > &base) const -> double
auto get_selfenergy_vector_incl_hartree () const -> Eigen::Array< Q, Eigen::Dynamic, 1 >
void update_grid (double Lambda, const fRG_config &config)
Interpolate self-energy to updated grid whose grid parameters are multiples of Delta = (Lambda + Gamma)/2.
void update_grid (const freqGrid_type &frequencies_new)
Interpolate self-energy to input grid.
void update_grid (const freqGrid_type &frequencies_new, SelfEnergy< Q > selfEnergy4Sigma)
Interpolate self-energy to input grid with Sigma given by selfEnergy4Sigma.
void findBestFreqGrid (bool verbose)
finds optimal grid parameters with minimizer()
auto shrink_freq_box (double rel_tail_threshold) const -> freqGrid_type
double analyze_tails (bool verbose) const
double get_deriv_maxSE (bool verbose) const
computes finite differences of Sigma
double get_curvature_maxSE (bool verbose) const
auto operator+= (const SelfEnergy< Q > &self1) -> SelfEnergy< Q >
template<typename Qfac >
auto operator+= (Qfac alpha) -> SelfEnergy< Q >
template<typename Qfac >
auto operator*= (Qfac alpha) -> SelfEnergy< Q >
auto operator-= (const SelfEnergy< Q > &self1) -> SelfEnergy< Q >
auto operator/= (const SelfEnergy< Q > &self1) -> SelfEnergy< Q >
Elementwise division (needed for error estimate of adaptive ODE solvers)
void check_resolution () const
void check_symmetries () const
Public Attributes
buffer_type Sigma
Q asymp_val_R = 0.
Friends
SelfEnergy< Q > operator+ (SelfEnergy< Q > lhs, const SelfEnergy< Q > &rhs)
template<typename Qfac >
SelfEnergy< Q > operator+ (SelfEnergy< Q > lhs, const Qfac &rhs)
template<typename Qfac >
SelfEnergy< Q > operator+ (const Qfac &rhs, SelfEnergy< Q > lhs)
template<typename Qfac >
SelfEnergy< Q > operator* (SelfEnergy< Q > lhs, const Qfac &rhs)
template<typename Qfac >
SelfEnergy< Q > operator* (const Qfac &rhs, SelfEnergy< Q > lhs)
SelfEnergy< Q > operator- (SelfEnergy< Q > lhs, const SelfEnergy< Q > &rhs)
SelfEnergy< Q > operator/ (SelfEnergy< Q > lhs, const SelfEnergy< Q > &rhs)
Detailed Description
template<typename Q>
class SelfEnergy< Q >
TODO: Use Vertex buffer for self-energy.
Definition at line 18 of file selfenergy.hpp.
Member Typedef Documentation
buffer_type
template<typename Q > using SelfEnergy< Q >::buffer_type = dataBuffer<Q, selfenergy, SE_config.rank, SE_config.num_freqs, SE_config.position_first_freq_index, freqGrid_type, INTERPOLATION>
Definition at line 21 of file selfenergy.hpp.
freqGrid_type
template<typename Q > using SelfEnergy< Q >::freqGrid_type = bufferFrequencyGrid<selfenergy>
Definition at line 20 of file selfenergy.hpp.
frequencies_type
template<typename Q > using SelfEnergy< Q >::frequencies_type = std::array<double,1>
Definition at line 22 of file selfenergy.hpp.
index_type
template<typename Q > using SelfEnergy< Q >::index_type = std::array<my_index_t, SE_config.rank>
Definition at line 23 of file selfenergy.hpp.
Constructor & Destructor Documentation
SelfEnergy() [1/2]
template<typename Q > SelfEnergy< Q >::SelfEnergy (double Lambda, const fRG_config & config) inline explicit
Definition at line 34 of file selfenergy.hpp.
: Sigma(Lambda, SE_config.dims, config) {};
SelfEnergy() [2/2]
template<typename Q > SelfEnergy< Q >::SelfEnergy (const freqGrid_type & frequencies_in) inline explicit
Definition at line 35 of file selfenergy.hpp.
: Sigma(0, SE_config.dims, fRG_config()) {Sigma.set_VertexFreqGrid(frequencies_in);};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and SelfEnergy< Q >::Sigma.
Member Function Documentation
acc()
template<typename Q > auto SelfEnergy< Q >::acc (int i) const -> Q
Access function to element i (hdf5-relevant)
Template Parameters
Q : Type of values (usually comp)
Parameters
i : Index
Returns
Sigma[i]
Definition at line 177 of file selfenergy.hpp.
{
    if(i>=0 && i < Sigma.size()) return Sigma.acc(i);
    else {utils::print("Error: Tried to access value outside of self-energy range. Abort."); assert(false);}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
addself()
template<typename Q > void SelfEnergy< Q >::addself (int iK, int iv, int i_in, Q val)
Adds the given value at the specified location
Template Parameters
Q : Type of values (usually comp)
Parameters
iK : Keldysh index (either 0 or 1)
iv : Frequency index
i_in : Internal index
val : Value of the self-energy at this given point
Definition at line 242 of file selfenergy.hpp.
{
     Sigma.setvert(val+Sigma.at(iK, iv, i_in), iK, iv, i_in);
}
Referenced by LoopCalculator< Q, vertType, all_spins, version >::compute_Keldysh(), and loop().
analyze_tails()
template<typename Q > double SelfEnergy< Q >::analyze_tails (bool verbose) const
Definition at line 325 of file selfenergy.hpp.
{
    buffer_type Sigma_temp = Sigma;
    //if(KELDYSH) for (int i = 0; i < Sigma.get_vec().size()/2; i++) Sigma_temp.direct_set(i, Sigma_temp.acc(i) - asymp_val_R);
    //else for (int i = 0; i < Sigma.get_vec().size(); i++) Sigma_temp.direct_set(i, Sigma_temp.acc(i) - asymp_val_R);
    double maxabs_SE_total = Sigma_temp.get_vec().max_norm();
    vec<double> maxabsSE_along_w = maxabs(Sigma_temp.get_vec(), Sigma_temp.get_dims(), 1);
    double result = maxabsSE_along_w[0] / maxabs_SE_total;
    if (verbose and mpi_world_rank() == 0)
    {
        std::cout << "rel. magnitude of tails in self energy :";
        std::cout << "\t\t" << result << std::endl;
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), maxabs(), and mpi_world_rank().
check_resolution()
template<typename Q > void SelfEnergy< Q >::check_resolution () const
TODO: dump state in file if certain thresholds are exceeded
Definition at line 397 of file selfenergy.hpp.
{
    double derivmax_SE = get_deriv_maxSE(true);
    double curvmax_SE = get_curvature_maxSE(true);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
check_symmetries()
template<typename Q > void SelfEnergy< Q >::check_symmetries () const
Definition at line 407 of file selfenergy.hpp.
{
    if (PARTICLE_HOLE_SYMMETRY) {
        vec<Q> dev(nFER);
        for (int i = 0; i < nFER; i++) {
            for (int j = 0; j < n_in; j++) {
                freqType v;
                Sigma.frequencies.get_freqs_w(v, i);
                dev[i] = valsmooth(0, v, j) + myconj(valsmooth(0,-v, j)) - 2.*asymp_val_R;
            }
        }
        utils::print("Maximal deviation from PHS: ", dev.max_norm(), "\n");
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), myconj(), n_in, nFER, PARTICLE_HOLE_SYMMETRY, and utils::print().
direct_set()
template<typename Q > void SelfEnergy< Q >::direct_set (int i, Q val)
Set value of self-energy at index i
Template Parameters
Q : Type of values (usually comp)
Parameters
i : Index
val Value
Definition at line 188 of file selfenergy.hpp.
{
    if(i>=0 && i < Sigma.get_vec().size()) Sigma.direct_set(i, val);
    else {utils::print("Error: Tried to access value outside of self-energy range. Abort."); assert(false);}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
findBestFreqGrid()
template<typename Q > void SelfEnergy< Q >::findBestFreqGrid (bool verbose)
finds optimal grid parameters with minimizer()
Definition at line 314 of file selfenergy.hpp.
{
    Sigma.optimize_grid(verbose);
}
Referenced by State< Q, differentiated >::findBestFreqGrid().
get_curvature_maxSE()
template<typename Q > auto SelfEnergy< Q >::get_curvature_maxSE (bool verbose) const
Definition at line 380 of file selfenergy.hpp.
{
    //vec<Q> Sigma_temp = Sigma;
    //if(KELDYSH) for (int i = 0; i < Sigma.size()/2; i++) Sigma_temp -= asymp_val_R;
    //else for (int i = 0; i < Sigma.size(); i++) Sigma_temp -= asymp_val_R;
    double max_SE = Sigma.get_curvature_max();
    if (verbose and mpi_world_rank() == 0) {
        std::cout << "max. Curvature in SE:";
        std::cout << "\t  \t" << max_SE << std::endl;
    }
    return max_SE;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_deriv_maxSE()
template<typename Q > auto SelfEnergy< Q >::get_deriv_maxSE (bool verbose) const
computes finite differences of Sigma
Definition at line 367 of file selfenergy.hpp.
{
    //vec<Q> Sigma_temp = Sigma;
    //if(KELDYSH) for (int i = 0; i < Sigma.size()/2; i++) Sigma_temp -= asymp_val_R;
    //else for (int i = 0; i < Sigma.size(); i++) Sigma_temp -= asymp_val_R;
    double max_SE = Sigma.get_deriv_max();
    if (verbose and mpi_world_rank() == 0) {
        std::cout << "max. Derivative in selfenergy:" << std::endl;
        std::cout << "\t  \t" << max_SE << std::endl;
    }
    return max_SE;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_selfenergy_vector_incl_hartree()
template<typename Q > auto SelfEnergy< Q >::get_selfenergy_vector_incl_hartree () const -> Eigen::Array<Q, Eigen::Dynamic, 1> inline
Definition at line 49 of file selfenergy.hpp.
{
        Eigen::Array<Q, Eigen::Dynamic, 1> result = Sigma.get_vec().elements;
        result.head(nFER) += asymp_val_R;
        return result;
    }
References SelfEnergy< Q >::asymp_val_R, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), nFER, and SelfEnergy< Q >::Sigma.
initialize()
template<typename Q > void SelfEnergy< Q >::initialize (Q valR, Q valK)
Function initializes the Retarded and Keldysh components of the self-energy
Template Parameters
Q : Type of values (usually comp)
Parameters
valR : Value for the constant Retarded self-energy
valK : Value for the constant Keldysh self-energy
Definition at line 153 of file selfenergy.hpp.
{
    // in particle-hole symmetric_full case (Matsubara formalism) the self-energy vector only stores the imaginary part -> initialize to zero
    // in all other cases: initialize to the Hartree value
    this-> asymp_val_R = valR;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Hartree_Solver::Hartree_Solver(), Hartree_Solver::Hartree_Solver(), and State< Q, differentiated >::initialize().
norm() [1/2]
template<typename Q > auto SelfEnergy< Q >::norm () const -> double
Definition at line 359 of file selfenergy.hpp.
{
    return this->norm(0);
}
norm() [2/2]
template<typename Q > auto SelfEnergy< Q >::norm (int p) const -> double
Definition at line 346 of file selfenergy.hpp.
{
    if(p==0){ //max norm
        double max = std::max(Sigma.get_vec().max_norm(), std::abs(asymp_val_R));
        return max;
    }
    else{ //p-norm
        double result = Sigma.get_vec().get_elements().abs().pow(p).sum() + pow(std::abs(asymp_val_R), p);
        return pow(result, 1/(double)p);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by check_FDTs_selfenergy(), and rhs_n_loop_flow().
operator*=()
template<typename Q > template<typename Qfac > auto SelfEnergy< Q >::operator*= (Qfac alpha) -> SelfEnergy<Q> inline
Definition at line 96 of file selfenergy.hpp.
{
        this->Sigma *= alpha;
        this->asymp_val_R *= alpha;
        return *this;
    }
operator+=() [1/2]
template<typename Q > auto SelfEnergy< Q >::operator+= (const SelfEnergy< Q > & self1) -> SelfEnergy<Q> inline
Definition at line 71 of file selfenergy.hpp.
                                                                  {//sum operator overloading
        this->Sigma += self1.Sigma;
        this->asymp_val_R += self1.asymp_val_R;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+=() [2/2]
template<typename Q > template<typename Qfac > auto SelfEnergy< Q >::operator+= (Qfac alpha) -> SelfEnergy<Q> inline
Definition at line 81 of file selfenergy.hpp.
{
        this->Sigma += alpha;
        return *this;
    }
operator-=()
template<typename Q > auto SelfEnergy< Q >::operator-= (const SelfEnergy< Q > & self1) -> SelfEnergy<Q> inline
Definition at line 119 of file selfenergy.hpp.
                                                                  {//sum operator overloading
        this->Sigma -= self1.Sigma;
        this->asymp_val_R -= self1.asymp_val_R;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/=()
template<typename Q > auto SelfEnergy< Q >::operator/= (const SelfEnergy< Q > & self1) -> SelfEnergy<Q> inline
Elementwise division (needed for error estimate of adaptive ODE solvers)
Definition at line 129 of file selfenergy.hpp.
                                                                  {//sum operator overloading
        this->Sigma /= self1.Sigma;
        this->asymp_val_R /= self1.asymp_val_R;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
rel_deviation_to()
template<typename Q > auto SelfEnergy< Q >::rel_deviation_to (const SelfEnergy< Q > & base) const -> double
Definition at line 362 of file selfenergy.hpp.
{
    return std::max(Sigma.get_vec().max_norm() / base.Sigma.get_vec().max_norm(), std::abs(asymp_val_R / base.asymp_val_R));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
set_frequency_grid()
template<typename Q > void SelfEnergy< Q >::set_frequency_grid (const SelfEnergy< Q > selfEnergy)
Definition at line 246 of file selfenergy.hpp.
{
    Sigma.frequencies = selfEnergy.Sigma.frequencies;
};
References SelfEnergy< Q >::Sigma.
Referenced by State< Q, differentiated >::set_frequency_grid().
setself()
template<typename Q > void SelfEnergy< Q >::setself (int iK, int iv, int i_in, Q val)
Sets the value of the self-energy to a specific value at the specified location
Template Parameters
Q : Type of values (usually comp)
Parameters
iK : Keldysh index (either 0 or 1)
iv : Frequency index
i_in : Internal index
val : Value of the self-energy at this given point
Definition at line 230 of file selfenergy.hpp.
{
    Sigma.setvert(val, iK, iv, i_in);
}
Referenced by LoopCalculator< Q, vertType, all_spins, version >::compute_Keldysh(), LoopCalculator< Q, vertType, all_spins, version >::compute_Matsubara_finiteT(), and LoopCalculator< Q, vertType, all_spins, version >::compute_Matsubara_zeroT().
shrink_freq_box()
template<typename Q > auto SelfEnergy< Q >::shrink_freq_box (double rel_tail_threshold) const -> freqGrid_type
Definition at line 319 of file selfenergy.hpp.
{
    freqGrid_type frequencies_new = Sigma.shrink_freq_box(rel_tail_threshold, false, 0.);
    return frequencies_new;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
update_grid() [1/3]
template<typename Q > void SelfEnergy< Q >::update_grid (const freqGrid_type & frequencies_new)
Interpolate self-energy to input grid.
Definition at line 255 of file selfenergy.hpp.
{
    Sigma.update_grid(frequencies_new, Sigma);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
update_grid() [2/3]
template<typename Q > void SelfEnergy< Q >::update_grid (const freqGrid_type & frequencies_new, SelfEnergy< Q > selfEnergy4Sigma)
Interpolate self-energy to input grid with Sigma given by selfEnergy4Sigma.
Definition at line 261 of file selfenergy.hpp.
{
    Sigma.update_grid(frequencies_new, selfEnergy4Sigma.Sigma);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
update_grid() [3/3]
template<typename Q > void SelfEnergy< Q >::update_grid (double Lambda, const fRG_config & config)
Interpolate self-energy to updated grid whose grid parameters are multiples of Delta = (Lambda + Gamma)/2.
Definition at line 250 of file selfenergy.hpp.
{
    Sigma.update_grid(Lambda, {0.,0.,0.}, config);
}
References dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::update_grid().
Referenced by State< Q, differentiated >::update_grid().
val()
template<typename Q > auto SelfEnergy< Q >::val (int iK, int iv, int i_in) const -> Q
Returns the saved value of the self-energy
Template Parameters
Q : Type of values (usually comp)
Parameters
iK : Keldysh index (either 0 or 1)
iv : Frequency index
i_in : Internal structure index
Returns
The value of SigmaR/K at the chosen indices
Definition at line 167 of file selfenergy.hpp.
{
    return Sigma.val(iK, iv, i_in);
}
Referenced by loop().
valsmooth()
template<typename Q > auto SelfEnergy< Q >::valsmooth (int iK, double v, int i_in) const -> Q
Linear interpolating function returning the value of the Retarded or Keldysh self-energy at freq v
Template Parameters
Q : Type of values (usually comp)
Parameters
iK : Keldysh index (either 0 or 1)
v : Frequency
i_in : Internal index
Returns
: Interpolated value using the saved values as basis
Definition at line 201 of file selfenergy.hpp.
                                                                                         {//smoothly interpolates for values between discrete frequency values of mesh
    if (std::abs(v) > Sigma.frequencies.get_wupper_b() + inter_tol)    //Check the range of frequency. If too large, return Sigma(\infty)
        //Returns asymptotic value (Hartree contribution for retarded and 0. for Keldysh component)
        return (1.-(double)iK)*(this->asymp_val_R);
    else {
    Q result;
#ifdef BARE_SE_FEEDBACK
        frequencies_type freqs = {0.0};
#else
        frequencies_type freqs = {v};
#endif
    index_type idx;
    idx[my_defs::SE::keldysh]= iK;
    idx[my_defs::SE::internal]= i_in;
    result = Sigma.interpolate_impl(freqs, idx);
    return result + (1.-(double)iK)*(this->asymp_val_R);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), inter_tol, my_defs::SE::internal, and my_defs::SE::keldysh.
Referenced by check_SE_causality(), and Integrand_Ward_id_integrated< gridType >::operator()().
Friends And Related Symbol Documentation
operator* [1/2]
template<typename Q > template<typename Qfac > SelfEnergy< Q > operator* (const Qfac & rhs, SelfEnergy< Q > lhs) friend
Definition at line 107 of file selfenergy.hpp.
{
        lhs *= rhs;
        return lhs;
    }
operator* [2/2]
template<typename Q > template<typename Qfac > SelfEnergy< Q > operator* (SelfEnergy< Q > lhs, const Qfac & rhs) friend
Definition at line 102 of file selfenergy.hpp.
{
        lhs *= rhs;
        return lhs;
    }
operator+ [1/3]
template<typename Q > template<typename Qfac > SelfEnergy< Q > operator+ (const Qfac & rhs, SelfEnergy< Q > lhs) friend
Definition at line 91 of file selfenergy.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator+ [2/3]
template<typename Q > template<typename Qfac > SelfEnergy< Q > operator+ (SelfEnergy< Q > lhs, const Qfac & rhs) friend
Definition at line 86 of file selfenergy.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator+ [3/3]
template<typename Q > SelfEnergy< Q > operator+ (SelfEnergy< Q > lhs, const SelfEnergy< Q > & rhs) friend
Definition at line 76 of file selfenergy.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator-
template<typename Q > SelfEnergy< Q > operator- (SelfEnergy< Q > lhs, const SelfEnergy< Q > & rhs) friend
Definition at line 124 of file selfenergy.hpp.
{
        lhs -= rhs;
        return lhs;
    }
operator/
template<typename Q > SelfEnergy< Q > operator/ (SelfEnergy< Q > lhs, const SelfEnergy< Q > & rhs) friend
Definition at line 134 of file selfenergy.hpp.
{
        lhs /= rhs;
        return lhs;
    }
Member Data Documentation
asymp_val_R
template<typename Q > Q SelfEnergy< Q >::asymp_val_R = 0.
Definition at line 32 of file selfenergy.hpp.
Referenced by compute_proprocessed_susceptibilities_PT2(), SelfEnergy< Q >::get_selfenergy_vector_incl_hartree(), and loop().
Sigma
template<typename Q > buffer_type SelfEnergy< Q >::Sigma
Definition at line 31 of file selfenergy.hpp.
Referenced by check_SE_causality(), SelfEnergy< Q >::get_selfenergy_vector_incl_hartree(), Hartree_Solver::Hartree_Solver(), Hartree_Solver::Hartree_Solver(), SelfEnergy< Q >::SelfEnergy(), and SelfEnergy< Q >::set_frequency_grid().
The documentation for this class was generated from the following file:
selfenergy.hpp