SIAM-Keldysh-mfRG: Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type > Class Template Reference
Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type > Class Template Reference abstract
Refactoring of the classes Integrand_K1, Integrand_K2, Integrand_K3 into one single class.
#include <integrand.hpp>
Public Member Functions
auto load_vertex_keldysh_and_spin_Components_left_vectorized (const VertexInput &input) const -> Eigen::Matrix< Q, 1,(channel=='t' and spin==0) or(channel
auto load_vertex_keldysh_and_spin_Components_right_vectorized (const VertexInput &input) const -> Eigen::Matrix< Q,(channel=='t' and spin==0) or(channel
auto load_Pi_keldysh_and_spin_Components_vectorized (const freqType input) const -> Eigen::Matrix< Q,(channel=='t' and spin==0) or(channel
Integrand (const vertexType_left &vertex1_in, const vertexType_right &vertex2_in, const Bubble_Object &Pi_in, int i0_in, int i2_in, const int iw_in, const freqType w_in, const freqType v_in, const freqType vp_in, const int i_in_in, const int i_spin_in, const bool diff_in)
auto operator() (freqType vpp) const -> return_type
void save_integrand () const
void save_integrand (const rvec &freqs, const std::string &filename_prefix) const
void get_integrand_vals (const rvec &freqs, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > &integrand_vals, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > &Pivals, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > &vertex_vals1, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > &vertex_vals2) const
auto get_projection_lambdaBar () const -> Eigen::Matrix< Q, 4, 4 >
auto get_projection_lambda () const -> Eigen::Matrix< Q, 4, 4 >
Public Attributes
const VertexInput input_external
const Eigen::Matrix< Q, 4, 4 > projection_lambdaBar = get_projection_lambdaBar()
const Eigen::Matrix< Q, 4, 4 > projection_lambda = get_projection_lambda()
Private Types
using buffer_type_vertex_l = Eigen::Matrix<Q,myRowsAtCompileTime<return_type>(),4>
using buffer_type_vertex_r = Eigen::Matrix<Q,4,myColsAtCompileTime<return_type>()>
Private Member Functions
void set_Keldysh_index_i0 (int i0_in)
void set_Keldysh_index_i0_left_right (int i0_in)
void precompute_vertices ()
bool case_always_has_to_be_zero () const
void compute_vertices (freqType vpp, Q &res_l_V, Q &res_r_V, Q &res_l_Vhat, Q &res_r_Vhat) const
template<int ispin>
void load_vertex_keldyshComponents_left_scalar (buffer_type_vertex_l &values_vertex, const VertexInput &input) const
template<int ispin>
void load_vertex_keldyshComponents_right_scalar (buffer_type_vertex_r &values_vertex, const VertexInput &input) const
template<int ispin>
void load_vertex_keldyshComponents_left_vectorized (buffer_type_vertex_l &values_vertex, const VertexInput &input) const
template<int ispin>
void load_vertex_keldyshComponents_right_vectorized (buffer_type_vertex_r &values_vertex, const VertexInput &input) const
Q sum_over_internal_scalar (freqType vpp) const
return_type sum_over_internal_vectorized (freqType vpp) const
Private Attributes
const vertexType_left & vertex1
const vertexType_right & vertex2
const Bubble_Object & Pi
int i0_symmred
int i0 = 0
int i0_left
int i0_right
const int i2
const int iw =0
const freqType w
const freqType v = 0.
const freqType vp = 0.
const int i_in
const int i_spin
const bool diff
Q res_l_V_initial
Q res_r_V_initial
Q res_l_Vhat_initial
Q res_r_Vhat_initial
Detailed Description
template<K_class diag_class, char channel, int spin, typename Q, typename vertexType_left, typename vertexType_right, class Bubble_Object, typename return_type = Q>
class Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >
Refactoring of the classes Integrand_K1, Integrand_K2, Integrand_K3 into one single class.
Definition at line 90 of file integrand.hpp.
Member Typedef Documentation
buffer_type_vertex_l
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> using Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::buffer_type_vertex_l = Eigen::Matrix<Q,myRowsAtCompileTime<return_type>(),4> private
Definition at line 110 of file integrand.hpp.
buffer_type_vertex_r
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> using Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::buffer_type_vertex_r = Eigen::Matrix<Q,4,myColsAtCompileTime<return_type>()> private
Definition at line 111 of file integrand.hpp.
Constructor & Destructor Documentation
Integrand()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::Integrand (const vertexType_left & vertex1_in, const vertexType_right & vertex2_in, const Bubble_Object & Pi_in, int i0_in, int i2_in, const int iw_in, const freqType w_in, const freqType v_in, const freqType vp_in, const int i_in_in, const int i_spin_in, const bool diff_in) inline
Constructor for asymptotic class Ki:
Parameters
vertex1_in : left vertex
vertex2_in : right vertex
Pi_in : Bubble object connecting the left and right vertex
i0_in : index specifying the (external) Keldysh component of integrand object; i0_in = [0, .. nK_Ki] where nK_Ki is the number of symmetry-reduced Keldysh components in the result (converted into actual Keldysh index i0 within the constructor)
w_in : external bosonic frequency \omega
i_in_in : external index for internal structure
ch_in : diagrammatic channel ('a', 'p', 't')
diff_in : determines whether to compute differentiated or non-differentiated bubble
Definition at line 156 of file integrand.hpp.
              :vertex1(vertex1_in), vertex2(vertex2_in), Pi(Pi_in), i0_symmred(i0_in),
              i2(i2_in), iw(iw_in), w(w_in), v(v_in), vp(vp_in), i_in(i_in_in), i_spin(i_spin_in), diff(diff_in),
               input_external(i0_in, 0, w_in, v_in, vp_in, i_in_in, channel, diag_class, iw_in) {
        set_Keldysh_index_i0(i0_in);
        if constexpr(MAX_DIAG_CLASS < 2 and ! VECTORIZED_INTEGRATION) {precompute_vertices();}
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::precompute_vertices(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::set_Keldysh_index_i0(), and VECTORIZED_INTEGRATION.
Member Function Documentation
case_always_has_to_be_zero()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > bool Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::case_always_has_to_be_zero () const private
Definition at line 421 of file integrand.hpp.
{
    bool zero_result = false;
    if (KELDYSH && (MAX_DIAG_CLASS <= 1)){
        if (!diff) {
            switch (channel) {
                case 'a':
                    // only nonzero combinations of \int dvpp Gamma_0 Pi(vpp) Gamma_0
                    if (i0 == 1 && (i2 != 11 && i2 != 13)) {zero_result = true;}
                    if (i0 == 3 &&
                        (i2 != 6 && i2 != 7 && i2 != 9 && i2 != 11 && i2 != 13 && i2 != 14 && i2 != 15))
                        {zero_result = true;}
                    break;
                case 'p':
                    // only nonzero combinations of \int dvpp Gamma_0 Pi(vpp) Gamma_0
                    if (i0 == 1 && (i2 != 7 && i2 != 11)) {zero_result = true;}
                    if (i0 == 5 &&
                        (i2 != 3 && i2 != 7 && i2 != 11 && i2 != 12 && i2 != 13 && i2 != 14 && i2 != 15))
                        {zero_result = true;}
                    break;
                case 't':
                    // only nonzero combinations of \int dvpp Gamma_0 Pi(vpp) Gamma_0
                    if (i0 == 1 && (i2 != 11 && i2 != 13)) {zero_result = true;}
                    if (i0 == 3 &&
                        (i2 != 6 && i2 != 7 && i2 != 9 && i2 != 11 && i2 != 13 && i2 != 14 && i2 != 15))
                        {zero_result = true;}
                    break;
                default:;
            }
        }
    }
    return zero_result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, and MAX_DIAG_CLASS.
compute_vertices()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::compute_vertices (freqType vpp, Q & res_l_V, Q & res_r_V, Q & res_l_Vhat, Q & res_r_Vhat) const private
Definition at line 455 of file integrand.hpp.
{
    if (MAX_DIAG_CLASS <= 1){
        res_l_V = res_l_V_initial;
        res_r_V = res_r_V_initial;
        res_l_Vhat = res_l_Vhat_initial;
        res_r_Vhat = res_r_Vhat_initial;
    }
    else{
        std::vector<int> indices = indices_sum(i0, i2, channel);
        VertexInput input_l (indices[0], spin, w, v, vpp,  i_in, channel, diag_class, iw);
        VertexInput input_r (indices[1], spin, w, vpp, vp, i_in, channel, diag_class, iw);
        if (i_spin == 0) { // first summand in all channels is res_l_V * Pival * res_r_V
            if (diag_class == k1 or diag_class == k2b)
                res_l_V = vertex1.template left_same_bare<channel>(input_l);
            else
                res_l_V = vertex1.template left_diff_bare<channel>(input_l);
            if (diag_class == k3 or diag_class == k2b)
                res_r_V = vertex2.template right_diff_bare<channel>(input_r);
            else
                res_r_V = vertex2.template right_same_bare<channel>(input_r);
#if DEBUG_SYMMETRIES
            if (channel == 'p') {  // res_l_Vhat * Pival * res_r_Vhat
                // compute res_l_Vhat
                input_l.spin = 1 - spin;
                if (diag_class == k1 or diag_class == k2b)
                    res_l_Vhat = vertex1.template left_same_bare<channel>(input_l);
                else
                    res_l_Vhat = vertex1.template left_diff_bare<channel>(input_l);
                // compute res_r_Vhat
                input_r.spin = 1 - spin;
                if (diag_class == k3 or diag_class == k2b)
                    res_r_Vhat = vertex2.template right_diff_bare<channel>(input_r);
                else
                    res_r_Vhat = vertex2.template right_same_bare<channel>(input_r);
            }
#endif
        }
        else { // relevant for t-channel (spin component 0) and a-channel (spin component 1): there i_spin = 0, 1, 2
            if constexpr(channel == 't'
#if DEBUG_SYMMETRIES
                or channel == 'a'
#endif
            ) {
                // channel = t, i_spin = 1
                if (i_spin == 1) {  // res_l_V * Pival * res_r_Vhat
                    // compute res_l_V
                    if (diag_class == k1 or diag_class == k2b)
                        res_l_V = vertex1.template left_same_bare<channel>(input_l);
                    else
                        res_l_V = vertex1.template left_diff_bare<channel>(input_l);
                    // compute res_r_Vhat
                    input_r.spin = 1 - spin;
                    if (diag_class == k3 or diag_class == k2b)
                        res_r_Vhat = vertex2.template right_diff_bare<channel>(input_r);
                    else
                        res_r_Vhat = vertex2.template right_same_bare<channel>(input_r);
                }
                // channel = t, i_spin = 2
                else {              // res_l_Vhat * Pival * res_r_V
                    assert(i_spin == 2);
                    // compute res_r_V
                    if (diag_class == k3 or diag_class == k2b)
                        res_r_V = vertex2.template right_diff_bare<channel>(input_r);
                    else
                        res_r_V = vertex2.template right_same_bare<channel>(input_r);
                    // compute res_l_Vhat
                    input_l.spin = 1 - spin;
                    if (diag_class == k1 or diag_class == k2b)
                        res_l_Vhat = vertex1.template left_same_bare<channel>(input_l);
                    else
                        res_l_Vhat = vertex1.template left_diff_bare<channel>(input_l);
                }
            }
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), indices_sum(), k1, k2b, k3, and MAX_DIAG_CLASS.
get_integrand_vals()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::get_integrand_vals (const rvec & freqs, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > & integrand_vals, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > & Pivals, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > & vertex_vals1, Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > & vertex_vals2) const
get_projection_lambda()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> auto Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::get_projection_lambda () const -> Eigen::Matrix<Q,4,4> inline
Definition at line 196 of file integrand.hpp.
{
        Eigen::Matrix<Q,4,4> result;
        if constexpr(CONTOUR_BASIS) {
            result << 1, 0, 0, 0,
                    0, 0, 0, 0,
                    0, 0, 0, 0,
                    0, 0, 0, 1;
        }
        else {
            result << 1, 0, 0, 1,
                    0, 1, 1, 0,
                    0, 1, 1, 0,
                    1, 0, 0, 1;
            result *= 0.5;
        }
        return result;
    }
References CONTOUR_BASIS, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_projection_lambdaBar()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> auto Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::get_projection_lambdaBar () const -> Eigen::Matrix<Q,4,4> inline
Definition at line 179 of file integrand.hpp.
{
        Eigen::Matrix<Q,4,4> result;
        if constexpr(CONTOUR_BASIS) {
            result << 1, 0, 0, 0,
                    0, 0, 0, 0,
                    0, 0, 0, 0,
                    0, 0, 0, 1;
        }
        else {
            result << 1, 0, 0, 1,
                    0, 1, 1, 0,
                    0, 1, 1, 0,
                    1, 0, 0, 1;
            result *= 0.5;
        }
        return result;
    }
References CONTOUR_BASIS, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
load_Pi_keldysh_and_spin_Components_vectorized()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> auto Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_Pi_keldysh_and_spin_Components_vectorized (const freqType input) const -> Eigen::Matrix< Q,(channel=='t' and spin= pure virtual
load_vertex_keldysh_and_spin_Components_left_vectorized()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> auto Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldysh_and_spin_Components_left_vectorized (const VertexInput & input) const -> Eigen::Matrix< Q, 1,(channel=='t' and spin= pure virtual
load_vertex_keldysh_and_spin_Components_right_vectorized()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> auto Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldysh_and_spin_Components_right_vectorized (const VertexInput & input) const -> Eigen::Matrix< Q,(channel=='t' and spin= pure virtual
load_vertex_keldyshComponents_left_scalar()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > template<int ispin> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_left_scalar (buffer_type_vertex_l & values_vertex, const VertexInput & input) const private
Definition at line 539 of file integrand.hpp.
{
    //size_t len_1 = values_vertex.length()[0];
    const auto vertexvalue_scalar = [&] (const VertexInput& input_l) {if constexpr(diag_class == k1 or diag_class == k2b) return vertex1.template left_same_bare_symmetry_expanded<ispin,channel,Q>(input_l) ; else return vertex1.template left_diff_bare_symmetry_expanded<ispin,channel,Q>(input_l);};
    //const auto vertexvalue_scalar = [&] (const VertexInput& input_l) {if constexpr(diag_class == k1 or diag_class == k2b) return vertex1.template left_same_bare<channel>(input_l) ; else return vertex1.template left_diff_bare<channel>(input_l);};
    //assert(len_1 == glb_number_of_Keldysh_components_bubble);
    if constexpr(not KELDYSH) {
        values_vertex =  vertexvalue_scalar(input);
    }
    else {
        //Q v11, v12, v21, v22;
        //const std::array<size_t,2> dims_vtemp = {2,2};
        // v_temp contains values for different Keldysh indices:
        // i.e. in a-channel v_temp(i,j) = v_{1',i |j,2}
        //      in p-channel v_temp(i,j) = v_{1',2'|j,i}
        //      in t-channel v_temp(i,j) = v_{i ,2'|j,2}
        //multidimensional::multiarray<Q,2> v_temp(dims_vtemp);
        //std::array<int,4> alpha = iK_to_alphas(input.iK);
        // fill v_temp:
        const std::array<size_t,4> dims_K = {2,2, 2,2};
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 2; j++) {
                //if constexpr(channel == 'a') {input_tmp.iK = getFlatIndex<4,int,int,int,int>(alpha[0]-1, i, j, alpha[3]-1, dims_K);}
                //else if constexpr(channel == 'p') {input_tmp.iK = getFlatIndex<4,int,int,int,int>(alpha[0]-1, alpha[1]-1, j, i, dims_K);}
                //else if constexpr(channel == 't') {input_tmp.iK = getFlatIndex<4,int,int,int,int>(i, alpha[1]-1, j, alpha[3]-1, dims_K);}
                //else assert(false);
                VertexInput input_tmp = input;
                input_tmp.iK = input.iK + i*2+j;
                values_vertex[i*2+j] = vertexvalue_scalar(input_tmp);
            }
        }
        /*
        // fill values_vertex:
        if constexpr(channel == 'a' or channel == 't') {
            values_vertex(1, spin_idx) =  v_temp(0,0);
            values_vertex(0, spin_idx) = values_vertex(2, spin_idx) = v_temp(1,0);
            values_vertex(5, spin_idx) = values_vertex(7, spin_idx) = v_temp(0,1);
            values_vertex(3, spin_idx) = values_vertex(4, spin_idx) = values_vertex(6, spin_idx) = values_vertex(8, spin_idx) = v_temp(1,1);
        }
        else if constexpr(channel == 'p') {
            values_vertex(0, spin_idx) =  v_temp(0,0);
            values_vertex(1, spin_idx) = values_vertex(2, spin_idx) = v_temp(1,0);
            values_vertex(3, spin_idx) = values_vertex(4, spin_idx) = v_temp(0,1);
            values_vertex(5, spin_idx) = values_vertex(6, spin_idx) = values_vertex(7, spin_idx) = values_vertex(8, spin_idx) = v_temp(1,1);
        }
        else assert(false);
        */
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), VertexInput::iK, k1, k2b, and KELDYSH.
load_vertex_keldyshComponents_left_vectorized()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > template<int ispin> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_left_vectorized (buffer_type_vertex_l & values_vertex, const VertexInput & input) const private
Definition at line 656 of file integrand.hpp.
{
    //size_t len_1 = values_vertex.length()[0];
    using result_type_fetch = Eigen::Matrix<Q, 4 * myRowsAtCompileTime<return_type>(),1>;
    const auto vertexvalue_vector = [&] (const VertexInput& input_l) {if constexpr(diag_class == k1 or diag_class == k2b) return vertex1.template left_same_bare_symmetry_expanded<ispin,channel,result_type_fetch>(input_l) ; else return vertex1.template left_diff_bare_symmetry_expanded<ispin,channel,result_type_fetch>(input_l);};
    //assert(len_1 == glb_number_of_Keldysh_components_bubble);
    if constexpr(not KELDYSH) {
        //static_assert(KELDYSH, "Currently vectorized integrand only available for Keldysh.");
        values_vertex = vertexvalue_vector(input);
    }
    else {
        Eigen::Matrix<Q,Eigen::Dynamic, Eigen::Dynamic> result_temp = vertexvalue_vector(input);
        result_temp.resize(4, myRowsAtCompileTime<return_type>());
        values_vertex = result_temp.transpose();
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2b, and KELDYSH.
load_vertex_keldyshComponents_right_scalar()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > template<int ispin> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_right_scalar (buffer_type_vertex_r & values_vertex, const VertexInput & input) const private
Definition at line 599 of file integrand.hpp.
{
    //size_t len_1 = values_vertex.length()[0];
    const auto vertexvalue_scalar = [&](const VertexInput& input_r) {if constexpr(diag_class == k3 or diag_class == k2b) return vertex2.template right_diff_bare_symmetry_expanded<ispin,channel,Q>(input_r); else return vertex2.template right_same_bare_symmetry_expanded<ispin,channel,Q>(input_r);};
    //const auto vertexvalue_scalar = [&](const VertexInput& input_r) {if constexpr(diag_class == k3 or diag_class == k2b) return vertex2.template right_diff_bare<channel>(input_r); else return vertex2.template right_same_bare<channel>(input_r);};
    //assert(len_1 == glb_number_of_Keldysh_components_bubble);
    if constexpr(not KELDYSH) {
        values_vertex =  vertexvalue_scalar(input);
    }
    else {
        //Q v11, v12, v21, v22;
        //const std::array<size_t, 2> dims_vtemp = {2, 2};
        // v_temp contains values for different Keldysh indices:
        // i.e. in a-channel v_temp(i,j) = v_{i ,2'|1,j}
        //      in p-channel v_temp(i,j) = v_{j ,i |1,2}
        //      in t-channel v_temp(i,j) = v_{1',i |1,j}
        //multidimensional::multiarray<Q, 2> v_temp(dims_vtemp);
        //std::array<int,4> alpha = iK_to_alphas(input.iK);
        // fill v_temp:
        const std::array<size_t, 4> dims_K = {2, 2, 2, 2};
        for (int i = 0; i < 2; i++) {
            for (int j = 0; j < 2; j++) {
                //if constexpr(channel == 'a') { input_tmp.iK = getFlatIndex<4,int,int,int,int>(i, alpha[1] - 1, alpha[2] - 1, j, dims_K); }
                //else if constexpr(channel == 'p') { input_tmp.iK = getFlatIndex<4,int,int,int,int>(j, i, alpha[2] - 1, alpha[3] - 1, dims_K); }
                //else if constexpr(channel == 't') { input_tmp.iK = getFlatIndex<4,int,int,int,int>(alpha[0] - 1, i, alpha[2] - 1, j, dims_K); }
                //else
                //    assert(false);
                VertexInput input_tmp = input;
                input_tmp.iK = input.iK + i*2+j;
                values_vertex[i*2+j] = vertexvalue_scalar(input_tmp);
            }
        }
        /*
        // fill values_vertex:
        if constexpr(channel == 'a' or channel == 't') {
            values_vertex[3] = v_temp(0, 0);
            values_vertex[5] = values_vertex[6] = v_temp(0, 1);
            values_vertex[0] = values_vertex[4] = v_temp(1, 0);
            values_vertex[1] = values_vertex[2] = values_vertex[7] = values_vertex[8] = v_temp(
                    1, 1);
        } else if constexpr(channel == 'p') {
            values_vertex[5] = v_temp(0, 0);
            values_vertex[3] = values_vertex[6] = v_temp(1, 0);
            values_vertex[1] = values_vertex[7] = v_temp(0, 1);
            values_vertex[0] = values_vertex[2] = values_vertex[4] = values_vertex[8] = v_temp(1, 1);
        } else
            assert(false);
            */
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), VertexInput::iK, k2b, k3, and KELDYSH.
load_vertex_keldyshComponents_right_vectorized()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > template<int ispin> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_right_vectorized (buffer_type_vertex_r & values_vertex, const VertexInput & input) const private
Definition at line 677 of file integrand.hpp.
{
    //size_t len_1 = values_vertex.length()[0];
    using result_type_fetch = Eigen::Matrix<Q, 4 * myColsAtCompileTime<return_type>(), 1>;
    const auto vertexvalue_vector = [&](const VertexInput& input_r) {if constexpr(diag_class == k3 or diag_class == k2b) return vertex2.template right_diff_bare_symmetry_expanded<ispin,channel,result_type_fetch>(input_r); else return vertex2.template right_same_bare_symmetry_expanded<ispin,channel,result_type_fetch>(input_r);};
    //assert(len_1 == glb_number_of_Keldysh_components_bubble);
    if constexpr(not KELDYSH) {
        //static_assert(KELDYSH, "Currently vectorized integrand only available for Keldysh.");
        values_vertex = vertexvalue_vector(input);
    }
    else {
        Eigen::Matrix<Q,Eigen::Dynamic, Eigen::Dynamic> result_temp = vertexvalue_vector(input);
        result_temp.resize(4, myColsAtCompileTime<return_type>());
        values_vertex = result_temp;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k2b, k3, and KELDYSH.
operator()()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > auto Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::operator() (freqType vpp) const -> return_type
Call operator:
Parameters
vpp : frequency at which to evaluate integrand (to be integrated over)
Returns
Q : value of the integrand object evaluated at frequency vpp (comp or double)
TODO: fix conflict with sum over internal spins
comment in to test vectorized access
Definition at line 338 of file integrand.hpp.
{
    return_type result;
#if not SWITCH_SUM_N_INTEGRAL
    if (case_always_has_to_be_zero()) {return 0.;}
    Q res_l_V, res_r_V, res_l_Vhat, res_r_Vhat;
    compute_vertices(vpp, res_l_V, res_r_V, res_l_Vhat, res_r_Vhat);
    Q Pival = Pi.value(i2, w, vpp, i_in, channel);
    if (channel != 't')  // no spin sum in a and p channel
        result = res_l_V * Pival * res_r_V;
    else {
        // in t channel, spin sum has 3 terms:
        // result = res_l_V * Pival * (res_r_V + res_r_Vhat) + (res_l_V + res_l_Vhat) * Pival * res_r_V;
        //        = 2. * res_l_V * Pival * res_r_V + res_l_V * Pival * res_r_Vhat + res_l_Vhat * Pival * res_r_V;
        switch (i_spin) {
            case 0:
                result = 2. * res_l_V * Pival * res_r_V;
                break;
            case 1:
                result = res_l_V * Pival * res_r_Vhat;
                break;
            case 2:
                result = res_l_Vhat * Pival * res_r_V;
                break;
            default:;
        }
    }
#if DEBUG_SYMMETRIES
    if (spin == 0 and channel ==  'p') {
        result = (res_l_V * Pival * res_r_V);
    }
    if (spin == 1) {
        if (channel == 't')  // no spin sum in t channel
            result = res_l_V * Pival * res_r_V;
        else if (channel == 'p') {
            result = (res_l_V * Pival * res_r_Vhat);
        }
        else { // channel == 'a'
            // in a channel, spin sum has 3 terms:
            // result = res_l_V * Pival * (res_r_V + res_r_Vhat) + (res_l_V + res_l_Vhat) * Pival * res_r_V;
            //        = 2. * res_l_V * Pival * res_r_V + res_l_V * Pival * res_r_Vhat + res_l_Vhat * Pival * res_r_V;
            switch (i_spin) {
                case 0:
                    result = 2. * res_l_V * Pival * res_r_V;
                    break;
                case 1:
                    result = res_l_V * Pival * res_r_Vhat;
                    break;
                case 2:
                    result = res_l_Vhat * Pival * res_r_V;
                    break;
                default:;
            }
        }
    }
#endif // DEBUG_SYMMETRIES
#else
    //assert(false);
    //result = sum_over_internal_scalar(vpp);
    if constexpr(KELDYSH)
    {
        result = sum_over_internal_vectorized(vpp);
    }
    else {
        result = sum_over_internal_scalar(vpp);
    }
    //Q result2 = sum_over_internal_scalar(vpp);
    //assert(std::abs(result-result2) < 1e-10);
#endif
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and KELDYSH.
precompute_vertices()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::precompute_vertices () private
Definition at line 284 of file integrand.hpp.
{
    // For K1 class, left and right vertices do not depend on integration frequency
    // -> precompute them to save time
    if constexpr(not DEBUG_SYMMETRIES) {
#if KELDYSH_FORMALISM
        std::vector<int> indices = indices_sum(i0, i2, channel);
        VertexInput input_l(indices[0], spin, w, 0., 0., i_in, channel);
        VertexInput input_r(indices[1], spin, w, 0., 0., i_in, channel);
#else
        VertexInput input_l (0, spin, w, 0., 0., i_in, channel);
        VertexInput &input_r = input_l;
#endif
        res_l_V_initial = vertex1.template left_same_bare<channel>(input_l);
        res_r_V_initial = vertex2.template right_same_bare<channel>(input_r);
        if (channel == 't') {
            input_l.spin = 1;
            input_r.spin = 1;
            res_l_Vhat_initial = vertex1.template left_same_bare<channel>(input_l);
            res_r_Vhat_initial = vertex2.template right_same_bare<channel>(input_r);
        }
    }
    else {// DEBUG_SYMMETRIES
    #if KELDYSH_FORMALISM
        std::vector<int> indices = indices_sum(i0, i2, channel);
        VertexInput input_l(indices[0], spin, w, 0., 0., i_in, channel);
        VertexInput input_r(indices[1], spin, w, 0., 0., i_in, channel);
    #else
        VertexInput input_l (0, spin, w, 0., 0., i_in, channel);
        VertexInput &input_r = input_l;
    #endif
        res_l_V_initial = vertex1.template left_same_bare<channel>(input_l);
        res_r_V_initial = vertex2.template right_same_bare<channel>(input_r);
        if (channel == 't' and spin == 0) {
            input_l.spin = 1 - input_l.spin; // flip spin 0 <-> 1
            input_r.spin = 1 - input_r.spin; // flip spin 0 <-> 1
            res_l_Vhat_initial = vertex1.template left_same_bare<channel>(input_l);
            res_r_Vhat_initial = vertex2.template right_same_bare<channel>(input_r);
        } else if (channel == 'a' and spin == 1) {
            input_l.spin = 1 - input_l.spin; // flip spin 0 <-> 1
            input_r.spin = 1 - input_r.spin; // flip spin 0 <-> 1
            res_l_Vhat_initial = vertex1.template left_same_bare<channel>(input_l);
            res_r_Vhat_initial = vertex2.template right_same_bare<channel>(input_r);
        } else if (channel == 'p' and spin == 1) {
            input_l.spin = 1 - input_l.spin; // flip spin 0 <-> 1
            input_r.spin = 1 - input_r.spin; // flip spin 0 <-> 1
            res_l_Vhat_initial = vertex1.template left_same_bare<channel>(input_l);
            res_r_Vhat_initial = vertex2.template right_same_bare<channel>(input_r);
        }
    } // DEBUG_SYMMETRIES
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, and indices_sum().
Referenced by Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::Integrand().
save_integrand() [1/2]
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::save_integrand () const
save_integrand() [2/2]
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::save_integrand (const rvec & freqs, const std::string & filename_prefix) const
set_Keldysh_index_i0()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::set_Keldysh_index_i0 (int i0_in) private
Definition at line 220 of file integrand.hpp.
{
if constexpr(KELDYSH){
   if constexpr(not DEBUG_SYMMETRIES and not VECTORIZED_INTEGRATION) {
    /*
        switch (diag_class) {
            case k1: // converting index i0_in (0 or 1) into actual Keldysh index i0 (0,...,15)
                switch (channel) {
                    case 'a':
                        i0 = non_zero_Keldysh_K1a[i0_in];
                        break;
                    case 'p':
                        i0 = non_zero_Keldysh_K1p[i0_in];
                        break;
                    case 't':
                        i0 = non_zero_Keldysh_K1t[i0_in];
                        break;
                    default:;
                }
                break;
            case k2: // converting index i0_in (0,...,4) into actual Keldysh index i0 (0,...,15)
                switch (channel) {
                    case 'a':
                        i0 = non_zero_Keldysh_K2a[i0_in];
                        break;
                    case 'p':
                        i0 = non_zero_Keldysh_K2p[i0_in];
                        break;
                    case 't':
                        i0 = non_zero_Keldysh_K2t[i0_in];
                        break;
                    default:;
                }
                break;
            case k3:
                i0 = non_zero_Keldysh_K3[i0_in]; // converting index i0_in (0,...,5) into actual Keldysh index i0 (0,...,15)
                break;
            default:;
        }
*/
       i0 = i0_in;
    }
   else {
       i0 = i0_in;
   }
       set_Keldysh_index_i0_left_right(i0);
   }
   else{
       i0 = 0;
       i0_left = 0;
       i0_right= 0;
   }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, KELDYSH, and VECTORIZED_INTEGRATION.
Referenced by Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::Integrand().
set_Keldysh_index_i0_left_right()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type > void Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::set_Keldysh_index_i0_left_right (int i0_in) private
Definition at line 276 of file integrand.hpp.
{
    my_index_t left, right;
    get_i0_left_right<channel>(i0_in, left, right);
    i0_left  = left * 4; //
    i0_right = right * 4; //
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
sum_over_internal_scalar()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> Q Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::sum_over_internal_scalar (freqType vpp) const private
sum_over_internal_vectorized()
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> return_type Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::sum_over_internal_vectorized (freqType vpp) const private
Member Data Documentation
diff
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const bool Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::diff private
Definition at line 104 of file integrand.hpp.
i0
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i0 = 0 private
Definition at line 96 of file integrand.hpp.
i0_left
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i0_left private
Definition at line 97 of file integrand.hpp.
i0_right
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i0_right private
Definition at line 98 of file integrand.hpp.
i0_symmred
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i0_symmred private
Definition at line 95 of file integrand.hpp.
i2
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i2 private
Definition at line 99 of file integrand.hpp.
i_in
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i_in private
Definition at line 102 of file integrand.hpp.
i_spin
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::i_spin private
Definition at line 103 of file integrand.hpp.
input_external
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const VertexInput Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::input_external
Definition at line 106 of file integrand.hpp.
iw
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const int Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::iw =0 private
Definition at line 100 of file integrand.hpp.
Pi
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const Bubble_Object& Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::Pi private
Definition at line 94 of file integrand.hpp.
projection_lambda
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const Eigen::Matrix<Q,4,4> Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::projection_lambda = get_projection_lambda()
Definition at line 214 of file integrand.hpp.
projection_lambdaBar
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const Eigen::Matrix<Q,4,4> Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::projection_lambdaBar = get_projection_lambdaBar()
Definition at line 213 of file integrand.hpp.
res_l_V_initial
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> Q Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::res_l_V_initial private
Definition at line 119 of file integrand.hpp.
res_l_Vhat_initial
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> Q Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::res_l_Vhat_initial private
Definition at line 119 of file integrand.hpp.
res_r_V_initial
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> Q Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::res_r_V_initial private
Definition at line 119 of file integrand.hpp.
res_r_Vhat_initial
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> Q Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::res_r_Vhat_initial private
Definition at line 119 of file integrand.hpp.
v
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const freqType Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::v = 0. private
Definition at line 101 of file integrand.hpp.
vertex1
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const vertexType_left& Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::vertex1 private
Definition at line 92 of file integrand.hpp.
vertex2
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const vertexType_right& Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::vertex2 private
Definition at line 93 of file integrand.hpp.
vp
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const freqType Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::vp = 0. private
Definition at line 101 of file integrand.hpp.
w
template<K_class diag_class, char channel, int spin, typename Q , typename vertexType_left , typename vertexType_right , class Bubble_Object , typename return_type = Q> const freqType Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::w private
Definition at line 101 of file integrand.hpp.
The documentation for this class was generated from the following file:
integrand.hpp