SIAM-Keldysh-mfRG: anderson_acceleration.hpp File Reference
anderson_acceleration.hpp File Reference
#include <deque>
#include <Eigen/Dense>
#include "../correlation_functions/two_point/selfenergy.hpp"
#include "../correlation_functions/state.hpp"
Namespaces
namespace anderson_impl
Functions
template<typename Q >
Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > anderson_impl::colwise_difference (Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > m)
template<typename Q >
Eigen::MatrixXd anderson_impl::ordinary_least_squares (const Eigen::Matrix< Q, Eigen::Dynamic, 1 > y, const Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic > A)
Solves an ordinary least-squares problem.
template<typename Q , bool diff>
State< Q, diff > anderson_update (const std::deque< State< Q, diff > > &rhs_evals, const std::deque< State< Q, diff > > &iteration_steps, double zeta=1.0)
Perform an anderson mixing update.
Function Documentation
anderson_update()
template<typename Q , bool diff> State< Q, diff > anderson_update (const std::deque< State< Q, diff > > & rhs_evals, const std::deque< State< Q, diff > > & iteration_steps, double zeta = 1.0)
Perform an anderson mixing update.
Template Parameters
num_components
lattice_type
Parameters
new_state Newly calculated state.
iter_states Previous Anderson steps.
selfenergy_evals Previous selfenergy evaluations.
Returns
state<num_components, lattice_type>
Definition at line 57 of file anderson_acceleration.hpp.
{
    using namespace anderson_impl;
    using myMatrixXQ = Eigen::Matrix< Q, Eigen::Dynamic, Eigen::Dynamic>;
    using myVectorXQ = Eigen::Matrix< Q, Eigen::Dynamic, 1>;
    int m = rhs_evals.size();
    Eigen::VectorXd alpha(m);
    if (m == 0)
    {
        throw std::invalid_argument(
        "Cannot do Anderson update without initial value.");
    }
    else if (m == 1)
    {
        alpha( 0) = 1.0;
    }
    else
    {
        size_t sigma_size = getFlatSize(rhs_evals[0].selfenergy.Sigma.get_dims());
    myMatrixXQ error_matrix(sigma_size, m);
    for (int i = 0; i < m; ++i)
    {
        error_matrix.col(i) =
                rhs_evals[i].selfenergy.get_selfenergy_vector_incl_hartree() -
                iteration_steps[i].selfenergy.get_selfenergy_vector_incl_hartree();
    }
        myMatrixXQ error_differences = colwise_difference(error_matrix);
    // Parametrization of alpha, to achieve $\sum_i \alpha_i = 1$.
    myVectorXQ y = -error_matrix.col(0);
    Eigen::VectorXd gamma = ordinary_least_squares(
            y,
            error_differences);
    alpha(0) = 1. - gamma(0);
    for (int i = 1; i < m - 1; ++i)
    {
    alpha(i) = gamma(i - 1) - gamma(i);
    }
    alpha(m - 1) = gamma(m - 2);
    }
    // const Eigen::IOFormat CleanFmt(4, 0, ", ", "\n", "[", "]");
    // logging::log_message_single("Anderson iteration mixing vector: ", alpha.transpose().format(CleanFmt));
    if (mpi_world_rank() == 0){
        utils::print("Anderson acceleration gives the coefficients: \t [");
        for (int j = 0; j < alpha.size(); j++) {std::cout << alpha[j] << ", ";}
        std::cout << "]\n";
    }
    State<Q, diff> result =
            alpha.coeff(0) *
            (zeta * rhs_evals[0] + (1 - zeta) * iteration_steps[0]);
    for (int i = 1; i < m; ++i)
    {
        result += alpha.coeff(i) *
        (zeta * rhs_evals[i] + (1 - zeta) * iteration_steps[i]);
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), getFlatSize(), mpi_world_rank(), utils::print(), and selfenergy.
Referenced by parquet_solver(), and rhs_n_loop_flow().