SIAM-Keldysh-mfRG: Hartree_Solver Class Reference
Hartree_Solver Class Reference
Class which determines the Hartree-term for the self-energy self-consistently in units of glb_U given the system parameters.
#include <hartree_term.hpp>
Public Member Functions
Hartree_Solver (const double Lambda_in, const fRG_config &config_in)
constructor used for obtaining the self-consistent solution of the Hartree-term
Hartree_Solver (const double Lambda_in, const SelfEnergy< comp > &Sigma_in, const fRG_config &config_in, const bool diff=false)
constructor used for a one-shot calculation of the Hartree-term with a given selfenergy, e.g. in parquet iterations or in the 1l flow equation.
Hartree_Solver (const double Lambda_in, const fRG_config &config_in, bool test_all_Keldysh_components)
constructor used for testing the Hartree-term computation with different Keldysh components of the single-scale propagator
double compute_filling_oneshot ()
double compute_Hartree_term (double convergence_threshold=1e-12)
double compute_Hartree_term_bracketing (double convergence_threshold=1e-12, bool Friedel_check=true, bool verbose=true)
double compute_Hartree_term_Friedel (double convergence_threshold=1e-12)
double compute_Hartree_term_oneshot ()
auto operator() (double nu) const -> double
void friedel_sum_rule_check () const
void write_out_propagators () const
Public Attributes
SelfEnergy< comp > selfEnergy = SelfEnergy<comp> (Lambda, config)
Private Member Functions
double fermi_distribution (double nu) const
Private Attributes
const double Lambda
const fRG_config & config
const double Delta = (config.Gamma + Lambda) / 2.
double filling = 1./2.
const double v_lower = 10 * Delta
const double v_upper = -10 * Delta
char prop_type = 'g'
bool test_different_Keldysh_component = false
std::string test_Keldysh_component
Detailed Description
Class which determines the Hartree-term for the self-energy self-consistently in units of glb_U given the system parameters.
Definition at line 17 of file hartree_term.hpp.
Constructor & Destructor Documentation
Hartree_Solver() [1/3]
Hartree_Solver::Hartree_Solver (const double Lambda_in, const fRG_config & config_in) inline
constructor used for obtaining the self-consistent solution of the Hartree-term
Definition at line 36 of file hartree_term.hpp.
                                                                       : Lambda(Lambda_in), config(config_in){
        //assert(KELDYSH);
        assert(EQUILIBRIUM); // because we use FDTs
        selfEnergy.initialize(config.U * filling, 0);
        selfEnergy.Sigma.initInterpolator();
    };
References config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), EQUILIBRIUM, filling, SelfEnergy< Q >::initialize(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initInterpolator(), selfEnergy, SelfEnergy< Q >::Sigma, and fRG_config::U.
Hartree_Solver() [2/3]
Hartree_Solver::Hartree_Solver (const double Lambda_in, const SelfEnergy< comp > & Sigma_in, const fRG_config & config_in, const bool diff = false) inline
constructor used for a one-shot calculation of the Hartree-term with a given selfenergy, e.g. in parquet iterations or in the 1l flow equation.
Definition at line 44 of file hartree_term.hpp.
                                                                                                                                : Lambda(Lambda_in), config(config_in){
        assert(EQUILIBRIUM); // because we use FDTs
        selfEnergy = Sigma_in;
        if (diff) prop_type = 's'; // single-scale
    };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), EQUILIBRIUM, prop_type, and selfEnergy.
Hartree_Solver() [3/3]
Hartree_Solver::Hartree_Solver (const double Lambda_in, const fRG_config & config_in, bool test_all_Keldysh_components) inline
constructor used for testing the Hartree-term computation with different Keldysh components of the single-scale propagator
Definition at line 51 of file hartree_term.hpp.
                                                                                                         :
    Lambda(Lambda_in), config(config_in){
        assert(KELDYSH);
        assert(EQUILIBRIUM); // because we use FDTs
        selfEnergy.initialize(config.U * filling, 0);
        selfEnergy.Sigma.initInterpolator();
        // first compute the proper Hartree term
        selfEnergy.initialize(
                this->compute_Hartree_term_bracketing(1e-12, false, true),
                0);
        assert(test_all_Keldysh_components);
        // now compute the Hartree-term once with each Keldysh-component of the single-scale propagator
        test_different_Keldysh_component = true;
        for (std::string component : {"A_real", "A_imag", "R_real", "R_imag", "K_real", "K_imag", "lesser"}) {
            test_Keldysh_component = component;
            double test_result = compute_Hartree_term_oneshot();
            //utils::print("Closing the Hartree loop with the " + test_Keldysh_component + " component of S gives "
            //             + std::to_string(test_result), true);
            std::cout << "Closing the Hartree loop with the " << test_Keldysh_component << " component of S gives " << test_result << "\n";
        }
        double test_Keldysh = 0.;
        double test_lesser = 0.;
        test_Keldysh_component = "K_imag";
        test_Keldysh = compute_Hartree_term_oneshot();
        test_Keldysh_component = "lesser";
        test_lesser = compute_Hartree_term_oneshot();
        double rel_diff = (test_Keldysh - test_lesser) /test_Keldysh;
        std::cout << "Relative difference between closing with S^K or 2S^lesser " << rel_diff << "\n";
    }
References compute_Hartree_term_bracketing(), compute_Hartree_term_oneshot(), config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), EQUILIBRIUM, filling, SelfEnergy< Q >::initialize(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initInterpolator(), KELDYSH, selfEnergy, SelfEnergy< Q >::Sigma, test_different_Keldysh_component, test_Keldysh_component, and fRG_config::U.
Member Function Documentation
compute_filling_oneshot()
double Hartree_Solver::compute_filling_oneshot ()
Definition at line 5 of file hartree_term.c++.
{
    if constexpr (KELDYSH) {
        return integrator_Matsubara_T0(*this, v_lower, v_upper, 10, {0}, 0, true);
    }
    else if constexpr (ZERO_T) { // Matsubara T=0
        return integrator_Matsubara_T0(*this, v_lower, v_upper, 0., {0}, 0, true) / (2.*M_PI)
               + (prop_type == 'g' ? 0.5 : 0.);
    }
    else { // Matsubara T>0
        const int Nmin = -POSINTRANGE*10;
        const int Nmax =  POSINTRANGE*10;
        const double vmin_temp = (2.*Nmin + 1);
        const double vmax_temp = (2.*Nmax + 1);
        const double filling_oneshot = matsubarasum<double>(*this, Nmin, Nmax) * config.T + (prop_type == 'g' ? 0.5 : 0.)
                                       + asymp_corrections_bubble_via_quadrature<double>(*this, vmin_temp, vmax_temp) * config.T;
        return filling_oneshot;
    }
}
References config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), integrator_Matsubara_T0(), KELDYSH, POSINTRANGE, prop_type, fRG_config::T, v_lower, v_upper, and ZERO_T.
Referenced by compute_Hartree_term(), compute_Hartree_term_bracketing(), and compute_Hartree_term_oneshot().
compute_Hartree_term()
double Hartree_Solver::compute_Hartree_term (double convergence_threshold = 1e-12)
Definition at line 25 of file hartree_term.c++.
{
    double diff = 1.;
    int n_iter = 0;
    while (std::abs(diff) > convergence_threshold) {
        n_iter++;
        double filling_new = compute_filling_oneshot();
        diff = filling_new - filling;
        filling = filling_new;
        SelfEnergy<comp> Sigma_new (Lambda, config);
        Sigma_new.initialize(config.U * filling, 0);
        selfEnergy = Sigma_new;
    }
    utils::print_add("  ", true);
    utils::print("Determined filling of: " + std::to_string(filling), true);
    utils::print("Number of iterations needed: " + std::to_string(n_iter), true);
    friedel_sum_rule_check();
    return config.U * filling;
}
References compute_filling_oneshot(), config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), filling, friedel_sum_rule_check(), Lambda, utils::print(), utils::print_add(), selfEnergy, and fRG_config::U.
compute_Hartree_term_bracketing()
double Hartree_Solver::compute_Hartree_term_bracketing (double convergence_threshold = 1e-12, bool Friedel_check = true, bool verbose = true)
Definition at line 44 of file hartree_term.c++.
{
    double LHS = 1.;
    int n_iter = 0;
    double filling_min = 0.;
    double filling_max = 1.;
    while (std::abs(LHS) > convergence_threshold) {
        assert(n_iter < 1e5); // Avoid infinite loop
        n_iter++;
        filling = (filling_min + filling_max) / 2.;
        SelfEnergy<comp> Sigma_new (Lambda, config);
        Sigma_new.initialize(config.U * filling, 0);
        Sigma_new.Sigma.initInterpolator();
        selfEnergy = Sigma_new;
        const double filling_tmp = compute_filling_oneshot();
        LHS = filling_tmp - filling;
        if (LHS > 0.) {
            filling_min = filling;
        }
        else if (LHS < 0.) {
            filling_max = filling;
        }
        else { // LHS == 0.0 exactly
            utils::print("Warning, obtained a numerically exact result for the filling. Might be suspicious.", true);
            return config.U * filling;
        }
    }
    if (verbose) {
        utils::print_add("  ", true);
        utils::print("Determined filling of: " + std::to_string(filling), true);
        utils::print("Number of iterations needed: " + std::to_string(n_iter), true);
    }
    if (Friedel_check) friedel_sum_rule_check();
    return config.U * filling;
}
References compute_filling_oneshot(), config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), filling, friedel_sum_rule_check(), Lambda, utils::print(), utils::print_add(), selfEnergy, and fRG_config::U.
Referenced by Hartree_Solver().
compute_Hartree_term_Friedel()
double Hartree_Solver::compute_Hartree_term_Friedel (double convergence_threshold = 1e-12)
Definition at line 81 of file hartree_term.c++.
{
    assert(ZERO_T);
    double n_ini = 1./2.;
    double n = n_ini;
    double diff = 1;
    int counter = 0;
    while (diff > convergence_threshold) {
        assert(counter < 1e5);
        n_ini = n;
        double Vg = config.U*0.5 + config.epsilon;
        n = 1./2. - 1./M_PI * atan(Vg / Delta + config.U / Delta * (n - 1./2.));
        diff = std::abs(n_ini - n);
        counter++;
    }
    return config.U * n;
}
References config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Delta, fRG_config::epsilon, fRG_config::U, and ZERO_T.
compute_Hartree_term_oneshot()
double Hartree_Solver::compute_Hartree_term_oneshot ()
Definition at line 100 of file hartree_term.c++.
{
    return config.U * compute_filling_oneshot();
}
References compute_filling_oneshot(), config, and fRG_config::U.
Referenced by Hartree_Solver().
fermi_distribution()
double Hartree_Solver::fermi_distribution (double nu) const private
Definition at line 182 of file hartree_term.c++.
{
    if constexpr (not ZERO_T){
        return 1 / (exp(nu / config.T) + 1.);
    }
    else{
        if (nu > 0.) return 0.;
        else if (nu == 0.) return 1/2.;
        else if (nu < 0.) return 1.;
        else assert(false);
    }
    assert (false);
    return 0.0;
}
References config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::T, and ZERO_T.
friedel_sum_rule_check()
void Hartree_Solver::friedel_sum_rule_check () const
Definition at line 143 of file hartree_term.c++.
{
    const double filling_friedel = 1./2. - 1./M_PI * atan((config.epsilon + config.U * filling)/(Delta));
    utils::print("Filling determined self-consistently = " + std::to_string(filling), true);
    utils::print("Filling from the Friedel sum rule, valid at zero T = " + std::to_string(filling_friedel), true);
    const double relative_difference = std::abs((filling - filling_friedel) / filling);
    utils::print("Relative difference = " + std::to_string(relative_difference), true);
    if (ZERO_T and (relative_difference > 1e-3)){
        utils::print(" ", true);
        utils::print("ERROR! The computed value of the filling does not agree with the result from the Friedel rule. Maybe the integrator's accuracy isn't high enough?", true);
        utils::print(" ", true);
        assert(false);
    }
}
References config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Delta, fRG_config::epsilon, filling, utils::print(), fRG_config::U, and ZERO_T.
Referenced by compute_Hartree_term(), and compute_Hartree_term_bracketing().
operator()()
auto Hartree_Solver::operator() (double nu) const -> double
in Matsubara formalism the integrand for the filling is 1/(2 pi) * G(nu) to make the integral converge for large nu one needs to subtract the asymptotic part, set the integrand to 1/(2 pi) [G(nu) - 1/(i nu)] and add 1/2 for the asymptotic part later on
Definition at line 104 of file hartree_term.c++.
{
    Propagator<comp> G (Lambda, selfEnergy, prop_type, config);
    if constexpr (KELDYSH) {
        // integrand for the filling (not the Hartree value!) given according to the formula
        // 1/pi * n_F(nu) Im G^R(nu)
        double val = - 1. / M_PI * fermi_distribution(nu);
        if (test_different_Keldysh_component){
            if      (test_Keldysh_component == "A_real") return std::conj(G.SR(nu, 0)).real();
            else if (test_Keldysh_component == "A_imag") return std::conj(G.SR(nu, 0)).imag();
            else if (test_Keldysh_component == "R_real") return G.SR(nu, 0).real();
            else if (test_Keldysh_component == "R_imag") return G.SR(nu, 0).imag();
            else if (test_Keldysh_component == "K_real") return G.SK(nu, 0).real();
            else if (test_Keldysh_component == "K_imag") return G.SK(nu, 0).imag();
            else if (test_Keldysh_component == "lesser") return - 4 * fermi_distribution(nu) * G.SR(nu, 0).imag();
        }
        else {
            switch (prop_type) {
                case 'g': return val * G.GR(nu, 0).imag();
                case 's': return val * G.SR(nu, 0).imag(); // TODO: sign and prefactor??
                default: assert(false); return 0.;
            }
        }
        assert (false);
        return 0;
    }
    else { // Matsubara
        switch (prop_type) {
            case 'g': return (G.GM(nu, 0) - 1./(glb_i * nu * ((!KELDYSH and !ZERO_T) ? M_PI*config.T : 1.))).real();
            case 's': return G.SM(nu, 0).real(); // TODO: sign and prefactor??
            default: assert(false); return 0.;
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), Propagator< Q >::GM(), Propagator< Q >::GR(), KELDYSH, Propagator< Q >::SK(), Propagator< Q >::SM(), Propagator< Q >::SR(), and ZERO_T.
write_out_propagators()
void Hartree_Solver::write_out_propagators () const
Definition at line 157 of file hartree_term.c++.
{
    Propagator<comp> G (Lambda, selfEnergy, 'g', config);
    rvec GR_real = {};
    rvec GR_imag = {};
    rvec GK_real = {};
    rvec GK_imag = {};
    vec<freqType> freqs = G.selfenergy.Sigma.frequencies.primary_grid.get_all_frequencies();
    for (double nu : freqs) {
        GR_real.push_back(G.GR(nu, 0).real());
        GR_imag.push_back(G.GR(nu, 0).imag());
        GK_real.push_back(G.GK(nu, 0).real());
        GK_imag.push_back(G.GK(nu, 0).imag());
    }
    const std::string filename = data_dir + "Hartree_Propagators_with_U_over_Delta_" \
    + std::to_string(config.U / Delta) + "_and_eVg_over_U_" + std::to_string((config.epsilon+config.U*0.5) / config.U) + ".h5";
    write_h5_rvecs(filename,
                   {"GR_real", "GR_imag", "GK_real", "GK_imag"},
                   {GR_real, GR_imag, GK_real, GK_imag});
    H5::H5File file_out(filename, H5F_ACC_RDWR);
    write_to_hdf(file_out, "freqs", freqs, false);
    file_out.close();
}
References config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), data_dir, Delta, fRG_config::epsilon, Propagator< Q >::GK(), Propagator< Q >::GR(), Lambda, Propagator< Q >::selfenergy, selfEnergy, fRG_config::U, write_h5_rvecs(), and write_to_hdf().
Member Data Documentation
config
const fRG_config& Hartree_Solver::config private
Definition at line 19 of file hartree_term.hpp.
Referenced by compute_filling_oneshot(), compute_Hartree_term(), compute_Hartree_term_bracketing(), compute_Hartree_term_Friedel(), compute_Hartree_term_oneshot(), fermi_distribution(), friedel_sum_rule_check(), Hartree_Solver(), Hartree_Solver(), and write_out_propagators().
Delta
const double Hartree_Solver::Delta = (config.Gamma + Lambda) / 2. private
Definition at line 20 of file hartree_term.hpp.
Referenced by compute_Hartree_term_Friedel(), friedel_sum_rule_check(), and write_out_propagators().
filling
double Hartree_Solver::filling = 1./2. private
Definition at line 22 of file hartree_term.hpp.
Referenced by compute_Hartree_term(), compute_Hartree_term_bracketing(), friedel_sum_rule_check(), Hartree_Solver(), and Hartree_Solver().
Lambda
const double Hartree_Solver::Lambda private
Definition at line 18 of file hartree_term.hpp.
Referenced by compute_Hartree_term(), compute_Hartree_term_bracketing(), and write_out_propagators().
prop_type
char Hartree_Solver::prop_type = 'g' private
Definition at line 27 of file hartree_term.hpp.
Referenced by compute_filling_oneshot(), and Hartree_Solver().
selfEnergy
SelfEnergy<comp> Hartree_Solver::selfEnergy = SelfEnergy<comp> (Lambda, config)
Definition at line 34 of file hartree_term.hpp.
Referenced by compute_Hartree_term(), compute_Hartree_term_bracketing(), Hartree_Solver(), Hartree_Solver(), Hartree_Solver(), and write_out_propagators().
test_different_Keldysh_component
bool Hartree_Solver::test_different_Keldysh_component = false private
Definition at line 29 of file hartree_term.hpp.
Referenced by Hartree_Solver().
test_Keldysh_component
std::string Hartree_Solver::test_Keldysh_component private
Definition at line 30 of file hartree_term.hpp.
Referenced by Hartree_Solver().
v_lower
const double Hartree_Solver::v_lower = 10 * Delta private
Definition at line 24 of file hartree_term.hpp.
Referenced by compute_filling_oneshot().
v_upper
const double Hartree_Solver::v_upper = -10 * Delta private
Definition at line 25 of file hartree_term.hpp.
Referenced by compute_filling_oneshot().
The documentation for this class was generated from the following files:
hartree_term.hpp
hartree_term.c++