SIAM-Keldysh-mfRG: Integrand_sum_rule_spectrum Class Reference
Integrand_sum_rule_spectrum Class Reference
#include <postprocessing.hpp>
Public Member Functions
Integrand_sum_rule_spectrum (const double Lambda, const SelfEnergy< state_datatype > &self_in, const fRG_config &config)
auto operator() (const double w) const -> double
Private Attributes
int it_spin = 0
const Propagator< state_datatype > prop
Detailed Description
Definition at line 105 of file postprocessing.hpp.
Constructor & Destructor Documentation
Integrand_sum_rule_spectrum()
Integrand_sum_rule_spectrum::Integrand_sum_rule_spectrum (const double Lambda, const SelfEnergy< state_datatype > & self_in, const fRG_config & config) inline
Definition at line 109 of file postprocessing.hpp.
: prop(Lambda, self_in, 'g', config) {}
Member Function Documentation
operator()()
auto Integrand_sum_rule_spectrum::operator() (const double w) const -> double inline
Definition at line 111 of file postprocessing.hpp.
{
        const double result = myimag(prop.valsmooth(0, w, 0)) /(-M_PI);
        return result;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), myimag(), prop, and Propagator< Q >::valsmooth().
Member Data Documentation
it_spin
int Integrand_sum_rule_spectrum::it_spin = 0 private
Definition at line 106 of file postprocessing.hpp.
prop
const Propagator<state_datatype> Integrand_sum_rule_spectrum::prop private
Definition at line 107 of file postprocessing.hpp.
Referenced by operator()().
The documentation for this class was generated from the following file:
postprocessing.hpp