SIAM-Keldysh-mfRG: vec< T > Class Template Reference
vec< T > Class Template Reference
DECLARATIONS ///.
#include <data_structures.hpp>
Public Member Functions
vec ()
vec (size_t n)
vec (size_t n, T value)
template<class InputIterator >
vec (InputIterator first, InputIterator last)
vec (std::initializer_list< T > m)
vec (std::vector< T > vect)
T operator() (int i) const
vec< T > operator() (int i1, int i2) const
vec< T > inv () const
vec< double > real () const
vec< double > imag () const
template<typename T2 = double>
vec< T2 > abs () const
vec< T > conj () const
double max_norm () const
vec< T > diff () const
T sum () const
template<typename Q >
vec< T > & operator+= (const vec< Q > &m)
DEFINITIONS – MEMBER FUNCTIONS ///.
template<typename Q >
vec< T > & operator+= (const Q &c)
template<typename Q >
vec< T > & operator-= (const vec< Q > &m)
template<typename Q >
vec< T > & operator-= (const Q &c)
template<typename Q >
vec< T > & operator*= (const vec< Q > &m)
template<typename Q >
vec< T > & operator*= (const Q &c)
template<typename Q >
vec< T > & operator/= (const vec< Q > &m)
template<typename Q , typename R >
vec< T > & elementwise_map_assign (const Q &op, const vec< R > &rhs)
template<typename Q , typename R >
vec< T > & scalar_map_assign (const Q &op, const R &rhs)
Detailed Description
template<typename T>
class vec< T >
DECLARATIONS ///.
General vector class, defining element-wise addition, subtraction and multiplication, as well as real/imag part etc.
Definition at line 118 of file data_structures.hpp.
Constructor & Destructor Documentation
vec() [1/6]
template<typename T > vec< T >::vec () inline
Definition at line 120 of file data_structures.hpp.
: std::vector<T> () {};                          // trivial constructor
vec() [2/6]
template<typename T > vec< T >::vec (size_t n) inline explicit
Definition at line 121 of file data_structures.hpp.
: std::vector<T> (n) {};                     // constructor with number of elements
vec() [3/6]
template<typename T > vec< T >::vec (size_t n, T value) inline
Definition at line 122 of file data_structures.hpp.
: std::vector<T> (n, value) {};   // constructor with number of elements and value
vec() [4/6]
template<typename T > template<class InputIterator > vec< T >::vec (InputIterator first, InputIterator last) inline
Definition at line 124 of file data_structures.hpp.
     : std::vector<T> (first, last) {};                   // constructor from iterators to copy parts of existing vector
vec() [5/6]
template<typename T > vec< T >::vec (std::initializer_list< T > m) inline
Definition at line 126 of file data_structures.hpp.
: std::vector<T> (m) {};   // constructor from initializer list
vec() [6/6]
template<typename T > vec< T >::vec (std::vector< T > vect) inline
Definition at line 127 of file data_structures.hpp.
: std::vector<T> (vect) {};
Member Function Documentation
abs()
template<typename T > template<typename T2 > vec< T2 > vec< T >::abs () const
Definition at line 361 of file data_structures.hpp.
{
    vec<T2> temp (this->size());
#pragma omp parallel for
    for (unsigned int i=0; i<this->size(); ++i) {
        temp[i] = std::abs((*this)[i]);
    }
    return temp;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by maxabs().
conj()
template<typename T > vec< T > vec< T >::conj () const
Definition at line 372 of file data_structures.hpp.
                          {                         // if T != comp, return input
    return transform_vec<T,T>(myconj<T>, *this);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
diff()
template<typename T > vec< T > vec< T >::diff () const
Definition at line 389 of file data_structures.hpp.
{
    vec<T> xp (this->begin() + 1, this->end()); // second -> last element
    vec<T> xm (this->begin(), this->end() - 1); // first -> second to last element
    return xp - xm;                             // compute differences
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
elementwise_map_assign()
template<typename T > template<typename Q , typename R > vec< T > & vec< T >::elementwise_map_assign (const Q & op, const vec< R > & rhs) inline
Definition at line 158 of file data_structures.hpp.
    {
        if (rhs.size() != this->size())
        {
            throw std::length_error("Cannot perform pairwise operations on vectors of different size.");
        }
        for (size_t i = 0; i < this->size(); i++)
        {
            (*this)[i] = op((*this)[i], rhs[i]);
        }
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
imag()
template<typename T > vec< double > vec< T >::imag () const
Definition at line 353 of file data_structures.hpp.
                               {                    // if T != comp, vector of zeros is returned
    return transform_vec<T,double>(myimag<T>, *this);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
inv()
template<typename T > vec< T > vec< T >::inv () const
Definition at line 341 of file data_structures.hpp.
{
    return transform_vec<T,T>([](const T& x) -> T {return 1./x;}, *this);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
max_norm()
template<typename T > double vec< T >::max_norm () const
Definition at line 379 of file data_structures.hpp.
{
    double out = 0.;
    for (size_t i=0; i<this->size(); ++i) {
        out = std::max(out, (double)std::abs((*this)[i]));
    }
    return out;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator()() [1/2]
template<typename T > T vec< T >::operator() (int i) const inline
Definition at line 129 of file data_structures.hpp.
{return (*this)[i]; }        // operator for element access
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator()() [2/2]
template<typename T > vec< T > vec< T >::operator() (int i1, int i2) const
Definition at line 291 of file data_structures.hpp.
{
    auto it1 = (i1 >= 0) ? this->begin() : this->end();
    auto it2 = (i2 >= 0) ? this->begin() : this->end();
    vec<T> subvector (it1 + i1, it2 + i2 + 1);
    return subvector;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*=() [1/2]
template<typename T > template<typename Q > vec< T > & vec< T >::operator*= (const Q & c)
Definition at line 283 of file data_structures.hpp.
{
    return scalar_map_assign([](const T &l, const Q &r) { return l * r; }, c);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*=() [2/2]
template<typename T > template<typename Q > vec< T > & vec< T >::operator*= (const vec< Q > & m)
Definition at line 276 of file data_structures.hpp.
{
    return elementwise_map_assign([](const T &l, const Q &r) { return l * r; }, m);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+=() [1/2]
template<typename T > template<typename Q > vec< T > & vec< T >::operator+= (const Q & c)
Definition at line 252 of file data_structures.hpp.
{
    return scalar_map_assign([](const T &l, const Q &r) { return l + r; }, c);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+=() [2/2]
template<typename T > template<typename Q > vec< T > & vec< T >::operator+= (const vec< Q > & m)
DEFINITIONS – MEMBER FUNCTIONS ///.
Definition at line 246 of file data_structures.hpp.
{
    return elementwise_map_assign([](const T &l, const Q &r) { return l + r; }, m);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-=() [1/2]
template<typename T > template<typename Q > vec< T > & vec< T >::operator-= (const Q & c)
Definition at line 264 of file data_structures.hpp.
{
    return scalar_map_assign([](const T &l, const Q &r) { return l - r; }, c);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-=() [2/2]
template<typename T > template<typename Q > vec< T > & vec< T >::operator-= (const vec< Q > & m)
Definition at line 258 of file data_structures.hpp.
{
    return elementwise_map_assign([](const T &l, const Q &r) { return l - r; }, m);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/=()
template<typename T > template<typename Q > vec< T > & vec< T >::operator/= (const vec< Q > & m)
Definition at line 271 of file data_structures.hpp.
{
    return elementwise_map_assign([](const T &l, const Q &r) { return l / r; }, m);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
real()
template<typename T > vec< double > vec< T >::real () const
Definition at line 347 of file data_structures.hpp.
                               {                    // if T != comp or double, vector of zeros is returned
    return transform_vec<T,double>(myreal<T>, *this);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
scalar_map_assign()
template<typename T > template<typename Q , typename R > vec< T > & vec< T >::scalar_map_assign (const Q & op, const R & rhs) inline
Definition at line 174 of file data_structures.hpp.
    {
        for (size_t i = 0; i < this->size(); i++)
        {
            (*this)[i] = op((*this)[i], rhs);
        }
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
sum()
template<typename T > T vec< T >::sum () const
Definition at line 397 of file data_structures.hpp.
                    {
    return std::accumulate(this->begin(), this->end(), myzero<T>());
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
The documentation for this class was generated from the following file:
data_structures.hpp