SIAM-Keldysh-mfRG: Spline< Q, rank, 3, pos_first_freq_index, DataContainer > Class Template Reference
Spline< Q, rank, 3, pos_first_freq_index, DataContainer > Class Template Reference
#include <InterpolatorSpline3D.hpp>
Public Member Functions
Spline ()
Spline (double Lambda, index_type dims)
void initInterpolator () const
void set_initializedInterpol (bool is_init) const
Eigen::Matrix< Q, 64, 1 > get_weights (const std::array< my_index_t, 3 > &freq_idx, const std::array< double, 3 > &dw_normalized) const
template<typename result_type >
result_type interpolate_spline (const frequencies_type &frequencies, const index_type &indices) const
Public Member Functions inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
DataContainer ()=default
DataContainer (double Lambda, dimensions_type dims, const fRG_config &config)
auto get_VertexFreqGrid () const -> const frequencyGrid_type &
Functions for getting and setting the frequency grid and its members.
void set_VertexFreqGrid (const frequencyGrid_type frequencyGrid)
template<unsigned int idim, typename std::enable_if_t<(idim< numberFrequencyDims), bool > = true>
double analyze_tails (const int index=0) const
buffer_type get_deriv_x (const buffer_type &dat) const
buffer_type get_deriv_y (const buffer_type &dat) const
buffer_type get_deriv_z (const buffer_type &dat) const
buffer_type get_deriv_xx () const
buffer_type get_deriv_yy () const
buffer_type get_deriv_zz () const
buffer_type get_deriv_xy () const
buffer_type get_deriv_xz () const
buffer_type get_deriv_yz () const
buffer_type get_deriv_xyz () const
auto get_deriv_max () const -> double
auto get_curvature_max () const -> double
template<typename gridType >
auto shrink_freq_box_impl (const gridType &freqGrid, const double rel_tail_threshold, const vec< double > &maxabs_along_x, const bool verbose) const -> gridType
auto shrink_freq_box (const double rel_tail_threshold, bool verbose=true, double constant=0.) const -> frequencyGrid_type
Public Member Functions inherited from dataContainerBase< Q, rank >
dataContainerBase ()=default
constructor:
dataContainerBase (const dimensions_type dims)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
dataContainerBase (const Types &... dims)
dataContainerBase (const buffer_type &data_in)
Q acc (const size_t flatIndex) const
Access data via flattened index.
void direct_set (const size_t flatIndex, Q value)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
Q val (const Types &... i) const
Returns value for a multiIndex.
Q val (const index_type &idx) const
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
const Q & at (const Types &... i) const
Returns reference to a value for a multiIndex.
template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true>
auto val_vectorized (const Types &... i) const -> Eigen::Matrix< Q, vecsize, 1 >
template<std::size_t freqrank, std::size_t vecsize>
auto val_vectorized (const index_type &idx) const -> Eigen::Matrix< Q, vecsize, 1 >
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
void setvert (const Q value, const Types &... i)
Sets a value at a multiIndex.
void setvert (const Q value, const index_type &idx)
template<std::size_t vecsize>
void setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > &value, const index_type &idx)
auto get_dims () const
const buffer_type & get_vec () const
Returns the buffer "data" containing the data.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void set_vec (const container &data_in)
Sets the the buffer "data".
void set_vec (const buffer_type &data_in)
void set_vec (const buffer_type &&data_in)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void add_vec (const container &summand)
Adds a vector to the data.
void add_vec (const buffer_type &summand)
constexpr auto eigen_segment (const index_type &start, const index_type &end)
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> get_values (const index_type &index) const
Public Attributes
bool initialized = false
Public Attributes inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
frequencyGrid_type frequencies
Protected Member Functions
void get_coeffs_from_derivs () const
known values of first or second derivative (corresponding to bd_type)
Protected Attributes
size_t n =0
vec< Q > m_deriv_x = vec<Q>(n)
vec< Q > m_deriv_y = vec<Q>(n)
vec< Q > m_deriv_z = vec<Q>(n)
vec< Q > m_deriv_xy = vec<Q>(n)
vec< Q > m_deriv_xz = vec<Q>(n)
vec< Q > m_deriv_yz = vec<Q>(n)
vec< Q > m_deriv_xyz = vec<Q>(n)
bd_type m_left = third_deriv
bd_type m_right = third_deriv
Q m_left_value = 0.0
set const?
Q m_right_value = 0.0
Protected Attributes inherited from dataContainerBase< Q, rank >
buffer_type data
Private Types
using coeffs_type = Eigen::Matrix<Q, Eigen::Dynamic,64>
using index_type = typename DataContainer::index_type
using frequencies_type = std::array<double, 3>
Private Attributes
coeffs_type all_coefficients
Additional Inherited Members
Public Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
using buffer_type = typename base_class::buffer_type
Protected Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using base_class = dataContainerBase<Q, rank>
Protected Types inherited from dataContainerBase< Q, rank >
using buffer_type = multidimensional::multiarray<Q, rank>
using index_type = typename buffer_type::index_type
using dimensions_type = typename buffer_type::dimensions_type
Detailed Description
template<typename Q, size_t rank, my_index_t pos_first_freq_index, class DataContainer>
class Spline< Q, rank, 3, pos_first_freq_index, DataContainer >
SplineK3 interpolation
Template Parameters
DataContainer contains vertex data and frequency grids frequencies. primary_grid and frequencies.secondary_grid computes partial derivative of data in x, y, z direction (and combinations of x/y/z)
Q double or comp
Definition at line 20 of file InterpolatorSpline3D.hpp.
Member Typedef Documentation
coeffs_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::coeffs_type = Eigen::Matrix<Q, Eigen::Dynamic,64> private
Definition at line 25 of file InterpolatorSpline3D.hpp.
frequencies_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::frequencies_type = std::array<double, 3> private
Definition at line 30 of file InterpolatorSpline3D.hpp.
index_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::index_type = typename DataContainer::index_type private
Definition at line 29 of file InterpolatorSpline3D.hpp.
Constructor & Destructor Documentation
Spline() [1/2]
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::Spline () inline
Definition at line 42 of file InterpolatorSpline3D.hpp.
: initialized(false) {};
Spline() [2/2]
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::Spline (double Lambda, index_type dims) inline explicit
Definition at line 43 of file InterpolatorSpline3D.hpp.
:   DataContainer(Lambda, dims), n(getFlatSize(DataContainer::get_dims())) {}
Member Function Documentation
get_coeffs_from_derivs()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs () const protected
known values of first or second derivative (corresponding to bd_type)
Definition at line 60 of file InterpolatorSpline3D.hpp.
{
    Eigen::Matrix<double,64,64> A;
    A <<
             1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
            -3, 3, 0, 0, 0, 0, 0, 0,   -2,-1, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             2,-2, 0, 0, 0, 0, 0, 0,    1, 1, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 3, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2,-1, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    2,-2, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 1, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
            //8:
            -3, 0, 3, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0,-1, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,   -3, 0, 3, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0,-1, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             9,-9,-9, 9, 0, 0, 0, 0,    6, 3,-6,-3, 0, 0, 0, 0,    6,-6, 3,-3, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    4, 2, 2, 1, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
            -6, 6, 6,-6, 0, 0, 0, 0,   -3,-3, 3, 3, 0, 0, 0, 0,   -4, 4,-2, 2, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2,-2,-1,-1, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             2, 0,-2, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 1, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    2, 0,-2, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 1, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
            -6, 6, 6,-6, 0, 0, 0, 0,   -4,-2, 4, 2, 0, 0, 0, 0,   -3, 3,-3, 3, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2,-1,-2,-1, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             4,-4,-4, 4, 0, 0, 0, 0,    2, 2,-2,-2, 0, 0, 0, 0,    2,-2, 2,-2, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 1, 1, 1, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
            //16:
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 3, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2,-1, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    2,-2, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 1, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 3, 0, 0, 0, 0, 0, 0,   -2,-1, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    2,-2, 0, 0, 0, 0, 0, 0,    1, 1, 0, 0, 0, 0, 0, 0,
            //24:
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 0, 3, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0,-1, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 0, 3, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0,-1, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    9,-9,-9, 9, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    6, 3,-6,-3, 0, 0, 0, 0,    6,-6, 3,-3, 0, 0, 0, 0,    4, 2, 2, 1, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -6, 6, 6,-6, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3,-3, 3, 3, 0, 0, 0, 0,   -4, 4,-2, 2, 0, 0, 0, 0,   -2,-2,-1,-1, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    2, 0,-2, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 1, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    2, 0,-2, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    1, 0, 1, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -6, 6, 6,-6, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -4,-2, 4, 2, 0, 0, 0, 0,   -3, 3,-3, 3, 0, 0, 0, 0,   -2,-1,-2,-1, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    4,-4,-4, 4, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    2, 2,-2,-2, 0, 0, 0, 0,    2,-2, 2,-2, 0, 0, 0, 0,    1, 1, 1, 1, 0, 0, 0, 0,
            //32:
            -3, 0, 0, 0, 3, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0, 0, 0,-1, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,   -3, 0, 0, 0, 3, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0, 0, 0,-1, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             9,-9, 0, 0,-9, 9, 0, 0,    6, 3, 0, 0,-6,-3, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    6,-6, 0, 0, 3,-3, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    4, 2, 0, 0, 2, 1, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
            -6, 6, 0, 0, 6,-6, 0, 0,   -3,-3, 0, 0, 3, 3, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -4, 4, 0, 0,-2, 2, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2,-2, 0, 0,-1,-1, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 0, 0, 0, 3, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0, 0, 0,-1, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3, 0, 0, 0, 3, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -2, 0, 0, 0,-1, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    9,-9, 0, 0,-9, 9, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    6, 3, 0, 0,-6,-3, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    6,-6, 0, 0, 3,-3, 0, 0,    4, 2, 0, 0, 2, 1, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -6, 6, 0, 0, 6,-6, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -3,-3, 0, 0, 3, 3, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,   -4, 4, 0, 0,-2, 2, 0, 0,   -2,-2, 0, 0,-1,-1, 0, 0,
            //40:
             9, 0,-9, 0,-9, 0, 9, 0,        0, 0, 0, 0, 0, 0, 0, 0,     6, 0, 3, 0,-6, 0,-3, 0,     6, 0,-6, 0, 3, 0,-3, 0,      0, 0, 0, 0, 0, 0, 0, 0,    0, 0, 0, 0, 0, 0, 0, 0,    4, 0, 2, 0, 2, 0, 1, 0,   0, 0, 0, 0, 0, 0, 0, 0,
             0, 0, 0, 0, 0, 0, 0, 0,        9, 0,-9, 0,-9, 0, 9, 0,     0, 0, 0, 0, 0, 0, 0, 0,     0, 0, 0, 0, 0, 0, 0, 0,      6, 0, 3, 0,-6, 0,-3, 0,    6, 0,-6, 0, 3, 0,-3, 0,    0, 0, 0, 0, 0, 0, 0, 0,   4, 0, 2, 0, 2, 0, 1, 0,
            -27,27,27,-27,27,-27,-27,27, -18,-9,18, 9,18, 9,-18,-9,   -18,18,-9, 9,18,-18, 9,-9,  -18,18,18,-18,-9, 9, 9,-9,   -12,-6,-6,-3,12, 6, 6, 3,  -12,-6,12, 6,-6,-3, 6, 3,  -12,12,-6, 6,-6, 6,-3, 3,  -8,-4,-4,-2,-4,-2,-2,-1,
            18,-18,-18,18,-18,18,18,-18,   9, 9,-9,-9,-9,-9, 9, 9,     12,-12, 6,-6,-12,12,-6, 6,  12,-12,-12,12, 6,-6,-6, 6,    6, 6, 3, 3,-6,-6,-3,-3,    6, 6,-6,-6, 3, 3,-3,-3,    8,-8, 4,-4, 4,-4, 2,-2,   4, 4, 2, 2, 2, 2, 1, 1,
            -6, 0, 6, 0,    6, 0,-6, 0,    0, 0, 0, 0,    0, 0, 0, 0,  -3, 0,-3, 0,   3, 0, 3, 0,  -4, 0, 4, 0,  -2, 0, 2, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -2, 0,-2, 0,  -1, 0,-1, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,   -6, 0, 6, 0,    6, 0,-6, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -3, 0,-3, 0,   3, 0, 3, 0,  -4, 0, 4, 0,  -2, 0, 2, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -2, 0,-2, 0,  -1, 0,-1, 0,
            18,-18,-18,18,-18,18,18,-18,  12, 6,-12,-6, -12,-6,12, 6,   9,-9, 9,-9,  -9, 9,-9, 9,  12,-12,-12,12, 6,-6,-6, 6,   6, 3, 6, 3,  -6,-3,-6,-3,   8, 4,-8,-4,   4, 2,-4,-2,   6,-6, 6,-6,   3,-3, 3,-3,   4, 2, 4, 2,   2, 1, 2, 1,
            -12,12,12,-12, 12,-12,-12,12, -6,-6, 6, 6,    6, 6,-6,-6,  -6, 6,-6, 6,   6,-6, 6,-6,  -8, 8, 8,-8,  -4, 4, 4,-4,  -3,-3,-3,-3,   3, 3, 3, 3,  -4,-4, 4, 4,  -2,-2, 2, 2,  -4, 4,-4, 4,  -2, 2,-2, 2,  -2,-2,-2,-2,  -1,-1,-1,-1,
            //48:
             2, 0, 0, 0,   -2, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,   1, 0, 0, 0,   1, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,    2, 0, 0, 0,  -2, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   1, 0, 0, 0,   1, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,
            -6, 6, 0, 0,    6,-6, 0, 0,   -4,-2, 0, 0,   4, 2, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,  -3, 3, 0, 0,  -3, 3, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -2,-1, 0, 0,  -2,-1, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             4,-4, 0, 0,   -4, 4, 0, 0,    2, 2, 0, 0,  -2,-2, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,   2,-2, 0, 0,   2,-2, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   1, 1, 0, 0,   1, 1, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,    2, 0, 0, 0,  -2, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   1, 0, 0, 0,   1, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   2, 0, 0, 0,  -2, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   1, 0, 0, 0,   1, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,   -6, 6, 0, 0,   6,-6, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -4,-2, 0, 0,   4, 2, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -3, 3, 0, 0,  -3, 3, 0, 0,  -2,-1, 0, 0,  -2,-1, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,    0, 0, 0, 0,   0, 0, 0, 0,    4,-4, 0, 0,  -4, 4, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   2, 2, 0, 0,  -2,-2, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   2,-2, 0, 0,   2,-2, 0, 0,   1, 1, 0, 0,   1, 1, 0, 0,
            //56:
            -6, 0, 6, 0,    6, 0,-6, 0,    0, 0, 0, 0,   0, 0, 0, 0,   -4, 0,-2, 0,   4, 0, 2, 0,  -3, 0, 3, 0,  -3, 0, 3, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -2, 0,-1, 0,  -2, 0,-1, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,   -6, 0, 6, 0,   6, 0,-6, 0,    0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -4, 0,-2, 0,   4, 0, 2, 0,  -3, 0, 3, 0,  -3, 0, 3, 0,   0, 0, 0, 0,   0, 0, 0, 0,  -2, 0,-1, 0,  -2, 0,-1, 0,
            18,-18,-18,18,-18,18,18,-18,  12, 6,-12,-6, -12,-6,12, 6,  12,-12, 6,-6,-12,12,-6, 6,   9,-9,-9, 9,   9,-9,-9, 9,   8, 4, 4, 2,  -8,-4,-4,-2,   6, 3,-6,-3,   6, 3,-6,-3,   6,-6, 3,-3,   6,-6, 3,-3,   4, 2, 2, 1,   4, 2, 2, 1,
           -12,12,12,-12,  12,-12,-12,12, -6,-6, 6, 6,   6, 6,-6,-6,   -8, 8,-4, 4,   8,-8, 4,-4,  -6, 6, 6,-6,  -6, 6, 6,-6,  -4,-4,-2,-2,   4, 4, 2, 2,  -3,-3, 3, 3,  -3,-3, 3, 3,  -4, 4,-2, 2,  -4, 4,-2, 2,  -2,-2,-1,-1,  -2,-2,-1,-1,
             4, 0,-4, 0,   -4, 0, 4, 0,    0, 0, 0, 0,   0, 0, 0, 0,    2, 0, 2, 0,  -2, 0,-2, 0,   2, 0,-2, 0,   2, 0,-2, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   1, 0, 1, 0,   1, 0, 1, 0,   0, 0, 0, 0,   0, 0, 0, 0,
             0, 0, 0, 0,    0, 0, 0, 0,    4, 0,-4, 0,  -4, 0, 4, 0,    0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   0, 0, 0, 0,   2, 0, 2, 0,  -2, 0,-2, 0,   2, 0,-2, 0,   2, 0,-2, 0,   0, 0, 0, 0,   0, 0, 0, 0,   1, 0, 1, 0,   1, 0, 1, 0,
            -12,12,12,-12, 12,-12,-12,12, -8,-4, 8, 4,   8, 4,-8,-4,   -6, 6,-6, 6,   6,-6, 6,-6,  -6, 6, 6,-6,  -6, 6, 6,-6,  -4,-2,-4,-2,   4, 2, 4, 2,  -4,-2, 4, 2,  -4,-2, 4, 2,  -3, 3,-3, 3,  -3, 3,-3, 3,  -2,-1,-2,-1,  -2,-1,-2,-1,
             8,-8,-8, 8,   -8, 8, 8,-8,    4, 4,-4,-4,  -4,-4, 4, 4,    4,-4, 4,-4,  -4, 4,-4, 4,   4,-4,-4, 4,   4,-4,-4, 4,   2, 2, 2, 2,  -2,-2,-2,-2,   2, 2,-2,-2,   2, 2,-2,-2,   2,-2, 2,-2,   2,-2, 2,-2,   1, 1, 1, 1,   1, 1, 1, 1;
    const size_t n_x = DataContainer::frequencies.  primary_grid.get_all_frequencies().size();
    const size_t n_y = DataContainer::frequencies.secondary_grid.get_all_frequencies().size();
    const size_t n_z = DataContainer::frequencies. tertiary_grid.get_all_frequencies().size();
    const size_t n_nonx = n/n_x/n_y/n_z;
    for (size_t i = 0; i < n_nonx; i++) {
        for (size_t j = 0; j < n_x-1; j++) {
            for (size_t k = 0; k < n_y-1; k++) {
                for (size_t l = 0; l < n_z - 1; l++) {
                    const double dw = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(j+1) - DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(j);
                    const double dv = DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(k+1) - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(k);
                    const double dvp= DataContainer::frequencies. tertiary_grid.get_auxiliary_gridpoint(l+1) - DataContainer::frequencies. tertiary_grid.get_auxiliary_gridpoint(l);
                    int idx_base_base_base = ::rotateFlatIndex(i*n_x*n_y*n_z + (j  )*n_y*n_z + (k  )*n_z + l  , DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_plus_base_base = ::rotateFlatIndex(i*n_x*n_y*n_z + (j+1)*n_y*n_z + (k  )*n_z + l  , DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_base_plus_base = ::rotateFlatIndex(i*n_x*n_y*n_z + (j  )*n_y*n_z + (k+1)*n_z + l  , DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_plus_plus_base = ::rotateFlatIndex(i*n_x*n_y*n_z + (j+1)*n_y*n_z + (k+1)*n_z + l  , DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_base_base_plus = ::rotateFlatIndex(i*n_x*n_y*n_z + (j  )*n_y*n_z + (k  )*n_z + l+1, DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_plus_base_plus = ::rotateFlatIndex(i*n_x*n_y*n_z + (j+1)*n_y*n_z + (k  )*n_z + l+1, DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_base_plus_plus = ::rotateFlatIndex(i*n_x*n_y*n_z + (j  )*n_y*n_z + (k+1)*n_z + l+1, DataContainer::get_dims(), pos_first_freq_index+2);
                    int idx_plus_plus_plus = ::rotateFlatIndex(i*n_x*n_y*n_z + (j+1)*n_y*n_z + (k+1)*n_z + l+1, DataContainer::get_dims(), pos_first_freq_index+2);
                    Eigen::Matrix<Q,64,1> _fs;
                    _fs << DataContainer::data[idx_base_base_base],   DataContainer::data[idx_plus_base_base],   DataContainer::data[idx_base_plus_base],   DataContainer::data[idx_plus_plus_base],   DataContainer::data[idx_base_base_plus],   DataContainer::data[idx_plus_base_plus],   DataContainer::data[idx_base_plus_plus],   DataContainer::data[idx_plus_plus_plus],
                                dw * m_deriv_x[idx_base_base_base],        dw * m_deriv_x[idx_plus_base_base],        dw * m_deriv_x[idx_base_plus_base],        dw * m_deriv_x[idx_plus_plus_base],        dw * m_deriv_x[idx_base_base_plus],        dw * m_deriv_x[idx_plus_base_plus],        dw * m_deriv_x[idx_base_plus_plus],        dw * m_deriv_x[idx_plus_plus_plus],
                                dv * m_deriv_y[idx_base_base_base],        dv * m_deriv_y[idx_plus_base_base],        dv * m_deriv_y[idx_base_plus_base],        dv * m_deriv_y[idx_plus_plus_base],        dv * m_deriv_y[idx_base_base_plus],        dv * m_deriv_y[idx_plus_base_plus],        dv * m_deriv_y[idx_base_plus_plus],        dv * m_deriv_y[idx_plus_plus_plus],
                                dvp* m_deriv_z[idx_base_base_base],        dvp* m_deriv_z[idx_plus_base_base],        dvp* m_deriv_z[idx_base_plus_base],        dvp* m_deriv_z[idx_plus_plus_base],        dvp* m_deriv_z[idx_base_base_plus],        dvp* m_deriv_z[idx_plus_base_plus],        dvp* m_deriv_z[idx_base_plus_plus],        dvp* m_deriv_z[idx_plus_plus_plus],
                            dw*dv * m_deriv_xy[idx_base_base_base],    dw*dv * m_deriv_xy[idx_plus_base_base],    dw*dv * m_deriv_xy[idx_base_plus_base],    dw*dv * m_deriv_xy[idx_plus_plus_base],    dw*dv * m_deriv_xy[idx_base_base_plus],    dw*dv * m_deriv_xy[idx_plus_base_plus],    dw*dv * m_deriv_xy[idx_base_plus_plus],    dw*dv * m_deriv_xy[idx_plus_plus_plus],
                            dw*dvp* m_deriv_xz[idx_base_base_base],    dw*dvp* m_deriv_xz[idx_plus_base_base],    dw*dvp* m_deriv_xz[idx_base_plus_base],    dw*dvp* m_deriv_xz[idx_plus_plus_base],    dw*dvp* m_deriv_xz[idx_base_base_plus],    dw*dvp* m_deriv_xz[idx_plus_base_plus],    dw*dvp* m_deriv_xz[idx_base_plus_plus],    dw*dvp* m_deriv_xz[idx_plus_plus_plus],
                            dv*dvp* m_deriv_yz[idx_base_base_base],    dv*dvp* m_deriv_yz[idx_plus_base_base],    dv*dvp* m_deriv_yz[idx_base_plus_base],    dv*dvp* m_deriv_yz[idx_plus_plus_base],    dv*dvp* m_deriv_yz[idx_base_base_plus],    dv*dvp* m_deriv_yz[idx_plus_base_plus],    dv*dvp* m_deriv_yz[idx_base_plus_plus],    dv*dvp* m_deriv_yz[idx_plus_plus_plus],
                        dw*dv*dvp* m_deriv_xyz[idx_base_base_base],dw*dv*dvp* m_deriv_xyz[idx_plus_base_base],dw*dv*dvp* m_deriv_xyz[idx_base_plus_base],dw*dv*dvp* m_deriv_xyz[idx_plus_plus_base],dw*dv*dvp* m_deriv_xyz[idx_base_base_plus],dw*dv*dvp* m_deriv_xyz[idx_plus_base_plus],dw*dv*dvp* m_deriv_xyz[idx_base_plus_plus],dw*dv*dvp* m_deriv_xyz[idx_plus_plus_plus];
                    all_coefficients.row(idx_base_base_base) = (A * _fs).transpose();
                    for (int i1 = 0; i1 < 4; i1++) {
                        for (int i2 = 0; i2 < 4; i2++) {
                            for (int i3 = 0; i3 < 4; i3++) {
                                all_coefficients(idx_base_base_base, i1 * 16 + i2 * 4 + i3) /= (pow(dvp, i1) * pow(dv, i2) * pow(dw, i3));
                            }
                        }
                    }
                }
            }
        }
    }
    /*
    int iK = indices[my_defs::K3::keldysh];
    int spin = indices[my_defs::K3::spin];
    int iw = indices[my_defs::K3::omega];
    int iv = indices[my_defs::K3::nu];
    int ivp= indices[my_defs::K3::nup];
    int i_in = indices[my_defs::K3::internal];
    const vec<Q> fs = {
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
            DataContainer::data[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dw * m_deriv_x[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dv * m_deriv_y[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
                 dvp* m_deriv_z[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dv * m_deriv_xy[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
             dw*dvp* m_deriv_xz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
             dv*dvp* m_deriv_yz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp    , iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp    , iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp    , iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv    , ivp + 1, iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw    , iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
         dw*dv*dvp* m_deriv_xyz[::getFlatIndex<6,int,int,int,int,int,int>(spin, iw + 1, iv + 1, ivp + 1, iK, i_in, DataContainer::get_dims())],
    };
    //vec<Q> coeffs = vec<Q> (64);
    //for (int i = 0; i<64; i++) {
    //    coeffs[i] = 0.;
    //    for (int j = 0; j<64; j++) {
    //        coeffs[i] += A[i][j] * fs[j];
    //    }
    //}
    const vec<Q> coeffs = {
    fs[0]
    ,fs[8]
    ,3.*(-fs[0]+fs[1]) -2.*fs[8] -fs[9]
    ,2.*(fs[0]-fs[1]) +fs[8] +fs[9]
    ,fs[16]
    ,fs[32]
    ,3.*(-fs[16]+fs[17]) -2.*fs[32] -fs[33]
    ,2.*(fs[16]-fs[17]) +fs[32] +fs[33]
    ,3.*(-fs[0]+fs[2]) -2.*fs[16] -fs[18]
    ,3.*(-fs[8]+fs[10])-2.*fs[32] -fs[34]
    , 9.*(fs[0]-fs[1]-fs[2]+fs[3]) + 6.*(fs[8]-fs[10]+fs[16]-fs[17]) + 3.*(fs[9]-fs[11]+fs[18]-fs[19]) + 4.*fs[32] + 2.*(fs[33]+fs[34]) + fs[35]
    , 6.*(-fs[0]+fs[1]+fs[2]-fs[3]) +3.*(-fs[8]-fs[9]+fs[10]+fs[11]) +4.*(-fs[16]+fs[17]) +2.*(-fs[18]+fs[19]-fs[32]-fs[33]) +(-fs[34]-fs[35])
    , 2.*(fs[0]-fs[2]) +fs[16] +fs[18]
    , 2.*(fs[8]-fs[10]) +fs[32] +fs[34]
    , 6.*(-fs[0]+fs[1]+fs[2]-fs[3]) +4.*(-fs[8]+fs[10]) +2.*(-fs[9]+fs[11]-fs[32]-fs[34]) +3.*(-fs[16]+fs[17]-fs[18]+fs[19]) +(-fs[33]-fs[35])
    , 4.*(fs[0]-fs[1]-fs[2]+fs[3]) +2.*(fs[8]+fs[9]-fs[10]-fs[11]+fs[16]-fs[17]+fs[18]-fs[19]) + fs[32]+fs[33]+fs[34]+fs[35]
    , fs[24]
    , fs[40]
    , 3.*(-fs[24]+fs[25]) -2.*fs[40] -fs[41]
    , 2.*(fs[24]-fs[25]) +fs[40] +fs[41]
    , fs[48]
    , fs[56]
    , 3.*(-fs[48]+fs[49]) -2.*fs[56] -fs[57]
    , 2.*(fs[48]-fs[49]) +fs[56] +fs[57]
    , 3.*(-fs[24]+fs[26]) -2.*fs[48] -fs[50]
    , 3.*(-fs[40]+fs[42]) -2.*fs[56] -fs[58]
    , 9.*(fs[24]-fs[25]-fs[26]+fs[27]) + 6.*(fs[40]-fs[42]+fs[48]-fs[49]) + 3.*(fs[41]-fs[43]+fs[50]-fs[51]) + 4.*fs[56] + 2.*(fs[57]+fs[58]) + fs[59]
    , 6.*(-fs[24]+fs[25]+fs[26]-fs[27]) +3.*(-fs[40]-fs[41]+fs[42]+fs[43]) +4.*(-fs[48]+fs[49]) +2.*(-fs[50]+fs[51]-fs[56]-fs[57]) +(-fs[58]-fs[59])
    , 2.*(fs[24]-fs[26]) +fs[48] +fs[50]
    , 2.*(fs[40]-fs[42]) +fs[56] +fs[58]
    , 6.*(-fs[24]+fs[25]+fs[26]-fs[27]) +4.*(-fs[40]+fs[42]) +2.*(-fs[41]+fs[43]-fs[56]-fs[58]) +3.*(-fs[48]+fs[49]-fs[50]+fs[51]) +(-fs[57]-fs[59])
    , 4.*(fs[24]-fs[25]-fs[26]+fs[27]) +2.*(fs[40]+fs[41]-fs[42]-fs[43]+fs[48]-fs[49]+fs[50]-fs[51]) + fs[56]+fs[57]+fs[58]+fs[59]
    , 3.*(-fs[0]+fs[4]) -2.*fs[24] -fs[28]
    , 3.*(-fs[8]+fs[12]) -2.*fs[40] -fs[44]
    , 9.*(fs[0]-fs[1]-fs[4]+fs[5]) + 6.*(fs[8]-fs[12]+fs[24]-fs[25]) + 3.*(fs[9]-fs[13]+fs[28]-fs[29]) + 4.*fs[40] + 2.*(fs[41]+fs[44]) + fs[45]
    , 6.*(-fs[0]+fs[1]+fs[4]-fs[5]) +3.*(-fs[8]-fs[9]+fs[12]+fs[13]) +4.*(-fs[24]+fs[25]) +2.*(-fs[28]+fs[29]-fs[40]-fs[41]) +(-fs[44]-fs[45])
    , 3.*(-fs[16]+fs[20]) -2.*fs[48] -fs[52]
    , 3.*(-fs[32]+fs[36]) -2.*fs[56] -fs[60]
    , 9.*(fs[16]-fs[17]-fs[20]+fs[21]) + 6.*(fs[32]-fs[36]+fs[48]-fs[49]) + 3.*(fs[33]-fs[37]+fs[52]-fs[53]) + 4.*fs[56] + 2.*(fs[57]+fs[60]) + fs[61]
    , 6.*(-fs[16]+fs[17]+fs[20]-fs[21]) +3.*(-fs[32]-fs[33]+fs[36]+fs[37]) +4.*(-fs[48]+fs[49]) +2.*(-fs[52]+fs[53]-fs[56]-fs[57]) +(-fs[60]-fs[61])
    , 9.*(fs[0]-fs[2]-fs[4]+fs[6]) + 6.*(fs[16]-fs[20]+fs[24]-fs[26]) + 3.*(fs[18]-fs[22]+fs[28]-fs[30]) + 4.*fs[48] + 2.*(fs[50]+fs[52]) + fs[54]
    , 9.*(fs[8]-fs[10]-fs[12]+fs[14]) + 6.*(fs[32]-fs[36]+fs[40]-fs[42]) + 3.*(fs[34]-fs[38]+fs[44]-fs[46]) + 4.*fs[56] + 2.*(fs[58]+fs[60]) + fs[62]
    , 27.*(-fs[0]+fs[1]+fs[2]-fs[3]+fs[4]-fs[5]-fs[6]+fs[7]) +18.*(-fs[8]+fs[10]+fs[12]-fs[14]-fs[16]+fs[17]+fs[20]-fs[21]-fs[24]+fs[25]+fs[26]-fs[27]) +9.*(-fs[9]+fs[11]+fs[13]-fs[15]-fs[18]+fs[19]+fs[22]-fs[23]-fs[28]+fs[29]+fs[30]-fs[31]) -8.*fs[56] +12.*(-fs[32]+fs[36]-fs[40]+fs[42]-fs[48]+fs[49]) +6.*(-fs[33]-fs[34]+fs[37]+fs[38]-fs[41]+fs[43]-fs[44]+fs[46]-fs[50]+fs[51]-fs[52]+fs[53]) +3.*(-fs[35]+fs[39]-fs[45]+fs[47]-fs[54]+fs[55]) + 4.*(-fs[57]-fs[58]-fs[60]) +2.*(-fs[59]-fs[61]-fs[62]) -fs[63]
    , 18.*(fs[0]-fs[1]-fs[2]+fs[3]-fs[4]+fs[5]+fs[6]-fs[7]) +9.*(fs[8]+fs[9]-fs[10]-fs[11]-fs[12]-fs[13]+fs[14]+fs[15]) +12.*(fs[16]-fs[17]-fs[20]+fs[21]+fs[24]-fs[25]-fs[26]+fs[27]) +6.*(fs[18]-fs[19]-fs[22]+fs[23]+fs[28]-fs[29]-fs[30]+fs[31]+fs[32]+fs[33]-fs[36]-fs[37]+fs[40]+fs[41]-fs[42]-fs[43]) +3.*(fs[34]+fs[35]-fs[38]-fs[39]+fs[44]+fs[45]-fs[46]-fs[47]) +8.*(fs[48]-fs[49]) +4.*(fs[50]-fs[51]+fs[52]-fs[53]+fs[56]+fs[57]) +2.*(fs[54]-fs[55]+fs[58]+fs[59]+fs[60]+fs[61]) + fs[62]+fs[63]
    , 6.*(-fs[0]+fs[2]+fs[4]-fs[6]) +3.*(-fs[16]-fs[18]+fs[20]+fs[22]) +4.*(-fs[24]+fs[26]) +2.*(-fs[28]+fs[30]-fs[48]-fs[50]) +(-fs[52]-fs[54])
    , 6.*(-fs[8]+fs[10]+fs[12]-fs[14]) +3.*(-fs[32]-fs[34]+fs[36]+fs[38]) +4.*(-fs[40]+fs[42]) +2.*(-fs[44]+fs[46]-fs[56]-fs[58]) +(-fs[60]-fs[62])
    , 18.*(fs[0]-fs[1]-fs[2]+fs[3]-fs[4]+fs[5]+fs[6]-fs[7]) +9.*(fs[16]-fs[17]+fs[18]-fs[19]-fs[20]+fs[21]-fs[22]+fs[23]) +12.*(fs[8]-fs[10]-fs[12]+fs[14]+fs[24]-fs[25]-fs[26]+fs[27]) +6.*(fs[9]-fs[11]-fs[13]+fs[15]+fs[28]-fs[29]-fs[30]+fs[31]+fs[32]+fs[34]-fs[36]-fs[38]+fs[48]-fs[49]+fs[50]-fs[51]) +3.*(fs[33]+fs[35]-fs[37]-fs[39]+fs[52]-fs[53]+fs[54]-fs[55]) +8.*(fs[40]-fs[42]) +4.*(fs[41]-fs[43]+fs[44]-fs[46]+fs[56]+fs[58]) +2.*(fs[45]-fs[47]+fs[57]+fs[59]+fs[60]+fs[62]) + fs[61]+fs[63]
    , 12.*(-fs[0]+fs[1]+fs[2]-fs[3]+fs[4]-fs[5]-fs[6]+fs[7]) +6.*(-fs[8]-fs[9]+fs[10]+fs[11]+fs[12]+fs[13]-fs[14]-fs[15]-fs[16]+fs[17]-fs[18]+fs[19]+fs[20]-fs[21]+fs[22]-fs[23]) +8.*(-fs[24]+fs[25]+fs[26]-fs[27]) +4.*(-fs[28]+fs[29]+fs[30]-fs[31]-fs[40]-fs[41]+fs[42]+fs[43]-fs[48]+fs[49]-fs[50]+fs[51]) +3.*(-fs[32]-fs[33]-fs[34]-fs[35]+fs[36]+fs[37]+fs[38]+fs[39]) +2.*(-fs[44]-fs[45]+fs[46]+fs[47]-fs[52]+fs[53]-fs[54]+fs[55]-fs[56]-fs[57]-fs[58]-fs[59]) -fs[60]-fs[61]-fs[62]-fs[63]
    , 2.*(fs[0]-fs[4]) +fs[24] +fs[28]
    , 2.*(fs[8]-fs[12]) +fs[40] +fs[44]
    , 6.*(-fs[0]+fs[1]+fs[4]-fs[5]) +3.*(-fs[24]+fs[25]-fs[28]+fs[29]) +4.*(-fs[8]+fs[12]) +2.*(-fs[9]+fs[13]-fs[40]-fs[44]) +(-fs[41]-fs[45])
    , 4.*(fs[0]-fs[1]-fs[4]+fs[5]) +2.*(fs[8]+fs[9]-fs[12]-fs[13]+fs[24]-fs[25]+fs[28]-fs[29]) + fs[40]+fs[41]+fs[44]+fs[45]
    , 2.*(fs[16]-fs[20]) +fs[48] +fs[52]
    , 2.*(fs[32]-fs[36]) +fs[56] +fs[60]
    , 6.*(-fs[16]+fs[17]+fs[20]-fs[21]) +3.*(-fs[48]+fs[49]-fs[52]+fs[53]) +4.*(-fs[32]+fs[36]) +2.*(-fs[33]+fs[37]-fs[56]-fs[60]) +(-fs[57]-fs[61])
    , 4.*(fs[16]-fs[17]-fs[20]+fs[21]) +2.*(fs[32]+fs[33]-fs[36]-fs[37]+fs[48]-fs[49]+fs[52]-fs[53]) + fs[56]+fs[57]+fs[60]+fs[61]
    , 6.*(-fs[0]+fs[2]+fs[4]-fs[6]) +3.*(-fs[24]+fs[26]-fs[28]+fs[30]) +4.*(-fs[16]+fs[20]) +2.*(-fs[18]+fs[22]-fs[48]-fs[52]) +(-fs[50]-fs[54])
    , 6.*(-fs[8]+fs[10]+fs[12]-fs[14]) +3.*(-fs[40]+fs[42]-fs[44]+fs[46]) +4.*(-fs[32]+fs[36]) +2.*(-fs[34]+fs[38]-fs[56]-fs[60]) +(-fs[58]-fs[62])
    , 18.*(fs[0]-fs[1]-fs[2]+fs[3]-fs[4]+fs[5]+fs[6]-fs[7]) +9.*(fs[24]-fs[25]-fs[26]+fs[27]+fs[28]-fs[29]-fs[30]+fs[31]) +12.*(fs[8]-fs[10]-fs[12]+fs[14]+fs[16]-fs[17]-fs[20]+fs[21]) +6.*(fs[9]-fs[11]-fs[13]+fs[15]+fs[18]-fs[19]-fs[22]+fs[23] +fs[40]-fs[42]+fs[44]-fs[46]+fs[48]-fs[49]+fs[52]-fs[53]) +3.*(fs[41]-fs[43]+fs[45]-fs[47]+fs[50]-fs[51]+fs[54]-fs[55]) +8.*(fs[32]-fs[36]) +4.*(fs[33]+fs[34]-fs[37]-fs[38]+fs[56]+fs[60]) +2.*(fs[35]-fs[39]+fs[57]+fs[58]+fs[61]+fs[62]) + fs[59]+fs[63]
    , 12.*(-fs[0]+fs[1]+fs[2]-fs[3]+fs[4]-fs[5]-fs[6]+fs[7]) +6.*(-fs[8]-fs[9]+fs[10]+fs[11]+fs[12]+fs[13]-fs[14]-fs[15] -fs[24]+fs[25]+fs[26]-fs[27]-fs[28]+fs[29]+fs[30]-fs[31]) +8.*(-fs[16]+fs[17]+fs[20]-fs[21]) +4.*(-fs[18]+fs[19]+fs[22]-fs[23]-fs[32]-fs[33]+fs[36]+fs[37]-fs[48]+fs[49]-fs[52]+fs[53]) +3.*(-fs[40]-fs[41]+fs[42]+fs[43]-fs[44]-fs[45]+fs[46]+fs[47]) +2.*(-fs[34]-fs[35]+fs[38]+fs[39]-fs[50]+fs[51]-fs[54]+fs[55]-fs[56]-fs[57]-fs[60]-fs[61]) -fs[58]-fs[59]-fs[62]-fs[63]
    , 4.*(fs[0]-fs[2]-fs[4]+fs[6]) +2.*(fs[16]+fs[18]-fs[20]-fs[22]+fs[24]-fs[26]+fs[28]-fs[30]) + fs[48]+fs[50]+fs[52]+fs[54]
    , 4.*(fs[8]-fs[10]-fs[12]+fs[14]) +2.*(fs[32]+fs[34]-fs[36]-fs[38]+fs[40]-fs[42]+fs[44]-fs[46]) + fs[56]+fs[58]+fs[60]+fs[62]
    ,  12.*(-fs[0]+fs[1]+fs[2]-fs[3]+fs[4]-fs[5]-fs[6]+fs[7]) +6.*(-fs[16]+fs[17]-fs[18]+fs[19]+fs[20]-fs[21]+fs[22]-fs[23] -fs[24]+fs[25]+fs[26]-fs[27]-fs[28]+fs[29]+fs[30]-fs[31]) +8.*(-fs[8]+fs[10]+fs[12]-fs[14]) +4.*(-fs[9]+fs[11]+fs[13]-fs[15]-fs[32]-fs[34]+fs[36]+fs[38]-fs[40]+fs[42]-fs[44]+fs[46]) +3.*(-fs[48]+fs[49]-fs[50]+fs[51]-fs[52]+fs[53]-fs[54]+fs[55]) +2.*(-fs[33]-fs[35]+fs[37]+fs[39]-fs[41]+fs[43]-fs[45]+fs[47]-fs[56]-fs[58]-fs[60]-fs[62]) -fs[57]-fs[59]-fs[61]-fs[63]
    , 8.*(fs[0]-fs[1]-fs[2]+fs[3]-fs[4]+fs[5]+fs[6]-fs[7]) +4.*(fs[8]+fs[9]-fs[10]-fs[11]-fs[12]-fs[13]+fs[14]+fs[15] +fs[16]-fs[17]+fs[18]-fs[19]-fs[20]+fs[21]-fs[22]+fs[23] +fs[24]-fs[25]-fs[26]+fs[27]+fs[28]-fs[29]-fs[30]+fs[31]) +2.*(fs[32]+fs[33]+fs[34]+fs[35]-fs[36]-fs[37]-fs[38]-fs[39] +fs[40]+fs[41]-fs[42]-fs[43]+fs[44]+fs[45]-fs[46]-fs[47] +fs[48]-fs[49]+fs[50]-fs[51]+fs[52]-fs[53]+fs[54]-fs[55]) +(fs[56]+fs[57]+fs[58]+fs[59]+fs[60]+fs[61]+fs[62]+fs[63])
    };
    return coeffs;
     */
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, dataContainerBase< Q, rank >::get_dims(), and rotateFlatIndex().
get_weights()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Eigen::Matrix< Q, 64, 1 > Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_weights (const std::array< my_index_t, 3 > & freq_idx, const std::array< double, 3 > & dw_normalized) const
Definition at line 373 of file InterpolatorSpline3D.hpp.
{
    //const double dw = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw+1) - DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw);
    //const double dv = DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv+1) - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv);
    const double hw = dt_unnormalized[0];
    const double hv = dt_unnormalized[1];
    const double hvp= dt_unnormalized[2];
    Eigen::Matrix<Q,64,1> weights;
    const double dwpow[4] = {1, hw , hw *hw , hw *hw *hw };
    const double dvpow[4] = {1, hv , hv *hv , hv *hv *hv };
    const double dvppow[4]= {1, hvp, hvp*hvp, hvp*hvp*hvp};
    for (int i = 0; i<4; i++) {
        for (int j = 0; j<4; j++) {
            for (int k = 0; k<4; k++) {
                weights(i * 16 + j * 4 + k) = dvppow[i] * dvpow[j] * dwpow[k];
            }
        }
    }
    assert(weights.allFinite());
    return weights;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
initInterpolator()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator () const
Definition at line 348 of file InterpolatorSpline3D.hpp.
{
    multidimensional::multiarray<Q,rank> temp = DataContainer::get_deriv_x();
    m_deriv_x =  vec<Q>(temp.begin(), temp.end());
    temp =  DataContainer::get_deriv_y();
    m_deriv_y =  vec<Q>(temp.begin(), temp.end());
    temp =  DataContainer::get_deriv_z();
    m_deriv_z =  vec<Q>(temp.begin(), temp.end());
    temp = DataContainer::get_deriv_xy();
    m_deriv_xy = vec<Q>(temp.begin(), temp.end());
    temp = DataContainer::get_deriv_xz();
    m_deriv_xz = vec<Q>(temp.begin(), temp.end());
    temp = DataContainer::get_deriv_yz();
    m_deriv_yz = vec<Q>(temp.begin(), temp.end());
    temp = DataContainer::get_deriv_xyz();
    m_deriv_xyz = vec<Q>(temp.begin(), temp.end());
    all_coefficients = coeffs_type(n,64);
    get_coeffs_from_derivs();
    initialized = true;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xy(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xyz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_y(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yz(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_z().
interpolate_spline()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > template<typename result_type > result_type Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::interpolate_spline (const frequencies_type & frequencies, const index_type & indices) const
Definition at line 399 of file InterpolatorSpline3D.hpp.
{
    assert(initialized);
    std::array<my_index_t,3> freq_idx;
    std::array<double,3> dt_unnormalized;
    DataContainer::frequencies.get_auxgrid_index_unnormalized(freq_idx, dt_unnormalized, frequencies);
    //double tw;
    //const size_t iw=DataContainer::frequencies.  primary_grid.get_grid_index(tw, frequencies[0]);
    //double tv;
    //const size_t iv=DataContainer::frequencies.secondary_grid.get_grid_index(tv, frequencies[1]);
    //double tvp;
    //const size_t ivp=DataContainer::frequencies.secondary_grid.get_grid_index(tvp, frequencies[2]);
    index_type index_temp = indices;
    index_temp[pos_first_freq_index  ] = freq_idx[0];
    index_temp[pos_first_freq_index+1] = freq_idx[1];
    index_temp[pos_first_freq_index+2] = freq_idx[2];
    const int i_row = getFlatIndex<rank>(index_temp, DataContainer::get_dims());
    Eigen::Matrix<Q,64,1> weights = get_weights(freq_idx, dt_unnormalized);
    if constexpr(std::is_same_v<result_type,Q>) {
        Q result;
        Eigen::Matrix<Q, 1, 64> values = all_coefficients.row(i_row);
        result = (values * weights).eval()[0];
        assert(isfinite(result));
        return result;
    }
    else if constexpr(std::is_same_v<result_type,Eigen::Matrix<Q,result_type::RowsAtCompileTime,1>>){
        Eigen::Matrix<Q,result_type::RowsAtCompileTime,1> result;
        Eigen::Matrix<Q, result_type::RowsAtCompileTime, 64> values = all_coefficients.template block<result_type::RowsAtCompileTime,64>(i_row,0);
        result = (values * weights).eval();
        assert(result.allFinite());
        return result;
    }
    else {
        assert(false);
        result_type result;
        return result;
    }
    //const double dw = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw +1) - DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw );
    //const double dv = DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv +1) - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv );
    //const double dvp= DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(ivp+1) - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(ivp);
    //const double hw = (tw - DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw )) / dw;
    //const double hv = (tv - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv )) / dv;
    //const double hvp= (tvp- DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(ivp)) / dvp;
    //const vec<Q> coeffs = get_coeffs_from_derivs(index_temp, dw, dv, dvp);
//
    //Q result = 0.;
    //const std::array<size_t,3> dims = {4,4,4};
//
    //const double dwpow[4] = {1, hw , hw*hw  , hw*hw*hw  };
    //const double dvpow[4] = {1, hv , hv*hv  , hv*hv*hv  };
    //const double dvppow[4]= {1, hvp, hvp*hvp, hvp*hvp*hvp};
    //for (int i = 0; i<4; i++) {
    //    for (int j = 0; j<4; j++) {
    //        for (int k = 0; k<4; k++) {
    //            result += coeffs[::getFlatIndex<3,int,int,int>(i, j, k, dims)] * dvppow[i] * dvpow[j] * dwpow[k];
    //        }
    //    }
    //}
//
    //assert(my_isfinite(result));
    //return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, and dataContainerBase< Q, rank >::get_dims().
set_initializedInterpol()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::set_initializedInterpol (bool is_init) const inline
Definition at line 47 of file InterpolatorSpline3D.hpp.
{initialized = is_init;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Member Data Documentation
all_coefficients
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > coeffs_type Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::all_coefficients mutable private
Definition at line 26 of file InterpolatorSpline3D.hpp.
initialized
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bool Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initialized = false mutable
Definition at line 41 of file InterpolatorSpline3D.hpp.
m_deriv_x
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_x = vec<Q>(n) mutable protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_deriv_xy
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_xy = vec<Q>(n) protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_deriv_xyz
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_xyz = vec<Q>(n) protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_deriv_xz
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_xz = vec<Q>(n) protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_deriv_y
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_y = vec<Q>(n) protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_deriv_yz
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_yz = vec<Q>(n) protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_deriv_z
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_deriv_z = vec<Q>(n) protected
Definition at line 33 of file InterpolatorSpline3D.hpp.
m_left
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bd_type Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_left = third_deriv protected
Definition at line 35 of file InterpolatorSpline3D.hpp.
m_left_value
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Q Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_left_value = 0.0 protected
set const?
Definition at line 36 of file InterpolatorSpline3D.hpp.
m_right
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bd_type Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_right = third_deriv protected
Definition at line 35 of file InterpolatorSpline3D.hpp.
m_right_value
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Q Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::m_right_value = 0.0 protected
Definition at line 36 of file InterpolatorSpline3D.hpp.
n
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > size_t Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::n =0 protected
Definition at line 32 of file InterpolatorSpline3D.hpp.
The documentation for this class was generated from the following file:
InterpolatorSpline3D.hpp