SIAM-Keldysh-mfRG: ode_solver_impl::butcher_tableau< stages > Struct Template Reference
ode_solver_impl::butcher_tableau< stages > Struct Template Reference
#include <ODE_solvers.hpp>
Public Member Functions
double get_a (size_t row_index, size_t column_index) const
double get_node (size_t stage) const
double get_error_b (size_t stage) const
Public Attributes
const std::array< double,(stages - 1) *(stages - 1)> a
const std::array< double, stages > b_high
const std::array< double, stages > b_low
const std::array< double, stages - 1 > c
const bool adaptive
const std::string name
Detailed Description
template<size_t stages>
struct ode_solver_impl::butcher_tableau< stages >
Definition at line 188 of file ODE_solvers.hpp.
Member Function Documentation
get_a()
template<size_t stages> double ode_solver_impl::butcher_tableau< stages >::get_a (size_t row_index, size_t column_index) const inline
Definition at line 203 of file ODE_solvers.hpp.
        {
            // 0th row and last column are 0.
            if (row_index == 0 || column_index == stages)
            {
                return 0.;
            }
            assert((row_index - 1) * (stages - 1) + column_index >= 0);
            return a[(row_index - 1) * (stages - 1) + column_index];
        }
References ode_solver_impl::butcher_tableau< stages >::a, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_error_b()
template<size_t stages> double ode_solver_impl::butcher_tableau< stages >::get_error_b (size_t stage) const inline
Definition at line 224 of file ODE_solvers.hpp.
        {
            return b_high[stage] - b_low[stage];
        }
References ode_solver_impl::butcher_tableau< stages >::b_high, ode_solver_impl::butcher_tableau< stages >::b_low, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_node()
template<size_t stages> double ode_solver_impl::butcher_tableau< stages >::get_node (size_t stage) const inline
Definition at line 214 of file ODE_solvers.hpp.
        {
            if (stage == 0)
            {
                return 0.;
            }
            return c[stage - 1];
        }
References ode_solver_impl::butcher_tableau< stages >::c, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Member Data Documentation
a
template<size_t stages> const std::array<double, (stages - 1) * (stages - 1)> ode_solver_impl::butcher_tableau< stages >::a
Definition at line 191 of file ODE_solvers.hpp.
Referenced by ode_solver_impl::butcher_tableau< stages >::get_a().
adaptive
template<size_t stages> const bool ode_solver_impl::butcher_tableau< stages >::adaptive
Definition at line 197 of file ODE_solvers.hpp.
b_high
template<size_t stages> const std::array<double, stages> ode_solver_impl::butcher_tableau< stages >::b_high
Definition at line 193 of file ODE_solvers.hpp.
Referenced by ode_solver_impl::butcher_tableau< stages >::get_error_b().
b_low
template<size_t stages> const std::array<double, stages> ode_solver_impl::butcher_tableau< stages >::b_low
Definition at line 194 of file ODE_solvers.hpp.
Referenced by ode_solver_impl::butcher_tableau< stages >::get_error_b().
c
template<size_t stages> const std::array<double, stages - 1> ode_solver_impl::butcher_tableau< stages >::c
Definition at line 196 of file ODE_solvers.hpp.
Referenced by ode_solver_impl::butcher_tableau< stages >::get_node().
name
template<size_t stages> const std::string ode_solver_impl::butcher_tableau< stages >::name
Definition at line 198 of file ODE_solvers.hpp.
The documentation for this struct was generated from the following file:
ODE_solvers.hpp