SIAM-Keldysh-mfRG: Spline< Q, rank, 2, pos_first_freq_index, DataContainer > Class Template Reference
Spline< Q, rank, 2, pos_first_freq_index, DataContainer > Class Template Reference
#include <InterpolatorSpline2D.hpp>
Public Types
using index_type = typename DataContainer::index_type
using frequencies_type = std::array<double, 2>
Public Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
using buffer_type = typename base_class::buffer_type
Public Member Functions
Spline ()
Spline (double Lambda, index_type dims)
void initInterpolator () const
void set_initializedInterpol (bool is_init) const
Eigen::Matrix< Q, 16, 1 > get_weights (const std::array< my_index_t, 2 > &freq_idx, const std::array< double, 2 > &dw_normalized) const
template<typename result_type >
result_type interpolate_spline (const frequencies_type &frequencies, const index_type &indices) const
Public Member Functions inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
DataContainer ()=default
DataContainer (double Lambda, dimensions_type dims, const fRG_config &config)
auto get_VertexFreqGrid () const -> const frequencyGrid_type &
Functions for getting and setting the frequency grid and its members.
void set_VertexFreqGrid (const frequencyGrid_type frequencyGrid)
template<unsigned int idim, typename std::enable_if_t<(idim< numberFrequencyDims), bool > = true>
double analyze_tails (const int index=0) const
buffer_type get_deriv_x (const buffer_type &dat) const
buffer_type get_deriv_y (const buffer_type &dat) const
buffer_type get_deriv_z (const buffer_type &dat) const
buffer_type get_deriv_xx () const
buffer_type get_deriv_yy () const
buffer_type get_deriv_zz () const
buffer_type get_deriv_xy () const
buffer_type get_deriv_xz () const
buffer_type get_deriv_yz () const
buffer_type get_deriv_xyz () const
auto get_deriv_max () const -> double
auto get_curvature_max () const -> double
template<typename gridType >
auto shrink_freq_box_impl (const gridType &freqGrid, const double rel_tail_threshold, const vec< double > &maxabs_along_x, const bool verbose) const -> gridType
auto shrink_freq_box (const double rel_tail_threshold, bool verbose=true, double constant=0.) const -> frequencyGrid_type
Public Member Functions inherited from dataContainerBase< Q, rank >
dataContainerBase ()=default
constructor:
dataContainerBase (const dimensions_type dims)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
dataContainerBase (const Types &... dims)
dataContainerBase (const buffer_type &data_in)
Q acc (const size_t flatIndex) const
Access data via flattened index.
void direct_set (const size_t flatIndex, Q value)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
Q val (const Types &... i) const
Returns value for a multiIndex.
Q val (const index_type &idx) const
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
const Q & at (const Types &... i) const
Returns reference to a value for a multiIndex.
template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true>
auto val_vectorized (const Types &... i) const -> Eigen::Matrix< Q, vecsize, 1 >
template<std::size_t freqrank, std::size_t vecsize>
auto val_vectorized (const index_type &idx) const -> Eigen::Matrix< Q, vecsize, 1 >
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
void setvert (const Q value, const Types &... i)
Sets a value at a multiIndex.
void setvert (const Q value, const index_type &idx)
template<std::size_t vecsize>
void setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > &value, const index_type &idx)
auto get_dims () const
const buffer_type & get_vec () const
Returns the buffer "data" containing the data.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void set_vec (const container &data_in)
Sets the the buffer "data".
void set_vec (const buffer_type &data_in)
void set_vec (const buffer_type &&data_in)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void add_vec (const container &summand)
Adds a vector to the data.
void add_vec (const buffer_type &summand)
constexpr auto eigen_segment (const index_type &start, const index_type &end)
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> get_values (const index_type &index) const
Public Attributes
bool initialized = false
Public Attributes inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
frequencyGrid_type frequencies
Protected Member Functions
void get_coeffs_from_derivs () const
known values of first or second derivative (corresponding to bd_type)
Protected Attributes
size_t n =0
vec< Q > m_deriv_x = vec<Q>(n)
vec< Q > m_deriv_y = vec<Q>(n)
vec< Q > m_deriv_xy = vec<Q>(n)
coeffs_type all_coefficients = coeffs_type (n,16)
bd_type m_left = third_deriv
bd_type m_right = third_deriv
Q m_left_value = 0.0
set const?
Q m_right_value = 0.0
Protected Attributes inherited from dataContainerBase< Q, rank >
buffer_type data
Private Types
using coeffs_type = Eigen::Matrix<Q, Eigen::Dynamic,16>
Additional Inherited Members
Protected Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using base_class = dataContainerBase<Q, rank>
Protected Types inherited from dataContainerBase< Q, rank >
using buffer_type = multidimensional::multiarray<Q, rank>
using index_type = typename buffer_type::index_type
using dimensions_type = typename buffer_type::dimensions_type
Detailed Description
template<typename Q, size_t rank, my_index_t pos_first_freq_index, class DataContainer>
class Spline< Q, rank, 2, pos_first_freq_index, DataContainer >
SplineK2 interpolation
Template Parameters
rank number of dimensions (of dataContainer)
pos_first_freq_index position of first frequency index (second frequency index is as position pos_first_freq_index+1)
DataContainer contains vertex data and frequency grids frequencies. primary_grid and frequencies.secondary_grid computes partial derivative of data in x, y and x&y direction
Q double or comp
Definition at line 32 of file InterpolatorSpline2D.hpp.
Member Typedef Documentation
coeffs_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::coeffs_type = Eigen::Matrix<Q, Eigen::Dynamic,16> private
Definition at line 37 of file InterpolatorSpline2D.hpp.
frequencies_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::frequencies_type = std::array<double, 2>
Definition at line 42 of file InterpolatorSpline2D.hpp.
index_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::index_type = typename DataContainer::index_type
Definition at line 41 of file InterpolatorSpline2D.hpp.
Constructor & Destructor Documentation
Spline() [1/2]
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::Spline () inline
Definition at line 55 of file InterpolatorSpline2D.hpp.
: initialized(false) {};
Spline() [2/2]
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::Spline (double Lambda, index_type dims) inline explicit
Definition at line 56 of file InterpolatorSpline2D.hpp.
            :   DataContainer(Lambda, dims), n(getFlatSize(DataContainer::get_dims()))
    {
        //this->initializeK2();
    }
Member Function Documentation
get_coeffs_from_derivs()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs () const protected
known values of first or second derivative (corresponding to bd_type)
Definition at line 77 of file InterpolatorSpline2D.hpp.
{
    Eigen::Matrix<double,16,16> A;
    A <<  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            -3,  3,  0,  0, -2, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            2, -2,  0,  0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,
            0,  0,  0,  0,  0,  0,  0,  0, -3,  3,  0,  0, -2, -1,  0,  0,
            0,  0,  0,  0,  0,  0,  0,  0,  2, -2,  0,  0,  1,  1,  0,  0,
            -3,  0,  3,  0,  0,  0,  0,  0, -2,  0, -1,  0,  0,  0,  0,  0,
            0,  0,  0,  0, -3,  0,  3,  0,  0,  0,  0,  0, -2,  0, -1,  0,
            9, -9, -9,  9,  6,  3, -6, -3,  6, -6,  3, -3,  4,  2,  2,  1,
            -6,  6,  6, -6, -3, -3,  3,  3, -4,  4, -2,  2, -2, -2, -1, -1,
            2,  0, -2,  0,  0,  0,  0,  0,  1,  0,  1,  0,  0,  0,  0,  0,
            0,  0,  0,  0,  2,  0, -2,  0,  0,  0,  0,  0,  1,  0,  1,  0,
            -6,  6,  6, -6, -4, -2,  4,  2, -3,  3, -3,  3, -2, -1, -2, -1,
            4, -4, -4,  4,  2,  2, -2, -2,  2, -2,  2, -2,  1,  1,  1,  1;
    const size_t n_x = DataContainer::frequencies.  primary_grid.number_of_gridpoints;
    const size_t n_y = DataContainer::frequencies.secondary_grid.number_of_gridpoints;
    const size_t n_nonx = n/n_x/n_y;
    for (size_t i = 0; i < n_nonx; i++) {
        for (size_t j = 0; j < n_x-1; j++) {
            for (size_t k = 0; k < n_y-1; k++) {
                const double dw = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(j+1) - DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(j);
                const double dv = DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(k+1) - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(k);
                int idx_base_base = ::rotateFlatIndex(i*n_x*n_y + (j  )*n_y + k  , DataContainer::get_dims(), pos_first_freq_index+1);
                int idx_plus_base = ::rotateFlatIndex(i*n_x*n_y + (j+1)*n_y + k  , DataContainer::get_dims(), pos_first_freq_index+1);
                int idx_base_plus = ::rotateFlatIndex(i*n_x*n_y + (j  )*n_y + k+1, DataContainer::get_dims(), pos_first_freq_index+1);
                int idx_plus_plus = ::rotateFlatIndex(i*n_x*n_y + (j+1)*n_y + k+1, DataContainer::get_dims(), pos_first_freq_index+1);
                Eigen::Matrix<Q,16,1> _fs;
                _fs << DataContainer::data[idx_base_base], DataContainer::data[idx_plus_base], DataContainer::data[idx_base_plus], DataContainer::data[idx_plus_plus],
                            dw * m_deriv_x[idx_base_base],      dw * m_deriv_x[idx_plus_base],      dw * m_deriv_x[idx_base_plus],      dw * m_deriv_x[idx_plus_plus],
                            dv * m_deriv_y[idx_base_base],      dv * m_deriv_y[idx_plus_base],      dv * m_deriv_y[idx_base_plus],      dv * m_deriv_y[idx_plus_plus],
                        dw*dv * m_deriv_xy[idx_base_base],  dw*dv * m_deriv_xy[idx_plus_base],  dw*dv * m_deriv_xy[idx_base_plus],  dw*dv * m_deriv_xy[idx_plus_plus];
                all_coefficients.row(idx_base_base) = (A * _fs).transpose();
                for (int i1 = 0; i1 < 4; i1++) {
                    for (int i2 = 0; i2 < 4; i2++) {
                        all_coefficients(idx_base_base, i1 * 4 + i2) /= (pow(dv, i1) * pow(dw, i2));
                    }
                }
            }
        }
    }
    //int ispin = indices[my_defs::K2::spin];
    //int iw = indices[my_defs::K2::omega];
    //int iv = indices[my_defs::K2::nu];
    //int iK = indices[my_defs::K2::keldysh];
    //int i_in = indices[my_defs::K2::internal];
    //const vec<Q> fs = {
    //        DataContainer::data[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv    , iK, i_in, DataContainer::get_dims())],
    //        DataContainer::data[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv    , iK, i_in, DataContainer::get_dims())],
    //        DataContainer::data[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv + 1, iK, i_in, DataContainer::get_dims())],
    //        DataContainer::data[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv + 1, iK, i_in, DataContainer::get_dims())],
    //             dw * m_deriv_x[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv    , iK, i_in, DataContainer::get_dims())],
    //             dw * m_deriv_x[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv    , iK, i_in, DataContainer::get_dims())],
    //             dw * m_deriv_x[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv + 1, iK, i_in, DataContainer::get_dims())],
    //             dw * m_deriv_x[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv + 1, iK, i_in, DataContainer::get_dims())],
    //             dv * m_deriv_y[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv    , iK, i_in, DataContainer::get_dims())],
    //             dv * m_deriv_y[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv    , iK, i_in, DataContainer::get_dims())],
    //             dv * m_deriv_y[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv + 1, iK, i_in, DataContainer::get_dims())],
    //             dv * m_deriv_y[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv + 1, iK, i_in, DataContainer::get_dims())],
    //         dw*dv * m_deriv_xy[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv    , iK, i_in, DataContainer::get_dims())],
    //         dw*dv * m_deriv_xy[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv    , iK, i_in, DataContainer::get_dims())],
    //         dw*dv * m_deriv_xy[::getFlatIndex<5,int,int,int,int,int>(ispin, iw    , iv + 1, iK, i_in, DataContainer::get_dims())],
    //         dw*dv * m_deriv_xy[::getFlatIndex<5,int,int,int,int,int>(ispin, iw + 1, iv + 1, iK, i_in, DataContainer::get_dims())],
    //};
    //vec<Q> coeffs = vec<Q> (16);
    //for (int i = 0; i<16; i++) {
    //    coeffs[i] = 0.;
    //    for (int j = 0; j<16; j++) {
    //        coeffs[i] += A[i][j] * fs[j];
    //    }
    //}
    // Same as double for-loop above (matrix-vector multiplication):
    //vec<Q> coeffs = {
    //        fs[0]
    //        , fs[4]
    //        , 3.*(-fs[0]+fs[1]) -2.*fs[4] -fs[5]
    //        , 2.*(fs[0]-fs[1]) +fs[4] +fs[5]
    //        , fs[8]
    //        , fs[12]
    //        , -3.*(fs[8]-fs[9]) -2.*fs[12] -fs[13]
    //        , 2.*(fs[8]-fs[9]) +fs[12] +fs[13]
    //        , -3.*(fs[0]-fs[2]) -2.*fs[8] -fs[10]
    //        , -3.*(fs[4]-fs[6]) -2.*fs[12] -fs[14]
    //        , 9.*(fs[0]-fs[1]-fs[2]+fs[3]) + 6.*(fs[4]-fs[6]+fs[8]-fs[9]) + 3.*(fs[5]-fs[7]+fs[10]-fs[11]) + 4.*fs[12] + 2.*(fs[13]+fs[14]) + fs[15]
    //        , 6.*(-fs[0]+fs[1]+fs[2]-fs[3]) +3.*(-fs[4]-fs[5]+fs[6]+fs[7]) +4.*(-fs[8]+fs[9]) +2.*(-fs[10]+fs[11]-fs[12]-fs[13]) +(-fs[14]-fs[15])
    //        , 2.*(fs[0]-fs[2]) +fs[8] +fs[10]
    //        , 2.*(fs[4]-fs[6]) +fs[12] +fs[14]
    //        , 6.*(-fs[0]+fs[1]+fs[2]-fs[3]) +4.*(-fs[4]+fs[6]) +2.*(-fs[5]+fs[7]-fs[12]-fs[14]) +3.*(-fs[8]+fs[9]-fs[10]+fs[11]) +(-fs[13]-fs[15])
    //        , 4.*(fs[0]-fs[1]-fs[2]+fs[3]) +2.*(fs[4]+fs[5]-fs[6]-fs[7]+fs[8]-fs[9]+fs[10]-fs[11]) + fs[12]+fs[13]+fs[14]+fs[15]
    //};
    //return coeffs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, dataContainerBase< Q, rank >::get_dims(), and rotateFlatIndex().
get_weights()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Eigen::Matrix< Q, 16, 1 > Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_weights (const std::array< my_index_t, 2 > & freq_idx, const std::array< double, 2 > & dw_normalized) const
Definition at line 204 of file InterpolatorSpline2D.hpp.
{
    //const double dw = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw+1) - DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(iw);
    //const double dv = DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv+1) - DataContainer::frequencies.secondary_grid.get_auxiliary_gridpoint(iv);
    const double hw = dt_unnormalized[0];
    const double hv = dt_unnormalized[1];
    Eigen::Matrix<Q,16,1> weights;
    const double dwpow[4] = {1, hw, hw*hw, hw*hw*hw};
    const double dvpow[4] = {1, hv, hv*hv, hv*hv*hv};
    for (int i = 0; i<4; i++) {
        for (int j = 0; j<4; j++) {
            weights(i*4+j) = dvpow[i] * dwpow[j];
        }
    }
    assert(weights.allFinite());
    return weights;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
initInterpolator()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::initInterpolator () const
Definition at line 184 of file InterpolatorSpline2D.hpp.
{
    multidimensional::multiarray<Q,rank> temp = DataContainer::get_deriv_x();
    m_deriv_x = vec<Q>(temp.begin(), temp.end());
    temp = DataContainer::get_deriv_y();
    m_deriv_y = vec<Q>(temp.begin(), temp.end());
    temp = DataContainer::get_deriv_xy();
    m_deriv_xy = vec<Q>(temp.begin(), temp.end());
    all_coefficients = coeffs_type(n,16);
    get_coeffs_from_derivs();
    initialized = true;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xy(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_y().
interpolate_spline()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > template<typename result_type > result_type Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::interpolate_spline (const frequencies_type & frequencies, const index_type & indices) const
Definition at line 227 of file InterpolatorSpline2D.hpp.
{
    assert(initialized);
    //const int iK, const int spin, const double w, const double v, const int i_in
    std::array<my_index_t,2> freq_idx;      // frequency indices of nearest smaller gridpoints
    std::array<double,2> dt_unnormalized;   // distance to nearest smaller gridpoint
    DataContainer::frequencies.get_auxgrid_index_unnormalized(freq_idx, dt_unnormalized, frequencies);
    //double tw;
    //const size_t iw=DataContainer::frequencies.  primary_grid.get_grid_index(tw, frequencies[0]);
    //double tv;
    //const size_t iv=DataContainer::frequencies.secondary_grid.get_grid_index(tv, frequencies[1]);
    index_type index_temp = indices;
    index_temp[pos_first_freq_index  ] = freq_idx[0];
    index_temp[pos_first_freq_index+1] = freq_idx[1];
    const int i_row = getFlatIndex<rank>(index_temp, DataContainer::get_dims());
    Eigen::Matrix<Q,16,1> weights = get_weights(freq_idx, dt_unnormalized);
    if constexpr(std::is_same_v<result_type,Q>) {
        Q result;
        //vec<Q> coeffs = get_coeffs_from_derivs(index_temp, dw, dv);
        //Q result = 0.;
        //const std::array<size_t,2> dims = {4,4};
        //
        //const double dwpow[4] = {1, hw, hw*hw, hw*hw*hw};
        //const double dvpow[4] = {1, hv, hv*hv, hv*hv*hv};
        //for (int i = 0; i<4; i++) {
        //    for (int j = 0; j<4; j++) {
        //        result += dvpow[i] * coeffs[::getFlatIndex<2,int,int>(i, j, dims)] * dwpow[j];
        //    }
        //}
        Eigen::Matrix<Q, 1, 16> values = all_coefficients.row(i_row);
        result = (values * weights).eval()[0];
        assert(isfinite(result));
        return result;
    }
    else if constexpr(std::is_same_v<result_type,Eigen::Matrix<Q,result_type::RowsAtCompileTime,1>>){
        Eigen::Matrix<Q,result_type::RowsAtCompileTime,1> result;
        Eigen::Matrix<Q, result_type::RowsAtCompileTime, 16> values = all_coefficients.template block<result_type::RowsAtCompileTime,16>(i_row,0);
        result = (values * weights).eval();
        assert(result.allFinite());
        return result;
    }
    else {
        assert(false);
        result_type result;
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, and dataContainerBase< Q, rank >::get_dims().
set_initializedInterpol()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::set_initializedInterpol (bool is_init) const inline
Definition at line 64 of file InterpolatorSpline2D.hpp.
{initialized = is_init;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Member Data Documentation
all_coefficients
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > coeffs_type Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::all_coefficients = coeffs_type (n,16) mutable protected
Definition at line 48 of file InterpolatorSpline2D.hpp.
initialized
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bool Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::initialized = false mutable
Definition at line 40 of file InterpolatorSpline2D.hpp.
m_deriv_x
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_deriv_x = vec<Q>(n) mutable protected
Definition at line 47 of file InterpolatorSpline2D.hpp.
m_deriv_xy
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_deriv_xy = vec<Q>(n) protected
Definition at line 47 of file InterpolatorSpline2D.hpp.
m_deriv_y
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_deriv_y = vec<Q>(n) protected
Definition at line 47 of file InterpolatorSpline2D.hpp.
m_left
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bd_type Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_left = third_deriv protected
Definition at line 50 of file InterpolatorSpline2D.hpp.
m_left_value
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Q Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_left_value = 0.0 protected
set const?
Definition at line 51 of file InterpolatorSpline2D.hpp.
m_right
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bd_type Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_right = third_deriv protected
Definition at line 50 of file InterpolatorSpline2D.hpp.
m_right_value
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Q Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::m_right_value = 0.0 protected
Definition at line 51 of file InterpolatorSpline2D.hpp.
n
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > size_t Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::n =0 protected
Definition at line 46 of file InterpolatorSpline2D.hpp.
The documentation for this class was generated from the following file:
InterpolatorSpline2D.hpp