SIAM-Keldysh-mfRG: data_structures.c++ File Reference
data_structures.c++ File Reference
#include "data_structures.hpp"
Functions
auto my_isfinite (comp z) -> bool
std::ostream & operator<< (std::ostream &out, K_class k)
std::ostream & operator<< (std::ostream &out, vertexType symmtype)
Function Documentation
my_isfinite()
auto my_isfinite (comp z) -> bool
Definition at line 3 of file data_structures.c++.
{
    return std::isfinite(real(z)) and std::isfinite(imag(z));
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by asymp_corrections_bubble(), correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(), correctionFunctionBubbleAT_REG2_Matsubara_PHS(), correctionFunctionBubbleAT_REG3_Matsubara_PHS(), correctionFunctionBubbleAT_REG4_Matsubara_PHS(), Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::GM_REG2(), Propagator< Q >::GR_REG3(), FrequencyGrid< eliasGrid >::initialize_grid(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl(), interpolate_lin1D(), interpolate_lin2D(), interpolate_lin3D(), interpolate_lin_on_aux1D(), interpolate_lin_on_aux2D(), interpolate_lin_on_aux3D(), interpolate_nearest1D(), interpolate_nearest2D(), interpolate_nearest3D(), interpolate_sloppycubic1D(), interpolate_sloppycubic2D(), interpolate_sloppycubic3D(), fullvert< Q >::left_diff_bare(), fullvert< Q >::left_diff_bare(), fullvert< Q >::left_diff_bare_symmetry_expanded(), fullvert< Q >::left_same_bare(), fullvert< Q >::left_same_bare(), rvert< Q >::read_symmetryreduced_rvert(), fullvert< Q >::right_diff_bare(), fullvert< Q >::right_diff_bare(), fullvert< Q >::right_diff_bare_symmetry_expanded(), fullvert< Q >::right_same_bare(), fullvert< Q >::right_same_bare(), Propagator< Q >::SM_REG4(), Bubble< Q >::value(), Bubble< Q >::value(), and Bubble< Q >::value_Matsubara().
operator<<() [1/2]
std::ostream & operator<< (std::ostream & out, K_class k)
Definition at line 8 of file data_structures.c++.
{
    if (k == k1 or k == k2) {out << "K" << static_cast<int>(k+1);}
    else if(k == k3) {out << "K" << static_cast<int>(k);}
    else if(k == k2b) {out << "K" << static_cast<int>(k) << "'";}
    else  {out << "selfenergy";}
    return out;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2, k2b, and k3.
operator<<() [2/2]
std::ostream & operator<< (std::ostream & out, vertexType symmtype)
Definition at line 16 of file data_structures.c++.
{
    if (symmtype == symmetric_full) {out << "symmetric_full";}
    else if (symmtype == symmetric_r_irred) {out << "symmetric_r_irred";}
    else if (symmtype == non_symmetric_diffleft) {out << "non_symmetric_diffleft";}
    else if (symmtype == non_symmetric_diffright) {out << "non_symmetric_diffright";}
    else {assert(false);}
    return out;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, symmetric_full, and symmetric_r_irred.