SIAM-Keldysh-mfRG: State< Q, differentiated > Class Template Reference
State< Q, differentiated > Class Template Reference
#include <state.hpp>
Public Member Functions
State ()
State (double Lambda, const fRG_config &config_in, bool initialize=false)
State (const State< Q, false > &state_in, const double Lambda_in)
State (const Vertex< Q, differentiated > &vertex_in, const SelfEnergy< Q > &selfenergy_in, const fRG_config &config_in, const double Lambda_in)
void initialize (bool checks=true)
void update_grid (double Lambda)
void findBestFreqGrid (bool verbose)
void set_frequency_grid (const State< Q, false > &state_in)
auto operator+= (const State &state) -> State
auto operator+= (const double alpha) -> State
auto operator*= (const double &alpha) -> State
auto operator-= (const State &state) -> State
auto operator/= (const State &state) -> State
void check_resolution () const
void analyze_tails () const
auto abs () const -> State< Q, differentiated >
auto norm () const -> double
Public Attributes
double Lambda
fRG_config config
Vertex< Q, differentiated > vertex
SelfEnergy< Q > selfenergy
bool initialized = false
Friends
State< state_datatype > n_loop_flow (const std::string outputFileName, bool save_intermediate_results)
template<typename T >
void test_PT_state (std::string outputFileName, double Lambda, bool diff)
State< Q, differentiated > operator+ (State< Q, differentiated > lhs, const State< Q, differentiated > &rhs)
State< Q, differentiated > operator+ (State< Q, differentiated > lhs, const double rhs)
State< Q, differentiated > operator+ (const double &rhs, State< Q, differentiated > lhs)
State< Q, differentiated > operator* (State< Q, differentiated > lhs, const double &rhs)
State< Q, differentiated > operator* (const double &rhs, State< Q, differentiated > lhs)
State< Q, differentiated > operator- (State< Q, differentiated > lhs, const State< Q, differentiated > &rhs)
State< Q, differentiated > operator/ (State< Q, differentiated > lhs, const State< Q, differentiated > &rhs)
Detailed Description
template<typename Q, bool differentiated = false>
class State< Q, differentiated >
Define a struct object which includes the self-energy and the vertex which are needed to evaluate the RHS of the flow equations. Class used for the state Ψ = (Σ, Γ).
Template Parameters
Q Type of the data.
differentiated Determines whether the state is differentiated.
Define essential data types: comp : complex number (complex<double>) glb_i : imaginary unit vec : vector class with additional functionality such as element-wise operations, real/imag part etc. VertexInput : auxiliary struct that contains all input variables of vertices
Functions to write/read a State object to/from an HDF5 file.
Definition at line 23 of file state.hpp.
Constructor & Destructor Documentation
State() [1/4]
template<typename Q , bool differentiated = false> State< Q, differentiated >::State () inline
Definition at line 34 of file state.hpp.
           : Lambda(0.) , vertex(fullvert<Q>(0., fRG_config())), selfenergy(SelfEnergy<Q>(0., fRG_config())) {
#ifndef NDEBUG
        //utils::print("Watch out! Use of default constructor for State<Q>!", true);
#endif
    }
State() [2/4]
template<typename Q , bool differentiated = false> State< Q, differentiated >::State (double Lambda, const fRG_config & config_in, bool initialize = false) inline explicit
Constructor which generates a state with frequency grids corresponding to the given value of Lambda.
Parameters
Lambda Value of the regulator Λ.
config_in Set of parameters.
initialize Determines whether the state has to be initialized or not.
Definition at line 45 of file state.hpp.
                                                                                      : Lambda(Lambda), config(config_in), vertex(Lambda, config_in), selfenergy(Lambda, config_in) {
        if (initialize) this->initialize();
    };
References State< Q, differentiated >::initialize().
State() [3/4]
template<typename Q , bool differentiated = false> State< Q, differentiated >::State (const State< Q, false > & state_in, const double Lambda_in) inline
Constructor which takes a State whose frequency grid will be copied. The State itself won't be copied!
Parameters
state_in Input State.
Lambda_in Value of the regulator Λ.
Definition at line 54 of file state.hpp.
    : Lambda(Lambda_in), config(state_in.config),  vertex(differentiated ? Vertex<Q,differentiated> (Lambda, config, state_in.vertex) : Vertex<Q,differentiated> (0, config)), selfenergy(SelfEnergy<Q> (state_in.selfenergy.Sigma.frequencies)){vertex.set_frequency_grid(state_in.vertex);};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and State< Q, differentiated >::vertex.
State() [4/4]
template<typename Q , bool differentiated = false> State< Q, differentiated >::State (const Vertex< Q, differentiated > & vertex_in, const SelfEnergy< Q > & selfenergy_in, const fRG_config & config_in, const double Lambda_in) inline
Constructor which takes a single vertex and a single self-energy and puts them together into a new state. Needed for the parquet checks.
Parameters
vertex_in Input vertex.
selfenergy_in Input self-energy.
config_in Set of parameters.
Lambda_in Value of the regulator Λ.
Definition at line 64 of file state.hpp.
    : Lambda(Lambda_in), config(config_in), vertex(vertex_in), selfenergy(selfenergy_in) {};
Member Function Documentation
abs()
template<typename Q , bool differentiated = false> auto State< Q, differentiated >::abs () const -> State<Q,differentiated> inline
Definition at line 137 of file state.hpp.
{
        State<Q,differentiated> state_abs = (*this);
        state_abs.selfenergy.Sigma.set_vec(selfenergy.Sigma.data.abs());
        state_abs.vertex.avertex().template apply_unary_op_to_all_vertexBuffers([&](auto buffer) -> void {buffer.data = buffer.data.abs();});
        state_abs.vertex.pvertex().template apply_unary_op_to_all_vertexBuffers([&](auto buffer) -> void {buffer.data = buffer.data.abs();});
        state_abs.vertex.tvertex().template apply_unary_op_to_all_vertexBuffers([&](auto buffer) -> void {buffer.data = buffer.data.abs();});
        return state_abs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and State< Q, differentiated >::selfenergy.
Referenced by abs().
analyze_tails()
template<typename Q , bool differentiated> void State< Q, differentiated >::analyze_tails () const
Definition at line 197 of file state.hpp.
{
    selfenergy.analyze_tails(true);
    vertex.half1().analyze_tails_K1(true);
    if (MAX_DIAG_CLASS > 1) {vertex.half1().analyze_tails_K2w(true); vertex.half1().analyze_tails_K2v(true);}
    if (MAX_DIAG_CLASS > 2) {vertex.half1().analyze_tails_K3w(true); vertex.half1().analyze_tails_K3v(true); vertex.half1().analyze_tails_K3vp(true);}
}
References MAX_DIAG_CLASS, State< Q, differentiated >::selfenergy, and State< Q, differentiated >::vertex.
check_resolution()
template<typename Q , bool differentiated> void State< Q, differentiated >::check_resolution () const
Definition at line 192 of file state.hpp.
{
    vertex.half1().check_vertex_resolution();
    selfenergy.check_resolution();
}
References State< Q, differentiated >::selfenergy, and State< Q, differentiated >::vertex.
findBestFreqGrid()
template<typename Q , bool differentiated> void State< Q, differentiated >::findBestFreqGrid (bool verbose)
Definition at line 187 of file state.hpp.
{
    this->selfenergy.findBestFreqGrid(verbose);
    this->vertex.half1().findBestFreqGrid(verbose);
}
References SelfEnergy< Q >::findBestFreqGrid(), and GeneralVertex< Q, symmtype, differentiated >::half1().
initialize()
template<typename Q , bool differentiated> void State< Q, differentiated >::initialize (bool checks = true)
Initializes a state by setting the asymptotic value of the self-energy and the bare interaction appropriately.
Parameters
checks If true, a check of the Friedel sum rule of the Hartree term of the self-energy of the asymmetric SIAM is done. See the Hartree_Solver class.
Definition at line 150 of file state.hpp.
{
    // Initial conditions
    // Assign initial conditions to self energy
    if (!KELDYSH && PARTICLE_HOLE_SYMMETRY) {
        this->selfenergy.initialize(0., 0.);
        }
    else {
        this->selfenergy.initialize(config.U / 2., 0.);
        if (!PARTICLE_HOLE_SYMMETRY){ // SIAM in Keldysh WITHOUT particle-hole symmetry
            assert (not PARTICLE_HOLE_SYMMETRY);
            Hartree_Solver Hartree_Term(Lambda, config);
            const double hartree_value = Hartree_Term.compute_Hartree_term_bracketing(1e-12, checks, checks);
            this->selfenergy.initialize(hartree_value, 0.);
            vertex.center_frequency_grids(shift_fgrids_woPHS ? hartree_value + config.epsilon : 0.);
        }
    }
    // Assign initial conditions to bare vertex
    if (KELDYSH and CONTOUR_BASIS != 1) this->vertex.initialize(-config.U/2.);
    else this->vertex.initialize(-config.U);
    this->initialized = true;
}
References State< Q, differentiated >::config, CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::epsilon, GeneralVertex< Q, symmtype, differentiated >::initialize(), SelfEnergy< Q >::initialize(), KELDYSH, State< Q, differentiated >::Lambda, PARTICLE_HOLE_SYMMETRY, shift_fgrids_woPHS, fRG_config::U, and State< Q, differentiated >::vertex.
Referenced by State< Q, differentiated >::State().
norm()
template<typename Q , bool differentiated> auto State< Q, differentiated >::norm () const -> double
Definition at line 205 of file state.hpp.
{
    double max_vert = vertex.half1().sum_norm(0);
    double max_self = selfenergy.norm(0);
    //print("norm von dGamma und dSigma: ", max_vert, max_self, "\n");
    return std::max(max_self, max_vert);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), State< Q, differentiated >::selfenergy, and State< Q, differentiated >::vertex.
operator*=()
template<typename Q , bool differentiated = false> auto State< Q, differentiated >::operator*= (const double & alpha) -> State inline
Definition at line 100 of file state.hpp.
{
        this->vertex *= alpha;
        this->selfenergy *= alpha;
        return (*this);
    }
operator+=() [1/2]
template<typename Q , bool differentiated = false> auto State< Q, differentiated >::operator+= (const double alpha) -> State inline
Definition at line 87 of file state.hpp.
{
        this->vertex += alpha;
        this->selfenergy += alpha;
        return (*this);
    }
operator+=() [2/2]
template<typename Q , bool differentiated = false> auto State< Q, differentiated >::operator+= (const State< Q, differentiated > & state) -> State inline
Definition at line 78 of file state.hpp.
{
        this->vertex += state.vertex;
        this->selfenergy += state.selfenergy;
        return (*this);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
operator-=()
template<typename Q , bool differentiated = false> auto State< Q, differentiated >::operator-= (const State< Q, differentiated > & state) -> State inline
Definition at line 113 of file state.hpp.
{
        this->vertex -= state.vertex;
        this->selfenergy -= state.selfenergy;
        return (*this);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
operator/=()
template<typename Q , bool differentiated = false> auto State< Q, differentiated >::operator/= (const State< Q, differentiated > & state) -> State inline
Definition at line 123 of file state.hpp.
{
        this->vertex /= state.vertex;
        this->selfenergy /= state.selfenergy;
        return (*this);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
set_frequency_grid()
template<typename Q , bool differentiated> void State< Q, differentiated >::set_frequency_grid (const State< Q, false > & state_in)
Definition at line 175 of file state.hpp.
{
    this->selfenergy.set_frequency_grid(state_in.selfenergy);
    this->vertex.set_frequency_grid(state_in.vertex);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), GeneralVertex< Q, symmtype, differentiated >::set_frequency_grid(), and SelfEnergy< Q >::set_frequency_grid().
update_grid()
template<typename Q , bool differentiated> void State< Q, differentiated >::update_grid (double Lambda)
Definition at line 180 of file state.hpp.
{
    this->selfenergy.update_grid(Lambda_in, config);
    const double hartree_value = myreal(selfenergy.asymp_val_R);
    this->vertex.update_grid(Lambda_in, shift_fgrids_woPHS ? hartree_value + config.epsilon : 0., config);
}
References State< Q, differentiated >::config, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::epsilon, myreal(), State< Q, differentiated >::selfenergy, shift_fgrids_woPHS, SelfEnergy< Q >::update_grid(), and GeneralVertex< Q, symmtype, differentiated >::update_grid().
Friends And Related Symbol Documentation
n_loop_flow
template<typename Q , bool differentiated = false> State< state_datatype > n_loop_flow (const std::string outputFileName, bool save_intermediate_results) friend
operator* [1/2]
template<typename Q , bool differentiated = false> State< Q, differentiated > operator* (const double & rhs, State< Q, differentiated > lhs) friend
Definition at line 109 of file state.hpp.
{
        lhs *= rhs;
        return lhs;
    }
operator* [2/2]
template<typename Q , bool differentiated = false> State< Q, differentiated > operator* (State< Q, differentiated > lhs, const double & rhs) friend
Definition at line 105 of file state.hpp.
{
        lhs *= rhs;
        return lhs;
    }
operator+ [1/3]
template<typename Q , bool differentiated = false> State< Q, differentiated > operator+ (const double & rhs, State< Q, differentiated > lhs) friend
Definition at line 96 of file state.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator+ [2/3]
template<typename Q , bool differentiated = false> State< Q, differentiated > operator+ (State< Q, differentiated > lhs, const double rhs) friend
Definition at line 92 of file state.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator+ [3/3]
template<typename Q , bool differentiated = false> State< Q, differentiated > operator+ (State< Q, differentiated > lhs, const State< Q, differentiated > & rhs) friend
Definition at line 83 of file state.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator-
template<typename Q , bool differentiated = false> State< Q, differentiated > operator- (State< Q, differentiated > lhs, const State< Q, differentiated > & rhs) friend
Definition at line 118 of file state.hpp.
{
        lhs -= rhs;
        return lhs;
    }
operator/
template<typename Q , bool differentiated = false> State< Q, differentiated > operator/ (State< Q, differentiated > lhs, const State< Q, differentiated > & rhs) friend
Definition at line 128 of file state.hpp.
{
        lhs /= rhs;
        return lhs;
    }
test_PT_state
template<typename Q , bool differentiated = false> template<typename T > void test_PT_state (std::string outputFileName, double Lambda, bool diff) friend
Member Data Documentation
config
template<typename Q , bool differentiated = false> fRG_config State< Q, differentiated >::config
Definition at line 29 of file state.hpp.
Referenced by State< Q, differentiated >::initialize(), mfRG_record< Q >::save_states(), and State< Q, differentiated >::update_grid().
initialized
template<typename Q , bool differentiated = false> bool State< Q, differentiated >::initialized = false
Definition at line 32 of file state.hpp.
Lambda
template<typename Q , bool differentiated = false> double State< Q, differentiated >::Lambda
Definition at line 28 of file state.hpp.
Referenced by State< Q, differentiated >::initialize(), and mfRG_record< Q >::save_states().
selfenergy
template<typename Q , bool differentiated = false> SelfEnergy<Q> State< Q, differentiated >::selfenergy
Definition at line 31 of file state.hpp.
Referenced by State< Q, differentiated >::abs(), State< Q, differentiated >::analyze_tails(), State< Q, differentiated >::check_resolution(), compare_with_FDTs(), State< Q, differentiated >::norm(), mfRG_record< Q >::save_states(), and State< Q, differentiated >::update_grid().
vertex
template<typename Q , bool differentiated = false> Vertex<Q,differentiated> State< Q, differentiated >::vertex
Definition at line 30 of file state.hpp.
Referenced by State< Q, differentiated >::analyze_tails(), State< Q, differentiated >::check_resolution(), State< Q, differentiated >::initialize(), State< Q, differentiated >::norm(), rhs_n_loop_flow(), and State< Q, differentiated >::State().
The documentation for this class was generated from the following files:
data_container.hpp
state.hpp