SIAM-Keldysh-mfRG: integrator.c++ File Reference
integrator.c++ File Reference
#include "integrator.hpp"
Functions
void handler (const char *reason, const char *file, int line, int gsl_errno)
auto integrator_gsl_qag_helper (gsl_function &F, double a, double b, int Nmax) -> double
auto integrator_gsl_qagp_helper (gsl_function &F, double *pts, size_t npts, int Nmax) -> double
auto integrator_gsl_qagiu_helper (gsl_function &F, double a, int Nmax) -> double
auto integrator_gsl_qagil_helper (gsl_function &F, double a, int Nmax) -> double
Function Documentation
handler()
void handler (const char * reason, const char * file, int line, int gsl_errno)
Definition at line 3 of file integrator.c++.
{
    //print(reason, true);
}
Referenced by integrator_gsl(), integrator_gsl(), integrator_gsl_qag_helper(), integrator_gsl_qagil_helper(), integrator_gsl_qagiu_helper(), and integrator_gsl_qagp_helper().
integrator_gsl_qag_helper()
auto integrator_gsl_qag_helper (gsl_function & F, double a, double b, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 10 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    int key = 1; // 1: GSL_INTEG_GAUSS15
    // 2: GSL_INTEG_GAUSS21
    // 3: GSL_INTEG_GAUSS31
    // 4: GSL_INTEG_GAUSS41
    // 5: GSL_INTEG_GAUSS51
    // 6: GSL_INTEG_GAUSS61
    gsl_integration_qag(&F, a, b, epsabs, integrator_tol, Nmax, key, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qag_v2().
integrator_gsl_qagil_helper()
auto integrator_gsl_qagil_helper (gsl_function & F, double a, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 65 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    gsl_integration_qagil(&F, a, epsabs, integrator_tol, Nmax, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qag_tails(), integrator_gsl_qag_v2(), and integrator_gsl_qagp_v2().
integrator_gsl_qagiu_helper()
auto integrator_gsl_qagiu_helper (gsl_function & F, double a, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 48 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    //gsl_integration_qagil(&F_real, intervals[0][0], 0, integrator_tol, Nmax, W_real, &result_real, &error_real);
    gsl_integration_qagiu(&F, a, epsabs, integrator_tol, Nmax, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qag_tails(), integrator_gsl_qag_v2(), and integrator_gsl_qagp_v2().
integrator_gsl_qagp_helper()
auto integrator_gsl_qagp_helper (gsl_function & F, double * pts, size_t npts, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 32 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    gsl_integration_qagp(&F, pts, npts, epsabs, integrator_tol, Nmax, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qagp_v2().