SIAM-Keldysh-mfRG: multidimensional Namespace Reference
multidimensional Namespace Reference
Classes
class BlockView
class multiarray
class ranged_view
Functions
template<typename T1 , typename T2 = T1>
static constexpr bool abs_compare (T1 lhs, T2 rhs)
template<typename T , size_t depth>
bool operator== (const multiarray< T, depth > &lhs, const multiarray< T, depth > &rhs)
template<typename T , size_t depth>
bool operator!= (const multiarray< T, depth > &lhs, const multiarray< T, depth > &rhs)
template<typename Q , typename L , size_t depth, std::enable_if_t< std::is_same_v< std::result_of_t< Q &&(L &&)>, L >, bool > = true>
auto transform (Q op, multiarray< L, depth > lhs) noexcept(noexcept(op(std::declval< L >())))
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true>
auto elementwise (Q op, multiarray< L, depth > lhs, const multiarray< R, depth > &rhs)
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true>
auto elementwise (Q op, const multiarray< L, depth > &lhs, const multiarray< R, depth > &rhs)
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true>
auto scalar_map (Q op, multiarray< L, depth > lhs, const R &rhs) noexcept(noexcept(op(std::declval< L >(), std::declval< R >())))
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true>
auto scalar_map (Q op, const multiarray< L, depth > &lhs, const R &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator+ (const multiarray< L, depth > &lhs, const R &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator+ (multiarray< L, depth > lhs, const R &rhs)
template<typename L , typename R , size_t depth>
auto operator+ (const R &lhs, const multiarray< L, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator+ (const multiarray< L, depth > &lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator+ (multiarray< L, depth > lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator- (const multiarray< L, depth > &lhs, const R &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() - std::declval< R >()), L > , bool >
auto operator- (multiarray< L, depth > lhs, const R &rhs)
template<typename L , typename R , size_t depth>
auto operator- (const R &lhs, const multiarray< L, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator- (const multiarray< L, depth > &lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() - std::declval< R >()), L > , bool >
auto operator- (multiarray< L, depth > lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator* (const multiarray< L, depth > &lhs, const R &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() *std::declval< R >()), L > , bool >
auto operator* (multiarray< L, depth > lhs, const R &rhs)
template<typename L , typename R , size_t depth>
auto operator* (const R &lhs, const multiarray< L, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator* (const multiarray< L, depth > &lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() *std::declval< R >()), L > , bool >
auto operator* (multiarray< L, depth > lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator/ (const multiarray< L, depth > &lhs, const R &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()/std::declval< R >()), L > , bool >
auto operator/ (multiarray< L, depth > lhs, const R &rhs)
template<typename L , typename R , size_t depth>
auto operator/ (const R &lhs, const multiarray< L, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool >
auto operator/ (const multiarray< L, depth > &lhs, const multiarray< R, depth > &rhs)
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()/std::declval< R >()), L > , bool >
auto operator/ (multiarray< L, depth > lhs, const multiarray< R, depth > &rhs)
template<typename value_type , size_t depth>
auto operator- (multiarray< value_type, depth > &&rhs)
template<typename value_type , size_t depth>
auto operator- (const multiarray< value_type, depth > &rhs)
template<class Container >
ranged_view< typename Container::iterator > make_range (Container &c, size_t b, size_t e)
Function Documentation
abs_compare()
template<typename T1 , typename T2 = T1> static constexpr bool multidimensional::abs_compare (T1 lhs, T2 rhs) static constexpr
Definition at line 24 of file multiarray.hpp.
    {
        return (std::abs(lhs) < std::abs(rhs));
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
elementwise() [1/2]
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true> auto multidimensional::elementwise (Q op, const multiarray< L, depth > & lhs, const multiarray< R, depth > & rhs)
Definition at line 736 of file multiarray.hpp.
    {
        if (lhs.length() != rhs.length())
        {
            throw std::length_error("Cannot perform pairwise operations on multiarrays of different length.");
        }
        multiarray<std::result_of_t<Q && (L &&, R &&)>, depth> res(lhs.length());
        for (size_t i = 0; i < res.size(); i++)
        {
            res.elements[i] = op(lhs.elements[i], rhs.elements[i]);
        }
        return res;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
elementwise() [2/2]
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true> auto multidimensional::elementwise (Q op, multiarray< L, depth > lhs, const multiarray< R, depth > & rhs)
Definition at line 717 of file multiarray.hpp.
    {
        if (lhs.length() != rhs.length())
        {
            throw std::length_error("Cannot perform pairwise operations on multiarrays of different length.");
        }
        for (size_t i = 0; i < lhs.size(); i++)
        {
            lhs.elements[i] = op(lhs.elements[i], rhs.elements[i]);
        }
        return lhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by operator*(), operator+(), operator-(), and operator/().
make_range()
template<class Container > ranged_view< typename Container::iterator > multidimensional::make_range (Container & c, size_t b, size_t e)
Definition at line 44 of file ranged_view.hpp.
    {
        return ranged_view<typename Container::iterator>(c.begin() + b, c.begin() + e);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by multidimensional::multiarray< T, depth >::range().
operator!=()
template<typename T , size_t depth> bool multidimensional::operator!= (const multiarray< T, depth > & lhs, const multiarray< T, depth > & rhs)
Definition at line 691 of file multiarray.hpp.
    {
        return !(lhs == rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*() [1/5]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator* (const multiarray< L, depth > & lhs, const multiarray< R, depth > & rhs)
Definition at line 912 of file multiarray.hpp.
    {
        return elementwise([](const L &l, const R &r)
                           { return l * r; },
                           lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator*() [2/5]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator* (const multiarray< L, depth > & lhs, const R & rhs)
Definition at line 886 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return l * r; },
                          lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator*() [3/5]
template<typename L , typename R , size_t depth> auto multidimensional::operator* (const R & lhs, const multiarray< L, depth > & rhs)
Definition at line 902 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return r * l; },
                          rhs, lhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator*() [4/5]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() *std::declval< R >()), L > , bool > auto multidimensional::operator* (multiarray< L, depth > lhs, const multiarray< R, depth > & rhs)
Definition at line 924 of file multiarray.hpp.
    {
        return lhs *= rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*() [5/5]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() *std::declval< R >()), L > , bool > auto multidimensional::operator* (multiarray< L, depth > lhs, const R & rhs)
Definition at line 896 of file multiarray.hpp.
    {
        return lhs *= rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+() [1/5]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator+ (const multiarray< L, depth > & lhs, const multiarray< R, depth > & rhs)
Definition at line 811 of file multiarray.hpp.
    {
        return elementwise([](const L &l, const R &r)
                           { return l + r; },
                           lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator+() [2/5]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator+ (const multiarray< L, depth > & lhs, const R & rhs)
Definition at line 784 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return l + r; },
                          lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator+() [3/5]
template<typename L , typename R , size_t depth> auto multidimensional::operator+ (const R & lhs, const multiarray< L, depth > & rhs)
Definition at line 800 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return r + l; },
                          rhs, lhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator+() [4/5]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator+ (multiarray< L, depth > lhs, const multiarray< R, depth > & rhs)
Definition at line 824 of file multiarray.hpp.
    {
        return lhs += rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+() [5/5]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator+ (multiarray< L, depth > lhs, const R & rhs)
Definition at line 794 of file multiarray.hpp.
    {
        return lhs += rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-() [1/7]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator- (const multiarray< L, depth > & lhs, const multiarray< R, depth > & rhs)
Definition at line 862 of file multiarray.hpp.
    {
        return elementwise([](const L &l, const R &r)
                           { return l - r; },
                           lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator-() [2/7]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator- (const multiarray< L, depth > & lhs, const R & rhs)
Definition at line 836 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return l - r; },
                          lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator-() [3/7]
template<typename value_type , size_t depth> auto multidimensional::operator- (const multiarray< value_type, depth > & rhs)
Definition at line 988 of file multiarray.hpp.
    {
        return (-1) * rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-() [4/7]
template<typename L , typename R , size_t depth> auto multidimensional::operator- (const R & lhs, const multiarray< L, depth > & rhs)
Definition at line 852 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return r - l; },
                          rhs, lhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator-() [5/7]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() - std::declval< R >()), L > , bool > auto multidimensional::operator- (multiarray< L, depth > lhs, const multiarray< R, depth > & rhs)
Definition at line 874 of file multiarray.hpp.
    {
        return lhs -= rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-() [6/7]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >() - std::declval< R >()), L > , bool > auto multidimensional::operator- (multiarray< L, depth > lhs, const R & rhs)
Definition at line 846 of file multiarray.hpp.
    {
        return lhs -= rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-() [7/7]
template<typename value_type , size_t depth> auto multidimensional::operator- (multiarray< value_type, depth > && rhs)
Definition at line 982 of file multiarray.hpp.
    {
        return (-1) * std::move(rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/() [1/5]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator/ (const multiarray< L, depth > & lhs, const multiarray< R, depth > & rhs)
Definition at line 960 of file multiarray.hpp.
    {
        return elementwise([](const L &l, const R &r)
                           { return l / r; },
                           lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and elementwise().
operator/() [2/5]
template<typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< decltype(std::declval< L >()+std::declval< R >()), L > , bool > auto multidimensional::operator/ (const multiarray< L, depth > & lhs, const R & rhs)
Definition at line 934 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return l / r; },
                          lhs, rhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator/() [3/5]
template<typename L , typename R , size_t depth> auto multidimensional::operator/ (const R & lhs, const multiarray< L, depth > & rhs)
Definition at line 950 of file multiarray.hpp.
    {
        return scalar_map([](const L &l, const R &r)
                          { return r / l; },
                          rhs, lhs);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and scalar_map().
operator/() [4/5]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()/std::declval< R >()), L > , bool > auto multidimensional::operator/ (multiarray< L, depth > lhs, const multiarray< R, depth > & rhs)
Definition at line 973 of file multiarray.hpp.
    {
        return lhs /= rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/() [5/5]
template<typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< decltype(std::declval< L >()/std::declval< R >()), L > , bool > auto multidimensional::operator/ (multiarray< L, depth > lhs, const R & rhs)
Definition at line 944 of file multiarray.hpp.
    {
        return lhs /= rhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator==()
template<typename T , size_t depth> bool multidimensional::operator== (const multiarray< T, depth > & lhs, const multiarray< T, depth > & rhs)
Definition at line 685 of file multiarray.hpp.
    {
        return (lhs.m_length == rhs.m_length) && (lhs.elements == rhs.elements).all();
    }
scalar_map() [1/2]
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t<!std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true> auto multidimensional::scalar_map (Q op, const multiarray< L, depth > & lhs, const R & rhs)
Definition at line 767 of file multiarray.hpp.
    {
        multiarray<std::result_of_t<Q && (L &&, R &&)>, depth> res(
                lhs.length());
        for (size_t i = 0; i < res.size(); i++)
        {
            res.elements[i] = op(lhs.elements[i], rhs);
        }
        return res;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
scalar_map() [2/2]
template<typename Q , typename L , typename R , size_t depth, std::enable_if_t< std::is_same_v< std::result_of_t< Q &&(L &&, R &&)>, L >, bool > = true> auto multidimensional::scalar_map (Q op, multiarray< L, depth > lhs, const R & rhs) noexcept
Definition at line 754 of file multiarray.hpp.
    {
        for (size_t i = 0; i < lhs.size(); i++)
        {
            lhs.elements[i] = op(lhs.elements[i], rhs);
        }
        return lhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by operator*(), operator*(), operator+(), operator+(), operator-(), operator-(), operator/(), and operator/().
transform()
template<typename Q , typename L , size_t depth, std::enable_if_t< std::is_same_v< std::result_of_t< Q &&(L &&)>, L >, bool > = true> auto multidimensional::transform (Q op, multiarray< L, depth > lhs) noexcept
Definition at line 702 of file multiarray.hpp.
    {
    for (size_t i = 0; i < lhs.size(); i++)
    {
    lhs.elements[i] = op(lhs.elements[i]);
    }
    return lhs;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by multidimensional::multiarray< T, depth >::abs().