SIAM-Keldysh-mfRG: KramersKronig.c++ File Reference
KramersKronig.c++ File Reference
#include "KramersKronig.hpp"
Functions
rvec log (const rvec &x)
Function Documentation
log()
rvec log (const rvec & x)
Definition at line 3 of file KramersKronig.c++.
{
    rvec result (x.size());
    for (unsigned int i=0; i<x.size(); ++i) {
        result[i] = log(x[i]);
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and log().
Referenced by correctionFunctionBubble_REG3_Matsubara_PHS_diff(), correctionFunctionBubble_REG3_Matsubara_PHS_nondiff(), correctionFunctionBubble_REG4_Matsubara_PHS(), correctionFunctionBubbleAT_REG2_Keldysh(), correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(), correctionFunctionBubbleAT_REG2_Matsubara_PHS(), correctionFunctionBubbleP_REG2_Keldysh(), correctionFunctionBubbleP_REG2_Matsubara_NoPHS(), correctionFunctionSelfEnergy_Keldysh(), correctionFunctionSelfEnergy_Matsubara_NoPHS(), correctionFunctionSelfEnergy_Matsubara_PHS(), FrequencyGrid< hybridGrid >::derive_auxiliary_parameters(), flowgrid::exp_parametrization::dlambda_dt(), flowgrid::log_parametrization::dlambda_dt(), flowgrid::exp_parametrization::lambda_from_t(), log(), FrequencyGrid< hybridGrid >::t_from_frequency(), and flowgrid::exp_parametrization::t_from_lambda().