SIAM-Keldysh-mfRG: ODE_solvers.hpp File Reference
ODE_solvers.hpp File Reference
#include <cmath>
#include "../grids/flow_grid.hpp"
#include "../utilities/util.hpp"
#include "../utilities/write_data2file.hpp"
#include "../parameters/master_parameters.hpp"
#include "../postprocessing/causality_FDT_checks.hpp"
#include "../utilities/hdf5_routines.hpp"
#include "../correlation_functions/state.hpp"
#include "old_solvers.hpp"
#include "ODE_solver_config.hpp"
#include <boost/numeric/odeint/integrate/integrate_adaptive.hpp>
#include <boost/numeric/odeint/integrate/detail/integrate_adaptive.hpp>
#include <boost/numeric/odeint.hpp>
Classes
struct ode_solver_impl::butcher_tableau< stages >
Namespaces
namespace ode_solver_impl
namespace boost
namespace boost::numeric
namespace boost::numeric::odeint
namespace boost::numeric::odeint::detail
Macros
#define ERR_STEPPER runge_kutta_cash_karp54
Functions
template<typename Y , typename System >
void postRKstep_stuff (Y &y_run, System &rhs, double x_run, const vec< double > &x_vals, int iteration, const std::string &filename, const ODE_solver_config &config, bool verbose)
template<typename T , typename System >
void ODE_solver_RK4 (T &y_fin, const T &y_ini, const System &rhs, const ODE_solver_config &config, double subst(double x), double resubst(double x), const std::vector< double > lambda_checkpoints={}, std::string filename="", const int it_start=0, bool save_intermediate_states=false)
template<typename T >
void ODE_solver_Euler (T &y_fin, const double x_fin, const T &y_ini, const double x_ini, T rhs(const T &y, const double x), const int N_ODE)
Currently unused ODE solvers:
template<typename T >
void SCE_solver (T &y_fin, const T &y_ini, const double x, T rhs(const T &y, const double x), const int N_SCE, const double damp)
template<typename Y , typename FlowGrid , size_t stages, typename System >
void ode_solver_impl::rk_step (const butcher_tableau< stages > &tableau, const Y &y_init, const Y &dydx, Y &result, const double t_value, const double t_step, double &maxrel_error, const System &rhs, const ODE_solver_config &config)
template<typename Y , typename FlowGrid , size_t stages, typename System >
void ode_solver_impl::rkqs (butcher_tableau< stages > tableau, Y &state_i, double &Lambda_i, double htry, double &hdid, double &hnext, double min_t_step, double max_t_step, const System &rhs, size_t iteration, const ODE_solver_config &config, const bool verbose)
template<typename Y , typename FlowGrid = flowgrid::sqrt_parametrization, typename System >
void ode_solver (Y &result, const Y &state_ini, const System &rhs, const ODE_solver_config &config=ODE_solver_config(), const bool verbose=true)
template<class Stepper , typename State_t , typename FlowGrid , class System >
State_t boost::numeric::odeint::detail::integrate_nonadaptive (Stepper stepper, System system, State_t &start_state, double &t_now, double t_final, const vec< double > &lambdas_try, vec< double > &lambdas_did, const ODE_solver_config &config, const bool verbose)
template<class Stepper , typename State_t , typename FlowGrid , class System >
State_t boost::numeric::odeint::detail::integrate_adaptive_check (Stepper stepper, System system, State_t &start_state, double &t_now, double t_final, double &dt, const size_t MAXSTP, vec< double > &lambdas_did, const ODE_solver_config &config, const bool verbose)
template<typename State_t , typename FlowGrid , typename System >
void boost::numeric::odeint::ode_solver_boost (State_t &result, const State_t &state_ini, const System &rhs, const ODE_solver_config &config=ODE_solver_config(), const bool verbose=true)
Variables
const butcher_tableau< 6 > ode_solver_impl::cash_carp
const butcher_tableau< 4 > ode_solver_impl::RK4basic
const butcher_tableau< 4 > ode_solver_impl::BogaSha
Macro Definition Documentation
ERR_STEPPER
#define ERR_STEPPER runge_kutta_cash_karp54
Function Documentation
ode_solver()
template<typename Y , typename FlowGrid = flowgrid::sqrt_parametrization, typename System > void ode_solver (Y & result, const Y & state_ini, const System & rhs, const ODE_solver_config & config = ODE_solver_config(), const bool verbose = true)
ODE solver with different options --> master_parameters.h currently implemented rules: basic Runge-Kutta 4 Bogacki–Shampine Cash-Carp
Template Parameters
Y double/comp/State
FlowGrid suggests a set of step sizes; for non-adaptive rules these are used --> lambdas_try for adaptive rules FlowGrid only approximately "guides" the step sizes; e.g. for FlowGrid::exp_parametrization we have Lambda(t) = exp(-t) such that equal step sizes in t lead to exponentially decaying step sizes. Adaptive rules can grow or shrink the step sizes in terms of t!
Parameters
result final state
Lambda_f final Lambda
state_ini initial state of type Y
Lambda_i initial Lambda
rhs right-hand side of differential equation rhs(y, dydt, Lambda)
lambda_checkpoints checkpoints at which we want to know a result
filename filename for storing the result (if Y == State)
iter_start start at a certain iteration step (to continue a ODE flow)
N_ODE number of ODE steps (true number of steps is N_ODE + U_NRG for hybridization flow)
load lambdas from file to continue ODE solver
next: try an equal stepsize in terms of the reparametrized flow parameter t
Definition at line 529 of file ODE_solvers.hpp.
{
    int world_rank = mpi_world_rank();
    // quality-controlled RK-step (cf. Numerical recipes in C, page 723)
    const auto tableau = ode_solver_impl::cash_carp;
    if (verbose and world_rank == 0) {
        const std::string message =
                "\n-------------------------------------------------------------------------\n\tStarting ODE solver with method: " + tableau.name + " \n"
               +"-------------------------------------------------------------------------\n";
        std::cout << message;
    }
    const unsigned int MAXSTP = config.maximal_number_of_ODE_steps + config.lambda_checkpoints.size(); //maximal number of steps that is computed
    vec<double> lambdas (MAXSTP+1); // contains all lambdas (including starting point)
    lambdas[0] = config.Lambda_i;
    if constexpr (std::is_same_v<Y,State<state_datatype>>) {
        if (config.iter_start > 0) {
            H5::H5File file_out(config.filename, H5F_ACC_RDONLY);
            read_from_hdf<double>(file_out, LAMBDA_LIST, lambdas);
            file_out.close();
        }
    }
    // get lambdas according to FlowGrid (for hybridization flow: + checkpoints acc. to U_NRG  ) -> for non-adaptive method
    const vec<double> lambdas_try = flowgrid::construct_flow_grid(config.Lambda_f, config.Lambda_i, FlowGrid::t_from_lambda, FlowGrid::lambda_from_t, config.maximal_number_of_ODE_steps, tableau.adaptive ? std::vector<double>() : config.lambda_checkpoints);
    const double max_t_step = 1e1;  // maximal step size in terms of t
    const double min_t_step = 1e-5; // minimal step size in terms of t
    double Lambda = config.Lambda_now;    // step size to try (in terms of Lambda)
    double h_try;
    if (tableau.adaptive and config.iter_start > 0) {
        double lambdas_0 = lambdas[config.iter_start-1];
        double lambdas_1 = lambdas[config.iter_start];
        double htry_last_reparametrized = FlowGrid::t_from_lambda(lambdas_1) - FlowGrid::t_from_lambda(lambdas_0);
        htry_last_reparametrized = std::min(std::abs(htry_last_reparametrized), max_t_step) ;
        htry_last_reparametrized = std::max(std::abs(htry_last_reparametrized), min_t_step) ;
        h_try = FlowGrid::lambda_from_t(FlowGrid::t_from_lambda(Lambda) + htry_last_reparametrized) - Lambda;
    }
    else {
        h_try = lambdas_try[config.iter_start + 1]-lambdas_try[config.iter_start];
    }
    double hnext, hdid, h_try_prev{}; // step size to try next; actually performed step size
    bool just_hit_a_lambda_checkpoint = false;
    result = state_ini;
    for (unsigned int i = config.iter_start; i < MAXSTP; i++)
    {
        if (verbose and world_rank == 0)
        {
            std::cout <<"-------------------------------------------------------------------------\n";
            utils::print("Now do ODE step number \t\t", i, true);
            utils::print("Lambda: ", Lambda, true);
        };
        if constexpr(std::is_same<State<state_datatype>, Y>::value) {
            rhs.iteration = i;
        }
        //if next step would get us outside the interval [Lambda_f, Lambda_i]
        if ((Lambda + h_try - config.Lambda_f) * (Lambda + h_try - config.Lambda_now) > 0.0)
        {
            // if remaining Lambda step is negligibly small
            if (std::abs(config.Lambda_f - Lambda) / config.Lambda_f < 1e-8)
            {
                if (verbose and world_rank == 0)
                {
                    std::cout << "Final Lambda=Lambda_f reached. Program terminated." << std::endl;
                };
                break;
            }
            else
            {
                h_try = config.Lambda_f - Lambda;
            };
        };
        if (just_hit_a_lambda_checkpoint) {h_try = std::max(h_try_prev, h_try_prev - h_try);} // jump to previously suggested Lambda_next if we just hit a Lambda checkpoint
        h_try_prev = h_try; // remember h_try from this iteration in case we hit a Lambda checkpoint
        just_hit_a_lambda_checkpoint = false;
        // === Checkpoints ===
        const double Lambda_next = config.Lambda_now + h_try;
        for (const double checkpoint : config.lambda_checkpoints)
        {
            // Guard against float arithmetic fails
            if ((config.Lambda_now - checkpoint) * (Lambda_next - checkpoint) < -1e-10 and tableau.adaptive)
            {
                h_try = checkpoint - config.Lambda_now;
                just_hit_a_lambda_checkpoint = true;
                break;
            }
        }
        // fix step size for non-adaptive methods
        if (not tableau.adaptive) h_try = lambdas_try[i+1] - lambdas_try[i];
        ode_solver_impl::rkqs<Y, FlowGrid>(tableau, result, Lambda, h_try, hdid, hnext, min_t_step, max_t_step, rhs, i, config, verbose);
        // Pick h_suggested and set Lambda_i for next iteration
        if (tableau.adaptive) {
            config.Lambda_now += hdid;
            if (just_hit_a_lambda_checkpoint){h_try = hdid;} else {h_try = hnext;}
        }
        lambdas[i+1] = Lambda;
        // if Y == State: save state in hdf5
        postRKstep_stuff<Y>(result, rhs, Lambda, lambdas, i, config.filename, config, verbose);
    };
}
References ode_solver_impl::cash_carp, flowgrid::construct_flow_grid(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), ODE_solver_config::filename, ODE_solver_config::iter_start, ODE_solver_config::lambda_checkpoints, ODE_solver_config::Lambda_f, ODE_solver_config::Lambda_i, LAMBDA_LIST(), ODE_solver_config::Lambda_now, ODE_solver_config::maximal_number_of_ODE_steps, mpi_world_rank(), and utils::print().
ODE_solver_Euler()
template<typename T > void ODE_solver_Euler (T & y_fin, const double x_fin, const T & y_ini, const double x_ini, T rhsconst T &y, const double x, const int N_ODE)
Currently unused ODE solvers:
Overload for above function, defining the standard case: Flow is integrated from the first iteration on. Overload for above function, defining the standard case: Flow is integrated from the first iteration on.
Definition at line 159 of file ODE_solvers.hpp.
{
    const double dx = (x_fin-x_ini)/((double)N_ODE); // explicit Euler, equidistant step width dx, N_ODE steps
    T y_run = y_ini; // initial y value
    double x_run = x_ini; // initial x value
    for (int i=0; i<N_ODE; ++i) {
        y_run += rhs(y_run, x_run) * dx; // update y
        x_run += dx; // update x
    }
    y_fin = y_run; // final y value
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
ODE_solver_RK4()
template<typename T , typename System > void ODE_solver_RK4 (T & y_fin, const T & y_ini, const System & rhs, const ODE_solver_config & config, double substdouble x, double resubstdouble x, const std::vector< double > lambda_checkpoints = {}, std::string filename = "", const int it_start = 0, bool save_intermediate_states = false)
Explicit RK4 using non-constant step-width determined by substitution, allowing to save state at each Lambda step. Allows for checkpointing: If last parameter it_start is given, ODE solver starts at this iteration (to continue previously canceled computation). If it_start is not given (see overload below), full flow is computed.
Template Parameters
T : type of object to be integrated (usually State, will currently only work for state, since result is saved using functions from hdf5_routines.h, which only support State)
Parameters
y_fin : reference to object into which result is stored (final State)
x_fin : final value of the integration variable (final Lambda)
y_ini : initial value of the integrated object (initial State)
x_ini : initial value of the integration variable (initial Lambda)
rhs : right hand side of the flow equation to be solved
subst : substitution to generate non-equidistant flow grid
resubst : resubstitution
N_ODE : number of ODE steps (will be increased by adding points at interesting Lambda values)
filename : output file name
it_start : Lambda iteration at which to start solving the flow
Definition at line 90 of file ODE_solvers.hpp.
                                                                 {}, std::string filename="", const int it_start=0, bool save_intermediate_states=false) {
    // construct non-linear flow grid via substitution
    rvec x_vals  = flowgrid::construct_flow_grid(config.Lambda_f, config.Lambda_i, subst, resubst, config.maximal_number_of_ODE_steps, lambda_checkpoints);
    rvec x_diffs = flowgrid::flow_grid_step_sizes(x_vals); // compute step sizes for flow grid
        // solve ODE using step sizes x_diffs
        T y_run = y_ini; // initial y value
        double x_run = x_vals[it_start]; // initial x value
        double dx;
        for (int i=it_start; i<x_diffs.size(); ++i) {
            dx = x_diffs[i];
        // perform RK4 step and write result into output file in
        old_ode_solvers::RK4_step(y_run, x_run, dx, rhs, x_vals, filename, i, save_intermediate_states);
        // update frequency grid, interpolate result to new grid
        postRKstep_stuff<T>(y_run, x_run, x_vals, i, filename, config, true);
    }
    y_fin = y_run; // final y value
}
postRKstep_stuff()
template<typename Y , typename System > void postRKstep_stuff (Y & y_run, System & rhs, double x_run, const vec< double > & x_vals, int iteration, const std::string & filename, const ODE_solver_config & config, bool verbose)
possible unit-tests: [IMPLEMENTED in unit_tests/test_ODE_solver] solve "trivial" ODE in 1 large step (polynomial of order N for a N-order rule) [IMPLEMENTED in unit_tests/test_ODE_solver] solve medium ODE with known solution and check accuracy of result with different choices of epsODE_rel possible unit-tests: [IMPLEMENTED in unit_tests/test_ODE_solver] solve "trivial" ODE in 1 large step (polynomial of order N for a N-order rule) [IMPLEMENTED in unit_tests/test_ODE_solver] solve medium ODE with known solution and check accuracy of result with different choices of epsODE_rel
Try to converge the parquet equations at this point.
const double Delta = (y_run.config.Gamma + x_run) * 0.5; double U_over_Delta = y_run.config.U / Delta; std::string parquet_filename = data_dir + "parquet4fRG_U_over_Delta=" + std::to_string(U_over_Delta) + "_T=" + std::to_string(y_run.config.T) + "_eVg=" + std::to_string(y_run.config.epsilon+y_run.config.U*0.5) + ".h5";; const bool converged = parquet_solver(parquet_filename, y_run, x_run, 2, 1e-6, 100, true, 0.5); if (not converged) utils::print("WARNING! THE PARQUET SOLVER DID NOT CONVERGE!!", true);
Definition at line 26 of file ODE_solvers.hpp.
{
    if constexpr (std::is_same_v<Y, State<state_datatype>>) {
        y_run.Lambda = x_run;
        check_SE_causality(y_run); // check if the self-energy is causal at each step of the flow
        if constexpr(KELDYSH and (REG!=5)) check_FDTs(y_run, verbose); // check FDTs for Sigma and K1r at each step of the flow
        if (filename != "") {
            const bool is_converged = std::abs(x_run - config.Lambda_f) <= 1e-10 * (1 + std::abs(config.Lambda_f));
            add_state_to_hdf(filename, iteration + 1, y_run, is_converged); // save result to hdf5 file
        }
        #ifdef ADAPTIVE_GRID
                y_run.findBestFreqGrid(true);
            y_run.analyze_tails();
            y_run.vertex.half1().check_vertex_resolution();
            if (filename != "") {
                add_state_to_hdf(filename+"_postOpt", iteration + 1,  y_run); // save result to hdf5 file
            }
        #else
            y_run.update_grid(x_run); // rescales grid with Delta or U
        #endif
        rhs.stats.write_to_hdf(filename, y_run.config, iteration + 1);
        rhs.stats.number_of_SE_iterations = 0;
        rhs.stats.time = 0.;
        rhs.stats.RKattempts = 0;
    }
    else {
        std::cout << "current value: " << y_run.value << std::endl;
    }
}
References add_state_to_hdf(), check_FDTs(), check_SE_causality(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, ODE_solver_config::Lambda_f, and REG.
SCE_solver()
template<typename T > void SCE_solver (T & y_fin, const T & y_ini, const double x, T rhsconst T &y, const double x, const int N_SCE, const double damp)
Definition at line 171 of file ODE_solvers.hpp.
{
    T y_run = y_ini; // initial y value
    for (int i=0; i<N_SCE; ++i) // iterate N_SCE times
        y_run = rhs(y_run, x) * (1.-damp) + y_run * damp; // update y with damping
    y_fin = y_run; // final y value
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().