SIAM-Keldysh-mfRG: fullvert< Q > Class Template Reference
fullvert< Q > Class Template Reference
#include <vertex.hpp>
Public Member Functions
fullvert ()=default
fullvert (const double Lambda)
fullvert (const double Lambda, const fRG_config &config)
void center_frequency_grids (const double hartree_plus_epsilon)
template<char ch_bubble, bool r_irred>
auto value (const VertexInput &input) const -> Q
template<char ch_bubble, bool r_irred>
auto value (const VertexInput &input, const fullvert< Q > &right_vertex) const -> Q
template<char ch_bubble, bool r_irred>
auto left_same_bare (const VertexInput &input) const -> Q
template<char ch_bubble, bool r_irred>
auto left_same_bare (const VertexInput &input, const fullvert< Q > &right_vertex) const -> Q
template<char ch_bubble, bool r_irred>
auto right_same_bare (const VertexInput &input) const -> Q
template<char ch_bubble, bool r_irred>
auto right_same_bare (const VertexInput &input, const fullvert< Q > &right_vertex) const -> Q
template<char ch_bubble, bool r_irred, bool only_channel_r>
auto left_diff_bare (const VertexInput &input) const -> Q
template<char ch_bubble, bool r_irred, bool only_channel_r>
auto left_diff_bare (const VertexInput &input, const fullvert< Q > &right_vertex) const -> Q
template<char ch_bubble, bool r_irred, bool only_channel_r>
auto right_diff_bare (const VertexInput &input) const -> Q
template<char ch_bubble, bool r_irred, bool only_channel_r>
auto right_diff_bare (const VertexInput &input, const fullvert< Q > &right_vertex) const -> Q
template<char ch_bubble, typename result_type >
auto gammaRb_symmetry_expanded (const VertexInput &input) const -> result_type
template<char ch_bubble, typename result_type , bool r_irred>
auto value_symmetry_expanded (const VertexInput &input) const -> result_type
template<char ch_bubble, typename result_type , bool r_irred>
auto value_minus_gamma0_symmetry_expanded (const VertexInput &input) const -> result_type
template<char ch_bubble, typename result_type , bool r_irred>
auto left_same_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<char ch_bubble, typename result_type , bool r_irred>
auto right_same_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<char ch_bubble, typename result_type , bool r_irred, bool only_channel_r>
auto left_diff_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<char ch_bubble, typename result_type , bool r_irred, bool only_channel_r>
auto right_diff_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<char r>
rvert< Q > & get_rvertex ()
rvert< Q > & get_rvertex (const char r)
template<char channel_bubble, char channel_rvert, bool is_left_vertex>
auto combine_SBE_to_K2 (const fullvert< Q > &vert_for_lambda, const fullvert< Q > &vert_for_w) const -> typename rvert< Q >::buffer_type_K2
template<char channel_bubble, char channel_rvert, bool is_left_vertex>
auto combine_SBE_to_K2b (const fullvert< Q > &vert_for_lambda, const fullvert< Q > &vert_for_w) const -> typename rvert< Q >::buffer_type_K2b
template<char channel_bubble, char channel_rvert, bool is_left_vertex>
auto combine_SBE_to_K3_SBE (const fullvert< Q > &vert_for_K2, const fullvert< Q > &vert_for_lambda) const -> typename rvert< Q >::buffer_type_K3_SBE
void initializeInterpol () const
void set_initializedInterpol (bool is_init) const
void reorder_due2antisymmetry (fullvert< Q > &right_vertex)
void initialize (Q val)
void set_frequency_grid (const fullvert< Q > &vertex)
void update_grid (double Lambda, double hartree_plus_epsilon, const fRG_config &config)
void findBestFreqGrid (bool verbose=true)
double sum_norm (int) const
double norm_K1 (int) const
double norm_K2 (int) const
double norm_K3 (int) const
auto operator+= (const fullvert< Q > &vertex1) -> fullvert< Q >
auto operator+= (const double alpha) -> fullvert< Q >
auto operator*= (const fullvert< Q > &vertex1) -> fullvert< Q >
auto operator*= (const double &alpha) -> fullvert< Q >
auto operator-= (const fullvert< Q > &vertex1) -> fullvert< Q >
auto operator/= (const fullvert< Q > &vertex1) -> fullvert< Q >
double get_deriv_max_K1 (bool verbose) const
double get_deriv_max_K2 (bool verbose) const
double get_deriv_max_K3 (bool verbose) const
double get_curvature_max_K1 (bool verbose) const
double get_curvature_max_K2 (bool verbose) const
double get_curvature_max_K3 (bool verbose) const
void check_vertex_resolution () const
double analyze_tails_K1 (bool verbose) const
double analyze_tails_K2w (bool verbose) const
double analyze_tails_K2v (bool verbose) const
double analyze_tails_K3w (bool verbose) const
double analyze_tails_K3v (bool verbose) const
double analyze_tails_K3vp (bool verbose) const
void check_symmetries (std::string identifier) const
template<char channel_bubble, bool is_left_vertex>
void symmetry_expand (const fullvert< Q > &fullvert_this, const fullvert< Q > &right_vert, int spin) const
void save_expanded (const std::string &filename_prefix) const
Public Attributes
irreducible< Q > irred
rvert< Q > avertex
rvert< Q > pvertex
rvert< Q > tvertex
bool Ir = false
bool only_same_channel = false
Private Member Functions
template<char ch_bubble>
auto gammaRb (const VertexInput &input) const -> Q
template<char ch_bubble>
auto gammaRb (const VertexInput &input, const fullvert< Q > &right_vertex) const -> Q
Friends
fullvert< Q > operator+ (fullvert< Q > lhs, const fullvert< Q > &rhs)
fullvert< Q > operator+ (fullvert< Q > lhs, const double &rhs)
fullvert< Q > operator* (fullvert< Q > lhs, const fullvert< Q > &rhs)
fullvert< Q > operator* (fullvert< Q > lhs, const double &rhs)
fullvert< Q > operator- (fullvert< Q > lhs, const fullvert< Q > &rhs)
fullvert< Q > operator/ (fullvert< Q > lhs, const fullvert< Q > &rhs)
Detailed Description
template<class Q>
class fullvert< Q >
The class fullvert defines a vertex in a full channel decomposition, i.e., it includes an irreducible (bare) contribution and a, p and t channel reducible contributions.
In the standard configuration (only_same_channel=false and Ir=false), the fullvert is the full vertex with all components. For Ir=true, it is an r-irreducible vertex I_r; for only_same_channel=true, it only contains the r-reducible component.
Template Parameters
Q Type of the data.
Definition at line 120 of file vertex.hpp.
Constructor & Destructor Documentation
fullvert() [1/3]
template<class Q > fullvert< Q >::fullvert () default
fullvert() [2/3]
template<class Q > fullvert< Q >::fullvert (const double Lambda) inline explicit
Constructor at regulator with the standard configuration.
Parameters
Lambda Value of the regulator.
Definition at line 139 of file vertex.hpp.
                                           :
                              avertex('a', Lambda, fRG_config(), true),
                              pvertex('p', Lambda, fRG_config(), true),
                              tvertex('t', Lambda, fRG_config(), true) {}
fullvert() [3/3]
template<class Q > fullvert< Q >::fullvert (const double Lambda, const fRG_config & config) inline explicit
Constructor at regulator with a given configuration.
Parameters
Lambda Value of the regulator.
config Set of parameters.
Definition at line 149 of file vertex.hpp.
                                                                     :
                              avertex('a', Lambda, config, true),
                              pvertex('p', Lambda, config, true),
                              tvertex('t', Lambda, config, true) {}
Member Function Documentation
analyze_tails_K1()
template<typename Q > auto fullvert< Q >::analyze_tails_K1 (bool verbose) const
Definition at line 2024 of file vertex.hpp.
{
    vec<double> Ktails_rel (3);
    Ktails_rel[0] = avertex.K1.template analyze_tails<0>();
    Ktails_rel[1] = pvertex.K1.template analyze_tails<0>();
    Ktails_rel[2] = tvertex.K1.template analyze_tails<0>();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "rel. magnitude of tails in K1" << std::endl;
        std::cout << "\t a: \t" << Ktails_rel[0] << std::endl;
        std::cout << "\t p: \t" << Ktails_rel[1] << std::endl;
        std::cout << "\t t: \t" << Ktails_rel[2] << std::endl;
    }
    double result = Ktails_rel.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
analyze_tails_K2v()
template<typename Q > auto fullvert< Q >::analyze_tails_K2v (bool verbose) const
Definition at line 2063 of file vertex.hpp.
{
    vec<double> Ktails_rely (3);
    Ktails_rely[0] = avertex.K2.template analyze_tails<1>();
    Ktails_rely[1] = pvertex.K2.template analyze_tails<1>();
    Ktails_rely[2] = tvertex.K2.template analyze_tails<1>();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "rel. magnitude of tails in K2" << std::endl;
        std::cout << "\t a -> along v: \t" << Ktails_rely[0] << std::endl;
        std::cout << "\t p -> along v: \t" << Ktails_rely[1] << std::endl;
        std::cout << "\t t -> along v: \t" << Ktails_rely[2] << std::endl;
    }
    double result = Ktails_rely.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
analyze_tails_K2w()
template<typename Q > auto fullvert< Q >::analyze_tails_K2w (bool verbose) const
Definition at line 2044 of file vertex.hpp.
{
    vec<double> Ktails_relx (3);
    Ktails_relx[0] = avertex.K2.template analyze_tails<0>();
    Ktails_relx[1] = pvertex.K2.template analyze_tails<0>();
    Ktails_relx[2] = tvertex.K2.template analyze_tails<0>();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "rel. magnitude of tails in K2" << std::endl;
        std::cout << "\t a -> along w: \t" << Ktails_relx[0] << std::endl;
        std::cout << "\t p -> along w: \t" << Ktails_relx[1] << std::endl;
        std::cout << "\t t -> along w: \t" << Ktails_relx[2] << std::endl;
    }
    double result = Ktails_relx.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
analyze_tails_K3v()
template<typename Q > auto fullvert< Q >::analyze_tails_K3v (bool verbose) const
Definition at line 2101 of file vertex.hpp.
{
    vec<double> Ktails_rely (3);
    Ktails_rely[0] = avertex.K3.template analyze_tails<1>();
    Ktails_rely[1] = pvertex.K3.template analyze_tails<1>();
    Ktails_rely[2] = tvertex.K3.template analyze_tails<1>();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "rel. magnitude of tails in K3" << std::endl;
        std::cout << "\t a -> along v: \t" << Ktails_rely[0] << std::endl;
        std::cout << "\t p -> along v: \t" << Ktails_rely[1] << std::endl;
        std::cout << "\t t -> along v: \t" << Ktails_rely[2] << std::endl;
    }
    double result = Ktails_rely.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
analyze_tails_K3vp()
template<typename Q > auto fullvert< Q >::analyze_tails_K3vp (bool verbose) const
Definition at line 2120 of file vertex.hpp.
{
    vec<double> Ktails_rely (3);
    Ktails_rely[0] = avertex.K3.template analyze_tails<2>();
    Ktails_rely[1] = pvertex.K3.template analyze_tails<2>();
    Ktails_rely[2] = tvertex.K3.template analyze_tails<2>();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "rel. magnitude of tails in K3" << std::endl;
        std::cout << "\t a -> along vp:\t" << Ktails_rely[0] << std::endl;
        std::cout << "\t p -> along vp:\t" << Ktails_rely[1] << std::endl;
        std::cout << "\t t -> along vp:\t" << Ktails_rely[2] << std::endl;
    }
    double result = Ktails_rely.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
analyze_tails_K3w()
template<typename Q > auto fullvert< Q >::analyze_tails_K3w (bool verbose) const
Definition at line 2082 of file vertex.hpp.
{
    vec<double> Ktails_relx (3);
    Ktails_relx[0] = avertex.K3.template analyze_tails<0>();
    Ktails_relx[1] = pvertex.K3.template analyze_tails<0>();
    Ktails_relx[2] = tvertex.K3.template analyze_tails<0>();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "rel. magnitude of tails in K3" << std::endl;
        std::cout << "\t a -> along w: \t" << Ktails_relx[0] << std::endl;
        std::cout << "\t p -> along w: \t" << Ktails_relx[1] << std::endl;
        std::cout << "\t t -> along w: \t" << Ktails_relx[2] << std::endl;
    }
    double result = Ktails_relx.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
center_frequency_grids()
template<class Q > void fullvert< Q >::center_frequency_grids (const double hartree_plus_epsilon) inline
Definition at line 153 of file vertex.hpp.
{
        if constexpr (KELDYSH_FORMALISM and !PARTICLE_HOLE_SYMM) {
            avertex.center_frequency_grids({0., hartree_plus_epsilon, hartree_plus_epsilon});
            tvertex.center_frequency_grids({0., hartree_plus_epsilon, hartree_plus_epsilon});
            pvertex.center_frequency_grids({2. * hartree_plus_epsilon, 0., 0.});
        }
    }
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH_FORMALISM, PARTICLE_HOLE_SYMM, fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
check_symmetries()
template<typename Q > void fullvert< Q >::check_symmetries (std::string identifier) const
Definition at line 2164 of file vertex.hpp.
{
    this->avertex.check_symmetries(identifier, avertex, tvertex);
    this->pvertex.check_symmetries(identifier, pvertex, pvertex);
    this->tvertex.check_symmetries(identifier, tvertex, avertex);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
check_vertex_resolution()
template<typename Q > void fullvert< Q >::check_vertex_resolution () const
TODO: dump state in file if certain thresholds are exceeded
Definition at line 2012 of file vertex.hpp.
{
    if (mpi_world_rank() == 0) {std::cout << "--> Check vertex resolution: " << std::endl;}
    get_deriv_max_K1(true);
    if (MAX_DIAG_CLASS>1) get_deriv_max_K2(true);
    if (MAX_DIAG_CLASS>2) get_deriv_max_K3(true);
    get_curvature_max_K1(true);
    if (MAX_DIAG_CLASS>1) get_curvature_max_K2(true);
    if (MAX_DIAG_CLASS>2) get_curvature_max_K3(true);
}
References MAX_DIAG_CLASS, and mpi_world_rank().
combine_SBE_to_K2()
template<class Q > template<char channel_bubble, char channel_rvert, bool is_left_vertex> auto fullvert< Q >::combine_SBE_to_K2 (const fullvert< Q > & vert_for_lambda, const fullvert< Q > & vert_for_w) const -> typename rvert<Q>::buffer_type_K2 inline
Definition at line 270 of file vertex.hpp.
{
        if constexpr(channel_rvert == 'a') {
            return avertex.template combine_SBE_to_K2<channel_bubble,channel_rvert,is_left_vertex>(vert_for_lambda.avertex, vert_for_w.avertex, vert_for_w.irred);
        }
        else if constexpr(channel_rvert == 'p') {
            return pvertex.template combine_SBE_to_K2<channel_bubble,channel_rvert,is_left_vertex>(vert_for_lambda.pvertex, vert_for_w.pvertex, vert_for_w.irred);
        }
        else if constexpr(channel_rvert == 't') {
            return tvertex.template combine_SBE_to_K2<channel_bubble,channel_rvert,is_left_vertex>(vert_for_lambda.tvertex, vert_for_w.tvertex, vert_for_w.irred);
        }
    };
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
combine_SBE_to_K2b()
template<class Q > template<char channel_bubble, char channel_rvert, bool is_left_vertex> auto fullvert< Q >::combine_SBE_to_K2b (const fullvert< Q > & vert_for_lambda, const fullvert< Q > & vert_for_w) const -> typename rvert<Q>::buffer_type_K2b inline
Definition at line 286 of file vertex.hpp.
{
        if constexpr(channel_rvert == 'a') {
            return avertex.template combine_SBE_to_K2b<channel_bubble,channel_rvert,is_left_vertex>(vert_for_lambda.avertex, vert_for_w.avertex, vert_for_w.irred);
        }
        else if constexpr(channel_rvert == 'p') {
            return pvertex.template combine_SBE_to_K2b<channel_bubble,channel_rvert,is_left_vertex>(vert_for_lambda.pvertex, vert_for_w.pvertex, vert_for_w.irred);
        }
        else if constexpr(channel_rvert == 't') {
            return tvertex.template combine_SBE_to_K2b<channel_bubble,channel_rvert,is_left_vertex>(vert_for_lambda.tvertex, vert_for_w.tvertex, vert_for_w.irred);
        }
        else {
            assert(false);
            return typename rvert<Q>::buffer_type_K2b{};
        }
    };
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
combine_SBE_to_K3_SBE()
template<class Q > template<char channel_bubble, char channel_rvert, bool is_left_vertex> auto fullvert< Q >::combine_SBE_to_K3_SBE (const fullvert< Q > & vert_for_K2, const fullvert< Q > & vert_for_lambda) const -> typename rvert<Q>::buffer_type_K3_SBE inline
Definition at line 306 of file vertex.hpp.
{
        if constexpr(channel_rvert == 'a') {
            return avertex.template combine_SBE_to_K3_SBE<channel_bubble,channel_rvert,is_left_vertex>(vert_for_K2.avertex, vert_for_lambda.avertex);
        }
        else if constexpr(channel_rvert == 'p') {
            return pvertex.template combine_SBE_to_K3_SBE<channel_bubble,channel_rvert,is_left_vertex>(vert_for_K2.pvertex, vert_for_lambda.pvertex);
        }
        else if constexpr(channel_rvert == 't') {
            return tvertex.template combine_SBE_to_K3_SBE<channel_bubble,channel_rvert,is_left_vertex>(vert_for_K2.tvertex, vert_for_lambda.tvertex);
        }
    };
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
findBestFreqGrid()
template<typename Q > void fullvert< Q >::findBestFreqGrid (bool verbose = true)
Definition at line 2142 of file vertex.hpp.
{
    static_assert(not INTERPOL2D_FOR_K3, "2D interpolation of K3 requires identical frequency grids for all channels.");
    avertex.findBestFreqGrid(verbose);
    pvertex.findBestFreqGrid(verbose);
    tvertex.findBestFreqGrid(verbose);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and INTERPOL2D_FOR_K3.
gammaRb() [1/2]
template<typename Q > template<char ch_bubble> auto fullvert< Q >::gammaRb (const VertexInput & input) const -> Q private
Returns \gamma_{\bar{r}} := the sum of the contributions of the diagrammatic classes r' =/= r
Template Parameters
ch_bubble Channel index r.
Parameters
input VertexInput struct for the set of arguments.
Returns
Value of \gamma_{\bar{r}}.
Definition at line 1296 of file vertex.hpp.
{
    Q res;
    if constexpr(ch_bubble == 'a') {
        res = pvertex.template value<ch_bubble>(input, pvertex) + tvertex.template value<ch_bubble>(input, avertex);
    }
    else if constexpr(ch_bubble == 'p') {
        res = avertex.template value<ch_bubble>(input, tvertex) + tvertex.template value<ch_bubble>(input, avertex);
    }
    else if constexpr(ch_bubble == 't') {
        res = avertex.template value<ch_bubble>(input, tvertex) + pvertex.template value<ch_bubble>(input, pvertex);
    }
    else {
        res = 0.;
        utils::print("Something's going wrong with gammaRb. Abort."); assert(false);
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
gammaRb() [2/2]
template<typename Q > template<char ch_bubble> auto fullvert< Q >::gammaRb (const VertexInput & input, const fullvert< Q > & right_vertex) const -> Q private
Definition at line 1313 of file vertex.hpp.
{
    Q res;
    if constexpr(ch_bubble=='a') {
        res = pvertex.template value<ch_bubble>(input, pvertex, right_vertex.pvertex, right_vertex.pvertex) + tvertex.template value<ch_bubble>(input, avertex, right_vertex.tvertex, right_vertex.avertex);
    }
    else if constexpr(ch_bubble=='p') {
        res = avertex.template value<ch_bubble>(input, tvertex, right_vertex.avertex, right_vertex.tvertex) + tvertex.template value<ch_bubble>(input, avertex, right_vertex.tvertex, right_vertex.avertex);
    }
    else if constexpr(ch_bubble=='t') {
        res = avertex.template value<ch_bubble>(input, tvertex, right_vertex.avertex, right_vertex.tvertex) + pvertex.template value<ch_bubble>(input, pvertex, right_vertex.pvertex, right_vertex.pvertex);
    }
    else {
        res = 0.;
        utils::print("Something's going wrong with gammaRb. Abort."); assert(false);
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
gammaRb_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type > auto fullvert< Q >::gammaRb_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1575 of file vertex.hpp.
{
    if constexpr(ch_bubble == 'a') {
        result_type res = pvertex.template value_symmetry_expanded<ch_bubble,result_type>(input) + tvertex.template value_symmetry_expanded<ch_bubble,result_type>(input);
        return res;
    }
    else if constexpr(ch_bubble == 'p') {
        result_type res = avertex.template value_symmetry_expanded<ch_bubble,result_type>(input) + tvertex.template value_symmetry_expanded<ch_bubble,result_type>(input);
        return res;
    }
    else {
        static_assert(ch_bubble == 't', "Something's going wrong with gammaRb. Abort.");
        result_type res = avertex.template value_symmetry_expanded<ch_bubble,result_type>(input) + pvertex.template value_symmetry_expanded<ch_bubble,result_type>(input);
        return res;
    }
    //else {
    //    utils::print("Something's going wrong with gammaRb. Abort."); assert(false);
    //}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_curvature_max_K1()
template<typename Q > auto fullvert< Q >::get_curvature_max_K1 (bool verbose) const
Definition at line 1955 of file vertex.hpp.
{
    vec<double> Kcurv_max (3);
    Kcurv_max[0] = avertex.K1.get_curvature_max();
    Kcurv_max[1] = pvertex.K1.get_curvature_max();
    Kcurv_max[2] = tvertex.K1.get_curvature_max();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "max. Curvature in K1" << std::endl;
        std::cout << "\t a: \t" << Kcurv_max[0] << std::endl;
        std::cout << "\t p: \t" << Kcurv_max[1] << std::endl;
        std::cout << "\t t: \t" << Kcurv_max[2] << std::endl;
    }
    double result = Kcurv_max.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_curvature_max_K2()
template<typename Q > auto fullvert< Q >::get_curvature_max_K2 (bool verbose) const
Definition at line 1974 of file vertex.hpp.
{
    vec<double> Kcurv_max (3);
    Kcurv_max[0] = avertex.K2.get_curvature_max();
    Kcurv_max[1] = pvertex.K2.get_curvature_max();
    Kcurv_max[2] = tvertex.K2.get_curvature_max();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "max. Curvature in K2" << std::endl;
        std::cout << "\t a: \t" << Kcurv_max[0] << std::endl;
        std::cout << "\t p: \t" << Kcurv_max[1] << std::endl;
        std::cout << "\t t: \t" << Kcurv_max[2] << std::endl;
    }
    double result = Kcurv_max.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_curvature_max_K3()
template<typename Q > auto fullvert< Q >::get_curvature_max_K3 (bool verbose) const
Definition at line 1993 of file vertex.hpp.
{
    vec<double> Kcurv_max (3);
    Kcurv_max[0] = avertex.K3.get_curvature_max();
    Kcurv_max[1] = pvertex.K3.get_curvature_max();
    Kcurv_max[2] = tvertex.K3.get_curvature_max();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "max. Curvature in K3" << std::endl;
        std::cout << "\t a: \t" << Kcurv_max[0] << std::endl;
        std::cout << "\t p: \t" << Kcurv_max[1] << std::endl;
        std::cout << "\t t: \t" << Kcurv_max[2] << std::endl;
    }
    double result = Kcurv_max.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_deriv_max_K1()
template<typename Q > auto fullvert< Q >::get_deriv_max_K1 (bool verbose) const
Definition at line 1898 of file vertex.hpp.
{
    vec<double> Kderiv_max (3);
    Kderiv_max[0] = avertex.K1.get_deriv_max();
    Kderiv_max[1] = pvertex.K1.get_deriv_max();
    Kderiv_max[2] = tvertex.K1.get_deriv_max();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "max. Derivative in K1" << std::endl;
        std::cout << "\t a: \t" << Kderiv_max[0] << std::endl;
        std::cout << "\t p: \t" << Kderiv_max[1] << std::endl;
        std::cout << "\t t: \t" << Kderiv_max[2] << std::endl;
    }
    double result = Kderiv_max.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_deriv_max_K2()
template<typename Q > auto fullvert< Q >::get_deriv_max_K2 (bool verbose) const
Definition at line 1917 of file vertex.hpp.
{
    vec<double> Kderiv_max (3);
    Kderiv_max[0] = avertex.K2.get_deriv_max();
    Kderiv_max[1] = pvertex.K2.get_deriv_max();
    Kderiv_max[2] = tvertex.K2.get_deriv_max();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "max. Derivative in K2" << std::endl;
        std::cout << "\t a: \t" << Kderiv_max[0] << std::endl;
        std::cout << "\t p: \t" << Kderiv_max[1] << std::endl;
        std::cout << "\t t: \t" << Kderiv_max[2] << std::endl;
    }
    double result = Kderiv_max.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_deriv_max_K3()
template<typename Q > auto fullvert< Q >::get_deriv_max_K3 (bool verbose) const
Definition at line 1936 of file vertex.hpp.
{
    vec<double> Kderiv_max (3);
    Kderiv_max[0] = avertex.K3.get_deriv_max();
    Kderiv_max[1] = pvertex.K3.get_deriv_max();
    Kderiv_max[2] = tvertex.K3.get_deriv_max();
    if (verbose and mpi_world_rank()==0) {
        std::cout << "max. Derivative in K3" << std::endl;
        std::cout << "\t a: \t" << Kderiv_max[0] << std::endl;
        std::cout << "\t p: \t" << Kderiv_max[1] << std::endl;
        std::cout << "\t t: \t" << Kderiv_max[2] << std::endl;
    }
    double result = Kderiv_max.max_norm();
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
get_rvertex() [1/2]
template<class Q > template<char r> rvert< Q > & fullvert< Q >::get_rvertex () inline
Returns the reducible part of the vertex in channel r.
Template Parameters
r channel index r
Returns
rvert in channel r.
Definition at line 241 of file vertex.hpp.
{
        if constexpr(r == 'a') {
            return avertex;
        }
        else if constexpr(r == 'p') {
            return pvertex;
        }
        else if constexpr(r == 't') {
            return tvertex;
        }
        else {
            assert(false);
        }
    }
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
get_rvertex() [2/2]
template<class Q > rvert< Q > & fullvert< Q >::get_rvertex (const char r) inline
Definition at line 255 of file vertex.hpp.
{
        if (r == 'a') {
            return avertex;
        }
        else if (r == 'p') {
            return pvertex;
        }
        else if (r == 't') {
            return tvertex;
        }
        else {
            assert(false);
            return avertex;
        }
    }
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
initialize()
template<typename Q > void fullvert< Q >::initialize (Q val)
Definition at line 1811 of file vertex.hpp.
{
    this->irred.initialize(val);
}
initializeInterpol()
template<typename Q > void fullvert< Q >::initializeInterpol () const
Definition at line 2150 of file vertex.hpp.
{
    avertex.initInterpolator();
    pvertex.initInterpolator();
    tvertex.initInterpolator();
}
left_diff_bare() [1/2]
template<typename Q > template<char ch_bubble, bool r_irred, bool only_channel_r> auto fullvert< Q >::left_diff_bare (const VertexInput & input) const -> Q
Combination of those diagrams that connect to the different bare vertices on the left side: K2, K3, gamma_bar{r}
Template Parameters
ch_bubble Channel index r used for the parametrization.
r_irred Determines whether the vertex is irreducible in channel r.
only_channel_r If true, only the r-reducible part K2 + K3 is given.
Parameters
input VertexInput struct for the set of arguments.
Returns
Value of K2 + K3 + gamma_bar{r}
Definition at line 1486 of file vertex.hpp.
{
    Q K2_K3, gamma_Rb;
    if constexpr(r_irred) {
        if (MAX_DIAG_CLASS >= 2) {
            gamma_Rb = gammaRb<ch_bubble>(input);
            assert(my_isfinite(gamma_Rb));
        }
        return gamma_Rb;
    }
    if constexpr (ch_bubble == 'a'){ K2_K3 = avertex.left_diff_bare(input, tvertex); }
    else if constexpr(ch_bubble == 'p'){ K2_K3 = pvertex.left_diff_bare(input, pvertex); }
    else if constexpr(ch_bubble == 't'){ K2_K3 = tvertex.left_diff_bare(input, avertex); }
    else assert(false);
    assert(my_isfinite(K2_K3));
    if constexpr(only_channel_r)
        return K2_K3;
    gamma_Rb = gammaRb<ch_bubble>(input);
    return K2_K3 + gamma_Rb;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, and my_isfinite().
left_diff_bare() [2/2]
template<typename Q > template<char ch_bubble, bool r_irred, bool only_channel_r> auto fullvert< Q >::left_diff_bare (const VertexInput & input, const fullvert< Q > & right_vertex) const -> Q
Definition at line 1507 of file vertex.hpp.
{
    Q K2_K3, gamma_Rb;
    if constexpr(r_irred) {
        if (MAX_DIAG_CLASS >= 2) {
            gamma_Rb = gammaRb<ch_bubble>(input, right_vertex);
            assert(my_isfinite(gamma_Rb));
        }
        return gamma_Rb;
    }
    if constexpr (ch_bubble == 'a'){ K2_K3 = avertex.left_diff_bare(input, tvertex, right_vertex.avertex, right_vertex.tvertex); }
    else if constexpr(ch_bubble == 'p'){ K2_K3 = pvertex.left_diff_bare(input, pvertex, right_vertex.pvertex, right_vertex.pvertex); }
    else if constexpr(ch_bubble == 't'){ K2_K3 = tvertex.left_diff_bare(input, avertex, right_vertex.tvertex, right_vertex.avertex); }
    else assert(false);
    assert(my_isfinite(K2_K3));
    if constexpr(only_channel_r)
        return K2_K3;
    gamma_Rb = gammaRb<ch_bubble>(input, right_vertex);
    return K2_K3 + gamma_Rb;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, and my_isfinite().
left_diff_bare_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type , bool r_irred, bool only_channel_r> auto fullvert< Q >::left_diff_bare_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1725 of file vertex.hpp.
{
    if constexpr(r_irred) {
        if (MAX_DIAG_CLASS >= 2) {
            const result_type gamma_Rb = gammaRb_symmetry_expanded<ch_bubble,result_type>(input);
            if constexpr(std::is_same_v<Q,result_type>) {assert(my_isfinite(gamma_Rb));} else {assert((gamma_Rb.allFinite()));}
            return gamma_Rb;
        }
    }
    else if constexpr(only_channel_r) {
        if constexpr     (ch_bubble == 'a'){ result_type K2_K3 = avertex.template left_diff_bare_symmetry_expanded<result_type>(input); return K2_K3;}
        else if constexpr(ch_bubble == 'p'){ result_type K2_K3 = pvertex.template left_diff_bare_symmetry_expanded<result_type>(input); return K2_K3;}
        else if constexpr(ch_bubble == 't'){ result_type K2_K3 = tvertex.template left_diff_bare_symmetry_expanded<result_type>(input); return K2_K3;}
    }
    else {
        const result_type gamma_Rb = gammaRb_symmetry_expanded<ch_bubble,result_type>(input);
        if constexpr     (ch_bubble == 'a'){ const result_type K2_K3 = avertex.template left_diff_bare_symmetry_expanded<result_type>(input); return K2_K3 + gamma_Rb;}
        else if constexpr(ch_bubble == 'p'){ const result_type K2_K3 = pvertex.template left_diff_bare_symmetry_expanded<result_type>(input); return K2_K3 + gamma_Rb;}
        else                               { const result_type K2_K3 = tvertex.template left_diff_bare_symmetry_expanded<result_type>(input); return K2_K3 + gamma_Rb;}
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, and my_isfinite().
left_same_bare() [1/2]
template<typename Q > template<char ch_bubble, bool r_irred> auto fullvert< Q >::left_same_bare (const VertexInput & input) const -> Q
Combination of those diagrams that connect to the same bare vertex on the left side: Gamma0, K1, K2b
Template Parameters
ch_bubble Channel index r used for the parametrization.
r_irred Determines whether the vertex is irreducible in channel r.
Parameters
input VertexInput struct for the set of arguments.
Returns
Value of Gamma0 + K1 + K2b.
Definition at line 1332 of file vertex.hpp.
{
    Q gamma0, K1_K2b;
    gamma0 = irred.val(input.iK, input.i_in, input.spin);
    if constexpr(r_irred)
        return gamma0;
    if constexpr (ch_bubble == 'a'){ K1_K2b = avertex.left_same_bare(input, tvertex); }
    else if constexpr(ch_bubble == 'p'){ K1_K2b = pvertex.left_same_bare(input, pvertex); }
    else if constexpr(ch_bubble == 't'){ K1_K2b = tvertex.left_same_bare(input, avertex); }
    else assert(false); //, "unsupported channel"+std::to_string(ch_bubble));
#ifdef STATIC_FEEDBACK
    if (MAX_DIAG_CLASS <= 1) {
        VertexInput input_p = input;
        VertexInput input_at = input;
        input_p.w = 2 * glb_mu;
        input_at.w = 0.;
        switch (ch_bubble) {
            case 'a':
                K1_K2b += pvertex.template valsmooth<k1>(input_p, pvertex)
                          + tvertex.template valsmooth<k1>(input_at, avertex);
                break;
            case 'p':
                K1_K2b += avertex.template valsmooth<k1>(input_at, tvertex)
                          + tvertex.template valsmooth<k1>(input_at, avertex);
                break;
            case 't':
                K1_K2b += avertex.template valsmooth<k1>(input_at, tvertex)
                          + pvertex.template valsmooth<k1>(input_p, pvertex);
                break;
            default:;
        }
    }
#endif
    assert(my_isfinite(K1_K2b));
    return gamma0 + K1_K2b;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_mu, MAX_DIAG_CLASS, my_isfinite(), and VertexInput::w.
left_same_bare() [2/2]
template<typename Q > template<char ch_bubble, bool r_irred> auto fullvert< Q >::left_same_bare (const VertexInput & input, const fullvert< Q > & right_vertex) const -> Q
Definition at line 1370 of file vertex.hpp.
{
    Q gamma0, K1_K2b;
    gamma0 = irred.val(input.iK, input.i_in, input.spin);
    if constexpr(r_irred)
        return gamma0;
    if constexpr (ch_bubble == 'a'){ K1_K2b = avertex.left_same_bare(input, tvertex, right_vertex.avertex, right_vertex.tvertex); }
    else if constexpr(ch_bubble == 'p'){ K1_K2b = pvertex.left_same_bare(input, pvertex, right_vertex.pvertex, right_vertex.pvertex); }
    else if constexpr(ch_bubble == 't'){ K1_K2b = tvertex.left_same_bare(input, avertex, right_vertex.tvertex, right_vertex.avertex); }
    else assert(false);
#ifdef STATIC_FEEDBACK
    if (MAX_DIAG_CLASS <= 1) {
        VertexInput input_p = input;
        VertexInput input_at = input;
        input_p.w = 2 * glb_mu;
        input_at.w = 0.;
        switch (ch_bubble) {
            case 'a':
                K1_K2b += pvertex.template valsmooth<k1>(input_p, pvertex, right_vertex)
                          + tvertex.template valsmooth<k1>(input_at, avertex, right_vertex);
                break;
            case 'p':
                K1_K2b += avertex.template valsmooth<k1>(input_at, tvertex, right_vertex)
                          + tvertex.template valsmooth<k1>(input_at, avertex, right_vertex);
                break;
            case 't':
                K1_K2b += avertex.template valsmooth<k1>(input_at, tvertex, right_vertex)
                          + pvertex.template valsmooth<k1>(input_p, pvertex, right_vertex);
                break;
            default:;
        }
    }
#endif
    assert(my_isfinite(K1_K2b));
    return gamma0 + K1_K2b;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_mu, MAX_DIAG_CLASS, my_isfinite(), and VertexInput::w.
left_same_bare_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type , bool r_irred> auto fullvert< Q >::left_same_bare_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1617 of file vertex.hpp.
{
#ifdef STATIC_FEEDBACK
    if (MAX_DIAG_CLASS <= 1) {
        VertexInput input_p = input;
        VertexInput input_at = input;
        input_p.w = 2 * glb_mu;
        input_at.w = 0.;
        const result_type gamma0 = irred.template val<result_type>(input.iK, input.i_in, input.spin);
        if constexpr(r_irred)
            return gamma0;
        result_type K1_K2b;
        switch (ch_bubble) {
            case 'a':
                K1_K2b = pvertex.template left_same_bare_symmetry_expanded<result_type>(input_p)
                          + tvertex.template left_same_bare_symmetry_expanded<result_type>(input_at);
                K1_K2b += avertex.template left_same_bare_symmetry_expanded<result_type>(input);
                break;
            case 'p':
                K1_K2b = avertex.template left_same_bare_symmetry_expanded<result_type>(input_at)
                          + tvertex.template left_same_bare_symmetry_expanded<result_type>(input_at);
                K1_K2b += pvertex.template left_same_bare_symmetry_expanded<result_type>(input);
                break;
            case 't':
                K1_K2b = avertex.template left_same_bare_symmetry_expanded<result_type>(input_at)
                          + pvertex.template left_same_bare_symmetry_expanded<result_type>(input_p);
                K1_K2b += tvertex.template left_same_bare_symmetry_expanded<result_type>(input);
                break;
            default: assert(false);
        }
        return gamma0 + K1_K2b;
    }
#else
    if (SBE_DECOMPOSITION) {
        if constexpr (r_irred) {return myzero<result_type>();}
        if constexpr     (ch_bubble == 'a') { const result_type K1_K2b = avertex.template left_same_bare_symmetry_expanded<result_type>(input); return K1_K2b;}
        else if constexpr(ch_bubble == 'p') { const result_type K1_K2b = pvertex.template left_same_bare_symmetry_expanded<result_type>(input); return K1_K2b;}
        else if constexpr(ch_bubble == 't') { const result_type K1_K2b = tvertex.template left_same_bare_symmetry_expanded<result_type>(input); return K1_K2b;}
    }
    else {
        const result_type gamma0 = irred.template val<result_type>(input.iK, input.i_in, input.spin);
        if constexpr(r_irred)
            return gamma0;
        if constexpr     (ch_bubble == 'a') { const result_type K1_K2b = avertex.template left_same_bare_symmetry_expanded<result_type>(input); return gamma0 + K1_K2b;}
        else if constexpr(ch_bubble == 'p') { const result_type K1_K2b = pvertex.template left_same_bare_symmetry_expanded<result_type>(input); return gamma0 + K1_K2b;}
        else if constexpr(ch_bubble == 't') { const result_type K1_K2b = tvertex.template left_same_bare_symmetry_expanded<result_type>(input); return gamma0 + K1_K2b;}
        else
            assert(false);
    }
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_mu, MAX_DIAG_CLASS, SBE_DECOMPOSITION, and VertexInput::w.
norm_K1()
template<typename Q > auto fullvert< Q >::norm_K1 (int p) const
Definition at line 1833 of file vertex.hpp.
{
    if(p==0) {//infinity (max) norm
        double max = this->avertex.K1.get_vec().max_norm();
        double compare = this->pvertex.K1.get_vec().max_norm();
        if (compare > max) max = compare;
        compare = this->tvertex.K1.get_vec().max_norm();
        if (compare > max) max = compare;
        return max;
    }
    else {//p-norm
        double norm = std::abs((this->avertex.K1.get_vec().get_elements().pow(p) + this->pvertex.K1.get_vec().get_elements().pow(p) + this->tvertex.K1.get_vec().get_elements().pow(p)).sum());
        return pow(norm, 1./((double)p));
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
norm_K2()
template<typename Q > auto fullvert< Q >::norm_K2 (int p) const
Definition at line 1850 of file vertex.hpp.
{
#if MAX_DIAG_CLASS > 1
    if(p==0) {//infinity (max) norm
        double max = this->avertex.K2.get_vec().max_norm();
        double compare = this->pvertex.K2.get_vec().max_norm();
        if (compare > max) max = compare;
        compare = this->tvertex.K2.get_vec().max_norm();
        if (compare > max) max = compare;
        return max;
    }
    else {//p-norm
        double norm = std::abs((this->avertex.K2.get_vec().get_elements().pow(p) + this->pvertex.K2.get_vec().get_elements().pow(p) + this->tvertex.K2.get_vec().get_elements().pow(p)).sum());
        return pow(norm, 1./((double)p));
    }
#else
    return 0.;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
norm_K3()
template<typename Q > auto fullvert< Q >::norm_K3 (int p) const
Definition at line 1870 of file vertex.hpp.
{
#if MAX_DIAG_CLASS > 2
    if(p==0) {//infinity (max) norm
        double max = this->avertex.K3.get_vec().max_norm();
        double compare = this->pvertex.K3.get_vec().max_norm();
        if (compare > max) max = compare;
        compare = this->tvertex.K3.get_vec().max_norm();
        if (compare > max) max = compare;
        return max;
    }
    else {//p-norm
        double norm = std::abs((this->avertex.K3.get_vec().get_elements().pow(p) + this->pvertex.K3.get_vec().get_elements().pow(p) + this->tvertex.K3.get_vec().get_elements().pow(p)).sum());
        return pow(norm, 1./((double)p));
    }
#else
    return 0.;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*=() [1/2]
template<class Q > auto fullvert< Q >::operator*= (const double & alpha) -> fullvert<Q> inline
Definition at line 392 of file vertex.hpp.
{
        this->irred   *= alpha;
        this->pvertex *= alpha;
        this->tvertex *= alpha;
        this->avertex *= alpha;
        return *this;
    }
operator*=() [2/2]
template<class Q > auto fullvert< Q >::operator*= (const fullvert< Q > & vertex1) -> fullvert<Q> inline
Definition at line 381 of file vertex.hpp.
{
        this->irred   *= vertex1.irred;
        this->pvertex *= vertex1.pvertex;
        this->tvertex *= vertex1.tvertex;
        this->avertex *= vertex1.avertex;
        return *this;
    }
operator+=() [1/2]
template<class Q > auto fullvert< Q >::operator+= (const double alpha) -> fullvert<Q> inline
Definition at line 370 of file vertex.hpp.
{
        this->irred   += alpha;
        this->pvertex += alpha;
        this->tvertex += alpha;
        this->avertex += alpha;
        return *this;
    }
operator+=() [2/2]
template<class Q > auto fullvert< Q >::operator+= (const fullvert< Q > & vertex1) -> fullvert<Q> inline
Definition at line 359 of file vertex.hpp.
{
        this->irred   += vertex1.irred;
        this->avertex += vertex1.avertex;
        this->pvertex += vertex1.pvertex;
        this->tvertex += vertex1.tvertex;
        return *this;
    }
operator-=()
template<class Q > auto fullvert< Q >::operator-= (const fullvert< Q > & vertex1) -> fullvert<Q> inline
Definition at line 403 of file vertex.hpp.
{
        this->irred   -= vertex1.irred;
        this->pvertex -= vertex1.pvertex;
        this->tvertex -= vertex1.tvertex;
        this->avertex -= vertex1.avertex;
        return *this;
    }
operator/=()
template<class Q > auto fullvert< Q >::operator/= (const fullvert< Q > & vertex1) -> fullvert<Q> inline
Definition at line 416 of file vertex.hpp.
{
        this->irred   /= vertex1.irred;
        this->avertex /= vertex1.avertex;
        this->pvertex /= vertex1.pvertex;
        this->tvertex /= vertex1.tvertex;
        return *this;
    }
reorder_due2antisymmetry()
template<typename Q > void fullvert< Q >::reorder_due2antisymmetry (fullvert< Q > & right_vertex)
TODO: Better reorder both at once
Definition at line 1769 of file vertex.hpp.
{
    initializeInterpol();
    right_vertex.initializeInterpol();
    avertex.enforce_freqsymmetriesK1(right_vertex.avertex);
    pvertex.enforce_freqsymmetriesK1(right_vertex.pvertex);
    tvertex.enforce_freqsymmetriesK1(right_vertex.tvertex);
    if (MAX_DIAG_CLASS > 1) {
        avertex.enforce_freqsymmetriesK2(right_vertex.avertex);
        pvertex.enforce_freqsymmetriesK2(right_vertex.pvertex);
        tvertex.enforce_freqsymmetriesK2(right_vertex.tvertex);
    }
    if (MAX_DIAG_CLASS > 2) {
        avertex.enforce_freqsymmetriesK3(right_vertex.avertex);
        pvertex.enforce_freqsymmetriesK3(right_vertex.pvertex);
        tvertex.enforce_freqsymmetriesK3(right_vertex.tvertex);
    }
    right_vertex.avertex.enforce_freqsymmetriesK1(avertex);
    right_vertex.pvertex.enforce_freqsymmetriesK1(pvertex);
    right_vertex.tvertex.enforce_freqsymmetriesK1(tvertex);
    if (MAX_DIAG_CLASS > 1) {
        right_vertex.avertex.enforce_freqsymmetriesK2(avertex);
        right_vertex.pvertex.enforce_freqsymmetriesK2(pvertex);
        right_vertex.tvertex.enforce_freqsymmetriesK2(tvertex);
    }
    if (MAX_DIAG_CLASS > 2) {
        right_vertex.avertex.enforce_freqsymmetriesK3(avertex);
        right_vertex.pvertex.enforce_freqsymmetriesK3(pvertex);
        right_vertex.tvertex.enforce_freqsymmetriesK3(tvertex);
    }
#if defined(EQUILIBRIUM) and USE_FDT
    for (char r:"apt") compute_components_through_FDTs(*this, *this, right_vertex, r, Pi.g.T);
    for (char r:"apt") compute_components_through_FDTs(right_vertex, right_vertex, *this, r, Pi.g.T);
#endif
    set_initializedInterpol(false);
    right_vertex.set_initializedInterpol(false);
}
References compute_components_through_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and MAX_DIAG_CLASS.
right_diff_bare() [1/2]
template<typename Q > template<char ch_bubble, bool r_irred, bool only_channel_r> auto fullvert< Q >::right_diff_bare (const VertexInput & input) const -> Q
Combination of those diagrams that connect to the different bare vertices on the right side: K2b, K3, gamma_bar{r}
Template Parameters
ch_bubble Channel index r used for the parametrization.
r_irred Determines whether the vertex is irreducible in channel r.
only_channel_r If true, only the r-reducible part K2b + K3 is given.
Parameters
input VertexInput struct for the set of arguments.
Returns
Value of K2b + K3 + gamma_bar{r}
Definition at line 1530 of file vertex.hpp.
{
    Q K2b_K3, gamma_Rb;
    if constexpr(r_irred) {
        if (MAX_DIAG_CLASS >= 2) {
            gamma_Rb = gammaRb<ch_bubble>(input);
            assert(my_isfinite(gamma_Rb));
        }
        return gamma_Rb;
    }
    if constexpr (ch_bubble == 'a'){ K2b_K3 = avertex.right_diff_bare(input, tvertex); }
    else if constexpr(ch_bubble == 'p'){ K2b_K3 = pvertex.right_diff_bare(input, pvertex); }
    else if constexpr(ch_bubble == 't'){ K2b_K3 = tvertex.right_diff_bare(input, avertex); }
    else assert(false);
    assert(my_isfinite(K2b_K3));
    if constexpr (only_channel_r)
        return K2b_K3;
    gamma_Rb = gammaRb<ch_bubble>(input);
    return K2b_K3 + gamma_Rb;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, and my_isfinite().
right_diff_bare() [2/2]
template<typename Q > template<char ch_bubble, bool r_irred, bool only_channel_r> auto fullvert< Q >::right_diff_bare (const VertexInput & input, const fullvert< Q > & right_vertex) const -> Q
Definition at line 1551 of file vertex.hpp.
{
    Q K2b_K3, gamma_Rb;
    if constexpr(r_irred) {
        if (MAX_DIAG_CLASS >= 2) {
            gamma_Rb = gammaRb<ch_bubble>(input, right_vertex);
            assert(my_isfinite(gamma_Rb));
        }
        return gamma_Rb;
    }
    if constexpr (ch_bubble == 'a'){ K2b_K3 = avertex.right_diff_bare(input, tvertex, right_vertex.avertex, right_vertex.tvertex); }
    else if constexpr(ch_bubble == 'p'){ K2b_K3 = pvertex.right_diff_bare(input, pvertex, right_vertex.pvertex, right_vertex.pvertex); }
    else if constexpr(ch_bubble == 't'){ K2b_K3 = tvertex.right_diff_bare(input, avertex, right_vertex.tvertex, right_vertex.avertex); }
    else assert(false);
    assert(my_isfinite(K2b_K3));
    if constexpr(only_channel_r)
        return K2b_K3;
    gamma_Rb = gammaRb<ch_bubble>(input, right_vertex);
    return K2b_K3 + gamma_Rb;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, and my_isfinite().
right_diff_bare_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type , bool r_irred, bool only_channel_r> auto fullvert< Q >::right_diff_bare_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1746 of file vertex.hpp.
{
    if constexpr(r_irred) {
        if (MAX_DIAG_CLASS >= 2) {
            result_type gamma_Rb = gammaRb_symmetry_expanded<ch_bubble, result_type>(input);
            if constexpr(std::is_same_v<Q,result_type>) {assert(my_isfinite(gamma_Rb));} else {assert(gamma_Rb.allFinite());}
            return gamma_Rb;
        }
    }
    else if constexpr(only_channel_r){
        if constexpr     (ch_bubble == 'a'){ result_type K2b_K3 = avertex.template right_diff_bare_symmetry_expanded<result_type>(input); return K2b_K3; }
        else if constexpr(ch_bubble == 'p'){ result_type K2b_K3 = pvertex.template right_diff_bare_symmetry_expanded<result_type>(input); return K2b_K3; }
        else                               { result_type K2b_K3 = tvertex.template right_diff_bare_symmetry_expanded<result_type>(input); return K2b_K3; }
    }
    else {
        result_type gamma_Rb = gammaRb_symmetry_expanded<ch_bubble,result_type>(input);
        if constexpr     (ch_bubble == 'a'){ result_type K2b_K3 = avertex.template right_diff_bare_symmetry_expanded<result_type>(input); return K2b_K3 + gamma_Rb; }
        else if constexpr(ch_bubble == 'p'){ result_type K2b_K3 = pvertex.template right_diff_bare_symmetry_expanded<result_type>(input); return K2b_K3 + gamma_Rb; }
        else                               { result_type K2b_K3 = tvertex.template right_diff_bare_symmetry_expanded<result_type>(input); return K2b_K3 + gamma_Rb; }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, and my_isfinite().
right_same_bare() [1/2]
template<typename Q > template<char ch_bubble, bool r_irred> auto fullvert< Q >::right_same_bare (const VertexInput & input) const -> Q
Combination of those diagrams that connect to the same bare vertex on the right side: Gamma0, K1, K2
Template Parameters
ch_bubble Channel index r used for the parametrization.
r_irred Determines whether the vertex is irreducible in channel r.
Parameters
input VertexInput struct for the set of arguments.
Returns
Value of Gamma0 + K1 + K2
Definition at line 1409 of file vertex.hpp.
{
    Q gamma0, K1_K2;
    gamma0 = irred.val(input.iK, input.i_in, input.spin);
    if constexpr(r_irred)
        return gamma0;
    if constexpr (ch_bubble == 'a'){ K1_K2 = avertex.right_same_bare(input, tvertex); }
    else if constexpr(ch_bubble == 'p'){ K1_K2 = pvertex.right_same_bare(input, pvertex); }
    else if constexpr(ch_bubble == 't'){ K1_K2 = tvertex.right_same_bare(input, avertex); }
    else assert(false);
#ifdef STATIC_FEEDBACK
    if (MAX_DIAG_CLASS <= 1) {
        VertexInput input_p = input;
        VertexInput input_at = input;
        input_p.w = 2 * glb_mu;
        input_at.w = 0.;
        switch (ch_bubble) {
            case 'a':
                K1_K2 += pvertex.template valsmooth<k1>(input_p, pvertex)
                         + tvertex.template valsmooth<k1>(input_at, avertex);
                break;
            case 'p':
                K1_K2 += avertex.template valsmooth<k1>(input_at, tvertex)
                         + tvertex.template valsmooth<k1>(input_at, avertex);
                break;
            case 't':
                K1_K2 += avertex.template valsmooth<k1>(input_at, tvertex)
                         + pvertex.template valsmooth<k1>(input_p, pvertex);
                break;
            default:;
        }
    }
#endif
    assert(my_isfinite(K1_K2));
    return gamma0 + K1_K2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_mu, MAX_DIAG_CLASS, my_isfinite(), and VertexInput::w.
right_same_bare() [2/2]
template<typename Q > template<char ch_bubble, bool r_irred> auto fullvert< Q >::right_same_bare (const VertexInput & input, const fullvert< Q > & right_vertex) const -> Q
Definition at line 1447 of file vertex.hpp.
{
    Q gamma0, K1_K2;
    gamma0 = irred.val(input.iK, input.i_in, input.spin);
    if constexpr(r_irred)
        return gamma0;
    if constexpr (ch_bubble == 'a'){ K1_K2 = avertex.right_same_bare(input, tvertex, right_vertex.avertex, right_vertex.tvertex); }
    else if constexpr(ch_bubble == 'p'){ K1_K2 = pvertex.right_same_bare(input, pvertex, right_vertex.pvertex, right_vertex.pvertex); }
    else if constexpr(ch_bubble == 't'){ K1_K2 = tvertex.right_same_bare(input, avertex, right_vertex.tvertex, right_vertex.avertex); }
    else assert(false);
#ifdef STATIC_FEEDBACK
    if (MAX_DIAG_CLASS <= 1) {
        VertexInput input_p = input;
        VertexInput input_at = input;
        input_p.w = 2 * glb_mu;
        input_at.w = 0.;
        switch (ch_bubble) {
            case 'a':
                K1_K2 += pvertex.template valsmooth<k1>(input_p, pvertex, right_vertex)
                         + tvertex.template valsmooth<k1>(input_at, avertex, right_vertex);
                break;
            case 'p':
                K1_K2 += avertex.template valsmooth<k1>(input_at, tvertex, right_vertex)
                         + tvertex.template valsmooth<k1>(input_at, avertex, right_vertex);
                break;
            case 't':
                K1_K2 += avertex.template valsmooth<k1>(input_at, tvertex, right_vertex)
                         + pvertex.template valsmooth<k1>(input_p, pvertex, right_vertex);
                break;
            default:;
        }
    }
#endif
    assert(my_isfinite(K1_K2));
    return gamma0 + K1_K2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_mu, MAX_DIAG_CLASS, my_isfinite(), and VertexInput::w.
right_same_bare_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type , bool r_irred> auto fullvert< Q >::right_same_bare_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1671 of file vertex.hpp.
{
#ifdef STATIC_FEEDBACK
    if (MAX_DIAG_CLASS <= 1) {
        VertexInput input_p = input;
        VertexInput input_at = input;
        input_p.w = 2 * glb_mu;
        input_at.w = 0.;
        const result_type gamma0 = irred.template val<result_type>(input.iK, input.i_in, input.spin);
        if constexpr(r_irred)
            return gamma0;
        result_type K1_K2b;
        switch (ch_bubble) {
            case 'a':
                K1_K2b = pvertex.template right_same_bare_symmetry_expanded<result_type>(input_p)
                         + tvertex.template right_same_bare_symmetry_expanded<result_type>(input_at);
                K1_K2b += avertex.template right_same_bare_symmetry_expanded<result_type>(input);
                break;
            case 'p':
                K1_K2b = avertex.template right_same_bare_symmetry_expanded<result_type>(input_at)
                         + tvertex.template right_same_bare_symmetry_expanded<result_type>(input_at);
                K1_K2b += pvertex.template right_same_bare_symmetry_expanded<result_type>(input);
                break;
            case 't':
                K1_K2b = avertex.template right_same_bare_symmetry_expanded<result_type>(input_at)
                         + pvertex.template right_same_bare_symmetry_expanded<result_type>(input_p);
                K1_K2b += tvertex.template right_same_bare_symmetry_expanded<result_type>(input);
                break;
            default: assert(false);
        }
        return gamma0 + K1_K2b;
    }
#else
    if constexpr (SBE_DECOMPOSITION) {
        if constexpr (r_irred) {return myzero<result_type>();}
        if constexpr     (ch_bubble == 'a') { const result_type K1_K2 = avertex.template right_same_bare_symmetry_expanded<result_type>(input); return K1_K2;}
        else if constexpr(ch_bubble == 'p') { const result_type K1_K2 = pvertex.template right_same_bare_symmetry_expanded<result_type>(input); return K1_K2;}
        else {static_assert(ch_bubble == 't', "Has to be t channel."); const result_type K1_K2 = tvertex.template right_same_bare_symmetry_expanded<result_type>(input); return K1_K2;}
    }
    else {
        result_type gamma0 = irred.template val<result_type>(input.iK, input.i_in, input.spin);
        if constexpr(r_irred)
            return gamma0;
        if constexpr     (ch_bubble == 'a') { result_type K1_K2 = avertex.template right_same_bare_symmetry_expanded<result_type>(input); return gamma0 + K1_K2;}
        else if constexpr(ch_bubble == 'p') { result_type K1_K2 = pvertex.template right_same_bare_symmetry_expanded<result_type>(input); return gamma0 + K1_K2;}
        else {static_assert(ch_bubble == 't', "Has to be t channel."); result_type K1_K2 = tvertex.template right_same_bare_symmetry_expanded<result_type>(input); return gamma0 + K1_K2;}
    }
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_mu, MAX_DIAG_CLASS, SBE_DECOMPOSITION, and VertexInput::w.
save_expanded()
template<typename Q > void fullvert< Q >::save_expanded (const std::string & filename_prefix) const
Definition at line 2178 of file vertex.hpp.
{
    avertex.save_expanded(filename_prefix + "_a.h5");
    pvertex.save_expanded(filename_prefix + "_p.h5");
    tvertex.save_expanded(filename_prefix + "_t.h5");
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
set_frequency_grid()
template<typename Q > void fullvert< Q >::set_frequency_grid (const fullvert< Q > & vertex)
Definition at line 1815 of file vertex.hpp.
{
    this->avertex.apply_binary_op_to_all_vertexBuffers([&](auto&& left, auto&& right) -> void {
        left.set_VertexFreqGrid(right.get_VertexFreqGrid());
    }, vertex.avertex);
    this->pvertex.apply_binary_op_to_all_vertexBuffers([&](auto&& left, auto&& right) -> void {
        left.set_VertexFreqGrid(right.get_VertexFreqGrid());
    }, vertex.pvertex);
    this->tvertex.apply_binary_op_to_all_vertexBuffers([&](auto&& left, auto&& right) -> void {
        left.set_VertexFreqGrid( right.get_VertexFreqGrid() );
    }, vertex.tvertex);
}
References fullvert< Q >::avertex, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fullvert< Q >::pvertex, and fullvert< Q >::tvertex.
set_initializedInterpol()
template<typename Q > void fullvert< Q >::set_initializedInterpol (bool is_init) const
Definition at line 2157 of file vertex.hpp.
{
    avertex.set_initializedInterpol(is_init);
    pvertex.set_initializedInterpol(is_init);
    tvertex.set_initializedInterpol(is_init);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
sum_norm()
template<typename Q > auto fullvert< Q >::sum_norm (int p) const
Definition at line 1890 of file vertex.hpp.
{
    double result = 0.;
    if (MAX_DIAG_CLASS >= 0) result += norm_K1(p);
    if (MAX_DIAG_CLASS >= 2) result += norm_K2(p);
    if (MAX_DIAG_CLASS >= 3) result += norm_K3(p);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and MAX_DIAG_CLASS.
symmetry_expand()
template<typename Q > template<char channel_bubble, bool is_left_vertex> void fullvert< Q >::symmetry_expand (const fullvert< Q > & fullvert_this, const fullvert< Q > & right_vert, int spin) const
Definition at line 2170 of file vertex.hpp.
{
    //irred: symmetry expansion not necessary
    irred.set_vec(fullvert_this.irred.get_vec() * (spin == 0 ? 1. : -1));   // other spin component flips sign
    avertex.template symmetry_expand<channel_bubble, is_left_vertex>(fullvert_this.avertex, fullvert_this.tvertex, right_vert.avertex, right_vert.tvertex, spin);
    pvertex.template symmetry_expand<channel_bubble, is_left_vertex>(fullvert_this.pvertex, fullvert_this.pvertex, right_vert.pvertex, right_vert.pvertex, spin);
    tvertex.template symmetry_expand<channel_bubble, is_left_vertex>(fullvert_this.tvertex, fullvert_this.avertex, right_vert.tvertex, right_vert.avertex, spin);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
update_grid()
template<typename Q > void fullvert< Q >::update_grid (double Lambda, double hartree_plus_epsilon, const fRG_config & config)
Definition at line 1827 of file vertex.hpp.
{
    this->avertex.update_grid(Lambda, {0., hartree_plus_epsilon, hartree_plus_epsilon}, config);
    this->pvertex.update_grid(Lambda, {2.*hartree_plus_epsilon, 0., 0.}, config);
    this->tvertex.update_grid(Lambda, {0., hartree_plus_epsilon, hartree_plus_epsilon}, config);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
value() [1/2]
template<typename Q > template<char ch_bubble, bool r_irred> auto fullvert< Q >::value (const VertexInput & input) const -> Q
Gives access to the data.
Template Parameters
ch_bubble Channel index r used for the parametrization.
r_irred Determines whether the vertex is irreducible in channel r.
Parameters
input VertexInput struct for the set of arguments.
Returns
Value of the full vertex
Definition at line 1271 of file vertex.hpp.
{
    assert(only_same_channel==false); // fullvert::value not implemented for only_same_channel
    if constexpr(r_irred) {
        return irred.val(input.iK, input.i_in, input.spin) + gammaRb<ch_bubble>(input);
    }
    else {
        return irred.val(input.iK, input.i_in, input.spin)
               + avertex.template value<ch_bubble>(input, tvertex)
               + pvertex.template value<ch_bubble>(input, pvertex)
               + tvertex.template value<ch_bubble>(input, avertex);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
value() [2/2]
template<typename Q > template<char ch_bubble, bool r_irred> auto fullvert< Q >::value (const VertexInput & input, const fullvert< Q > & right_vertex) const -> Q
Definition at line 1283 of file vertex.hpp.
{
    assert(only_same_channel==false); // fullvert::value not implemented for only_same_channel
    if constexpr(r_irred) {
        return irred.val(input.iK, input.i_in, input.spin) + gammaRb<ch_bubble>(input, right_vertex);
    }
    else {
        return irred.val(input.iK, input.i_in, input.spin)
               + avertex.template value<ch_bubble>(input, tvertex, right_vertex.avertex, right_vertex.tvertex)
               + pvertex.template value<ch_bubble>(input, pvertex, right_vertex.pvertex, right_vertex.pvertex)
               + tvertex.template value<ch_bubble>(input, avertex, right_vertex.tvertex, right_vertex.avertex);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
value_minus_gamma0_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type , bool r_irred> auto fullvert< Q >::value_minus_gamma0_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1606 of file vertex.hpp.
{
    if constexpr(r_irred) {
        const result_type gamma_Rb = gammaRb_symmetry_expanded<ch_bubble,result_type>(input);
        return  gamma_Rb;
    }
    else {
        return   avertex.template value_symmetry_expanded<ch_bubble,result_type>(input)
               + pvertex.template value_symmetry_expanded<ch_bubble,result_type>(input)
               + tvertex.template value_symmetry_expanded<ch_bubble,result_type>(input);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
value_symmetry_expanded()
template<typename Q > template<char ch_bubble, typename result_type , bool r_irred> auto fullvert< Q >::value_symmetry_expanded (const VertexInput & input) const -> result_type
Definition at line 1593 of file vertex.hpp.
{
    result_type gamma0 = irred.template val<result_type>(input.iK, input.i_in, input.spin);
    if constexpr(r_irred) {
        result_type gamma_Rb = gammaRb_symmetry_expanded<ch_bubble,result_type>(input);
        return gamma0 + gamma_Rb;
    }
    else {
        return gamma0
                + avertex.template value_symmetry_expanded<ch_bubble,result_type>(input)
                + pvertex.template value_symmetry_expanded<ch_bubble,result_type>(input)
                + tvertex.template value_symmetry_expanded<ch_bubble,result_type>(input);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Friends And Related Symbol Documentation
operator* [1/2]
template<class Q > fullvert< Q > operator* (fullvert< Q > lhs, const double & rhs) friend
Definition at line 399 of file vertex.hpp.
                                                                     {// passing lhs by value helps optimize chained a+b+c
        lhs *= rhs; // reuse compound assignment
        return lhs; // return the result by value (uses move constructor)
    }
operator* [2/2]
template<class Q > fullvert< Q > operator* (fullvert< Q > lhs, const fullvert< Q > & rhs) friend
Definition at line 388 of file vertex.hpp.
                                                                          {// passing lhs by value helps optimize chained a+b+c
        lhs *= rhs; // reuse compound assignment
        return lhs; // return the result by value (uses move constructor)
    }
operator+ [1/2]
template<class Q > fullvert< Q > operator+ (fullvert< Q > lhs, const double & rhs) friend
Definition at line 377 of file vertex.hpp.
                                                                     {// passing lhs by value helps optimize chained a+b+c
        lhs += rhs; // reuse compound assignment
        return lhs; // return the result by value (uses move constructor)
    }
operator+ [2/2]
template<class Q > fullvert< Q > operator+ (fullvert< Q > lhs, const fullvert< Q > & rhs) friend
Definition at line 366 of file vertex.hpp.
                                                                          {// passing lhs by value helps optimize chained a+b+c
        lhs += rhs; // reuse compound assignment
        return lhs; // return the result by value (uses move constructor)
    }
operator-
template<class Q > fullvert< Q > operator- (fullvert< Q > lhs, const fullvert< Q > & rhs) friend
Definition at line 410 of file vertex.hpp.
                                                                          {// passing lhs by value helps optimize chained a+b+c
        lhs -= rhs; // reuse compound assignment
        return lhs; // return the result by value (uses move constructor)
    }
operator/
template<class Q > fullvert< Q > operator/ (fullvert< Q > lhs, const fullvert< Q > & rhs) friend
Definition at line 423 of file vertex.hpp.
                                                                          {// passing lhs by value helps optimize chained a+b+c
        lhs /= rhs; // reuse compound assignment
        return lhs; // return the result by value (uses move constructor)
    }
Member Data Documentation
avertex
template<class Q > rvert<Q> fullvert< Q >::avertex
Definition at line 124 of file vertex.hpp.
Referenced by fullvert< Q >::center_frequency_grids(), fullvert< Q >::combine_SBE_to_K2(), fullvert< Q >::combine_SBE_to_K2b(), fullvert< Q >::combine_SBE_to_K3_SBE(), fullvert< Q >::get_rvertex(), fullvert< Q >::get_rvertex(), and fullvert< Q >::set_frequency_grid().
Ir
template<class Q > bool fullvert< Q >::Ir = false
Definition at line 127 of file vertex.hpp.
irred
template<class Q > irreducible<Q> fullvert< Q >::irred mutable
Definition at line 123 of file vertex.hpp.
only_same_channel
template<class Q > bool fullvert< Q >::only_same_channel = false
Definition at line 129 of file vertex.hpp.
pvertex
template<class Q > rvert<Q> fullvert< Q >::pvertex
Definition at line 125 of file vertex.hpp.
Referenced by fullvert< Q >::center_frequency_grids(), fullvert< Q >::combine_SBE_to_K2(), fullvert< Q >::combine_SBE_to_K2b(), fullvert< Q >::combine_SBE_to_K3_SBE(), fullvert< Q >::get_rvertex(), fullvert< Q >::get_rvertex(), and fullvert< Q >::set_frequency_grid().
tvertex
template<class Q > rvert<Q> fullvert< Q >::tvertex
Definition at line 126 of file vertex.hpp.
Referenced by fullvert< Q >::center_frequency_grids(), fullvert< Q >::combine_SBE_to_K2(), fullvert< Q >::combine_SBE_to_K2b(), fullvert< Q >::combine_SBE_to_K3_SBE(), fullvert< Q >::get_rvertex(), fullvert< Q >::get_rvertex(), and fullvert< Q >::set_frequency_grid().
The documentation for this class was generated from the following files:
r_vertex.hpp
vertex.hpp