SIAM-Keldysh-mfRG: propagator.hpp File Reference
propagator.hpp File Reference
#include <cmath>
#include "../../data_structures.hpp"
#include "../../utilities/math_utils.hpp"
#include "selfenergy.hpp"
#include "../../parameters/master_parameters.hpp"
#include "../../utilities/util.hpp"
Classes
class Propagator< Q >
Functions
auto Fermi_distr (double v, double mu, const double T) -> double
auto Fermi_fac (double v, double mu, const double T) -> double
auto Eff_distr (double v, const double T) -> double
auto Eff_fac (double v, const double T) -> double
double Fermi_distribution (double nu)
Function Documentation
Eff_distr()
auto Eff_distr (double v, const double T) -> double
Definition at line 14 of file propagator.c++.
{
    if (EQUILIBRIUM) return Fermi_distr(v, glb_mu, T);
    else return 0.5 * (Fermi_distr(v, glb_mu + glb_V / 2., T) + Fermi_distr(v, glb_mu - glb_V / 2., T));
}
References EQUILIBRIUM, Fermi_distr(), glb_mu, and glb_V.
Eff_fac()
auto Eff_fac (double v, const double T) -> double
Definition at line 19 of file propagator.c++.
{
    if (EQUILIBRIUM) return Fermi_fac(v, glb_mu, T);
    else return 1. - (Fermi_distr(v, glb_mu + glb_V / 2., T) + Fermi_distr(v, glb_mu - glb_V / 2., T));
}
References EQUILIBRIUM, Fermi_distr(), Fermi_fac(), glb_mu, and glb_V.
Referenced by check_FDTs_K1(), check_FDTs_selfenergy(), Propagator< Q >::GK(), and Propagator< Q >::SK().
Fermi_distr()
auto Fermi_distr (double v, double mu, const double T) -> double
Definition at line 3 of file propagator.c++.
{
    // return 1./(exp((v-mu)/T)+1.);
    if constexpr (!ZERO_T) return 0.5 * (1. - tanh((v-mu)/(2.*T))); // numerically preferential
    else return (v-mu) < 0. ? 1. : 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and ZERO_T.
Referenced by Eff_distr(), and Eff_fac().
Fermi_distribution()
double Fermi_distribution (double nu)
Fermi_fac()
auto Fermi_fac (double v, double mu, const double T) -> double
Definition at line 9 of file propagator.c++.
{
    if constexpr (!ZERO_T) return tanh((v-mu)/(2.*T));
    else return sgn(v-mu);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), sgn(), and ZERO_T.
Referenced by compute_components_through_FDTs(), Eff_fac(), and Integrand_Phi_tilde< Q >::operator()().