SIAM-Keldysh-mfRG: flowgrid::sqrt_parametrization Class Reference
flowgrid::sqrt_parametrization Class Reference
#include <flow_grid.hpp>
Static Public Member Functions
static double lambda_from_t (double t)
static double t_from_lambda (double Lambda)
static double dlambda_dt (double t)
Static Private Attributes
static constexpr double a = 5.
Detailed Description
Definition at line 84 of file flow_grid.hpp.
Member Function Documentation
dlambda_dt()
static double flowgrid::sqrt_parametrization::dlambda_dt (double t) inline static
Definition at line 98 of file flow_grid.hpp.
        {
            double temp = sqrt(1-t*t);
            return a*std::abs(t) * (2. - t*t) / (temp*temp*temp);
        }
References a, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
lambda_from_t()
static double flowgrid::sqrt_parametrization::lambda_from_t (double t) inline static
Definition at line 88 of file flow_grid.hpp.
        {
            return a*t*t / sqrt(1. - t*t) * sign(t);
        }
References a, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sign().
t_from_lambda()
static double flowgrid::sqrt_parametrization::t_from_lambda (double Lambda) inline static
Definition at line 93 of file flow_grid.hpp.
        {
            return sqrt((sqrt(pow(Lambda, 4) + 4.*pow(a*Lambda, 2)) - pow(Lambda, 2))/2.)/a * sign(Lambda);
        }
References a, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sign().
Member Data Documentation
a
constexpr double flowgrid::sqrt_parametrization::a = 5. static constexpr private
Definition at line 86 of file flow_grid.hpp.
Referenced by dlambda_dt(), lambda_from_t(), and t_from_lambda().
The documentation for this class was generated from the following file:
flow_grid.hpp