SIAM-Keldysh-mfRG: causality_FDT_checks.hpp File Reference
causality_FDT_checks.hpp File Reference
#include "../data_structures.hpp"
#include "../correlation_functions/state.hpp"
#include "../correlation_functions/two_point/selfenergy.hpp"
#include "../utilities/util.hpp"
#include "../utilities/hdf5_routines.hpp"
Functions
template<typename Q >
void check_SE_causality (const SelfEnergy< Q > &selfEnergy)
template<typename Q >
void check_SE_causality (const State< Q > &state)
template<typename Q >
void check_SE_causality (const Q &selfEnergy)
template<typename Q >
SelfEnergy< Q > check_FDTs_selfenergy (const SelfEnergy< Q > &selfenergy, const double T, const bool verbose)
template<typename Q >
void check_FDTs_K1 (const rvert< Q > &rvert4K1, const char channel, const double T, const bool verbose)
deprecated
template<typename Q >
void check_FDTs (const State< Q > &state, bool verbose)
template<typename Q , char channel>
void compute_components_through_FDTs (fullvert< Q > &vertex_out, const fullvert< Q > &vertex_in, const fullvert< Q > &vertex_half2_in, const double T)
template<typename Q , typename vertexType >
void compute_components_through_FDTs (vertexType &vertex_out, const vertexType &vertex_in, const double T)
template<typename vertexType >
vertexType compare_with_FDTs (const vertexType &vertex_in, double Lambda, int Lambda_it, const std::string &filename_prefix, const fRG_config &config, const bool write_flag=false, int nLambda=1)
template<typename Q >
void compare_with_FDTs (const State< Q > &state_in, const int Lambda_it, const std::string &filename_prefix, const bool write_flag=false, const int nLambda=1)
void compare_flow_with_FDTs (const std::string filename, bool write_flag=false)
Function Documentation
check_FDTs()
template<typename Q > void check_FDTs (const State< Q > & state, bool verbose)
Definition at line 181 of file causality_FDT_checks.hpp.
{
    check_FDTs_selfenergy(state.selfenergy, state.config.T, verbose);
    for (char ch : {'a', 'p', 't'}) {
        check_FDTs_K1(state.vertex.get_rvertex(ch), ch, state.config.T, verbose);
    }
}
References check_FDTs_K1(), check_FDTs_selfenergy(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by postRKstep_stuff(), old_ode_solvers::RK4_step(), and sanity_check().
check_FDTs_K1()
template<typename Q > void check_FDTs_K1 (const rvert< Q > & rvert4K1, const char channel, const double T, const bool verbose)
deprecated
Definition at line 136 of file causality_FDT_checks.hpp.
{
    if constexpr(!CONTOUR_BASIS) {
        std::array<size_t, K1at_config.rank> dims_K = rvert4K1.K1.get_dims();
        dims_K[my_defs::K1::keldysh] = 1;
        using buffer_t = multidimensional::multiarray<Q, K1at_config.rank>;
        buffer_t Im_K1_R_from_data(dims_K);
        buffer_t Im_K1_R_from_FDTs(dims_K);
        const size_t size_flat = getFlatSize<K1at_config.rank>(dims_K);
        for (unsigned int i = 0; i < size_flat; i++) {
            std::array<my_index_t, K1at_config.rank> idx_R;
            getMultIndex<K1at_config.rank>(idx_R, i, dims_K);
            const std::array<my_index_t, K1at_config.rank> idx_0 = idx_R;
            idx_R[my_defs::K1::keldysh] = 1;
            std::array<my_index_t, K1at_config.rank> idx_K = idx_R;
            idx_K[my_defs::K1::keldysh] = channel == 'p' ? 5 : 3;
            const Q val_K_from_data = rvert4K1.K1.val(idx_K);
            const Q val_Im_R_from_data = myimag(rvert4K1.K1.val(idx_R));
            // Compute Keldysh component from FDTs:
            int iv = idx_K[my_defs::K1::omega];
            double v;
            rvert4K1.K1.frequencies.get_freqs_w(v, iv);
            const Q val_Im_R_from_FDTs = glb_i * 0.5 * Eff_fac(v,T) * val_K_from_data;
            Im_K1_R_from_data.at(idx_0) = val_Im_R_from_data;
            Im_K1_R_from_FDTs.at(idx_0) = val_Im_R_from_FDTs;
        }
        buffer_t difference = Im_K1_R_from_data - Im_K1_R_from_FDTs;
        double max_deviation = difference.max_norm();
        double max_norm_Kdat = Im_K1_R_from_data.max_norm();
        if (verbose) {
            utils::print("Check FDT for K1", rvert4K1.channel, ": \n");
            utils::print("Maximal abs. deviation from FDTs: \t", max_deviation, "\t",
                         " ||Im(K1^R)||_oo: \t", max_norm_Kdat, "\n");
        }
    }
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Eff_fac(), getFlatSize(), getMultIndex(), glb_i(), K1at_config, my_defs::K1::keldysh, myimag(), my_defs::K1::omega, and utils::print().
Referenced by check_FDTs().
check_FDTs_selfenergy()
template<typename Q > SelfEnergy< Q > check_FDTs_selfenergy (const SelfEnergy< Q > & selfenergy, const double T, const bool verbose)
Function that checks FDTs for a given self-energy.
Template Parameters
Q Template parameter specifying the type of the data.
Parameters
selfenergy Reference to a self-energy that shall be checked.
T Temperature at which the FDT shall be evaluated
verbose If true, the result of the check is written into the log file
Returns
Self-energy with the Keldysh component evaluated using the FDT. Can then be compared to the input self-energy.
Definition at line 92 of file causality_FDT_checks.hpp.
{
    std::array<size_t,SE_config.rank> dims_K = SE_config.dims;
    dims_K[my_defs::SE::keldysh] = 1;
    using buffer_t = multidimensional::multiarray<Q,SE_config.rank>;
    buffer_t SE_K_from_data(dims_K);
    SelfEnergy<Q> selfenergy_out = selfenergy;
    #if KELDYSH_FORMALISM
    const size_t size_flat = getFlatSize<SE_config.rank>(dims_K);
    for (unsigned int i = 0; i < size_flat; i++) {
        std::array<my_index_t,SE_config.rank> idx_R;
        getMultIndex<SE_config.rank>(idx_R,i,dims_K);
        std::array<my_index_t,SE_config.rank> idx_K = idx_R;
        idx_K[my_defs::SE::keldysh] = 1;
        const Q val_K_from_data = selfenergy.Sigma.val(idx_K);
        const Q val_R_from_data = selfenergy.Sigma.val(idx_R);
        // Compute Keldysh component from FDTs:
        int iv = idx_K[my_defs::SE::nu];
        double v;
        selfenergy.Sigma.frequencies.get_freqs_w(v, iv);
        const Q val_K_from_FDTs = glb_i * 2. * Eff_fac(v,T) * myimag(val_R_from_data);
        SE_K_from_data.at(idx_R) = val_K_from_data;
        selfenergy_out.Sigma.setvert(val_K_from_FDTs, idx_K);
    }
    SelfEnergy<Q> difference = selfenergy_out - selfenergy;
    double max_deviation = difference.norm();
    double max_norm_Kdat = SE_K_from_data.max_norm();
    if (verbose) {
        utils::print("Check FDT for selfenergy: \n");
        utils::print("Maximal deviation from FDTs (absolute): \t", max_deviation, "\n");
        utils::print("Maximal absolute value of Sigma^K: \t", max_norm_Kdat, "\n");
    }
    #endif
    return selfenergy_out;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Eff_fac(), getFlatSize(), getMultIndex(), glb_i(), my_defs::SE::keldysh, myimag(), SelfEnergy< Q >::norm(), my_defs::SE::nu, utils::print(), SE_config, and selfenergy.
Referenced by check_FDTs(), and compare_with_FDTs().
check_SE_causality() [1/3]
template<typename Q > void check_SE_causality (const Q & selfEnergy)
Definition at line 81 of file causality_FDT_checks.hpp.
{}
check_SE_causality() [2/3]
template<typename Q > void check_SE_causality (const SelfEnergy< Q > & selfEnergy)
Function that checks causality of self-energy Im(Sigma^R)<=0, and writes the result into the log file.
Template Parameters
Q Template parameter specifying the type of the data.
Parameters
selfEnergy Reference to a self-energy that shall be checked.
Definition at line 16 of file causality_FDT_checks.hpp.
{
    if (KELDYSH) {
        utils::print("Causality check of self-energy: Im(Sigma^R)<=0.", true);
        using SE_buffertype = typename SelfEnergy<Q>::buffer_type;
        SE_buffertype Sigma = selfEnergy.Sigma;                        // take self-energy
        vec<Q> Sigma_R(Sigma.get_vec().begin(), Sigma.get_vec().begin() + (nFER));     // take first half of self-energy (retarded comp.)
        assert(Sigma_R.size() == nFER);
        // check if Im(Sigma^R) is positive for every data point
        int cnt = 0;
        double sum = 0.;
        double max = 0.;
        for (unsigned int i = 0; i < Sigma_R.size(); ++i) {
            double val = myimag(Sigma_R[i]);
            if (val > 0.) {
                cnt += 1;
                sum += val;
                max = std::max(max, val);
            }
        }
        selfEnergy.Sigma.initInterpolator();
        if (cnt > 0) {
            utils::print("Selfenergy is non-causal: ", true);
            utils::print(cnt, " values of Im(Sigma^R) are positive, with a maximum of ", max, true);
            utils::print("value at v=0: ", selfEnergy.valsmooth(0, 0., 0), true);
        } else {
            utils::print("Selfenergy is causal.", true);
            utils::print("value at v=0: ", selfEnergy.valsmooth(0, 0., 0), true);
        }
    }
    else {
        utils::print("Causality check of self-energy: Im[Sigma(w)]*w<=0.", true);
        auto Sigma = selfEnergy.Sigma;                        // take self-energy
        // check if Im(Sigma^R) is positive for every data point
        int cnt = 0;
        double sum = 0.;
        for (int i = 0; i < nFER; ++i) {
            double val = myimag(Sigma.acc(i)) * sign(selfEnergy.Sigma.frequencies.  primary_grid.get_frequency(i));
            if (val > 0.) {
                //cout << "i: " << i << "\t for w = " << selfenergy.Sigma.frequencies.  primary_grid.get_frequency(i) << "; \t Sigma[i] = " << Sigma[i] << "\n";
                cnt += 1;
                sum += val;
            }
        }
        if (cnt > 0) {
            utils::print("Im[Selfenergy] is not negative for positive w (vice versa): ", true);
            utils::print(cnt, " values of Im(Sigma) have the wrong sign, with a sum of ", sum, true);
        } else
            utils::print("Selfenergy has the right sign.", true);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::initInterpolator(), KELDYSH, myimag(), nFER, utils::print(), SelfEnergy< Q >::Sigma, sign(), and SelfEnergy< Q >::valsmooth().
Referenced by check_SE_causality(), postRKstep_stuff(), old_ode_solvers::RK4_step(), and sanity_check().
check_SE_causality() [3/3]
template<typename Q > void check_SE_causality (const State< Q > & state)
Definition at line 76 of file causality_FDT_checks.hpp.
{
    check_SE_causality(state.selfenergy);
}
References check_SE_causality(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
compare_flow_with_FDTs()
void compare_flow_with_FDTs (const std::string filename, bool write_flag = false)
Definition at line 3 of file causality_FDT_checks.c++.
{
    rvec Lambdas = read_Lambdas_from_hdf(filename);
    //const int nLambda = Lambdas.size();
    int Lambda_it_max = -1;
    check_convergence_hdf(filename, Lambda_it_max);
    for (unsigned int i = 0; i < Lambda_it_max; i++) {
        State<state_datatype>  state_in = read_state_from_hdf(filename, i); // read state
        compare_with_FDTs(state_in, i, filename, write_flag, Lambda_it_max);
    }
}
References check_convergence_hdf(), compare_with_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), read_Lambdas_from_hdf(), and read_state_from_hdf().
compare_with_FDTs() [1/2]
template<typename Q > void compare_with_FDTs (const State< Q > & state_in, const int Lambda_it, const std::string & filename_prefix, const bool write_flag = false, const int nLambda = 1)
Definition at line 920 of file causality_FDT_checks.hpp.
{
    State<Q> state_out = state_in;
    state_out.selfenergy = check_FDTs_selfenergy(state_in.selfenergy, state_in.config.T, true);
    state_out.vertex = compare_with_FDTs(state_in.vertex, state_in.Lambda, Lambda_it, filename_prefix, state_in.config, false, nLambda);
    if (write_flag) {
        State<Q> state_diff = state_out - state_in;
        if (Lambda_it == 0) {
            write_state_to_hdf(data_dir + filename_prefix + "_FDTresult", state_in.Lambda, nLambda, state_out);
            write_state_to_hdf(data_dir + filename_prefix + "_FDTdiff", state_in.Lambda, nLambda, state_diff);
        } else {
            add_state_to_hdf(data_dir + filename_prefix + "_FDTresult", Lambda_it, state_out);
            add_state_to_hdf(data_dir + filename_prefix + "_FDTdiff", Lambda_it, state_diff);
        }
    }
}
References add_state_to_hdf(), check_FDTs_selfenergy(), compare_with_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), data_dir, State< Q, differentiated >::selfenergy, and write_state_to_hdf().
compare_with_FDTs() [2/2]
template<typename vertexType > vertexType compare_with_FDTs (const vertexType & vertex_in, double Lambda, int Lambda_it, const std::string & filename_prefix, const fRG_config & config, const bool write_flag = false, int nLambda = 1)
Definition at line 856 of file causality_FDT_checks.hpp.
{
    using Q = typename vertexType::base_type;
    vertexType vertex_out = vertex_in;
    if(KELDYSH) {
        const double T = config.T;
            compute_components_through_FDTs<Q>(vertex_out, vertex_in, T);
            utils::print("Checking the FDTs for Lambda_it", Lambda_it, true);
            vertexType vertex_diff = vertex_in - vertex_out;
            if (mpi_world_rank() == 0) {
                utils::print("K1: max-norm of deviation = ", false);
                std::cout << vertex_diff.half1().norm_K1(0) << std::scientific << '\n';
                utils::print("K1: relative deviation = ", false);
                std::cout << vertex_diff.half1().norm_K1(0) / vertex_out.half1().norm_K1(0) << std::scientific << '\n';
                utils::print("K1: max-norm = ", false);
                std::cout << vertex_out.half1().norm_K1(0) << std::scientific << '\n';
                if (MAX_DIAG_CLASS > 1) {
                    utils::print("K2: max-norm of deviation = ", false);
                    std::cout << vertex_diff.half1().norm_K2(0) << std::scientific << '\n';
                    utils::print("K2: relative deviation = ", false);
                    std::cout << vertex_diff.half1().norm_K2(0) / vertex_out.half1().norm_K2(0) << std::scientific << '\n';
                    utils::print("K2: max-norm = ", false);
                    std::cout << vertex_out.half1().norm_K2(0) << std::scientific << '\n';
                }
                if (MAX_DIAG_CLASS > 2) {
                    utils::print("K3: max-norm of deviation = ", false);
                    std::cout << vertex_diff.half1().norm_K3(0) << std::scientific << '\n';
                    utils::print("K3: relative deviation = ", false);
                    std::cout << vertex_diff.half1().norm_K3(0) / vertex_out.half1().norm_K3(0) << std::scientific << '\n';
                    utils::print("K3: max-norm = ", false);
                    std::cout << vertex_out.half1().norm_K3(0) << std::scientific << '\n';
                }
            }
            if (write_flag) {
                SelfEnergy<Q> SE_empty(Lambda, config);
                Vertex<Q,false> temp_diff(Lambda, config);
                temp_diff.half1() = vertex_diff.half1();
                Vertex<Q,false> temp_out(Lambda, config);
                temp_out.half1() = vertex_out.half1();
                State<Q> state_out(temp_out, SE_empty, config, Lambda);
                State<Q> state_diff(temp_diff, SE_empty, config, Lambda);
                if (Lambda_it == 0) {
                    write_state_to_hdf(data_dir + filename_prefix + "_FDTresult", Lambda, nLambda, state_out);
                    write_state_to_hdf(data_dir + filename_prefix + "_FDTdiff", Lambda, nLambda, state_diff);
                } else {
                    add_state_to_hdf(data_dir + filename_prefix + "_FDTresult", Lambda_it, state_out);
                    add_state_to_hdf(data_dir + filename_prefix + "_FDTdiff", Lambda_it, state_diff);
                }
            }
    }
    return vertex_out;
}
References add_state_to_hdf(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), data_dir, KELDYSH, MAX_DIAG_CLASS, mpi_world_rank(), utils::print(), fRG_config::T, and write_state_to_hdf().
Referenced by compare_flow_with_FDTs(), compare_with_FDTs(), and rhs_n_loop_flow().
compute_components_through_FDTs() [1/2]
template<typename Q , char channel> void compute_components_through_FDTs (fullvert< Q > & vertex_out, const fullvert< Q > & vertex_in, const fullvert< Q > & vertex_half2_in, const double T)
Function that computes vertex components with the help of fluctuation-dissipation relations. Components obtainable by FDTs: K1r[1] (with r = a/p/t) K2a, K2a[2], K2a[3] K2p[0], K2p[1], K2p[3] K2t[0], K2t[2], K2t[3] K3r[0], K3r[1] (with r = a/p/t)
These components are written into state_out. The other components are copied to state_out. CAUTION: For the K2-class the FDTs involve numerically diverging prefactors for zero bosonic frequency
FDTs for K1
FDTs for K2 objects:
Definition at line 203 of file causality_FDT_checks.hpp.
{
    if constexpr(CONTOUR_BASIS) {
        vertex_out = vertex_in;
    } else {
        if constexpr(channel == 'a') {
#pragma omp parallel for collapse(3)
            for (int itw = 0; itw < nw1; itw++) {
                for (int itspin = 0; itspin < n_in; itspin++) {
                    for (int itin = 0; itin < n_in; itin++) {
                        my_defs::K1::index_type idx;
                        idx[my_defs::K1::keldysh] = 3;
                        idx[my_defs::K1::spin] = itspin;
                        idx[my_defs::K1::omega] = itw;
                        idx[my_defs::K1::internal] = itin;
                        freqType w;
                        double N1;
                        Q G1, G2;
                        vertex_in.avertex.K1.frequencies.get_freqs_w(w, itw);
                        if (std::abs(w) > T * 25.) { // spare the region around zero
                            N1 = 1. / Fermi_fac(w, glb_mu, T);
                            VertexInput inputG1(1, itspin, w, 0, 0, itin, 'a');  // advanced component
                            G1 = vertex_in.avertex.template valsmooth<k1>(inputG1, vertex_in.tvertex,
                                                                          vertex_half2_in.avertex,
                                                                          vertex_half2_in.tvertex);
                            G2 = N1 * (myconj(G1) - G1);
                            vertex_out.avertex.K1.setvert(G2, idx);
                        }
                    }
                }
            }
        } else if constexpr(channel == 'p') {
#pragma omp parallel for collapse(3)
            for (int itw = 0; itw < nw1; itw++) {
                for (int itspin = 0; itspin < n_in; itspin++) {
                    for (int itin = 0; itin < n_in; itin++) {
                        my_defs::K1::index_type idx;
                        idx[my_defs::K1::keldysh] = 5;
                        idx[my_defs::K1::spin] = itspin;
                        idx[my_defs::K1::omega] = itw;
                        idx[my_defs::K1::internal] = itin;
                        freqType w;
                        double N1;
                        Q G1, G2;
                        vertex_in.pvertex.K1.frequencies.get_freqs_w(w, itw);
                        if (std::abs(w) > T * 25.) {
                            N1 = 1. / Fermi_fac(w, glb_mu, T);
                            VertexInput inputG1(1, itspin, w, 0, 0, itin, 'a');  // advanced component
                            G1 = vertex_in.pvertex.template valsmooth<k1>(inputG1, vertex_in.pvertex,
                                                                          vertex_half2_in.pvertex,
                                                                          vertex_half2_in.pvertex);
                            G2 = N1 * (myconj(G1) - G1);
                            vertex_out.pvertex.K1.setvert(G2, idx);
                        }
                    }
                }
            }
        } else {
            static_assert(channel == 't', "Invalid channel");
#pragma omp parallel for collapse(3)
            for (int itw = 0; itw < nw1; itw++) {
                for (int itspin = 0; itspin < n_in; itspin++) {
                    for (int itin = 0; itin < n_in; itin++) {
                        my_defs::K1::index_type idx;
                        idx[my_defs::K1::keldysh] = 3;
                        idx[my_defs::K1::spin] = itspin;
                        idx[my_defs::K1::omega] = itw;
                        idx[my_defs::K1::internal] = itin;
                        freqType w;
                        double N1;
                        Q G1, G2;
                        vertex_in.tvertex.K1.frequencies.get_freqs_w(w, itw);
                        if (std::abs(w) > T * 25.) {
                            N1 = 1. / Fermi_fac(w, glb_mu, T);
                            VertexInput inputG1(1, itspin, w, 0, 0, itin, 'a');  // advanced component
                            G1 = vertex_in.tvertex.template valsmooth<k1>(inputG1, vertex_in.avertex,
                                                                          vertex_half2_in.tvertex,
                                                                          vertex_half2_in.avertex);
                            G2 = N1 * (myconj(G1) - G1);
                            vertex_out.tvertex.K1.setvert(G2, idx);
                        }
                    }
                }
            }
        }
#if MAX_DIAG_CLASS > 1
        if constexpr(channel == 'a') {
#pragma omp parallel for collapse(4)
            for (int itw = 0; itw < nw2; itw++) {
                for (int itv = 0; itv < nv2; itv++) {
                    for (int itspin = 0; itspin < n_in; itspin++) {
                        for (int itin = 0; itin < n_in; itin++) {
                            my_defs::K2::index_type idx;
                            //idx[my_defs::K2::keldysh] = ;
                            idx[my_defs::K2::spin] = itspin;
                            idx[my_defs::K2::omega] = itw;
                            idx[my_defs::K2::nu] = itv;
                            idx[my_defs::K2::internal] = itin;
                            freqType w, v;
                            double N1, N2, N3;
                            Q G1, G2, G3, G12, G23, G123;
                            vertex_in.avertex.K2.frequencies.get_freqs_w(w, v, itw, itv);
                            if (std::abs(w) > T) {
                                N1 = Fermi_fac(-v - w / 2, glb_mu, T);
                                N2 = Fermi_fac(v - w / 2, glb_mu, T);
                                N3 = 1. / Fermi_fac(w, glb_mu, T);
                                VertexInput inputG1(8, itspin, w, v, 0, itin, 'a');
                                VertexInput inputG2(1, itspin, w, v, 0, itin, 'a');
                                VertexInput inputG3(11, itspin, w, v, 0, itin, 'a');
                                G1 = vertex_in.avertex.template valsmooth<k2>(inputG1, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G2 = vertex_in.avertex.template valsmooth<k2>(inputG2, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G3 = vertex_in.avertex.template valsmooth<k2>(inputG3, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G123 = myconj(G1 + G2 + G3)
                                       + myreal(G1 * N2 * N3
                                                + N1 * G2 * N3
                                                + N1 * N2 * G3) * 2.;
                                G12 = N2 * (myconj(G3) - G1) + N1 * (myconj(G3) - G2);
                                //G13 = N3 * (myconj(G2) - G1) + N1 * (myconj(G2) - G3);
                                G23 = N3 * (myconj(G1) - G2) + N2 * (myconj(G1) - G3);
                                idx[my_defs::K2::keldysh] = 0;
                                vertex_out.avertex.K2.setvert(G12, idx);
                                idx[my_defs::K2::keldysh] = 2;
                                vertex_out.avertex.K2.setvert(G123, idx);
                                idx[my_defs::K2::keldysh] = 3;
                                vertex_out.avertex.K2.setvert(G23, idx);
                            }
                        }
                    }
                }
            }
        } else if constexpr (channel == 'p') {
#pragma omp parallel for collapse(4)
            for (int itw = 0; itw < nw2; itw++) {
                for (int itv = 0; itv < nv2; itv++) {
                    for (int itspin = 0; itspin < n_in; itspin++) {
                        for (int itin = 0; itin < n_in; itin++) {
                            my_defs::K2::index_type idx;
                            //idx[my_defs::K2::keldysh] = ;
                            idx[my_defs::K2::spin] = itspin;
                            idx[my_defs::K2::omega] = itw;
                            idx[my_defs::K2::nu] = itv;
                            idx[my_defs::K2::internal] = itin;
                            freqType w, v;
                            double N1, N2, N3;
                            Q G1, G2, G3, G12, G13, G123;
                            vertex_in.pvertex.K2.frequencies.get_freqs_w(w, v, itw, itv);
                            if (std::abs(w) > T * 1.) {//
                                N1 = Fermi_fac(v + w / 2, glb_mu, T);
                                N2 = Fermi_fac(-v + w / 2, glb_mu, T);
                                N3 = 1. / Fermi_fac(-w, glb_mu, T);
                                VertexInput inputG1(4, itspin, w, v, 0, itin, 'p');
                                VertexInput inputG2(8, itspin, w, v, 0, itin, 'p');
                                VertexInput inputG3(13, itspin, w, v, 0, itin, 'p');
                                G1 = vertex_in.pvertex.template valsmooth<k2>(inputG1, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G2 = vertex_in.pvertex.template valsmooth<k2>(inputG2, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G3 = vertex_in.pvertex.template valsmooth<k2>(inputG3, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G123 = myconj(G1 + G2 + G3)
                                       + myreal(G1 * N2 * N3
                                                + N1 * G2 * N3
                                                + N1 * N2 * G3) * 2.;
                                G12 = N2 * (myconj(G3) - G1) + N1 * (myconj(G3) - G2);
                                G13 = N3 * (myconj(G2) - G1) + N1 * (myconj(G2) - G3);
                                //G23 = N3 * (myconj(G1) - G2) + N2 * (myconj(G1) - G3);
                                idx[my_defs::K2::keldysh] = 0;
                                vertex_out.pvertex.K2.setvert(G12, idx);
                                idx[my_defs::K2::keldysh] = 1;
                                vertex_out.pvertex.K2.setvert(G123, idx);
                                idx[my_defs::K2::keldysh] = 5;
                                vertex_out.pvertex.K2.setvert(G13, idx);
                            }
                        }
                    }
                }
            }
        } else {
            static_assert(channel == 't', "Invalid channel");
#pragma omp parallel for collapse(4)
            for (int itw = 0; itw < nw2; itw++) {
                for (int itv = 0; itv < nv2; itv++) {
                    for (int itspin = 0; itspin < n_in; itspin++) {
                        for (int itin = 0; itin < n_in; itin++) {
                            my_defs::K2::index_type idx;
                            idx[my_defs::K2::spin] = itspin;
                            idx[my_defs::K2::omega] = itw;
                            idx[my_defs::K2::nu] = itv;
                            idx[my_defs::K2::internal] = itin;
                            freqType w, v;
                            double N1, N2, N3;
                            Q G1, G2, G3, G12, G23, G123;
                            vertex_in.tvertex.K2.frequencies.get_freqs_w(w, v, itw, itv);
                            if (std::abs(w) > T * 1.) {
                                N1 = Fermi_fac(-v - w / 2, glb_mu, T);
                                N2 = Fermi_fac(v - w / 2, glb_mu, T);
                                N3 = 1. / Fermi_fac(w, glb_mu, T);
                                VertexInput inputG1(4, itspin, w, v, 0, itin, 't');
                                VertexInput inputG2(1, itspin, w, v, 0, itin, 't');
                                VertexInput inputG3(7, itspin, w, v, 0, itin, 't');
                                G1 = vertex_in.tvertex.template valsmooth<k2>(inputG1, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G2 = vertex_in.tvertex.template valsmooth<k2>(inputG2, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G3 = vertex_in.tvertex.template valsmooth<k2>(inputG3, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G123 = myconj(G1 + G2 + G3)
                                       + myreal(G1 * N2 * N3
                                                + N1 * G2 * N3
                                                + N1 * N2 * G3) * 2.;
                                G12 = N2 * (myconj(G3) - G1) + N1 * (myconj(G3) - G2);
                                //G13 = N3 * (myconj(G2) - G1) + N1 * (myconj(G2) - G3);
                                G23 = N3 * (myconj(G1) - G2) + N2 * (myconj(G1) - G3);
                                idx[my_defs::K2::keldysh] = 0;
                                vertex_out.tvertex.K2.setvert(G12, idx);
                                idx[my_defs::K2::keldysh] = 2;
                                vertex_out.tvertex.K2.setvert(G123, idx);
                                idx[my_defs::K2::keldysh] = 3;
                                vertex_out.tvertex.K2.setvert(G23, idx);
                            }
                        }
                    }
                }
            }
        }
#endif
#if MAX_DIAG_CLASS > 2
        if constexpr(channel == 'a') {
#pragma omp parallel for collapse(5)
            for (int itw = 0; itw < nw3; itw++) {
                for (int itv = 0; itv < nv3; itv++) {
                    for (int itvp = 0; itvp < (GRID != 2 ? nv3 : (nv3 - 1) / 2 + 1); itvp++) {
                        for (int itspin = 0; itspin < n_spin; itspin++) {
                            for (int itin = 0; itin < n_in; itin++) {
                                my_defs::K3::index_type idx;
                                idx[my_defs::K3::spin] = itspin;
                                idx[my_defs::K3::omega] = itw;
                                idx[my_defs::K3::nu] = itv;
                                idx[my_defs::K3::nup] = itvp;
                                idx[my_defs::K3::internal] = itin;
                                double w, v, vp, N1, N2, N3, N4;
                                Q G1, G2, G3, G4, G12, G13, G14, G23, G24, G34, G1234, G123;
                                vertex_in.avertex.K3.frequencies.get_freqs_w(w, v, vp, itw, itv, itvp);
                                N1 = Fermi_fac(v - w / 2, glb_mu, T);
                                N2 = Fermi_fac(vp + w / 2, glb_mu, T);
                                N3 = Fermi_fac(-vp + w / 2, glb_mu, T);
                                N4 = Fermi_fac(-v - w / 2, glb_mu, T);
                                VertexInput inputG1(7, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG2(11, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG3(13, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG4(14, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG12(3, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG13(5, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG14(6, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG23(9, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG24(10, itspin, w, v, vp, itin, 'a');
                                VertexInput inputG34(12, itspin, w, v, vp, itin, 'a');
                                G1 = vertex_in.avertex.template valsmooth<k3>(inputG1, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G2 = vertex_in.avertex.template valsmooth<k3>(inputG2, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G3 = vertex_in.avertex.template valsmooth<k3>(inputG3, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G4 = vertex_in.avertex.template valsmooth<k3>(inputG4, vertex_in.tvertex,
                                                                              vertex_half2_in.avertex,
                                                                              vertex_half2_in.tvertex);
                                G12 = vertex_in.avertex.template valsmooth<k3>(inputG12, vertex_in.tvertex,
                                                                               vertex_half2_in.avertex,
                                                                               vertex_half2_in.tvertex);
                                G13 = vertex_in.avertex.template valsmooth<k3>(inputG13, vertex_in.tvertex,
                                                                               vertex_half2_in.avertex,
                                                                               vertex_half2_in.tvertex);
                                G14 = vertex_in.avertex.template valsmooth<k3>(inputG14, vertex_in.tvertex,
                                                                               vertex_half2_in.avertex,
                                                                               vertex_half2_in.tvertex);
                                G23 = vertex_in.avertex.template valsmooth<k3>(inputG23, vertex_in.tvertex,
                                                                               vertex_half2_in.avertex,
                                                                               vertex_half2_in.tvertex);
                                G24 = vertex_in.avertex.template valsmooth<k3>(inputG24, vertex_in.tvertex,
                                                                               vertex_half2_in.avertex,
                                                                               vertex_half2_in.tvertex);
                                G34 = vertex_in.avertex.template valsmooth<k3>(inputG34, vertex_in.tvertex,
                                                                               vertex_half2_in.avertex,
                                                                               vertex_half2_in.tvertex);
                                G123 = (1 + N1 * N2 + N1 * N3 + N2 * N3) * myconj(G4)
                                       - (G1 * N2 * N3
                                          + N1 * G2 * N3
                                          + N1 * N2 * G3
                                          + N1 * G23
                                          + G12 * N3
                                          + G13 * N2);
                                G1234 = G1 * N2 * N3 * N4 * 2.
                                        + N1 * G2 * N3 * N4 * 2.
                                        + N1 * N2 * G3 * N4 * 2.
                                        + N1 * N2 * N3 * G4 * 2.
                                        + (N2 * N3 * N4 + N2 + N3 + N4) * myconj(G1)
                                        + (N1 * N3 * N4 + N1 + N3 + N4) * myconj(G2)
                                        + (N1 * N2 * N4 + N1 + N2 + N4) * myconj(G3)
                                        + (N1 * N2 * N3 + N1 + N2 + N3) * myconj(G4)
                                        + N3 * N4 * G12
                                        + N2 * N4 * G13
                                        + N2 * N3 * G14
                                        + N1 * N4 * G23
                                        + N1 * N3 * G24
                                        + N1 * N2 * G34;
                                idx[my_defs::K3::keldysh] = 0;
                                vertex_out.avertex.K3.setvert(G1234, idx);
                                idx[my_defs::K3::keldysh] = 1;
                                vertex_out.avertex.K3.setvert(G123, idx);
                            }
                        }
                    }
                }
            }
        } else if constexpr (channel == 'p') {
#pragma omp parallel for collapse(5)
            for (int itw = 0; itw < nw3; itw++) {
                for (int itv = 0; itv < nv3; itv++) {
                    for (int itvp = 0; itvp < (GRID != 2 ? nv3 : (nv3 - 1) / 2 + 1); itvp++) {
                        for (int itspin = 0; itspin < n_spin; itspin++) {
                            for (int itin = 0; itin < n_in; itin++) {
                                my_defs::K3::index_type idx;
                                idx[my_defs::K3::spin] = itspin;
                                idx[my_defs::K3::omega] = itw;
                                idx[my_defs::K3::nu] = itv;
                                idx[my_defs::K3::nup] = itvp;
                                idx[my_defs::K3::internal] = itin;
                                double w, v, vp, N1, N2, N3, N4;
                                Q G1, G2, G3, G4, G12, G13, G14, G23, G24, G34, G1234, G123;
                                vertex_in.pvertex.K3.frequencies.get_freqs_w(w, v, vp, itw, itv, itvp);
                                N1 = Fermi_fac(v + w / 2, glb_mu, T);
                                N2 = Fermi_fac(-v + w / 2, glb_mu, T);
                                N3 = Fermi_fac(-vp - w / 2, glb_mu, T);
                                N4 = Fermi_fac(vp - w / 2, glb_mu, T);
                                VertexInput inputG1(7, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG2(11, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG3(13, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG4(14, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG12(3, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG13(5, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG14(6, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG23(9, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG24(10, itspin, w, v, vp, itin, 'p');
                                VertexInput inputG34(12, itspin, w, v, vp, itin, 'p');
                                G1 = vertex_in.pvertex.template valsmooth<k3>(inputG1, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G2 = vertex_in.pvertex.template valsmooth<k3>(inputG2, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G3 = vertex_in.pvertex.template valsmooth<k3>(inputG3, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G4 = vertex_in.pvertex.template valsmooth<k3>(inputG4, vertex_in.pvertex,
                                                                              vertex_half2_in.pvertex,
                                                                              vertex_half2_in.pvertex);
                                G12 = vertex_in.pvertex.template valsmooth<k3>(inputG12, vertex_in.pvertex,
                                                                               vertex_half2_in.pvertex,
                                                                               vertex_half2_in.pvertex);
                                G13 = vertex_in.pvertex.template valsmooth<k3>(inputG13, vertex_in.pvertex,
                                                                               vertex_half2_in.pvertex,
                                                                               vertex_half2_in.pvertex);
                                G14 = vertex_in.pvertex.template valsmooth<k3>(inputG14, vertex_in.pvertex,
                                                                               vertex_half2_in.pvertex,
                                                                               vertex_half2_in.pvertex);
                                G23 = vertex_in.pvertex.template valsmooth<k3>(inputG23, vertex_in.pvertex,
                                                                               vertex_half2_in.pvertex,
                                                                               vertex_half2_in.pvertex);
                                G24 = vertex_in.pvertex.template valsmooth<k3>(inputG24, vertex_in.pvertex,
                                                                               vertex_half2_in.pvertex,
                                                                               vertex_half2_in.pvertex);
                                G34 = vertex_in.pvertex.template valsmooth<k3>(inputG34, vertex_in.pvertex,
                                                                               vertex_half2_in.pvertex,
                                                                               vertex_half2_in.pvertex);
                                G123 = (1 + N1 * N2 + N1 * N3 + N2 * N3) * myconj(G4)
                                       - (G1 * N2 * N3
                                          + N1 * G2 * N3
                                          + N1 * N2 * G3
                                          + N1 * G23
                                          + G12 * N3
                                          + G13 * N2);
                                G1234 = G1 * N2 * N3 * N4 * 2.
                                        + N1 * G2 * N3 * N4 * 2.
                                        + N1 * N2 * G3 * N4 * 2.
                                        + N1 * N2 * N3 * G4 * 2.
                                        + (N2 * N3 * N4 + N2 + N3 + N4) * myconj(G1)
                                        + (N1 * N3 * N4 + N1 + N3 + N4) * myconj(G2)
                                        + (N1 * N2 * N4 + N1 + N2 + N4) * myconj(G3)
                                        + (N1 * N2 * N3 + N1 + N2 + N3) * myconj(G4)
                                        + N3 * N4 * G12
                                        + N2 * N4 * G13
                                        + N2 * N3 * G14
                                        + N1 * N4 * G23
                                        + N1 * N3 * G24
                                        + N1 * N2 * G34;
                                idx[my_defs::K3::keldysh] = 0;
                                vertex_out.pvertex.K3.setvert(G1234, itspin, itw, itv, itvp, 0, itin);
                                idx[my_defs::K3::keldysh] = 1;
                                vertex_out.pvertex.K3.setvert(G123, itspin, itw, itv, itvp, 1, itin);
                            }
                        }
                    }
                }
            }
        } else {
            static_assert(channel == 't', "Invalid channel");
#pragma omp parallel for collapse(5)
            for (int itw = 0; itw < nw3; itw++) {
                for (int itv = 0; itv < nv3; itv++) {
                    for (int itvp = 0; itvp < (GRID != 2 ? nv3 : (nv3 - 1) / 2 + 1); itvp++) {
                        for (int itspin = 0; itspin < n_spin; itspin++) {
                            for (int itin = 0; itin < n_in; itin++) {
                                my_defs::K3::index_type idx;
                                idx[my_defs::K3::spin] = itspin;
                                idx[my_defs::K3::omega] = itw;
                                idx[my_defs::K3::nu] = itv;
                                idx[my_defs::K3::nup] = itvp;
                                idx[my_defs::K3::internal] = itin;
                                double w, v, vp, N1, N2, N3, N4;
                                Q G1, G2, G3, G4, G12, G13, G14, G23, G24, G34, G1234, G123;
                                vertex_in.tvertex.K3.frequencies.get_freqs_w(w, v, vp, itw, itv, itvp);
                                N1 = Fermi_fac(vp + w / 2, glb_mu, T);
                                N2 = Fermi_fac(v - w / 2, glb_mu, T);
                                N3 = Fermi_fac(-vp + w / 2, glb_mu, T);
                                N4 = Fermi_fac(-v - w / 2, glb_mu, T);
                                VertexInput inputG1(7, itspin, w, v, vp, itin, 't');
                                VertexInput inputG2(11, itspin, w, v, vp, itin, 't');
                                VertexInput inputG3(13, itspin, w, v, vp, itin, 't');
                                VertexInput inputG4(14, itspin, w, v, vp, itin, 't');
                                VertexInput inputG12(3, itspin, w, v, vp, itin, 't');
                                VertexInput inputG13(5, itspin, w, v, vp, itin, 't');
                                VertexInput inputG14(6, itspin, w, v, vp, itin, 't');
                                VertexInput inputG23(9, itspin, w, v, vp, itin, 't');
                                VertexInput inputG24(10, itspin, w, v, vp, itin, 't');
                                VertexInput inputG34(12, itspin, w, v, vp, itin, 't');
                                G1 = vertex_in.tvertex.template valsmooth<k3>(inputG1, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G2 = vertex_in.tvertex.template valsmooth<k3>(inputG2, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G3 = vertex_in.tvertex.template valsmooth<k3>(inputG3, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G4 = vertex_in.tvertex.template valsmooth<k3>(inputG4, vertex_in.avertex,
                                                                              vertex_half2_in.tvertex,
                                                                              vertex_half2_in.avertex);
                                G12 = vertex_in.tvertex.template valsmooth<k3>(inputG12, vertex_in.avertex,
                                                                               vertex_half2_in.tvertex,
                                                                               vertex_half2_in.avertex);
                                G13 = vertex_in.tvertex.template valsmooth<k3>(inputG13, vertex_in.avertex,
                                                                               vertex_half2_in.tvertex,
                                                                               vertex_half2_in.avertex);
                                G14 = vertex_in.tvertex.template valsmooth<k3>(inputG14, vertex_in.avertex,
                                                                               vertex_half2_in.tvertex,
                                                                               vertex_half2_in.avertex);
                                G23 = vertex_in.tvertex.template valsmooth<k3>(inputG23, vertex_in.avertex,
                                                                               vertex_half2_in.tvertex,
                                                                               vertex_half2_in.avertex);
                                G24 = vertex_in.tvertex.template valsmooth<k3>(inputG24, vertex_in.avertex,
                                                                               vertex_half2_in.tvertex,
                                                                               vertex_half2_in.avertex);
                                G34 = vertex_in.tvertex.template valsmooth<k3>(inputG34, vertex_in.avertex,
                                                                               vertex_half2_in.tvertex,
                                                                               vertex_half2_in.avertex);
                                G123 = (1 + N1 * N2 + N1 * N3 + N2 * N3) * myconj(G4)
                                       - (G1 * N2 * N3
                                          + N1 * G2 * N3
                                          + N1 * N2 * G3
                                          + N1 * G23
                                          + G12 * N3
                                          + G13 * N2);
                                G1234 = G1 * N2 * N3 * N4 * 2.
                                        + N1 * G2 * N3 * N4 * 2.
                                        + N1 * N2 * G3 * N4 * 2.
                                        + N1 * N2 * N3 * G4 * 2.
                                        + (N2 * N3 * N4 + N2 + N3 + N4) * myconj(G1)
                                        + (N1 * N3 * N4 + N1 + N3 + N4) * myconj(G2)
                                        + (N1 * N2 * N4 + N1 + N2 + N4) * myconj(G3)
                                        + (N1 * N2 * N3 + N1 + N2 + N3) * myconj(G4)
                                        + N3 * N4 * G12
                                        + N2 * N4 * G13
                                        + N2 * N3 * G14
                                        + N1 * N4 * G23
                                        + N1 * N3 * G24
                                        + N1 * N2 * G34;
                                idx[my_defs::K3::keldysh] = 0;
                                vertex_out.tvertex.K3.setvert(G1234, itspin, itw, itv, itvp, 0, itin);
                                idx[my_defs::K3::keldysh] = 1;
                                vertex_out.tvertex.K3.setvert(G123, itspin, itw, itv, itvp, 1, itin);
                            }
                        }
                    }
                }
            }
        }
#endif
    }
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Fermi_fac(), glb_mu, GRID, my_defs::K1::internal, my_defs::K2::internal, my_defs::K3::internal, my_defs::K1::keldysh, my_defs::K2::keldysh, my_defs::K3::keldysh, myconj(), myreal(), n_in, n_spin, my_defs::K2::nu, my_defs::K3::nu, my_defs::K3::nup, nv2, nv3, nw1, nw2, nw3, my_defs::K1::omega, my_defs::K2::omega, my_defs::K3::omega, my_defs::K1::spin, my_defs::K2::spin, and my_defs::K3::spin.
Referenced by fullvert< Q >::reorder_due2antisymmetry(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K2(), and BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K3().
compute_components_through_FDTs() [2/2]
template<typename Q , typename vertexType > void compute_components_through_FDTs (vertexType & vertex_out, const vertexType & vertex_in, const double T)
Evaluate the FDTs:
for contour basis and T=0:
for Keldysh basis:
Definition at line 765 of file causality_FDT_checks.hpp.
{
    vertex_in.initializeInterpol();
    if (CONTOUR_BASIS and not ZERO_T) {
        throw std::runtime_error("No implementation of FDTs for finite T in contour basis yet.");
    }
    else if (CONTOUR_BASIS and ZERO_T) {
        for (char r: {'a', 'p', 't'}) {
            const auto& K1 = vertex_in.get_rvertex(r).K1;
            for (unsigned int iflat = 0; iflat < getFlatSize(K1.get_dims()); iflat++) {
                my_defs::K1::index_type idx;
                getMultIndex<rank_K1>(idx, iflat, K1.get_dims());
                int itK = (int) idx[my_defs::K1::keldysh];
                my_index_t itw = idx[my_defs::K1::omega];
                freqType w;
                K1.frequencies.get_freqs_w(w, itw);
                if (is_zero_due_to_FDTs<k1>(itK, w, 0., 0., r)) {
                    vertex_out.get_rvertex(r).K1.setvert(0., idx);
                }
                else {
                    Q value = K1.val(idx);
                    vertex_out.get_rvertex(r).K1.setvert(value, idx);
                }
            }
        }
        if (MAX_DIAG_CLASS > 1) {
            for (char r: {'a', 'p', 't'}) {
                const auto& K2 = vertex_in.get_rvertex(r).K2;
                for (unsigned int iflat = 0; iflat < getFlatSize(K2.get_dims()); iflat++) {
                    my_defs::K2::index_type idx;
                    getMultIndex<rank_K2>(idx, iflat, K2.get_dims());
                    int itK = (int) idx[my_defs::K2::keldysh];
                    my_index_t itw = idx[my_defs::K2::omega];
                    my_index_t itv = idx[my_defs::K2::nu];
                    freqType w, v;
                    K2.frequencies.get_freqs_w(w, v, itw, itv);
                    if (is_zero_due_to_FDTs<k2>(itK, w, v, 0., r)) {
                        vertex_out.get_rvertex(r).K2.setvert(0., idx);
                    }
                    else {
                        Q value = K2.val(idx);
                        vertex_out.get_rvertex(r).K2.setvert(value, idx);
                    }
                }
            }
        }
        if (MAX_DIAG_CLASS > 2) {
            for (char r: {'a', 'p', 't'}) {
                const auto& K3 = vertex_in.get_rvertex(r).K3;
                for (unsigned int iflat = 0; iflat < getFlatSize(K3.get_dims()); iflat++) {
                    my_defs::K3::index_type idx;
                    getMultIndex<rank_K3>(idx, iflat, K3.get_dims());
                    int itK = (int) idx[my_defs::K3::keldysh];
                    my_index_t itw = idx[my_defs::K3::omega];
                    my_index_t itv = idx[my_defs::K3::nu];
                    my_index_t itvp= idx[my_defs::K3::nup];
                    freqType w, v, vp;
                    K3.frequencies.get_freqs_w(w, v, vp, itw, itv, itvp);
                    if (is_zero_due_to_FDTs<k3>(itK, w, v, vp, r)) {
                        vertex_out.get_rvertex(r).K3.setvert(0., idx);
                    }
                    else {
                        Q value = K3.val(idx);
                        vertex_out.get_rvertex(r).K3.setvert(value, idx);
                    }
                }
            }
        }
    }
    else {
        compute_components_through_FDTs<Q, 'a'>(vertex_out.half1(), vertex_in.half1(), vertex_in.half1(), T);
        compute_components_through_FDTs<Q, 'p'>(vertex_out.half1(), vertex_in.half1(), vertex_in.half1(), T);
        compute_components_through_FDTs<Q, 't'>(vertex_out.half1(), vertex_in.half1(), vertex_in.half1(), T);
    }
    vertex_in.set_initializedInterpol(false);
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), getFlatSize(), my_defs::K1::keldysh, my_defs::K2::keldysh, my_defs::K3::keldysh, MAX_DIAG_CLASS, my_defs::K2::nu, my_defs::K3::nu, my_defs::K3::nup, my_defs::K1::omega, my_defs::K2::omega, my_defs::K3::omega, and ZERO_T.