SIAM-Keldysh-mfRG: causality_FDT_checks.c++ File Reference
causality_FDT_checks.c++ File Reference
#include "causality_FDT_checks.hpp"
Functions
void compare_flow_with_FDTs (const std::string filename, bool write_flag)
Function Documentation
compare_flow_with_FDTs()
void compare_flow_with_FDTs (const std::string filename, bool write_flag)
Definition at line 3 of file causality_FDT_checks.c++.
{
    rvec Lambdas = read_Lambdas_from_hdf(filename);
    //const int nLambda = Lambdas.size();
    int Lambda_it_max = -1;
    check_convergence_hdf(filename, Lambda_it_max);
    for (unsigned int i = 0; i < Lambda_it_max; i++) {
        State<state_datatype>  state_in = read_state_from_hdf(filename, i); // read state
        compare_with_FDTs(state_in, i, filename, write_flag, Lambda_it_max);
    }
}
References check_convergence_hdf(), compare_with_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), read_Lambdas_from_hdf(), and read_state_from_hdf().