SIAM-Keldysh-mfRG: FrequencyGrid< hybridGrid > Class Reference
FrequencyGrid< hybridGrid > Class Reference
#include <frequency_grid.hpp>
Public Member Functions
void guess_essential_parameters (double Lambda, const fRG_config &config)
guess essential parameters from value of Lambda
void derive_auxiliary_parameters ()
freqType frequency_from_t (freqType t) const
grid functions:
freqType t_from_frequency (freqType w) const
FrequencyGrid (const char type_in, const unsigned int diag_class_in, const double Lambda, const fRG_config &config, const bool purely_positive=false)
constructor:
freqType get_frequency (const int index) const
getter functions:
freqType get_auxiliary_gridpoint (const int index) const
const vec< freqType > & get_all_frequencies () const
const vec< freqType > & get_all_auxiliary_gridpoints () const
freqType get_spacing_auxiliary_gridpoints () const
char get_type () const
char get_diag_class () const
void set_essential_parameters (freqType wmax_in, std::array< freqType, 2 > new_pos_section_boundaries)
setter functions:
void set_w_upper (freqType wmax)
void initialize_grid ()
void update_pos_section_boundaries (std::array< freqType, 2 > new_pos_section_boundaries)
int get_grid_index (freqType frequency) const
core grid functionality (has to be super efficient)
int get_grid_index (freqType &t, freqType frequency) const
Public Attributes
int number_of_gridpoints
essential grid parameters:
freqType w_upper
freqType w_lower
freqType w_center = 0
std::array< freqType, 2 > pos_section_boundaries
char type
grid identifier:
int diag_class
bool purely_positive
freqType t_upper
auxiliary grid parameters:
freqType t_lower
std::array< double, 2 > aux_pos_section_boundaries
freqType spacing_auxiliary_gridpoint =1.
freqType recip_curvature_quad
freqType recip_slope_lin
freqType factor_rat
freqType rescale_rat
vec< freqType > all_frequencies
list of all frequencies:
vec< freqType > auxiliary_grid
Friends
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type >
class DataContainer
Detailed Description
Definition at line 193 of file frequency_grid.hpp.
Constructor & Destructor Documentation
FrequencyGrid()
FrequencyGrid< hybridGrid >::FrequencyGrid (const char type_in, const unsigned int diag_class_in, const double Lambda, const fRG_config & config, const bool purely_positive = false) inline
constructor:
Definition at line 237 of file frequency_grid.hpp.
                                                                                                                                                         : type(type_in), diag_class(diag_class_in), purely_positive(purely_positive) {
#ifndef DENSEGRID
        assert(KELDYSH || ZERO_T);  // for Matsubara T>0 only allow dense grid
#endif
        guess_essential_parameters(Lambda, config);
        initialize_grid();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, and ZERO_T.
Member Function Documentation
derive_auxiliary_parameters()
void FrequencyGrid< hybridGrid >::derive_auxiliary_parameters ()
Definition at line 405 of file frequency_grid.c++.
{
#if HYBRID_GRID_OPTION==0
    const double temp = (pos_section_boundaries[0] + 2.*pos_section_boundaries[1]);
    const double temp_quad = temp * w_upper - pos_section_boundaries[1]*pos_section_boundaries[1];
    aux_pos_section_boundaries[0] = (2.*t_upper*pos_section_boundaries[0]*w_upper)                              / temp_quad;
    aux_pos_section_boundaries[1] = (t_upper*(pos_section_boundaries[0] + pos_section_boundaries[1]) * w_upper) / temp_quad;
    recip_curvature_quad = (4.*t_upper*t_upper*pos_section_boundaries[0]*w_upper*w_upper) / (temp_quad*temp_quad );
    recip_slope_lin = t_upper*w_upper / (temp_quad);
    factor_rat = pos_section_boundaries[1]*pos_section_boundaries[1] / (temp);
    rescale_rat = (t_upper * w_upper * temp) / temp_quad;
#else
    const double log_wmax_w2 = log(w_upper / pos_section_boundaries[1]);
    const double factor = (pos_section_boundaries[1] - pos_section_boundaries[0]) / (1 - 2 * pos_section_boundaries[0] / (pos_section_boundaries[0] + pos_section_boundaries[1])) / pos_section_boundaries[1];
    //aux_pos_section_boundaries[1] = t_upper / (1 + log(w_upper/pos_section_boundaries[1]) * (1 - 2. * pos_section_boundaries[0] / (pos_section_boundaries[0] + pos_section_boundaries[1]) / (pos_section_boundaries[1] - pos_section_boundaries[0])));
    aux_pos_section_boundaries[1] = t_upper / (log_wmax_w2 / factor + 1);
    aux_pos_section_boundaries[0] = 2. * pos_section_boundaries[0] * aux_pos_section_boundaries[1] / (pos_section_boundaries[0] + pos_section_boundaries[1]);
    recip_slope_lin = (aux_pos_section_boundaries[1] - aux_pos_section_boundaries[0]) / (pos_section_boundaries[1] - pos_section_boundaries[0]);
    recip_curvature_quad = aux_pos_section_boundaries[0]*aux_pos_section_boundaries[0] / pos_section_boundaries[0];
#endif
    spacing_auxiliary_gridpoint = (t_upper - t_lower) / ((double)number_of_gridpoints - 1.);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and log().
frequency_from_t()
freqType FrequencyGrid< hybridGrid >::frequency_from_t (freqType t) const
grid functions:
Definition at line 495 of file frequency_grid.c++.
{
    const double t_abs = std::abs(t);
    if (t_abs < aux_pos_section_boundaries[0]) {
        // quaddratic part
        const double result = t_abs*t_abs / recip_curvature_quad * sgn(t);
        assert(isfinite(result));
        return result;
    }
    else if (t_abs < aux_pos_section_boundaries[1]) {
        // linear part
        const double result = (pos_section_boundaries[0] + (t_abs - aux_pos_section_boundaries[0]) / recip_slope_lin)* sgn(t);
        assert(isfinite(result));
        return result;
    }
    else {
#if HYBRID_GRID_OPTION==0
        // rational part
        const double result = factor_rat / (1. - t_abs / rescale_rat) * sgn(t);
        assert(isfinite(result));
        return result;
#else
        // exponential part
        const double result = (pos_section_boundaries[1] * exp((t_abs - aux_pos_section_boundaries[1]) / (recip_slope_lin * pos_section_boundaries[1]))) * sgn(t);
        assert(isfinite(result));
        return result;
#endif
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sgn().
get_all_auxiliary_gridpoints()
const vec< freqType > & FrequencyGrid< hybridGrid >::get_all_auxiliary_gridpoints () const inline
Definition at line 249 of file frequency_grid.hpp.
{return auxiliary_grid;};
get_all_frequencies()
const vec< freqType > & FrequencyGrid< hybridGrid >::get_all_frequencies () const inline
Definition at line 248 of file frequency_grid.hpp.
{return all_frequencies;};
get_auxiliary_gridpoint()
freqType FrequencyGrid< hybridGrid >::get_auxiliary_gridpoint (const int index) const inline
Definition at line 247 of file frequency_grid.hpp.
{assert(index>=0); assert(index<number_of_gridpoints); return auxiliary_grid[index];};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_diag_class()
char FrequencyGrid< hybridGrid >::get_diag_class () const inline
Definition at line 252 of file frequency_grid.hpp.
{return diag_class;};
get_frequency()
freqType FrequencyGrid< hybridGrid >::get_frequency (const int index) const inline
getter functions:
Definition at line 246 of file frequency_grid.hpp.
{assert(index>=0); return all_frequencies[index];};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_grid_index() [1/2]
int FrequencyGrid< hybridGrid >::get_grid_index (freqType & t, freqType frequency) const
Definition at line 593 of file frequency_grid.c++.
{
    t = t_from_frequency(frequency);
#ifdef DENSEGRID
    auto index = ((int) ((t - t_lower) / spacing_auxiliary_gridpoint + 0.1 )) ;
#else
    assert(std::abs(spacing_auxiliary_gridpoint - 1.) < 1e-10); // By making sure that spacing_auxiliary_gridpoint = 1, there is no need to divide through spacing_auxiliary_gridpoint
    int index = int((t - t_lower) + 1e-12);
    index = std::max(0, index);
    index = std::min(number_of_gridpoints - 2, index);
#endif
    assert(auxiliary_grid[index] <= t + inter_tol);
    assert(auxiliary_grid[index+1] >= t - inter_tol or index == number_of_gridpoints-2);
    return index;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and inter_tol.
get_grid_index() [2/2]
int FrequencyGrid< hybridGrid >::get_grid_index (freqType frequency) const
core grid functionality (has to be super efficient)
Do I need this? The next function basically does the same
Definition at line 575 of file frequency_grid.c++.
{
    const double t = t_from_frequency(frequency);
#ifdef DENSEGRID
    auto index = ((int) ((t - t_lower) / spacing_auxiliary_gridpoint + 0.1 )) ;
#else
    assert(std::abs(spacing_auxiliary_gridpoint - 1.) < 1e-10); // By making sure that spacing_auxiliary_gridpoint = 1, there is no need to divide through spacing_auxiliary_gridpoint
    int index = int((t - t_lower) + 1e-12);
    index = std::max(0, index);
    index = std::min(number_of_gridpoints - 2, index);
#endif
    //assert(all_frequencies[index] <= frequency + (std::abs(frequency)+1)*1e-12);
    //assert(all_frequencies[index+1] >= frequency);
    assert(auxiliary_grid[index] <= t+inter_tol);
    assert(auxiliary_grid[index+1] >= t-inter_tol or index == number_of_gridpoints-2);
    return index;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and inter_tol.
get_spacing_auxiliary_gridpoints()
freqType FrequencyGrid< hybridGrid >::get_spacing_auxiliary_gridpoints () const inline
Definition at line 250 of file frequency_grid.hpp.
{return spacing_auxiliary_gridpoint;}
get_type()
char FrequencyGrid< hybridGrid >::get_type () const inline
Definition at line 251 of file frequency_grid.hpp.
{return type;};
guess_essential_parameters()
void FrequencyGrid< hybridGrid >::guess_essential_parameters (double Lambda, const fRG_config & config)
guess essential parameters from value of Lambda
Definition at line 427 of file frequency_grid.c++.
{
    const double Delta = (config.Gamma + Lambda) * 0.5;
    switch (diag_class) {
        case 1:
            if (type == 'b') {
                number_of_gridpoints = nBOS;
                pos_section_boundaries[0] = 20.*Delta;
                pos_section_boundaries[1] = 30.*Delta;
                w_upper = 5000.*15.*Delta;
            }
            else {
                assert(type == 'f');
                number_of_gridpoints = nFER;
                pos_section_boundaries[0] = 25.;
                pos_section_boundaries[1] = 27.*Delta;
                w_upper = 40.*15.*Delta;
            }
            break;
        case 2:
            if (type == 'b') {
                number_of_gridpoints = nBOS2;
                pos_section_boundaries[0] = 6.*Delta;
                pos_section_boundaries[1] = 20.*Delta;
                w_upper = 80.*15.*Delta;
            }
            else {
                assert(type == 'f');
                number_of_gridpoints = nFER2;
                pos_section_boundaries[0] = 3.*Delta;
                pos_section_boundaries[1] = 10.*Delta;
                w_upper = 40.*15.*Delta;
            }
            break;
        case 3:
            if (type == 'b') {
                number_of_gridpoints = nBOS3;
                pos_section_boundaries[0] = Delta;
                pos_section_boundaries[1] = 3.*Delta;
                w_upper = 30.*15.*Delta;
            }
            else {
                assert(type == 'f');
                number_of_gridpoints = nFER3;
                pos_section_boundaries[0] = Delta;
                pos_section_boundaries[1] = 3.*Delta;
                w_upper = 15*15.*Delta;
            }
            break;
        default:
            break;
    }
    t_upper = ((double) number_of_gridpoints - 1) * (purely_positive ? 1. : 0.5);
    if (purely_positive) {
        w_lower = 0;
        t_lower = 0;
    }
    else {
        w_lower = -w_upper;
        t_lower =-((double) number_of_gridpoints - 1) * 0.5;
    }
    all_frequencies = vec<freqType>(number_of_gridpoints);
    auxiliary_grid = vec<freqType>(number_of_gridpoints);
    initialize_grid();
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::Gamma, nBOS, nBOS2, nBOS3, nFER, nFER2, and nFER3.
initialize_grid()
void FrequencyGrid< hybridGrid >::initialize_grid ()
Definition at line 554 of file frequency_grid.c++.
{
    derive_auxiliary_parameters();
    //auxiliary_grid[0] = t_lower; auxiliary_grid[number_of_gridpoints-1] = t_upper;
    //all_frequencies[0] = -std::numeric_limits<double>::infinity(); all_frequencies[number_of_gridpoints-1] = std::numeric_limits<double>::infinity();
    for (int i = 0; i < number_of_gridpoints; i++) {
        const double t = t_lower + spacing_auxiliary_gridpoint * (double)i;
        auxiliary_grid[i] = t;
        all_frequencies[i] = frequency_from_t(t);
        assert(std::isfinite(all_frequencies[i]));
    }
    if (purely_positive) {
        all_frequencies[0] = 0.;
        auxiliary_grid[0] = 0.;
    }
    if (number_of_gridpoints % 2 == 1 and not purely_positive) {
        all_frequencies[(int) number_of_gridpoints / 2] = 0.;  // make sure that the center of the grid is exactly zero (and not ~10^{-30})
        auxiliary_grid[(int) number_of_gridpoints / 2] = 0.;
    }
    if (!KELDYSH && !ZERO_T) assert (is_doubleOccurencies(all_frequencies) == 0);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), is_doubleOccurencies(), KELDYSH, and ZERO_T.
set_essential_parameters()
void FrequencyGrid< hybridGrid >::set_essential_parameters (freqType wmax_in, std::array< freqType, 2 > new_pos_section_boundaries) inline
setter functions:
Definition at line 255 of file frequency_grid.hpp.
{
        w_upper = wmax_in;
        w_lower =-w_upper;
        pos_section_boundaries = std::move(new_pos_section_boundaries);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
set_w_upper()
void FrequencyGrid< hybridGrid >::set_w_upper (freqType wmax) inline
Definition at line 260 of file frequency_grid.hpp.
{
        set_essential_parameters(wmax, pos_section_boundaries);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
t_from_frequency()
freqType FrequencyGrid< hybridGrid >::t_from_frequency (freqType w) const
Definition at line 525 of file frequency_grid.c++.
{
    const double w_abs = std::abs(w);
    if (w_abs < pos_section_boundaries[0]) {
        // quadratic part
        const double result = sqrt(w_abs * recip_curvature_quad) * sgn(w);
        assert(isfinite(result));
        return result;
    }
    else if (w_abs < pos_section_boundaries[1]) {
        // linear part
        const double result = ((w_abs - pos_section_boundaries[0]) * recip_slope_lin + aux_pos_section_boundaries[0]) * sgn(w);
        assert(isfinite(result));
        return result;
    }
    else {
#if HYBRID_GRID_OPTION==0
        // rational part
        const double result = (1. - factor_rat / w_abs) * rescale_rat * sgn(w);
        assert(isfinite(result));
        return result;
#else
        // exponential part
        const double result = sgn(w) * (aux_pos_section_boundaries[1] + log(w_abs / pos_section_boundaries[1]) * pos_section_boundaries[1] * recip_slope_lin);
        assert(isfinite(result));
        return result;
#endif
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), log(), and sgn().
update_pos_section_boundaries()
void FrequencyGrid< hybridGrid >::update_pos_section_boundaries (std::array< freqType, 2 > new_pos_section_boundaries) inline
Definition at line 264 of file frequency_grid.hpp.
{
        //pos_section_boundaries = std::move(new_pos_section_boundaries);
        pos_section_boundaries[0] = std::min(w_upper, new_pos_section_boundaries[0]);
        pos_section_boundaries[1] = std::max(pos_section_boundaries[0], new_pos_section_boundaries[1]);
        initialize_grid();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Friends And Related Symbol Documentation
DataContainer
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > friend class DataContainer friend
Definition at line 195 of file frequency_grid.hpp.
Member Data Documentation
all_frequencies
vec<freqType> FrequencyGrid< hybridGrid >::all_frequencies
list of all frequencies:
Definition at line 227 of file frequency_grid.hpp.
aux_pos_section_boundaries
std::array<double,2> FrequencyGrid< hybridGrid >::aux_pos_section_boundaries
Definition at line 218 of file frequency_grid.hpp.
auxiliary_grid
vec<freqType> FrequencyGrid< hybridGrid >::auxiliary_grid
Definition at line 228 of file frequency_grid.hpp.
diag_class
int FrequencyGrid< hybridGrid >::diag_class
Definition at line 212 of file frequency_grid.hpp.
factor_rat
freqType FrequencyGrid< hybridGrid >::factor_rat
Definition at line 222 of file frequency_grid.hpp.
number_of_gridpoints
int FrequencyGrid< hybridGrid >::number_of_gridpoints
essential grid parameters:
Definition at line 199 of file frequency_grid.hpp.
pos_section_boundaries
std::array<freqType,2> FrequencyGrid< hybridGrid >::pos_section_boundaries
Definition at line 203 of file frequency_grid.hpp.
purely_positive
bool FrequencyGrid< hybridGrid >::purely_positive
Definition at line 213 of file frequency_grid.hpp.
recip_curvature_quad
freqType FrequencyGrid< hybridGrid >::recip_curvature_quad
Definition at line 220 of file frequency_grid.hpp.
recip_slope_lin
freqType FrequencyGrid< hybridGrid >::recip_slope_lin
Definition at line 221 of file frequency_grid.hpp.
rescale_rat
freqType FrequencyGrid< hybridGrid >::rescale_rat
Definition at line 223 of file frequency_grid.hpp.
spacing_auxiliary_gridpoint
freqType FrequencyGrid< hybridGrid >::spacing_auxiliary_gridpoint =1.
Definition at line 219 of file frequency_grid.hpp.
t_lower
freqType FrequencyGrid< hybridGrid >::t_lower
Definition at line 217 of file frequency_grid.hpp.
t_upper
freqType FrequencyGrid< hybridGrid >::t_upper
auxiliary grid parameters:
Definition at line 216 of file frequency_grid.hpp.
type
char FrequencyGrid< hybridGrid >::type
grid identifier:
Definition at line 211 of file frequency_grid.hpp.
w_center
freqType FrequencyGrid< hybridGrid >::w_center = 0
Definition at line 202 of file frequency_grid.hpp.
w_lower
freqType FrequencyGrid< hybridGrid >::w_lower
Definition at line 201 of file frequency_grid.hpp.
w_upper
freqType FrequencyGrid< hybridGrid >::w_upper
Definition at line 200 of file frequency_grid.hpp.
The documentation for this class was generated from the following files:
frequency_grid.hpp
frequency_grid.c++