SIAM-Keldysh-mfRG: hdf5_routines.hpp File Reference
hdf5_routines.hpp File Reference
#include <stdexcept>
#include <cmath>
#include <vector>
#include "../parameters/master_parameters.hpp"
#include "util.hpp"
#include "../data_structures.hpp"
#include "../grids/frequency_grid.hpp"
#include "H5Cpp.h"
#include "../correlation_functions/state.hpp"
#include "../multidimensional/multiarray.hpp"
#include "../symmetries/Keldysh_symmetries.hpp"
#include "mpi_setup.hpp"
Classes
struct h5_comp
— Definitions of necessary data types — ///
Namespaces
namespace hdf5_impl
Typedefs
typedef struct h5_comp h5_comp
— Definitions of necessary data types — ///
Functions
const H5std_string DATASET_irred ("irred")
const H5std_string DATASET_K1_a ("K1_a")
const H5std_string DATASET_K1_p ("K1_p")
const H5std_string DATASET_K1_t ("K1_t")
const H5std_string DATASET_K1_a_postproc ("K1_a_postproc")
const H5std_string DATASET_K1_p_postproc ("K1_p_postproc")
const H5std_string DATASET_K1_t_postproc ("K1_t_postproc")
const H5std_string DATASET_K2_a ("K2_a")
const H5std_string DATASET_K2_p ("K2_p")
const H5std_string DATASET_K2_t ("K2_t")
const H5std_string DATASET_K2b_a ("K2b_a")
const H5std_string DATASET_K2b_p ("K2b_p")
const H5std_string DATASET_K2b_t ("K2b_t")
const H5std_string DATASET_K3_a ("K3_a")
const H5std_string DATASET_K3_p ("K3_p")
const H5std_string DATASET_K3_t ("K3_t")
const H5std_string SELF_LIST ("selflist")
const H5std_string HARTREE ("hartree")
const H5std_string LAMBDA_LIST ("lambdas")
const H5std_string BFREQS_LISTa ("bfreqs_a")
const H5std_string BFREQS_LISTp ("bfreqs_p")
const H5std_string BFREQS_LISTt ("bfreqs_t")
const H5std_string BFREQS2_LISTa ("bfreqs2_a")
const H5std_string BFREQS2_LISTp ("bfreqs2_p")
const H5std_string BFREQS2_LISTt ("bfreqs2_t")
const H5std_string BFREQS2b_LISTa ("bfreqs2b_a")
const H5std_string BFREQS2b_LISTp ("bfreqs2b_p")
const H5std_string BFREQS2b_LISTt ("bfreqs2b_t")
const H5std_string BFREQS3_LISTa ("bfreqs3_a")
const H5std_string BFREQS3_LISTp ("bfreqs3_p")
const H5std_string BFREQS3_LISTt ("bfreqs3_t")
const H5std_string FFREQS_LIST ("ffreqs")
const H5std_string FFREQS2_LISTa ("ffreqs2_a")
const H5std_string FFREQS2_LISTp ("ffreqs2_p")
const H5std_string FFREQS2_LISTt ("ffreqs2_t")
const H5std_string FFREQS2b_LISTa ("ffreqs2b_a")
const H5std_string FFREQS2b_LISTp ("ffreqs2b_p")
const H5std_string FFREQS2b_LISTt ("ffreqs2b_t")
const H5std_string FFREQS3_LISTa ("ffreqs3_a")
const H5std_string FFREQS3_LISTp ("ffreqs3_p")
const H5std_string FFREQS3_LISTt ("ffreqs3_t")
const H5std_string FFREQS3_LISTa2 ("ffreqs3_a2")
const H5std_string FFREQS3_LISTp2 ("ffreqs3_p2")
const H5std_string FFREQS3_LISTt2 ("ffreqs3_t2")
const H5std_string FREQ_PARAMS ("freq_params")
const H5std_string PARAM_LIST ("parameters")
const H5std_string IS_CONVERGED ("is_converged")
const H5std_string W_CENTER ("w_center")
const H5std_string RE ("re")
const H5std_string IM ("im")
H5::CompType def_mtype_comp ()
H5::DSetCreatPropList def_proplist_comp ()
H5::H5File create_hdf_file (const std::string &filename)
H5::H5File open_hdf_file_readOnly (const std::string &filename)
H5::H5File open_hdf_file_readWrite (const std::string &filename)
void close_hdf_file (H5::H5File &file)
template<typename Q , typename H5Object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, char >, bool > = true>
H5::DataSet hdf5_impl::create_Dataset (H5Object &group, const H5std_string &dataset_name, H5::DataSpace &file_space)
Create new dataset of suitable datatype.
template<typename H5Object >
H5::DataSet hdf5_impl::open_Dataset (H5Object &group, const H5std_string &dataset_name)
Open existing dataset of suitable datatype.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, double >||std::is_same_v< typename container::value_type, comp >||std::is_same_v< typename container::value_type, int >||std::is_same_v< typename container::value_type, char >, bool > = true>
void hdf5_impl::write_data_to_Dataset (const container data, H5::DataSet &dataset)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, double >||std::is_same_v< typename container::value_type, comp >||std::is_same_v< typename container::value_type, int >||std::is_same_v< typename container::value_type, char >, bool > = true>
void hdf5_impl::write_data_to_Dataset (const container data, H5::DataSet &dataset, H5::DataSpace &mem_space, H5::DataSpace &file_space)
template<typename Q , std::size_t depth, typename H5object , typename container , typename dimensions_type >
void hdf5_impl::write_to_hdf_LambdaLayer_impl (H5object &group, const H5std_string &dataset_name, const container &data, const dimensions_type &length, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
template<typename Q , std::size_t depth, typename H5object >
std::vector< Q > hdf5_impl::read_from_hdf_impl (const H5object &group, const H5std_string &dataset_name, std::array< std::size_t, depth > &dims_result)
template<typename Q , std::size_t depth, typename H5object >
std::vector< Q > hdf5_impl::read_from_hdf_LambdaLayer_impl (const H5object &group, const H5std_string &dataset_name, std::array< std::size_t, depth > &dims_result, const int Lambda_it)
template<typename Q , typename H5object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, bool >||std::is_same_v< Q, char >, bool > = true>
void write_to_hdf (H5object &group, const H5std_string &dataset_name, const Q &data, const bool data_set_exists)
Write scalar to HDF group/file as Attribute.
template<typename Q , typename H5object >
void write_to_hdf (H5object &group, const H5std_string &dataset_name, const std::vector< Q > &data, const bool data_set_exists)
Write vector to HDF group/file.
template<typename Q , std::size_t depth, typename H5object >
void write_to_hdf (H5object &group, const H5std_string &dataset_name, const multidimensional::multiarray< Q, depth > &data, const bool data_set_exists)
Write multiarray to HDF group/file.
template<typename Q , typename H5object , int nrows, int ncols>
void write_to_hdf (H5object &group, const H5std_string &dataset_name, const Eigen::Matrix< Q, nrows, ncols > &data, const bool data_set_exists)
Write Eigen::Matrix to HDF group/file.
template<typename Q , typename H5object >
void write_to_hdf_LambdaLayer (H5object &group, const H5std_string &dataset_name, const std::vector< Q > &data, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
Write vector to Lambda layer of HDF group/file.
template<typename Q , std::size_t depth, typename H5object >
void write_to_hdf_LambdaLayer (H5object &group, const H5std_string &dataset_name, const multidimensional::multiarray< Q, depth > &data, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
Write multiarray to Lambda layer of HDF group/file.
template<typename Q , typename H5object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, bool >||std::is_same_v< Q, char >, bool > = true>
void read_from_hdf (H5object &group, const H5std_string &dataset_name, Q &result)
Read scalar from HDF group/file as Attribute.
template<typename Q , std::size_t depth, typename H5object >
void read_from_hdf (const H5object &group, const H5std_string &dataset_name, multidimensional::multiarray< Q, depth > &result)
Read multiarray from HDF group/file.
template<typename Q , typename H5object >
void read_from_hdf (const H5object &group, const H5std_string &dataset_name, std::vector< Q > &result)
Read vector from HDF group/file.
template<typename Q , std::size_t depth, typename H5object >
void read_from_hdf_LambdaLayer (const H5object &group, const H5std_string &dataset_name, multidimensional::multiarray< Q, depth > &result, const int Lambda_it)
Read multiarray from Lambda layer of HDF group/file.
template<typename Q , typename H5object >
void read_from_hdf_LambdaLayer (const H5object &group, const H5std_string &dataset_name, std::vector< Q > &result, const int Lambda_it)
Read vector from Lambda layer of HDF group/file.
template<typename gridType >
void hdf5_impl::write_freqparams_to_hdf_LambdaLayer (H5::Group &group, const gridType &freqgrid, const int Lambda_it, const int numberLambdaLayers, const bool file_exists, const bool verbose)
template<typename gridType >
void hdf5_impl::init_freqgrid_from_hdf_LambdaLayer (H5::Group &group, gridType &freqgrid, const int Lambda_it, const double Lambda)
template<typename Q , bool diff>
void hdf5_impl::write_state_to_hdf_LambdaLayer (const H5std_string &filename, const State< Q, diff > &state, const int Lambda_it, const int numberLambdaLayers, const std::string write_mode, const bool is_converged=false, const bool verbose=true)
template<typename Q , bool diff>
void write_state_to_hdf (const H5std_string FILE_NAME, double Lambda_i, const int Lambda_size, const State< Q, diff > &state_in, const bool verbose=true, const bool is_converged=false)
Create file with fixed number of Lambda layers and save state to first Lambda layer.
template<typename Q , bool diff>
void add_state_to_hdf (const H5std_string FILE_NAME, int Lambda_it, const State< Q, diff > &state_in, const bool is_converged=false, const bool verbose=true)
Open file and save state to a specified Lambda layer.
State< state_datatype, false > read_state_from_hdf (const H5std_string &filename, int Lambda_it)
Read state from specified Lambda layer of hdf file.
bool check_convergence_hdf (const H5std_string &filename, int &Lambda_it)
rvec read_Lambdas_from_hdf (H5std_string FILE_NAME)
— Functions for reading data from file — ///
fRG_config read_config_from_hdf (H5std_string FILE_NAME)
bool test_read_write_data_hdf (bool verbose)
— Test function — ///
template<typename Q >
bool test_read_write_state_hdf (bool verbose)
Variables
const int RANK_K1 = 2
TODO: Save frequency grids and frequency parameters for each channel individually.
const int RANK_K2 = 2
const int RANK_K3 = 2
const int RANK_irreducible = 2
const int RANK_self = 2
const int RANK_freqs = 2
const int N_freq_params = 64
Typedef Documentation
h5_comp
typedef struct h5_comp h5_comp
— Definitions of necessary data types — ///
Function Documentation
add_state_to_hdf()
template<typename Q , bool diff> void add_state_to_hdf (const H5std_string FILE_NAME, int Lambda_it, const State< Q, diff > & state_in, const bool is_converged = false, const bool verbose = true)
Open file and save state to a specified Lambda layer.
Definition at line 852 of file hdf5_routines.hpp.
{
#ifdef USE_MPI
    if (mpi_world_rank() == 0)  // only the process with ID 0 writes into file to avoid collisions
#endif
    {
        multidimensional::multiarray<double,2> Lambdas;
        H5::H5File file_out = open_hdf_file_readWrite(FILE_NAME);
        read_from_hdf<double>(file_out, LAMBDA_LIST, Lambdas);
        file_out.close();
        const std::size_t Lambda_size = Lambdas.size();
        if (Lambda_it < Lambda_size) {
            hdf5_impl::write_state_to_hdf_LambdaLayer(FILE_NAME, state_in, Lambda_it, Lambda_size, "rw", is_converged);
            if (verbose) {
                utils::print("Successfully saved in hdf5 file: ", FILE_NAME);
                utils::print_add(" in Lambda-layer ", Lambda_it, false);
                utils::print_add("", true);
            }
        } else {
            utils::print("\t\t  ERROR: Cannot write to file ", FILE_NAME, " since Lambda layer", Lambda_it,
                  " is out of range.", "\n");
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), LAMBDA_LIST(), mpi_world_rank(), open_hdf_file_readWrite(), utils::print(), utils::print_add(), and hdf5_impl::write_state_to_hdf_LambdaLayer().
Referenced by compare_with_FDTs(), compare_with_FDTs(), compute_BSE(), parquet_checks(), parquet_solver(), postRKstep_stuff(), old_ode_solvers::RK4_step(), and test_read_write_state_hdf().
BFREQS2_LISTa()
const H5std_string BFREQS2_LISTa ("bfreqs2_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS2_LISTp()
const H5std_string BFREQS2_LISTp ("bfreqs2_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS2_LISTt()
const H5std_string BFREQS2_LISTt ("bfreqs2_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS2b_LISTa()
const H5std_string BFREQS2b_LISTa ("bfreqs2b_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS2b_LISTp()
const H5std_string BFREQS2b_LISTp ("bfreqs2b_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS2b_LISTt()
const H5std_string BFREQS2b_LISTt ("bfreqs2b_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS3_LISTa()
const H5std_string BFREQS3_LISTa ("bfreqs3_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS3_LISTp()
const H5std_string BFREQS3_LISTp ("bfreqs3_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS3_LISTt()
const H5std_string BFREQS3_LISTt ("bfreqs3_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS_LISTa()
const H5std_string BFREQS_LISTa ("bfreqs_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS_LISTp()
const H5std_string BFREQS_LISTp ("bfreqs_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
BFREQS_LISTt()
const H5std_string BFREQS_LISTt ("bfreqs_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
check_convergence_hdf()
bool check_convergence_hdf (const H5std_string & filename, int & Lambda_it)
Definition at line 194 of file hdf5_routines.c++.
{
    H5::H5File file_out;
    H5::Exception::dontPrint();
    bool is_converged;
    try {
        file_out = H5::H5File(filename, H5F_ACC_RDONLY);
        H5::Group group_params(file_out.openGroup(PARAM_LIST));
        read_from_hdf(group_params, IS_CONVERGED, is_converged);
        read_from_hdf(group_params, "last_Lambda_it", Lambda_it);
    } catch(const H5::FileIException&) {
        is_converged = false;
        Lambda_it = -1;
    }
    file_out.close();
    return is_converged;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), IS_CONVERGED(), PARAM_LIST(), and read_from_hdf().
Referenced by compare_flow_with_FDTs(), and parquet_solver().
close_hdf_file()
void close_hdf_file (H5::H5File & file)
Definition at line 32 of file hdf5_routines.c++.
{
    if (mpi_world_rank() == 0) {
        file.close();
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
Referenced by read_Lambdas_from_hdf().
create_hdf_file()
H5::H5File create_hdf_file (const std::string & filename)
Definition at line 6 of file hdf5_routines.c++.
{
    if (mpi_world_rank() == 0) {
        H5::H5File outfile(filename, H5F_ACC_TRUNC);
        return outfile;
    }
    else {
        H5::H5File file;
        return file;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
Referenced by test_read_write_data_hdf().
DATASET_irred()
const H5std_string DATASET_irred ("irred")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K1_a()
const H5std_string DATASET_K1_a ("K1_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K1_a_postproc()
const H5std_string DATASET_K1_a_postproc ("K1_a_postproc")
DATASET_K1_p()
const H5std_string DATASET_K1_p ("K1_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K1_p_postproc()
const H5std_string DATASET_K1_p_postproc ("K1_p_postproc")
DATASET_K1_t()
const H5std_string DATASET_K1_t ("K1_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K1_t_postproc()
const H5std_string DATASET_K1_t_postproc ("K1_t_postproc")
DATASET_K2_a()
const H5std_string DATASET_K2_a ("K2_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K2_p()
const H5std_string DATASET_K2_p ("K2_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K2_t()
const H5std_string DATASET_K2_t ("K2_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K2b_a()
const H5std_string DATASET_K2b_a ("K2b_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K2b_p()
const H5std_string DATASET_K2b_p ("K2b_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K2b_t()
const H5std_string DATASET_K2b_t ("K2b_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K3_a()
const H5std_string DATASET_K3_a ("K3_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K3_p()
const H5std_string DATASET_K3_p ("K3_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
DATASET_K3_t()
const H5std_string DATASET_K3_t ("K3_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
def_mtype_comp()
H5::CompType def_mtype_comp ()
Definition at line 39 of file hdf5_routines.c++.
{
    H5::CompType mtype(sizeof(h5_comp));
    mtype.insertMember(RE, HOFFSET(h5_comp, re), H5::PredType::NATIVE_DOUBLE);
    mtype.insertMember(IM, HOFFSET(h5_comp, im), H5::PredType::NATIVE_DOUBLE);
    return mtype;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), IM(), and RE().
Referenced by hdf5_impl::create_Dataset(), def_proplist_comp(), hdf5_impl::read_from_hdf_impl(), hdf5_impl::read_from_hdf_LambdaLayer_impl(), hdf5_impl::write_data_to_Dataset(), hdf5_impl::write_data_to_Dataset(), and write_to_hdf().
def_proplist_comp()
H5::DSetCreatPropList def_proplist_comp ()
Definition at line 45 of file hdf5_routines.c++.
{
    h5_comp fillvalue_vert;
    fillvalue_vert.re = 0;
    fillvalue_vert.im = 0;
    H5::DSetCreatPropList plist_vert;
    H5::CompType mtype_comp = def_mtype_comp();
    plist_vert.setFillValue(mtype_comp, &fillvalue_vert);
    return plist_vert;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), def_mtype_comp(), and h5_comp::re.
Referenced by hdf5_impl::create_Dataset().
FFREQS2_LISTa()
const H5std_string FFREQS2_LISTa ("ffreqs2_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS2_LISTp()
const H5std_string FFREQS2_LISTp ("ffreqs2_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS2_LISTt()
const H5std_string FFREQS2_LISTt ("ffreqs2_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS2b_LISTa()
const H5std_string FFREQS2b_LISTa ("ffreqs2b_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS2b_LISTp()
const H5std_string FFREQS2b_LISTp ("ffreqs2b_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS2b_LISTt()
const H5std_string FFREQS2b_LISTt ("ffreqs2b_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS3_LISTa()
const H5std_string FFREQS3_LISTa ("ffreqs3_a")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS3_LISTa2()
const H5std_string FFREQS3_LISTa2 ("ffreqs3_a2")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS3_LISTp()
const H5std_string FFREQS3_LISTp ("ffreqs3_p")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS3_LISTp2()
const H5std_string FFREQS3_LISTp2 ("ffreqs3_p2")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS3_LISTt()
const H5std_string FFREQS3_LISTt ("ffreqs3_t")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS3_LISTt2()
const H5std_string FFREQS3_LISTt2 ("ffreqs3_t2")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FFREQS_LIST()
const H5std_string FFREQS_LIST ("ffreqs")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
FREQ_PARAMS()
const H5std_string FREQ_PARAMS ("freq_params")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
HARTREE()
const H5std_string HARTREE ("hartree")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
IM()
const H5std_string IM ("im")
Referenced by def_mtype_comp().
IS_CONVERGED()
const H5std_string IS_CONVERGED ("is_converged")
Referenced by check_convergence_hdf(), and hdf5_impl::write_state_to_hdf_LambdaLayer().
LAMBDA_LIST()
const H5std_string LAMBDA_LIST ("lambdas")
Referenced by add_state_to_hdf(), ode_solver(), and hdf5_impl::write_state_to_hdf_LambdaLayer().
open_hdf_file_readOnly()
H5::H5File open_hdf_file_readOnly (const std::string & filename)
Definition at line 16 of file hdf5_routines.c++.
{
    // no problem with reading same file from different nodes
    H5::H5File outfile(filename, H5F_ACC_RDONLY);
    return outfile;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by read_Lambdas_from_hdf().
open_hdf_file_readWrite()
H5::H5File open_hdf_file_readWrite (const std::string & filename)
Definition at line 21 of file hdf5_routines.c++.
{
    if (mpi_world_rank() == 0) {
        H5::H5File outfile(filename, H5F_ACC_RDWR);
        return outfile;
    }
    else {
        H5::H5File file;
        return file;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
Referenced by add_state_to_hdf(), parquet_solver(), and mfRG_stats::write_to_hdf().
PARAM_LIST()
const H5std_string PARAM_LIST ("parameters")
Referenced by check_convergence_hdf(), read_config_from_hdf(), and hdf5_impl::write_state_to_hdf_LambdaLayer().
RE()
const H5std_string RE ("re")
Referenced by def_mtype_comp().
read_config_from_hdf()
fRG_config read_config_from_hdf (H5std_string FILE_NAME)
Definition at line 392 of file hdf5_routines.c++.
{
    H5::H5File file_out(FILE_NAME, H5F_ACC_RDONLY);
    fRG_config config;
    int REG_loaded, MAX_DIAG_CLASS_loaded, N_LOOPS_loaded, GRID_loaded;
    double glb_Gamma_loaded, glb_T_loaded, glb_mu_loaded, glb_U_loaded, glb_epsilon_loaded, glb_V_loaded, nODE_loaded;
    H5::Group group_params(file_out.openGroup(PARAM_LIST));
    read_from_hdf(group_params, "REG", REG_loaded);
    read_from_hdf(group_params, "nODE", nODE_loaded);
    read_from_hdf(group_params, "Gamma", glb_Gamma_loaded);
    read_from_hdf(group_params, "MAX_DIAG_CLASS", MAX_DIAG_CLASS_loaded);
    read_from_hdf(group_params, "N_LOOPS", N_LOOPS_loaded);
    read_from_hdf(group_params, "T", glb_T_loaded);
    read_from_hdf(group_params, "mu", glb_mu_loaded);
    read_from_hdf(group_params, "U", glb_U_loaded);
    read_from_hdf(group_params, "epsilon", glb_epsilon_loaded);
    read_from_hdf(group_params, "V", glb_V_loaded);
    // write values in fRG_config
    config.nloops = N_LOOPS_loaded;
    config.U = glb_U_loaded;
    config.Gamma = glb_Gamma_loaded;
    config.T = glb_T_loaded;
    config.epsilon = glb_epsilon_loaded;
    config.nODE_ = nODE_loaded;
    return config;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::epsilon, fRG_config::Gamma, fRG_config::nloops, fRG_config::nODE_, PARAM_LIST(), read_from_hdf(), fRG_config::T, and fRG_config::U.
read_from_hdf() [1/3]
template<typename Q , std::size_t depth, typename H5object > void read_from_hdf (const H5object & group, const H5std_string & dataset_name, multidimensional::multiarray< Q, depth > & result)
Read multiarray from HDF group/file.
Definition at line 499 of file hdf5_routines.hpp.
{
    typename multidimensional::multiarray<Q,depth>::dimensions_type dims_result;
    std::vector<Q> result_vec = hdf5_impl::read_from_hdf_impl<Q,depth,H5object>(group, dataset_name, dims_result);
    result = multidimensional::multiarray<Q,depth>(dims_result, result_vec);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
read_from_hdf() [2/3]
template<typename Q , typename H5object > void read_from_hdf (const H5object & group, const H5std_string & dataset_name, std::vector< Q > & result)
Read vector from HDF group/file.
Definition at line 507 of file hdf5_routines.hpp.
{
    std::array<std::size_t, 1> dims_result;
    result = hdf5_impl::read_from_hdf_impl<Q,1,H5object>(group, dataset_name, dims_result);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
read_from_hdf() [3/3]
template<typename Q , typename H5object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, bool >||std::is_same_v< Q, char >, bool > = true> void read_from_hdf (H5object & group, const H5std_string & dataset_name, Q & result)
Read scalar from HDF group/file as Attribute.
Definition at line 488 of file hdf5_routines.hpp.
{
    H5::DataSpace file_space(H5S_SCALAR);
    H5::Attribute attr = group.openAttribute( dataset_name );
    H5::DataType type = attr.getDataType();
    attr.read(type,&result);
    file_space.close();
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by check_convergence_hdf(), and read_config_from_hdf().
read_from_hdf_LambdaLayer() [1/2]
template<typename Q , std::size_t depth, typename H5object > void read_from_hdf_LambdaLayer (const H5object & group, const H5std_string & dataset_name, multidimensional::multiarray< Q, depth > & result, const int Lambda_it)
Read multiarray from Lambda layer of HDF group/file.
Definition at line 515 of file hdf5_routines.hpp.
{
    typename multidimensional::multiarray<Q,depth>::dimensions_type dims_result;
    std::vector<Q> result_vec = hdf5_impl::read_from_hdf_LambdaLayer_impl<Q,depth,H5object>(group, dataset_name, dims_result, Lambda_it);
    result = multidimensional::multiarray<Q,depth>(dims_result, result_vec);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
read_from_hdf_LambdaLayer() [2/2]
template<typename Q , typename H5object > void read_from_hdf_LambdaLayer (const H5object & group, const H5std_string & dataset_name, std::vector< Q > & result, const int Lambda_it)
Read vector from Lambda layer of HDF group/file.
Definition at line 523 of file hdf5_routines.hpp.
{
    std::array<std::size_t, 1> dims_result;
    result = hdf5_impl::read_from_hdf_LambdaLayer_impl<Q,1,H5object>(group, dataset_name, dims_result, Lambda_it);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
read_Lambdas_from_hdf()
rvec read_Lambdas_from_hdf (H5std_string FILE_NAME)
— Functions for reading data from file — ///
Read Lambdas from an existing file
Parameters
FILE_NAME : File name
Returns
: Lambdas in a vector of doubles
load data into buffer
Definition at line 217 of file hdf5_routines.c++.
{
    // Open the file. Access rights: read-only
    H5::H5File file = open_hdf_file_readOnly(FILE_NAME);
    H5::DataSet lambda_dataset = file.openDataSet("lambdas");
    // Create the data spaces for the data sets in file and for buffer objects
    H5::DataSpace dataSpace_Lambda = lambda_dataset.getSpace();
    //
    //Get the dimension size of each dimension in the dataspace and
    //display them.
    //
    hsize_t dims_out[2];
    dataSpace_Lambda.getSimpleExtentDims( dims_out, NULL);
    //std::cout << "rank " << rank << ", dimensions " <<
    //     (unsigned long)(dims_out[0]) << " x " <<
    //     (unsigned long)(dims_out[1]) << std::endl;
    H5::DataSpace dataSpace_Lambda_buffer(1, dims_out);
    double Lambdas_arr[dims_out[0]];
    lambda_dataset.read(Lambdas_arr, H5::PredType::NATIVE_DOUBLE,
                        dataSpace_Lambda_buffer, dataSpace_Lambda);
    rvec Lambdas (Lambdas_arr, Lambdas_arr + sizeof(Lambdas_arr) / sizeof(double));
    // Terminate
    lambda_dataset.close();
    close_hdf_file(file);
    return Lambdas;
}
References close_hdf_file(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and open_hdf_file_readOnly().
Referenced by compare_flow_with_FDTs(), and parquet_checks().
read_state_from_hdf()
State< state_datatype, false > read_state_from_hdf (const H5std_string & filename, int Lambda_it)
Read state from specified Lambda layer of hdf file.
check whether parameters in HDF file agree with parameters/master_parameters.hpp
Write used parameters for documentation purpose
check whether parameters in HDF file agree with parameters/master_parameters.hpp
Write used parameters for documentation purpose
Definition at line 20 of file hdf5_routines.c++.
{
    H5::H5File file_out = open_hdf_file_readOnly(filename);
    std::vector<double> Lambda;
    read_from_hdf_LambdaLayer<double>(file_out, LAMBDA_LIST, Lambda, Lambda_it);
    fRG_config config = read_config_from_hdf(filename);
    State<state_datatype,false> state(Lambda[0], config);
    std::vector<state_datatype> Sigma_H;
    read_from_hdf_LambdaLayer<state_datatype>(file_out, SELF_LIST, state.selfenergy.Sigma.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, HARTREE, Sigma_H, Lambda_it);
    state.selfenergy.asymp_val_R = Sigma_H[0];
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_irred, state.vertex.irred().bare, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_a, state.vertex.avertex().K1.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_p, state.vertex.pvertex().K1.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_t, state.vertex.tvertex().K1.data, Lambda_it);
#if MAX_DIAG_CLASS>1
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_a, state.vertex.avertex().K2.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_p, state.vertex.pvertex().K2.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_t, state.vertex.tvertex().K2.data, Lambda_it);
#if DEBUG_SYMMETRIES
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_a, state.vertex.avertex().K2b.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_p, state.vertex.pvertex().K2b.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_t, state.vertex.tvertex().K2b.data, Lambda_it);
#endif
#endif
#if MAX_DIAG_CLASS>2
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_a, state.vertex.avertex().K3.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_p, state.vertex.pvertex().K3.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_t, state.vertex.tvertex().K3.data, Lambda_it);
#endif
    H5::Group group_freqparams(file_out.openGroup(FREQ_PARAMS));
    H5::Group group_freqparams_ffreqs (group_freqparams.openGroup(FFREQS_LIST ));
    H5::Group group_freqparams_bfreqsa (group_freqparams.openGroup(BFREQS_LISTa ));
    H5::Group group_freqparams_bfreqsp (group_freqparams.openGroup(BFREQS_LISTp ));
    H5::Group group_freqparams_bfreqst (group_freqparams.openGroup(BFREQS_LISTt ));
    H5::Group group_freqparams_bfreqs2a(group_freqparams.openGroup(BFREQS2_LISTa));
    H5::Group group_freqparams_bfreqs2p(group_freqparams.openGroup(BFREQS2_LISTp));
    H5::Group group_freqparams_bfreqs2t(group_freqparams.openGroup(BFREQS2_LISTt));
    H5::Group group_freqparams_bfreqs2ba(group_freqparams.openGroup(BFREQS2b_LISTa));
    H5::Group group_freqparams_bfreqs2bp(group_freqparams.openGroup(BFREQS2b_LISTp));
    H5::Group group_freqparams_bfreqs2bt(group_freqparams.openGroup(BFREQS2b_LISTt));
    H5::Group group_freqparams_bfreqs3a(group_freqparams.openGroup(BFREQS3_LISTa));
    H5::Group group_freqparams_bfreqs3p(group_freqparams.openGroup(BFREQS3_LISTp));
    H5::Group group_freqparams_bfreqs3t(group_freqparams.openGroup(BFREQS3_LISTt));
    H5::Group group_freqparams_ffreqs2a(group_freqparams.openGroup(FFREQS2_LISTa));
    H5::Group group_freqparams_ffreqs2p(group_freqparams.openGroup(FFREQS2_LISTp));
    H5::Group group_freqparams_ffreqs2t(group_freqparams.openGroup(FFREQS2_LISTt));
    H5::Group group_freqparams_ffreqs2ba(group_freqparams.openGroup(FFREQS2b_LISTa));
    H5::Group group_freqparams_ffreqs2bp(group_freqparams.openGroup(FFREQS2b_LISTp));
    H5::Group group_freqparams_ffreqs2bt(group_freqparams.openGroup(FFREQS2b_LISTt));
    H5::Group group_freqparams_ffreqs3a(group_freqparams.openGroup(FFREQS3_LISTa));
    H5::Group group_freqparams_ffreqs3p(group_freqparams.openGroup(FFREQS3_LISTp));
    H5::Group group_freqparams_ffreqs3t(group_freqparams.openGroup(FFREQS3_LISTt));
    H5::Group group_freqparams_ffreqs3a2(group_freqparams.openGroup(FFREQS3_LISTa2));
    H5::Group group_freqparams_ffreqs3p2(group_freqparams.openGroup(FFREQS3_LISTp2));
    H5::Group group_freqparams_ffreqs3t2(group_freqparams.openGroup(FFREQS3_LISTt2));
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs , state.selfenergy.Sigma.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqsa, state.vertex.avertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqsp, state.vertex.pvertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqst, state.vertex.tvertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
#if MAX_DIAG_CLASS>1
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2a,state.vertex.avertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2p,state.vertex.pvertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2t,state.vertex.tvertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2a,state.vertex.avertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2p,state.vertex.pvertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2t,state.vertex.tvertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
#if DEBUG_SYMMETRIES
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2ba,state.vertex.avertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2bp,state.vertex.pvertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2bt,state.vertex.tvertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2ba,state.vertex.avertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2bp,state.vertex.pvertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2bt,state.vertex.tvertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
#endif
#endif
#if MAX_DIAG_CLASS>2
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3a, state.vertex.avertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3p, state.vertex.pvertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3t, state.vertex.tvertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3a, state.vertex.avertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3p, state.vertex.pvertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3t, state.vertex.tvertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3a2,state.vertex.avertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3p2,state.vertex.pvertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3t2,state.vertex.tvertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
#endif
        int REG_loaded, MAX_DIAG_CLASS_loaded, N_LOOPS_loaded, GRID_loaded;
        double glb_Gamma_loaded, glb_T_loaded, glb_mu_loaded, glb_U_loaded, glb_epsilon_loaded, glb_V_loaded;
    H5::Group group_params(file_out.openGroup(PARAM_LIST));
    read_from_hdf(group_params, "REG", REG_loaded);
    read_from_hdf(group_params, "MAX_DIAG_CLASS", MAX_DIAG_CLASS_loaded);
    read_from_hdf(group_params, "mu", glb_mu_loaded);
    read_from_hdf(group_params, "V", glb_V_loaded);
    read_from_hdf(group_params, "GRID", GRID_loaded);
    bool are_parameters_identical = REG == REG_loaded and
            MAX_DIAG_CLASS == MAX_DIAG_CLASS_loaded and
            glb_mu == glb_mu_loaded and
            glb_V == glb_V_loaded and
            GRID == GRID_loaded;
    if (!are_parameters_identical) {
        utils::print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        utils::print("\t Warning!: \t Parameters of executable do not agree with those in HDF file ", filename, "\n");
        const vec<bool> is_identical_parameter = {
                MAX_DIAG_CLASS == MAX_DIAG_CLASS_loaded
                ,glb_mu == glb_mu_loaded
                ,glb_V == glb_V_loaded
                ,GRID == GRID_loaded
        };
        const vec<std::string> parameter_names = {
                "MAX_DIAG_CLASS"
                ,"glb_mu"
                ,"glb_V"
                ,"GRID"
        };
        for (int i = 0; i < is_identical_parameter.size(); i++){
            if (!is_identical_parameter[i]) utils::print("\t parameter ", parameter_names[i], " is different.\n");
        }
        utils::print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
    }
    file_out.close();
    return state;
}
Referenced by compare_flow_with_FDTs(), parquet_checks(), parquet_solver(), and test_read_write_state_hdf().
SELF_LIST()
const H5std_string SELF_LIST ("selflist")
Referenced by hdf5_impl::write_state_to_hdf_LambdaLayer().
test_read_write_data_hdf()
bool test_read_write_data_hdf (bool verbose)
— Test function — ///
Definition at line 259 of file hdf5_routines.c++.
{
    //if (verbose) utils::print("Testing HDF input and output:", true);
    vec<comp> vector_original(10, glb_i);
    std::array<std::size_t,3> dims_mularr = {1,2,3};
    multidimensional::multiarray<comp,3> mularr_original(dims_mularr, glb_i);
    std::string testfile_name = "test.h5";
    //if (verbose) utils::print("File name: " + testfile_name, true);
    // write to hdf file
    H5::H5File file_out = create_hdf_file(testfile_name.c_str());
    //if (verbose) utils::print("Created file.", true);
    //H5::H5std_string FILE_NAME(data_dir + "test.h5");
    H5::Group group_out(file_out.createGroup("/data"));
    //if (verbose) utils::print("Created group.", true);
    write_to_hdf(group_out, "vector", vector_original, false);
    write_to_hdf(group_out, "mularr", mularr_original, false);
    //if (verbose) utils::print("Written to hdf.", true);
    // read from hdf file
    hid_t file_id = H5Fopen(testfile_name.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
    H5::Group group = H5Gopen(file_id, "data", H5P_DEFAULT);
    //if (verbose) utils::print("Loaded group.", true);
    vec<comp> vector_input;
    read_from_hdf<comp>(group, "vector", vector_input);
    //if (verbose) utils::print("Loaded vector.", true);
    multidimensional::multiarray<comp,3> mularr_input;
    read_from_hdf<comp,3>(group, "mularr", mularr_input);
    //if (verbose) utils::print("Loaded multiarray.", true);
    //if (verbose) utils::print("Length of original vec: ", vector_original.size(), true);
    //if (verbose) utils::print("Length of loaded vec: ", vector_input.size(), true);
    comp deviation_vec = (vector_input - vector_original).max_norm();
    if (std::abs(deviation_vec) < 1e-10) utils::print("Read / write of vector to HDF file successful.", true);
    else utils::print("PROBLEM during read / write of vector to HDF file.", true);
    comp deviation_mularr=(mularr_input -mularr_original).maxabs();
    if (std::abs(deviation_mularr) < 1e-10) utils::print("Read / write of multiarray to HDF file successful.", true);
    else utils::print("PROBLEM during read / write of multiarray to HDF file.", true);
    //H5::H5std_string FILE_NAME(data_dir + "test.h5");
    H5::Group group_out_L(file_out.createGroup("/data_with_LambdaLayers"));
    //if (verbose) putils::print("Created group.", true);
    write_to_hdf_LambdaLayer(group_out_L, "vector", vector_original, 1, 10,  false);
    write_to_hdf_LambdaLayer(group_out_L, "mularr", mularr_original, 1, 10,  false);
    //if (verbose) putils::print("Written to hdf LambdaLayer.", true);
    // read from hdf file
    //hid_t file_id = H5Fopen(testfile_name.c_str(), H5F_ACC_RDONLY, H5P_DEFAULT);
    H5::Group group_L = H5Gopen(file_id, "data_with_LambdaLayers", H5P_DEFAULT);
    vec<comp> vector_input_L;
    read_from_hdf_LambdaLayer<comp>(group_L, "vector", vector_input_L, 1);
    multidimensional::multiarray<comp,3> mularr_input_L;
    read_from_hdf_LambdaLayer<comp>(group_L, "mularr", mularr_input_L, 1);
    comp deviation_vec_L = (vector_input_L - vector_original).max_norm();
    comp deviation_mularr_L=(mularr_input_L -mularr_original).maxabs();
    bool passed = true;
    if (verbose) {
        if (std::abs(deviation_vec_L) < 1e-10)
            utils::print("Read / write of vector to LambdaLayer of HDF file successful.", true);
        else {
            passed = false;
            utils::print("PROBLEM during read / write of vector to LambdaLayer of HDF file.", true);
        }
        if (std::abs(deviation_mularr_L) < 1e-10)
            utils::print("Read / write of multiarray to LambdaLayer ofHDF file successful.", true);
        else {
            passed = false;
            utils::print("PROBLEM during read / write to LambdaLayer of multiarray to HDF file.", true);
        }
    }
    return passed;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), create_hdf_file(), glb_i(), maxabs(), utils::print(), write_to_hdf(), and write_to_hdf_LambdaLayer().
test_read_write_state_hdf()
template<typename Q > bool test_read_write_state_hdf (bool verbose)
Definition at line 897 of file hdf5_routines.hpp.
{
    //if (verbose) utils::print("Testing HDF input and output of states:", true);
    const double Lambda = 1.;
    const int Lambda_it = 1;
    const int numberLambdaLayers = 10;
    State<Q,false> state_output(Lambda);
    state_output.initialize();
    state_output = state_output + 1.;
    write_state_to_hdf("test_state.h5", 0. , numberLambdaLayers, state_output);
    //utils::print("Written state", true);
    State<Q,false> state_input = read_state_from_hdf("test_state.h5", 0);
    //utils::print("Read state", true);
    State<Q,false> state_diff = state_output - state_input;
    add_state_to_hdf("test_state.h5", Lambda_it  , state_output*2);
    add_state_to_hdf("test_state.h5", Lambda_it+1, state_input);
    write_state_to_hdf("test_statediff.h5", 0., numberLambdaLayers, state_diff);
    bool passed = true;
    if (verbose) {
        if (state_diff.norm() < 1e-10) utils::print("Read / write of state data to LambdaLayer of HDF file successful.", true);
        else {
            passed = false;
            utils::print("PROBLEM during read / write of state data to LambdaLayer of HDF file. deviation : ",
                         state_diff.norm(), true);
        }
        if ((state_output.selfenergy.Sigma.frequencies.  primary_grid.get_all_frequencies() -
             state_input.selfenergy.Sigma.frequencies.  primary_grid.get_all_frequencies()).max_norm() < 1e-10)
            utils::print("Read / write of frequency grid to LambdaLayer of HDF file successful.", true);
        else {
            passed = false;
            utils::print("PROBLEM during read / write of frequency grid to LambdaLayer to HDF file.", true);
        }
    }
    return passed;
}
References add_state_to_hdf(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), utils::print(), read_state_from_hdf(), and write_state_to_hdf().
W_CENTER()
const H5std_string W_CENTER ("w_center")
write_state_to_hdf()
template<typename Q , bool diff> void write_state_to_hdf (const H5std_string FILE_NAME, double Lambda_i, const int Lambda_size, const State< Q, diff > & state_in, const bool verbose = true, const bool is_converged = false)
Create file with fixed number of Lambda layers and save state to first Lambda layer.
Definition at line 836 of file hdf5_routines.hpp.
{
#ifdef USE_MPI
    if (mpi_world_rank() == 0)  // only the process with ID 0 writes into file to avoid collisions
#endif
    {
        hdf5_impl::write_state_to_hdf_LambdaLayer(FILE_NAME, state_in, 0, Lambda_size, "w", is_converged);
        if (verbose) {
            utils::print("Successfully saved in hdf5 file: ", FILE_NAME);
            utils::print_add(" in Lambda-layer ", 0, false);
            utils::print_add("", true);
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), mpi_world_rank(), utils::print(), utils::print_add(), and hdf5_impl::write_state_to_hdf_LambdaLayer().
Referenced by compare_with_FDTs(), compare_with_FDTs(), main(), parquet_checks(), parquet_solver(), run_parquet(), and test_read_write_state_hdf().
write_to_hdf() [1/4]
template<typename Q , typename H5object , int nrows, int ncols> void write_to_hdf (H5object & group, const H5std_string & dataset_name, const Eigen::Matrix< Q, nrows, ncols > & data, const bool data_set_exists)
Write Eigen::Matrix to HDF group/file.
Definition at line 444 of file hdf5_routines.hpp.
{
    if (mpi_world_rank() == 0) {
        hsize_t dims[2] = {(hsize_t)data.cols(), (hsize_t)data.rows()}; // standard Eigen::Matrix is stored in column-major format
        H5::DataSpace file_space(2, dims);
        H5::DataSet mydataset;
        if (!data_set_exists) mydataset = hdf5_impl::create_Dataset<Q,H5object>(group, dataset_name, file_space);
        else mydataset = group.openDataSet(dataset_name); // hdf5_impl::open_Dataset<H5object>(group, dataset_name);
        hdf5_impl::write_data_to_Dataset(data, mydataset);
        mydataset.close();
        file_space.close();
    }
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), mpi_world_rank(), and hdf5_impl::write_data_to_Dataset().
write_to_hdf() [2/4]
template<typename Q , std::size_t depth, typename H5object > void write_to_hdf (H5object & group, const H5std_string & dataset_name, const multidimensional::multiarray< Q, depth > & data, const bool data_set_exists)
Write multiarray to HDF group/file.
Definition at line 425 of file hdf5_routines.hpp.
{
    if (mpi_world_rank() == 0) {
        hsize_t dims[depth];
        std::copy(std::begin(data.length()), std::end(data.length()), std::begin(dims));
        H5::DataSpace file_space(depth, dims);
        H5::DataSet mydataset;
        if (!data_set_exists) mydataset = hdf5_impl::create_Dataset<Q,H5object>(group, dataset_name, file_space);
        else mydataset = group.openDataSet(dataset_name); // hdf5_impl::open_Dataset<H5object>(group, dataset_name);
        hdf5_impl::write_data_to_Dataset(data, mydataset);
        mydataset.close();
        file_space.close();
    }
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::length(), mpi_world_rank(), and hdf5_impl::write_data_to_Dataset().
Referenced by rvert< Q >::check_symmetries(), compute_diff_SDE(), rvert< Q >::save_expanded(), IntegrandSE< Q, vertType, all_spins, return_type, version >::save_integrand(), Propagator< Q >::save_propagator_values(), test_read_write_data_hdf(), Hartree_Solver::write_out_propagators(), and hdf5_impl::write_state_to_hdf_LambdaLayer().
write_to_hdf() [3/4]
template<typename Q , typename H5object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, bool >||std::is_same_v< Q, char >, bool > = true> void write_to_hdf (H5object & group, const H5std_string & dataset_name, const Q & data, const bool data_set_exists)
Write scalar to HDF group/file as Attribute.
Definition at line 367 of file hdf5_routines.hpp.
{
    if (mpi_world_rank() == 0) {
        H5::DataSpace file_space(H5S_SCALAR);
    if constexpr(std::is_same_v<Q, double>) {
        H5::Attribute attr;
        if (!data_set_exists) attr = group.createAttribute( dataset_name, H5::PredType::NATIVE_DOUBLE, file_space );
        else attr = group.openAttribute( dataset_name );
        attr.write( H5::PredType::NATIVE_DOUBLE, &data );
    }
    else if constexpr(std::is_same_v<Q, comp>) {
        H5::CompType mtype_comp = def_mtype_comp();
        H5::Attribute attr;
        if (!data_set_exists) attr = group.createAttribute( dataset_name, mtype_comp, file_space );
        else attr = group.openAttribute( dataset_name );
        attr.write( mtype_comp, &data );
    }
    else if constexpr(std::is_same_v<Q, int>) {
        H5::Attribute attr;
        if (!data_set_exists) attr = group.createAttribute( dataset_name, H5::PredType::NATIVE_INT, file_space );
        else attr = group.openAttribute( dataset_name );
        attr.write( H5::PredType::NATIVE_INT, &data );
    }
    else if constexpr(std::is_same_v<Q, char>) {
        H5::Attribute attr;
        if (!data_set_exists) attr = group.createAttribute( dataset_name, H5::PredType::NATIVE_CHAR, file_space );
        else attr = group.openAttribute( dataset_name );
        attr.write( H5::PredType::NATIVE_CHAR, &data );
    }
    else if constexpr(std::is_same_v<Q, bool>) {
        H5::Attribute attr;
        if (!data_set_exists) attr = group.createAttribute( dataset_name, H5::PredType::NATIVE_HBOOL, file_space );
        else attr = group.openAttribute( dataset_name );
        attr.write( H5::PredType::NATIVE_HBOOL, &data );
    }
        file_space.close();
    }
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), def_mtype_comp(), and mpi_world_rank().
write_to_hdf() [4/4]
template<typename Q , typename H5object > void write_to_hdf (H5object & group, const H5std_string & dataset_name, const std::vector< Q > & data, const bool data_set_exists)
Write vector to HDF group/file.
Definition at line 408 of file hdf5_routines.hpp.
{
    if (mpi_world_rank() == 0) {
        hsize_t dims[1] = {data.size()};
        H5::DataSpace file_space(1, dims);
        H5::DataSet mydataset;
        if (!data_set_exists) mydataset = hdf5_impl::create_Dataset<Q,H5object>(group, dataset_name, file_space);
        else mydataset = group.openDataSet(dataset_name); // hdf5_impl::open_Dataset<H5object>(group, dataset_name);
        hdf5_impl::write_data_to_Dataset(data, mydataset);
        mydataset.close();
        file_space.close();
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), mpi_world_rank(), and hdf5_impl::write_data_to_Dataset().
write_to_hdf_LambdaLayer() [1/2]
template<typename Q , std::size_t depth, typename H5object > void write_to_hdf_LambdaLayer (H5object & group, const H5std_string & dataset_name, const multidimensional::multiarray< Q, depth > & data, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
Write multiarray to Lambda layer of HDF group/file.
Definition at line 469 of file hdf5_routines.hpp.
{
    assert(Lambda_it < numberLambda_layers);
    typename multidimensional::multiarray<Q, depth>::dimensions_type length = data.length();
    hdf5_impl::write_to_hdf_LambdaLayer_impl<Q,depth,H5object>(group, dataset_name, data, length, Lambda_it, numberLambda_layers, data_set_exists);
};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::length().
write_to_hdf_LambdaLayer() [2/2]
template<typename Q , typename H5object > void write_to_hdf_LambdaLayer (H5object & group, const H5std_string & dataset_name, const std::vector< Q > & data, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
Write vector to Lambda layer of HDF group/file.
Definition at line 462 of file hdf5_routines.hpp.
{
    assert(Lambda_it < numberLambda_layers);
    std::array<std::size_t,1> length = {data.size()};
    hdf5_impl::write_to_hdf_LambdaLayer_impl<Q,1,H5object>(group, dataset_name, data, length, Lambda_it, numberLambda_layers, data_set_exists);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by test_read_write_data_hdf(), and mfRG_stats::write_to_hdf().
Variable Documentation
N_freq_params
const int N_freq_params = 64
Definition at line 44 of file hdf5_routines.hpp.
RANK_freqs
const int RANK_freqs = 2
Definition at line 42 of file hdf5_routines.hpp.
RANK_irreducible
const int RANK_irreducible = 2
Definition at line 40 of file hdf5_routines.hpp.
RANK_K1
const int RANK_K1 = 2
TODO: Save frequency grids and frequency parameters for each channel individually.
— Constants concerning HDF5 data format — ///
Definition at line 37 of file hdf5_routines.hpp.
RANK_K2
const int RANK_K2 = 2
Definition at line 38 of file hdf5_routines.hpp.
RANK_K3
const int RANK_K3 = 2
Definition at line 39 of file hdf5_routines.hpp.
RANK_self
const int RANK_self = 2
Definition at line 41 of file hdf5_routines.hpp.