SIAM-Keldysh-mfRG: propagator.c++ File Reference
propagator.c++ File Reference
#include "propagator.hpp"
Functions
auto Fermi_distr (const double v, const double mu, const double T) -> double
auto Fermi_fac (const double v, const double mu, const double T) -> double
auto Eff_distr (const double v, const double T) -> double
auto Eff_fac (const double v, const double T) -> double
double Fermi_distribution (const double nu, const double T)
Function Documentation
Eff_distr()
auto Eff_distr (const double v, const double T) -> double
Definition at line 14 of file propagator.c++.
{
    if (EQUILIBRIUM) return Fermi_distr(v, glb_mu, T);
    else return 0.5 * (Fermi_distr(v, glb_mu + glb_V / 2., T) + Fermi_distr(v, glb_mu - glb_V / 2., T));
}
References EQUILIBRIUM, Fermi_distr(), glb_mu, and glb_V.
Eff_fac()
auto Eff_fac (const double v, const double T) -> double
Definition at line 19 of file propagator.c++.
{
    if (EQUILIBRIUM) return Fermi_fac(v, glb_mu, T);
    else return 1. - (Fermi_distr(v, glb_mu + glb_V / 2., T) + Fermi_distr(v, glb_mu - glb_V / 2., T));
}
References EQUILIBRIUM, Fermi_distr(), Fermi_fac(), glb_mu, and glb_V.
Referenced by check_FDTs_K1(), check_FDTs_selfenergy(), Propagator< Q >::GK(), and Propagator< Q >::SK().
Fermi_distr()
auto Fermi_distr (const double v, const double mu, const double T) -> double
Definition at line 3 of file propagator.c++.
{
    // return 1./(exp((v-mu)/T)+1.);
    if constexpr (!ZERO_T) return 0.5 * (1. - tanh((v-mu)/(2.*T))); // numerically preferential
    else return (v-mu) < 0. ? 1. : 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and ZERO_T.
Referenced by Eff_distr(), and Eff_fac().
Fermi_distribution()
double Fermi_distribution (const double nu, const double T)
Definition at line 24 of file propagator.c++.
{
    if constexpr (not ZERO_T){
        return 1 / (exp(nu / T) + 1.);
    }
    else{
        if (nu > 0.) return 0.;
        else if (nu == 0.) return 1/2.;
        else if (nu < 0.) return 1.;
        else assert(false); return 0.;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and ZERO_T.
Fermi_fac()
auto Fermi_fac (const double v, const double mu, const double T) -> double
Definition at line 9 of file propagator.c++.
{
    if constexpr (!ZERO_T) return tanh((v-mu)/(2.*T));
    else return sgn(v-mu);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), sgn(), and ZERO_T.
Referenced by compute_components_through_FDTs(), Eff_fac(), and Integrand_Phi_tilde< Q >::operator()().