SIAM-Keldysh-mfRG: state.hpp File Reference
state.hpp File Reference
#include "../data_structures.hpp"
#include "four_point/vertex.hpp"
#include "two_point/selfenergy.hpp"
#include "two_point/propagator.hpp"
#include "../perturbation_theory_and_parquet/hartree_term.hpp"
#include "../utilities/util.hpp"
#include <boost/numeric/odeint.hpp>
#include <string>
Classes
class State< Q, differentiated >
struct boost::numeric::odeint::vector_space_norm_inf< State< state_datatype > >
vector space infinity-norm for ODE solver of Boost
Namespaces
namespace boost
namespace boost::numeric
namespace boost::numeric::odeint
Functions
template<typename Q >
auto max_rel_err (const State< Q, false > &err, const State< Q, false > &scale_State) -> double
template<typename Q , bool differentiated = false>
State< Q, differentiated > abs (const State< Q, differentiated > &state)
Function Documentation
abs()
template<typename Q , bool differentiated = false> State< Q, differentiated > abs (const State< Q, differentiated > & state)
Definition at line 200 of file state.hpp.
{
    State<Q,differentiated> state_abs = state.abs();
    return state_abs;
}
References State< Q, differentiated >::abs(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K2(), maxabs(), and ode_solver_impl::rk_step().
max_rel_err()
template<typename Q > auto max_rel_err (const State< Q, false > & err, const State< Q, false > & scale_State) -> double
element-wise relative deviation
alternative: relative deviation of norm
Definition at line 189 of file state.hpp.
{
    //State<Q,false> relState = (err / scale_State);
    //return relState.norm();
    return err.norm() / scale_State.norm();
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by ode_solver_impl::rk_step().