#!/bin/bash
#SBATCH -o /home/hpc/uh3o1/ri26yad/LOG/Density_matrix/myjob.%j.%N.out
#SBATCH -D /home/hpc/uh3o1/ri26yad/RUN
#SBATCH -J some_job
#SBATCH --get-user-env
#SBATCH --clusters=mpp2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=28
#SBATCH --mail-type=end
#SBATCH --export=NONE
#SBATCH --time=00:15:00

cd /naslx/projects/uh3o1/ri26yad/DATA/Density_matrix_eigenvalues/Without_leads
/home/hpc/uh3o1/ri26yad/bin/density_matrix_non_int -N 8 -Vg 1.0 -mu 0.0 -T 0.1 -num_freq_pre 600000 -seed 1
