SIAM-Keldysh-mfRG: bubble_corrections.hpp File Reference
bubble_corrections.hpp File Reference
#include "../data_structures.hpp"
#include "../correlation_functions/four_point/vertex.hpp"
#include "../parameters/master_parameters.hpp"
#include "../utilities/util.hpp"
#include <cmath>
Functions
template<typename Q >
auto correctionFunctionBubbleAT_REG2_Keldysh (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<>
auto correctionFunctionBubbleAT_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<typename Q >
auto correctionFunctionBubbleAT_REG2_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubbleAT_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<>
auto correctionFunctionBubbleAT_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<typename Q >
auto correctionFunctionBubbleP_REG2_Keldysh (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<>
auto correctionFunctionBubbleP_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<typename Q >
auto correctionFunctionBubbleP_REG2_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubbleP_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<>
auto correctionFunctionBubbleP_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<typename Q >
auto correctionFunctionBubble_REG4_Matsubara_PHS (double w, double vmin, double vmax, double Delta) -> Q
template<typename Q >
auto correctionFunctionBubble_REG3_Matsubara_PHS_nondiff (const double w, const double vmax, const double Lambda, const double Delta)
Correction functions for interaction regulator (REG == 3)
template<typename Q >
auto correctionFunctionBubble_REG3_Matsubara_PHS_diff (double w, double vmax, double Lambda, const double Delta)
template<typename Q >
auto correctionFunctionBubbleAT_REG3_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubbleP_REG3_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubbleAT_REG4_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Correction functions for interaction regulator (REG == 4)
template<typename Q >
auto correctionFunctionBubbleP_REG4_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubbleAT (double w, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubbleP (double w, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
template<typename Q >
auto correctionFunctionBubble (double w, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, double Lambda, double eta_1, double eta_2, char channel, bool diff) -> Q
Function Documentation
correctionFunctionBubble()
template<typename Q > auto correctionFunctionBubble (double w, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, double Lambda, double eta_1, double eta_2, char channel, bool diff) -> Q
Wrapper for the two functions above, distinguishing a/t channels from p channel.
Definition at line 459 of file bubble_corrections.hpp.
{
    if (channel == 'p')
        return correctionFunctionBubbleP (w, vmin, vmax, epsilon, Sigma_H, Delta, Lambda, eta_1, eta_2, diff);
    else
        return correctionFunctionBubbleAT(w, vmin, vmax, epsilon, Sigma_H, Delta, Lambda, eta_1, eta_2, diff);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), correctionFunctionBubbleAT(), and correctionFunctionBubbleP().
Referenced by asymp_corrections_bubble().
correctionFunctionBubble_REG3_Matsubara_PHS_diff()
template<typename Q > auto correctionFunctionBubble_REG3_Matsubara_PHS_diff (double w, double vmax, double Lambda, const double Delta)
Definition at line 295 of file bubble_corrections.hpp.
{
    Q value;
    if (std::abs(w) < 1e-10) {
        if (Lambda/vmax < 1e-5) {
            value = -0.5 * (
                    -2. * vmax * Lambda / pow(vmax*vmax + Lambda*Lambda, 2)
            );
        }
        else {
            value = -0.5 * (
                    -2. * vmax * Lambda / pow(vmax*vmax + Lambda*Lambda, 2) - atan(Lambda / vmax) / (Lambda*Lambda)
                    + vmax / (Lambda * (vmax*vmax + Lambda*Lambda))
            );
        }
    }
    else {
        value = -0.25 * (
                0.5 * vmax * Lambda * (-4.*Lambda*Lambda + 4*vmax*vmax - 5*w*w) / (
                        (Lambda*Lambda + w*w*0.25)
                        *
                        (Lambda*Lambda + pow(vmax + w*0.5, 2))
                        *
                        (Lambda*Lambda + pow(vmax - w*0.5, 2))
                                                                                  )
                +
                2. * std::real( -2.*glb_i *log((vmax + w*0.5 + glb_i * Lambda) / (vmax - w*0.5 - glb_i * Lambda)) / pow(w + 2.*glb_i*Lambda, 2))
        );
    }
    return value;
}
References glb_i(), and log().
Referenced by multidimensional::multiarray< T, depth >::_flat_size(), vec< T >::abs(), multidimensional::multiarray< T, depth >::abs(), State< Q, differentiated >::abs(), abs(), multidimensional::abs_compare(), dataContainerBase< Q, rank >::acc(), irreducible< Q >::acc(), SelfEnergy< Q >::acc(), adaptive_simpson_integrator(), add(), flowgrid::add_points_to_Lambda_grid(), add_state_to_hdf(), dataContainerBase< Q, rank >::add_vec(), dataContainerBase< Q, rank >::add_vec(), alphas_to_iK(), SelfEnergy< Q >::analyze_tails(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::analyze_tails(), fullvert< Q >::analyze_tails_K1(), fullvert< Q >::analyze_tails_K2v(), fullvert< Q >::analyze_tails_K2w(), fullvert< Q >::analyze_tails_K3v(), fullvert< Q >::analyze_tails_K3vp(), fullvert< Q >::analyze_tails_K3w(), anderson_update(), rvert< Q >::apply_binary_op_to_all_vertexBuffers(), rvert< Q >::apply_unary_op_to_all_vertexBuffers(), rvert< Q >::apply_unary_op_to_all_vertexBuffers(), asymp_corrections_bubble(), asymp_corrections_loop(), multidimensional::multiarray< T, depth >::at(), multidimensional::multiarray< T, depth >::at(), multidimensional::BlockView< T, depth >::at(), dataContainerBase< Q, rank >::at(), multidimensional::multiarray< T, depth >::at(), multidimensional::multiarray< T, depth >::at(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::BlockView< T, depth >::BlockView(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::bubble_value_prefactor(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_bubble_function(), calculate_dGammaC_left_insertion(), calculate_dGammaC_right_insertion(), calculate_dGammaL(), calculate_dGammaR(), calculate_dSigma_SOPT(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::case_always_has_to_be_zero(), ceil2bfreq(), ceil2bfreq(), fullvert< Q >::center_frequency_grids(), GeneralVertex< Q, symmtype, differentiated >::center_frequency_grids(), rvert< Q >::center_frequency_grids(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::center_frequency_grids(), multidimensional::BlockView< T, depth >::check_bounds(), multidimensional::multiarray< T, depth >::check_bounds(), multidimensional::multiarray< T, depth >::check_bounds_end(), check_convergence_hdf(), check_FDTs(), check_FDTs_K1(), check_FDTs_selfenergy(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::check_if_frequencyGrid_identical(), utils::check_input(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::check_presence_of_symmetry_related_contributions(), SelfEnergy< Q >::check_resolution(), check_SE_causality(), check_SE_causality(), check_selfconsistency_of_K1K2(), SelfEnergy< Q >::check_symmetries(), GeneralVertex< Q, symmtype, differentiated >::check_symmetries(), fullvert< Q >::check_symmetries(), rvert< Q >::check_symmetries(), close_hdf_file(), collapse(), collapse_all(), anderson_impl::colwise_difference(), fullvert< Q >::combine_SBE_to_K2(), rvert< Q >::combine_SBE_to_K2(), fullvert< Q >::combine_SBE_to_K2b(), rvert< Q >::combine_SBE_to_K2b(), fullvert< Q >::combine_SBE_to_K3_SBE(), rvert< Q >::combine_SBE_to_K3_SBE(), compare_flow_with_FDTs(), compare_with_FDTs(), compare_with_FDTs(), compute_BSE(), compute_BSE(), compute_components_through_FDTs(), compute_components_through_FDTs(), compute_diff_SDE(), Hartree_Solver::compute_filling_oneshot(), Hartree_Solver::compute_Hartree_term(), Hartree_Solver::compute_Hartree_term_bracketing(), Hartree_Solver::compute_Hartree_term_Friedel(), LoopCalculator< Q, vertType, all_spins, version >::compute_Keldysh(), LoopCalculator< Q, vertType, all_spins, version >::compute_Matsubara_finiteT(), LoopCalculator< Q, vertType, all_spins, version >::compute_Matsubara_zeroT(), compute_SDE(), compute_SDE_impl(), compute_SDE_impl_v1(), compute_SDE_impl_v2(), compute_SDE_impl_v3(), compute_SDE_v1(), compute_SDE_v2(), compute_SDE_v3(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::compute_vertices(), vec< T >::conj(), flowgrid::construct_flow_grid(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K2(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K2b(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K3_SBE(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K2(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K2b(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K3_SBE(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K1(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K2(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K2b(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K3(), oneBubble< Q >::convert_to_fermionic_frequencies_1(), Bubble< Q >::convert_to_fermionic_frequencies_1(), oneBubble< Q >::convert_to_fermionic_frequencies_2(), Bubble< Q >::convert_to_fermionic_frequencies_2(), convert_vec_to_type(), correctionFunctionBubble(), correctionFunctionBubbleAT(), correctionFunctionBubbleAT_REG3_Matsubara_PHS(), correctionFunctionBubbleAT_REG4_Matsubara_PHS(), correctionFunctionBubbleP(), correctionFunctionBubbleP_REG3_Matsubara_PHS(), correctionFunctionBubbleP_REG4_Matsubara_PHS(), correctionFunctionSelfEnergy(), correctionFunctionSelfEnergy_Keldysh(), correctionFunctionSelfEnergy_Keldysh(), correctionFunctionSelfEnergy_Matsubara_NoPHS(), correctionFunctionSelfEnergy_Matsubara_NoPHS(), CostSE_Wscale< Q >::CostSE_Wscale(), costval(), costval_nD(), hdf5_impl::create_Dataset(), create_hdf_file(), def_mtype_comp(), def_proplist_comp(), FrequencyGrid< hybridGrid >::derive_auxiliary_parameters(), FrequencyGrid< angularGrid >::derive_auxiliary_parameters(), vec< T >::diff(), Propagator< Q >::diff_Sigma_K_REG5(), dataContainerBase< Q, rank >::direct_set(), SelfEnergy< Q >::direct_set(), irreducible< Q >::direct_set(), flowgrid::exp_parametrization::dlambda_dt(), flowgrid::log_parametrization::dlambda_dt(), flowgrid::sqrt_parametrization::dlambda_dt(), dot(), dotproduct(), dataContainerBase< Q, rank >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), dataContainerBase< Q, rank >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), elementwise(), multidimensional::elementwise(), multidimensional::elementwise(), vec< T >::elementwise_map_assign(), multidimensional::multiarray< T, depth >::elementwise_map_assign(), rvert< Q >::enforce_freqsymmetriesK1(), rvert< Q >::enforce_freqsymmetriesK2(), rvert< Q >::enforce_freqsymmetriesK3(), IntegrandSE< Q, vertType, all_spins, return_type, version >::evaluate_propagator(), IntegrandSE< Q, vertType, all_spins, return_type, version >::evaluate_propagator_vectorized(), IntegrandSE< Q, vertType, all_spins, return_type, version >::evaluate_vertex(), IntegrandSE< Q, vertType, all_spins, return_type, version >::evaluate_vertex(), IntegrandSE< Q, vertType, all_spins, return_type, version >::evaluate_vertex_vectorized(), f_imag(), f_real(), Fermi_distr(), Fermi_distribution(), Hartree_Solver::fermi_distribution(), Fermi_fac(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::find_vmin_and_vmax(), fullvert< Q >::findBestFreqGrid(), multidimensional::multiarray< T, depth >::flat_at(), multidimensional::multiarray< T, depth >::flat_at(), multidimensional::multiarray< T, depth >::flat_index(), multidimensional::BlockView< T, depth >::flat_index(), floor2bfreq(), floor2bfreq(), flowgrid::flow_grid_step_sizes(), fopt_state(), FrequencyGrid< angularGrid >::frequency_from_t(), FrequencyGrid< hybridGrid >::frequency_from_t(), FrequencyGrid< eliasGrid >::frequency_from_t(), FrequencyGrid< angularGrid >::FrequencyGrid(), FrequencyGrid< hybridGrid >::FrequencyGrid(), FrequencyTransformations::FrequencyTransformations(), Hartree_Solver::friedel_sum_rule_check(), Propagator< Q >::G0M_inv(), Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::G0R_inv_SIAM(), fullvert< Q >::gammaRb(), fullvert< Q >::gammaRb(), fullvert< Q >::gammaRb_symmetry_expanded(), Gauss_Kronrod_13(), Gauss_Kronrod_7(), Gauss_Lobatto_4(), GeneralVertex< Q, symmtype, differentiated >::GeneralVertex(), GeneralVertex< Q, symmtype, differentiated >::GeneralVertex(), GeneralVertex< Q, symmtype, differentiated >::GeneralVertex(), GeneralVertex< Q, symmtype, differentiated >::GeneralVertex(), GeneralVertex< Q, symmtype, differentiated >::GeneralVertex(), GeneralVertex< Q, symmtype, differentiated >::GeneralVertex(), utils::generate_data_directory(), utils::generate_filename(), ode_solver_impl::butcher_tableau< stages >::get_a(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), FrequencyGrid< hybridGrid >::get_auxiliary_gridpoint(), FrequencyGrid< angularGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), utils::get_cpu_hours(), multidimensional::multiarray< T, depth >::get_cumul_length(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), fullvert< Q >::get_curvature_max_K1(), fullvert< Q >::get_curvature_max_K2(), fullvert< Q >::get_curvature_max_K3(), SelfEnergy< Q >::get_curvature_maxSE(), multidimensional::multiarray< T, depth >::get_depth(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), fullvert< Q >::get_deriv_max_K1(), fullvert< Q >::get_deriv_max_K2(), fullvert< Q >::get_deriv_max_K3(), SelfEnergy< Q >::get_deriv_maxSE(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xx(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xy(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xyz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_y(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yy(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_z(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_zz(), bufferFrequencyGrid< k >::get_diagclass(), ode_solver_impl::butcher_tableau< stages >::get_error_b(), multidimensional::multiarray< T, depth >::get_flatindex_ini(), bufferFrequencyGrid< k >::get_freqGrid_3(), bufferFrequencyGrid< k >::get_freqGrid_f(), VertexInput::get_freqs(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), FrequencyGrid< hybridGrid >::get_frequency(), FrequencyGrid< angularGrid >::get_frequency(), FrequencyGrid< eliasGrid >::get_frequency(), FrequencyGrid< angularGrid >::get_grid_index(), FrequencyGrid< angularGrid >::get_grid_index(), FrequencyGrid< hybridGrid >::get_grid_index(), FrequencyGrid< eliasGrid >::get_grid_index(), FrequencyGrid< hybridGrid >::get_grid_index(), FrequencyGrid< eliasGrid >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), get_i0_left_right(), get_Id_Matrix_4x4(), VertexInput::get_indices(), IntegrandSE< Q, vertType, all_spins, return_type, version >::get_integrand_vals(), flowgrid::get_Lambda_checkpoints(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_Matsubara_integration_intervals(), ode_solver_impl::butcher_tableau< stages >::get_node(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::get_projection_lambda(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::get_projection_lambdaBar(), fullvert< Q >::get_rvertex(), fullvert< Q >::get_rvertex(), GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), SelfEnergy< Q >::get_selfenergy_vector_incl_hartree(), get_slice(), utils::get_time(), utils::get_time(), utils::get_time(), bufferFrequencyGrid< k >::get_tlower_f_aux(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K1(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K2(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K3(), bufferFrequencyGrid< k >::get_tupper_f_aux(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_value(), dataContainerBase< Q, rank >::get_values(), multidimensional::multiarray< T, depth >::get_values(), GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r(), multidimensional::BlockView< T, depth >::get_vec(), GeneralVertex< Q, symmtype, differentiated >::get_w_r_value_symmetry_expanded_nondiff(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::get_weights(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_weights(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_weights(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::get_weights(), bufferFrequencyGrid< k >::get_wlower_f(), bufferFrequencyGrid< k >::get_wupper_f(), getFlatIndex(), math_impl::getFlatIndex(), getFlatIndex(), getFlatIndex(), getFlatSize(), getMultIndex(), getMultIndex(), getMultIndex< 1 >(), getMultIndexSkippingOneDimension(), Propagator< Q >::GK(), Propagator< Q >::GK(), Propagator< Q >::GM(), Propagator< Q >::GM_REG2(), Propagator< Q >::GM_REG3(), Propagator< Q >::GM_REG4(), Propagator< Q >::GR(), Propagator< Q >::GR_REG2(), Propagator< Q >::GR_REG3(), Propagator< Q >::GR_REG4(), Propagator< Q >::GR_REG5(), grid_transf_inv_lin(), grid_transf_inv_v1(), grid_transf_inv_v2(), grid_transf_inv_v3(), grid_transf_inv_v4(), grid_transf_v1(), grid_transf_v2(), grid_transf_v3(), grid_transf_v4(), bufferFrequencyGrid< k >::gridtransf_f(), FrequencyGrid< eliasGrid >::guess_essential_parameters(), FrequencyGrid< hybridGrid >::guess_essential_parameters(), FrequencyGrid< angularGrid >::guess_essential_parameters(), bufferFrequencyGrid< k >::guess_essential_parameters(), h5_cast(), GeneralVertex< Q, symmtype, differentiated >::half2(), GeneralVertex< Q, symmtype, differentiated >::half2(), Hartree_Solver::Hartree_Solver(), Hartree_Solver::Hartree_Solver(), Hartree_Solver::Hartree_Solver(), heaviside(), iK_to_alphas(), vec< T >::imag(), indices_sum(), IndicesSymmetryTransformations::IndicesSymmetryTransformations(), IndicesSymmetryTransformations::IndicesSymmetryTransformations(), IndicesSymmetryTransformations::IndicesSymmetryTransformations(), hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(), State< Q, differentiated >::initialize(), irreducible< Q >::initialize(), GeneralVertex< Q, symmtype, differentiated >::initialize(), SelfEnergy< Q >::initialize(), FrequencyGrid< eliasGrid >::initialize_grid(), FrequencyGrid< hybridGrid >::initialize_grid(), FrequencyGrid< angularGrid >::initialize_grid(), GeneralVertex< Q, symmtype, differentiated >::initializeInterpol(), Propagator< Q >::initInterpolator(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::initInterpolator(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::initInterpolator(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator(), integer_division_ceil(), integer_division_floor(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::Integrand(), Adapt< Integrand, Q >::integrate(), Adapt< Integrand, Q >::integrate(), boost::numeric::odeint::detail::integrate_adaptive_check(), boost::numeric::odeint::detail::integrate_nonadaptive(), integration_measure_v1(), integration_measure_v2(), integration_measure_v3(), integration_measure_v4(), integrator(), integrator(), integrator_gsl(), integrator_gsl(), integrator_gsl_qag_helper(), integrator_gsl_qag_tails(), integrator_gsl_qag_v2(), integrator_gsl_qagil_helper(), integrator_gsl_qagiu_helper(), integrator_gsl_qagp_helper(), integrator_gsl_qagp_v2(), integrator_Matsubara_T0(), integrator_onlyTails(), integrator_riemann(), integrator_simpson(), integrator_simpson(), integrator_simpson(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::interpolate(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::interpolate_impl(), interpolate_lin1D(), interpolate_lin2D(), interpolate_lin3D(), interpolate_lin_on_aux1D(), interpolate_lin_on_aux2D(), interpolate_lin_on_aux3D(), interpolate_nearest1D(), interpolate_nearest2D(), interpolate_nearest3D(), interpolate_sloppycubic1D(), interpolate_sloppycubic2D(), interpolate_sloppycubic3D(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::interpolate_spline(), vec< T >::inv(), utils::is_all_finite(), GeneralVertex< Q, symmtype, differentiated >::is_differentiated(), is_doubleOccurencies(), bufferFrequencyGrid< k >::is_in_box(), bufferFrequencyGrid< k >::is_in_box(), bufferFrequencyGrid< k >::is_in_box(), multidimensional::multiarray< T, depth >::is_same_length(), is_symmetric(), is_zero_due_to_FDTs(), K2_convert2internalFreqs(), K2_convert2naturalFreqs(), K3_convert2internalFreqs(), K3_convert2naturalFreqs(), Propagator< Q >::Katanin_K(), LoopCalculator< Q, vertType, all_spins, version >::Keldysh_prefactor(), IntegrandSE< Q, vertType, all_spins, return_type, version >::Keldysh_value(), lagrangePoly(), flowgrid::exp_parametrization::lambda_from_t(), flowgrid::log_parametrization::lambda_from_t(), flowgrid::sqrt_parametrization::lambda_from_t(), flowgrid::linear_parametrization::lambda_from_t(), fullvert< Q >::left_diff_bare(), GeneralVertex< Q, symmtype, differentiated >::left_diff_bare(), fullvert< Q >::left_diff_bare(), rvert< Q >::left_diff_bare(), rvert< Q >::left_diff_bare(), rvert< Q >::left_diff_bare_symmetry_expanded(), fullvert< Q >::left_diff_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::left_diff_bare_symmetry_expanded(), fullvert< Q >::left_same_bare(), GeneralVertex< Q, symmtype, differentiated >::left_same_bare(), fullvert< Q >::left_same_bare(), rvert< Q >::left_same_bare(), rvert< Q >::left_same_bare(), rvert< Q >::left_same_bare_symmetry_expanded(), fullvert< Q >::left_same_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::left_same_bare_symmetry_expanded(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_left_scalar(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_left_vectorized(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_right_scalar(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::load_vertex_keldyshComponents_right_vectorized(), locate(), log(), flowgrid::log_resubstitution(), flowgrid::log_substitution(), loop(), multidimensional::multiarray< T, depth >::lpNorm(), main(), multidimensional::make_range(), utils::makedir(), LoopCalculator< Q, vertType, all_spins, version >::Matsubara_prefactor(), IntegrandSE< Q, vertType, all_spins, return_type, version >::Matsubara_value(), matsubarasum(), matsubarasum_vectorized(), vec< T >::max_norm(), max_rel_err(), multidimensional::multiarray< T, depth >::maxabs(), maxabs(), maxabs(), multidimensional::multiarray< T, depth >::minabs(), minimizer(), minimizer_nD(), mpi_collect(), mpi_collect(), mpi_initialize_buffer(), mpi_initialize_result(), mpi_reorder_result(), mpi_world_rank(), mpi_world_size(), multidimensional::multiarray< T, depth >::multiarray(), multiply(), my_integer_pow(), my_isfinite(), my_isfinite(), myabs(), myconj(), myconj< double >(), myIdentity(), myimag(), myimag< double >(), myreal(), myreal< double >(), myround(), myzero(), GeneralVertex< Q, symmtype, differentiated >::norm(), State< Q, differentiated >::norm(), Propagator< Q >::norm(), SelfEnergy< Q >::norm(), GeneralVertex< Q, symmtype, differentiated >::norm_K1(), fullvert< Q >::norm_K1(), GeneralVertex< Q, symmtype, differentiated >::norm_K2(), fullvert< Q >::norm_K2(), GeneralVertex< Q, symmtype, differentiated >::norm_K3(), fullvert< Q >::norm_K3(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::numSamples(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples_half(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::numSamples_half(), ode_solver(), boost::numeric::odeint::ode_solver_boost(), ODE_solver_Euler(), hdf5_impl::open_Dataset(), open_hdf_file_readOnly(), multidimensional::operator!=(), Integrand_sum_rule_spectrum::operator()(), adaptive_integrator_detail::integrand_reparametrized_Upper< Integrand >::operator()(), adaptive_integrator_detail::integrand_reparametrized_Lower< Integrand >::operator()(), rhs_n_loop_flow_t< Q >::operator()(), boost::numeric::odeint::vector_space_norm_inf< State< state_datatype > >::operator()(), multidimensional::multiarray< T, depth >::operator()(), multidimensional::multiarray< T, depth >::operator()(), Hartree_Solver::operator()(), Integrand_Phi_tilde< Q >::operator()(), Integrand_Ward_id_integrated< gridType >::operator()(), Integrand_sum_rule_K1tK::operator()(), CostSE_Wscale< Q >::operator()(), IntegrandBubble< Q >::operator()(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::operator()(), vec< T >::operator()(), vec< T >::operator()(), operator*(), multidimensional::operator*(), multidimensional::operator*(), multidimensional::operator*(), operator*(), operator*(), multidimensional::operator*(), multidimensional::operator*(), operator*(), GeneralVertex< Q, symmtype, differentiated >::operator*=(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator*=(), GeneralVertex< Q, symmtype, differentiated >::operator*=(), multidimensional::multiarray< T, depth >::operator*=(), multidimensional::multiarray< T, depth >::operator*=(), vec< T >::operator*=(), multidimensional::multiarray< T, depth >::operator*=(), rvert< Q >::operator*=(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator*=(), vec< T >::operator*=(), operator+(), operator+(), multidimensional::operator+(), multidimensional::operator+(), multidimensional::operator+(), operator+(), operator+(), multidimensional::operator+(), multidimensional::operator+(), operator+(), GeneralVertex< Q, symmtype, differentiated >::operator+=(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator+=(), GeneralVertex< Q, symmtype, differentiated >::operator+=(), multidimensional::multiarray< T, depth >::operator+=(), multidimensional::multiarray< T, depth >::operator+=(), vec< T >::operator+=(), multidimensional::multiarray< T, depth >::operator+=(), rvert< Q >::operator+=(), SelfEnergy< Q >::operator+=(), State< Q, differentiated >::operator+=(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator+=(), vec< T >::operator+=(), operator+=(), operator-(), multidimensional::operator-(), multidimensional::operator-(), multidimensional::operator-(), multidimensional::operator-(), operator-(), operator-(), multidimensional::operator-(), multidimensional::operator-(), multidimensional::operator-(), operator-(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator-=(), GeneralVertex< Q, symmtype, differentiated >::operator-=(), multidimensional::multiarray< T, depth >::operator-=(), multidimensional::multiarray< T, depth >::operator-=(), vec< T >::operator-=(), multidimensional::multiarray< T, depth >::operator-=(), rvert< Q >::operator-=(), SelfEnergy< Q >::operator-=(), State< Q, differentiated >::operator-=(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator-=(), vec< T >::operator-=(), operator-=(), multidimensional::operator/(), multidimensional::operator/(), multidimensional::operator/(), operator/(), multidimensional::operator/(), multidimensional::operator/(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator/=(), GeneralVertex< Q, symmtype, differentiated >::operator/=(), multidimensional::multiarray< T, depth >::operator/=(), multidimensional::multiarray< T, depth >::operator/=(), multidimensional::multiarray< T, depth >::operator/=(), rvert< Q >::operator/=(), SelfEnergy< Q >::operator/=(), State< Q, differentiated >::operator/=(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator/=(), vec< T >::operator/=(), operator<<(), operator<<(), multidimensional::ranged_view< Iter >::operator[](), multidimensional::multiarray< T, depth >::operator[](), multidimensional::multiarray< T, depth >::operator[](), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::optimize_grid(), anderson_impl::ordinary_least_squares(), parquet_checks(), parquet_iteration(), parquet_solver(), partial_deriv(), partial_deriv(), partial_deriv_v2(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::perform_computation(), selfenergy_loop::pick_channel(), selfenergy_loop::pick_spin(), postRKstep_stuff(), power2(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::precompute_vertices(), utils::print(), utils::print(), utils::print(), utils::print(), utils::print(), utils::print(), utils::print_add(), utils::print_add(), utils::print_add(), utils::print_job_info(), utils::print_time_stamp(), PT_initialize_Bubble(), multidimensional::multiarray< T, depth >::range(), multidimensional::multiarray< T, depth >::range(), read_config_from_hdf(), read_from_hdf(), read_from_hdf(), read_from_hdf(), hdf5_impl::read_from_hdf_impl(), read_from_hdf_LambdaLayer(), read_from_hdf_LambdaLayer(), hdf5_impl::read_from_hdf_LambdaLayer_impl(), read_Lambdas_from_hdf(), rvert< Q >::read_symmetryreduced_rvert(), rvert< Q >::read_value(), vec< T >::real(), SelfEnergy< Q >::rel_deviation_to(), fullvert< Q >::reorder_due2antisymmetry(), rhs_n_loop_flow(), fullvert< Q >::right_diff_bare(), GeneralVertex< Q, symmtype, differentiated >::right_diff_bare(), fullvert< Q >::right_diff_bare(), rvert< Q >::right_diff_bare(), rvert< Q >::right_diff_bare(), rvert< Q >::right_diff_bare_symmetry_expanded(), fullvert< Q >::right_diff_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::right_diff_bare_symmetry_expanded(), fullvert< Q >::right_same_bare(), GeneralVertex< Q, symmtype, differentiated >::right_same_bare(), fullvert< Q >::right_same_bare(), rvert< Q >::right_same_bare(), rvert< Q >::right_same_bare(), rvert< Q >::right_same_bare_symmetry_expanded(), fullvert< Q >::right_same_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::right_same_bare_symmetry_expanded(), old_ode_solvers::RK4_step(), old_ode_solvers::RK4_step(), ode_solver_impl::rk_step(), ode_solver_impl::rkqs(), rotate_Keldysh_matrix(), rotateFlatIndex(), rotateFlatIndex(), round2bfreq(), round2ffreq(), round2Infty(), run_parquet(), rvert< Q >::rvert(), sanity_check(), rvert< Q >::save_expanded(), fullvert< Q >::save_expanded(), GeneralVertex< Q, symmtype, differentiated >::save_expanded(), IntegrandSE< Q, vertType, all_spins, return_type, version >::save_integrand(), IntegrandSE< Q, vertType, all_spins, return_type, version >::save_integrand(), Propagator< Q >::save_propagator_values(), mfRG_record< Q >::save_states(), scalar_map(), multidimensional::scalar_map(), multidimensional::scalar_map(), vec< T >::scalar_map_assign(), multidimensional::multiarray< T, depth >::scalar_map_assign(), SCE_solver(), SelfEnergy< Q >::SelfEnergy(), selfEnergyConverged(), selfEnergyFlowCorrections(), selfEnergyInSOPT(), selfEnergyOneLoopFlow(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_coeffs_from_b(), FrequencyGrid< eliasGrid >::set_essential_parameters(), FrequencyGrid< angularGrid >::set_essential_parameters(), FrequencyGrid< hybridGrid >::set_essential_parameters(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::set_external_arguments_for_parallelization(), fullvert< Q >::set_frequency_grid(), GeneralVertex< Q, symmtype, differentiated >::set_frequency_grid(), State< Q, differentiated >::set_frequency_grid(), fullvert< Q >::set_initializedInterpol(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_initializedInterpol(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::set_initializedInterpol(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::set_initializedInterpol(), GeneralVertex< Q, symmtype, differentiated >::set_initializedInterpol(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::set_initializedInterpol(), rvert< Q >::set_initializedInterpol(), GeneralVertex< Q, symmtype, differentiated >::set_Ir(), rvert< Q >::set_K_symmetryexpanded_to_zero(), IntegrandSE< Q, vertType, all_spins, return_type, version >::set_Keldysh_components_to_be_calculated(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::set_Keldysh_index_i0(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::set_Keldysh_index_i0_left_right(), GeneralVertex< Q, symmtype, differentiated >::set_only_same_channel(), GeneralVertex< Q, symmtype, differentiated >::set_to_zero_in_integrand(), LoopCalculator< Q, vertType, all_spins, version >::set_v_limits(), dataContainerBase< Q, rank >::set_vec(), irreducible< Q >::set_vec(), dataContainerBase< Q, rank >::set_vec(), dataContainerBase< Q, rank >::set_vec(), multidimensional::multiarray< T, depth >::set_vectorized(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::set_VertexFreqGrid(), FrequencyGrid< eliasGrid >::set_w_center(), FrequencyGrid< angularGrid >::set_w_upper(), FrequencyGrid< eliasGrid >::set_w_upper(), FrequencyGrid< hybridGrid >::set_w_upper(), dataContainerBase< Q, rank >::setvert(), dataContainerBase< Q, rank >::setvert(), dataContainerBase< Q, rank >::setvert_vectorized(), sgn(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box(), SelfEnergy< Q >::shrink_freq_box(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box_impl(), sign(), sign_index(), signFlipCorrection_MF(), signFlipCorrection_MF_int(), simpson_rule_3(), simpson_rule_3(), Propagator< Q >::SK(), Propagator< Q >::SK(), Propagator< Q >::SM(), Propagator< Q >::SM_REG3(), Propagator< Q >::SM_REG4(), sopt_state(), sopt_state(), sopt_state_impl(), flowgrid::sq_resubstitution(), flowgrid::sq_substitution(), Propagator< Q >::SR(), Propagator< Q >::SR_REG3(), Propagator< Q >::SR_REG4(), State< Q, differentiated >::State(), subtract(), vec< T >::sum(), GeneralVertex< Q, symmtype, differentiated >::sum_norm(), fullvert< Q >::sum_norm(), susceptibilities_postprocessing(), switch2bosonicFreqs(), switch2bosonicFreqs< 'p'>(), switch2bosonicFreqs< 't'>(), switch2naturalFreqs(), switch2naturalFreqs< 'p'>(), switch2naturalFreqs< 't'>(), switch_channel(), GeneralVertex< Q, symmtype, differentiated >::symmetry_expand(), fullvert< Q >::symmetry_expand(), rvert< Q >::symmetry_expand(), GeneralVertex< Q, symmtype, differentiated >::symmetry_expand_impl(), rvert< Q >::symmetry_reduce(), rvert< Q >::symmetry_reduce(), T1(), T2(), T3(), FrequencyGrid< angularGrid >::t_from_frequency(), FrequencyGrid< hybridGrid >::t_from_frequency(), FrequencyGrid< eliasGrid >::t_from_frequency(), flowgrid::exp_parametrization::t_from_lambda(), flowgrid::log_parametrization::t_from_lambda(), flowgrid::sqrt_parametrization::t_from_lambda(), TC(), test_read_write_data_hdf(), test_read_write_state_hdf(), test_write_dat_rvecs(), test_write_h5_rvecs(), Ti(), utils::to_array(), topt_state(), Tph(), TR(), multidimensional::transform(), transform_vec(), rvert< Q >::transfToR(), unrotate_Keldysh_matrix(), rvert< Q >::update_grid(), SelfEnergy< Q >::update_grid(), SelfEnergy< Q >::update_grid(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::update_grid(), State< Q, differentiated >::update_grid(), fullvert< Q >::update_grid(), GeneralVertex< Q, symmtype, differentiated >::update_grid(), rvert< Q >::update_grid(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::update_grid(), FrequencyGrid< angularGrid >::update_number_of_intervals(), FrequencyGrid< hybridGrid >::update_pos_section_boundaries(), FrequencyGrid< angularGrid >::update_power(), FrequencyGrid< eliasGrid >::update_Wscale(), dataContainerBase< Q, rank >::val(), dataContainerBase< Q, rank >::val(), irreducible< Q >::val(), dataContainerBase< Q, rank >::val_vectorized(), dataContainerBase< Q, rank >::val_vectorized(), rvert< Q >::valsmooth(), rvert< Q >::valsmooth(), SelfEnergy< Q >::valsmooth(), Propagator< Q >::valsmooth(), rvert< Q >::valsmooth_symmetry_expanded(), Propagator< Q >::valsmooth_vectorized(), fullvert< Q >::value(), GeneralVertex< Q, symmtype, differentiated >::value(), fullvert< Q >::value(), rvert< Q >::value(), Bubble< Q >::value(), Bubble< Q >::value(), rvert< Q >::value(), GeneralVertex< Q, symmtype, differentiated >::value_expanded(), Bubble< Q >::value_Matsubara(), fullvert< Q >::value_minus_gamma0_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::value_minus_gamma0_symmetry_expanded(), fullvert< Q >::value_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::value_symmetry_expanded(), rvert< Q >::value_symmetry_expanded(), Bubble< Q >::value_vectorized(), vertexConvergedInLoops(), vertexInFOPT(), VertexInput::VertexInput(), vertexInSOPT(), vertexInTOPT(), vertexOneLoopFlow(), write_dat_rvecs(), hdf5_impl::write_data_to_Dataset(), hdf5_impl::write_data_to_Dataset(), hdf5_impl::write_freqparams_to_hdf_LambdaLayer(), write_h5_rvecs(), Hartree_Solver::write_out_propagators(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K1(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K2(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K2b(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K3(), write_state_to_hdf(), hdf5_impl::write_state_to_hdf_LambdaLayer(), mfRG_stats::write_to_hdf(), write_to_hdf(), write_to_hdf(), write_to_hdf(), write_to_hdf(), write_to_hdf_LambdaLayer(), write_to_hdf_LambdaLayer(), hdf5_impl::write_to_hdf_LambdaLayer_impl(), FrequencyGrid< eliasGrid >::wscale_from_wmax(), wscale_from_wmax_v1(), wscale_from_wmax_v2(), and wscale_from_wmax_v3().
correctionFunctionBubble_REG3_Matsubara_PHS_nondiff()
template<typename Q > auto correctionFunctionBubble_REG3_Matsubara_PHS_nondiff (const double w, const double vmax, const double Lambda, const double Delta)
Correction functions for interaction regulator (REG == 3)
Definition at line 169 of file bubble_corrections.hpp.
{
    Q value;
    if (std::abs(w) < 1e-10) {
        if (Lambda/vmax < 1e-2) {
            value = -0.5 * (
                    vmax / (vmax*vmax + Lambda*Lambda) + 1 / vmax - Lambda*Lambda / (3.*vmax*vmax*vmax)
            );
        }
        else {
            value = -0.5 * (
                    vmax / (vmax*vmax + Lambda*Lambda) + atan(Lambda / vmax) / Lambda
            );
            const double addition = -0.5 * Delta * (
                -1. *(
                    (
                    2. * (
                            (2.* pow(Delta,3))/(Delta + vmax)
                            +
                            (3. * Delta*Delta * Lambda*Lambda + pow(Lambda,4) + 2.* pow(Delta,3) *vmax)
                                /
                                (Lambda*Lambda + vmax*vmax)
                         )
                    )
                    /
                    pow((Delta*Delta + Lambda*Lambda), 2)
                )
                +
                Delta * std::imag((
                    log(-glb_i * Lambda + vmax)/pow((Delta + glb_i * Lambda), 2)
                    +
                    log( glb_i * Lambda + vmax)/pow((glb_i * Delta + Lambda),2)
                    )/Lambda)
                    +
                    std::imag(
                            log(-glb_i * Lambda + vmax)/(Delta * Lambda + glb_i * Lambda*Lambda)
                            - log(glb_i * Lambda + vmax)/(Delta * Lambda - glb_i * Lambda*Lambda)
                            )
                    +
                    std::real(
                            (2. * Delta * ((6. * pow(Delta,3) - 2. * Delta * Lambda * Lambda) * log(Delta + vmax) - pow((Delta - glb_i * Lambda),3) * log(-glb_i * Lambda + vmax)
                    - pow((Delta + glb_i * Lambda),3) * log(glb_i * Lambda + vmax)))
                        /
                        pow((Delta*Delta + Lambda*Lambda),3)
                    )
                    -
                    2. * std::real(log(-glb_i * Lambda + vmax)/pow((Delta + glb_i * Lambda),2))
            );
            value += addition;
        }
    }
    else {
        value = -0.25 * (
                log((pow(vmax+w/2,2) + Lambda*Lambda)/(pow(vmax-w/2,2) + Lambda*Lambda)) / w
                +
                2. * std::real(log(
                        (vmax + w/2 + glb_i * Lambda) / (vmax - w/2 - glb_i * Lambda)) / (w + 2. * glb_i*Lambda))
        );
        double addition = 0.;
        for (int sigma1 : {-1, 1}) {
            for (int sigma2 : {-1, 1}) {
                for (int sigma3 : {-1, 1}) {
                    addition += 4. * Delta * std::real(
                            - log(w + 2*vmax + 2.*glb_i*(Lambda*sigma1)) / (
                                    (w + glb_i*(Lambda*(sigma1-sigma2))) *
                                    (2.*Delta - w - 2.*glb_i*(Lambda*sigma1) + w*sigma3)
                            )
                            + log(-w + 2*vmax + 2.*glb_i*(Lambda*sigma2)) / (
                                    (w + glb_i*(Lambda*(sigma1-sigma2))) *
                                    (2.*Delta + w - 2.*glb_i*(Lambda*sigma2) + w*sigma3)
                            )
                            + 2.*log(2.*Delta + 2*vmax + w*sigma3) / (
                                    (2.*Delta - w - 2.*glb_i*(Lambda*sigma1) + w*sigma3) *
                                    (2.*Delta + w - 2.*glb_i*(Lambda*sigma2) + w*sigma3)
                            )
                    );
                    assert(std::isfinite(addition));
                }
            }
        }
        for (int sigma1 : {-1, 1}) {
            for (int sigma2 : {-1, 1}) {
                addition += 2. * Delta * Delta * std::real(
                        glb_i * log(w + 2*vmax + 2.*glb_i*(Lambda*sigma1)) / (
                                (Delta - glb_i*(Lambda*sigma1))*
                                (Delta - w - glb_i*(Lambda*sigma1)) *
                                (-glb_i*w + Lambda*(sigma1-sigma2))
                        )
                );
                addition += 2. * Delta * Delta * std::real(
                        -
                        log(2.*Delta - w + 2*vmax) / (
                                w *
                                (-Delta + w + glb_i*(Lambda*sigma1))*
                                (Delta - glb_i*(Lambda*sigma2))
                        )
                        -
                        log(2.*Delta + w + 2*vmax) / (
                                w *
                                (Delta + w - glb_i*(Lambda*sigma2))*
                                (Delta - glb_i*(Lambda*sigma1))
                        )
                        +
                        glb_i * log(-w + 2*vmax + 2.*glb_i*(Lambda*sigma2)) / (
                                (Delta - glb_i*(Lambda*sigma2))*
                                (Delta + w - glb_i*(Lambda*sigma2)) *
                                (glb_i*w - Lambda*(sigma1-sigma2))
                        )
                );
                assert(std::isfinite(addition));
            }
        }
        addition *= -0.25*0.5   ;
        value += addition;
    }
    return value;
}
References glb_i(), and log().
correctionFunctionBubble_REG4_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubble_REG4_Matsubara_PHS (double w, double vmin, double vmax, double Delta) -> Q
Definition at line 154 of file bubble_corrections.hpp.
{
    if (std::abs(w) < 1e-20) {
        return - 1. / (vmax + Delta) + 1. / (vmin - Delta) ;
    }
    else {
        return - log((vmax + w*0.5 + Delta) * (vmin - w*0.5 - Delta)
                    /((vmax - w*0.5 + Delta)*(vmin + w*0.5 - Delta))) / w;
    }
}
References log().
correctionFunctionBubbleAT()
template<typename Q > auto correctionFunctionBubbleAT (double w, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 389 of file bubble_corrections.hpp.
{
    Q eps_p = epsilon + Sigma_H;
    if (REG == 2) {
        if (KELDYSH) {
            return correctionFunctionBubbleAT_REG2_Keldysh(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
        }
        else {
            if (PARTICLE_HOLE_SYMMETRY) {
                return correctionFunctionBubbleAT_REG2_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
            }
            else {
                return correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
            }
        }
    }
    else if (REG == 3) {// TODO(medium): Make this more readable!
        if (PARTICLE_HOLE_SYMMETRY) {
            return correctionFunctionBubbleAT_REG3_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
        }
        else std::runtime_error("Bubble correction not implemented for omega cutoff yet.");
    }
    else if (REG == 4) {
        if (PARTICLE_HOLE_SYMMETRY) {
            return correctionFunctionBubbleAT_REG4_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
        }
        else std::runtime_error("Bubble correction not implemented for interaction cutoff yet.");
    }
    else {
        return 0.;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), correctionFunctionBubbleAT_REG2_Keldysh(), correctionFunctionBubbleAT_REG2_Matsubara_NoPHS(), correctionFunctionBubbleAT_REG2_Matsubara_PHS(), correctionFunctionBubbleAT_REG3_Matsubara_PHS(), correctionFunctionBubbleAT_REG4_Matsubara_PHS(), KELDYSH, PARTICLE_HOLE_SYMMETRY, and REG.
Referenced by correctionFunctionBubble().
correctionFunctionBubbleAT_REG2_Keldysh() [1/2]
template<> auto correctionFunctionBubbleAT_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 4 of file bubble_corrections.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleAT_REG2_Keldysh() [2/2]
template<typename Q > auto correctionFunctionBubbleAT_REG2_Keldysh (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Helper function for computing the analytical result for the asymptotic tails of the bubble integral in the a and t channel, assuming the self-energy to be decayed to the Hartree value. See the function asymp_corrections_bubble below.
Parameters
w : Bosonic transfer frequency
vmin : Lower limit of the numerically evaluated integral
vmax : Upper limit of the numerically evaluated integral
Sigma_H : Hartree self-energy
Delta : Hybridization (~ flow parameter) at which the bubble is evaluated
eta_1 : +1/-1 if first propagator in the bubble is retarded/advanced
eta_2 : +1/-1 if second propagator in the bubble is retarded/advanced
Returns
: Analytical result of the integrated tails
Definition at line 25 of file bubble_corrections.hpp.
{
    if (diff) return 0.;
    else {
        if (w == 0. && eta_1 == eta_2)
            return 1. / (vmax - eps_p + eta_1 * glb_i * Delta)
                   + 1. / (std::abs(vmin) + eps_p - eta_1 * glb_i * Delta);
        else
            return 1. / (-w + (eta_1 - eta_2) * glb_i * Delta)
                   * log(((vmax - w / 2. - eps_p + eta_1 * glb_i * Delta) *
                          (std::abs(vmin) - w / 2. + eps_p - eta_2 * glb_i * Delta))
                         / ((vmax + w / 2. - eps_p + eta_2 * glb_i * Delta) *
                            (std::abs(vmin) + w / 2. + eps_p - eta_1 * glb_i * Delta)));
    }
}
References glb_i(), and log().
Referenced by correctionFunctionBubbleAT().
correctionFunctionBubbleAT_REG2_Matsubara_NoPHS() [1/2]
template<> auto correctionFunctionBubbleAT_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 13 of file bubble_corrections.c++.
{
    utils::print("Error! Computations without particle hole symmetry require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleAT_REG2_Matsubara_NoPHS() [2/2]
template<typename Q > auto correctionFunctionBubbleAT_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 73 of file bubble_corrections.hpp.
{
    Q val;
    if (diff){
        val = 1. / 2. * (1. / (pow(-vmin - glb_i * eps_p + Delta, 2) - pow(w / 2., 2))
                          + 1. / (pow(vmax + glb_i * eps_p + Delta, 2) - pow(w / 2., 2)));
    }
    else{
        if (w == 0.) {
            val = -1. / (vmax + glb_i * eps_p + Delta)
                   + 1. / (vmin + glb_i * eps_p - Delta);
        }
        else {
            val = 1. / w *
                   log(((-vmin - w / 2. - glb_i * eps_p + Delta) * (vmax - w / 2. + glb_i * eps_p + Delta))
                       / ((-vmin + w / 2. - glb_i * eps_p + Delta) *
                          (vmax + w / 2. + glb_i * eps_p + Delta)));
        }
    }
    my_isfinite(val);
    return val;
}
References glb_i(), log(), and my_isfinite().
Referenced by correctionFunctionBubbleAT().
correctionFunctionBubbleAT_REG2_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubbleAT_REG2_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 48 of file bubble_corrections.hpp.
{
    Q val;
    double x;
    if (diff){
        val = 1. / 2. * (1. / (pow(-vmin + Delta, 2) - pow(w / 2., 2))
                          + 1. / (pow(vmax + Delta, 2) - pow(w / 2., 2)));
    }
    else{
        if (w == 0.) {
            val = -1. / (vmax + Delta)
                   + 1. / (vmin - Delta);
        }
        else {
            x = ((-vmin - w / 2. + Delta) * (vmax - w / 2. + Delta))
                       / ((-vmin + w / 2. + Delta) * (vmax + w / 2. + Delta));
            val = 1. / w * log(x);
        }
    }
    my_isfinite(val);
    return val;
}
References log(), and my_isfinite().
Referenced by correctionFunctionBubbleAT(), and correctionFunctionBubbleP_REG2_Matsubara_PHS().
correctionFunctionBubbleAT_REG3_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubbleAT_REG3_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 327 of file bubble_corrections.hpp.
{
    Q val;
    if (diff) {
        val = correctionFunctionBubble_REG3_Matsubara_PHS_diff<Q>(w, vmax, Lambda, Delta) + correctionFunctionBubble_REG3_Matsubara_PHS_diff<Q>(w, -vmin, Lambda, Delta);
    }
    else {
        val = correctionFunctionBubble_REG3_Matsubara_PHS_nondiff<Q>(w, vmax, Lambda, Delta) + correctionFunctionBubble_REG3_Matsubara_PHS_nondiff<Q>(w, -vmin, Lambda, Delta);
    }
    my_isfinite(val);
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
Referenced by correctionFunctionBubbleAT().
correctionFunctionBubbleAT_REG4_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubbleAT_REG4_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Correction functions for interaction regulator (REG == 4)
Definition at line 356 of file bubble_corrections.hpp.
{
    Q val;
    if (diff) {
        val = 2 * Lambda * correctionFunctionBubble_REG4_Matsubara_PHS<Q>(w, vmin, vmax, Delta);
    }
    else {
        val = Lambda * Lambda * correctionFunctionBubble_REG4_Matsubara_PHS<Q>(w, vmin, vmax, Delta);
    }
    my_isfinite(val);
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_isfinite().
Referenced by correctionFunctionBubbleAT().
correctionFunctionBubbleP()
template<typename Q > auto correctionFunctionBubbleP (double w, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 424 of file bubble_corrections.hpp.
{
    Q eps_p = epsilon + Sigma_H;
    if (REG==2) {
        if (KELDYSH) {
            return correctionFunctionBubbleP_REG2_Keldysh(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
        }
        else {
            if (PARTICLE_HOLE_SYMMETRY) {
                return correctionFunctionBubbleP_REG2_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
            }
            else {
                return correctionFunctionBubbleP_REG2_Matsubara_NoPHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
            }
        }
    }
    else if (REG==3) {
        if (PARTICLE_HOLE_SYMMETRY) {
            return correctionFunctionBubbleP_REG3_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
        }
        else std::runtime_error("Bubble correction not implemented for omega cutoff yet.");
    }
    else if (REG == 4) {
        if (PARTICLE_HOLE_SYMMETRY) {
            return correctionFunctionBubbleP_REG4_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
        }
        else std::runtime_error("Bubble correction not implemented for interaction cutoff yet.");
    }
    else {
        return 0.;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), correctionFunctionBubbleP_REG2_Keldysh(), correctionFunctionBubbleP_REG2_Matsubara_NoPHS(), correctionFunctionBubbleP_REG2_Matsubara_PHS(), correctionFunctionBubbleP_REG3_Matsubara_PHS(), correctionFunctionBubbleP_REG4_Matsubara_PHS(), KELDYSH, PARTICLE_HOLE_SYMMETRY, and REG.
Referenced by correctionFunctionBubble().
correctionFunctionBubbleP_REG2_Keldysh() [1/2]
template<> auto correctionFunctionBubbleP_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 22 of file bubble_corrections.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleP_REG2_Keldysh() [2/2]
template<typename Q > auto correctionFunctionBubbleP_REG2_Keldysh (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 102 of file bubble_corrections.hpp.
{
    if (diff) return 0.;
    else {
        if (w == 2. * eps_p && eta_1 == -eta_2)
            return -1. / (vmax + eta_1 * glb_i * Delta) - 1. / (std::abs(vmin) - eta_1 * glb_i * Delta);
        else
            return -1. / (w - 2. * eps_p + (eta_1 + eta_2) * glb_i * Delta)
                   * log(((vmax + w / 2. - eps_p + eta_1 * glb_i * Delta) *
                          (std::abs(vmin) + w / 2. - eps_p + eta_2 * glb_i * Delta))
                         / ((vmax - w / 2. + eps_p - eta_2 * glb_i * Delta) *
                            (std::abs(vmin) - w / 2. + eps_p - eta_1 * glb_i * Delta)));
    }
}
References glb_i(), and log().
Referenced by correctionFunctionBubbleP().
correctionFunctionBubbleP_REG2_Matsubara_NoPHS() [1/2]
template<> auto correctionFunctionBubbleP_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 31 of file bubble_corrections.c++.
{
    utils::print("Error! Computations without particle hole symmetry require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleP_REG2_Matsubara_NoPHS() [2/2]
template<typename Q > auto correctionFunctionBubbleP_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 130 of file bubble_corrections.hpp.
{
    if (diff){
        return 1. / 2. * (1. / (pow(-vmin + Delta, 2) - pow(w / 2. + glb_i * eps_p, 2))
                          + 1. / (pow(vmax + Delta, 2) - pow(w / 2. + glb_i * eps_p, 2)));
    }
    else{
        if (eps_p == 0. and w == 0.) {
            return +1. / (vmax + Delta) - 1. / (vmin - Delta);
        } else {
            return 1. / (w + 2. * glb_i * eps_p)
                   * log(((-vmin + w / 2. + glb_i * eps_p + Delta) * (vmax + w / 2. + glb_i * eps_p + Delta))
                         /
                         ((-vmin - w / 2. - glb_i * eps_p + Delta) * (vmax - w / 2. - glb_i * eps_p + Delta)));
        }
    }
}
References glb_i(), and log().
Referenced by correctionFunctionBubbleP().
correctionFunctionBubbleP_REG2_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubbleP_REG2_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 123 of file bubble_corrections.hpp.
{
    return -correctionFunctionBubbleAT_REG2_Matsubara_PHS(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
}
References correctionFunctionBubbleAT_REG2_Matsubara_PHS().
Referenced by correctionFunctionBubbleP().
correctionFunctionBubbleP_REG3_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubbleP_REG3_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 343 of file bubble_corrections.hpp.
{
    Q val;
    val = - correctionFunctionBubbleAT_REG3_Matsubara_PHS<Q>(w, vmin, vmax, eps_p, Delta, Lambda, eta_1, eta_2, diff);
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by correctionFunctionBubbleP().
correctionFunctionBubbleP_REG4_Matsubara_PHS()
template<typename Q > auto correctionFunctionBubbleP_REG4_Matsubara_PHS (double w, double vmin, double vmax, Q eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> Q
Definition at line 372 of file bubble_corrections.hpp.
{
    Q val;
    if (diff) {
        val = - 2 * Lambda * correctionFunctionBubble_REG4_Matsubara_PHS<Q>(w, vmin, vmax, Delta);
    }
    else {
        val = - Lambda * Lambda * correctionFunctionBubble_REG4_Matsubara_PHS<Q>(w, vmin, vmax, Delta);
    }
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by correctionFunctionBubbleP().