SIAM-Keldysh-mfRG: integrator.hpp File Reference
integrator.hpp File Reference
#include <numeric>
#include <type_traits>
#include "../data_structures.hpp"
#include "../parameters/master_parameters.hpp"
#include <gsl/gsl_integration.h>
#include <gsl/gsl_errno.h>
#include "old_integrators.hpp"
#include "integrator_NR.hpp"
#include "../utilities/util.hpp"
Functions
template<typename Integrand >
auto f_real (double x, void *params) -> double
template<typename Integrand >
auto f_imag (double x, void *params) -> double
void handler (const char *reason, const char *file, int line, int gsl_errno)
auto integrator_gsl_qag_helper (gsl_function &F, double a, double b, int Nmax) -> double
auto integrator_gsl_qagp_helper (gsl_function &F, double *pts, size_t npts, int Nmax) -> double
auto integrator_gsl_qagiu_helper (gsl_function &F, double a, int Nmax) -> double
auto integrator_gsl_qagil_helper (gsl_function &F, double a, int Nmax) -> double
template<typename Q , typename Integrand >
auto integrator_gsl_qag_tails (Integrand &integrand, double a, double b, int Nmax) -> Q
template<typename Q , typename Integrand >
auto integrator_gsl_qag_v2 (Integrand &integrand, double a, double b, int Nmax, const bool isinf) -> Q
template<typename Q , typename Integrand >
auto integrator_gsl_qagp_v2 (Integrand &integrand, double *pts, int npts, int Nmax, const bool isinf) -> Q
template<typename Q , typename Integrand >
auto integrator_gsl (Integrand &integrand, double a, double b, double w1_in, double w2_in, int Nmax) -> Q
template<typename Q , typename Integrand >
auto integrator_gsl (Integrand &integrand, const vec< vec< double > > &intervals, const size_t num_intervals, const int Nmax, const bool isinf=false) -> Q
template<typename Q , typename Integrand >
auto integrator (Integrand &integrand, double a, double b) -> Q
— WRAPPER FUNCTIONS: INTERFACE FOR ACCESSING THE INTEGRATOR IN BUBBLES/LOOP — ///
template<typename Q , typename Integrand >
auto integrator (Integrand &integrand, double a, double b, double w) -> Q
template<typename Q , typename Integrand >
auto integrator (Integrand &integrand, double a, double b, double w1, double w2) -> Q
template<typename Integrand >
auto integrator (Integrand &integrand, double a, double b, double w1, double w2, double Delta, const bool isinf=false) -> std::result_of_t< Integrand(double)>
template<typename Integrand >
auto integrator (Integrand &integrand, vec< vec< double > > &intervals, const my_index_t num_intervals, const bool isinf=false) -> std::result_of_t< Integrand(double)>
template<typename Integrand >
auto integrator_onlyTails (Integrand &integrand, const double vmin, const double vmax) -> std::result_of_t< Integrand(double)>
template<typename Integrand >
auto integrator_Matsubara_T0 (Integrand &integrand, const double vmin, const double vmax, double w_half, const vec< double > &freqs, const double Delta, const bool isinf=false) -> std::result_of_t< Integrand(double)>
template<typename Q , typename Integrand >
auto matsubarasum (const Integrand &integrand, const int Nmin, const int Nmax, const int N_tresh=60, int balance_fac=2, double reltol=1e-5, double abstol=1e-7) -> Q
template<int spin, int channel, typename Integrand >
auto matsubarasum_vectorized (const Integrand &integrand, const int Nmin_v, const int Nmax_v, const int Nmin_sum, const int Nmax_sum, const int Nmin_vp, const int Nmax_vp) -> Eigen::Matrix< std::result_of_t< Integrand(freqType)>, Eigen::Dynamic, Eigen::Dynamic >
Function Documentation
f_imag()
template<typename Integrand > auto f_imag (double x, void * params) -> double
Definition at line 25 of file integrator.hpp.
{
    Integrand integrand = *(Integrand*) params;
    double f = myimag(integrand(x));
    return f;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and myimag().
f_real()
template<typename Integrand > auto f_real (double x, void * params) -> double
Definition at line 16 of file integrator.hpp.
{
    Integrand integrand = *(Integrand*) params;
    double f_real = myreal(integrand(x));
    return f_real;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), f_real(), and myreal().
Referenced by f_real().
handler()
void handler (const char * reason, const char * file, int line, int gsl_errno)
Definition at line 3 of file integrator.c++.
{
    //print(reason, true);
}
Referenced by integrator_gsl(), integrator_gsl(), integrator_gsl_qag_helper(), integrator_gsl_qagil_helper(), integrator_gsl_qagiu_helper(), and integrator_gsl_qagp_helper().
integrator() [1/5]
template<typename Q , typename Integrand > auto integrator (Integrand & integrand, double a, double b) -> Q
— WRAPPER FUNCTIONS: INTERFACE FOR ACCESSING THE INTEGRATOR IN BUBBLES/LOOP — ///
Definition at line 318 of file integrator.hpp.
{
    Adapt<Integrand> adaptor(integrator_tol, integrand);
    return adaptor.integrate(a, b);
}
References Adapt< Integrand, Q >::integrate(), and integrator_tol.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value(), integrator_Matsubara_T0(), and sum_rule_spectrum().
integrator() [2/5]
template<typename Q , typename Integrand > auto integrator (Integrand & integrand, double a, double b, double w) -> Q
Definition at line 324 of file integrator.hpp.
{
    Adapt<Integrand> adaptor(integrator_tol, integrand);
    return adaptor.integrate(a, b);
}
References Adapt< Integrand, Q >::integrate(), and integrator_tol.
integrator() [3/5]
template<typename Q , typename Integrand > auto integrator (Integrand & integrand, double a, double b, double w1, double w2) -> Q
wrapper function, used for bubbles.
Parameters
integrand
a : lower limit for integration
b : upper limit for integration
w1 : unused
w2 : unused
Definition at line 337 of file integrator.hpp.
{
    Adapt<Integrand> adaptor(integrator_tol, integrand);
    return adaptor.integrate(a, b);
}
References Adapt< Integrand, Q >::integrate(), and integrator_tol.
integrator() [4/5]
template<typename Integrand > auto integrator (Integrand & integrand, double a, double b, double w1, double w2, double Delta, const bool isinf = false) -> std::result_of_t<Integrand(double)>
Wrapper function for bubbles and loops, splitting the integration domain along difficult features.
Parameters
a : lower limit for integration
b : upper limit for integration
w1 : first frequency where features occur
w2 : second frequency where features occur
Delta : with of window around the features which should be integrated separately (to be set by hybridization strength)
Definition at line 350 of file integrator.hpp.
{
    using return_type = std::result_of_t<Integrand(double)>;
    // define points at which to split the integrals (including lower and upper integration limits)
    rvec intersections{a, w1 - Delta, w1 + Delta, w2 - Delta, w2 + Delta, b};
    std::sort(intersections.begin(), intersections.end()); // sort the intersection points to get correct intervals
    return_type result = myzero<return_type>(); // initialize results
    // integrate intervals of with 2*Delta around the features at w1, w2
    Adapt<Integrand> adaptor_peaks(integrator_tol, integrand);
    result += adaptor_peaks.integrate(intersections[3], intersections[4]);
    result += adaptor_peaks.integrate(intersections[1], intersections[2]);
    // integrate the tails and the interval between the features, with increased tolerance
    Adapt<Integrand> adaptor_tails(integrator_tol * 10, integrand);
    result += adaptor_tails.integrate(intersections[0], intersections[1]);
    result += adaptor_tails.integrate(intersections[2], intersections[3]);
    result += adaptor_tails.integrate(intersections[4], intersections[5]);
    if (isinf) {
        Adapt_semiInfinitLower<Integrand> adapt_il(integrator_tol, integrand, intersections[0]);
        Adapt_semiInfinitUpper<Integrand> adapt_iu(integrator_tol, integrand, intersections[5]);
        result += adapt_il.integrate();
        result += adapt_iu.integrate();
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integrator_tol.
integrator() [5/5]
template<typename Integrand > auto integrator (Integrand & integrand, vec< vec< double > > & intervals, const my_index_t num_intervals, const bool isinf = false) -> std::result_of_t<Integrand(double)>
wrapper function, used for bubbles.
Parameters
integrand
intervals : list of intervals (lower and upper limit for integrations)
num_intervals : number of intervals
Definition at line 383 of file integrator.hpp.
{
    using return_type = std::result_of_t<Integrand(double)>;
    Adapt<Integrand> adaptor(integrator_tol, integrand);
    vec<return_type> result = vec<return_type>(num_intervals);
    assert(result.size() == num_intervals);
    for (my_index_t i = 0; i < num_intervals; i++){
        if (intervals[i][0] < intervals[i][1]) result[i] = adaptor.integrate(intervals[i][0], intervals[i][1]);
    }
    if (isinf) {
        Adapt_semiInfinitLower<Integrand> adapt_il(integrator_tol, integrand, intervals[0][0]);
        Adapt_semiInfinitUpper<Integrand> adapt_iu(integrator_tol, integrand, intervals[num_intervals-1][1]);
        result[0] += adapt_il.integrate();
        result[0] += adapt_iu.integrate();
    }
    assert(result.size() == num_intervals);
    const return_type val = result.sum();
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Adapt< Integrand, Q >::integrate(), and integrator_tol.
integrator_gsl() [1/2]
template<typename Q , typename Integrand > auto integrator_gsl (Integrand & integrand, const vec< vec< double > > & intervals, const size_t num_intervals, const int Nmax, const bool isinf = false) -> Q
Definition at line 222 of file integrator.hpp.
{
    if constexpr (std::is_same<Q, std::complex<double>>::value) {
        gsl_integration_workspace *W_real = gsl_integration_workspace_alloc(Nmax);
        gsl_function F_real;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        double result_real{}, error_real{};
        gsl_set_error_handler(handler);
        double result_real_temp{}, error_real_temp{};
        if (isinf) {
            gsl_integration_qagil(&F_real, intervals[0][0], 0, integrator_tol, Nmax, W_real, &result_real, &error_real);
            gsl_integration_qagiu(&F_real, intervals[num_intervals - 1][1], 0, integrator_tol, Nmax, W_real,
                                  &result_real_temp, &error_real_temp);
            result_real += result_real_temp;
            error_real += error_real_temp;
        }
        for (int i = 0; i < num_intervals; i++) {
            result_real_temp = 0.;
            error_real_temp = 0.;
            if (intervals[i][0] < intervals[i][1])
                gsl_integration_qag(&F_real, intervals[i][0], intervals[i][1], 0, integrator_tol, Nmax, 1, W_real,
                                    &result_real_temp, &error_real_temp);
            result_real += result_real_temp;
            error_real += error_real_temp;
        }
        gsl_integration_workspace_free(W_real);
        gsl_integration_workspace *W_imag = gsl_integration_workspace_alloc(Nmax);
        gsl_function F_imag;
        F_imag.function = &f_imag<Integrand>;
        F_imag.params = &integrand;
        double result_imag{}, error_imag{};
        double result_imag_temp{}, error_imag_temp{};
        if (isinf) {
            gsl_integration_qagil(&F_imag, intervals[0][0], 0, integrator_tol, Nmax, W_imag, &result_imag, &error_imag);
            gsl_integration_qagiu(&F_imag, intervals[num_intervals - 1][1], 0, integrator_tol, Nmax, W_imag,
                                  &result_imag_temp, &error_imag_temp);
            result_imag += result_imag_temp;
            error_imag += error_imag_temp;
        }
        for (int i = 0; i < num_intervals; i++) {
            result_imag_temp = 0.;
            error_imag_temp = 0.;
            if (intervals[i][0] < intervals[i][1])
                gsl_integration_qag(&F_imag, intervals[i][0], intervals[i][1], 0, integrator_tol, Nmax, 1, W_imag,
                                    &result_imag_temp, &error_imag_temp);
            result_imag += result_imag_temp;
            error_imag += error_imag_temp;
        }
        gsl_integration_workspace_free(W_imag);
        return result_real + glb_i * result_imag;
    }
    else {
        gsl_integration_workspace *W_real = gsl_integration_workspace_alloc(Nmax);
        gsl_function F_real;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        double result_real = 0., error_real = 0.;
        gsl_set_error_handler(handler);
        double result_real_temp{}, error_real_temp{};
        if (isinf) {
            gsl_integration_qagil(&F_real, intervals[0][0], 0, integrator_tol, Nmax, W_real, &result_real, &error_real);
            gsl_integration_qagiu(&F_real, intervals[num_intervals - 1][1], 0, integrator_tol, Nmax, W_real,
                                  &result_real_temp, &error_real_temp);
            result_real += result_real_temp;
            error_real += error_real_temp;
        }
        vec<Q> result = vec<Q>(num_intervals);
        for (int i = 0; i < num_intervals; i++) {
            error_real_temp = 0.;
            if (intervals[i][0] < intervals[i][1])
                gsl_integration_qag(&F_real, intervals[i][0], intervals[i][1], 0., integrator_tol, Nmax, 1, W_real,
                                    &(result[i]), &error_real_temp);
            error_real += error_real_temp;
        }
        gsl_integration_workspace_free(W_real);
        result_real += result.sum();
        return result_real;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), handler(), and integrator_tol.
integrator_gsl() [2/2]
template<typename Q , typename Integrand > auto integrator_gsl (Integrand & integrand, double a, double b, double w1_in, double w2_in, int Nmax) -> Q
Definition at line 174 of file integrator.hpp.
{
    if constexpr (std::is_same<Q, std::complex<double>>::value){
        gsl_integration_workspace* W_real = gsl_integration_workspace_alloc(Nmax);
        gsl_integration_workspace* W_imag = gsl_integration_workspace_alloc(Nmax);
        gsl_function F_real;
        gsl_function F_imag;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        F_imag.function = &f_imag<Integrand>;
        F_imag.params = &integrand;
        double result_real, error_real;
        double result_imag, error_imag;
        gsl_set_error_handler(handler);
        gsl_integration_qag(&F_real, a, b, 0, integrator_tol, Nmax, 1, W_real, &result_real, &error_real);
        gsl_integration_qag(&F_imag, a, b, 0, integrator_tol, Nmax, 1, W_imag, &result_imag, &error_imag);
        gsl_integration_workspace_free(W_real);
        gsl_integration_workspace_free(W_imag);
        return result_real + glb_i*result_imag;
    }
    else{
        gsl_integration_workspace* W_real = gsl_integration_workspace_alloc(Nmax);
        gsl_function F_real;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        double result_real, error_real;
        gsl_set_error_handler(handler);
        gsl_integration_qag(&F_real, a, b, 0, integrator_tol, Nmax, 1, W_real, &result_real, &error_real);
        gsl_integration_workspace_free(W_real);
        return result_real;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), handler(), and integrator_tol.
integrator_gsl_qag_helper()
auto integrator_gsl_qag_helper (gsl_function & F, double a, double b, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 10 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    int key = 1; // 1: GSL_INTEG_GAUSS15
    // 2: GSL_INTEG_GAUSS21
    // 3: GSL_INTEG_GAUSS31
    // 4: GSL_INTEG_GAUSS41
    // 5: GSL_INTEG_GAUSS51
    // 6: GSL_INTEG_GAUSS61
    gsl_integration_qag(&F, a, b, epsabs, integrator_tol, Nmax, key, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qag_v2().
integrator_gsl_qag_tails()
template<typename Q , typename Integrand > auto integrator_gsl_qag_tails (Integrand & integrand, double a, double b, int Nmax) -> Q
Definition at line 49 of file integrator.hpp.
{
    if constexpr (std::is_same<Q,comp>::value){
        gsl_function F_real;
        gsl_function F_imag;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        F_imag.function = &f_imag<Integrand>;
        F_imag.params = &integrand;
        double result_real = 0.;
        double result_imag = 0.;
        result_real += integrator_gsl_qagil_helper(F_real, a, Nmax);
        result_real += integrator_gsl_qagiu_helper(F_real, b, Nmax);
        result_imag += integrator_gsl_qagil_helper(F_imag, a, Nmax);
        result_imag += integrator_gsl_qagiu_helper(F_imag, b, Nmax);
        return result_real + glb_i*result_imag;
    }
    else{
        gsl_function F_real;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        double result_real = 0.;
            result_real += integrator_gsl_qagil_helper(F_real, a, Nmax);
            result_real += integrator_gsl_qagiu_helper(F_real, b, Nmax);
        return result_real;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), integrator_gsl_qagil_helper(), and integrator_gsl_qagiu_helper().
integrator_gsl_qag_v2()
template<typename Q , typename Integrand > auto integrator_gsl_qag_v2 (Integrand & integrand, double a, double b, int Nmax, const bool isinf) -> Q
Definition at line 89 of file integrator.hpp.
{
    if constexpr (std::is_same<Q,comp>::value){
        gsl_function F_real;
        gsl_function F_imag;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        F_imag.function = &f_imag<Integrand>;
        F_imag.params = &integrand;
        double result_real = integrator_gsl_qag_helper(F_real, a, b, Nmax);
        double result_imag = integrator_gsl_qag_helper(F_imag, a, b, Nmax);
        if (isinf) {
            result_real += integrator_gsl_qagil_helper(F_real, a, Nmax);
            result_real += integrator_gsl_qagiu_helper(F_real, b, Nmax);
            result_imag += integrator_gsl_qagil_helper(F_imag, a, Nmax);
            result_imag += integrator_gsl_qagiu_helper(F_imag, b, Nmax);
        }
        return result_real + glb_i*result_imag;
    }
    else{
        gsl_function F_real;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        double result_real = integrator_gsl_qag_helper(F_real, a, b, Nmax);
        if (isinf) {
            result_real += integrator_gsl_qagil_helper(F_real, a, Nmax);
            result_real += integrator_gsl_qagiu_helper(F_real, b, Nmax);
        }
        return result_real;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), integrator_gsl_qag_helper(), integrator_gsl_qagil_helper(), and integrator_gsl_qagiu_helper().
integrator_gsl_qagil_helper()
auto integrator_gsl_qagil_helper (gsl_function & F, double a, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 65 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    gsl_integration_qagil(&F, a, epsabs, integrator_tol, Nmax, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qag_tails(), integrator_gsl_qag_v2(), and integrator_gsl_qagp_v2().
integrator_gsl_qagiu_helper()
auto integrator_gsl_qagiu_helper (gsl_function & F, double a, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 48 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    //gsl_integration_qagil(&F_real, intervals[0][0], 0, integrator_tol, Nmax, W_real, &result_real, &error_real);
    gsl_integration_qagiu(&F, a, epsabs, integrator_tol, Nmax, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qag_tails(), integrator_gsl_qag_v2(), and integrator_gsl_qagp_v2().
integrator_gsl_qagp_helper()
auto integrator_gsl_qagp_helper (gsl_function & F, double * pts, size_t npts, int Nmax) -> double
If needed: more information can be extracted, e.g. error, number of interval subdivisions
Definition at line 32 of file integrator.c++.
{
    gsl_integration_workspace* W = gsl_integration_workspace_alloc(Nmax);
    double result, error;
    gsl_set_error_handler(handler);
    const double epsabs = 0.;
    gsl_integration_qagp(&F, pts, npts, epsabs, integrator_tol, Nmax, W, &result, &error);
    gsl_integration_workspace_free(W);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), handler(), and integrator_tol.
Referenced by integrator_gsl_qagp_v2().
integrator_gsl_qagp_v2()
template<typename Q , typename Integrand > auto integrator_gsl_qagp_v2 (Integrand & integrand, double * pts, int npts, int Nmax, const bool isinf) -> Q
Definition at line 130 of file integrator.hpp.
{
    if constexpr (std::is_same<Q,comp>::value){
        gsl_function F_real;
        gsl_function F_imag;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        F_imag.function = &f_imag<Integrand>;
        F_imag.params = &integrand;
        double result_real = integrator_gsl_qagp_helper(F_real, pts, npts, Nmax);
        double result_imag = integrator_gsl_qagp_helper(F_imag, pts, npts, Nmax);
        if (isinf) {
            result_real += integrator_gsl_qagil_helper(F_real, pts[0]       , Nmax);
            result_real += integrator_gsl_qagiu_helper(F_real, pts[npts - 1], Nmax);
            result_imag += integrator_gsl_qagil_helper(F_imag, pts[0]       , Nmax);
            result_imag += integrator_gsl_qagiu_helper(F_imag, pts[npts - 1], Nmax);
        }
        return result_real + glb_i*result_imag;
    }
    else{
        gsl_function F_real;
        F_real.function = &f_real<Integrand>;
        F_real.params = &integrand;
        double result_real = integrator_gsl_qagp_helper(F_real, pts, npts, Nmax);
        if (isinf) {
            result_real += integrator_gsl_qagil_helper(F_real, pts[0]       , Nmax);
            result_real += integrator_gsl_qagiu_helper(F_real, pts[npts - 1], Nmax);
        }
        return result_real;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), integrator_gsl_qagil_helper(), integrator_gsl_qagiu_helper(), and integrator_gsl_qagp_helper().
integrator_Matsubara_T0()
template<typename Integrand > auto integrator_Matsubara_T0 (Integrand & integrand, const double vmin, const double vmax, double w_half, const vec< double > & freqs, const double Delta, const bool isinf = false) -> std::result_of_t<Integrand(double)>
wrapper function, used for bubbles. Splits up integration interval in suitable pieces for Matsubara T=0
Parameters
integrand
intervals : list of intervals (lower and upper limit for integrations)
num_intervals : number of intervals
Definition at line 425 of file integrator.hpp.
{
    double tol = 1e-10;
    const int num_freqs = freqs.size();
    // The idea is to split up the interval and thereby make sure that the integrator recognizes all the relevant features of the integrand.
    vec<double> intersections;
    size_t num_intervals_max;
    if (w_half < tol) {
        w_half = 0.;
        intersections = {w_half, vmin, vmax};
        num_intervals_max = num_freqs * 2 + 2;
    }
    else {
        intersections = {-w_half, w_half, vmin, vmax};
        num_intervals_max = num_freqs * 2 + 3;
    }
    for (int i = 0; i<num_freqs; i++){
        for (int sign1:{-1,1}) {
            //for (int sign2:{-1,1}) {
            //    intersections.push_back(sign1 * freqs[i] + sign2 * Delta);
            //}
            intersections.push_back(sign1 * freqs[i]);
        }
    }
    std::sort(intersections.begin(), intersections.end());
    int num_intervals = 0;
    vec<vec<double>> intervals(num_freqs*2 + 3, {1.,-1.});
    for (size_t i = 0; i < num_intervals_max; i++) {
        if (intersections[i] != intersections[i+1]) {
            intervals[num_intervals] = {intersections[i], intersections[i + 1]};
            if (std::abs(std::abs(intersections[i]) - w_half) < tol) {
                intervals[num_intervals][0] += tol;
                if (num_intervals > 0) intervals[num_intervals - 1][1] -= tol;
            }
            num_intervals++;
        }
    }
    if (std::abs(std::abs(intervals[num_intervals-1][1]) - w_half) < tol) {
        intervals[num_intervals-1][1] -= tol;
    }
/*
    size_t num_intervals_max;
    vec<vec<double>> intervals;
    if( -w_half+tol < w_half-tol){
        intervals = {{vmin, -w_half-tol}, {-w_half+tol, w_half-tol}, {w_half+tol, vmax}};
        num_intervals_max = 3;
    }
    else {
        intervals = {{vmin, -w_half-tol}, {w_half+tol, vmax}};
        num_intervals_max = 2;
    }
*/
    return integrator(integrand, intervals, num_intervals, isinf);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integrator().
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value(), Hartree_Solver::compute_filling_oneshot(), LoopCalculator< Q, vertType, all_spins, version >::compute_Keldysh(), and LoopCalculator< Q, vertType, all_spins, version >::compute_Matsubara_zeroT().
integrator_onlyTails()
template<typename Integrand > auto integrator_onlyTails (Integrand & integrand, const double vmin, const double vmax) -> std::result_of_t<Integrand(double)>
wrapper function, used for bubbles.
Parameters
integrand
intervals : list of intervals (lower and upper limit for integrations)
num_intervals : number of intervals
Definition at line 408 of file integrator.hpp.
{
    using return_type = std::result_of_t<Integrand(double)>;
    Adapt_semiInfinitLower<Integrand> adapt_il(integrator_tol, integrand, vmin);
    Adapt_semiInfinitUpper<Integrand> adapt_iu(integrator_tol, integrand, vmax);
    const return_type val = adapt_il.integrate() + adapt_iu.integrate();
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integrator_tol.
Referenced by asymp_corrections_bubble_via_quadrature().
matsubarasum()
template<typename Q , typename Integrand > auto matsubarasum (const Integrand & integrand, const int Nmin, const int Nmax, const int N_tresh = 60, int balance_fac = 2, double reltol = 1e-5, double abstol = 1e-7) -> Q
Definition at line 490 of file integrator.hpp.
{
    int N = Nmax - Nmin  + 1;
    vec<Q> values(N);
    Q result = 0;
    freqType vpp;
    for (int i = 0; i < N; i++) {
        vpp = ((Nmin + i)*2 + 1);
        //values[i] = integrand(vpp);
        result += integrand(vpp);
    }
    return result;// values.sum();
    /*
    if (N_tresh * balance_fac >= N) {
        //cout << "Direct SUMMATION on interval[" << Nmin << ", " << Nmax << "] of length " << N <<  "!!! \n";
        vec<Q> values(N);
        double vpp;
        for (int i = 0; i < N; i++) {
            vpp = (2*Nmin+1) * (M_PI * glb_T) + i * freq_step;
            values[i] = integrand(vpp);
        }
        return values.sum();
    }
    else {
        //cout << "Adapt on interval[" << vmin << ", " << vmax << "] of length " << N <<  "!!! \n";
        vec<Q> values(N_tresh);
        vec<double> mfreqs(N_tresh);    // linear grid of sample points
        int intstep = (Nmax - Nmin) / (N_tresh-1);
        for (int i = 0; i < N_tresh-1; i++) {
            mfreqs[i] = ((Nmin + intstep * i ) * 2 + 1) * (M_PI * glb_T);
            values[i] = integrand(mfreqs[i]);
        }
        mfreqs[N_tresh-1] = (Nmax * 2 + 1) * (M_PI * glb_T);
        values[N_tresh-1] = integrand(mfreqs[N_tresh-1]);
        Q slope = (values[N_tresh-1] - values[0]) / (mfreqs[N_tresh-1] - mfreqs[0]);
        vec<Q> linrzd = values[0] + (mfreqs - mfreqs[0]) * slope;   // linear approximation
        //vec<double> intermediate = (linrzd - values).abs(); // deviation of linear approximation from function values
        double error_estimate = (values[0] + (mfreqs - mfreqs[0]) * slope - values).abs().sum();
        //double vmaxn = vmax/(M_PI*glb_T);
        //double vminn = vmin/(M_PI*glb_T);
        Q resul_estimate = (values[0] - freq_step/.2 * slope) * (double)N + freq_step*slope / 2. * (double)N * (double)N;
        //cout << "error_estimate = " << error_estimate << "\t < tol * sum = " << reltol * values.std::abs().sum() << " ? \n";
        if (error_estimate < reltol * std::abs(values.abs().sum()) or error_estimate < abstol) {
            //cout << "Accepted estimate! \n";
            return resul_estimate;
        }
        else {
            //cout << "Recursion step \n";
            vec<Q> result(N_tresh-1);
            //cout << "Recursion step with error " << error_estimate << "\t on the interval[" << Nmin << ", " << Nmax << "] of length " << N << "\n";
            for (int i = 0; i < N_tresh - 2; i++) {
                result[i] = matsubarasum<Q>(integrand, Nmin + i*intstep, Nmin + (i+1)*intstep - 1, N_tresh, balance_fac, reltol, abstol);
            }
            result[N_tresh-2] = matsubarasum<Q>(integrand, Nmin + (N_tresh - 2)*intstep, Nmax, N_tresh, balance_fac, reltol, abstol);
            return result.sum();
        }
    }
    */
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
matsubarasum_vectorized()
template<int spin, int channel, typename Integrand > auto matsubarasum_vectorized (const Integrand & integrand, const int Nmin_v, const int Nmax_v, const int Nmin_sum, const int Nmax_sum, const int Nmin_vp, const int Nmax_vp) -> Eigen::Matrix<std::result_of_t<Integrand(freqType)>, Eigen::Dynamic, Eigen::Dynamic>
Definition at line 559 of file integrator.hpp.
{
    using Q = std::result_of_t<Integrand(freqType)>;
    constexpr int n_spin_sum = (channel == 't' and spin == 0) or (channel == 'a' and spin == 1) ? 2 : 1;
    Eigen::Matrix<Q, Eigen::Dynamic, Eigen::Dynamic> vertex_values_left ( Nmax_v -Nmin_v   +1              ,(Nmax_sum-Nmin_sum+1) * n_spin_sum);
    Eigen::Matrix<Q, Eigen::Dynamic, Eigen::Dynamic> vertex_values_right((Nmax_sum-Nmin_sum+1) * n_spin_sum, Nmax_vp-Nmin_vp  +1              );
    Eigen::Matrix<Q, Eigen::Dynamic, 1> Pi_values((Nmax_sum-Nmin_sum+1) * n_spin_sum);
//#pragma omp parallel for schedule(guided)
    for (int i = Nmin_sum; i <= Nmax_sum; i++) {
        const freqType vpp = (i*2 + 1);
        const Eigen::Matrix<Q, (channel == 't' and spin == 0) or (channel == 'a' and spin == 1) ? 2 : 1, 1> res_temp = integrand.load_Pi_keldysh_and_spin_Components_vectorized(vpp);
        //std::cout << Pi_values.template block<n_spin_sum,1>((-Nmin_sum+i)*n_spin_sum, 0) << std::endl;
        Pi_values.template block<n_spin_sum,1>((-Nmin_sum+i)*n_spin_sum, 0) = res_temp;
    }
//#pragma omp parallel for schedule(static, 500) collapse(2)
    for (int i = Nmin_v; i <= Nmax_v; i++) {
        for (int j = Nmin_sum; j <= Nmax_sum; j++) {
            const freqType v   = (i*2 + 1) ;
            const freqType vpp = (j*2 + 1) ;
            VertexInput input_l = integrand.input_external;
            input_l.v1 = v;
            input_l.v2 = vpp;
            Q value;
            vertex_values_left.template block<1,n_spin_sum>(-Nmin_v+i, (-Nmin_sum+j) * n_spin_sum) = integrand.load_vertex_keldysh_and_spin_Components_left_vectorized(input_l);
        }
    }
//#pragma omp parallel for schedule(static, 500) collapse(2)
    for (int i = Nmin_sum; i <= Nmax_sum; i++) {
        for (int j = Nmin_vp; j <= Nmax_vp; j++) {
            const freqType vpp= (i*2 + 1);
            const freqType vp = (j*2 + 1);
            VertexInput input_r = integrand.input_external;
            input_r.v1 = vpp;
            input_r.v2 = vp;
            Q value;
            vertex_values_right.template block<n_spin_sum,1>((-Nmin_sum+i) * n_spin_sum, -Nmin_vp+j) = integrand.load_vertex_keldysh_and_spin_Components_right_vectorized(input_r);
        }
    }
    Eigen::Matrix<std::result_of_t<Integrand(freqType)>, Eigen::Dynamic, Eigen::Dynamic> result = vertex_values_left * Pi_values.asDiagonal() * vertex_values_right;
    auto result_alt = Pi_values.sum() * 2.5*2.5;
    //std::cout << vertex_values_left << "\n * " << Pi_values << "\n * " << vertex_values_right << std::endl;
    //std::cout << "result: " << result << std::endl;
    //std::cout << "result_alt: " << result_alt << std::endl;
    return vertex_values_left * Pi_values.asDiagonal() * vertex_values_right;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and VertexInput::v1.