SIAM-Keldysh-mfRG: Integrand_Ward_id_integrated< gridType > Class Template Reference
Integrand_Ward_id_integrated< gridType > Class Template Reference
#include <postprocessing.hpp>
Public Member Functions
Integrand_Ward_id_integrated (const gridType &v_in, const rvec &Phi_in, const SelfEnergy< state_datatype > &selfEnergy_in, const int iLambda_in, const int i_in_in)
auto operator() (double vp) const -> double
Public Attributes
const gridType v
const rvec & Phi
const SelfEnergy< state_datatype > & selfEnergy
const int iLambda
const int i_in
Detailed Description
template<typename gridType>
class Integrand_Ward_id_integrated< gridType >
Definition at line 36 of file postprocessing.hpp.
Constructor & Destructor Documentation
Integrand_Ward_id_integrated()
template<typename gridType > Integrand_Ward_id_integrated< gridType >::Integrand_Ward_id_integrated (const gridType & v_in, const rvec & Phi_in, const SelfEnergy< state_datatype > & selfEnergy_in, const int iLambda_in, const int i_in_in) inline
Definition at line 44 of file postprocessing.hpp.
            : v(v_in), Phi(Phi_in), selfEnergy(selfEnergy_in), iLambda(iLambda_in), i_in(i_in_in) {}
Member Function Documentation
operator()()
template<typename gridType > auto Integrand_Ward_id_integrated< gridType >::operator() (double vp) const -> double inline
Definition at line 48 of file postprocessing.hpp.
{
        if (std::abs(vp) < v.w_upper) {
            int index = v.get_grid_index(vp);
            double x1 = v.get_frequency(index);
            double x2 = v.get_frequency(index + 1);
            if (!(x1 < x2)) {
                index -= 1;
                x1 = v.get_frequency(index);
                x2 = v.get_frequency(index + 1);
            }
            double xd = (vp - x1) / (x2 - x1);
            double f1 = Phi[iLambda * nFER * n_in + index * n_in + i_in];
            double f2 = Phi[iLambda * nFER * n_in + (index + 1) * n_in + i_in];
            return myimag((1. - xd) * f1 + xd * f2 + 2. * selfEnergy.valsmooth(0, vp, i_in));
        }
        else
            return 0.;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Integrand_Ward_id_integrated< gridType >::i_in, Integrand_Ward_id_integrated< gridType >::iLambda, myimag(), n_in, nFER, Integrand_Ward_id_integrated< gridType >::Phi, Integrand_Ward_id_integrated< gridType >::selfEnergy, Integrand_Ward_id_integrated< gridType >::v, and SelfEnergy< Q >::valsmooth().
Member Data Documentation
i_in
template<typename gridType > const int Integrand_Ward_id_integrated< gridType >::i_in
Definition at line 42 of file postprocessing.hpp.
Referenced by Integrand_Ward_id_integrated< gridType >::operator()().
iLambda
template<typename gridType > const int Integrand_Ward_id_integrated< gridType >::iLambda
Definition at line 41 of file postprocessing.hpp.
Referenced by Integrand_Ward_id_integrated< gridType >::operator()().
Phi
template<typename gridType > const rvec& Integrand_Ward_id_integrated< gridType >::Phi
Definition at line 39 of file postprocessing.hpp.
Referenced by Integrand_Ward_id_integrated< gridType >::operator()().
selfEnergy
template<typename gridType > const SelfEnergy<state_datatype>& Integrand_Ward_id_integrated< gridType >::selfEnergy
Definition at line 40 of file postprocessing.hpp.
Referenced by Integrand_Ward_id_integrated< gridType >::operator()().
v
template<typename gridType > const gridType Integrand_Ward_id_integrated< gridType >::v
Definition at line 38 of file postprocessing.hpp.
Referenced by Integrand_Ward_id_integrated< gridType >::operator()().
The documentation for this class was generated from the following file:
postprocessing.hpp