SIAM-Keldysh-mfRG: right_hand_sides.hpp File Reference
right_hand_sides.hpp File Reference
#include "../data_structures.hpp"
#include "../utilities/write_data2file.hpp"
#include "../correlation_functions/two_point/propagator.hpp"
#include "../correlation_functions/two_point/selfenergy.hpp"
#include "../correlation_functions/state.hpp"
#include "../correlation_functions/four_point/vertex.hpp"
#include "../loop/loop.hpp"
#include "../bubble/bubble_function.hpp"
#include "../parameters/master_parameters.hpp"
#include "../ODE_solvers/ODE_solvers.hpp"
#include <cassert>
#include "../utilities/hdf5_routines.hpp"
#include "../utilities/util.hpp"
#include "../perturbation_theory_and_parquet/parquet_solver.hpp"
#include "../utilities/anderson_acceleration.hpp"
Classes
struct mfRG_record< Q >
struct mfRG_stats
class rhs_n_loop_flow_t< Q >
class oneBubble< Q >
Functions
template<typename Q >
auto rhs_n_loop_flow (const State< Q > &Psi, double Lambda, const fRG_config &config) -> State< Q >
template<typename Q >
void selfEnergyOneLoopFlow (SelfEnergy< Q > &dPsiSelfEnergy, const Vertex< Q, false > &PsiVertex, const Propagator< Q > &S)
template<typename Q , class Bubble_Object >
void vertexOneLoopFlow (Vertex< Q, true > &dPsiVertex, const Vertex< Q, false > &Psi, const Bubble_Object &dPi, const fRG_config &config)
template<typename Q >
void selfEnergyFlowCorrections (SelfEnergy< Q > &dPsiSelfEnergy, const GeneralVertex< Q, symmetric_r_irred, true > &dGammaC_tbar, const State< Q > &Psi, const Propagator< Q > &G)
template<typename Q , class Bubble_Object >
auto calculate_dGammaL (const GeneralVertex< Q, symmetric_r_irred, true > &dPsiVertex, const Vertex< Q, false > &PsiVertex, const Bubble_Object &Pi, const fRG_config &config) -> Vertex< Q, true >
template<typename Q , class Bubble_Object >
auto calculate_dGammaR (const GeneralVertex< Q, symmetric_r_irred, true > &dPsiVertex, const Vertex< Q, false > &PsiVertex, const Bubble_Object &Pi, const fRG_config &config) -> Vertex< Q, true >
template<typename Q , class Bubble_Object >
auto calculate_dGammaC_right_insertion (const Vertex< Q, false > &PsiVertex, const GeneralVertex< Q, non_symmetric_diffleft, true > &nonsymVertex, const Bubble_Object &Pi, const fRG_config &config) -> Vertex< Q, true >
template<typename Q , class Bubble_Object >
auto calculate_dGammaC_left_insertion (const GeneralVertex< Q, non_symmetric_diffright, true > &nonsymVertex, const Vertex< Q, false > &PsiVertex, const Bubble_Object &Pi, const fRG_config &config) -> Vertex< Q, true >
template<typename Q >
bool vertexConvergedInLoops (Vertex< Q, true > &dGamma_T, Vertex< Q, true > &dGamma)
template<typename Q >
bool selfEnergyConverged (SelfEnergy< Q > &dPsiSelfEnergy, SelfEnergy< Q > &PsiSelfEnergy, Propagator< Q > &dG)
template<typename Q >
void calculate_dSigma_SOPT (SelfEnergy< Q > &Sigma_out, const State< Q > &Psi, const double Lambda, const fRG_config &config)
compute dSigma in SOPT
template<typename Q >
auto rhs_n_loop_flow (const State< Q > &Psi, const double Lambda, const int nloops_max, const vec< size_t > opt, const fRG_config &config, mfRG_stats &stats) -> State< Q >
template<typename Q >
auto vertexConvergedInLoops (Vertex< Q, true > &dGamma_T, Vertex< Q, true > &dGamma) -> bool
template<typename Q >
auto selfEnergyConverged (SelfEnergy< Q > &dPsiSelfEnergy, SelfEnergy< Q > &PsiSelfEnergy, Propagator< Q > &dG) -> bool
Function Documentation
calculate_dGammaC_left_insertion()
template<typename Q , class Bubble_Object > auto calculate_dGammaC_left_insertion (const GeneralVertex< Q, non_symmetric_diffright, true > & nonsymVertex, const Vertex< Q, false > & PsiVertex, const Bubble_Object & Pi, const fRG_config & config) -> Vertex<Q,true>
Definition at line 781 of file right_hand_sides.hpp.
{
    Vertex<Q,true> dGammaC (Lambda_ini, config, PsiVertex);
    dGammaC.set_frequency_grid(PsiVertex);
    //GeneralVertex<Q, non_symmetric_diffright> nonsymVertex_calc = nonsymVertex;
    //for (char r: {'a', 'p', 't'}) {
    //    nonsymVertex_calc.get_rvertex(r).K2 *= 0;
    //    if (DEBUG_SYMMETRIES) nonsymVertex_calc.get_rvertex(r).K2b *= 0;
    //    if (r != 'p')
    //        nonsymVertex_calc.get_rvertex(r).K3 *= 0;
    //}
    //Vertex<Q> PsiVertex_calc = PsiVertex;
    //for (char r: {'a', 'p', 't'}) {
    //    if (r != 'a')
    //        PsiVertex_calc.get_rvertex(r).K1 *= 0;
    //    PsiVertex_calc.get_rvertex(r).K2 *= 0;
    //    if (DEBUG_SYMMETRIES) PsiVertex_calc.get_rvertex(r).K2b *= 0;
    //    //if (r != 'p')
    //        //PsiVertex_calc.get_rvertex(r).K3 *= 0;
    //}
    if constexpr (SBE_DECOMPOSITION and MAX_DIAG_CLASS==2 and USE_NEW_MFRG_EQS) {
        Vertex<Q,false> One = PsiVertex;
        for (char r: {'a', 'p','t'}) {
            One.get_rvertex(r).K2 *= 0;
        }
        for (char r: {'a', 'p', 't'}) {
            bubble_function(dGammaC, nonsymVertex, One, Pi, r, config);
            if constexpr (DEBUG_SYMMETRIES) dGammaC.get_rvertex(r).K2b *= 0.;
        }
    }
    else {
        for (char r: "apt") {
            bubble_function(dGammaC, nonsymVertex, PsiVertex, Pi, r, config);
        }
    }
    return dGammaC;
}
References bubble_function(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), Lambda_ini, MAX_DIAG_CLASS, SBE_DECOMPOSITION, and USE_NEW_MFRG_EQS.
Referenced by rhs_n_loop_flow().
calculate_dGammaC_right_insertion()
template<typename Q , class Bubble_Object > auto calculate_dGammaC_right_insertion (const Vertex< Q, false > & PsiVertex, const GeneralVertex< Q, non_symmetric_diffleft, true > & nonsymVertex, const Bubble_Object & Pi, const fRG_config & config) -> Vertex< Q, true >
for dGammaC in channel r we combine: dgammaC_r = Gamma Pi_r dGammaL_r Hence dGammaL only returns values of the r-reducible sector
Definition at line 746 of file right_hand_sides.hpp.
{
    Vertex<Q,true> dGammaC (Lambda_ini, config, PsiVertex);
    dGammaC.set_frequency_grid(PsiVertex);
    //GeneralVertex<Q, non_symmetric_diffleft> nonsymVertex_calc = nonsymVertex;
    //for (char r: {'a', 'p', 't'}) {
    //    nonsymVertex_calc.get_rvertex(r).K2 *= 0;
    //    if (DEBUG_SYMMETRIES) nonsymVertex_calc.get_rvertex(r).K2b *= 0;
    //    if (r != 'p')
    //        nonsymVertex_calc.get_rvertex(r).K3 *= 0;
    //}
    if constexpr (SBE_DECOMPOSITION and MAX_DIAG_CLASS==2 and USE_NEW_MFRG_EQS) {
        Vertex<Q,false> One = PsiVertex;
        for (char r: {'a', 'p','t'}) {
            One.get_rvertex(r).K2 *= 0;
        }
        for (char r: {'a', 'p', 't'}) {
            bubble_function(dGammaC, One, nonsymVertex, Pi, r, config);
            dGammaC.get_rvertex(r).K2 *= 0.;
        }
    }
    else {
        for (char r: "apt") {
            bubble_function(dGammaC, PsiVertex, nonsymVertex, Pi, r, config);
        }
    }
    return dGammaC;
}
References bubble_function(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), Lambda_ini, MAX_DIAG_CLASS, SBE_DECOMPOSITION, and USE_NEW_MFRG_EQS.
Referenced by rhs_n_loop_flow().
calculate_dGammaL()
template<typename Q , class Bubble_Object > auto calculate_dGammaL (const GeneralVertex< Q, symmetric_r_irred, true > & dPsiVertex, const Vertex< Q, false > & PsiVertex, const Bubble_Object & Pi, const fRG_config & config) -> Vertex< Q, true >
for dGammaR in channel r we combine: dgammaL_r = dgamma_rbar Pi_r Gamma Hence dgamma_rbar only returns values of the r-IRreducible sector
Definition at line 612 of file right_hand_sides.hpp.
{
    Vertex<Q,true> dGammaL(Lambda_ini, config, PsiVertex);
    dGammaL.set_frequency_grid(PsiVertex);
    //Vertex<Q,false> dPsiVertex_calc = dPsiVertex;
    //dPsiVertex_calc.set_Ir(true); // Only use the r-irreducible part
    //Vertex<Q> PsiVertex_calc = PsiVertex;
    //for (char r : {'a', 'p', 't'}) {
    //    PsiVertex_calc.get_rvertex(r).K1 *= 0;
    //    PsiVertex_calc.get_rvertex(r).K2 *= 0;
    //    if (DEBUG_SYMMETRIES) PsiVertex_calc.get_rvertex(r).K2b *= 0;
    //}
    if constexpr (SBE_DECOMPOSITION and MAX_DIAG_CLASS==2 and USE_NEW_MFRG_EQS) {
        Vertex<Q,false> One(Lambda_ini, config);
        for (char r: "apt") {
            bubble_function(dGammaL, dPsiVertex, One, Pi, r, config);
        }
    }
    else {
        for (char r: "apt") {
            bubble_function(dGammaL, dPsiVertex, PsiVertex, Pi, r, config);
        }
    }
    return dGammaL;
}
References bubble_function(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Lambda_ini, MAX_DIAG_CLASS, SBE_DECOMPOSITION, and USE_NEW_MFRG_EQS.
Referenced by rhs_n_loop_flow().
calculate_dGammaR()
template<typename Q , class Bubble_Object > auto calculate_dGammaR (const GeneralVertex< Q, symmetric_r_irred, true > & dPsiVertex, const Vertex< Q, false > & PsiVertex, const Bubble_Object & Pi, const fRG_config & config) -> Vertex< Q, true >
for dGammaR in channel r we combine: dgammaR_r = Gamma Pi_r dgamma_rbar Hence dgamma_rbar only returns values of the r-IRreducible sector
Definition at line 642 of file right_hand_sides.hpp.
{
    Vertex<Q,true> dGammaR(Lambda_ini, config, PsiVertex);
    dGammaR.set_frequency_grid(PsiVertex);
    //Vertex<Q,true> dPsiVertex_calc = dPsiVertex;
    //dPsiVertex_calc.set_Ir(true); // Only use the r-irreducible part
    if constexpr (SBE_DECOMPOSITION and MAX_DIAG_CLASS==2 and USE_NEW_MFRG_EQS) {
        Vertex<Q,false> One(Lambda_ini, config);
        for (char r: "apt") {
            bubble_function(dGammaR, One, dPsiVertex, Pi, r, config);
        }
    }
    else {
        for (char r: "apt") {
            bubble_function(dGammaR, PsiVertex, dPsiVertex, Pi, r, config);
        }
    }
    return dGammaR;
}
References bubble_function(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Lambda_ini, MAX_DIAG_CLASS, SBE_DECOMPOSITION, and USE_NEW_MFRG_EQS.
Referenced by rhs_n_loop_flow().
calculate_dSigma_SOPT()
template<typename Q > void calculate_dSigma_SOPT (SelfEnergy< Q > & Sigma_out, const State< Q > & Psi, const double Lambda, const fRG_config & config)
compute dSigma in SOPT
Definition at line 39 of file right_hand_sides.hpp.
{
    SelfEnergy<Q> Sigma_H (Lambda);
    Sigma_H.initialize(Psi.selfenergy.asymp_val_R, 0);
    Propagator<Q> G0(Lambda, Sigma_H, 'g');
    Propagator<Q>dG0(Lambda, Sigma_H, 's');
    Bubble<Q> Pi (G0, G0, false);
    Bubble<Q>dPi (G0,dG0, true);
    Vertex<Q,false> Gamma0(Lambda);
    Gamma0.initialize(Psi.vertex.irred().acc(0));
    Vertex<Q,false> bubble_a(Lambda);
    Vertex<Q,false>dbubble_a(Lambda);
    bubble_a.set_frequency_grid(Psi.vertex);
    dbubble_a.set_frequency_grid(Psi.vertex);
    bubble_function( bubble_a, Gamma0, Gamma0, Pi, 'a', config);
    bubble_function(dbubble_a, Gamma0, Gamma0,dPi, 'a', config);
    SelfEnergy<Q> result1(Lambda);
    SelfEnergy<Q> result2(Lambda);
    loop<false,0>(result1, bubble_a, dG0);
    loop<false,0>(result2, dbubble_a, G0);
    Sigma_out = result1 + result2;
}
References bubble_function(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
rhs_n_loop_flow() [1/2]
template<typename Q > auto rhs_n_loop_flow (const State< Q > & Psi, const double Lambda, const int nloops_max, const vec< size_t > opt, const fRG_config & config, mfRG_stats & stats) -> State<Q>
Function to implement an n-loop flow (without Katanin substitution).
Parameters
Psi : Known state of the State at Lambda
Lambda Scale at which the calculation is being performed
Returns
dPsi : The derivative at Lambda, which includes the differential vertex as well as self-energy at scale Lambda
For flow without self-energy, comment out this line
For flow giving SOPT (in selfenergy):
for Anderson acceleration:
for testing:
for testing:
limit number of states in history?
save intermediate results:
Definition at line 167 of file right_hand_sides.hpp.
                                                                                                                                                                    {  //, const bool save_intermediate=false
    Psi.vertex.check_symmetries("Psi");
    assert(nloops_max>=1);
    std::string dir_str = data_dir + "intermediateResults/";
    int iteration=-1;
    int rkStep=-1;
    double t0 = utils::get_time();
    bool save = false;
    if (opt.size() > 1) {
         iteration = opt[0];
         rkStep = opt[1];
         if (rkStep==0 and iteration==0 and config.save_intermediateResults) {
             utils::makedir(dir_str);
             save = true;
         }
    }
    // initialize empty state with frequency grids corresponding to those in Psi:
    State<Q,true> dPsi(Psi, Lambda); // result
#if ((not defined STATIC_FEEDBACK) and (not defined PT2_FLOW))
    Propagator<Q> S (Lambda, Psi.selfenergy, 's', Psi.config);
    Propagator<Q> G (Lambda, Psi.selfenergy, 'g', Psi.config);
#else
    SelfEnergy<Q> bareSelfEnergy (Psi.selfenergy.Sigma.frequencies);
    bareSelfEnergy.initialize(config.U/2., 0.);
    Propagator<Q> S (Lambda, bareSelfEnergy, 's', Psi.config);
    Propagator<Q> G (Lambda, bareSelfEnergy, 'g', Psi.config);
#endif
    selfEnergyOneLoopFlow(dPsi.selfenergy, Psi.vertex, S);
    //calculate_dSigma_SOPT<Q>(dPsi.selfenergy, Psi, Lambda);
    const SelfEnergy<Q> selfenergy_1loop = dPsi.selfenergy;
    //dPsi.selfenergy.check_resolution();
    int counter_Selfenergy_iterations = 0;
    double selfenergy_correction_abs = 1e10;
    double selfenergy_correction_rel = 1.;
    std::deque<State<Q,true>> rhs_evals;             // dSigma according to evaluation of mfRG equations
    std::deque<State<Q,true>> iteration_steps;       // accepted dPsi.selfenergy's
#if SELF_ENERGY_FLOW_CORRECTIONS != 0
    do {
#endif
#if not defined BARE_SE_FEEDBACK and not defined PT2_FLOW
#ifdef KATANIN
    Propagator<Q> dG (Lambda, Psi.selfenergy, dPsi.selfenergy, 'k', Psi.config);
#else
    Propagator<Q> dG (Lambda, Psi.selfenergy, 's', Psi.config);
#endif // KATANIN
    //Run alternatively, for no self-energy feedback
//    Propagator<Q> dG (Lambda, Psi.selfenergy, 's');
#else
    Propagator<Q> dG (Lambda, bareSelfEnergy, 's', Psi.config);
#endif // BARE_SE_FEEDBACK, PT2_FLOW
    // Initialize bubble objects;
    Bubble<Q> Pi(G, dG, false);
    Bubble<Q> dPi(G, dG, true);
    if (VERBOSE) utils::print("Compute 1-loop contribution: ", true);
#ifdef PT2_FLOW
    State<Q> bareState = State<Q> (Psi.Lambda, Psi.config); // shall and forever will be a bare state.
    bareState.initialize(false);  // a state with a bare vertex and a self-energy initialized at the Hartree value
    vertexOneLoopFlow(dPsi.vertex, bareState.vertex, dPi, config);
#else
    vertexOneLoopFlow(dPsi.vertex, Psi.vertex, dPi, config);
#endif
    mfRG_record<Q> record_of_intermediate_results{.dPsi_1loop = dPsi};
    record_of_intermediate_results.dPsi_1loop = dPsi;
#if DEBUG_SYMMETRIES
    dPsi.vertex.template symmetry_expand<'a',true,false>();
    dPsi.vertex.save_expanded(data_dir + "dPsi_symmetry_expanded_for_a_left_");
    dPsi.vertex.template symmetry_expand<'p',true,false>();
    dPsi.vertex.save_expanded(data_dir + "dPsi_symmetry_expanded_for_p_left_");
    dPsi.vertex.template symmetry_expand<'t',true,false>();
    dPsi.vertex.save_expanded(data_dir + "dPsi_symmetry_expanded_for_t_left_");
#endif
        if(VERBOSE) {
        dPsi.vertex.half1().check_vertex_resolution();
        dPsi.analyze_tails();
        compare_with_FDTs(Psi.vertex, Lambda, iteration, "Psi_RKstep"+std::to_string(rkStep), Psi.config, false, config.nODE_ + U_NRG.size() + 1);
        compare_with_FDTs(dPsi.vertex, Lambda, iteration, "dPsi_RKstep"+std::to_string(rkStep), Psi.config, false, config.nODE_ + U_NRG.size() + 1);
    }
    if (nloops_max>=2) {
        // Calculate left and right part of 2-loop contribution.
        // The result contains only part of the information (half 1), thus needs to be completed to a non-symmetric_full vertex
        // when inserted in the 3-loop contribution below.
        GeneralVertex<Q, symmetric_r_irred,true> dGamma_1loop(dPsi.vertex.half1(), Psi.vertex);
#if DEBUG_SYMMETRIES
        dGamma_1loop.template symmetry_expand<'a',true,false>();
        dGamma_1loop.save_expanded(data_dir + "dPsi_irr_symmetry_expanded_for_a_left_");
        dGamma_1loop.template symmetry_expand<'p',true,false>();
        dGamma_1loop.save_expanded(data_dir + "dPsi_irr_symmetry_expanded_for_p_left_");
        dGamma_1loop.template symmetry_expand<'t',true,false>();
        dGamma_1loop.save_expanded(data_dir + "dPsi_irr_symmetry_expanded_for_t_left_");
#endif
        if (VERBOSE) utils::print("Compute dGammaL (2-loop): ", true);
        Vertex<Q,true> dGammaL_half1 = calculate_dGammaL(dGamma_1loop, Psi.vertex, Pi, config);
        if(VERBOSE) {
            dGammaL_half1.half1().check_vertex_resolution();
            compare_with_FDTs(dGammaL_half1, Lambda, iteration, "dGammaL_RKstep"+std::to_string(rkStep)+"_forLoop"+std::to_string(2), Psi.config, false, config.nODE_ + U_NRG.size() + 1);
        }
        if (VERBOSE) utils::print("Compute dGammaR (2-loop):", true);
        Vertex<Q,true> dGammaR_half1 = calculate_dGammaR(dGamma_1loop, Psi.vertex, Pi, config);
        if(VERBOSE) {
            dGammaR_half1.half1().check_vertex_resolution();
        }
        Vertex<Q,true> dGammaT =
                dGammaL_half1 + dGammaR_half1; // since sum dGammaL + dGammaR is symmetric_full, half 1 is sufficient
        dPsi.vertex += dGammaT;
        record_of_intermediate_results.dGamma_L_nloop.push_back(dGammaL_half1);
        record_of_intermediate_results.dGamma_R_nloop.push_back(dGammaR_half1);
    if constexpr(not DEBUG_SYMMETRIES) {
        // subdiagrams don't fulfill the full symmetry of the vertex
        // the symmetry-related diagram with a differentiated vertex on the left might be one with differentiated vertex on the right (vice versa)
        // for further evaluation as part of a bigger diagram they need to be reordered to recover the correct dGammaL and dGammaR
        // acc. to symmetry relations (enforce_symmetry() assumes full symmetry)
        dGammaL_half1.half1().reorder_due2antisymmetry(dGammaR_half1.half1());
    }
        if (nloops_max >= 3) {
#if SELF_ENERGY_FLOW_CORRECTIONS != 0
            // initialize central part of the vertex flow in the a and p channels (\bar{t}), needed for self-energy corrections
            GeneralVertex<Q, symmetric_r_irred,true> dGammaC_tbar(Lambda, Psi.config, Psi.vertex);
            dGammaC_tbar.set_frequency_grid(Psi.vertex);
            //dGammaC_tbar.set_Ir(true);
#endif
            double abs_loop = 1;
            double rel_loop = 1;
            for (int i = 3; i <= nloops_max; i++) {
                // create non-symmetric_full vertex with differentiated vertex on the left (full dGammaL, containing half 1 and 2)
                // assign half 1 to dGammaL
                // assign half 2 as half 1 of dGammaR [symmetric_full -> half1()=half2()]
                GeneralVertex<Q, non_symmetric_diffleft,true> dGammaL(dGammaL_half1.half1(), dGammaR_half1.half1(), Psi.vertex);
                if (VERBOSE) {
                    compare_with_FDTs(dGammaL, Lambda, iteration,
                                      "dGammaL_RKstep" + std::to_string(rkStep) + "_forLoop" + std::to_string(2), Psi.config, false,
                                      config.nODE_ + U_NRG.size() + 1);
                }
#if DEBUG_SYMMETRIES
                dGammaL.template symmetry_expand<'a',true,false>();
                dGammaL.save_expanded(data_dir + "dGammaL_symmetry_expanded_for_a_left_");
                dGammaL.template symmetry_expand<'p',true,false>();
                dGammaL.save_expanded(data_dir + "dGammaL_symmetry_expanded_for_p_left_");
                dGammaL.template symmetry_expand<'t',true,false>();
                dGammaL.save_expanded(data_dir + "dGammaL_symmetry_expanded_for_t_left_");
#endif
                // insert this non-symmetric_full vertex on the right of the bubble
                if (VERBOSE) utils::print("Compute dGammaC (right insertion) ( ", i, "-loop): \n");
                Vertex<Q,true> dGammaC_r = calculate_dGammaC_right_insertion(Psi.vertex, dGammaL, Pi, config);
                record_of_intermediate_results.dGamma_Cr_nloop.push_back(dGammaC_r);
                if (VERBOSE) dGammaC_r.half1().check_vertex_resolution();
                if (VERBOSE) {
                    compare_with_FDTs(dGammaC_r, Lambda, iteration,
                                      "dGammaC_r_RKstep" + std::to_string(rkStep) + "_forLoop" + std::to_string(2),
                                      Psi.config,false, config.nODE_ + U_NRG.size() + 1);
                }
                // create non-symmetric_full vertex with differentiated vertex on the right (full dGammaR, containing half 1 and 2)
                // assign half 1
                // assign half 2 as half 1 of dGammaL
                GeneralVertex<Q, non_symmetric_diffright, true> dGammaR(dGammaR_half1.half1(), dGammaL_half1.half1(), Psi.vertex);
                if (VERBOSE) {
                    compare_with_FDTs(dGammaR, Lambda, iteration,
                                      "dGammaR_RKstep" + std::to_string(rkStep) + "_forLoop" + std::to_string(2),
                                      Psi.config, false,config.nODE_ + U_NRG.size() + 1);
                }
                // insert this non-symmetric_full vertex on the left of the bubble
                Vertex<Q, true> dGammaC_l = calculate_dGammaC_left_insertion(dGammaR, Psi.vertex, Pi, config);
                record_of_intermediate_results.dGamma_Cl_nloop.push_back(dGammaC_l);
                if (VERBOSE) {
                    compare_with_FDTs(dGammaC_l, Lambda, iteration,
                                      "dGammaC_l_RKstep" + std::to_string(rkStep) + "_forLoop" + std::to_string(2),
                                      Psi.config, false, config.nODE_ + U_NRG.size() + 1);
                }
                // symmetrize by averaging left and right insertion
                for (char r : {'a', 'p', 't'}) {
                    dGammaC_l.get_rvertex(r).K2 = dGammaC_r.get_rvertex(r).K2;
                }
                if constexpr(DEBUG_SYMMETRIES) {
                    for (char r: {'a', 'p', 't'}) {
                        dGammaC_r.get_rvertex(r).K2b = dGammaC_l.get_rvertex(r).K2b;
                    }
                }
                //for (char r : {'a', 'p', 't'}) {
                //    dGammaC_l.get_rvertex(r).K3 *= 0.;
                //    dGammaC_r.get_rvertex(r).K3 *= 0.;
                //}
                Vertex<Q,true> dGammaC = (dGammaC_r + dGammaC_l) * 0.5; //dGammaC_r; //                  /// TODO: Find better solution --> K2 in dGammaC_l is bad, K3 in dGammaC_l can be obtained from dGammaC_r
                if (VERBOSE) utils::print("Compute dGammaL ( ", i, "-loop): \n");
                const GeneralVertex<Q, symmetric_r_irred,true> dGammaT_irr(dGammaT.half1(), Psi.vertex);
                dGammaL_half1 = calculate_dGammaL(dGammaT_irr, Psi.vertex, Pi, config);
                if (VERBOSE) dGammaL_half1.half1().check_vertex_resolution();
                if (VERBOSE) utils::print("Compute dGammaR ( ", i, "-loop): \n");
                dGammaR_half1 = calculate_dGammaR(dGammaT_irr, Psi.vertex, Pi, config);
                if (VERBOSE) dGammaR_half1.half1().check_vertex_resolution();
                record_of_intermediate_results.dGamma_L_nloop.push_back(dGammaL_half1);
                record_of_intermediate_results.dGamma_R_nloop.push_back(dGammaR_half1);
                dGammaT = dGammaL_half1 + dGammaC +
                          dGammaR_half1; // since sum dGammaL + dGammaR is symmetric_full, half 1 is sufficient
                dPsi.vertex += dGammaT;
                if constexpr (not DEBUG_SYMMETRIES) {
                    // subdiagrams don't fulfill the full symmetry of the vertex
                    // the symmetry-related diagram with a differentiated vertex on the left might be one with differentiated vertex on the right (vice versa)
                    // for further evaluation as part of a bigger diagram they need to be reordered to recover the correct dGammaL and dGammaR
                    // acc. to symmetry relations (enforce_symmetry() assumes full symmetry)
                    dGammaL_half1.half1().reorder_due2antisymmetry(dGammaR_half1.half1());
                }
#if SELF_ENERGY_FLOW_CORRECTIONS != 0
                // extract central part of the vertex flow in the a and p channels (\bar{t}), needed for self-energy corrections
                //Vertex<Q,true> dGammaC_ap(Lambda);                   // initialize new vertex
                //dGammaC_ap.set_frequency_grid(Psi.vertex);
                //dGammaC_ap.avertex() = dGammaC.avertex();  // copy results from calculations above
                //dGammaC_ap.pvertex() = dGammaC.pvertex();
                dGammaC_tbar += GeneralVertex<Q, symmetric_r_irred,true>(dGammaC.half1(), Psi.vertex);                      // add the i-loop contribution to the full dGammaC_tbar
#endif
                abs_loop = dGammaT.norm();
                rel_loop = dGammaT.norm() / dPsi.vertex.norm();
                utils::print("Rel. contribution from loop ", i, ": ", rel_loop*100, " %\n");
                utils::print("Abs. contribution from loop ", i, ": ", abs_loop, "\n");
                if (abs_loop < loop_tol_abs or rel_loop < loop_tol_rel) break;
            }
#if SELF_ENERGY_FLOW_CORRECTIONS == 1
            // compute multiloop corrections to self-energy flow
            State<Q,true> Psi_SEcorrection(dPsi.vertex, dPsi.selfenergy, Psi.config, Lambda);
            selfEnergyFlowCorrections(Psi_SEcorrection.selfenergy, dGammaC_tbar, Psi, G); // isolated SE correction
            SelfEnergy<Q> selfEnergy_old = dPsi.selfenergy;
            SelfEnergy<Q> selfEnergy_new = selfenergy_1loop + Psi_SEcorrection.selfenergy;
#if USE_ANDERSON_ACCELERATION
            State<Q,true> dPsi_new(dPsi.vertex, selfEnergy_new, Psi.config, Lambda); // vertex in dPsi and dPsi_new are identical --> only find dSigma by Anderson Acceleration
            rhs_evals.push_back(dPsi_new);
            iteration_steps.push_back(dPsi);
            //if (rhs_evals.size() > n_States_for_AndersonAcceleration) {
            //    rhs_evals.pop_front();
            //    iteration_steps.pop_front();
            //}
            dPsi.selfenergy = anderson_update(rhs_evals, iteration_steps, 1.0).selfenergy;
#else
            dPsi.selfenergy = selfEnergy_new;
#endif
            SelfEnergy<Q> selfEnergy_err = dPsi.selfenergy - selfEnergy_old;
            record_of_intermediate_results.dSigma_correction = Psi_SEcorrection;
            selfenergy_correction_abs = selfEnergy_err.norm();
            selfenergy_correction_rel = selfEnergy_err.rel_deviation_to(dPsi.selfenergy);
            State<Q> state_self_diffrel(Lambda, Psi.config);
            state_self_diffrel.selfenergy = selfEnergy_err * (1./ dPsi.selfenergy.norm());
#elif SELF_ENERGY_FLOW_CORRECTIONS == 2
            utils::print("  ---  Computing dSigma from the SDE  --- \n");
            State<Q,true> Psi_SDE_diff_documentation = dPsi;
            double tol = 1.e-3;
            double diff = 1;
            int iteration_SDE = 0;
            std::deque<State<Q,true>> rhs_evals_SDE_iteration;             // dSigma according to evaluation of mfRG equations
            std::deque<State<Q,true>> iteration_steps_SDE_iteration;       // accepted dPsi.selfenergy's
            do {
                const SelfEnergy<Q> dSigma_SDE = compute_diff_SDE<Q>(Psi, dPsi.vertex, dPsi.selfenergy)   ;
                #if USE_ANDERSON_ACCELERATION
                    State<Q,true> dPsi_new(dPsi.vertex, dSigma_SDE, Psi.config, Lambda); // vertex in dPsi and dPsi_new are identical --> only find dSigma by Anderson Acceleration
                    rhs_evals_SDE_iteration.push_back(dPsi_new);
                    iteration_steps_SDE_iteration.push_back(dPsi);
                    //if (rhs_evals.size() > n_States_for_AndersonAcceleration) {
                    //    rhs_evals.pop_front();
                    //    iteration_steps.pop_front();
                    //}
                    dPsi.selfenergy = anderson_update(rhs_evals_SDE_iteration, iteration_steps_SDE_iteration, 1.0).selfenergy;
                #else
                    dPsi.selfenergy = dSigma_SDE;
                #endif
                const SelfEnergy<Q> selfenergy_diff = dPsi.selfenergy - dSigma_SDE;
                const double norm_compare =  dPsi.selfenergy.norm(0);
                diff = norm_compare < 1e-10 ? 1 : selfenergy_diff.rel_deviation_to(dPsi.selfenergy);
                utils::print("SDE iteration ", iteration_SDE ," \t relative change : ", diff, "\n");
                iteration_SDE++;
            }
            while (diff > tol and iteration_SDE < 4);
#if USE_ANDERSON_ACCELERATION
            rhs_evals.push_back(dPsi);
            iteration_steps.push_back(Psi_SDE_diff_documentation);
            //if (rhs_evals.size() > n_States_for_AndersonAcceleration) {
            //    rhs_evals.pop_front();
            //    iteration_steps.pop_front();
            //}
            dPsi.selfenergy = anderson_update(rhs_evals, iteration_steps, 1.0);
#endif
            // Compute difference of old dSigma and new dSigma
            Psi_SDE_diff_documentation.selfenergy -= dPsi.selfenergy;
            record_of_intermediate_results.dSigma_correction = Psi_SDE_diff_documentation;
            selfenergy_correction_abs = Psi_SDE_diff_documentation.selfenergy.norm();
            selfenergy_correction_rel = Psi_SDE_diff_documentation.selfenergy.rel_deviation_to(dPsi.selfenergy);
            //TODO(low): Implement self-energy iterations (see lines 37-39 of pseudo-code).
            //if(selfEnergyConverged(Psi.selfenergy, Lambda))
            //    break;
#endif
            if constexpr (SELF_ENERGY_FLOW_CORRECTIONS) {
                utils::print("Self-energy iteration ", counter_Selfenergy_iterations, "\n");
                utils::print("Self-energy correction (abs.): ", selfenergy_correction_abs, "\n");
                utils::print("Self-energy correction (rel.): ", selfenergy_correction_rel*100, " %\n");
            }
            counter_Selfenergy_iterations++;
        }
//#endif
        }
        if (save) {record_of_intermediate_results.save_states(dir_str, iteration, rkStep, counter_Selfenergy_iterations);}
#if SELF_ENERGY_FLOW_CORRECTIONS != 0
    } while (nloops_max > 2 and counter_Selfenergy_iterations < nmax_Selfenergy_iterations and selfenergy_correction_abs > tol_selfenergy_correction_abs and selfenergy_correction_rel > tol_selfenergy_correction_rel);
#endif
    if (true and mpi_world_rank() == 0) { //
        utils::print("Time needed for evaluation of RHS --> ");
        utils::get_time(t0); // measure time for one iteration
    }
    stats.number_of_SE_iterations += counter_Selfenergy_iterations;
    stats.time += utils::get_time() - t0;
    State<Q,false> dPsi_return(Vertex<Q,false>(dPsi.vertex.half1()), dPsi.selfenergy, Psi.config, Lambda);
    return dPsi_return;
}
References anderson_update(), calculate_dGammaC_left_insertion(), calculate_dGammaC_right_insertion(), calculate_dGammaL(), calculate_dGammaR(), compare_with_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), data_dir, DEBUG_SYMMETRIES, mfRG_record< Q >::dPsi_1loop, utils::get_time(), loop_tol_abs, loop_tol_rel, utils::makedir(), mpi_world_rank(), SelfEnergy< Q >::norm(), utils::print(), SELF_ENERGY_FLOW_CORRECTIONS, selfEnergyFlowCorrections(), selfEnergyOneLoopFlow(), tol_selfenergy_correction_abs, tol_selfenergy_correction_rel, U_NRG, VERBOSE, GeneralVertex< Q, symmtype, differentiated >::vertex, State< Q, differentiated >::vertex, and vertexOneLoopFlow().
rhs_n_loop_flow() [2/2]
template<typename Q > auto rhs_n_loop_flow (const State< Q > & Psi, double Lambda, const fRG_config & config) -> State< Q >
Referenced by rhs_n_loop_flow_t< Q >::operator()().
selfEnergyConverged() [1/2]
template<typename Q > bool selfEnergyConverged (SelfEnergy< Q > & dPsiSelfEnergy, SelfEnergy< Q > & PsiSelfEnergy, Propagator< Q > & dG)
Definition at line 854 of file right_hand_sides.hpp.
{
    Propagator<Q> compare(dG.Lambda, PsiSelfEnergy, dPsiSelfEnergy, 'k', fRG_config());
    compare += dG*((Q)-1.);
    return (  compare.norm()/ dG.norm() < converged_tol );
}
References converged_tol, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
selfEnergyConverged() [2/2]
template<typename Q > auto selfEnergyConverged (SelfEnergy< Q > & dPsiSelfEnergy, SelfEnergy< Q > & PsiSelfEnergy, Propagator< Q > & dG) -> bool
Definition at line 854 of file right_hand_sides.hpp.
{
    Propagator<Q> compare(dG.Lambda, PsiSelfEnergy, dPsiSelfEnergy, 'k', fRG_config());
    compare += dG*((Q)-1.);
    return (  compare.norm()/ dG.norm() < converged_tol );
}
References converged_tol, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
selfEnergyFlowCorrections()
template<typename Q > void selfEnergyFlowCorrections (SelfEnergy< Q > & dPsiSelfEnergy, const GeneralVertex< Q, symmetric_r_irred, true > & dGammaC_tbar, const State< Q > & Psi, const Propagator< Q > & G)
The first selfenergy correction is given by dSigma_tbar = G * dGamma_tbar => dGamma_tbar has to be irreducible in the t-channel The second selfenergy correction is dSigma_t = (G dSigma_tbar G) * Gamma
Definition at line 831 of file right_hand_sides.hpp.
{
    // TODO(low): also implement self-energy flow via differentiated SDE
    // TODO(low): iterate self-energy corrections (feedback of full SE flow into vertex flow etc.)?
    SelfEnergy<Q> dSigma_tbar(Psi.selfenergy.Sigma.frequencies);
    SelfEnergy<Q> dSigma_t(Psi.selfenergy.Sigma.frequencies);
    // compute first multiloop correction to self-energy flow, irreducible in the t channel
    loop<true,0>(dSigma_tbar, dGammaC_tbar, G);
    // compute second multiloop correction to self-energy flow, reducible in the t channel
    Propagator<Q> extension (G.Lambda, Psi.selfenergy, dSigma_tbar, 'e', Psi.config);
    loop<true,0>(dSigma_t, Psi.vertex, extension);
    dPsiSelfEnergy = dSigma_tbar + dSigma_t;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and Propagator< Q >::Lambda.
Referenced by rhs_n_loop_flow().
selfEnergyOneLoopFlow()
template<typename Q > void selfEnergyOneLoopFlow (SelfEnergy< Q > & dPsiSelfEnergy, const Vertex< Q, false > & PsiVertex, const Propagator< Q > & S)
Definition at line 569 of file right_hand_sides.hpp.
{
    // Self-energy flow
    loop<true,0>(dPsiSelfEnergy, PsiVertex, S); // Loop for the Self-Energy calculation
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by rhs_n_loop_flow().
vertexConvergedInLoops() [1/2]
template<typename Q > bool vertexConvergedInLoops (Vertex< Q, true > & dGamma_T, Vertex< Q, true > & dGamma)
Definition at line 850 of file right_hand_sides.hpp.
{
    return (dGamma_T.norm() / dGamma.norm() < converged_tol);
}
References converged_tol, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
vertexConvergedInLoops() [2/2]
template<typename Q > auto vertexConvergedInLoops (Vertex< Q, true > & dGamma_T, Vertex< Q, true > & dGamma) -> bool
Definition at line 850 of file right_hand_sides.hpp.
{
    return (dGamma_T.norm() / dGamma.norm() < converged_tol);
}
References converged_tol, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
vertexOneLoopFlow()
template<typename Q , class Bubble_Object > void vertexOneLoopFlow (Vertex< Q, true > & dPsiVertex, const Vertex< Q, false > & Psi, const Bubble_Object & dPi, const fRG_config & config)
Definition at line 575 of file right_hand_sides.hpp.
{
    // Vertex flow
    if constexpr (SBE_DECOMPOSITION and MAX_DIAG_CLASS==2 and USE_NEW_MFRG_EQS) {
        Vertex<Q,false> One = PsiVertex;
        for (char r: {'a', 'p','t'}) {
            One.get_rvertex(r).K2 *= 0;
            if constexpr (DEBUG_SYMMETRIES) One.get_rvertex(r).K2b *= 0;
        }
        dPsiVertex *= 0;
        for (char r: {'a', 'p', 't'}) {
            bubble_function(dPsiVertex, PsiVertex, One, dPi, r, config);  // Differentiated bubble in channel r \in {a, p, t}
            if constexpr (DEBUG_SYMMETRIES) dPsiVertex.get_rvertex(r).K2b *= 0.;
            Vertex<Q,true> dPsiVertex_temp = dPsiVertex;
            dPsiVertex_temp *= 0.;
            bubble_function(dPsiVertex_temp, One, PsiVertex, dPi, r, config);  // Differentiated bubble in channel r \in {a, p, t}
            dPsiVertex_temp.get_rvertex(r).K2 *= 0.;
            dPsiVertex += dPsiVertex_temp;
            dPsiVertex_temp *= 0.;
            bubble_function(dPsiVertex_temp, One, One, dPi, r, config);  // Differentiated bubble in channel r \in {a, p, t}
            dPsiVertex_temp.get_rvertex(r).K2 *= 0.;
            if constexpr (DEBUG_SYMMETRIES) dPsiVertex_temp.get_rvertex(r).K2b *= 0.;
            dPsiVertex -= dPsiVertex_temp;
        }
    }
    else {
        for (char r: "apt") {
            bubble_function(dPsiVertex, PsiVertex, PsiVertex, dPi, r, config);  // Differentiated bubble in channel r \in {a, p, t}
        }
    }
}
References bubble_function(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and USE_NEW_MFRG_EQS.
Referenced by rhs_n_loop_flow().