SIAM-Keldysh-mfRG: flowgrid::log_parametrization Class Reference
flowgrid::log_parametrization Class Reference
#include <flow_grid.hpp>
Static Public Member Functions
static double lambda_from_t (double t)
static double t_from_lambda (double Lambda)
static double dlambda_dt (double t)
Detailed Description
Definition at line 58 of file flow_grid.hpp.
Member Function Documentation
dlambda_dt()
static double flowgrid::log_parametrization::dlambda_dt (double t) inline static
Definition at line 76 of file flow_grid.hpp.
        {
            return -Lambda_scale*pow(10, -t) * log(10);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Lambda_scale, and log().
lambda_from_t()
static double flowgrid::log_parametrization::lambda_from_t (double t) inline static
Definition at line 61 of file flow_grid.hpp.
        {
            double value = Lambda_scale*(pow(10, -t) - 1);
            assert (isfinite(value));
            return value; // -t;//
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and Lambda_scale.
t_from_lambda()
static double flowgrid::log_parametrization::t_from_lambda (double Lambda) inline static
Definition at line 68 of file flow_grid.hpp.
        {
            double value = -log10(1 + Lambda/Lambda_scale);
            assert (isfinite(value));
            return value; // -Lambda;//
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and Lambda_scale.
The documentation for this class was generated from the following file:
flow_grid.hpp