SIAM-Keldysh-mfRG: math_utils.c++ File Reference
math_utils.c++ File Reference
#include "math_utils.hpp"
Functions
auto heaviside (const double x) -> double
double sgn (const double x)
int integer_division_ceil (int a, int b)
int integer_division_floor (int a, int b)
auto round2Infty (const double x) -> double
auto myround (const double x) -> double
auto floor2bfreq (const int w) -> int
auto ceil2bfreq (const int w) -> int
auto floor2bfreq (const double w) -> double
auto ceil2bfreq (const double w) -> double
auto round2bfreq (const double w) -> double
auto round2ffreq (const double w) -> double
auto signFlipCorrection_MF (const freqType w) -> freqType
int signFlipCorrection_MF_int (const freqType w)
auto is_doubleOccurencies (const vec< freqType > &freqs) -> int
auto is_symmetric (const rvec &freqs) -> double
template<>
void switch2bosonicFreqs< 'p'> (double &w_in, double &v1_in, double &v2_in)
Functions for change of coordinates (for 2D and 3D):
template<>
void switch2bosonicFreqs< 't'> (double &w_in, double &v1_in, double &v2_in)
template<>
void switch2naturalFreqs< 'p'> (double &w_a, double &w_p, double &w_t)
template<>
void switch2naturalFreqs< 't'> (double &w_a, double &w_p, double &w_t)
void K2_convert2internalFreqs (freqType &w, freqType &v)
converts the frequencies to the parametrization that is used internally, e.g. rotate frequency plane
void K2_convert2naturalFreqs (freqType &w, freqType &v)
void K3_convert2internalFreqs (freqType &w, freqType &v, freqType &vp)
void K3_convert2naturalFreqs (freqType &w, freqType &v, freqType &vp)
Function Documentation
ceil2bfreq() [1/2]
auto ceil2bfreq (const double w) -> double
Definition at line 87 of file math_utils.c++.
{
    const double tol = 1e-8;
    const double a = (2.);
    const double result = ceil(w / a-tol) * a;
    assert(result >= w);
    assert(result <= w + 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
ceil2bfreq() [2/2]
auto ceil2bfreq (const int w) -> int
Definition at line 71 of file math_utils.c++.
{
    const int a = 2;
    const double result = integer_division_ceil(w , a) * a;
    assert(result >= w);
    assert(result <= w + 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integer_division_ceil().
Referenced by oneBubble< Q >::convert_to_fermionic_frequencies_1(), Bubble< Q >::convert_to_fermionic_frequencies_1(), oneBubble< Q >::convert_to_fermionic_frequencies_2(), Bubble< Q >::convert_to_fermionic_frequencies_2(), and Bubble< Q >::value().
floor2bfreq() [1/2]
auto floor2bfreq (const double w) -> double
Definition at line 79 of file math_utils.c++.
{
    const double tol = 1e-8;
    const double a = (2.);
    const double result = floor(w / a+tol) * a;
    assert(result <= w);
    assert(result >= w - 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
floor2bfreq() [2/2]
auto floor2bfreq (const int w) -> int
Definition at line 64 of file math_utils.c++.
{
    const int a = 2;
    const int result = integer_division_floor(w , a) * a;
    assert(result <= w);
    assert(result >= w - 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integer_division_floor().
Referenced by oneBubble< Q >::convert_to_fermionic_frequencies_1(), Bubble< Q >::convert_to_fermionic_frequencies_1(), oneBubble< Q >::convert_to_fermionic_frequencies_2(), Bubble< Q >::convert_to_fermionic_frequencies_2(), rvert< Q >::transfToR(), and Bubble< Q >::value().
heaviside()
auto heaviside (const double x) -> double
Definition at line 3 of file math_utils.c++.
{
    if (x > 0.0){
        return 1.0;
    }
    else if (x < 0.0){
        return 0.0;
    }
    else if (x == 0.0){
        return 0.5;
    }
    else {
        std::cout << "x ill-defined! \n";
        assert(false);
        return 0.;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
integer_division_ceil()
int integer_division_ceil (int a, int b)
Definition at line 25 of file math_utils.c++.
{
    assert(b>0);
    if (a >= 0) {
        const int result = (a + b - 1) / b;
        return result;
    }
    else {
        const int result = - ((-a) / b);
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by ceil2bfreq().
integer_division_floor()
int integer_division_floor (int a, int b)
Definition at line 37 of file math_utils.c++.
{
    assert(b>0);
    if (a >= 0) {
        const int result = a / b;
        assert(result <= a);
        return result;
    }
    else {
        const int result = - ((-a + b - 1) / b);
        assert(result <= 0);
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by floor2bfreq().
is_doubleOccurencies()
auto is_doubleOccurencies (const vec< freqType > & freqs) -> int
Definition at line 128 of file math_utils.c++.
{
    for (unsigned int i = 0; i < freqs.size() - 1; i++){
        if (freqs[i] == freqs[i+1]) return 1;
    }
    return 0;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::initialize_grid(), and FrequencyGrid< hybridGrid >::initialize_grid().
is_symmetric()
auto is_symmetric (const rvec & freqs) -> double
Definition at line 135 of file math_utils.c++.
{
    double asymmetry = 0;
    for (unsigned int i = 0; i< freqs.size() - 1; i++){
        asymmetry += std::abs(freqs[i] + freqs[freqs.size()-i-1]);
    }
    return asymmetry;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
K2_convert2internalFreqs()
void K2_convert2internalFreqs (freqType & w, freqType & v)
converts the frequencies to the parametrization that is used internally, e.g. rotate frequency plane
Insert this function before interpolation
need to convert natural parametrization to internal coordinates when interpolating
convert frequencies w and v to polar coordinates rho and phi (with phi in [-Pi, Pi])
Definition at line 184 of file math_utils.c++.
{
#ifdef ROTATEK2
    // The internal parametrization corresponds to the fermionic frequencies at the two fermionic legs of K2
    const double w_tmp = w*0.5 + v;
    const double v_tmp = w*0.5 - v;
    w = w_tmp;
    v = v_tmp;
#endif
    if constexpr (GRID == 2) {
        const double rho = sqrt(w*w*0.25 + v*v);
        const double phi = atan2(v,  w*0.5); //rho < 1e-15 ? 0. : acos(  w*0.5 / rho);
        assert(isfinite(phi));
        assert(std::abs(phi) < M_PI + 1e-15);
        assert(rho > -1e-15);
        v = phi;// * (v > 0 ? 1. : -1.);
        w = rho;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_grid_index(), and bufferFrequencyGrid< k >::is_in_box().
K2_convert2naturalFreqs()
void K2_convert2naturalFreqs (freqType & w, freqType & v)
Insert this function before returning frequency values
need to convert internal coordinates to natural parametrization when retrieving frequencies at a specific grid point -> get_freqs_w(w,v)
convert polar coordinates to frequencies (w,v) = rho * (cos phi * 2, sin phi)
Definition at line 204 of file math_utils.c++.
{
    if constexpr (GRID == 2) {
        const double w_temp = w * cos(v) * 2;
        const double v_temp = w * sin(v);
        w = w_temp;
        v = v_temp;
    }
#ifdef ROTATEK2
    const double w_tmp = w + v;
    const double v_tmp =(w - v)*0.5;
    w = w_tmp;
    v = v_tmp;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_freqs_w().
K3_convert2internalFreqs()
void K3_convert2internalFreqs (freqType & w, freqType & v, freqType & vp)
Insert this function before interpolation
need to convert natural parametrization to internal coordinates when interpolating
Definition at line 222 of file math_utils.c++.
{
    if constexpr (GRID == 2) {
        // for spherical coordinates:
        // (vp, v, w/2) = rho * (cos phi * sin theta, cos phi * sin theta, cos theta)
        // rho = || (vp, v, w/2) ||
        // phi = atan(v / vp)
        // theta = acos(w/2 / rho)
        const double rho = sqrt(w*w*0.25 + v*v + vp*vp);
        const double phi = atan2(  v, vp);
        const double theta = rho < 1e-15 ? 0. : acos(w*0.5/rho);
        //const double r = sqrt(v*v + vp*vp);
        //const double theta = atan2(r, w*0.5);
        assert(isfinite(phi));
        vp = theta;
        v = phi;
        assert(std::abs(phi) < M_PI + 1e-15);
        assert(theta > -1e-15);
        assert(rho > -1e-15);
        w = rho;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_grid_index(), and bufferFrequencyGrid< k >::is_in_box().
K3_convert2naturalFreqs()
void K3_convert2naturalFreqs (freqType & w, freqType & v, freqType & vp)
Insert this function before returning frequency values
need to convert internal coordinates to natural parametrization when retrieving frequencies at a specific grid point -> get_freqs_w(w,v,vp)
Definition at line 245 of file math_utils.c++.
{
    if constexpr (GRID == 2) {
        // for spherical coordinates:
        // (vp, v, w/2) = rho * (cos phi * sin theta, cos phi * sin theta, cos theta)
        const double vp_temp = w * cos(v) * sin(vp);
        const double v_temp  = w * sin(v) * sin(vp);
        const double w_temp= w          * cos(vp) * 2;
        w = w_temp;
        v = v_temp;
        vp = vp_temp;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_freqs_w().
myround()
auto myround (const double x) -> double
Definition at line 58 of file math_utils.c++.
{
    const double tol = 1e-10;
    if (x <= -0.5) return floor(x+tol);
    else return ceil(x-tol);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
round2bfreq()
auto round2bfreq (const double w) -> double
Definition at line 96 of file math_utils.c++.
{
    const int w_int = (int) (w + 0.1*sign(w));
    const double result = 2.* (double) (w_int / 2); // rounding toward zero in integer division
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sign().
Referenced by FrequencyGrid< eliasGrid >::set_essential_parameters().
round2ffreq()
auto round2ffreq (const double w) -> double
Definition at line 101 of file math_utils.c++.
{
    const int w_int = (int) (w + 0.1*sign(w));
    const double result = 2.* (double) ((w_int-1) / 2) + 1.; // rounding toward zero in integer division
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sign().
Referenced by FrequencyGrid< eliasGrid >::set_essential_parameters().
round2Infty()
auto round2Infty (double x) -> double
Functions for rounding to Matsubara frequencies
Definition at line 51 of file math_utils.c++.
{
    const double tol = 1e-10;
    // trunc() rounds towards zero
    if (x <= 0.) return floor(x+tol);
    else return ceil(x-tol);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
sgn()
double sgn (const double x)
Definition at line 21 of file math_utils.c++.
{
    return (x >= 0) - (x <= 0); // (x > 0) ? 1. : ((x < 0) ? -1. : 0.);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Fermi_fac(), FrequencyGrid< angularGrid >::frequency_from_t(), FrequencyGrid< hybridGrid >::frequency_from_t(), grid_transf_inv_v4(), grid_transf_v2(), grid_transf_v4(), boost::numeric::odeint::detail::integrate_nonadaptive(), integration_measure_v2(), integration_measure_v4(), ode_solver_impl::rkqs(), FrequencyGrid< angularGrid >::t_from_frequency(), and FrequencyGrid< hybridGrid >::t_from_frequency().
signFlipCorrection_MF()
auto signFlipCorrection_MF (const freqType w) -> freqType
Definition at line 107 of file math_utils.c++.
{
#if not KELDYSH_FORMALISM and not ZERO_TEMP
    const freqType correction = signFlipCorrection_MF_int(w) * 2;
    return correction;
#else
    assert(false);
    return 0.;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and signFlipCorrection_MF_int().
Referenced by rvert< Q >::enforce_freqsymmetriesK2(), rvert< Q >::enforce_freqsymmetriesK3(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K2(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K3(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_value(), bufferFrequencyGrid< k >::is_in_box(), T1(), T2(), TC(), and TR().
signFlipCorrection_MF_int()
int signFlipCorrection_MF_int (const freqType w)
Definition at line 117 of file math_utils.c++.
{
#if not KELDYSH_FORMALISM and not ZERO_TEMP
    const int correction = -((int) (std::abs(w / 2) ) ) % 2;
    assert(correction==0 or correction == -1);
    return correction;
#else
    assert(false);
    return 0;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl(), and signFlipCorrection_MF().
switch2bosonicFreqs< 'p'>()
template<> void switch2bosonicFreqs< 'p'> (double & w_in, double & v1_in, double & v2_in)
Functions for change of coordinates (for 2D and 3D):
Definition at line 146 of file math_utils.c++.
{
    double w, v1, v2;
    w  = -v1_in - v2_in;                    // input.w  = w_p
    v1 =  w_in;                              // input.v1 = v_p
    v2 =  v1_in - v2_in;                    // input.v2 = v'_p
    w_in  = w;
    v1_in = v1;
    v2_in = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2bosonicFreqs< 't'>()
template<> void switch2bosonicFreqs< 't'> (double & w_in, double & v1_in, double & v2_in)
Definition at line 155 of file math_utils.c++.
{
    double w, v1, v2;
    w  = v1_in - v2_in;                    // input.w  = w_t
    v1 = v1_in + v2_in;                    // input.v1 = v_t
    v2 = w_in;                              // input.v2 = v'_t
    w_in  = w;
    v1_in = v1;
    v2_in = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2naturalFreqs< 'p'>()
template<> void switch2naturalFreqs< 'p'> (double & w_a, double & w_p, double & w_t)
Definition at line 165 of file math_utils.c++.
{
    double w, v1, v2;
    w  = w_p;                             // input.w  = w_a
    v1 = 0.5*( - w_a + w_t);              // input.v1 = w_p
    v2 = 0.5*( - w_a - w_t);              // input.v2 = w_t
    w_a  = w;
    w_p = v1;
    w_t = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2naturalFreqs< 't'>()
template<> void switch2naturalFreqs< 't'> (double & w_a, double & w_p, double & w_t)
Definition at line 174 of file math_utils.c++.
{
    double w, v1, v2;
    w  = w_t;                             // input.w  = w_a
    v1 = 0.5*( w_a + w_p);               // input.v1 = w_p
    v2 = 0.5*(-w_a + w_p);               // input.v2 = w_t
    w_a  = w;
    w_p = v1;
    w_t = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().