SIAM-Keldysh-mfRG: dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, > Class Template Reference
dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, > Class Template Reference
#include <data_buffer.hpp>
Public Types
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
Public Types inherited from Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >, inter >
using index_type
using dimensions_type
Public Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
using buffer_type = typename base_class::buffer_type
Public Member Functions
dataBuffer ()
dataBuffer (double Lambda, dimensions_type dims, const fRG_config &config)
void center_frequency_grids (const std::array< double, 3 > shifts)
template<typename result_type = Q, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true>
result_type interpolate (const VertexInput &input) const
void update_grid (double Lambda, std::array< double, 3 > shifts, const fRG_config &config)
void update_grid (const frequencyGrid_type &frequencies_new, const this_class &buffer4data)
void optimize_grid (bool verbose)
void check_if_frequencyGrid_identical (const this_class &rhs) const
auto operator+= (const this_class &rhs) -> this_class
auto operator-= (const this_class &rhs) -> this_class
auto operator*= (const this_class &rhs) -> this_class
auto operator/= (const this_class &rhs) -> this_class
auto operator+= (const double rhs) -> this_class
auto operator-= (const double rhs) -> this_class
auto operator*= (const double rhs) -> this_class
auto operator/= (const double rhs) -> this_class
Public Member Functions inherited from Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >, inter >
Interpolator ()
Interpolator (double Lambda, dimensions_type dims, const fRG_config &config)
void initInterpolator () const
void set_initializedInterpol (const bool is) const
Eigen::Matrix< double, numSamples(), 1 > get_weights (const frequencies_type &frequencies, index_type &idx_low) const
auto interpolate_impl (const frequencies_type &frequencies, index_type indices) const -> result_type
Public Member Functions inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
DataContainer ()=default
DataContainer (double Lambda, dimensions_type dims, const fRG_config &config)
auto get_VertexFreqGrid () const -> const frequencyGrid_type &
Functions for getting and setting the frequency grid and its members.
void set_VertexFreqGrid (const frequencyGrid_type frequencyGrid)
template<unsigned int idim, typename std::enable_if_t<(idim< numberFrequencyDims), bool > = true>
double analyze_tails (const int index=0) const
buffer_type get_deriv_x (const buffer_type &dat) const
buffer_type get_deriv_y (const buffer_type &dat) const
buffer_type get_deriv_z (const buffer_type &dat) const
buffer_type get_deriv_xx () const
buffer_type get_deriv_yy () const
buffer_type get_deriv_zz () const
buffer_type get_deriv_xy () const
buffer_type get_deriv_xz () const
buffer_type get_deriv_yz () const
buffer_type get_deriv_xyz () const
auto get_deriv_max () const -> double
auto get_curvature_max () const -> double
template<typename gridType >
auto shrink_freq_box_impl (const gridType &freqGrid, const double rel_tail_threshold, const vec< double > &maxabs_along_x, const bool verbose) const -> gridType
auto shrink_freq_box (const double rel_tail_threshold, bool verbose=true, double constant=0.) const -> frequencyGrid_type
Public Member Functions inherited from dataContainerBase< Q, rank >
dataContainerBase ()=default
constructor:
dataContainerBase (const dimensions_type dims)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
dataContainerBase (const Types &... dims)
dataContainerBase (const buffer_type &data_in)
Q acc (const size_t flatIndex) const
Access data via flattened index.
void direct_set (const size_t flatIndex, Q value)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
Q val (const Types &... i) const
Returns value for a multiIndex.
Q val (const index_type &idx) const
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
const Q & at (const Types &... i) const
Returns reference to a value for a multiIndex.
template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true>
auto val_vectorized (const Types &... i) const -> Eigen::Matrix< Q, vecsize, 1 >
template<std::size_t freqrank, std::size_t vecsize>
auto val_vectorized (const index_type &idx) const -> Eigen::Matrix< Q, vecsize, 1 >
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
void setvert (const Q value, const Types &... i)
Sets a value at a multiIndex.
void setvert (const Q value, const index_type &idx)
template<std::size_t vecsize>
void setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > &value, const index_type &idx)
auto get_dims () const
const buffer_type & get_vec () const
Returns the buffer "data" containing the data.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void set_vec (const container &data_in)
Sets the the buffer "data".
void set_vec (const buffer_type &data_in)
void set_vec (const buffer_type &&data_in)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void add_vec (const container &summand)
Adds a vector to the data.
void add_vec (const buffer_type &summand)
constexpr auto eigen_segment (const index_type &start, const index_type &end)
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> get_values (const index_type &index) const
Private Types
using base_class = Interpolator<Q, rank, numberFrequencyDims, pos_first_freqpoint, DataContainer<Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type>, inter>
using this_class = dataBuffer<Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter>
using frequencies_type = std::array<freqType, numberFrequencyDims>
Friends
this_class operator+ (const this_class &lhs, const this_class &rhs)
this_class operator- (const this_class &lhs, const this_class &rhs)
this_class operator* (const this_class &lhs, const this_class &rhs)
this_class operator/ (const this_class &lhs, const this_class &rhs)
this_class operator+ (const this_class &lhs, const double rhs)
this_class operator- (const this_class &lhs, const double rhs)
this_class operator* (const this_class &lhs, const double rhs)
this_class operator+ (const double rhs, const this_class &lhs)
this_class operator* (const double rhs, const this_class &lhs)
this_class operator/ (const this_class &lhs, const double rhs)
Additional Inherited Members
Public Attributes inherited from Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >, inter >
bool initialized
Public Attributes inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
frequencyGrid_type frequencies
Protected Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using base_class = dataContainerBase<Q, rank>
Protected Types inherited from dataContainerBase< Q, rank >
using buffer_type = multidimensional::multiarray<Q, rank>
using index_type = typename buffer_type::index_type
using dimensions_type = typename buffer_type::dimensions_type
Protected Attributes inherited from dataContainerBase< Q, rank >
buffer_type data
Detailed Description
template<typename Q, K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type, interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true>
class dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >
Stores and interpolates data
Template Parameters
Q type of data
k K_class selfenergy / k1 / k2 / k2b / k3
rank number of dimensions
numberFrequencyDims number of frequency indices
pos_first_freqpoint position of first frequency index
frequencyGrid_type frequency grid
inter interpolation method
Definition at line 659 of file data_buffer.hpp.
Member Typedef Documentation
base_class
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> using dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::base_class = Interpolator<Q, rank, numberFrequencyDims, pos_first_freqpoint, DataContainer<Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type>, inter> private
Definition at line 660 of file data_buffer.hpp.
dimensions_type
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> using dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::dimensions_type = typename base_class::dimensions_type
Definition at line 666 of file data_buffer.hpp.
frequencies_type
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> using dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::frequencies_type = std::array<freqType, numberFrequencyDims> private
Definition at line 662 of file data_buffer.hpp.
index_type
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> using dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::index_type = typename base_class::index_type
Definition at line 665 of file data_buffer.hpp.
this_class
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> using dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::this_class = dataBuffer<Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter> private
Definition at line 661 of file data_buffer.hpp.
Constructor & Destructor Documentation
dataBuffer() [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::dataBuffer () inline
Definition at line 668 of file data_buffer.hpp.
: base_class() {};
dataBuffer() [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::dataBuffer (double Lambda, dimensions_type dims, const fRG_config & config) inline explicit
Definition at line 669 of file data_buffer.hpp.
: base_class(Lambda, dims, config) {};
Member Function Documentation
center_frequency_grids()
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> void dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::center_frequency_grids (const std::array< double, 3 > shifts) inline
shifting the center of the frequency grids is only allowed if no data is in the buffers yet.
Definition at line 671 of file data_buffer.hpp.
{
        assert(base_class::data.max_norm() < 1.e-10);
        base_class::frequencies.  primary_grid.set_w_center(shifts[0]);
        base_class::frequencies.secondary_grid.set_w_center(shifts[1]);
        base_class::frequencies. tertiary_grid.set_w_center(shifts[2]);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
check_if_frequencyGrid_identical()
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> void dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::check_if_frequencyGrid_identical (const this_class & rhs) const inline
Definition at line 813 of file data_buffer.hpp.
{
#if not defined(NDEBUG)
        if ((base_class::frequencies.primary_grid.get_all_frequencies() - rhs.frequencies.primary_grid.get_all_frequencies()).max_norm() > 1e-10) {
            throw std::runtime_error("Arithmetic operations involving databuffers with different frequency grids are forbidden.");
        }
        if constexpr (numberFrequencyDims > 1) {
            if((base_class::frequencies.secondary_grid.get_all_frequencies() - rhs.frequencies.secondary_grid.get_all_frequencies()).max_norm() > 1e-10) {
                throw std::runtime_error("Arithmetic operations involving databuffers with different frequency grids are forbidden.");
            }
        }
#endif
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
interpolate()
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> template<typename result_type = Q, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> result_type dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::interpolate (const VertexInput & input) const inline
Definition at line 680 of file data_buffer.hpp.
{
        return base_class::template interpolate_impl<result_type>(input.template get_freqs<k>(), input.template get_indices<k>());
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*=() [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator*= (const double rhs) -> this_class inline
Definition at line 855 of file data_buffer.hpp.
{base_class::data *= rhs; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*=() [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator*= (const this_class & rhs) -> this_class inline
Definition at line 829 of file data_buffer.hpp.
{check_if_frequencyGrid_identical(rhs); base_class::data *= rhs.data; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+=() [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator+= (const double rhs) -> this_class inline
Definition at line 853 of file data_buffer.hpp.
{base_class::data += rhs; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator+=() [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator+= (const this_class & rhs) -> this_class inline
Definition at line 827 of file data_buffer.hpp.
{check_if_frequencyGrid_identical(rhs); base_class::data += rhs.data; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-=() [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator-= (const double rhs) -> this_class inline
Definition at line 854 of file data_buffer.hpp.
{base_class::data -= rhs; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator-=() [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator-= (const this_class & rhs) -> this_class inline
Definition at line 828 of file data_buffer.hpp.
{check_if_frequencyGrid_identical(rhs); base_class::data -= rhs.data; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/=() [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator/= (const double rhs) -> this_class inline
Definition at line 856 of file data_buffer.hpp.
{base_class::data /= rhs; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator/=() [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::operator/= (const this_class & rhs) -> this_class inline
Definition at line 830 of file data_buffer.hpp.
{check_if_frequencyGrid_identical(rhs); base_class::data /= rhs.data; return *this;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
optimize_grid()
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> void dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::optimize_grid (bool verbose) inline
shrink grid
Optimize grid parameters in first direction
in other direction(s)
no optimization for angular grid
Definition at line 725 of file data_buffer.hpp.
{
        if (verbose) utils::print("---> Now Optimize grid for ", k, " in direction w:\n");
        const bool superverbose = false;
        const double epsrel = 0.01;
        const double epsabs = 0.0;
        frequencyGrid_type frequencies_new = base_class::get_VertexFreqGrid();
        const double rel_tail_threshold = 1e-6;
        frequencies_new = base_class::shrink_freq_box(rel_tail_threshold, verbose);
        update_grid(frequencies_new, *this);
        if (verbose and mpi_world_rank() == 0) {
            std::cout << "rel.tail height in direction w: " << base_class::template analyze_tails<0>() << std::endl;
        }
        if constexpr(std::is_same_v<typename frequencyGrid_type::grid_type1, FrequencyGrid<eliasGrid>>) {
            double a_Wscale_b = base_class::get_VertexFreqGrid().  primary_grid.W_scale / 2.;
            double m_Wscale_b = base_class::get_VertexFreqGrid().  primary_grid.W_scale;
            double b_Wscale_b = base_class::get_VertexFreqGrid().  primary_grid.W_scale * 2;
            CostResolution<'b', this_class, frequencyGrid_type> cost_b(*this, verbose);
            minimizer(cost_b, a_Wscale_b, m_Wscale_b, b_Wscale_b, 20, verbose, superverbose, epsabs, epsrel);
            frequencies_new.  primary_grid.update_Wscale(m_Wscale_b);
        }
        else if constexpr(std::is_same_v<typename frequencyGrid_type::grid_type1, FrequencyGrid<hybridGrid>>) {
            std::array<double,2> section_boundaries_b = base_class::get_VertexFreqGrid().  primary_grid.pos_section_boundaries;
            vec<double> start_params_b = {section_boundaries_b[0], section_boundaries_b[1]};
            CostResolution<'b',this_class,frequencyGrid_type> cost_b(*this, verbose);
            double ini_stepsize_b = (section_boundaries_b[0] + section_boundaries_b[1])/10.;
            vec<double> result_b = minimizer_nD(cost_b, start_params_b, ini_stepsize_b, 100, verbose, superverbose, epsabs, epsrel);
            frequencies_new.  primary_grid.update_pos_section_boundaries(std::array<double,2>({result_b[0], result_b[1]}));
        }
        else if constexpr (std::is_same_v<typename frequencyGrid_type::grid_type1, FrequencyGrid<angularGrid>>) {
            double a_power_b = base_class::get_VertexFreqGrid().  primary_grid.power / 2.;
            double m_power_b = base_class::get_VertexFreqGrid().  primary_grid.power;
            double b_power_b = base_class::get_VertexFreqGrid().  primary_grid.power * 2;
            CostResolution<'b', this_class, frequencyGrid_type> cost_b(*this, verbose);
            minimizer(cost_b, a_power_b, m_power_b, b_power_b, 20, verbose, superverbose, epsabs, epsrel);
            frequencies_new.  primary_grid.update_power(m_power_b);
        }
        update_grid(frequencies_new, *this);
        if constexpr (numberFrequencyDims > 1) {
            if constexpr(std::is_same_v<typename frequencyGrid_type::grid_type2, FrequencyGrid<eliasGrid>>) {
                double a_Wscale_f = base_class::get_VertexFreqGrid().secondary_grid.W_scale / 2.;
                double m_Wscale_f = base_class::get_VertexFreqGrid().secondary_grid.W_scale;
                double b_Wscale_f = base_class::get_VertexFreqGrid().secondary_grid.W_scale * 2;
                CostResolution<'f', this_class, frequencyGrid_type> cost_f(*this, verbose);
                minimizer(cost_f, a_Wscale_f, m_Wscale_f, b_Wscale_f, 20, verbose, superverbose, epsabs, epsrel);
                frequencies_new.secondary_grid.update_Wscale(m_Wscale_f);
                frequencies_new. tertiary_grid.update_Wscale(m_Wscale_f);
            }
            else if constexpr(std::is_same_v<typename frequencyGrid_type::grid_type2, FrequencyGrid<hybridGrid>>) {
                std::array<double,2> section_boundaries_f = base_class::get_VertexFreqGrid().secondary_grid.pos_section_boundaries;
                vec<double> start_params_f = {section_boundaries_f[0], section_boundaries_f[1]};
                CostResolution<'f',this_class,frequencyGrid_type> cost_f(*this, verbose);
                double ini_stepsize_f = (section_boundaries_f[0] + section_boundaries_f[1])/10.;
                vec<double> result_f = minimizer_nD(cost_f, start_params_f, ini_stepsize_f, 100, verbose, superverbose, epsabs, epsrel);
                frequencies_new.secondary_grid.update_pos_section_boundaries(std::array<double,2>({result_f[0], result_f[1]}));
                frequencies_new. tertiary_grid.update_pos_section_boundaries(std::array<double,2>({result_f[0], result_f[1]}));
            }
            else if constexpr (std::is_same_v<typename frequencyGrid_type::grid_type2, FrequencyGrid<angularGrid>>) {
                double a_power_f = base_class::get_VertexFreqGrid().secondary_grid.power / 2.;
                double m_power_f = base_class::get_VertexFreqGrid().secondary_grid.power;
                double b_power_f = base_class::get_VertexFreqGrid().secondary_grid.power * 2;
                CostResolution<'f', this_class, frequencyGrid_type> cost_f(*this, verbose);
                minimizer(cost_f, a_power_f, m_power_f, b_power_f, 20, verbose, superverbose, epsabs, epsrel);
                frequencies_new.secondary_grid.update_power(m_power_f);
                frequencies_new. tertiary_grid.update_power(m_power_f);
            }
            update_grid(frequencies_new, *this);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), minimizer(), minimizer_nD(), mpi_world_rank(), and utils::print().
update_grid() [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> void dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::update_grid (const frequencyGrid_type & frequencies_new, const this_class & buffer4data) inline
Definition at line 700 of file data_buffer.hpp.
{
        using buffer_type = multidimensional::multiarray<Q,rank>;
        buffer4data.initInterpolator();
        const dimensions_type dims = base_class::get_dims();
        const size_t flatsize = getFlatSize<rank>(dims);
        buffer_type data_new (dims);  // temporary data vector
#pragma omp parallel
        for (my_index_t iflat=0; iflat < flatsize; ++iflat) {
            index_type idx;
            std::array<my_index_t, numberFrequencyDims> i_freqs;
            frequencies_type freqs;
            getMultIndex<rank>(idx, iflat, dims);
            for (my_index_t i = 0; i < numberFrequencyDims; i++) {
                i_freqs[i] = idx[i+pos_first_freqpoint];
            }
            frequencies_new.get_freqs_w(freqs, i_freqs);
            // interpolate old values to new vector
            Q value =  buffer4data.interpolate_impl(freqs, idx);
            data_new.at(idx) = value;
        }
        base_class::set_vec(std::move(data_new)); // update vertex to new interpolated values
        base_class::set_VertexFreqGrid(frequencies_new);
        buffer4data.set_initializedInterpol(false);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
update_grid() [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> void dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::update_grid (double Lambda, std::array< double, 3 > shifts, const fRG_config & config) inline
updates frequency grids by rescaling with Lambda
Parameters
Lambda
shifts determines how much the centers of the frequency grids need to be shifted this shift can be non-zero for runs outside of PHS
config
Definition at line 691 of file data_buffer.hpp.
{
        frequencyGrid_type frequencies_new = base_class::get_VertexFreqGrid();  // new frequency grid
        frequencies_new.guess_essential_parameters(Lambda, config);                     // rescale new frequency grid
        frequencies_new.  primary_grid.set_w_center(shifts[0]);
        frequencies_new.secondary_grid.set_w_center(shifts[1]);
        frequencies_new. tertiary_grid.set_w_center(shifts[2]);
        update_grid(frequencies_new, *this);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by SelfEnergy< Q >::update_grid().
Friends And Related Symbol Documentation
operator* [1/3]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator* (const double rhs, const this_class & lhs) friend
Definition at line 877 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp *= rhs;
        return lhs_temp;
    }
operator* [2/3]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator* (const this_class & lhs, const double rhs) friend
Definition at line 867 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp *= rhs;
        return lhs_temp;
    }
operator* [3/3]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator* (const this_class & lhs, const this_class & rhs) friend
Definition at line 841 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp *= rhs;
        return lhs_temp;
    }
operator+ [1/3]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator+ (const double rhs, const this_class & lhs) friend
Definition at line 872 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp += rhs;
        return lhs_temp;
    }
operator+ [2/3]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator+ (const this_class & lhs, const double rhs) friend
Definition at line 857 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp += rhs;
        return lhs_temp;
    }
operator+ [3/3]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator+ (const this_class & lhs, const this_class & rhs) friend
Definition at line 831 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp += rhs;
        return lhs_temp;
    }
operator- [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator- (const this_class & lhs, const double rhs) friend
Definition at line 862 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp -= rhs;
        return lhs_temp;
    }
operator- [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator- (const this_class & lhs, const this_class & rhs) friend
Definition at line 836 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp -= rhs;
        return lhs_temp;
    }
operator/ [1/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator/ (const this_class & lhs, const double rhs) friend
Definition at line 882 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp /= rhs;
        return lhs_temp;
    }
operator/ [2/2]
template<typename Q , K_class k, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type , interpolMethod inter, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> this_class operator/ (const this_class & lhs, const this_class & rhs) friend
Definition at line 846 of file data_buffer.hpp.
{
        this_class lhs_temp = lhs;
        lhs_temp /= rhs;
        return lhs_temp;
    }
The documentation for this class was generated from the following file:
data_buffer.hpp