SIAM-Keldysh-mfRG: loop_corrections.hpp File Reference
loop_corrections.hpp File Reference
#include <cmath>
#include "../data_structures.hpp"
#include "../correlation_functions/four_point/vertex.hpp"
#include "../parameters/master_parameters.hpp"
#include "../utilities/util.hpp"
#include "bubble_corrections.hpp"
Functions
template<typename Q >
auto correctionFunctionSelfEnergy_Keldysh (int iK, double vmin, double vmax, Q eps_p, double Delta, char type) -> Q
template<>
auto correctionFunctionSelfEnergy_Keldysh (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
template<typename Q >
auto correctionFunctionSelfEnergy_Matsubara_PHS (int iK, double vmin, double vmax, Q eps_p, double Delta, char type) -> Q
template<typename Q >
auto correctionFunctionSelfEnergy_Matsubara_NoPHS (int iK, double vmin, double vmax, Q eps_p, double Delta, char type) -> Q
template<>
auto correctionFunctionSelfEnergy_Matsubara_NoPHS (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
template<typename Q >
auto correctionFunctionSelfEnergy (int iK, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, char type) -> Q
Function Documentation
correctionFunctionSelfEnergy()
template<typename Q > auto correctionFunctionSelfEnergy (int iK, double vmin, double vmax, double epsilon, Q Sigma_H, double Delta, char type) -> Q
Definition at line 83 of file loop_corrections.hpp.
{
    Q eps_p = epsilon + Sigma_H;
    if (KELDYSH)                    return correctionFunctionSelfEnergy_Keldysh(iK, vmin, vmax, eps_p, Delta, type);
    else{
        if (PARTICLE_HOLE_SYMMETRY) return correctionFunctionSelfEnergy_Matsubara_PHS(iK, vmin, vmax, eps_p, Delta, type);
        else                        return correctionFunctionSelfEnergy_Matsubara_NoPHS(iK, vmin, vmax, eps_p, Delta, type);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), correctionFunctionSelfEnergy_Keldysh(), correctionFunctionSelfEnergy_Matsubara_NoPHS(), correctionFunctionSelfEnergy_Matsubara_PHS(), KELDYSH, and PARTICLE_HOLE_SYMMETRY.
Referenced by asymp_corrections_loop().
correctionFunctionSelfEnergy_Keldysh() [1/2]
template<> auto correctionFunctionSelfEnergy_Keldysh (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
Definition at line 4 of file loop_corrections.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
correctionFunctionSelfEnergy_Keldysh() [2/2]
template<typename Q > auto correctionFunctionSelfEnergy_Keldysh (int iK, double vmin, double vmax, Q eps_p, double Delta, char type) -> Q
Helper function for computing the analytical result for the asymptotic tails of the loop integral, assuming the self-energy of the propagator to be decayed to the Hartree value. See the function asymp_corrections_loop below.
Parameters
iK : Type of the loop propagator 0: G^R, 1: G^A, 2: G^K
vmin : Lower limit of the numerically evaluated integral
vmax : Upper limit of the numerically evaluated integral
Sigma_H : Hartree self-energy
Delta : Hybridization (~ flow parameter) at which the bubble is evaluated
type : Propagator type ('g': full, 's': single-scale)
Returns
: Analytical result of the integrated tails
Definition at line 25 of file loop_corrections.hpp.
{
    switch (type) {
        case 'g':   // full (non-differentiated) propagator
            switch (iK) {
                case 0: // G^R
                    return log((std::abs(vmin) + eps_p - glb_i * Delta) / (vmax - eps_p + glb_i * Delta));
                case 1: // G^A
                    return log((std::abs(vmin) + eps_p + glb_i * Delta) / (vmax - eps_p - glb_i * Delta));
                case 2: // G^K
                    return 2. * glb_i * (atan((vmax - eps_p) / Delta) - atan((std::abs(vmin) + eps_p) / Delta));
                default:;
            }
        case 's':   // single-scale propagator
            switch (iK) {
                case 0: // G^R
                    return -glb_i / 2. * (1. / (vmax - eps_p + glb_i * Delta) - 1. / (vmin - eps_p + glb_i * Delta));
                case 1: // G^A
                    return  glb_i / 2. * (1. / (vmax - eps_p - glb_i * Delta) - 1. / (vmin - eps_p - glb_i * Delta));
                case 2: // G^K
                    return -glb_i * (  (vmax - eps_p) / ((vmax - eps_p) * (vmax - eps_p) + Delta * Delta)
                                       + (vmin - eps_p) / ((vmin - eps_p) * (vmin - eps_p) + Delta * Delta));
                default:;
            }
        default:;
    }
    return 0;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), and log().
Referenced by correctionFunctionSelfEnergy().
correctionFunctionSelfEnergy_Matsubara_NoPHS() [1/2]
template<> auto correctionFunctionSelfEnergy_Matsubara_NoPHS (int iK, double vmin, double vmax, double eps_p, double Delta, char type) -> double
Definition at line 11 of file loop_corrections.c++.
{
    utils::print("Error! Computations without particle hole symmetry require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
correctionFunctionSelfEnergy_Matsubara_NoPHS() [2/2]
template<typename Q > auto correctionFunctionSelfEnergy_Matsubara_NoPHS (int iK, double vmin, double vmax, Q eps_p, double Delta, char type) -> Q
Definition at line 68 of file loop_corrections.hpp.
{
    switch (type) {
        case 'g':   // full (non-differentiated) propagator
            return -glb_i * log((std::abs(vmin) - glb_i * eps_p + Delta) / (vmax + glb_i * eps_p + Delta));
        case 's':   // single-scale propagator
            return -glb_i / 2. * (-1. / (vmax + glb_i * eps_p + Delta) - 1. / (vmin + glb_i * eps_p - Delta));
        default:;
    }
    return 0;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), and log().
Referenced by correctionFunctionSelfEnergy().
correctionFunctionSelfEnergy_Matsubara_PHS()
template<typename Q > auto correctionFunctionSelfEnergy_Matsubara_PHS (int iK, double vmin, double vmax, Q eps_p, double Delta, char type) -> Q
Definition at line 56 of file loop_corrections.hpp.
{
    switch (type) {
        case 'g':   // full (non-differentiated) propagator
            return  -log((std::abs(vmin) + Delta) / (vmax + Delta));
        case 's':   // single-scale propagator
            return -1. / 2. * (-1. / (vmax + Delta) + 1. / (-vmin + Delta));
        default:;
    }
    return 0;
}
References log().
Referenced by correctionFunctionSelfEnergy().