SIAM-Keldysh-mfRG: hdf5_impl Namespace Reference
hdf5_impl Namespace Reference
Functions
template<typename gridType >
void init_freqgrid_from_hdf_LambdaLayer (H5::Group &group, gridType &freqgrid, const int Lambda_it, const double Lambda)
template<typename gridType >
void write_freqparams_to_hdf_LambdaLayer (H5::Group &group, const gridType &freqgrid, const int Lambda_it, const int numberLambdaLayers, const bool file_exists, const bool verbose)
template<typename Q , typename H5Object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, char >, bool > = true>
H5::DataSet create_Dataset (H5Object &group, const H5std_string &dataset_name, H5::DataSpace &file_space)
Create new dataset of suitable datatype.
template<typename H5Object >
H5::DataSet open_Dataset (H5Object &group, const H5std_string &dataset_name)
Open existing dataset of suitable datatype.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, double >||std::is_same_v< typename container::value_type, comp >||std::is_same_v< typename container::value_type, int >||std::is_same_v< typename container::value_type, char >, bool > = true>
void write_data_to_Dataset (const container data, H5::DataSet &dataset)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, double >||std::is_same_v< typename container::value_type, comp >||std::is_same_v< typename container::value_type, int >||std::is_same_v< typename container::value_type, char >, bool > = true>
void write_data_to_Dataset (const container data, H5::DataSet &dataset, H5::DataSpace &mem_space, H5::DataSpace &file_space)
template<typename Q , std::size_t depth, typename H5object , typename container , typename dimensions_type >
void write_to_hdf_LambdaLayer_impl (H5object &group, const H5std_string &dataset_name, const container &data, const dimensions_type &length, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
template<typename Q , std::size_t depth, typename H5object >
std::vector< Q > read_from_hdf_impl (const H5object &group, const H5std_string &dataset_name, std::array< std::size_t, depth > &dims_result)
template<typename Q , std::size_t depth, typename H5object >
std::vector< Q > read_from_hdf_LambdaLayer_impl (const H5object &group, const H5std_string &dataset_name, std::array< std::size_t, depth > &dims_result, const int Lambda_it)
template<typename Q , bool diff>
void write_state_to_hdf_LambdaLayer (const H5std_string &filename, const State< Q, diff > &state, const int Lambda_it, const int numberLambdaLayers, const std::string write_mode, const bool is_converged=false, const bool verbose=true)
Function Documentation
create_Dataset()
template<typename Q , typename H5Object , std::enable_if_t< std::is_same_v< Q, double >||std::is_same_v< Q, comp >||std::is_same_v< Q, int >||std::is_same_v< Q, char >, bool > = true> H5::DataSet hdf5_impl::create_Dataset (H5Object & group, const H5std_string & dataset_name, H5::DataSpace & file_space)
Create new dataset of suitable datatype.
Definition at line 135 of file hdf5_routines.hpp.
{
        if constexpr(std::is_same_v<Q, double>) {
            H5::DataSet mydataset = group.createDataSet(dataset_name, H5::PredType::NATIVE_DOUBLE, file_space);
            return mydataset;
        }
        else if constexpr(std::is_same_v<Q, comp>) {
            H5::DSetCreatPropList plist_vert = def_proplist_comp();
            H5::CompType mtype_comp = def_mtype_comp();
            H5::DataSet mydataset = group.createDataSet(dataset_name, mtype_comp, file_space, plist_vert);
            return mydataset;
        }
        else if constexpr(std::is_same_v<Q, int>) {
            H5::DataSet mydataset = group.createDataSet(dataset_name, H5::PredType::NATIVE_INT, file_space);
            return mydataset;
        }
        else if constexpr(std::is_same_v<Q, char>) {
            H5::DataSet mydataset = group.createDataSet(dataset_name, H5::PredType::NATIVE_CHAR, file_space);
            return mydataset;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), def_mtype_comp(), and def_proplist_comp().
init_freqgrid_from_hdf_LambdaLayer()
template<typename gridType > void hdf5_impl::init_freqgrid_from_hdf_LambdaLayer (H5::Group & group, gridType & freqgrid, const int Lambda_it, const double Lambda)
Definition at line 565 of file hdf5_routines.hpp.
{
        std::vector<char> type;
        std::vector<int> diag_class;
        std::vector<int> purely_positive;
        std::vector<int> number_of_gridpoints;
        std::vector<double> w_upper;
        std::vector<double> w_lower;
        std::vector<double> w_center;
        read_from_hdf_LambdaLayer<char>(group, "type", type, Lambda_it);
        read_from_hdf_LambdaLayer<int>(group, "diag_class", diag_class, Lambda_it);
        read_from_hdf_LambdaLayer<int>(group, "purely_positive", purely_positive, Lambda_it);
        read_from_hdf_LambdaLayer<int>(group, "number_of_gridpoints", number_of_gridpoints, Lambda_it);
        read_from_hdf_LambdaLayer<double>(group, "w_upper", w_upper, Lambda_it);
        read_from_hdf_LambdaLayer<double>(group, "w_lower", w_lower, Lambda_it);
        // read_from_hdf_LambdaLayer<double>(group, W_CENTER, w_center, Lambda_it);
        gridType freqgrid_new(type[0], diag_class[0], Lambda, fRG_config(), purely_positive[0]);
        freqgrid_new.w_upper = w_upper[0];
        freqgrid_new.w_lower = w_lower[0];
        // freqgrid_new.w_center = w_center[0];
        if constexpr(std::is_same_v<gridType,FrequencyGrid<eliasGrid>>) {
            std::vector<double> Delta_factor;
            std::vector<double> U_factor;
            std::vector<double> W_scale;
            read_from_hdf_LambdaLayer<double>(group, "Delta_factor", Delta_factor, Lambda_it);
            read_from_hdf_LambdaLayer<double>(group, "U_factor", U_factor, Lambda_it);
            read_from_hdf_LambdaLayer<double>(group, "W_scale", W_scale, Lambda_it);
            freqgrid_new.Delta_factor = Delta_factor[0];
            freqgrid_new.U_factor = U_factor[0];
            freqgrid_new.W_scale = W_scale[0];
        }
        else if constexpr(std::is_same_v<gridType,FrequencyGrid<hybridGrid>>){
            std::vector<double> pos_section_boundaries0;
            std::vector<double> pos_section_boundaries1;
            read_from_hdf_LambdaLayer<double>(group, "pos_section_boundaries0", pos_section_boundaries0, Lambda_it);
            read_from_hdf_LambdaLayer<double>(group, "pos_section_boundaries1", pos_section_boundaries1, Lambda_it);
            freqgrid_new.pos_section_boundaries = std::array<double,2>({pos_section_boundaries0[0], pos_section_boundaries1[0]});
        }
        else if constexpr(std::is_same_v<gridType,FrequencyGrid<angularGrid>>){
            std::vector<int> number_of_intervals;
            read_from_hdf_LambdaLayer<int>(group, "number_of_intervals", number_of_intervals, Lambda_it);
            freqgrid_new.number_of_intervals = number_of_intervals[0];
        }
        else {
            assert(false);
        }
        freqgrid_new.initialize_grid();
        freqgrid = freqgrid_new;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
open_Dataset()
template<typename H5Object > H5::DataSet hdf5_impl::open_Dataset (H5Object & group, const H5std_string & dataset_name)
Open existing dataset of suitable datatype.
Definition at line 159 of file hdf5_routines.hpp.
{
            H5::DataSet mydataset = group.openDataSet(dataset_name);
            return mydataset;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by read_from_hdf_impl(), read_from_hdf_LambdaLayer_impl(), and write_to_hdf_LambdaLayer_impl().
read_from_hdf_impl()
template<typename Q , std::size_t depth, typename H5object > std::vector< Q > hdf5_impl::read_from_hdf_impl (const H5object & group, const H5std_string & dataset_name, std::array< std::size_t, depth > & dims_result)
Funktioniert das auch fr comp?
Definition at line 247 of file hdf5_routines.hpp.
{
        H5::DataSet dataset = hdf5_impl::open_Dataset(group, dataset_name);
        H5::DataSpace file_space = dataset.getSpace();
        // get the size of the dataset
        // choose the length of this array a bit bigger, so we can also load vectors of shape (Lambda_size, 1)
        hsize_t dims_file[depth+1];
#ifndef NDEBUG
        hsize_t rank =
#endif
        file_space.getSimpleExtentDims(dims_file, NULL);
        assert(rank == depth or (dims_file[0] and depth==1));  // Important assertion! Makes sure that the desired multiarray depth matches the data in the file
        hsize_t dims_mem[depth];
        hsize_t dims_mem_flat = 1;
        for (hsize_t i = 0; i < depth; i++) {
            dims_mem[i] = dims_file[i];
            dims_mem_flat *= dims_file[i];
        }
        H5::DataSpace dataSpace_buffer(depth, dims_mem);
        //std::cout<<"Datasize of loaded (flat): "<<dims_mem_flat<<std::endl; // this is the correct number of values
        // create a vector the same size as the dataset
        std::vector<Q> result;
        result.resize(dims_mem_flat);
        //std::cout<<"Vectsize: "<<result.size()<<std::endl;
        if constexpr(std::is_same_v<Q,double>) dataset.read(result.data(), H5::PredType::NATIVE_DOUBLE, dataSpace_buffer, file_space);
        else if constexpr(std::is_same_v<Q,comp>) {
            H5::CompType mtype_comp = def_mtype_comp();
            dataset.read(result.data(), mtype_comp, dataSpace_buffer, file_space);
        }
        else if constexpr(std::is_same_v<Q,int>) dataset.read(result.data(), H5::PredType::NATIVE_INT, dataSpace_buffer, file_space);
        else if constexpr(std::is_same_v<Q,char>) dataset.read(result.data(), H5::PredType::NATIVE_CHAR, dataSpace_buffer, file_space);
        for (size_t i = 0; i < depth; i++) dims_result[i] = dims_file[i];
        return result;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), def_mtype_comp(), and open_Dataset().
read_from_hdf_LambdaLayer_impl()
template<typename Q , std::size_t depth, typename H5object > std::vector< Q > hdf5_impl::read_from_hdf_LambdaLayer_impl (const H5object & group, const H5std_string & dataset_name, std::array< std::size_t, depth > & dims_result, const int Lambda_it)
Funktioniert das auch fr comp?
Definition at line 293 of file hdf5_routines.hpp.
{
        // open file_space to read from
        H5::DataSet dataset = hdf5_impl::open_Dataset(group, dataset_name);
        H5::DataSpace file_space = dataset.getSpace();
        // get the size of the file_space (including all Lambda layers)
        hsize_t dims_file[depth+1];       // size of the full dataspace (including all lambda layers)
#ifndef NDEBUG
        hsize_t rank =
#endif
        file_space.getSimpleExtentDims(dims_file, NULL);
        assert(rank == depth+1);  // Important assertion! Makes sure that the desired multiarray depth matches the data in the file
        assert(Lambda_it < dims_file[0]); // if this fails, Lambda_it exceeded the available Lambda layers
        // create arrays with information on dimensions
        const hsize_t RANK = depth;
        hsize_t start[RANK+1];      // starting location for the hyperslab
        hsize_t stride[RANK+1];     // number of elements to separate each element or block
        hsize_t count[RANK+1];      // number of elements or blocks to select along each dimension
        hsize_t block[RANK+1];      // size of the block selected from the dataspace
        hsize_t dims_mem[RANK];       // size of the full dataspace (including all lambda layers)
        for (size_t i = 0; i < RANK+1; i++) {
            stride[i] = 1;
            block[i] = 1;
        }
        count[0] = 1;           // dimension of Lambda layer
        start[0] = Lambda_it;
        for (size_t i = 1; i < RANK+1; i++) {
            count[i] = dims_file[i];
            start[i] = 0;
            dims_result[i-1] = dims_file[i];
            dims_mem[i-1] = dims_file[i];
        }
        hsize_t dims_mem_flat = 1;
        for (hsize_t i = 0; i < depth; i++) {
            dims_mem_flat *= dims_file[i+1];
        }
        // select hyperslab to read from
        file_space.selectHyperslab(H5S_SELECT_SET, count, start, stride, block);
        H5::DataSet mydataset;
        H5::DataSpace dataSpace_buffer(depth, dims_mem);
        // create a vector the same size as the dataset
        std::vector<Q> result(dims_mem_flat);
        if constexpr(std::is_same_v<Q,double>) dataset.read(result.data(), H5::PredType::NATIVE_DOUBLE, dataSpace_buffer, file_space);
        else if constexpr(std::is_same_v<Q,comp>) {
            H5::CompType mtype_comp = def_mtype_comp();
            dataset.read(result.data(), mtype_comp, dataSpace_buffer, file_space);
        }
        else if constexpr(std::is_same_v<Q,int>) dataset.read(result.data(), H5::PredType::NATIVE_INT, dataSpace_buffer, file_space);
        else if constexpr(std::is_same_v<Q,char>) dataset.read(result.data(), H5::PredType::NATIVE_CHAR, dataSpace_buffer, file_space);
        return result;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), def_mtype_comp(), and open_Dataset().
write_data_to_Dataset() [1/2]
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, double >||std::is_same_v< typename container::value_type, comp >||std::is_same_v< typename container::value_type, int >||std::is_same_v< typename container::value_type, char >, bool > = true> void hdf5_impl::write_data_to_Dataset (const container data, H5::DataSet & dataset)
Definition at line 172 of file hdf5_routines.hpp.
{
        if constexpr(std::is_same_v<typename container::value_type, double>) dataset.write(data.data(), H5::PredType::NATIVE_DOUBLE);
        else if constexpr(std::is_same_v<typename container::value_type, comp>) {
            H5::CompType mtype_comp = def_mtype_comp();
            dataset.write(data.data(), mtype_comp);
        }
        else if constexpr(std::is_same_v<typename container::value_type, int>) dataset.write(data.data(), H5::PredType::NATIVE_INT);
        else if constexpr(std::is_same_v<typename container::value_type, char>) dataset.write(data.data(), H5::PredType::NATIVE_CHAR);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and def_mtype_comp().
Referenced by write_to_hdf(), write_to_hdf(), write_to_hdf(), and write_to_hdf_LambdaLayer_impl().
write_data_to_Dataset() [2/2]
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, double >||std::is_same_v< typename container::value_type, comp >||std::is_same_v< typename container::value_type, int >||std::is_same_v< typename container::value_type, char >, bool > = true> void hdf5_impl::write_data_to_Dataset (const container data, H5::DataSet & dataset, H5::DataSpace & mem_space, H5::DataSpace & file_space)
Definition at line 189 of file hdf5_routines.hpp.
{
        if constexpr(std::is_same_v<typename container::value_type, double>) dataset.write(data.data(), H5::PredType::NATIVE_DOUBLE, mem_space, file_space);
        else if constexpr(std::is_same_v<typename container::value_type, comp>) {
            H5::CompType mtype_comp = def_mtype_comp();
            dataset.write(data.data(), mtype_comp, mem_space, file_space);
        }
        else if constexpr(std::is_same_v<typename container::value_type, int>) dataset.write(data.data(), H5::PredType::NATIVE_INT, mem_space, file_space);
        else if constexpr(std::is_same_v<typename container::value_type, char>) dataset.write(data.data(), H5::PredType::NATIVE_CHAR, mem_space, file_space);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and def_mtype_comp().
write_freqparams_to_hdf_LambdaLayer()
template<typename gridType > void hdf5_impl::write_freqparams_to_hdf_LambdaLayer (H5::Group & group, const gridType & freqgrid, const int Lambda_it, const int numberLambdaLayers, const bool file_exists, const bool verbose)
Definition at line 531 of file hdf5_routines.hpp.
{
        write_to_hdf_LambdaLayer<char>(group, "type", std::vector<char>({freqgrid.get_type()}), Lambda_it, numberLambdaLayers, file_exists);
        write_to_hdf_LambdaLayer<int>(group, "diag_class", std::vector<int>({freqgrid.get_diag_class()}), Lambda_it, numberLambdaLayers, file_exists);
        write_to_hdf_LambdaLayer<int>(group, "purely_positive", std::vector<int>({freqgrid.purely_positive}), Lambda_it, numberLambdaLayers, file_exists);
        write_to_hdf_LambdaLayer<int>(group, "number_of_gridpoints", std::vector<int>({freqgrid.number_of_gridpoints}), Lambda_it, numberLambdaLayers, file_exists);
        write_to_hdf_LambdaLayer<freqType>(group, "w_upper", std::vector<freqType>({freqgrid.w_upper}), Lambda_it, numberLambdaLayers, file_exists);
        write_to_hdf_LambdaLayer<freqType>(group, "w_lower", std::vector<freqType>({freqgrid.w_lower}), Lambda_it, numberLambdaLayers, file_exists);
        // write_to_hdf_LambdaLayer<freqType>(group, W_CENTER, std::vector<freqType>({freqgrid.w_center}), Lambda_it, numberLambdaLayers, file_exists);
        if constexpr(std::is_same_v<gridType,FrequencyGrid<eliasGrid>>)
        {
            write_to_hdf_LambdaLayer<double>(group, "Delta_factor", std::vector<double>({freqgrid.Delta_factor}),
                                             Lambda_it, numberLambdaLayers, file_exists);
            write_to_hdf_LambdaLayer<double>(group, "U_factor", std::vector<double>({freqgrid.U_factor}), Lambda_it,
                                             numberLambdaLayers, file_exists);
            write_to_hdf_LambdaLayer<freqType>(group, "W_scale", std::vector<freqType>({freqgrid.W_scale}), Lambda_it,
                                               numberLambdaLayers, file_exists);
        }
        else if constexpr(std::is_same_v<gridType,FrequencyGrid<hybridGrid>>) {
            write_to_hdf_LambdaLayer<double>(group, "pos_section_boundaries0", std::vector<double>({freqgrid.pos_section_boundaries[0]}),
                                             Lambda_it, numberLambdaLayers, file_exists);
            write_to_hdf_LambdaLayer<double>(group, "pos_section_boundaries1", std::vector<double>({freqgrid.pos_section_boundaries[1]}), Lambda_it,
                                             numberLambdaLayers, file_exists);
        }
        else if constexpr(std::is_same_v<gridType,FrequencyGrid<angularGrid>>) {
            write_to_hdf_LambdaLayer<int>(group, "number_of_intervals", std::vector<int>({freqgrid.number_of_intervals}),
                                          Lambda_it, numberLambdaLayers, file_exists);
        }
        else {
            assert(false);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by write_state_to_hdf_LambdaLayer().
write_state_to_hdf_LambdaLayer()
template<typename Q , bool diff> void hdf5_impl::write_state_to_hdf_LambdaLayer (const H5std_string & filename, const State< Q, diff > & state, const int Lambda_it, const int numberLambdaLayers, const std::string write_mode, const bool is_converged = false, const bool verbose = true)
Save state data
Write used parameters for documentation purpose
Write frequency parameters
Definition at line 621 of file hdf5_routines.hpp.
{
        H5::H5File file_out;
        //H5::Exception::dontPrint();
        const bool keep_existing_file = (write_mode == "rw");
        bool is_dataset_existent = (write_mode == "rw");
        assert(write_mode == "w" or write_mode == "rw");
        if (!keep_existing_file) {
            // Create a new file using the default property lists. (No matter of file exists)
            file_out = H5::H5File(filename, H5F_ACC_TRUNC);
        }
        else {
            // If file exists, open existing file. Access rights: read/write
            try {
                file_out = H5::H5File(filename, H5F_ACC_RDWR);
            } catch(const H5::FileIException&) {
                // If file does not exist, open new file
                file_out = H5::H5File(filename, H5F_ACC_TRUNC);
                is_dataset_existent = false;
            }
        }
        write_to_hdf_LambdaLayer<double>(file_out, LAMBDA_LIST, std::vector<double>({state.Lambda}), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, SELF_LIST, state.selfenergy.Sigma.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, HARTREE, std::vector<Q>({state.selfenergy.asymp_val_R}), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_irred, state.vertex.irred().get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K1_a, state.vertex.avertex().K1.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K1_p, state.vertex.pvertex().K1.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K1_t, state.vertex.tvertex().K1.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS_LIST, state.selfenergy.Sigma.frequencies.  primary_grid.get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS_LISTa, state.vertex.avertex().K1.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS_LISTp, state.vertex.pvertex().K1.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS_LISTt, state.vertex.tvertex().K1.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
#if MAX_DIAG_CLASS>1
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K2_a, state.vertex.avertex().K2.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K2_p, state.vertex.pvertex().K2.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K2_t, state.vertex.tvertex().K2.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS2_LISTa, state.vertex.avertex().K2.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS2_LISTp, state.vertex.pvertex().K2.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS2_LISTt, state.vertex.tvertex().K2.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS2_LISTa, state.vertex.avertex().K2.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS2_LISTp, state.vertex.pvertex().K2.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS2_LISTt, state.vertex.tvertex().K2.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
#if DEBUG_SYMMETRIES
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K2b_a, state.vertex.avertex().K2b.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K2b_p, state.vertex.pvertex().K2b.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K2b_t, state.vertex.tvertex().K2b.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS2b_LISTa, state.vertex.avertex().K2b.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS2b_LISTp, state.vertex.pvertex().K2b.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS2b_LISTt, state.vertex.tvertex().K2b.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS2b_LISTa, state.vertex.avertex().K2b.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS2b_LISTp, state.vertex.pvertex().K2b.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS2b_LISTt, state.vertex.tvertex().K2b.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
#endif
#endif
#if MAX_DIAG_CLASS>2
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K3_a, state.vertex.avertex().K3.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K3_p, state.vertex.pvertex().K3.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<Q>(file_out, DATASET_K3_t, state.vertex.tvertex().K3.get_vec(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS3_LISTa, state.vertex.avertex().K3.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS3_LISTp, state.vertex.pvertex().K3.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, BFREQS3_LISTt, state.vertex.tvertex().K3.frequencies.get_freqGrid_b().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS3_LISTa, state.vertex.avertex().K3.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS3_LISTp, state.vertex.pvertex().K3.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS3_LISTt, state.vertex.tvertex().K3.frequencies.get_freqGrid_f().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS3_LISTa2,state.vertex.avertex().K3.frequencies.get_freqGrid_3().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS3_LISTp2,state.vertex.pvertex().K3.frequencies.get_freqGrid_3().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
        write_to_hdf_LambdaLayer<freqType>(file_out, FFREQS3_LISTt2,state.vertex.tvertex().K3.frequencies.get_freqGrid_3().get_all_frequencies(), Lambda_it, numberLambdaLayers, is_dataset_existent);
#endif
        if(!is_dataset_existent) {
            H5::Group group_params(file_out.createGroup(PARAM_LIST));
            write_to_hdf(group_params, "REG", REG, is_dataset_existent);
            write_to_hdf(group_params, "nODE", state.config.nODE_, is_dataset_existent);
            write_to_hdf(group_params, "Gamma", state.config.Gamma, is_dataset_existent);
            write_to_hdf(group_params, "MAX_DIAG_CLASS", MAX_DIAG_CLASS, is_dataset_existent);
            write_to_hdf(group_params, "N_LOOPS", state.config.nloops, is_dataset_existent);
            write_to_hdf(group_params, "T", state.config.T, is_dataset_existent);
            write_to_hdf(group_params, "mu", glb_mu, is_dataset_existent);
            write_to_hdf(group_params, "U", state.config.U, is_dataset_existent);
            write_to_hdf(group_params, "epsilon", state.config.epsilon, is_dataset_existent);
            write_to_hdf(group_params, "V", glb_V, is_dataset_existent);
            write_to_hdf(group_params, "GRID", GRID, is_dataset_existent);
            write_to_hdf(group_params, IS_CONVERGED, is_converged, is_dataset_existent);
        }
        H5::Group group_params(file_out.openGroup(PARAM_LIST));
        write_to_hdf(group_params, "last_Lambda_it", Lambda_it, is_dataset_existent);
        if (is_converged) {
            write_to_hdf(group_params, IS_CONVERGED, is_converged, is_dataset_existent);
        }
        H5::Group group_freqparams;
        H5::Group group_freqparams_ffreqs;
        H5::Group group_freqparams_bfreqsa;
        H5::Group group_freqparams_bfreqsp;
        H5::Group group_freqparams_bfreqst;
        H5::Group group_freqparams_bfreqs2a;
        H5::Group group_freqparams_bfreqs2p;
        H5::Group group_freqparams_bfreqs2t;
        H5::Group group_freqparams_bfreqs2ba;
        H5::Group group_freqparams_bfreqs2bp;
        H5::Group group_freqparams_bfreqs2bt;
        H5::Group group_freqparams_bfreqs3a;
        H5::Group group_freqparams_bfreqs3p;
        H5::Group group_freqparams_bfreqs3t;
        H5::Group group_freqparams_ffreqs2a;
        H5::Group group_freqparams_ffreqs2p;
        H5::Group group_freqparams_ffreqs2t;
        H5::Group group_freqparams_ffreqs2ba;
        H5::Group group_freqparams_ffreqs2bp;
        H5::Group group_freqparams_ffreqs2bt;
        H5::Group group_freqparams_ffreqs3a;
        H5::Group group_freqparams_ffreqs3p;
        H5::Group group_freqparams_ffreqs3t;
        H5::Group group_freqparams_ffreqs3a2;
        H5::Group group_freqparams_ffreqs3p2;
        H5::Group group_freqparams_ffreqs3t2;
    if (!keep_existing_file) {
        group_freqparams = file_out.createGroup(FREQ_PARAMS);
        group_freqparams_ffreqs = group_freqparams.createGroup(FFREQS_LIST );
        group_freqparams_bfreqsa = group_freqparams.createGroup(BFREQS_LISTa );
        group_freqparams_bfreqsp = group_freqparams.createGroup(BFREQS_LISTp );
        group_freqparams_bfreqst = group_freqparams.createGroup(BFREQS_LISTt );
        group_freqparams_bfreqs2a = group_freqparams.createGroup(BFREQS2_LISTa);
        group_freqparams_bfreqs2p = group_freqparams.createGroup(BFREQS2_LISTp);
        group_freqparams_bfreqs2t = group_freqparams.createGroup(BFREQS2_LISTt);
        group_freqparams_bfreqs2ba = group_freqparams.createGroup(BFREQS2b_LISTa);
        group_freqparams_bfreqs2bp = group_freqparams.createGroup(BFREQS2b_LISTp);
        group_freqparams_bfreqs2bt = group_freqparams.createGroup(BFREQS2b_LISTt);
        group_freqparams_bfreqs3a = group_freqparams.createGroup(BFREQS3_LISTa);
        group_freqparams_bfreqs3p = group_freqparams.createGroup(BFREQS3_LISTp);
        group_freqparams_bfreqs3t = group_freqparams.createGroup(BFREQS3_LISTt);
        group_freqparams_ffreqs2a = group_freqparams.createGroup(FFREQS2_LISTa);
        group_freqparams_ffreqs2p = group_freqparams.createGroup(FFREQS2_LISTp);
        group_freqparams_ffreqs2t = group_freqparams.createGroup(FFREQS2_LISTt);
        group_freqparams_ffreqs2ba = group_freqparams.createGroup(FFREQS2b_LISTa);
        group_freqparams_ffreqs2bp = group_freqparams.createGroup(FFREQS2b_LISTp);
        group_freqparams_ffreqs2bt = group_freqparams.createGroup(FFREQS2b_LISTt);
        group_freqparams_ffreqs3a = group_freqparams.createGroup(FFREQS3_LISTa);
        group_freqparams_ffreqs3p = group_freqparams.createGroup(FFREQS3_LISTp);
        group_freqparams_ffreqs3t = group_freqparams.createGroup(FFREQS3_LISTt);
        group_freqparams_ffreqs3a2= group_freqparams.createGroup(FFREQS3_LISTa2);
        group_freqparams_ffreqs3p2= group_freqparams.createGroup(FFREQS3_LISTp2);
        group_freqparams_ffreqs3t2= group_freqparams.createGroup(FFREQS3_LISTt2);
    }
    else {
        group_freqparams = file_out.openGroup(FREQ_PARAMS);
        group_freqparams_ffreqs = group_freqparams.openGroup(FFREQS_LIST );
        group_freqparams_bfreqsa = group_freqparams.openGroup(BFREQS_LISTa );
        group_freqparams_bfreqsp = group_freqparams.openGroup(BFREQS_LISTp );
        group_freqparams_bfreqst = group_freqparams.openGroup(BFREQS_LISTt );
        group_freqparams_bfreqs2a = group_freqparams.openGroup(BFREQS2_LISTa);
        group_freqparams_bfreqs2p = group_freqparams.openGroup(BFREQS2_LISTp);
        group_freqparams_bfreqs2t = group_freqparams.openGroup(BFREQS2_LISTt);
        group_freqparams_bfreqs2ba = group_freqparams.openGroup(BFREQS2b_LISTa);
        group_freqparams_bfreqs2bp = group_freqparams.openGroup(BFREQS2b_LISTp);
        group_freqparams_bfreqs2bt = group_freqparams.openGroup(BFREQS2b_LISTt);
        group_freqparams_bfreqs3a = group_freqparams.openGroup(BFREQS3_LISTa);
        group_freqparams_bfreqs3p = group_freqparams.openGroup(BFREQS3_LISTp);
        group_freqparams_bfreqs3t = group_freqparams.openGroup(BFREQS3_LISTt);
        group_freqparams_ffreqs2a = group_freqparams.openGroup(FFREQS2_LISTa);
        group_freqparams_ffreqs2p = group_freqparams.openGroup(FFREQS2_LISTp);
        group_freqparams_ffreqs2t = group_freqparams.openGroup(FFREQS2_LISTt);
        group_freqparams_ffreqs2ba = group_freqparams.openGroup(FFREQS2b_LISTa);
        group_freqparams_ffreqs2bp = group_freqparams.openGroup(FFREQS2b_LISTp);
        group_freqparams_ffreqs2bt = group_freqparams.openGroup(FFREQS2b_LISTt);
        group_freqparams_ffreqs3a = group_freqparams.openGroup(FFREQS3_LISTa);
        group_freqparams_ffreqs3p = group_freqparams.openGroup(FFREQS3_LISTp);
        group_freqparams_ffreqs3t = group_freqparams.openGroup(FFREQS3_LISTt);
        group_freqparams_ffreqs3a2= group_freqparams.openGroup(FFREQS3_LISTa2);
        group_freqparams_ffreqs3p2= group_freqparams.openGroup(FFREQS3_LISTp2);
        group_freqparams_ffreqs3t2= group_freqparams.openGroup(FFREQS3_LISTt2);
    }
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs , state.selfenergy.Sigma.frequencies.get_freqGrid_b()      , Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqsa, state.vertex.avertex().K1.frequencies.get_freqGrid_b()  , Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqsp, state.vertex.pvertex().K1.frequencies.get_freqGrid_b()  , Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqst, state.vertex.tvertex().K1.frequencies.get_freqGrid_b()  , Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
#if MAX_DIAG_CLASS>1
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs2a,state.vertex.avertex().K2.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs2p,state.vertex.pvertex().K2.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs2t,state.vertex.tvertex().K2.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs2a,state.vertex.avertex().K2.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs2p,state.vertex.pvertex().K2.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs2t,state.vertex.tvertex().K2.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
#if DEBUG_SYMMETRIES
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs2ba,state.vertex.avertex().K2b.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs2bp,state.vertex.pvertex().K2b.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs2bt,state.vertex.tvertex().K2b.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs2ba,state.vertex.avertex().K2b.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs2bp,state.vertex.pvertex().K2b.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs2bt,state.vertex.tvertex().K2b.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
#endif
#endif
#if MAX_DIAG_CLASS>2
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs3a, state.vertex.avertex().K3.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs3p, state.vertex.pvertex().K3.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_bfreqs3t, state.vertex.tvertex().K3.frequencies.get_freqGrid_b(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs3a, state.vertex.avertex().K3.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs3p, state.vertex.pvertex().K3.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs3t, state.vertex.tvertex().K3.frequencies.get_freqGrid_f(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs3a2,state.vertex.avertex().K3.frequencies.get_freqGrid_3(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs3p2,state.vertex.pvertex().K3.frequencies.get_freqGrid_3(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
        write_freqparams_to_hdf_LambdaLayer(group_freqparams_ffreqs3t2,state.vertex.tvertex().K3.frequencies.get_freqGrid_3(), Lambda_it, numberLambdaLayers, is_dataset_existent, verbose);
#endif
        file_out.close();
    }
References BFREQS2_LISTa(), BFREQS2_LISTp(), BFREQS2_LISTt(), BFREQS2b_LISTa(), BFREQS2b_LISTp(), BFREQS2b_LISTt(), BFREQS3_LISTa(), BFREQS3_LISTp(), BFREQS3_LISTt(), BFREQS_LISTa(), BFREQS_LISTp(), BFREQS_LISTt(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DATASET_irred(), DATASET_K1_a(), DATASET_K1_p(), DATASET_K1_t(), DATASET_K2_a(), DATASET_K2_p(), DATASET_K2_t(), DATASET_K2b_a(), DATASET_K2b_p(), DATASET_K2b_t(), DATASET_K3_a(), DATASET_K3_p(), DATASET_K3_t(), FFREQS2_LISTa(), FFREQS2_LISTp(), FFREQS2_LISTt(), FFREQS2b_LISTa(), FFREQS2b_LISTp(), FFREQS2b_LISTt(), FFREQS3_LISTa(), FFREQS3_LISTa2(), FFREQS3_LISTp(), FFREQS3_LISTp2(), FFREQS3_LISTt(), FFREQS3_LISTt2(), FFREQS_LIST(), FREQ_PARAMS(), glb_mu, glb_V, GRID, HARTREE(), IS_CONVERGED(), LAMBDA_LIST(), MAX_DIAG_CLASS, PARAM_LIST(), REG, SELF_LIST(), write_freqparams_to_hdf_LambdaLayer(), and write_to_hdf().
Referenced by add_state_to_hdf(), and write_state_to_hdf().
write_to_hdf_LambdaLayer_impl()
template<typename Q , std::size_t depth, typename H5object , typename container , typename dimensions_type > void hdf5_impl::write_to_hdf_LambdaLayer_impl (H5object & group, const H5std_string & dataset_name, const container & data, const dimensions_type & length, const hsize_t Lambda_it, const hsize_t numberLambda_layers, const bool data_set_exists)
create arrays with information on dimensions
Definition at line 201 of file hdf5_routines.hpp.
{
        assert(Lambda_it < numberLambda_layers);
        const hsize_t RANK = depth;
        hsize_t start[RANK+1];      // starting location for the hyperslab
        hsize_t stride[RANK+1];     // number of elements to separate each element or block
        hsize_t count[RANK+1];      // number of elements or blocks to select along each dimension
        hsize_t block[RANK+1];      // size of the block selected from the dataspace
        hsize_t dims_file[RANK+1];       // size of the full dataspace (including all lambda layers)
        hsize_t dims_mem[RANK];       // size of the full dataspace (including all lambda layers)
        for (hsize_t i = 0; i < RANK+1; i++) {
            stride[i] = 1;
            block[i] = 1;
        }
        count[0] = 1;           // dimension of Lambda layer
        start[0] = Lambda_it;
        dims_file[0] = numberLambda_layers;
        for (hsize_t i = 1; i < RANK+1; i++) {
            count[i] = length[i-1];
            start[i] = 0;
            dims_file[i] = length[i-1];
            dims_mem[i-1] = length[i-1];
        }
        // create dataspaces and select hyperslab
        H5::DataSpace file_space(RANK+1, dims_file);
        H5::DataSpace mem_space(RANK, dims_mem);
        file_space.selectHyperslab(H5S_SELECT_SET, count, start, stride, block);
        // create or open dataset in HDF5group/file
        H5::DataSet mydataset;
        if (!data_set_exists) mydataset = hdf5_impl::create_Dataset<Q,H5object>(group, dataset_name, file_space);
        else mydataset = hdf5_impl::open_Dataset(group, dataset_name);//= hdf5_impl::open_Dataset<H5object>(group, dataset_name);
        //write data to dataset
        hdf5_impl::write_data_to_Dataset(data, mydataset, mem_space, file_space);
        mydataset.close();
        mem_space.close();
        file_space.close();
    };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), open_Dataset(), and write_data_to_Dataset().