SIAM-Keldysh-mfRG: math_utils.hpp File Reference
math_utils.hpp File Reference
#include "../data_structures.hpp"
#include "../multidimensional/multiarray.hpp"
#include "template_utils.hpp"
#include "runtime_error.hpp"
#include "util.hpp"
#include <iostream>
#include <cassert>
Namespaces
namespace math_impl
Enumerations
enum bd_type { first_deriv = 1 , second_deriv = 2 , third_deriv = 3 }
Functions
template<unsigned int n, typename Q >
constexpr Q my_integer_pow (const Q i)
template<typename T >
auto sign (T x) -> double
double sgn (double x)
int integer_division_ceil (int a, int b)
int integer_division_floor (int a, int b)
auto heaviside (const double x) -> double
template<typename Q >
auto sign_index (Q freq) -> int
auto round2Infty (double x) -> double
auto myround (double x) -> double
auto floor2bfreq (int w) -> int
auto ceil2bfreq (int w) -> int
auto floor2bfreq (double w) -> double
auto ceil2bfreq (double w) -> double
auto round2bfreq (double w) -> double
auto round2ffreq (double w) -> double
auto signFlipCorrection_MF (freqType w) -> freqType
int signFlipCorrection_MF_int (freqType w)
auto is_doubleOccurencies (const vec< freqType > &freqs) -> int
auto is_symmetric (const rvec &freqs) -> double
template<int degreeplus, typename Q >
auto lagrangePoly (const Q x, const double(&xs)[degreeplus], const Q(&ys)[degreeplus]) -> Q
template<size_t rank>
constexpr size_t getFlatSize (const std::array< size_t, rank > &dims)
template<size_t rank>
size_t getFlatIndex (const std::array< size_t, rank > &indx, const std::array< size_t, rank > &dims)
template<>
size_t getFlatIndex< 1 > (const std::array< size_t, 1 > &indx, const std::array< size_t, 1 > &dims)
Template specialization for special case rank == 1.
template<size_t rank>
size_t math_impl::getFlatIndex (const std::array< size_t, rank > &indx, const std::array< size_t, rank > &dims, const std::array< size_t, rank > &permutation)
template<size_t rank, typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< int, Types... >::value), bool > = true>
int getFlatIndex (const Types &... i, const std::array< size_t, rank > &dims)
Overloads of above function for 5, 4, 3 or 2 indices (with the array dims containing number of grids points in each direction)
template<size_t rank, typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< int, Types... >::value), bool > = true>
int getFlatIndex (const Types &&... i, const std::array< size_t, rank > &dims)
template<size_t rank, typename I = size_t, typename std::enable_if_t< std::is_integral< I >::value, bool > = true>
void getMultIndex (std::array< I, rank > &indx, const size_t iflat, const std::array< I, rank > &dims)
template<>
void getMultIndex< 1 > (std::array< size_t, 1 > &indx, const size_t iflat, const std::array< size_t, 1 > &dims)
Template specialization for special case rank == 1.
template<size_t rank, typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< int, Types... >::value), bool > = true>
void getMultIndex (Types &... i, const size_t iflat, const std::array< size_t, rank > &dims)
template<size_t rank, size_t idim>
void getMultIndexSkippingOneDimension (std::array< size_t, rank > &indx, const size_t iflat, const std::array< size_t, rank > &dims)
template<size_t rank>
size_t rotateFlatIndex (const size_t iflat, const std::array< size_t, rank > &dims, const std::array< size_t, rank > &permutation)
template<size_t rank>
size_t rotateFlatIndex (const size_t iflat, const std::array< size_t, rank > &dims_native, const size_t i_dim)
template<typename T , size_t rank>
vec< T > partial_deriv (const vec< T > &data, const vec< freqType > &xs, const std::array< size_t, rank > &dims, const size_t i_dim, const double order=5)
template<typename T , size_t rank>
vec< T > partial_deriv_v2 (const vec< T > &data, const vec< freqType > &xs, const std::array< size_t, rank > &dims, const size_t i_dim, const double order=5)
template<typename T , size_t rank>
Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > get_slice (const multidimensional::multiarray< T, rank > &data, const size_t idim, const size_t i, const size_t j)
template<typename T , size_t rank>
multidimensional::multiarray< T, rank > partial_deriv (const multidimensional::multiarray< T, rank > &data, const size_t i_dim)
partial derivative with finite differences method (accuracy: 2nd order)
template<typename binaryOp , typename T , size_t rank, size_t rank_new>
vec< T > collapse (const vec< T > &data, const binaryOp &op, const std::array< size_t, rank > &dims_native, const std::array< size_t, rank_new > &i_dims, const std::array< size_t, rank_new > &dims_new)
template<typename binaryOp , typename T >
T collapse_all (const vec< T > &data, const binaryOp &op)
template<typename T >
vec< T > power2 (const vec< T > &vec_in)
template<typename T , std::size_t rank>
vec< T > power2 (const multidimensional::multiarray< T, rank > &data)
template<size_t rank, typename T >
vec< double > maxabs (const vec< T > &data, const std::array< size_t, rank > &dims, const size_t i_dim)
Computes maximum along axis i_dim.
template<std::size_t rank, typename T >
vec< double > maxabs (const multidimensional::multiarray< T, rank > &data, const std::array< size_t, rank > &dims, const size_t i_dim)
template<char >
void switch2bosonicFreqs (double &w_in, double &v1_in, double &v2_in)
Base template for a channel.
template<>
void switch2bosonicFreqs< 'p'> (double &w_in, double &v1_in, double &v2_in)
Functions for change of coordinates (for 2D and 3D):
template<>
void switch2bosonicFreqs< 't'> (double &w_in, double &v1_in, double &v2_in)
template<char >
void switch2naturalFreqs (double &w_a, double &w_p, double &w_t)
Base template for a channel.
template<>
void switch2naturalFreqs< 'p'> (double &w_a, double &w_p, double &w_t)
template<>
void switch2naturalFreqs< 't'> (double &w_a, double &w_p, double &w_t)
void K2_convert2internalFreqs (freqType &w, freqType &v)
converts the frequencies to the parametrization that is used internally, e.g. rotate frequency plane
void K2_convert2naturalFreqs (freqType &w, freqType &v)
void K3_convert2internalFreqs (freqType &w, freqType &v, freqType &vp)
void K3_convert2naturalFreqs (freqType &w, freqType &v, freqType &vp)
template<typename T >
void locate (const std::vector< T > xx, const size_t n, const T x, int &j, const int jl_start, const int ju_start)
template<typename T , size_t rank>
auto multiply (const std::array< T, rank > &l, const std::array< T, rank > &r) -> std::array< T, rank >
math utilities for arrays
template<typename T , size_t rank>
auto add (const std::array< T, rank > &l, const std::array< T, rank > &r) -> std::array< T, rank >
template<typename T , size_t rank>
auto subtract (const std::array< T, rank > &l, const std::array< T, rank > &r) -> std::array< T, rank >
template<typename T , size_t rank>
auto dot (const std::array< T, rank > &l, const std::array< T, rank > &r) -> T
Enumeration Type Documentation
bd_type
enum bd_type
Enumerator
first_deriv
second_deriv
known first derivative
third_deriv
known second derivative
Definition at line 323 of file math_utils.hpp.
             {
    first_deriv = 1,
    second_deriv = 2,
    third_deriv = 3
};
Function Documentation
add()
template<typename T , size_t rank> auto add (const std::array< T, rank > & l, const std::array< T, rank > & r) -> std::array<T,rank>
Definition at line 1069 of file math_utils.hpp.
{
    std::array<T,rank> res = l;
    for (int i = 0; i < rank; i++) {
        res[i] += r[i];
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
ceil2bfreq() [1/2]
auto ceil2bfreq (double w) -> double
Definition at line 87 of file math_utils.c++.
{
    const double tol = 1e-8;
    const double a = (2.);
    const double result = ceil(w / a-tol) * a;
    assert(result >= w);
    assert(result <= w + 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
ceil2bfreq() [2/2]
auto ceil2bfreq (int w) -> int
Definition at line 71 of file math_utils.c++.
{
    const int a = 2;
    const double result = integer_division_ceil(w , a) * a;
    assert(result >= w);
    assert(result <= w + 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integer_division_ceil().
Referenced by oneBubble< Q >::convert_to_fermionic_frequencies_1(), Bubble< Q >::convert_to_fermionic_frequencies_1(), oneBubble< Q >::convert_to_fermionic_frequencies_2(), Bubble< Q >::convert_to_fermionic_frequencies_2(), and Bubble< Q >::value().
collapse()
template<typename binaryOp , typename T , size_t rank, size_t rank_new> vec< T > collapse (const vec< T > & data, const binaryOp & op, const std::array< size_t, rank > & dims_native, const std::array< size_t, rank_new > & i_dims, const std::array< size_t, rank_new > & dims_new)
Collapses the dimensions of a vector using an operator op
Template Parameters
binaryOp
T
rank rank of the data tensor
Parameters
data multi-dimensional tensor
op binary operator used to collapse the dimensions that are not contained in i_dims
dims_native native dimensions of data
i_dims indices of the dimensions that should be kept, in the order in which data should be returned
dims_new dimensions of result corresponding to i_dims
Returns
Definition at line 838 of file math_utils.hpp.
{
    size_t dim_collapse = 1; // flat dimension of dimensions that are to be collapsed
    size_t dimsflat_new = 1; // flat dimension of result
    for (size_t i = 0; i < rank_new; i++) dimsflat_new *= dims_native[i_dims[i]];
    for (size_t i = 0; i < rank; i++) dim_collapse *= dims_native[i];
    dim_collapse /= dimsflat_new;
    std::array<size_t,rank>  perm_rot; // permutation to rotate dims_native to dims_rot
    std::array<size_t,rank>  dims_rot; // array of dimensions, rotated such that the trailing dimensions are to be collapsed
    size_t iter_new;
    size_t iter_col = 0;
    for (size_t i = 0; i < rank; i++) {
        bool is_new = false;
        size_t j;
        for (j = 0; j < rank_new; j++) { // is i in i_dims?
            if (i == i_dims[j]) {is_new = true; iter_new = j;} // break;
        }
        if (is_new) {
            perm_rot[iter_new] = i;
            dims_rot[iter_new] = dims_native[i];
        }
        else {
            perm_rot[rank-iter_col-1] = i;
            dims_rot[rank-iter_col-1] = dims_native[i];
            iter_col++;
        }
    }
    vec<size_t> perm_inv_vec = get_inverse_permutation(perm_rot);
    std::array<size_t,rank> perm_inv;
    //std::copy(perm_inv_vec.begin(), perm_inv_vec.end(), perm_inv);
    for (unsigned int j = 0; j < rank; j++) perm_inv[j] = perm_inv_vec[j];
    vec<T> result(dimsflat_new);
#pragma omp parallel for
    for (size_t i = 0; i < dimsflat_new; i++) {
        result[i] = data[rotateFlatIndex(i*dim_collapse + 0, dims_rot, perm_inv)];
        for (size_t j = 1; j < dim_collapse; j++) {
            result[i] = op(result[i], data[rotateFlatIndex(i*dim_collapse + j  , dims_rot, perm_inv)]
            );
        }
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and rotateFlatIndex().
Referenced by maxabs().
collapse_all()
template<typename binaryOp , typename T > T collapse_all (const vec< T > & data, const binaryOp & op)
Collapses all dimensions of a vector using an operator op
Definition at line 889 of file math_utils.hpp.
{
    size_t dim_collapse = data.size(); // flat dimension of dimensions that are to be collapsed
    assert(dim_collapse > 1); //otherwise nothing to collapse with binary operator
    T result = data[0];
#pragma omp parallel for
    for (size_t j = 1; j < dim_collapse; j++) result = op(result, data[j]);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
dot()
template<typename T , size_t rank> auto dot (const std::array< T, rank > & l, const std::array< T, rank > & r) -> T
Definition at line 1085 of file math_utils.hpp.
{
    T res{};
    for (int i = 0; i < rank; i++) {
        res += l[i]*r[i];
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
floor2bfreq() [1/2]
auto floor2bfreq (double w) -> double
Definition at line 79 of file math_utils.c++.
{
    const double tol = 1e-8;
    const double a = (2.);
    const double result = floor(w / a+tol) * a;
    assert(result <= w);
    assert(result >= w - 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
floor2bfreq() [2/2]
auto floor2bfreq (int w) -> int
Definition at line 64 of file math_utils.c++.
{
    const int a = 2;
    const int result = integer_division_floor(w , a) * a;
    assert(result <= w);
    assert(result >= w - 2);
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and integer_division_floor().
Referenced by oneBubble< Q >::convert_to_fermionic_frequencies_1(), Bubble< Q >::convert_to_fermionic_frequencies_1(), oneBubble< Q >::convert_to_fermionic_frequencies_2(), Bubble< Q >::convert_to_fermionic_frequencies_2(), rvert< Q >::transfToR(), and Bubble< Q >::value().
get_slice()
template<typename T , size_t rank> Eigen::Matrix< T, Eigen::Dynamic, Eigen::Dynamic > get_slice (const multidimensional::multiarray< T, rank > & data, const size_t idim, const size_t i, const size_t j)
Definition at line 775 of file math_utils.hpp.
{
    //const int idim = 0;
    //const int i = 1;
    //const int j = 0;
    const size_t flatsize = getFlatSize(data.length());
    const size_t dimsL = data.length_cumul()[idim];
    const size_t dimsR = flatsize / dimsL;
    const size_t blockCols = dimsR-i-j;
    const size_t blockRows = dimsL;
    Eigen::MatrixXd m_temp = data.get_elements();
    m_temp.resize(dimsL,dimsR);
    return m_temp.block(0,i, blockRows, blockCols);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::get_elements(), getFlatSize(), multidimensional::multiarray< T, depth >::length(), and multidimensional::multiarray< T, depth >::length_cumul().
getFlatIndex() [1/3]
template<size_t rank> size_t getFlatIndex (const std::array< size_t, rank > & indx, const std::array< size_t, rank > & dims) inline
Returns a flattened index of a multi-dimensional vector
Template Parameters
rank number of dimensions
Parameters
indx array of multi-dimensional indices
dims number of grid points in the different directions
Returns
Definition at line 120 of file math_utils.hpp.
{
        size_t result = indx[0];
        for (size_t it = 1; it < rank; it++) {
            result *= dims[it];
            result += indx[it];
        }
        return result;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
getFlatIndex() [2/3]
template<size_t rank, typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< int, Types... >::value), bool > = true> int getFlatIndex (const Types &&... i, const std::array< size_t, rank > & dims) inline
Definition at line 184 of file math_utils.hpp.
{
    auto temp = utils::to_array<size_t, Types...>(i...);
    return getFlatIndex<rank>(temp, dims);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::to_array().
getFlatIndex() [3/3]
template<size_t rank, typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< int, Types... >::value), bool > = true> int getFlatIndex (const Types &... i, const std::array< size_t, rank > & dims) inline
Overloads of above function for 5, 4, 3 or 2 indices (with the array dims containing number of grids points in each direction)
Definition at line 178 of file math_utils.hpp.
{
    auto temp = utils::to_array<size_t, Types...>(i...);
    return getFlatIndex<rank>(temp, dims);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::to_array().
getFlatIndex< 1 >()
template<> size_t getFlatIndex< 1 > (const std::array< size_t, 1 > & indx, const std::array< size_t, 1 > & dims) inline
Template specialization for special case rank == 1.
Definition at line 131 of file math_utils.hpp.
{
        return dims[0];
    }
getFlatSize()
template<size_t rank> constexpr size_t getFlatSize (const std::array< size_t, rank > & dims) constexpr
Definition at line 106 of file math_utils.hpp.
{
    size_t result = dims[0];
    for (size_t it = 1; it < rank; it++) result *= dims[it];
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by anderson_update(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator(), check_FDTs_K1(), check_FDTs_selfenergy(), rvert< Q >::check_symmetries(), rvert< Q >::combine_SBE_to_K2(), rvert< Q >::combine_SBE_to_K2b(), rvert< Q >::combine_SBE_to_K3_SBE(), compute_components_through_FDTs(), rvert< Q >::enforce_freqsymmetriesK1(), rvert< Q >::enforce_freqsymmetriesK2(), rvert< Q >::enforce_freqsymmetriesK3(), get_slice(), multidimensional::BlockView< T, depth >::get_vec(), partial_deriv(), and rvert< Q >::symmetry_expand().
getMultIndex() [1/2]
template<size_t rank, typename I = size_t, typename std::enable_if_t< std::is_integral< I >::value, bool > = true> void getMultIndex (std::array< I, rank > & indx, const size_t iflat, const std::array< I, rank > & dims) inline
Definition at line 214 of file math_utils.hpp.
{
    size_t temp = iflat;
    size_t dimtemp = 1;
    for (my_index_t it = 1; it < rank; it++) {
        dimtemp *= dims[it];
    }
    indx[0] = temp / dimtemp;
    temp -= indx[0] * dimtemp;
    for (my_index_t it = 1; it < rank; it++) {
        dimtemp = dimtemp / dims[it];
        indx[it] = temp / dimtemp;
        temp -= indx[it] * dimtemp;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by check_FDTs_K1(), check_FDTs_selfenergy(), get_i0_left_right(), is_zero_due_to_FDTs(), rotate_Keldysh_matrix(), and unrotate_Keldysh_matrix().
getMultIndex() [2/2]
template<size_t rank, typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< int, Types... >::value), bool > = true> void getMultIndex (Types &... i, const size_t iflat, const std::array< size_t, rank > & dims) inline
Definition at line 236 of file math_utils.hpp.
{
    std::array<size_t,rank> temp = {{static_cast<size_t>(i)...}};
    getMultIndex<rank>(temp, iflat, dims);
    int it = 0;
    ((i = temp[it], it++), ...);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
getMultIndex< 1 >()
template<> void getMultIndex< 1 > (std::array< size_t, 1 > & indx, const size_t iflat, const std::array< size_t, 1 > & dims) inline
Template specialization for special case rank == 1.
Definition at line 230 of file math_utils.hpp.
{
    indx[0] = iflat;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
getMultIndexSkippingOneDimension()
template<size_t rank, size_t idim> void getMultIndexSkippingOneDimension (std::array< size_t, rank > & indx, const size_t iflat, const std::array< size_t, rank > & dims) inline
Convert iflat into a multi-index while keeping the idim-th dimension fixed (i.e. assuming that the idim-th direction has dimension = 1)
Definition at line 246 of file math_utils.hpp.
{
    static_assert(idim < rank, "idim must be smaller than rank.");
    size_t temp = iflat;
    size_t dimtemp = 1;
    for (unsigned int it = 1; it < idim; it++) {
        dimtemp *= dims[it];
    }
    for (unsigned int it = idim+1; it < rank; it++) {
        dimtemp *= dims[it];
    }
    if constexpr (idim != 0) {
        indx[0] = temp / dimtemp;
        temp -= indx[0] * dimtemp;
    }
    for (unsigned int it = 1; it < idim; it++) {
        dimtemp = dimtemp / dims[it];
        indx[it] = temp / dimtemp;
        temp -= indx[it] * dimtemp;
    }
    for (unsigned int it = idim+1; it < rank; it++) {
        dimtemp = dimtemp / dims[it];
        indx[it] = temp / dimtemp;
        temp -= indx[it] * dimtemp;
    }
    indx[idim] = 0;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
heaviside()
auto heaviside (const double x) -> double
Definition at line 3 of file math_utils.c++.
{
    if (x > 0.0){
        return 1.0;
    }
    else if (x < 0.0){
        return 0.0;
    }
    else if (x == 0.0){
        return 0.5;
    }
    else {
        std::cout << "x ill-defined! \n";
        assert(false);
        return 0.;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
integer_division_ceil()
int integer_division_ceil (int a, int b)
Definition at line 25 of file math_utils.c++.
{
    assert(b>0);
    if (a >= 0) {
        const int result = (a + b - 1) / b;
        return result;
    }
    else {
        const int result = - ((-a) / b);
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by ceil2bfreq().
integer_division_floor()
int integer_division_floor (int a, int b)
Definition at line 37 of file math_utils.c++.
{
    assert(b>0);
    if (a >= 0) {
        const int result = a / b;
        assert(result <= a);
        return result;
    }
    else {
        const int result = - ((-a + b - 1) / b);
        assert(result <= 0);
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by floor2bfreq().
is_doubleOccurencies()
auto is_doubleOccurencies (const vec< freqType > & freqs) -> int
Definition at line 128 of file math_utils.c++.
{
    for (unsigned int i = 0; i < freqs.size() - 1; i++){
        if (freqs[i] == freqs[i+1]) return 1;
    }
    return 0;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::initialize_grid(), and FrequencyGrid< hybridGrid >::initialize_grid().
is_symmetric()
auto is_symmetric (const rvec & freqs) -> double
Definition at line 135 of file math_utils.c++.
{
    double asymmetry = 0;
    for (unsigned int i = 0; i< freqs.size() - 1; i++){
        asymmetry += std::abs(freqs[i] + freqs[freqs.size()-i-1]);
    }
    return asymmetry;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
K2_convert2internalFreqs()
void K2_convert2internalFreqs (freqType & w, freqType & v)
converts the frequencies to the parametrization that is used internally, e.g. rotate frequency plane
Insert this function before interpolation
need to convert natural parametrization to internal coordinates when interpolating
convert frequencies w and v to polar coordinates rho and phi (with phi in [-Pi, Pi])
Definition at line 184 of file math_utils.c++.
{
#ifdef ROTATEK2
    // The internal parametrization corresponds to the fermionic frequencies at the two fermionic legs of K2
    const double w_tmp = w*0.5 + v;
    const double v_tmp = w*0.5 - v;
    w = w_tmp;
    v = v_tmp;
#endif
    if constexpr (GRID == 2) {
        const double rho = sqrt(w*w*0.25 + v*v);
        const double phi = atan2(v,  w*0.5); //rho < 1e-15 ? 0. : acos(  w*0.5 / rho);
        assert(isfinite(phi));
        assert(std::abs(phi) < M_PI + 1e-15);
        assert(rho > -1e-15);
        v = phi;// * (v > 0 ? 1. : -1.);
        w = rho;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_grid_index(), and bufferFrequencyGrid< k >::is_in_box().
K2_convert2naturalFreqs()
void K2_convert2naturalFreqs (freqType & w, freqType & v)
Insert this function before returning frequency values
need to convert internal coordinates to natural parametrization when retrieving frequencies at a specific grid point -> get_freqs_w(w,v)
convert polar coordinates to frequencies (w,v) = rho * (cos phi * 2, sin phi)
Definition at line 204 of file math_utils.c++.
{
    if constexpr (GRID == 2) {
        const double w_temp = w * cos(v) * 2;
        const double v_temp = w * sin(v);
        w = w_temp;
        v = v_temp;
    }
#ifdef ROTATEK2
    const double w_tmp = w + v;
    const double v_tmp =(w - v)*0.5;
    w = w_tmp;
    v = v_tmp;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_freqs_w().
K3_convert2internalFreqs()
void K3_convert2internalFreqs (freqType & w, freqType & v, freqType & vp)
Insert this function before interpolation
need to convert natural parametrization to internal coordinates when interpolating
Definition at line 222 of file math_utils.c++.
{
    if constexpr (GRID == 2) {
        // for spherical coordinates:
        // (vp, v, w/2) = rho * (cos phi * sin theta, cos phi * sin theta, cos theta)
        // rho = || (vp, v, w/2) ||
        // phi = atan(v / vp)
        // theta = acos(w/2 / rho)
        const double rho = sqrt(w*w*0.25 + v*v + vp*vp);
        const double phi = atan2(  v, vp);
        const double theta = rho < 1e-15 ? 0. : acos(w*0.5/rho);
        //const double r = sqrt(v*v + vp*vp);
        //const double theta = atan2(r, w*0.5);
        assert(isfinite(phi));
        vp = theta;
        v = phi;
        assert(std::abs(phi) < M_PI + 1e-15);
        assert(theta > -1e-15);
        assert(rho > -1e-15);
        w = rho;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_grid_index(), and bufferFrequencyGrid< k >::is_in_box().
K3_convert2naturalFreqs()
void K3_convert2naturalFreqs (freqType & w, freqType & v, freqType & vp)
Insert this function before returning frequency values
need to convert internal coordinates to natural parametrization when retrieving frequencies at a specific grid point -> get_freqs_w(w,v,vp)
Definition at line 245 of file math_utils.c++.
{
    if constexpr (GRID == 2) {
        // for spherical coordinates:
        // (vp, v, w/2) = rho * (cos phi * sin theta, cos phi * sin theta, cos theta)
        const double vp_temp = w * cos(v) * sin(vp);
        const double v_temp  = w * sin(v) * sin(vp);
        const double w_temp= w          * cos(vp) * 2;
        w = w_temp;
        v = v_temp;
        vp = vp_temp;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GRID.
Referenced by bufferFrequencyGrid< k >::get_freqs_w().
lagrangePoly()
template<int degreeplus, typename Q > auto lagrangePoly (const Q x, const double(&) xs[degreeplus], const Q(&) ys[degreeplus]) -> Q inline
Definition at line 82 of file math_utils.hpp.
{
    Q result = 0.;
    double denominator, numerator;
    for (int i = 0; i < degreeplus; i++) {
        numerator = 1.;
        denominator = 1.;
        for (int k = 0; k < i; k++) {
            denominator *= (xs[i] - xs[k]);
            numerator *= (x - xs[k]);
        }
        for (int k = i+1; k < degreeplus; k++) {
            denominator *= (xs[i] - xs[k]);
            numerator *= (x - xs[k]);
        }
        result += ys[i] * numerator/denominator;
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
locate()
template<typename T > void locate (const std::vector< T > xx, const size_t n, const T x, int & j, const int jl_start, const int ju_start) inline
Given an array xx[0..n-1], and given a value x, returns a value j such that x is between xx[j] and xx[j+1]. xx must be monotonically increasing.
Definition at line 1038 of file math_utils.hpp.
{
    int ju, jm, jl;
    //Initialize lower and upper limits.
    jl = jl_start;
    ju = ju_start;
    //int ascnd = (xx[n-1] >= xx[0]); // +1 for monotonically increasing xx; -1 for decreasing xx
    //If we are not yet done, compute a midpoint; and replace either the lower limit or the upper limit
    while (ju - jl > 1) {
        jm = (ju + jl)/2;
        if (x >= xx[jm])
            jl = jm;
        else
            ju = jm;
    }
    j = jl;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by FrequencyGrid< eliasGrid >::get_grid_index(), and FrequencyGrid< eliasGrid >::get_grid_index().
maxabs() [1/2]
template<std::size_t rank, typename T > vec< double > maxabs (const multidimensional::multiarray< T, rank > & data, const std::array< size_t, rank > & dims, const size_t i_dim)
Definition at line 985 of file math_utils.hpp.
{
    //vec<T> data_temp = vec<T>(data.begin(),data.end());
    return maxabs<rank,T>(vec<T>(data.begin(),data.end()), data.length(), i_dim);
}
References multidimensional::multiarray< T, depth >::begin(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::end(), and multidimensional::multiarray< T, depth >::length().
maxabs() [2/2]
template<size_t rank, typename T > vec< double > maxabs (const vec< T > & data, const std::array< size_t, rank > & dims, const size_t i_dim)
Computes maximum along axis i_dim.
Definition at line 973 of file math_utils.hpp.
{
    vec<double> result (dims[i_dim]);
    std::array<size_t,1> i_dims = {i_dim};
    std::array<size_t,1> dims_new = {dims[i_dim]};
    if (data.size() == dims[i_dim]) result = data.abs(); // no other dimensions to collapse
    //else result = collapse_rev(data, [](const T& l, const T& r) -> T {return static_cast<T>(std::max(std::abs(l),std::abs(r)));}, dims, i_dim).abs();
    else result = collapse(data, [](const T& l, const T& r) -> T {return static_cast<T>(std::max(std::abs(l),std::abs(r)));}, dims, i_dims, dims_new).abs();
        //else result = collapse_rev(data, [](const T& l, const T& r) -> T {return l + r;}, dims, i_dim).abs();
    return result;
}
References vec< T >::abs(), abs(), collapse(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by SelfEnergy< Q >::analyze_tails(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::analyze_tails(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box(), and test_read_write_data_hdf().
multiply()
template<typename T , size_t rank> auto multiply (const std::array< T, rank > & l, const std::array< T, rank > & r) -> std::array<T,rank>
math utilities for arrays
Definition at line 1060 of file math_utils.hpp.
{
    std::array<T,rank> res = l;
    for (int i = 0; i < rank; i++) {
        res[i] *= r[i];
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
my_integer_pow()
template<unsigned int n, typename Q > constexpr Q my_integer_pow (const Q i) constexpr
Definition at line 13 of file math_utils.hpp.
{
    if constexpr(n == 0) return 1;
    else if constexpr(n == 1) return i;
    else return i * my_integer_pow<n-1,Q>(i);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_integer_pow().
Referenced by my_integer_pow(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::numSamples_half(), and Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::numSamples_half().
myround()
auto myround (double x) -> double
Definition at line 58 of file math_utils.c++.
{
    const double tol = 1e-10;
    if (x <= -0.5) return floor(x+tol);
    else return ceil(x-tol);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
partial_deriv() [1/2]
template<typename T , size_t rank> multidimensional::multiarray< T, rank > partial_deriv (const multidimensional::multiarray< T, rank > & data, const size_t i_dim)
partial derivative with finite differences method (accuracy: 2nd order)
Definition at line 793 of file math_utils.hpp.
{
    assert(i_dim < rank);
    assert(data.length()[i_dim] > 2); // data must have at least 3 indices in dimension i_dim.
    //utils::print("Computing partial derivative in direction ", i_dim);
    const size_t flatsize = getFlatSize(data.length());
    const size_t dimsL = data.length_cumul()[i_dim];
    const size_t dimsR = flatsize / dimsL;
    Eigen::Matrix<T,Eigen::Dynamic,Eigen::Dynamic>  m_temp = data.get_elements();
    m_temp.resize(dimsL,dimsR);
    const size_t blockCols = dimsR-2;
    const size_t blockRows = dimsL;
    // derivative for central indices
    Eigen::Matrix<T,Eigen::Dynamic,Eigen::Dynamic> m_result(dimsL, dimsR);
    m_result.block(0,1, blockRows, blockCols) = m_temp.block(0,0, blockRows, blockCols) * (-0.5)
                                                            + m_temp.block(0,2, blockRows, blockCols) * ( 0.5);
    // derivative for smallest indices
    m_result.block(0,0, blockRows, 1) = m_temp.block(0,0, blockRows, 1) * (-3./2.)
                                                             + m_temp.block(0,1, blockRows, 1) * ( 2.)
                                                             + m_temp.block(0,2, blockRows, 1) * (-0.5);
    // derivative for highest indices
    m_result.block(0,dimsR-1, blockRows, 1) = m_temp.block(0,dimsR-3, blockRows, 1) * ( 1./2.)
                                                                   + m_temp.block(0,dimsR-2, blockRows, 1) * (-2.)
                                                                   + m_temp.block(0,dimsR-1, blockRows, 1) * ( 3./2.);
    return multidimensional::multiarray<T,rank>(data.length(), m_result);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::get_elements(), getFlatSize(), multidimensional::multiarray< T, depth >::length(), and multidimensional::multiarray< T, depth >::length_cumul().
partial_deriv() [2/2]
template<typename T , size_t rank> vec< T > partial_deriv (const vec< T > & data, const vec< freqType > & xs, const std::array< size_t, rank > & dims, const size_t i_dim, const double order = 5)
TODO: Write function that directly computes the curvature TODO: Write function that computes the derivative / curvature on an equidistant grid compute the partial derivative of some data with the finite differences method
Template Parameters
T datatype of data
rank
Parameters
data
xs frequency values in data (currently only equidistant grids allowed)
dims number of points in the respective directions of data, in column-major (as implemented in the flat index of data)
i_dim direction in which the derivative is computed; needs to be 0 <= i_dim < rank
order determines exactness
Returns
Definition at line 746 of file math_utils.hpp.
{
    if (i_dim >= rank) assert(false);
    std::array<size_t,rank> dims_permuted;
    vec<size_t> dims_temp = permuteCyclic<rank>(dims, rank - i_dim - 1);
    for (size_t i = 0; i < rank; i++) dims_permuted[i] = dims_temp[i];
    std::array<size_t,rank> permutation;
    for (size_t i = 0; i <= i_dim; i++) permutation[i] = i + rank - i_dim - 1;
    for (size_t i = i_dim+1; i < rank; i++) permutation[i] = i - i_dim - 1;
    return get_finite_differences_v2<T,rank>(data, xs, dims_permuted, permutation);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
partial_deriv_v2()
template<typename T , size_t rank> vec< T > partial_deriv_v2 (const vec< T > & data, const vec< freqType > & xs, const std::array< size_t, rank > & dims, const size_t i_dim, const double order = 5)
Compute the partial derivative on a uniform grid with grid spacing 1
Definition at line 761 of file math_utils.hpp.
{
    if (i_dim >= rank) assert(false);
    std::array<size_t,rank> dims_permuted;
    vec<size_t> dims_temp = permuteCyclic<rank>(dims, rank - i_dim - 1);
    for (size_t i = 0; i < rank; i++) dims_permuted[i] = dims_temp[i];
    std::array<size_t,rank> permutation;
    for (size_t i = 0; i <= i_dim; i++) permutation[i] = i + rank - i_dim - 1;
    for (size_t i = i_dim+1; i < rank; i++) permutation[i] = i - i_dim - 1;
    return get_finite_differences_v4<T,rank>(data, xs, dims_permuted, permutation, order);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
power2() [1/2]
template<typename T , std::size_t rank> vec< T > power2 (const multidimensional::multiarray< T, rank > & data)
Definition at line 968 of file math_utils.hpp.
{
    return power2(vec<T>(data.begin(), data.end()));
}
References multidimensional::multiarray< T, depth >::begin(), multidimensional::multiarray< T, depth >::end(), and power2().
power2() [2/2]
template<typename T > vec< T > power2 (const vec< T > & vec_in)
Definition at line 957 of file math_utils.hpp.
{
    size_t flatdim = vec_in.size();
    vec <T> result (flatdim);
    T temp;
    for (size_t it = 0; it < flatdim; it++) {
        temp = std::abs(vec_in[it]);
        result[it] = temp * temp;
    }
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), and power2().
rotateFlatIndex() [1/2]
template<size_t rank> size_t rotateFlatIndex (const size_t iflat, const std::array< size_t, rank > & dims, const std::array< size_t, rank > & permutation)
Takes a flat index and returns a flat index for a vector with rotated directions
Template Parameters
rank rank of tensor (number of "directions")
Parameters
iflat flat index in row-major acc. to dims
dims contains number of points in each direction
permutation determines how the dimensions are to be permuted for permutation = {a, b, c} dims is permuted to {dims[a], dims[b], dims[c]} A vector has a native order of dimensions. The permutation allows to express the multi-index in a rotated version. But the permutation needs to picked such that it permutes indx and perms into the native order.
Returns
Definition at line 287 of file math_utils.hpp.
{
    std::array<size_t,rank> multIndx;
    getMultIndex<rank>(multIndx, iflat, dims);
    size_t iflat_new = math_impl::getFlatIndex(multIndx, dims, permutation); //(const size_t (&indx) [rank], size_t (&dims) [rank], size_t (&permutation) [rank]) {
    return iflat_new;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and math_impl::getFlatIndex().
Referenced by collapse(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), rotateFlatIndex(), and Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_coeffs_from_b().
rotateFlatIndex() [2/2]
template<size_t rank> size_t rotateFlatIndex (const size_t iflat, const std::array< size_t, rank > & dims_native, const size_t i_dim)
Wraps above function to rotate the i_dim-th element of dims to the trailing dimension; permutation is a cyclic permutation: elements of of dims are shifted to the right until i_dim is the trailing dimension of the rotated flat index
Definition at line 299 of file math_utils.hpp.
{
    assert(i_dim <= rank);
    std::array<size_t,rank>  permutation;
    std::array<size_t,rank>  dims_rot;
    // just make sure that permutation[-1] == i_dim
    for (size_t i = 0; i < rank-i_dim-1; i++) {
        //permutation[i] = i + 1 + i_dim;
        dims_rot[i] = dims_native[i + 1 + i_dim];
    }
    for (size_t i = rank-i_dim-1; i < rank; i++) {
        //permutation[i] = i - rank + 1 + i_dim;
        dims_rot[i] = dims_native[i - rank + 1 + i_dim]; // dims_rot[rank-1] = dims_native[i_dim]
    }
    for (size_t i = 0      ; i <=i_dim; i++) permutation[i] = i + rank - 1 - i_dim;   // permutation[i_dim] = rank - 1
    for (size_t i = i_dim+1; i < rank ; i++) permutation[i] = i - 1 - i_dim;
    size_t iflat_new = rotateFlatIndex(iflat, dims_rot, permutation);
    return iflat_new;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and rotateFlatIndex().
round2bfreq()
auto round2bfreq (double w) -> double
Definition at line 96 of file math_utils.c++.
{
    const int w_int = (int) (w + 0.1*sign(w));
    const double result = 2.* (double) (w_int / 2); // rounding toward zero in integer division
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sign().
Referenced by FrequencyGrid< eliasGrid >::set_essential_parameters().
round2ffreq()
auto round2ffreq (double w) -> double
Definition at line 101 of file math_utils.c++.
{
    const int w_int = (int) (w + 0.1*sign(w));
    const double result = 2.* (double) ((w_int-1) / 2) + 1.; // rounding toward zero in integer division
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sign().
Referenced by FrequencyGrid< eliasGrid >::set_essential_parameters().
round2Infty()
auto round2Infty (double x) -> double
Functions for rounding to Matsubara frequencies
Definition at line 51 of file math_utils.c++.
{
    const double tol = 1e-10;
    // trunc() rounds towards zero
    if (x <= 0.) return floor(x+tol);
    else return ceil(x-tol);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
sgn()
double sgn (double x)
Definition at line 21 of file math_utils.c++.
{
    return (x >= 0) - (x <= 0); // (x > 0) ? 1. : ((x < 0) ? -1. : 0.);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by Fermi_fac(), FrequencyGrid< angularGrid >::frequency_from_t(), FrequencyGrid< hybridGrid >::frequency_from_t(), grid_transf_inv_v4(), grid_transf_v2(), grid_transf_v4(), boost::numeric::odeint::detail::integrate_nonadaptive(), integration_measure_v2(), integration_measure_v4(), ode_solver_impl::rkqs(), FrequencyGrid< angularGrid >::t_from_frequency(), and FrequencyGrid< hybridGrid >::t_from_frequency().
sign()
template<typename T > auto sign (T x) -> double
TODO: Which implementation is more efficient? This one or the one below? (with ternary operators)
Definition at line 24 of file math_utils.hpp.
{
    return (T(0) < x) - (x < T(0));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by check_SE_causality(), Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::GM_REG2(), flowgrid::sqrt_parametrization::lambda_from_t(), round2bfreq(), round2ffreq(), Propagator< Q >::SM_REG2(), and flowgrid::sqrt_parametrization::t_from_lambda().
sign_index()
template<typename Q > auto sign_index (Q freq) -> int
returns 0 for freq<=0 and 1 for freq>0
Template Parameters
Q
Parameters
freq
Returns
Definition at line 40 of file math_utils.hpp.
{
    if constexpr (std::is_same_v<Q,int>) {
        return (freq > 0);
    }
    else {
        const double safety = 1e-10;
        return (freq > safety); // safety to ensure that w=0 gets sign_w=-1
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by rvert< Q >::check_symmetries(), rvert< Q >::enforce_freqsymmetriesK1(), rvert< Q >::enforce_freqsymmetriesK2(), and rvert< Q >::enforce_freqsymmetriesK3().
signFlipCorrection_MF()
auto signFlipCorrection_MF (freqType w) -> freqType
Definition at line 107 of file math_utils.c++.
{
#if not KELDYSH_FORMALISM and not ZERO_TEMP
    const freqType correction = signFlipCorrection_MF_int(w) * 2;
    return correction;
#else
    assert(false);
    return 0.;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and signFlipCorrection_MF_int().
Referenced by rvert< Q >::enforce_freqsymmetriesK2(), rvert< Q >::enforce_freqsymmetriesK3(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K2(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K3(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_value(), bufferFrequencyGrid< k >::is_in_box(), T1(), T2(), TC(), and TR().
signFlipCorrection_MF_int()
int signFlipCorrection_MF_int (freqType w)
Definition at line 117 of file math_utils.c++.
{
#if not KELDYSH_FORMALISM and not ZERO_TEMP
    const int correction = -((int) (std::abs(w / 2) ) ) % 2;
    assert(correction==0 or correction == -1);
    return correction;
#else
    assert(false);
    return 0;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value(), Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, inter >::interpolate_impl(), and signFlipCorrection_MF().
subtract()
template<typename T , size_t rank> auto subtract (const std::array< T, rank > & l, const std::array< T, rank > & r) -> std::array<T,rank>
Definition at line 1077 of file math_utils.hpp.
{
    std::array<T,rank> res = l;
    for (int i = 0; i < rank; i++) {
        res[i] -= r[i];
    }
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2bosonicFreqs()
template<char > void switch2bosonicFreqs (double & w_in, double & v1_in, double & v2_in)
Base template for a channel.
Function to switch from the natural parametrization to the bosonic one
Definition at line 997 of file math_utils.hpp.
{
    double w, v1, v2;
    w  = w_in;                              // input.w  = w_a
    v1 = v1_in+v2_in;                    // input.v1 = v_a
    v2 = v1_in-v2_in;                    // input.v2 = v'_a'
    w_in  = w;
    v1_in = v1;
    v2_in = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2bosonicFreqs< 'p'>()
template<> void switch2bosonicFreqs< 'p'> (double & w_in, double & v1_in, double & v2_in)
Functions for change of coordinates (for 2D and 3D):
Definition at line 146 of file math_utils.c++.
{
    double w, v1, v2;
    w  = -v1_in - v2_in;                    // input.w  = w_p
    v1 =  w_in;                              // input.v1 = v_p
    v2 =  v1_in - v2_in;                    // input.v2 = v'_p
    w_in  = w;
    v1_in = v1;
    v2_in = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2bosonicFreqs< 't'>()
template<> void switch2bosonicFreqs< 't'> (double & w_in, double & v1_in, double & v2_in)
Definition at line 155 of file math_utils.c++.
{
    double w, v1, v2;
    w  = v1_in - v2_in;                    // input.w  = w_t
    v1 = v1_in + v2_in;                    // input.v1 = v_t
    v2 = w_in;                              // input.v2 = v'_t
    w_in  = w;
    v1_in = v1;
    v2_in = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2naturalFreqs()
template<char > void switch2naturalFreqs (double & w_a, double & w_p, double & w_t)
Base template for a channel.
Function to switch from the bosonic parametrization to the natural one
Definition at line 1015 of file math_utils.hpp.
{
    double w, v1, v2;
    w  = w_a;                              // input.w = w_a
    v1 = 0.5*(w_p + w_t);              // input.w = w_p
    v2 = 0.5*(w_p - w_t);              // input.w = w_t
    w_a  = w;
    w_p = v1;
    w_t = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2naturalFreqs< 'p'>()
template<> void switch2naturalFreqs< 'p'> (double & w_a, double & w_p, double & w_t)
Definition at line 165 of file math_utils.c++.
{
    double w, v1, v2;
    w  = w_p;                             // input.w  = w_a
    v1 = 0.5*( - w_a + w_t);              // input.v1 = w_p
    v2 = 0.5*( - w_a - w_t);              // input.v2 = w_t
    w_a  = w;
    w_p = v1;
    w_t = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
switch2naturalFreqs< 't'>()
template<> void switch2naturalFreqs< 't'> (double & w_a, double & w_p, double & w_t)
Definition at line 174 of file math_utils.c++.
{
    double w, v1, v2;
    w  = w_t;                             // input.w  = w_a
    v1 = 0.5*( w_a + w_p);               // input.v1 = w_p
    v2 = 0.5*(-w_a + w_p);               // input.v2 = w_t
    w_a  = w;
    w_p = v1;
    w_t = v2;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().