#!/bin/bash
#SBATCH -o /home/hpc/uh3o1/ri26yad/LOG/Density_matrix/myjob.%j.%N.out
#SBATCH -D /home/hpc/uh3o1/ri26yad/RUN
#SBATCH -J some_job
#SBATCH --get-user-env
#SBATCH --clusters=mpp2
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=28
#SBATCH --mail-type=end
#SBATCH --export=NONE
#SBATCH --time=00:15:00

cd /naslx/projects/uh3o1/ri26yad/DATA/Unit_tests/Conductance_zero_mag
/home/hpc/uh3o1/ri26yad/bin/conductance_zero_mag_compare /naslx/projects/uh3o1/ri26yad/DATA/keldysh_low_acc/Conductance/U_.55_B_0.0_T_0.01_/Chain_N31_Vg0.250000_mu-1.475000000_T0.010000000_h0.000000000_U\ 0.550000.mat
