SIAM-Keldysh-mfRG: FrequencyGrid< eliasGrid > Class Reference
FrequencyGrid< eliasGrid > Class Reference
#include <frequency_grid.hpp>
Public Member Functions
void guess_essential_parameters (double Lambda, const fRG_config &config)
guess essential parameters from value of Lambda
void derive_auxiliary_parameters ()
derive auxiliary parameters from essential parameters
FrequencyGrid (char type_in, unsigned int diag_class_in, double Lambda, const fRG_config &config, bool purely_positive=false)
This constructor initializes a frequency grid with the global values. This is not needed anymore!
auto get_frequency (int index) const -> freqType
getter functions
auto get_auxiliary_gridpoint (int index) const -> freqType
auto get_all_frequencies () const -> vec< freqType >
auto get_all_auxiliary_gridpoints () const -> vec< freqType >
freqType get_spacing_auxiliary_gridpoints () const
char get_type () const
char get_diag_class () const
void set_essential_parameters (const freqType wmax_in, const freqType Wscale_in)
setter functions
void set_w_upper (freqType wmax)
void set_w_center (freqType w_center_in)
auto wscale_from_wmax (freqType &Wscale, freqType w1, freqType wmax, int N) -> double
void initialize_grid ()
void update_Wscale (freqType Wscale)
auto get_grid_index (freqType w_in) const -> int
core grid functionality (has to be super efficient)
int get_grid_index (freqType &t, freqType w_in) const
auto t_from_frequency (freqType w) const -> freqType
grid functions:
auto frequency_from_t (freqType t) const -> freqType
Public Attributes
int number_of_gridpoints
essential grid parameters:
freqType w_upper
freqType w_lower
freqType W_scale
freqType w_center = 0
char type
grid identifier
unsigned int diag_class
bool purely_positive
freqType t_upper
auxiliary grid parameters:
freqType t_lower
freqType spacing_auxiliary_gridpoint
double U_factor = 0./3.
double Delta_factor = 10.
vec< freqType > all_frequencies
list of all frequencies:
vec< freqType > auxiliary_grid
Friends
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type >
class DataContainer
template<typename gridType >
void hdf5_impl::init_freqgrid_from_hdf_LambdaLayer (H5::Group &group, gridType &freqgrid, int Lambda_it, double Lambda)
template<typename gridType >
void hdf5_impl::write_freqparams_to_hdf_LambdaLayer (H5::Group &group, const gridType &freqgrid, const int Lambda_it, const int numberLambdaLayers, const bool file_exists, const bool verbose)
Detailed Description
Definition at line 70 of file frequency_grid.hpp.
Constructor & Destructor Documentation
FrequencyGrid()
FrequencyGrid< eliasGrid >::FrequencyGrid (char type_in, unsigned int diag_class_in, double Lambda, const fRG_config & config, bool purely_positive = false) inline
This constructor initializes a frequency grid with the global values. This is not needed anymore!
Definition at line 112 of file frequency_grid.hpp.
                                                                                                                                 : type(type_in), diag_class(diag_class_in), purely_positive(purely_positive) {
        guess_essential_parameters(Lambda, config);
    };
Member Function Documentation
derive_auxiliary_parameters()
void FrequencyGrid< eliasGrid >::derive_auxiliary_parameters ()
derive auxiliary parameters from essential parameters
Definition at line 33 of file frequency_grid.c++.
{
    t_upper = t_from_frequency(w_upper);
    t_lower = t_from_frequency(w_lower);
    spacing_auxiliary_gridpoint = (t_upper - t_lower) / ((double) (number_of_gridpoints-1));
}
frequency_from_t()
auto FrequencyGrid< eliasGrid >::frequency_from_t (freqType t) const -> freqType
The used frequency_from_t function is determined here
Parameters
t point on auxiliary grid
Returns
Definition at line 238 of file frequency_grid.c++.
{
    if constexpr (KELDYSH) return grid_transf_inv_v2(t, this->W_scale, w_center);
    else if (this->type == 'f' and this->diag_class == 1) {
        if (ZERO_T) return grid_transf_inv_v3(t, this->W_scale, w_center);
        else return grid_transf_inv_lin(t, this->W_scale) + (std::is_same_v<freqType,int> and type=='f' ? 1 : 0);
    }
        //else if (this->type == 'b' and this->diag_class == 1) {
        //    return grid_transf_inv_v2(w, this->W_scale);
        //}
    else { // TODO(medium): Remove commented part?
        if constexpr (KELDYSH || ZERO_T) return grid_transf_inv_v4(t, this->W_scale, w_center);
        else return grid_transf_inv_lin(t, this->W_scale) + (std::is_same_v<freqType,int> and type=='f' ? 1 : 0);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), grid_transf_inv_lin(), grid_transf_inv_v2(), grid_transf_inv_v3(), grid_transf_inv_v4(), KELDYSH, and ZERO_T.
get_all_auxiliary_gridpoints()
auto FrequencyGrid< eliasGrid >::get_all_auxiliary_gridpoints () const -> vec<freqType> inline
Definition at line 120 of file frequency_grid.hpp.
{return auxiliary_grid;}
get_all_frequencies()
auto FrequencyGrid< eliasGrid >::get_all_frequencies () const -> vec<freqType> inline
Definition at line 119 of file frequency_grid.hpp.
{return all_frequencies;}
get_auxiliary_gridpoint()
auto FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint (int index) const -> freqType inline
Definition at line 118 of file frequency_grid.hpp.
{assert(index>=0); assert(index<number_of_gridpoints); assert(isfinite(auxiliary_grid[index])); return auxiliary_grid[index];};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_aux(), and bufferFrequencyGrid< k >::get_freqs_aux().
get_diag_class()
char FrequencyGrid< eliasGrid >::get_diag_class () const inline
Definition at line 123 of file frequency_grid.hpp.
{return diag_class;};
get_frequency()
auto FrequencyGrid< eliasGrid >::get_frequency (int index) const -> freqType inline
getter functions
Definition at line 117 of file frequency_grid.hpp.
{assert(index>=0); assert(index<number_of_gridpoints); assert(isfinite(all_frequencies[index])); return all_frequencies[index];};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), and bufferFrequencyGrid< k >::get_grid_index().
get_grid_index() [1/2]
auto FrequencyGrid< eliasGrid >::get_grid_index (freqType & t, freqType w_in) const
This function returns the index corresponding to the frequency w_in. It rounds down due to the narrowing conversion from double to int. This is only used for (linear) interpolations. Hence the narrowing conversion is harmless.
TODO: If this is not satisfied -> use locate
Definition at line 177 of file frequency_grid.c++.
{
    t = t_from_frequency(w_in);
    assert(isfinite(t));
#ifdef PARAMETRIZED_GRID
    freqType t_rescaled = (t - t_lower) / spacing_auxiliary_gridpoint;
    auto index = ((int) t_rescaled) ;  // round down
    if constexpr(INTERPOLATION==linear) {
        index = std::max(0, index);
        index = std::min(number_of_gridpoints - 2, index);
    }
    else {
        if (all_frequencies[index+1] < w_in and index < number_of_gridpoints-1)
            index++;
        if (all_frequencies[index] > w_in and index > 0)
            index--;
        index = std::max(0, index);
        index = std::min(number_of_gridpoints - 2, index);
        assert(all_frequencies[index] - w_in  <= 1e-5*std::abs(w_in) or index == 0);
        assert(w_in - all_frequencies[index+1] < 1e-5 or index == number_of_gridpoints-2);
    }
    return index;
#else
    int j;
    if (INTERPOLATION==linear) {locate(all_frequencies, number_of_gridpoints, w_in, j, 0, number_of_gridpoints-1);} // we cannot interpolate with infinity
    else {locate(auxiliary_grid, number_of_gridpoints, t, j, 0, number_of_gridpoints-1); }
    int index = j;
        assert(all_frequencies[index] - w_in  <= 1e-5 or index == 0);
        assert(w_in - all_frequencies[index+1] < 1e-5 or index == number_of_gridpoints-1);
    return index;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), INTERPOLATION, linear, and locate().
get_grid_index() [2/2]
auto FrequencyGrid< eliasGrid >::get_grid_index (freqType w_in) const -> int
core grid functionality (has to be super efficient)
This function returns the index corresponding to the frequency w_in. It rounds down due to the narrowing conversion from double to int. This is only used for (linear) interpolations. Hence the narrowing conversion is harmless.
Definition at line 143 of file frequency_grid.c++.
{
#ifdef PARAMETRIZED_GRID
    const freqType t = (t_from_frequency(w_in) - t_lower) / spacing_auxiliary_gridpoint;
#ifdef DENSEGRID
    auto index = ((int) (t + 0.1 )) ;
#else
    int index = ((int) t) ;
    if (INTERPOLATION==linear) {
        index = std::max(0, index);
        index = std::min(number_of_gridpoints - 2, index);
    }
    else {
        if (all_frequencies[index+1] < w_in) index++;
        index = std::max(0, index);
        index = std::min(number_of_gridpoints - 2, index);
    }
#endif
    return index;
#else
    int j;
    if (INTERPOLATION==linear) {locate(all_frequencies, number_of_gridpoints, w_in, j, 0, number_of_gridpoints-1);} // we cannot interpolate with infinity
    else {locate(all_frequencies, number_of_gridpoints, w_in, j, 0, number_of_gridpoints-1); }
    int index = j;
        assert(all_frequencies[index] - w_in  <= 1e-5 or index == 0);
        assert(w_in - all_frequencies[index+1] < 1e-5 or index == number_of_gridpoints-1);
    return index;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), INTERPOLATION, linear, and locate().
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), and bufferFrequencyGrid< k >::get_grid_index().
get_spacing_auxiliary_gridpoints()
freqType FrequencyGrid< eliasGrid >::get_spacing_auxiliary_gridpoints () const inline
Definition at line 121 of file frequency_grid.hpp.
{return spacing_auxiliary_gridpoint;}
get_type()
char FrequencyGrid< eliasGrid >::get_type () const inline
Definition at line 122 of file frequency_grid.hpp.
{return type;};
guess_essential_parameters()
void FrequencyGrid< eliasGrid >::guess_essential_parameters (double Lambda, const fRG_config & config)
guess essential parameters from value of Lambda
Definition at line 38 of file frequency_grid.c++.
{
    U_factor = 0.;
    switch (diag_class) {
        case 1:
            switch (type) {
                case 'b':
                    number_of_gridpoints = nBOS;
                    Delta_factor = Delta_factor_K1;
                    break;
                case 'f':
                    number_of_gridpoints = nFER;
                    Delta_factor = Delta_factor_SE;
                    break;
                default:
                    break;
                    }
            break;
        case 2:
            switch (type) {
                case 'b':
                    number_of_gridpoints = nBOS2;
                    Delta_factor = Delta_factor_K2_w;
                    #ifdef ROTATEK2
                    if (KELDYSH){
                            U_factor = 0.;
                            Delta_factor = 5.;
                        }
                        else{
                            U_factor = 10./3.;
                            Delta_factor = 10.;
                        }
                    #endif
                    break;
                case 'f':
                    number_of_gridpoints = nFER2;
                    Delta_factor = Delta_factor_K2_v;
                    #ifdef ROTATEK2
                    if (KELDYSH) {
                        U_factor = 0.;
                        Delta_factor = 5.;
                    }
                    else {
                        U_factor = 10./3.;
                        Delta_factor = 10.;
                    }
                    #endif
                    break;
                default:
                    break;
                }
            break;
        case 3:
            switch (type) {
                case 'b':
                    number_of_gridpoints = nBOS3;
                    Delta_factor = Delta_factor_K3_w;
                    break;
                case 'f':
                    number_of_gridpoints = nFER3;
                    Delta_factor = Delta_factor_K3_v;
                    break;
                default:;
                }
        default:;
    }
    freqType scale;
    if constexpr(REG == 2) {
        // scale the grid with Delta until Delta = T_K (Kondo temperature), then scale with T_K
        double Delta = (Lambda + config.Gamma) / 2.;
        scale = Delta_factor * Delta;
    }
    else if constexpr(REG == 3) {
        scale = std::max(U_factor * config.U, Delta_factor * (config.Gamma) / 2. + Lambda * (Lambda + 1));
    }
    else {
        //scale = std::max(U_factor * glb_U, Delta_factor * (config.Gamma) / 2.);
        scale = Delta_factor * (config.Gamma) / 2.;
    }
    freqType wmax_guess = scale * 100.;
#if not KELDYSH_FORMALISM and not ZERO_TEMP
    scale = 2;
    wmax_guess = (number_of_gridpoints-1);
#endif
    all_frequencies = vec<freqType>(number_of_gridpoints);
    auxiliary_grid = vec<freqType>(number_of_gridpoints);
    set_essential_parameters(wmax_guess, scale);
    initialize_grid();
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Delta_factor_K1, Delta_factor_K2_v, Delta_factor_K2_w, Delta_factor_K3_v, Delta_factor_K3_w, Delta_factor_SE, fRG_config::Gamma, KELDYSH, nBOS, nBOS2, nBOS3, nFER, nFER2, nFER3, REG, and fRG_config::U.
Referenced by bufferFrequencyGrid< k >::guess_essential_parameters().
initialize_grid()
void FrequencyGrid< eliasGrid >::initialize_grid ()
This function initializes the frequency grid according to the grid parameters w_upper(=-w_lower): upper limit of frequency box number_of_gridpoints: number of frequency points W_scale: non-linearity of the t_from_frequency function
Definition at line 10 of file frequency_grid.c++.
{
    derive_auxiliary_parameters();
    freqType W;
    for(int i=0; i<number_of_gridpoints; ++i) {
        W = t_lower + i * spacing_auxiliary_gridpoint;
        all_frequencies[i] = frequency_from_t(W);
        assert(my_isfinite(all_frequencies[i]));
        auxiliary_grid[i]= W;
    }
    if (purely_positive) {
        all_frequencies[0] = 0.;
        auxiliary_grid[0] = 0.;
    }
    //if (number_of_gridpoints % 2 == 1 and not purely_positive) {
    //    all_frequencies[(int) number_of_gridpoints / 2] = 0.;  // make sure that the center of the grid is exactly zero (and not ~10^{-30})
    //    auxiliary_grid[(int) number_of_gridpoints / 2] = 0.;
    //}
    if (!KELDYSH && !ZERO_T) assert (is_doubleOccurencies(all_frequencies) == 0);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), is_doubleOccurencies(), KELDYSH, my_isfinite(), and ZERO_T.
set_essential_parameters()
void FrequencyGrid< eliasGrid >::set_essential_parameters (const freqType wmax_in, const freqType Wscale_in) inline
setter functions
TODO: Figure out better solution for non-uniform grid
Definition at line 127 of file frequency_grid.hpp.
{
        if constexpr (!KELDYSH && !ZERO_T){
#ifndef DENSEGRID
            // for Matsubara T>0: pick grid such that no frequencies occur twice
            if (type == 'b') {
                w_upper = std::max(round2bfreq(wmax_in), (double)(number_of_gridpoints+1));
            }
            else {
                w_upper = std::max(round2ffreq(wmax_in), (double)(number_of_gridpoints+1));
            }
#endif
        }
        w_upper = wmax_in;
        if (purely_positive) {
            w_lower = 0;
        }
        else {
            w_lower = -wmax_in;
        }
        if constexpr(!KELDYSH && !ZERO_T)
        {
#ifndef DENSEGRID
            // for Matsubara T>0: pick grid such that no frequencies occur twice
            if (type == 'b') {
                W_scale = wscale_from_wmax(W_scale, 2, w_upper, (number_of_gridpoints - 1) / 2);
            } else {
                W_scale = wscale_from_wmax(W_scale, 1, w_upper, number_of_gridpoints - 1);
            }
#else
            // for Matsubara T>0: pick grid such that no frequencies occur twice
        W_scale = Wscale_in;
#endif
        }
        else {
            W_scale = Wscale_in;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, round2bfreq(), round2ffreq(), and ZERO_T.
set_w_center()
void FrequencyGrid< eliasGrid >::set_w_center (freqType w_center_in) inline
Definition at line 171 of file frequency_grid.hpp.
{
        w_center = w_center_in;
        const double w_upper_centered = (w_upper - w_lower) * 0.5;
        w_upper = w_upper_centered + w_center_in;
        w_lower =-w_upper_centered + w_center_in;
        initialize_grid();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
set_w_upper()
void FrequencyGrid< eliasGrid >::set_w_upper (freqType wmax) inline
Definition at line 170 of file frequency_grid.hpp.
{double scale = W_scale; set_essential_parameters(wmax, scale);};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
t_from_frequency()
auto FrequencyGrid< eliasGrid >::t_from_frequency (freqType w) const -> freqType
grid functions:
The used t_from_frequency function is determined here
Parameters
w frequency
Returns
Definition at line 217 of file frequency_grid.c++.
{
    if constexpr (KELDYSH) return grid_transf_v2(w, this->W_scale, w_center);
    else if (this->type == 'f' and this->diag_class == 1) {
        if constexpr (ZERO_T) return grid_transf_v3(w, this->W_scale, w_center);
        else return grid_transf_lin(w, this->W_scale);
    }
        //else if (this->type == 'b' and this->diag_class == 1) {
        //    return grid_transf_v2(w, this->W_scale);
        //}
    else {
        if constexpr (ZERO_T) return grid_transf_v4(w, this->W_scale, w_center);
        else                   return grid_transf_lin(w, this->W_scale);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), grid_transf_lin(), grid_transf_v2(), grid_transf_v3(), grid_transf_v4(), KELDYSH, and ZERO_T.
Referenced by bufferFrequencyGrid< k >::gridtransf_f().
update_Wscale()
void FrequencyGrid< eliasGrid >::update_Wscale (freqType Wscale)
Definition at line 134 of file frequency_grid.c++.
{
    W_scale = Wscale;
    initialize_grid();
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
wscale_from_wmax()
auto FrequencyGrid< eliasGrid >::wscale_from_wmax (freqType & Wscale, freqType w1, freqType wmax, int N) -> double
This function picks a suitable W_scale for a given wmax for Matsubara T>0
Returns
Wscale non-linearity of t_from_frequency()
Parameters
w1 first positive Matsubara frequency
wmax upper bound of frequency grid
N relates tmax to t1 by t1=tmax/N (for bosons: (nBOS-1)/2; for fermions: nFER-1)
Definition at line 260 of file frequency_grid.c++.
{
    if (!KELDYSH && !ZERO_T){
        if (this->type == 'f' and this->diag_class == 1) {
            return wscale_from_wmax_v3(Wscale, w1, wmax, N);
        }
        else {
            return wscale_from_wmax_v1(Wscale, w1, wmax, N);
        }
    }
    else {
        assert(false);
        return 0;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, wscale_from_wmax_v1(), wscale_from_wmax_v3(), and ZERO_T.
Friends And Related Symbol Documentation
DataContainer
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > friend class DataContainer friend
Definition at line 71 of file frequency_grid.hpp.
hdf5_impl::init_freqgrid_from_hdf_LambdaLayer
template<typename gridType > void hdf5_impl::init_freqgrid_from_hdf_LambdaLayer (H5::Group & group, gridType & freqgrid, int Lambda_it, double Lambda) friend
hdf5_impl::write_freqparams_to_hdf_LambdaLayer
template<typename gridType > void hdf5_impl::write_freqparams_to_hdf_LambdaLayer (H5::Group & group, const gridType & freqgrid, const int Lambda_it, const int numberLambdaLayers, const bool file_exists, const bool verbose) friend
Member Data Documentation
all_frequencies
vec<freqType> FrequencyGrid< eliasGrid >::all_frequencies
list of all frequencies:
Definition at line 104 of file frequency_grid.hpp.
auxiliary_grid
vec<freqType> FrequencyGrid< eliasGrid >::auxiliary_grid
Definition at line 105 of file frequency_grid.hpp.
Delta_factor
double FrequencyGrid< eliasGrid >::Delta_factor = 10.
Definition at line 100 of file frequency_grid.hpp.
diag_class
unsigned int FrequencyGrid< eliasGrid >::diag_class
Definition at line 92 of file frequency_grid.hpp.
number_of_gridpoints
int FrequencyGrid< eliasGrid >::number_of_gridpoints
essential grid parameters:
Definition at line 79 of file frequency_grid.hpp.
purely_positive
bool FrequencyGrid< eliasGrid >::purely_positive
Definition at line 93 of file frequency_grid.hpp.
spacing_auxiliary_gridpoint
freqType FrequencyGrid< eliasGrid >::spacing_auxiliary_gridpoint
Definition at line 98 of file frequency_grid.hpp.
t_lower
freqType FrequencyGrid< eliasGrid >::t_lower
Definition at line 97 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_tlower_b_aux(), and bufferFrequencyGrid< k >::get_tlower_f_aux().
t_upper
freqType FrequencyGrid< eliasGrid >::t_upper
auxiliary grid parameters:
Definition at line 96 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_tupper_b_aux(), and bufferFrequencyGrid< k >::get_tupper_f_aux().
type
char FrequencyGrid< eliasGrid >::type
grid identifier
Definition at line 91 of file frequency_grid.hpp.
U_factor
double FrequencyGrid< eliasGrid >::U_factor = 0./3.
Definition at line 99 of file frequency_grid.hpp.
w_center
freqType FrequencyGrid< eliasGrid >::w_center = 0
Definition at line 83 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::is_in_box(), bufferFrequencyGrid< k >::is_in_box(), and bufferFrequencyGrid< k >::is_in_box().
w_lower
freqType FrequencyGrid< eliasGrid >::w_lower
Definition at line 81 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_wlower_b(), and bufferFrequencyGrid< k >::get_wlower_f().
W_scale
freqType FrequencyGrid< eliasGrid >::W_scale
Definition at line 82 of file frequency_grid.hpp.
w_upper
freqType FrequencyGrid< eliasGrid >::w_upper
Definition at line 80 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_wupper_b(), bufferFrequencyGrid< k >::get_wupper_f(), bufferFrequencyGrid< k >::is_in_box(), bufferFrequencyGrid< k >::is_in_box(), and bufferFrequencyGrid< k >::is_in_box().
The documentation for this class was generated from the following files:
frequency_grid.hpp
frequency_grid.c++