SIAM-Keldysh-mfRG: bufferFrequencyGrid< k > Class Template Reference
bufferFrequencyGrid< k > Class Template Reference
#include <frequency_grid.hpp>
Public Types
using grid_type1 = FrequencyGrid<eliasGrid>
using grid_type2 = FrequencyGrid<eliasGrid>
using grid_type3 = FrequencyGrid<eliasGrid>
Public Member Functions
int get_diagclass ()
bufferFrequencyGrid ()
bufferFrequencyGrid (double Lambda, const fRG_config &config)
void guess_essential_parameters (double Lambda, const fRG_config &config)
auto get_freqGrid_b () const -> const grid_type1 &
getter functions:
auto get_freqGrid_f () const -> const grid_type2 &
auto get_freqGrid_3 () const -> const grid_type2 &
const freqType & get_wlower_b () const
const freqType & get_wupper_b () const
const freqType & get_wlower_f () const
const freqType & get_wupper_f () const
const freqType & get_tlower_b_aux () const
const freqType & get_tupper_b_aux () const
const freqType & get_tlower_f_aux () const
const freqType & get_tupper_f_aux () const
bool is_in_box (std::array< freqType, 1 > freqs) const
Check whether frequencies are in the frequency box:
bool is_in_box (std::array< freqType, 2 > freqs) const
bool is_in_box (std::array< freqType, 3 > freqs) const
void get_grid_index (std::array< my_index_t, 1 > &idx, std::array< double, 1 > &dw_normalized, const std::array< freqType, 1 > &freqs) const
determine the grid indices for the frequencies + determine normalized distance to next smaller grid point on all_frequencies
void get_grid_index (std::array< my_index_t, 2 > &idx, std::array< double, 2 > &dw_normalized, const std::array< freqType, 2 > &freqs) const
void get_grid_index (std::array< my_index_t, 3 > &idx, std::array< double, 3 > &dw_normalized, const std::array< freqType, 3 > &freqs) const
void get_auxgrid_index (std::array< my_index_t, 1 > &idx, std::array< double, 1 > &dt_normalized, const std::array< freqType, 1 > &freqs) const
determine the grid indices for the frequencies + determine normalized distance to next smaller grid point on auxiliary grid
void get_auxgrid_index (std::array< my_index_t, 2 > &idx, std::array< freqType, 2 > &dt_normalized, const std::array< freqType, 2 > &freqs) const
void get_auxgrid_index (std::array< my_index_t, 3 > &idx, std::array< double, 3 > &dt_normalized, const std::array< freqType, 3 > &freqs) const
void get_auxgrid_index_unnormalized (std::array< my_index_t, 1 > &idx, std::array< double, 1 > &dt_unnormalized, const std::array< freqType, 1 > &freqs) const
determine the grid indices for the frequencies + determine UN-normalized distance to next smaller grid point on auxiliary grid
void get_auxgrid_index_unnormalized (std::array< my_index_t, 2 > &idx, std::array< double, 2 > &dt_unnormalized, const std::array< freqType, 2 > &freqs) const
void get_auxgrid_index_unnormalized (std::array< my_index_t, 3 > &idx, std::array< double, 3 > &dt_unnormalized, const std::array< freqType, 3 > &freqs) const
void get_freqs_w (freqType &w, const int iw) const
get frequencies corresponding to a set of grid indices
void get_freqs_w (freqType &w, freqType &v, const int iw, const int iv) const
void get_freqs_w (freqType &w, freqType &v, freqType &vp, const int iw, const int iv, const int ivp) const
template<size_t num>
void get_freqs_w (std::array< freqType, num > &freqs, std::array< my_index_t, num > &i_freqs) const
void get_freqs_aux (freqType &w, const int iw) const
only used in test_functions:
void get_freqs_aux (freqType &w, freqType &v, const int iw, const int iv) const
void get_freqs_aux (freqType &w, freqType &v, double &vp, const int iw, const int iv, const int ivp) const
auto gridtransf_f (freqType w) const -> freqType
Public Attributes
grid_type1 primary_grid
grid_type2 secondary_grid
grid_type3 tertiary_grid
double T
Detailed Description
template<K_class k>
class bufferFrequencyGrid< k >
Definition at line 375 of file frequency_grid.hpp.
Member Typedef Documentation
grid_type1
template<K_class k> using bufferFrequencyGrid< k >::grid_type1 = FrequencyGrid<eliasGrid>
Definition at line 378 of file frequency_grid.hpp.
grid_type2
template<K_class k> using bufferFrequencyGrid< k >::grid_type2 = FrequencyGrid<eliasGrid>
Definition at line 379 of file frequency_grid.hpp.
grid_type3
template<K_class k> using bufferFrequencyGrid< k >::grid_type3 = FrequencyGrid<eliasGrid>
Definition at line 380 of file frequency_grid.hpp.
Constructor & Destructor Documentation
bufferFrequencyGrid() [1/2]
template<K_class k> bufferFrequencyGrid< k >::bufferFrequencyGrid () inline
Definition at line 401 of file frequency_grid.hpp.
:    primary_grid(k == selfenergy ? 'f' : 'b', get_diagclass(), 0, fRG_config(), GRID==2), secondary_grid('f', get_diagclass(), 0, fRG_config(), false), tertiary_grid('f', get_diagclass(), 0, fRG_config(), GRID==2) {};
bufferFrequencyGrid() [2/2]
template<K_class k> bufferFrequencyGrid< k >::bufferFrequencyGrid (double Lambda, const fRG_config & config) inline
Definition at line 402 of file frequency_grid.hpp.
                                                                 :  T(config.T), primary_grid(k == selfenergy ? 'f' : 'b', get_diagclass(), Lambda, config, GRID==2 and (k==k2 or k==k2b or k==k3))
                                         , secondary_grid('f', get_diagclass(), Lambda, config, false)
                                         , tertiary_grid('f', get_diagclass(), Lambda, config, GRID==2)
    {};
Member Function Documentation
get_auxgrid_index() [1/3]
template<K_class k> void bufferFrequencyGrid< k >::get_auxgrid_index (std::array< my_index_t, 1 > & idx, std::array< double, 1 > & dt_normalized, const std::array< freqType, 1 > & freqs) const inline
determine the grid indices for the frequencies + determine normalized distance to next smaller grid point on auxiliary grid
Definition at line 510 of file frequency_grid.hpp.
{
        if constexpr(k == k1 or k == selfenergy)  {
            //double w = freqs[0];
            freqType tw;
            int iw =   primary_grid.get_grid_index(tw, freqs[0]);
            idx[0] = iw;
            double tw_low =   primary_grid.get_auxiliary_gridpoint(iw);
            double tw_high=   primary_grid.get_auxiliary_gridpoint(iw+1);
            dt_normalized[0] = (tw - tw_low) / (tw_high - tw_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_grid_index(), k1, bufferFrequencyGrid< k >::primary_grid, and selfenergy.
get_auxgrid_index() [2/3]
template<K_class k> void bufferFrequencyGrid< k >::get_auxgrid_index (std::array< my_index_t, 2 > & idx, std::array< freqType, 2 > & dt_normalized, const std::array< freqType, 2 > & freqs) const inline
Definition at line 522 of file frequency_grid.hpp.
{
        if constexpr(k == k2)  {
            freqType w  = freqs[0];
            freqType v  = freqs[1];
            K2_convert2internalFreqs(w, v);
            freqType tw, tv;
            int iw =   primary_grid.get_grid_index(tw, w);
            int iv = secondary_grid.get_grid_index(tv, v);
            idx[0] = iw;
            idx[1] = iv;
            double tw_low =   primary_grid.get_auxiliary_gridpoint(iw);
            double tw_high=   primary_grid.get_auxiliary_gridpoint(iw+1);
            double tv_low = secondary_grid.get_auxiliary_gridpoint(iv);
            double tv_high= secondary_grid.get_auxiliary_gridpoint(iv+1);
            dt_normalized[0] = (tw - tw_low) / (tw_high - tw_low);
            dt_normalized[1] = (tv - tv_low) / (tv_high - tv_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_grid_index(), k2, K2_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, and bufferFrequencyGrid< k >::secondary_grid.
get_auxgrid_index() [3/3]
template<K_class k> void bufferFrequencyGrid< k >::get_auxgrid_index (std::array< my_index_t, 3 > & idx, std::array< double, 3 > & dt_normalized, const std::array< freqType, 3 > & freqs) const inline
Definition at line 542 of file frequency_grid.hpp.
{
        if constexpr(k == k3 or (k == k2 and SBE_DECOMPOSITION))  {
            freqType w  = freqs[0];
            freqType v  = freqs[1];
            freqType vp = freqs[2];
            K3_convert2internalFreqs(w, v, vp);
            freqType tw, tv, tvp;
            int iw =   primary_grid.get_grid_index(tw, w);
            int iv = secondary_grid.get_grid_index(tv, v);
            int ivp=  tertiary_grid.get_grid_index(tvp,vp);
            idx[0] = iw;
            idx[1] = iv;
            idx[2] = ivp;
            double tw_low =   primary_grid.get_auxiliary_gridpoint(iw);
            double tw_high=   primary_grid.get_auxiliary_gridpoint(iw+1);
            double tv_low = secondary_grid.get_auxiliary_gridpoint(iv);
            double tv_high= secondary_grid.get_auxiliary_gridpoint(iv+1);
            double tvp_low =tertiary_grid.get_auxiliary_gridpoint(ivp);
            double tvp_high=tertiary_grid.get_auxiliary_gridpoint(ivp+1);
            dt_normalized[0] = (tw - tw_low) / (tw_high - tw_low);
            dt_normalized[1] = (tv - tv_low) / (tv_high - tv_low);
            dt_normalized[2] = (tvp-tvp_low) / (tvp_high-tvp_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_grid_index(), k2, k3, K3_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, SBE_DECOMPOSITION, bufferFrequencyGrid< k >::secondary_grid, and bufferFrequencyGrid< k >::tertiary_grid.
get_auxgrid_index_unnormalized() [1/3]
template<K_class k> void bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized (std::array< my_index_t, 1 > & idx, std::array< double, 1 > & dt_unnormalized, const std::array< freqType, 1 > & freqs) const inline
determine the grid indices for the frequencies + determine UN-normalized distance to next smaller grid point on auxiliary grid
Definition at line 569 of file frequency_grid.hpp.
{
        if constexpr(k == k1 or k == selfenergy)  {
            //double w = freqs[0];
            freqType tw;
            int iw =   primary_grid.get_grid_index(tw, freqs[0]);
            idx[0] = iw;
            double tw_low =   primary_grid.get_auxiliary_gridpoint(iw);
            double tw_high=   primary_grid.get_auxiliary_gridpoint(iw+1);
            dt_unnormalized[0] = (tw - tw_low); // / (tw_high - tw_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_grid_index(), k1, bufferFrequencyGrid< k >::primary_grid, and selfenergy.
get_auxgrid_index_unnormalized() [2/3]
template<K_class k> void bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized (std::array< my_index_t, 2 > & idx, std::array< double, 2 > & dt_unnormalized, const std::array< freqType, 2 > & freqs) const inline
Definition at line 581 of file frequency_grid.hpp.
{
        if constexpr(k == k2)  {
            freqType w  = freqs[0];
            freqType v  = freqs[1];
            K2_convert2internalFreqs(w, v);
            freqType tw, tv;
            int iw =   primary_grid.get_grid_index(tw, w);
            int iv = secondary_grid.get_grid_index(tv, v);
            idx[0] = iw;
            idx[1] = iv;
            double tw_low =   primary_grid.get_auxiliary_gridpoint(iw);
            //double tw_high=   primary_grid.get_auxiliary_gridpoint(iw+1);
            double tv_low = secondary_grid.get_auxiliary_gridpoint(iv);
            //double tv_high= secondary_grid.get_auxiliary_gridpoint(iv+1);
            dt_unnormalized[0] = (tw - tw_low); // / (tw_high - tw_low);
            dt_unnormalized[1] = (tv - tv_low); // / (tv_high - tv_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_grid_index(), k2, K2_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, and bufferFrequencyGrid< k >::secondary_grid.
get_auxgrid_index_unnormalized() [3/3]
template<K_class k> void bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized (std::array< my_index_t, 3 > & idx, std::array< double, 3 > & dt_unnormalized, const std::array< freqType, 3 > & freqs) const inline
Definition at line 601 of file frequency_grid.hpp.
{
        if constexpr(k == k3 or (k == k2 and SBE_DECOMPOSITION))  {
            freqType w  = freqs[0];
            freqType v  = freqs[1];
            freqType vp = freqs[2];
            K3_convert2internalFreqs(w, v, vp);
            freqType tw, tv, tvp;
            const int iw =   primary_grid.get_grid_index(tw, w);
            const int iv = secondary_grid.get_grid_index(tv, v);
            const int ivp=  tertiary_grid.get_grid_index(tvp,vp);
            idx[0] = iw;
            idx[1] = iv;
            idx[2] = ivp;
            const double tw_low =   primary_grid.get_auxiliary_gridpoint(iw);
            //const double tw_high=   primary_grid.get_auxiliary_gridpoint(iw+1);
            const double tv_low = secondary_grid.get_auxiliary_gridpoint(iv);
            //const double tv_high= secondary_grid.get_auxiliary_gridpoint(iv+1);
            const double tvp_low = tertiary_grid.get_auxiliary_gridpoint(ivp);
            //const double tvp_high= tertiary_grid.get_auxiliary_gridpoint(ivp+1);
            dt_unnormalized[0] = (tw - tw_low); // / (tw_high - tw_low);
            dt_unnormalized[1] = (tv - tv_low); // / (tv_high - tv_low);
            dt_unnormalized[2] = (tvp-tvp_low); // / (tvp_high-tvp_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), FrequencyGrid< eliasGrid >::get_grid_index(), k2, k3, K3_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, SBE_DECOMPOSITION, bufferFrequencyGrid< k >::secondary_grid, and bufferFrequencyGrid< k >::tertiary_grid.
get_diagclass()
template<K_class k> int bufferFrequencyGrid< k >::get_diagclass () inline
Definition at line 395 of file frequency_grid.hpp.
{
        if constexpr(k == selfenergy or k == k1) return 1;
        else if constexpr(k == k2 or k == k2b) return 2;
        else return 3;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2, k2b, and selfenergy.
get_freqGrid_3()
template<K_class k> auto bufferFrequencyGrid< k >::get_freqGrid_3 () const -> const grid_type2& inline
Definition at line 418 of file frequency_grid.hpp.
{if constexpr(k == k3)return tertiary_grid; else assert(false);};//, "Exists no fermionic grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k3, and bufferFrequencyGrid< k >::tertiary_grid.
get_freqGrid_b()
template<K_class k> auto bufferFrequencyGrid< k >::get_freqGrid_b () const -> const grid_type1& inline
getter functions:
Definition at line 416 of file frequency_grid.hpp.
{return   primary_grid;};
References bufferFrequencyGrid< k >::primary_grid.
get_freqGrid_f()
template<K_class k> auto bufferFrequencyGrid< k >::get_freqGrid_f () const -> const grid_type2& inline
Definition at line 417 of file frequency_grid.hpp.
{if constexpr(k != k1 and k != selfenergy)return secondary_grid; else assert(false);};//, "Exists no fermionic grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, bufferFrequencyGrid< k >::secondary_grid, and selfenergy.
get_freqs_aux() [1/3]
template<K_class k> void bufferFrequencyGrid< k >::get_freqs_aux (freqType & w, const int iw) const inline
only used in test_functions:
Definition at line 668 of file frequency_grid.hpp.
{
        if constexpr(k == k1 or k == selfenergy) w =   primary_grid.get_auxiliary_gridpoint(iw);
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), k1, bufferFrequencyGrid< k >::primary_grid, and selfenergy.
get_freqs_aux() [2/3]
template<K_class k> void bufferFrequencyGrid< k >::get_freqs_aux (freqType & w, freqType & v, const int iw, const int iv) const inline
Definition at line 672 of file frequency_grid.hpp.
{
        if constexpr(k == k2) {
            w =   primary_grid.get_auxiliary_gridpoint(iw);
            v = secondary_grid.get_auxiliary_gridpoint(iv);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), k2, bufferFrequencyGrid< k >::primary_grid, and bufferFrequencyGrid< k >::secondary_grid.
get_freqs_aux() [3/3]
template<K_class k> void bufferFrequencyGrid< k >::get_freqs_aux (freqType & w, freqType & v, double & vp, const int iw, const int iv, const int ivp) const inline
Definition at line 679 of file frequency_grid.hpp.
{
        if constexpr(k == k3 or (k == k2 and SBE_DECOMPOSITION)) {
            w =   primary_grid.get_auxiliary_gridpoint(iw);
            v = secondary_grid.get_auxiliary_gridpoint(iv);
            vp=  tertiary_grid.get_auxiliary_gridpoint(ivp);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_auxiliary_gridpoint(), k2, k3, bufferFrequencyGrid< k >::primary_grid, SBE_DECOMPOSITION, bufferFrequencyGrid< k >::secondary_grid, and bufferFrequencyGrid< k >::tertiary_grid.
get_freqs_w() [1/4]
template<K_class k> void bufferFrequencyGrid< k >::get_freqs_w (freqType & w, const int iw) const inline
get frequencies corresponding to a set of grid indices
Definition at line 629 of file frequency_grid.hpp.
{
        if constexpr(k == k1 or k == selfenergy) w =   primary_grid.get_frequency(iw);
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_frequency(), k1, bufferFrequencyGrid< k >::primary_grid, and selfenergy.
Referenced by bufferFrequencyGrid< k >::get_freqs_w().
get_freqs_w() [2/4]
template<K_class k> void bufferFrequencyGrid< k >::get_freqs_w (freqType & w, freqType & v, const int iw, const int iv) const inline
Definition at line 633 of file frequency_grid.hpp.
{
        if constexpr(k == k2)
        {
            w =   primary_grid.get_frequency(iw);
            v = secondary_grid.get_frequency(iv);
            K2_convert2naturalFreqs(w, v);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_frequency(), k2, K2_convert2naturalFreqs(), bufferFrequencyGrid< k >::primary_grid, and bufferFrequencyGrid< k >::secondary_grid.
get_freqs_w() [3/4]
template<K_class k> void bufferFrequencyGrid< k >::get_freqs_w (freqType & w, freqType & v, freqType & vp, const int iw, const int iv, const int ivp) const inline
Definition at line 642 of file frequency_grid.hpp.
{
        if constexpr(k == k3 or (k == k2 and SBE_DECOMPOSITION)) {
            w =   primary_grid.get_frequency(iw);
            v = secondary_grid.get_frequency(iv);
            vp = tertiary_grid.get_frequency(ivp);
            K3_convert2naturalFreqs(w, v, vp);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_frequency(), k2, k3, K3_convert2naturalFreqs(), bufferFrequencyGrid< k >::primary_grid, SBE_DECOMPOSITION, bufferFrequencyGrid< k >::secondary_grid, and bufferFrequencyGrid< k >::tertiary_grid.
get_freqs_w() [4/4]
template<K_class k> template<size_t num> void bufferFrequencyGrid< k >::get_freqs_w (std::array< freqType, num > & freqs, std::array< my_index_t, num > & i_freqs) const inline
Definition at line 653 of file frequency_grid.hpp.
{
        if constexpr(num == 1) {
            get_freqs_w(freqs[0], i_freqs[0]);
        }
        else if constexpr(num == 2) {
            get_freqs_w(freqs[0], freqs[1], i_freqs[0], i_freqs[1]);
        }
        else if constexpr(num == 3) {
            get_freqs_w(freqs[0], freqs[1], freqs[2], i_freqs[0], i_freqs[1], i_freqs[2]);
        }
        else assert(false);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and bufferFrequencyGrid< k >::get_freqs_w().
get_grid_index() [1/3]
template<K_class k> void bufferFrequencyGrid< k >::get_grid_index (std::array< my_index_t, 1 > & idx, std::array< double, 1 > & dw_normalized, const std::array< freqType, 1 > & freqs) const inline
determine the grid indices for the frequencies + determine normalized distance to next smaller grid point on all_frequencies
Definition at line 454 of file frequency_grid.hpp.
{
        if constexpr(k == k1 or k == selfenergy)  {
            freqType w = freqs[0];
            int iw =   primary_grid.get_grid_index(w);
            idx[0] = iw;
            double w_low =   primary_grid.get_frequency(iw);
            double w_high=   primary_grid.get_frequency(iw+1);
            dw_normalized[0] = (w - w_low) / (w_high - w_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_frequency(), FrequencyGrid< eliasGrid >::get_grid_index(), k1, bufferFrequencyGrid< k >::primary_grid, and selfenergy.
get_grid_index() [2/3]
template<K_class k> void bufferFrequencyGrid< k >::get_grid_index (std::array< my_index_t, 2 > & idx, std::array< double, 2 > & dw_normalized, const std::array< freqType, 2 > & freqs) const inline
Definition at line 465 of file frequency_grid.hpp.
{
        if constexpr(k == k2)  {
            freqType w  = freqs[0];
            freqType v  = freqs[1];
            K2_convert2internalFreqs(w, v);
            int iw =   primary_grid.get_grid_index(w);
            int iv = secondary_grid.get_grid_index(v);
            idx[0] = iw;
            idx[1] = iv;
            double w_low =   primary_grid.get_frequency(iw);
            double w_high=   primary_grid.get_frequency(iw+1);
            double v_low = secondary_grid.get_frequency(iv);
            double v_high= secondary_grid.get_frequency(iv+1);
            dw_normalized[0] = (w - w_low) / (w_high - w_low);
            dw_normalized[1] = (v - v_low) / (v_high - v_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_frequency(), FrequencyGrid< eliasGrid >::get_grid_index(), k2, K2_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, and bufferFrequencyGrid< k >::secondary_grid.
get_grid_index() [3/3]
template<K_class k> void bufferFrequencyGrid< k >::get_grid_index (std::array< my_index_t, 3 > & idx, std::array< double, 3 > & dw_normalized, const std::array< freqType, 3 > & freqs) const inline
Definition at line 484 of file frequency_grid.hpp.
{
        if constexpr(k == k3 or (k == k2 and SBE_DECOMPOSITION))  {
            freqType w  = freqs[0];
            freqType v  = freqs[1];
            freqType vp = freqs[2];
            K3_convert2internalFreqs(w, v, vp);
            const int iw =   primary_grid.get_grid_index(freqs[0]);
            const int iv = secondary_grid.get_grid_index(freqs[1]);
            const int ivp=  tertiary_grid.get_grid_index(freqs[2]);
            idx[0] = iw;
            idx[1] = iv;
            idx[2] = ivp;
            const double w_low =   primary_grid.get_frequency(iw);
            const double w_high=   primary_grid.get_frequency(iw+1);
            const double v_low = secondary_grid.get_frequency(iv);
            const double v_high= secondary_grid.get_frequency(iv+1);
            const double vp_low =tertiary_grid.get_frequency(ivp);
            const double vp_high=tertiary_grid.get_frequency(ivp+1);
            dw_normalized[0] = (w - w_low) / (w_high - w_low);
            dw_normalized[1] = (v - v_low) / (v_high - v_low);
            dw_normalized[2] = (vp-vp_low) / (vp_high-vp_low);
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::get_frequency(), FrequencyGrid< eliasGrid >::get_grid_index(), k2, k3, K3_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, SBE_DECOMPOSITION, bufferFrequencyGrid< k >::secondary_grid, and bufferFrequencyGrid< k >::tertiary_grid.
get_tlower_b_aux()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_tlower_b_aux () const inline
Definition at line 423 of file frequency_grid.hpp.
{return   primary_grid.t_lower;};
References bufferFrequencyGrid< k >::primary_grid, and FrequencyGrid< eliasGrid >::t_lower.
get_tlower_f_aux()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_tlower_f_aux () const inline
Definition at line 425 of file frequency_grid.hpp.
{if constexpr(k != k1 and k != selfenergy) return secondary_grid.t_lower; else assert(false);};//, "Exists no second grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, bufferFrequencyGrid< k >::secondary_grid, selfenergy, and FrequencyGrid< eliasGrid >::t_lower.
get_tupper_b_aux()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_tupper_b_aux () const inline
Definition at line 424 of file frequency_grid.hpp.
{return   primary_grid.t_upper;};
References bufferFrequencyGrid< k >::primary_grid, and FrequencyGrid< eliasGrid >::t_upper.
get_tupper_f_aux()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_tupper_f_aux () const inline
Definition at line 426 of file frequency_grid.hpp.
{if constexpr(k != k1 and k != selfenergy) return secondary_grid.t_upper; else assert(false);};//, "Exists no second grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, bufferFrequencyGrid< k >::secondary_grid, selfenergy, and FrequencyGrid< eliasGrid >::t_upper.
get_wlower_b()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_wlower_b () const inline
Definition at line 419 of file frequency_grid.hpp.
{return   primary_grid.w_lower;};
References bufferFrequencyGrid< k >::primary_grid, and FrequencyGrid< eliasGrid >::w_lower.
get_wlower_f()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_wlower_f () const inline
Definition at line 421 of file frequency_grid.hpp.
{if constexpr(k != k1 and k != selfenergy) return secondary_grid.w_lower; else assert(false);};//, "Exists no second grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, bufferFrequencyGrid< k >::secondary_grid, selfenergy, and FrequencyGrid< eliasGrid >::w_lower.
get_wupper_b()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_wupper_b () const inline
Definition at line 420 of file frequency_grid.hpp.
{return   primary_grid.w_upper;};
References bufferFrequencyGrid< k >::primary_grid, and FrequencyGrid< eliasGrid >::w_upper.
get_wupper_f()
template<K_class k> const freqType & bufferFrequencyGrid< k >::get_wupper_f () const inline
Definition at line 422 of file frequency_grid.hpp.
{if constexpr(k != k1 and k != selfenergy) return secondary_grid.w_upper; else assert(false);};//, "Exists no second grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, bufferFrequencyGrid< k >::secondary_grid, selfenergy, and FrequencyGrid< eliasGrid >::w_upper.
gridtransf_f()
template<K_class k> auto bufferFrequencyGrid< k >::gridtransf_f (freqType w) const -> freqType inline
Definition at line 687 of file frequency_grid.hpp.
{if constexpr(k != k1 and k != selfenergy) return secondary_grid.t_from_frequency(w); else assert(false);};//, "Exists no second grid");};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, bufferFrequencyGrid< k >::secondary_grid, selfenergy, and FrequencyGrid< eliasGrid >::t_from_frequency().
guess_essential_parameters()
template<K_class k> void bufferFrequencyGrid< k >::guess_essential_parameters (double Lambda, const fRG_config & config) inline
Definition at line 407 of file frequency_grid.hpp.
{
          primary_grid.guess_essential_parameters(Lambda, config);
        if constexpr(k != k1 and k != selfenergy) {
            secondary_grid.guess_essential_parameters(Lambda, config);
             tertiary_grid.guess_essential_parameters(Lambda, config);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), FrequencyGrid< eliasGrid >::guess_essential_parameters(), k1, bufferFrequencyGrid< k >::primary_grid, bufferFrequencyGrid< k >::secondary_grid, selfenergy, and bufferFrequencyGrid< k >::tertiary_grid.
is_in_box() [1/3]
template<K_class k> bool bufferFrequencyGrid< k >::is_in_box (std::array< freqType, 1 > freqs) const inline
Check whether frequencies are in the frequency box:
Definition at line 429 of file frequency_grid.hpp.
{
        if constexpr(k == k1 or k == selfenergy) return std::abs(freqs[0] - primary_grid.w_center) <   primary_grid.w_upper + inter_tol;
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), inter_tol, k1, bufferFrequencyGrid< k >::primary_grid, selfenergy, FrequencyGrid< eliasGrid >::w_center, and FrequencyGrid< eliasGrid >::w_upper.
is_in_box() [2/3]
template<K_class k> bool bufferFrequencyGrid< k >::is_in_box (std::array< freqType, 2 > freqs) const inline
Definition at line 433 of file frequency_grid.hpp.
{
        K2_convert2internalFreqs(freqs[0], freqs[1]);
        if constexpr(k == k2) {
            if constexpr (!KELDYSH_FORMALISM and !ZERO_T) {
                return std::abs(freqs[0]) <   primary_grid.w_upper + inter_tol and (freqs[1] > -secondary_grid.w_upper - inter_tol and freqs[1] < secondary_grid.w_upper + signFlipCorrection_MF(freqs[0]) + inter_tol );
            }
            else {
                return std::abs(freqs[0] - primary_grid.w_center) <   primary_grid.w_upper + inter_tol and std::abs(freqs[1] - secondary_grid.w_center) < secondary_grid.w_upper + inter_tol;
            }
        }
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), inter_tol, k2, K2_convert2internalFreqs(), KELDYSH_FORMALISM, bufferFrequencyGrid< k >::primary_grid, bufferFrequencyGrid< k >::secondary_grid, signFlipCorrection_MF(), FrequencyGrid< eliasGrid >::w_center, FrequencyGrid< eliasGrid >::w_upper, and ZERO_T.
is_in_box() [3/3]
template<K_class k> bool bufferFrequencyGrid< k >::is_in_box (std::array< freqType, 3 > freqs) const inline
Definition at line 447 of file frequency_grid.hpp.
{
        K3_convert2internalFreqs(freqs[0], freqs[1], freqs[2]);
        if constexpr(k == k3 or (k == k2 and SBE_DECOMPOSITION)) return std::abs(freqs[0] - primary_grid.w_center) <   primary_grid.w_upper + inter_tol and std::abs(freqs[1] - secondary_grid.w_center) < secondary_grid.w_upper + inter_tol and std::abs(freqs[2] - tertiary_grid.w_center) < tertiary_grid.w_upper + inter_tol;
        else assert(false); // "Inconsistent number of frequency arguments.");
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), inter_tol, k2, k3, K3_convert2internalFreqs(), bufferFrequencyGrid< k >::primary_grid, SBE_DECOMPOSITION, bufferFrequencyGrid< k >::secondary_grid, bufferFrequencyGrid< k >::tertiary_grid, FrequencyGrid< eliasGrid >::w_center, and FrequencyGrid< eliasGrid >::w_upper.
Member Data Documentation
primary_grid
template<K_class k> grid_type1 bufferFrequencyGrid< k >::primary_grid
Definition at line 390 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_freqGrid_b(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_tlower_b_aux(), bufferFrequencyGrid< k >::get_tupper_b_aux(), bufferFrequencyGrid< k >::get_wlower_b(), bufferFrequencyGrid< k >::get_wupper_b(), bufferFrequencyGrid< k >::guess_essential_parameters(), bufferFrequencyGrid< k >::is_in_box(), bufferFrequencyGrid< k >::is_in_box(), and bufferFrequencyGrid< k >::is_in_box().
secondary_grid
template<K_class k> grid_type2 bufferFrequencyGrid< k >::secondary_grid
Definition at line 391 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_freqGrid_f(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::get_tlower_f_aux(), bufferFrequencyGrid< k >::get_tupper_f_aux(), bufferFrequencyGrid< k >::get_wlower_f(), bufferFrequencyGrid< k >::get_wupper_f(), bufferFrequencyGrid< k >::gridtransf_f(), bufferFrequencyGrid< k >::guess_essential_parameters(), bufferFrequencyGrid< k >::is_in_box(), and bufferFrequencyGrid< k >::is_in_box().
T
template<K_class k> double bufferFrequencyGrid< k >::T
Definition at line 393 of file frequency_grid.hpp.
tertiary_grid
template<K_class k> grid_type3 bufferFrequencyGrid< k >::tertiary_grid
Definition at line 392 of file frequency_grid.hpp.
Referenced by bufferFrequencyGrid< k >::get_auxgrid_index(), bufferFrequencyGrid< k >::get_auxgrid_index_unnormalized(), bufferFrequencyGrid< k >::get_freqGrid_3(), bufferFrequencyGrid< k >::get_freqs_aux(), bufferFrequencyGrid< k >::get_freqs_w(), bufferFrequencyGrid< k >::get_grid_index(), bufferFrequencyGrid< k >::guess_essential_parameters(), and bufferFrequencyGrid< k >::is_in_box().
The documentation for this class was generated from the following file:
frequency_grid.hpp