SIAM-Keldysh-mfRG: old_ode_solvers Namespace Reference
old_ode_solvers Namespace Reference
Functions
template<typename T , typename System >
void RK4_step (T &y_run, double &x_run, const double dx, const System &rhs, bool save_intermediate_results, rvec &x_vals, const std::string &filename, const int iteration)
template<typename T , typename System >
void RK4_step (T &y_run, double &x_run, const double dx, const System &rhs, rvec &x_vals, std::string filename, const int iteration, bool save_intermediate_states)
Function Documentation
RK4_step() [1/2]
template<typename T , typename System > void old_ode_solvers::RK4_step (T & y_run, double & x_run, const double dx, const System & rhs, bool save_intermediate_results, rvec & x_vals, const std::string & filename, const int iteration)
Perform one Runge-Kutta-4 step
Definition at line 16 of file old_solvers.hpp.
{
        T y1; rhs(y_run         , y1, x_run        ); y1 *= dx;
        T y2; rhs(y_run + y1*0.5, y2, x_run + dx/2.); y2 *= dx;
        T y3; rhs(y_run + y2*0.5, y3, x_run + dx/2.); y3 *= dx;
        T y4; rhs(y_run + y3    , y4, x_run + dx   ); y4 *= dx;
        y_run += (y1 + y2*2. + y3*2. + y4) * (1./6.); // update y
        if constexpr(std::is_same_v<T, State<state_datatype>>) {
            rhs.iteration ++;
            rhs.rk_step = 0;
        }
        /*
        if (save_intermediate_results) {
            T y1 = rhs(y_run, x_run, {iteration, 0}) * dx;
            T y2 = rhs(y_run + y1*0.5, x_run + dx/2., {iteration, 1}) * dx;
            T y3 = rhs(y_run + y2*0.5, x_run + dx/2., {iteration, 2}) * dx;
            T y4 = rhs(y_run + y3, x_run + dx, {iteration, 3}) * dx;
            y_run += (y1 + y2*2. + y3*2. + y4) * (1./6.); // update y
        }
        else {
            T y1 = rhs(y_run, x_run, {}) * dx;
            T y2 = rhs(y_run + y1*0.5, x_run + dx/2., {}) * dx;
            T y3 = rhs(y_run + y2*0.5, x_run + dx/2., {}) * dx;
            T y4 = rhs(y_run + y3, x_run + dx, {}) * dx;
            y_run += (y1 + y2*2. + y3*2. + y4) * (1./6.); // update y
        }
*/
        x_run += dx; // update x
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by RK4_step().
RK4_step() [2/2]
template<typename T , typename System > void old_ode_solvers::RK4_step (T & y_run, double & x_run, const double dx, const System & rhs, rvec & x_vals, std::string filename, const int iteration, bool save_intermediate_states)
Perform Runge-Kutta-4 step and write result into output file in a specified Lambda layer, and print info to log
Definition at line 51 of file old_solvers.hpp.
{
        // print iteration number and Lambda to log file
        utils::print("i: ", iteration, true);
        utils::print("Lambda: ", x_run, true);
        // utils::print("y: ", y_run.value, true);
        double t0 = utils::get_time();
        RK4_step(y_run, x_run, dx, rhs, save_intermediate_states, x_vals, filename, iteration); // compute RK4 step
        utils::get_time(t0); // measure time for one iteration
        check_SE_causality(y_run); // check if the self-energy is causal at each step of the flow
        if (KELDYSH and (REG!=5)) check_FDTs(y_run, true); // check FDTs for Sigma and K1r at each step of the flow
        if (filename != "") {
            add_state_to_hdf(filename, iteration + 1,  y_run); // save result to hdf5 file
        }
    }
References add_state_to_hdf(), check_FDTs(), check_SE_causality(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), utils::get_time(), KELDYSH, utils::print(), REG, and RK4_step().