SIAM-Keldysh-mfRG: loop.hpp File Reference
loop.hpp File Reference
#include <cmath>
#include "../correlation_functions/two_point/selfenergy.hpp"
#include "../correlation_functions/four_point/vertex.hpp"
#include "../correlation_functions/two_point/propagator.hpp"
#include "../parameters/master_parameters.hpp"
#include "../integrator/integrator.hpp"
#include "../utilities/write_data2file.hpp"
#include "../asymptotic_corrections/correction_functions.hpp"
#include "integrandSE.hpp"
#include "../utilities/hdf5_routines.hpp"
Classes
class LoopCalculator< Q, vertType, all_spins, version >
Functions
Self-energy loop Class to actually calculate the loop integral for a given external fermionic frequency and internal index. Invoked by the loop function. Note: the vertices in versions 0 and 1 are related by crossing symmetry, hence we expect the results to be identical in both versions
Template Parameters
Q Type of the data.
vertType Type of the vertex used.
all_spins Compute all spin contributions?
version The self-energy loop can be closed in two different versions:
version 0: close the loop above with propagator G^{3|1} => parametrize vertex in t-channel convention with w=0
version 1: close the loop right with propagator G^{2|1} => parametrize vertex in a-channel convention with w=0
3 -->--|-----|-->-- 1
       |  Γ  |
0 --<--|-----|--<-- 2
template<bool all_spins, bool version = 0, typename Q , typename vertType >
void loop (SelfEnergy< Q > &self, const vertType &fullvertex, const Propagator< Q > &prop)
Function Documentation
loop()
template<bool all_spins, bool version = 0, typename Q , typename vertType > void loop (SelfEnergy< Q > & self, const vertType & fullvertex, const Propagator< Q > & prop)
Loop function for calculating the self energy
Template Parameters
all_spins sum over spins in loop?
version : 0 --> symmetry_expand vertex in 't' channel and close the loop ABOVE
     ___<___ prop
    /       \
    \       /
     |-----|
     |  Γ  |
--<--|-----|--<--
1 --> symmetry_expand vertex in 'a' channel and close the loop RIGHT
            /---\
-->--|-----|     |  prop
     |  Γ  |     v
--<--|-----|     |
            \---/
Q : Type of the elements of the vertex, usually comp
Parameters
self : SelfEnergy<Q> object of which the Retarded and Keldysh components will be updated in the loop
fullvertex Vertex object for the calculation of the loop
prop : Propagator object for the calculation of the loop
all_spins : Whether the calculation of the loop should include all spin components of the vertex
problem with aliasing if self is identical to a member of prop
Definition at line 528 of file loop.hpp.
{
    SelfEnergy<Q> self_temp = self;
    fullvertex.initializeInterpol();
#if SWITCH_SUM_N_INTEGRAL
    fullvertex.template symmetry_expand<version == 0 ? 't' : 'a',false,true>();
#endif
    prop.initInterpolator();
#pragma omp parallel for schedule(dynamic) //default(none) shared(self, fullvertex, prop, all_spins)
    for (int iSE = 0; iSE < nSE * n_in; ++iSE) {
        LoopCalculator<Q, vertType, all_spins, version> LoopIntegrationMachine(self_temp, fullvertex, prop, iSE);
        LoopIntegrationMachine.perform_computation();
    }
    self = self_temp * (version == 0 ? 1. : -1.);
    fullvertex.set_initializedInterpol(false);
    if (not PARTICLE_HOLE_SYMMETRY){
        // extract the renormalization of the asymptotic value from the Hartree- and the K1_t and K2'_t terms:
        const Q asymp_val = (self.val(0, 0, 0) + self.val(0, nFER-1, 0)) / 2.;
        self.asymp_val_R = std::real(asymp_val);
        // we do not want to add the asymptotic value twice:
        for (int iv = 0; iv < nFER; ++iv) {
            for (int i_in = 0; i_in < n_in; ++i_in) {
                self.addself(0, iv, i_in, -std::real(asymp_val));
            }
        }
    }
}
References SelfEnergy< Q >::addself(), SelfEnergy< Q >::asymp_val_R, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::initInterpolator(), n_in, nFER, nSE, PARTICLE_HOLE_SYMMETRY, and SelfEnergy< Q >::val().