SIAM-Keldysh-mfRG: mfRG_stats Struct Reference
mfRG_stats Struct Reference
#include <right_hand_sides.hpp>
Public Member Functions
void write_to_hdf (const std::string &filename, const fRG_config &config, const int Lambda_it) const
Public Attributes
int number_of_SE_iterations = 0
double time = 0.
int RKattempts = 0
Detailed Description
Definition at line 133 of file right_hand_sides.hpp.
Member Function Documentation
write_to_hdf()
void mfRG_stats::write_to_hdf (const std::string & filename, const fRG_config & config, const int Lambda_it) const inline
Definition at line 138 of file right_hand_sides.hpp.
{
        if (mpi_world_rank() == 0) {
            const std::size_t numberLambda_layers = config.nODE_ + U_NRG.size() + 1;
            H5::H5File file = open_hdf_file_readWrite(filename);
            const bool data_set_exists = Lambda_it > 1; // Lambda_it == 0 contains initial state => first mfRG stats are in Lambda_it == 1
            H5::Group group_stats;
            if (data_set_exists) {
                group_stats = file.openGroup("mfRG_stats");
            } else {
                group_stats = file.createGroup("mfRG_stats");
            }
            write_to_hdf_LambdaLayer(group_stats, "SE_iterations", vec<int>({number_of_SE_iterations}), Lambda_it, numberLambda_layers, data_set_exists);
            write_to_hdf_LambdaLayer(group_stats, "time_for_mfRG_Eqs", vec<double>({time}), Lambda_it, numberLambda_layers, data_set_exists);
            write_to_hdf_LambdaLayer(group_stats, "RK_attempts", vec<double>({time}), Lambda_it, numberLambda_layers, data_set_exists);
            file.close();
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), mpi_world_rank(), fRG_config::nODE_, number_of_SE_iterations, open_hdf_file_readWrite(), time, U_NRG, and write_to_hdf_LambdaLayer().
Member Data Documentation
number_of_SE_iterations
int mfRG_stats::number_of_SE_iterations = 0
Definition at line 134 of file right_hand_sides.hpp.
Referenced by write_to_hdf().
RKattempts
int mfRG_stats::RKattempts = 0
Definition at line 136 of file right_hand_sides.hpp.
time
double mfRG_stats::time = 0.
Definition at line 135 of file right_hand_sides.hpp.
Referenced by write_to_hdf().
The documentation for this struct was generated from the following file:
right_hand_sides.hpp