SIAM-Keldysh-mfRG: mpi_setup.c++ File Reference
mpi_setup.c++ File Reference
#include "mpi_setup.hpp"
Functions
int mpi_world_rank ()
int mpi_world_size ()
void mpi_collect (vec< comp > &buffer, vec< comp > &result, int n_mpi, int n_omp)
void mpi_collect (vec< double > &buffer, vec< double > &result, int n_mpi, int n_omp)
Function Documentation
mpi_collect() [1/2]
void mpi_collect (vec< comp > & buffer, vec< comp > & result, int n_mpi, int n_omp)
distribute results between all MPI processes, using MPI_Allgather (for data type comp)
Parameters
buffer : buffer vector containing the results of the current process
result : buffer vector in which the results of all processes are written
n_mpi : # of MPI tasks (# of grid points for external variable(s) in which we do MPI parallelization)
n_omp : # of OMP tasks (# of grid points for external variable(s) in which we do OMP parallelization)
Definition at line 15 of file mpi_setup.c++.
{
    int world_size = mpi_world_size();
    MPI_Allgather(&buffer[0], static_cast<int>(2*n_omp*(n_mpi/world_size+1)), MPI_COMPLEX,
                  &result[0], static_cast<int>(2*n_omp*(n_mpi/world_size+1)), MPI_COMPLEX, MPI_COMM_WORLD);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_size().
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_bubble_function().
mpi_collect() [2/2]
void mpi_collect (vec< double > & buffer, vec< double > & result, int n_mpi, int n_omp)
distribute results between all MPI processes, using MPI_Allgather (for data type double)
Parameters
buffer : buffer vector containing the results of the current process
result : buffer vector in which the results of all processes are written
n_mpi : # of MPI tasks (# of grid points for external variable(s) in which we do MPI parallelization)
n_omp : # of OMP tasks (# of grid points for external variable(s) in which we do OMP parallelization)
Definition at line 21 of file mpi_setup.c++.
{
    int world_size = mpi_world_size();
    MPI_Allgather(&buffer[0], static_cast<int>(n_omp*(n_mpi/world_size+1)), MPI_DOUBLE,
                  &result[0], static_cast<int>(n_omp*(n_mpi/world_size+1)), MPI_DOUBLE, MPI_COMM_WORLD);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_size().
mpi_world_rank()
int mpi_world_rank ()
Functions for handling MPI parallelization: initializing buffers, distributing results between MPI processes etc.
Definition at line 3 of file mpi_setup.c++.
                     {
    int world_rank= 0;
    if constexpr (MPI_FLAG) MPI_Comm_rank(MPI_COMM_WORLD, &world_rank);
    return world_rank;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and MPI_FLAG.
Referenced by add_state_to_hdf(), SelfEnergy< Q >::analyze_tails(), fullvert< Q >::analyze_tails_K1(), fullvert< Q >::analyze_tails_K2v(), fullvert< Q >::analyze_tails_K2w(), fullvert< Q >::analyze_tails_K3v(), fullvert< Q >::analyze_tails_K3vp(), fullvert< Q >::analyze_tails_K3w(), anderson_update(), rvert< Q >::check_symmetries(), fullvert< Q >::check_vertex_resolution(), close_hdf_file(), compare_with_FDTs(), create_hdf_file(), utils::get_cpu_hours(), fullvert< Q >::get_curvature_max_K1(), fullvert< Q >::get_curvature_max_K2(), fullvert< Q >::get_curvature_max_K3(), SelfEnergy< Q >::get_curvature_maxSE(), fullvert< Q >::get_deriv_max_K1(), fullvert< Q >::get_deriv_max_K2(), fullvert< Q >::get_deriv_max_K3(), SelfEnergy< Q >::get_deriv_maxSE(), utils::get_time(), utils::get_time(), boost::numeric::odeint::detail::integrate_adaptive_check(), boost::numeric::odeint::detail::integrate_nonadaptive(), utils::makedir(), minimizer(), minimizer_nD(), ode_solver(), dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::optimize_grid(), parquet_solver(), utils::print(), utils::print(), utils::print(), utils::print(), utils::print_add(), utils::print_add(), utils::print_add(), rhs_n_loop_flow(), ode_solver_impl::rkqs(), IntegrandSE< Q, vertType, all_spins, return_type, version >::save_integrand(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box(), write_dat_rvecs(), write_h5_rvecs(), write_state_to_hdf(), mfRG_stats::write_to_hdf(), write_to_hdf(), write_to_hdf(), write_to_hdf(), and write_to_hdf().
mpi_world_size()
int mpi_world_size ()
Definition at line 9 of file mpi_setup.c++.
                     {
    int world_size = 1;
    if constexpr (MPI_FLAG) MPI_Comm_size(MPI_COMM_WORLD, &world_size);
    return world_size;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and MPI_FLAG.
Referenced by utils::get_cpu_hours(), mpi_collect(), mpi_collect(), mpi_initialize_buffer(), mpi_initialize_result(), mpi_reorder_result(), and utils::print_job_info().