SIAM-Keldysh-mfRG: BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object > Class Template Reference
BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object > Class Template Reference
#include <bubble_function.hpp>
Public Member Functions
void perform_computation ()
BubbleFunctionCalculator (vertexType_result &dgamma_in, const vertexType_left &vertex1_in, const vertexType_right &vertex2_in, const Bubble_Object &Pi_in, const int number_of_nodes_in, const std::array< bool, 3 > tobecomputed)
template<K_class diag_class>
auto get_value (const int i_mpi, const int i_omp, const int n_omp, const int n_vectorization) -> value_type
Private Types
using value_type = vec<Q>
Private Member Functions
void check_presence_of_symmetry_related_contributions ()
void set_channel_specific_freq_ranges_and_prefactor ()
void find_vmin_and_vmax ()
template<K_class diag_class>
void calculate_bubble_function ()
template<K_class diag_class>
value_type get_value (int i_mpi, int i_omp, int n_omp, int n_vectorization)
template<K_class diag_class, int spin>
void calculate_value (value_type &value, int i0, int i_in, int iw, freqType w, freqType v, freqType vp)
void write_out_results (const vec< Q > &Ordered_result, K_class diag_class)
void write_out_results_K1 (const vec< Q > &K1_ordered_result)
void write_out_results_K2 (const vec< Q > &K2_ordered_result)
void write_out_results_K2b (const vec< Q > &K2b_ordered_result)
void write_out_results_K3 (const vec< Q > &K3_ordered_result)
void set_external_arguments_for_parallelization (size_t &n_mpi, size_t &n_omp, size_t &n_vectorization, K_class diag_class)
void convert_external_MPI_OMP_indices_to_physical_indices_K1 (int &iK1, int &i0, int &ispin, int &iw, int &i_in, freqType &w, int i_mpi, int n_omp, int i_omp)
void convert_external_MPI_OMP_indices_to_physical_indices_K2 (int &iK2, int &i0, int &ispin, int &iw, int &iv, int &i_in, freqType &w, freqType &v, int i_mpi, int n_omp, int i_omp)
void convert_external_MPI_OMP_indices_to_physical_indices_K2b (int &iK2, int &i0, int &ispin, int &iw, int &ivp, int &i_in, freqType &w, freqType &vp, int i_mpi, int n_omp, int i_omp)
void convert_external_MPI_OMP_indices_to_physical_indices_K3 (int &iK3, int &i0, int &ispin, int &iw, int &iv, int &ivp, int &i_in, freqType &w, freqType &v, freqType &vp, int i_mpi, int n_omp, int i_omp)
int get_trafo_K1 (int i0, freqType w)
int get_trafo_K2 (int i0, freqType w, freqType v)
int get_trafo_K3 (int i0, freqType w, freqType v, freqType vp)
void get_Matsubara_integration_intervals (size_t &num_intervals, vec< vec< freqType > > &intervals, freqType w)
Q bubble_value_prefactor ()
Private Attributes
vertexType_result & dgamma
const vertexType_left vertex1
const vertexType_right vertex2
THIS IS A COPY; needed for symmetry-expansion.
const Bubble_Object & Pi
THIS IS A COPY; needed for symmetry-expansion.
const bool diff = Pi.diff
const double Delta = (Pi.g.Lambda + Pi.g.Gamma) / 2.
int nw1_w = 0
int nw2_w = 0
int nw2_v = 0
int nw3_w = 0
int nw3_v = 0
int nw3_v_p = 0
Q prefactor = 1.
size_t number_of_nodes
size_t mpi_size = mpi_world_size()
size_t mpi_rank = mpi_world_rank()
std::array< std::size_t, my_defs::K1::rank > dimsK1
std::array< std::size_t, my_defs::K2::rank > dimsK2
std::array< std::size_t, my_defs::K3::rank > dimsK3
size_t dims_flat_K1
size_t dims_flat_K2
size_t dims_flat_K3
size_t n_vectorization_K1
size_t n_vectorization_K2
size_t n_vectorization_K3
freqType vmin = 0
freqType vmax = 0
int Nmin
int Nmax
double tK1 = 0
double tK2 = 0
double tK3 = 0
std::array< bool, 3 > tobecomputed
const bool store_integrand_for_PT = false
Detailed Description
template<char channel, typename Q, typename vertexType_result, typename vertexType_left, typename vertexType_right, class Bubble_Object>
class BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >
Class that actually performs the bubble computation. Invoked by the bubble_function.
Template Parameters
channel Two-particle channel of the computation. Can be a, p, or t.
Q Template parameter specifying the type of the data.
vertexType_result Type of the vertex that results in the bubble computation.
vertexType_left Type of the vertex that enters as the left part of the computation.
vertexType_right Type of the vertex that enters as the right part of the computation.
Bubble_Object Type of the Bubble object to connect the two vertices
Definition at line 32 of file bubble_function.hpp.
Member Typedef Documentation
value_type
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > using BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::value_type = vec<Q> private
Definition at line 33 of file bubble_function.hpp.
Constructor & Destructor Documentation
BubbleFunctionCalculator()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator (vertexType_result & dgamma_in, const vertexType_left & vertex1_in, const vertexType_right & vertex2_in, const Bubble_Object & Pi_in, const int number_of_nodes_in, const std::array< bool, 3 > tobecomputed) inline
TODO(high): Figure out computations which need gamma_a_uu = gamma_a_ud - gamma_t_ud in a t-bubble, i.e. CP_to_t(gamma_a_uu) = CP_to_t(gamma_a_ud) - CP_to_a(gamma_t_ud). The integrand will need vertex AND vertex_initial to have access to cross-projected parts and non-crossprojected parts.
Definition at line 109 of file bubble_function.hpp.
                             :dgamma(dgamma_in), vertex1(vertex1_in), vertex2(vertex2_in),
                             Pi(Pi_in), number_of_nodes(number_of_nodes_in), tobecomputed(tobecomputed){
#if not  DEBUG_SYMMETRIES
        //check_presence_of_symmetry_related_contributions();
#endif
        set_channel_specific_freq_ranges_and_prefactor();
        find_vmin_and_vmax();
#if SWITCH_SUM_N_INTEGRAL
        vertex1.template symmetry_expand<channel,true ,false>();
        vertex2.template symmetry_expand<channel,false,false>();
#endif
        vec<int> vectorization_dimensions_K1;
        vec<int> vectorization_dimensions_K2;
        vec<int> vectorization_dimensions_K3;
        if constexpr (VECTORIZED_INTEGRATION) {
            if constexpr (KELDYSH_FORMALISM) {
                vectorization_dimensions_K1 = {my_defs::K1::keldysh};
                vectorization_dimensions_K2 = {my_defs::K2::keldysh};
                vectorization_dimensions_K3 = {my_defs::K3::keldysh};
            }
            else if constexpr (!KELDYSH_FORMALISM and !ZERO_T) {
                vectorization_dimensions_K2 = {my_defs::K2::nu};
                vectorization_dimensions_K3 = {my_defs::K3::nu, my_defs::K3::nup};
            }
        }
        dimsK1 = vertex1.get_rvertex(channel).K1.get_dims();
        dimsK2 = MAX_DIAG_CLASS > 1 ? vertex1.get_rvertex(channel).K2.get_dims() : std::array<std::size_t, my_defs::K2::rank>();
        dimsK3 = MAX_DIAG_CLASS > 2 ? vertex1.get_rvertex(channel).K3.get_dims() : std::array<std::size_t, my_defs::K3::rank>();
        n_vectorization_K1 = 1;
        n_vectorization_K2 = 1;
        n_vectorization_K3 = 1;
        for (int i : vectorization_dimensions_K1) {
            n_vectorization_K1 *= dimsK1[i];
            dimsK1[i] = 1;
            //utils::print("vectorization_dimensions_K1 \t i=", i, "\n");
        }
        for (int i : vectorization_dimensions_K2) {
            n_vectorization_K2 *= dimsK2[i];
            dimsK2[i] = 1;
            //utils::print("vectorization_dimensions_K2 \t i=", i, "\n");
        }
        for (int i : vectorization_dimensions_K3) {
            n_vectorization_K3 *= dimsK3[i];
            dimsK3[i] = 1;
            //utils::print("vectorization_dimensions_K3 \t i=", i, "\n");
        }
        dims_flat_K1 = getFlatSize(dimsK1);
        dims_flat_K2 = getFlatSize(dimsK2);
        dims_flat_K3 = getFlatSize(dimsK3);
        //indepKeldyshComponents_K1 = channel == 'a' ? non_zero_Keldysh_K1a : (channel == 'p'? non_zero_Keldysh_K1p : non_zero_Keldysh_K1t);
        //indepKeldyshComponents_K2 = channel == 'a' ? non_zero_Keldysh_K2a : (channel == 'p'? non_zero_Keldysh_K2p : non_zero_Keldysh_K2t);
        //indepKeldyshComponents_K3 = non_zero_Keldysh_K3;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dims_flat_K1, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dims_flat_K2, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dims_flat_K3, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dimsK1, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dimsK2, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dimsK3, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::find_vmin_and_vmax(), getFlatSize(), my_defs::K1::keldysh, my_defs::K2::keldysh, my_defs::K3::keldysh, KELDYSH_FORMALISM, MAX_DIAG_CLASS, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::n_vectorization_K1, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::n_vectorization_K2, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::n_vectorization_K3, my_defs::K2::nu, my_defs::K3::nu, my_defs::K3::nup, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::set_channel_specific_freq_ranges_and_prefactor(), VECTORIZED_INTEGRATION, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::vertex1, BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::vertex2, and ZERO_T.
Member Function Documentation
bubble_value_prefactor()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > Q BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::bubble_value_prefactor () private
Definition at line 988 of file bubble_function.hpp.
{
    if constexpr (KELDYSH) return prefactor * (1. / (2. * M_PI * glb_i));
    else                   return prefactor * (1. / (2. * M_PI));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), glb_i(), and KELDYSH.
calculate_bubble_function()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > template<K_class diag_class> void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_bubble_function () private
Definition at line 272 of file bubble_function.hpp.
{
    if (diag_class < k1 || diag_class > k3){utils::print("Incompatible diagrammatic class! Abort."); assert(false); return;}
    std::size_t n_mpi, n_omp, n_vectorization;
    set_external_arguments_for_parallelization(n_mpi, n_omp, n_vectorization, diag_class);
    // initialize buffer into which each MPI process writes their results
    vec<Q> Buffer = mpi_initialize_buffer<Q>(n_mpi, n_omp * n_vectorization);
    vertex1.initializeInterpol();
    vertex2.initializeInterpol();
    // start for-loop over external arguments, using MPI and OMP
    int iterator = 0;
    // total number of processes for MPI and OMP parallelization:
    const int dimsKi_flat = diag_class == k1 ? dims_flat_K1 : (diag_class == k3 ? dims_flat_K3 : dims_flat_K2);
    for (int i_mpi = 0; i_mpi < n_mpi; ++i_mpi) {
        if (i_mpi % mpi_size == mpi_rank) {
#pragma omp parallel for schedule(dynamic)
            for (int i_omp = 0; i_omp < n_omp; ++i_omp) {
                if (i_mpi * n_omp + i_omp < dimsKi_flat) {
                    value_type value = get_value<diag_class>(i_mpi, i_omp, n_omp, n_vectorization);
                    for (int k = 0; k < n_vectorization; k++) {
                        Buffer[(iterator * n_omp + i_omp) * n_vectorization + k] = value[k]; // write result of integration into MPI buffer
                    }
                }
            }
            ++iterator;
        }
    }
    // collect+combine results from different MPI processes, reorder them appropriately
    vec<Q> Result = mpi_initialize_result<Q> (n_mpi, n_omp * n_vectorization);
    mpi_collect(Buffer, Result, n_mpi, n_omp * n_vectorization);
    vec<Q> Ordered_result = mpi_reorder_result(Result, n_mpi, n_omp * n_vectorization);
    const int target_size_of_result = diag_class == k1 ? dims_flat_K1 * n_vectorization_K1 : (diag_class == k3 ? dims_flat_K3 * n_vectorization_K3 : dims_flat_K2 * n_vectorization_K2);
#ifndef NDEBUG
    const int current_size_of_result = Ordered_result.size();
    for (int i = target_size_of_result; i < current_size_of_result; i++) {
        assert(std::abs(Ordered_result[i]) < 1e-12);
    }
#endif
    // cut off superflous vector elements:
    Ordered_result.resize(target_size_of_result);
    write_out_results(Ordered_result, diag_class);
    vertex1.set_initializedInterpol(false);
    vertex2.set_initializedInterpol(false);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k3, mpi_collect(), mpi_reorder_result(), and utils::print().
calculate_value()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > template<K_class k, int spin> void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::calculate_value (value_type & value, int i0, int i_in, int iw, freqType w, freqType v, freqType vp) private
determine integral of the integrand's tails via formula (corresponds to quadrature of bare bubble):
determine integral of the integrand's tails via formula:
write integration_result into value
Definition at line 384 of file bubble_function.hpp.
{
#if VECTORIZED_INTEGRATION==1 and KELDYSH_FORMALISM
    using Integrand_class = Integrand<k, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object,Eigen::Matrix<Q,4,4>>;
#else
    using Integrand_class = Integrand<k, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object,Q>;
#endif
    using integrand_valtype = std::result_of_t<Integrand_class(freqType)>;
    integrand_valtype integration_result = myzero<integrand_valtype>();
#if not SWITCH_SUM_N_INTEGRAL
    static_assert(n_spin == 1, "SWITCH_SUM_N_INTEGRAL not ready for DEBUG_SYMMETRIES.");
    for (int i2 : glb_non_zero_Keldysh_bubble) {
        int n_spin_sum = 1;                  // number of summands in spin sum (=1 in the a channel)
        if ((channel == 't' and spin == 0) or (channel == 'a' and spin == 1)) n_spin_sum = 3;  // in the t channel, spin sum includes three terms
        for (int i_spin=0; i_spin < n_spin_sum; ++i_spin) {
#else
    int i2 = 0;
    int i_spin = 0;
#endif
            // initialize the integrand object and perform frequency integration
            Integrand_class integrand(vertex1, vertex2, Pi, i0, i2, iw, w, v, vp, i_in, i_spin, diff);
            if (store_integrand_for_PT){ // for PT-Calculations: Store the integrand for the fully retarded up-down component at zero frequency:
#if SWITCH_SUM_N_INTEGRAL
                assert(false); // Cannot do it this way if the integration is vectorized over the internal Keldysh sum
#endif
                if (channel == 'a' and i0 == 7 and i_spin == 0 and w == 0 and v == 0 and vp == 0) integrand.save_integrand();
            }
            if constexpr(ZERO_T) {
                switch (k) {
                    case k1:
                        integration_result += bubble_value_prefactor() *
                                 integrator_Matsubara_T0(integrand, vmin, vmax, std::abs(w / 2),
                                                               {0.}, Delta, true);
                break;
            case k2:
                integration_result += bubble_value_prefactor() * integrator_Matsubara_T0(integrand, vmin, vmax, std::abs(w / 2), {0., v, v + w, v - w}, Delta, true);
                break;
            case k3:
                integration_result += bubble_value_prefactor() * integrator_Matsubara_T0(integrand, vmin, vmax, std::abs(w / 2), {0, v, vp, w - vp, w + vp, w - v, w + v}, Delta, true);
                break;
            case k2b:
                integration_result += bubble_value_prefactor() * integrator_Matsubara_T0(integrand, vmin, vmax, std::abs(w / 2), {0, vp, vp + w, vp - w}, Delta, true);
                break;
            default:
                break;
        }
    } else {
        if constexpr(KELDYSH) {
            integration_result += bubble_value_prefactor() * integrator(integrand, vmin, vmax, -w / 2., w / 2., Delta, true);
        } else {
            const int interval_correction = signFlipCorrection_MF_int(w);
            const int W = (int) (w / 2);
            const int Nmin_sum = -POSINTRANGE - std::abs(W / 2) + interval_correction;
            const int Nmax_sum = POSINTRANGE - 1 + std::abs(W / 2);
            const freqType vmin_temp = (2 * Nmin_sum + 1.);
            const freqType vmax_temp = (2 * Nmax_sum + 1.);
            if constexpr (VECTORIZED_INTEGRATION) // (VECTORIZED_INTEGRATION and k == k3)
            {
                int Nmin_v, Nmax_v, Nmin_vp, Nmax_vp, N_vp;
                if (k == k1) {
                    Nmin_v = 0; Nmax_v = 0; Nmin_vp = 0; Nmax_vp = 0; N_vp = 1;
                }
                else if (k == k2) {
                    Nmin_v = -nFER2/2; Nmax_v = DEBUG_SYMMETRIES ? nFER2/2-1 : -1; Nmin_vp = 0; Nmax_vp = 0; N_vp = 1;
                }
                else if (k == k2b) {
                    Nmin_v = 0; Nmax_v = 0; Nmin_vp = -nFER2/2; Nmax_vp = DEBUG_SYMMETRIES ? nFER2/2-1 : -1; N_vp = nFER2;
                }
                else {
                    Nmin_v = -nFER3/2; Nmax_v = DEBUG_SYMMETRIES ? nFER3/2-1 : -1; Nmin_vp = -nFER3/2; Nmax_vp = nFER3/2-1; N_vp = nFER3;
                }
                Eigen::Matrix<Q, Eigen::Dynamic, Eigen::Dynamic> summation_result =
                        matsubarasum_vectorized<spin,channel>(integrand, Nmin_v, Nmax_v, Nmin_sum, Nmax_sum, Nmin_vp, Nmax_vp) * bubble_value_prefactor() * (2 * M_PI) * Pi.g.T;
                for (int i = Nmin_v; i <= Nmax_v; i++) {
                    for (int j = Nmin_vp; j <= Nmax_vp; j++) {
                        const freqType v_temp  = (i*2 + 1);
                        const freqType vp_temp = (j*2 + 1);
                        Integrand_class integrand_asymp(vertex1, vertex2, Pi, i0, i2, iw, w, v_temp, vp_temp, i_in, i_spin, diff);
#if ANALYTIC_TAILS
                        summation_result(-Nmin_v+i,-Nmin_vp+j) +=
                                bubble_value_prefactor() * asymp_corrections_bubble<channel,spin>(k, vertex1, vertex2, Pi.g,
                                                                                                  vmin_temp, vmax_temp, w, v_temp, vp_temp, i0, i2,
                                                                                                  i_in, diff);
#else
                        summation_result(-Nmin_v+i,-Nmin_vp+j) += bubble_value_prefactor() * M_PI * Pi.g.T *
                                                                  asymp_corrections_bubble_via_quadrature<Q>(integrand_asymp, vmin_temp, vmax_temp);
#endif
                    }
                }
                //if (k == k2) {
                //    std::cout << "summation result" << summation_result << std::endl;
                //}
                for (int i = Nmin_v; i <= Nmax_v; i++) {
                    for (int j = Nmin_vp; j <= Nmax_vp; j++) {
                        value[(-Nmin_v+i)*N_vp  + (-Nmin_vp+j)] = summation_result(-Nmin_v+i,-Nmin_vp+j);
                    }
                }
            }
            else
            {
                // if interval_correction=-1, then the integrand is symmetric_full around v=-M_PI*T
                integration_result = bubble_value_prefactor() * (2 * M_PI) * Pi.g.T *
                                     matsubarasum<Q>(integrand, Nmin_sum, Nmax_sum);
#if ANALYTIC_TAILS
                integration_result +=
                        bubble_value_prefactor() * asymp_corrections_bubble<channel,spin>(k, vertex1, vertex2, Pi.g,
                                                                                     vmin_temp, vmax_temp, w, v, vp, i0, i2,
                                                                                     i_in, diff);
#else
                integration_result += bubble_value_prefactor() * (2 * M_PI) * Pi.g.T *
                                      asymp_corrections_bubble_via_quadrature<Q>(integrand, vmin_temp, vmax_temp);
#endif
            }
        }
    }
#if not SWITCH_SUM_N_INTEGRAL
    }
#else
    //for (int i2: glb_non_zero_Keldysh_bubble)
    {
#endif
        // asymptotic corrections include spin sum
        if constexpr ((ZERO_T or KELDYSH) and false) {
            integration_result +=
                    bubble_value_prefactor() * asymp_corrections_bubble<channel>(k, vertex1, vertex2, Pi.g,
                                                                                 vmin, vmax, w, v, vp, i0, i2,
                                                                                 i_in, diff, spin);
        }
    }
    if constexpr(VECTORIZED_INTEGRATION == 1) {
        if constexpr (KELDYSH_FORMALISM) {
            // for vector-/matrix-valued result:
            if constexpr(DEBUG_SYMMETRIES or true) {
                // if DEBUG_SYMMETRIES is true, we compute and store ALL components
                for (int i = 0; i < 4; i++) {
                    for (int j = 0; j < 4; j++) {
                        value[rotate_Keldysh_matrix<channel, true>(i * 4 + j)] = integration_result(i, j);
                    }
                }
            }
            else {
                /*
                // if DEBUG_SYMMETRIES is false, we compute and store symmetry-reduced components (given in indepKeldyshComponents_Ki)
                std::vector<int> &indepKeldyshComponents = (k == k1 ? indepKeldyshComponents_K1 : (k == k3 ? indepKeldyshComponents_K3 : indepKeldyshComponents_K2));
                const int size = indepKeldyshComponents.size();
                for (int i = 0; i < size; i++) {
                    int left, right;
                    get_i0_left_right<channel>(indepKeldyshComponents[i], left, right);
                    const Q val_temp = integration_result(left, right);
                    value[i] = val_temp;
                }
                */
            }
        }
        //else { // Matsubara finite_T
        //    assert(!ZERO_T);
        //
        //
        //}
    } else {
        // for scalar result:
        value[0] = integration_result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, glb_non_zero_Keldysh_bubble(), integrator(), integrator_Matsubara_T0(), k1, k2, k2b, k3, KELDYSH, KELDYSH_FORMALISM, n_spin, nFER2, nFER3, POSINTRANGE, signFlipCorrection_MF_int(), VECTORIZED_INTEGRATION, and ZERO_T.
check_presence_of_symmetry_related_contributions()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::check_presence_of_symmetry_related_contributions () private
Definition at line 999 of file bubble_function.hpp.
{
    bool vertex1_is_bare = false;
    bool vertex2_is_bare = false;
    if ((vertex1.avertex().max_norm() < 1e-18)
        && (vertex1.pvertex().max_norm() < 1e-18)
        && (vertex1.tvertex().max_norm() < 1e-18)) {vertex1_is_bare = true;}
    if ((vertex2.avertex().max_norm() < 1e-18)
        && (vertex2.pvertex().max_norm() < 1e-18)
        && (vertex2.tvertex().max_norm() < 1e-18)) {vertex2_is_bare = true;}
    if (channel == 'a'){ // There must be a non-vanishing contribution in the t-channel for both vertices
        if (not vertex1_is_bare) assert(vertex1.tvertex().max_norm() > 1e-18);
        if (not vertex2_is_bare) assert(vertex2.tvertex().max_norm() > 1e-18);
    }
    if (channel == 't'){ // There must be a non-vanishing contribution in the a-channel for both vertices
        if (not vertex1_is_bare) assert(vertex1.avertex().max_norm() > 1e-18);
        if (not vertex2_is_bare) assert(vertex2.avertex().max_norm() > 1e-18);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
convert_external_MPI_OMP_indices_to_physical_indices_K1()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K1 (int & iK1, int & i0, int & ispin, int & iw, int & i_in, freqType & w, int i_mpi, int n_omp, int i_omp) private
Definition at line 700 of file bubble_function.hpp.
{
    iK1 = i_mpi * n_omp + i_omp;
    my_defs::K1::index_type idx;
    getMultIndex<rank_K1>(idx, iK1, dimsK1);
    i0       = (int) idx[my_defs::K1::keldysh];
    ispin    = (int) idx[my_defs::K1::spin];
    iw       = (int) idx[my_defs::K1::omega];
    i_in     = (int) idx[my_defs::K1::internal];
   //getMultIndex<4,int,int,int,int>(ispin, iw, i0, i_in, iK1, vertex1.avertex().K1.get_dims());
    if (channel == 'a') dgamma.avertex().K1.frequencies.get_freqs_w(w, iw);           // frequency acc. to frequency index
    if (channel == 'p') dgamma.pvertex().K1.frequencies.get_freqs_w(w, iw);           // frequency acc. to frequency index
    if (channel == 't') dgamma.tvertex().K1.frequencies.get_freqs_w(w, iw);           // frequency acc. to frequency index
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), my_defs::K1::internal, my_defs::K1::keldysh, my_defs::K1::omega, and my_defs::K1::spin.
convert_external_MPI_OMP_indices_to_physical_indices_K2()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K2 (int & iK2, int & i0, int & ispin, int & iw, int & iv, int & i_in, freqType & w, freqType & v, int i_mpi, int n_omp, int i_omp) private
Definition at line 721 of file bubble_function.hpp.
{
    iK2 = i_mpi * n_omp + i_omp;
    my_defs::K2::index_type idx;
    getMultIndex<rank_K2>(idx, iK2, dimsK2);
    i0       = (int) idx[my_defs::K2::keldysh];
    ispin    = (int) idx[my_defs::K2::spin];
    iw       = (int) idx[my_defs::K2::omega];
    iv       = (int) idx[my_defs::K2::nu];
    i_in     = (int) idx[my_defs::K2::internal];
    //getMultIndex<5,int,int,int,int,int>(ispin, iw, iv, i0, i_in, iK2, vertex1.avertex().K2.get_dims());
    if (channel == 'a') dgamma.avertex().K2.frequencies.get_freqs_w(w, v, iw, iv);
    if (channel == 'p') dgamma.pvertex().K2.frequencies.get_freqs_w(w, v, iw, iv);
    if (channel == 't') dgamma.tvertex().K2.frequencies.get_freqs_w(w, v, iw, iv);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), my_defs::K2::internal, my_defs::K2::keldysh, my_defs::K2::nu, my_defs::K2::omega, and my_defs::K2::spin.
convert_external_MPI_OMP_indices_to_physical_indices_K2b()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K2b (int & iK2, int & i0, int & ispin, int & iw, int & ivp, int & i_in, freqType & w, freqType & vp, int i_mpi, int n_omp, int i_omp) private
Definition at line 744 of file bubble_function.hpp.
{
    iK2 = i_mpi * n_omp + i_omp;
    my_defs::K2::index_type idx;
    getMultIndex<rank_K2>(idx, iK2, dimsK2);
    i0       = (int) idx[my_defs::K2b::keldysh];
    ispin    = (int) idx[my_defs::K2b::spin];
    iw       = (int) idx[my_defs::K2b::omega];
    ivp      = (int) idx[my_defs::K2b::nup];
    i_in     = (int) idx[my_defs::K2b::internal];
    //getMultIndex<5,int,int,int,int,int>(ispin, iw, ivp, i0, i_in, iK2, vertex1.avertex().K2b.get_dims());
    if (channel == 'a') dgamma.avertex().K2b.frequencies.get_freqs_w(w, vp, iw, ivp);
    if (channel == 'p') dgamma.pvertex().K2b.frequencies.get_freqs_w(w, vp, iw, ivp);
    if (channel == 't') dgamma.tvertex().K2b.frequencies.get_freqs_w(w, vp, iw, ivp);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), my_defs::K2b::internal, my_defs::K2b::keldysh, my_defs::K2b::nup, my_defs::K2b::omega, and my_defs::K2b::spin.
convert_external_MPI_OMP_indices_to_physical_indices_K3()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::convert_external_MPI_OMP_indices_to_physical_indices_K3 (int & iK3, int & i0, int & ispin, int & iw, int & iv, int & ivp, int & i_in, freqType & w, freqType & v, freqType & vp, int i_mpi, int n_omp, int i_omp) private
Definition at line 767 of file bubble_function.hpp.
{
    iK3 = i_mpi * n_omp + i_omp;
    my_defs::K3::index_type idx;
    getMultIndex<rank_K3>(idx, iK3, dimsK3);
    i0       = (int) idx[my_defs::K3::keldysh];
    ispin    = (int) idx[my_defs::K3::spin];
    iw       = (int) idx[my_defs::K3::omega];
    iv       = (int) idx[my_defs::K3::nu];
    ivp      = (int) idx[my_defs::K3::nup];
    i_in     = (int) idx[my_defs::K3::internal];
    //getMultIndex<6,int,int,int,int,int,int>(ispin, iw, iv, ivp, i0, i_in, iK3, vertex1.avertex().K3.get_dims());
    if (channel == 'a') dgamma.avertex().K3.frequencies.get_freqs_w(w, v, vp, iw, iv, ivp);
    if (channel == 'p') dgamma.pvertex().K3.frequencies.get_freqs_w(w, v, vp, iw, iv, ivp);
    if (channel == 't') dgamma.tvertex().K3.frequencies.get_freqs_w(w, v, vp, iw, iv, ivp);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), my_defs::K3::internal, my_defs::K3::keldysh, my_defs::K3::nu, my_defs::K3::nup, my_defs::K3::omega, and my_defs::K3::spin.
find_vmin_and_vmax()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::find_vmin_and_vmax () private
Definition at line 199 of file bubble_function.hpp.
{
    // use std::min/std::max of selfenergy/K1 frequency grids as integration limits
    vmin =-Delta * 10.; // std::min(dgamma.avertex().K1.frequencies.get_wupper_b(), Pi.g.selfenergy.Sigma.frequencies.primary_grid.w_lower);
    vmax = Delta * 10.; // std::max(dgamma.avertex().K1.frequencies.get_wupper_b(), Pi.g.selfenergy.Sigma.frequencies.primary_grid.w_upper);
    if constexpr(MAX_DIAG_CLASS >= 2){
        // use std::min/std::max of selfenergy/K1/K2 frequency grids as integration limits
        //vmin = std::min(vmin, dgamma.avertex().K2.frequencies.get_wlower_f());
        //vmax = std::max(vmax, dgamma.avertex().K2.frequencies.get_wupper_f());
    }
    if constexpr(MAX_DIAG_CLASS >= 3){
        // use std::min/std::max of selfenergy/K1/K2/K3 frequency grids as integration limits
        //vmin = std::min(vmin, dgamma.avertex().K3.frequencies.get_wlower_f());
        //vmax = std::max(vmax, dgamma.avertex().K3.frequencies.get_wupper_f());
    }
    if constexpr((!KELDYSH) && (!ZERO_T)) { // for finite-temperature Matsubara calculations
        // make sure that the limits for the Matsubara sum are fermionic
        Nmin = - POSINTRANGE;
        Nmax = - Nmin - 1;
        vmin = (Nmin*2+1)*(M_PI*Pi.g.T);
        vmax = (Nmax*2+1)*(M_PI*Pi.g.T);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, MAX_DIAG_CLASS, POSINTRANGE, and ZERO_T.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
get_Matsubara_integration_intervals()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_Matsubara_integration_intervals (size_t & num_intervals, vec< vec< freqType > > & intervals, freqType w) private
Definition at line 972 of file bubble_function.hpp.
{
    if( -std::abs(w/2)+inter_tol < std::abs(w/2)-inter_tol){
        intervals = {{vmin, -std::abs(w/2)}, {-std::abs(w/2), std::abs(w/2)}, {std::abs(w/2), vmax}};
        num_intervals = 3;
    }
    else {
        intervals = {{vmin, -std::abs(w/2)}, {std::abs(w/2), vmax}};
        num_intervals = 2;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and inter_tol.
get_trafo_K1()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K1 (int i0, freqType w) private
Definition at line 791 of file bubble_function.hpp.
{
    int trafo = 1;
    if constexpr(DEBUG_SYMMETRIES) {
        trafo = 0; // compute integrals for all frequency components
    }
    else {
        if constexpr(VECTORIZED_INTEGRATION) {
            if constexpr (KELDYSH_FORMALISM) {
                // Make sure that the frequency point does not belong to the symmetry-reduced sector for all relevant Keldysh components
                // otherwise we have to compute that point
                int sign_w = sign_index<freqType>(w );
                const int number_of_indep_Components = dgamma.get_rvertex(channel).K1.get_dims()[my_defs::K1::keldysh];
                if (dgamma.get_rvertex(channel).freq_transformations.K1[sign_w] == 0) trafo = 0;
                /*
                for (int i0_temp = 0; i0_temp < number_of_indep_Components; i0_temp++) {
                    if (dgamma.get_rvertex(channel).freq_transformations.K1[i0_temp][sign_w] == 0) trafo = 0;
                }
                 */
            }
            else { // Matsubara finite T
                int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
                if (sign_w == 0) trafo = 0;
            }
        }
        else {
            int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
            trafo = dgamma.get_rvertex(channel).freq_transformations.K1[i0][sign_w];
#if CONTOUR_BASIS == 1 and ZERO_TEMP and USE_FDT
            if (is_zero_due_to_FDTs<k1>(i0, w, 0, 0, channel)) trafo = -1; // components zero according to FDTs
#endif // CONTOUR_BASIS
        } // VECTORIZED_INTEGRATION
    } // DEBUG_SYMMETRIES
    return trafo;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, my_defs::K1::keldysh, KELDYSH_FORMALISM, and VECTORIZED_INTEGRATION.
get_trafo_K2()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K2 (int i0, freqType w, freqType v) private
Definition at line 833 of file bubble_function.hpp.
{
    int trafo = 1;
    if constexpr (DEBUG_SYMMETRIES) {
        trafo = 0; // compute integrals for all frequency components
        if (!KELDYSH and !ZERO_T and -v + signFlipCorrection_MF(w) * 0.5 < vertex1.avertex().K2.frequencies.get_wlower_f()) {
            trafo = -1;
        }
    }
    else {
        if constexpr (VECTORIZED_INTEGRATION) {
            if constexpr (KELDYSH_FORMALISM) {
                // Make sure that the frequency point does not belong to the symmetry-reduced sector for any relevant Keldysh component
                // otherwise we have to compute that point via quadrature
                int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
                int sign_v = sign_index<freqType>(v ); // safety to ensure that w=0 gets sign_w=-1
                if (dgamma.get_rvertex(channel).freq_transformations.K2[sign_w * 2 + sign_v] == 0) trafo = 0;
                /*
                const int number_of_indep_Components = dgamma.get_rvertex(channel).K2.get_dims()[my_defs::K2::keldysh];
                for (int i0_temp = 0; i0_temp < number_of_indep_Components; i0_temp++) {
                    if (dgamma.get_rvertex(channel).freq_transformations.K2[i0_temp][sign_w * 2 + sign_v] == 0) trafo = 0;
                }
                 */
            }
            else {// Matsubara finite T
                int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
                if (sign_w == 0) trafo = 0;
            }
        }
        else{
            int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
            int sign_v = sign_index<freqType>(v ); // safety to ensure that w=0 gets sign_w=-1
            trafo = dgamma.get_rvertex(channel).freq_transformations.K2[i0][sign_w*2 + sign_v];
        if (!KELDYSH and !ZERO_T and -v + signFlipCorrection_MF(w)*0.5 < vertex1.avertex().K2.frequencies.get_wlower_f()) {
            trafo = -1;
        }
    #if USE_FDT
        if (EQUILIBRIUM) {
    #if CONTOUR_BASIS != 1
        switch (channel) {
            case 'a':
                if ((i0 == 0 or i0 == 2 or i0 == 3) and abs(w)>Pi.g.T*26.) trafo = -1; // components can be determined via FDTs, no need to compute it via integration
                break;
            case 'p':
                if ((i0 == 0 or i0 == 1 or i0 == 3) and abs(w)>Pi.g.T*26.) trafo = -1; // components can be determined via FDTs, no need to compute it via integration
                break;
            case 't':
                if ((i0 == 0 or i0 == 2 or i0 == 3) and abs(w)>Pi.g.T*26.) trafo = -1; // components can be determined via FDTs, no need to compute it via integration
                break;
            default:
                break;
        }
    #else
    #if ZERO_TEMP and USE_FDT
        if (is_zero_due_to_FDTs<k2>(i0, w, v, 0, channel)) trafo = -1; // components zero according to FDTs
    #endif //ZERO_TEMP
    #endif // CONTOUR_BASIS
        }
    #endif // EQUILIBRIUM...
        } // VECTORIZED_INTEGRATION
    } // DEBUG_SYMMETRIES
    return trafo;
}
References abs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, EQUILIBRIUM, KELDYSH, KELDYSH_FORMALISM, signFlipCorrection_MF(), VECTORIZED_INTEGRATION, and ZERO_T.
get_trafo_K3()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_trafo_K3 (int i0, freqType w, freqType v, freqType vp) private
Definition at line 901 of file bubble_function.hpp.
{
    int trafo = 1;
    if constexpr(DEBUG_SYMMETRIES) {
        trafo = 0; // compute integrals for all frequency components
        if (!KELDYSH and !ZERO_T and
            (-v + signFlipCorrection_MF(w) * 0.5 < vertex1.avertex().K3.frequencies.get_wlower_f() or
             -vp + signFlipCorrection_MF(w) * 0.5 < vertex1.avertex().K3.frequencies.get_wlower_f())) {
            trafo = -1;
        }
    }
    else {
        if constexpr(VECTORIZED_INTEGRATION) {
            if constexpr (KELDYSH_FORMALISM) {
                // Make sure that the frequency point does not belong to the symmetry-reduced sector for all relevant Keldysh components
                // otherwise we have to compute that point
                int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
                int sign_f = sign_index<freqType>(v + vp );
                int sign_fp = sign_index<freqType>(v - vp );
                if (dgamma.get_rvertex(channel).freq_transformations.K3[sign_w * 4 + sign_f * 2 + sign_fp] == 0) trafo = 0;
                /*
                const int number_of_indep_Components = dgamma.get_rvertex(channel).K3.get_dims()[my_defs::K3::keldysh];
                for (int i0_temp = 0; i0_temp < number_of_indep_Components; i0_temp++) {
                    if (dgamma.get_rvertex(channel).freq_transformations.K3[i0_temp][sign_w * 4 + sign_f * 2 + sign_fp] ==
                        0)
                        trafo = 0;
                }
                 */
            }
            else {// Matsubara finite T
                int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
                if (sign_w == 0) trafo = 0;
            }
        }
        else {
            int sign_w = sign_index<freqType>(w ); // safety to ensure that w=0 gets sign_w=-1
            int sign_f = sign_index<freqType>(v + vp );
            int sign_fp= sign_index<freqType>(v - vp );
            trafo = dgamma.get_rvertex(channel).freq_transformations.K3[i0][sign_w * 4 + sign_f * 2 + sign_fp];
            if (!KELDYSH and !ZERO_T and (-v + signFlipCorrection_MF(w)*0.5 < vertex1.avertex().K3.frequencies.get_wlower_f() or -vp + signFlipCorrection_MF(w)*0.5 < vertex1.avertex().K3.frequencies.get_wlower_f())) {
                trafo = -1;
                //std::cout << "omitted frequencies: " << v << "\t" << vp << std::endl;
                //std::cout << "with limits " << vertex1.avertex().K3.frequencies.get_wlower_f() << std::endl;
            }
#if USE_FDT
            if (EQUILIBRIUM) {
#if CONTOUR_BASIS != 1
                if (i0 == 0 or i0 == 1) trafo = -1; // components can be determined via FDTs, no need to compute it via integration
#else
#if ZERO_TEMP
                if (is_zero_due_to_FDTs<k3>(i0, w, v, vp, channel)) trafo = -1; // components zero according to FDTs
#endif //ZERO_TEMP
#endif // CONTOUR_BASIS
            }
#endif //EQUILIBRIUM...
        } // VECTORIZED_INTEGRATION
    } // DEBUG_SYMMETRIES
    return trafo;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DEBUG_SYMMETRIES, EQUILIBRIUM, KELDYSH, KELDYSH_FORMALISM, signFlipCorrection_MF(), VECTORIZED_INTEGRATION, and ZERO_T.
get_value() [1/2]
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > template<K_class diag_class> auto BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_value (const int i_mpi, const int i_omp, const int n_omp, const int n_vectorization) -> value_type
Definition at line 328 of file bubble_function.hpp.
{
    value_type value(n_vectorization);
    int iK1, iK2, i0, ispin, iw, iv, ivp, i_in;
    freqType w, v, vp;
    int trafo;
    switch (diag_class) {
        case k1:
            convert_external_MPI_OMP_indices_to_physical_indices_K1(iK1, i0, ispin,iw, i_in, w,
                                                                    i_mpi, n_omp, i_omp);
            trafo = get_trafo_K1(i0, w);
            if (trafo == 0) {
                if (ispin == 0 or n_spin == 1)  calculate_value<diag_class,0>(value, i0, i_in, 0, w, 0, 0);
                else                            calculate_value<diag_class,1>(value, i0, i_in, 0, w, 0, 0);
            }
            break;
        case k2:
            convert_external_MPI_OMP_indices_to_physical_indices_K2(iK2, i0, ispin, iw, iv, i_in, w, v,
                                                                    i_mpi, n_omp, i_omp);
            trafo = get_trafo_K2(i0, w, v);
            if (trafo == 0) {
                if (ispin == 0 or n_spin == 1) calculate_value<diag_class,0>(value, i0, i_in, 0, w, v, 0);
                else                           calculate_value<diag_class,1>(value, i0, i_in, 0, w, v, 0);}
            break;
#if DEBUG_SYMMETRIES
        case k2b:
            convert_external_MPI_OMP_indices_to_physical_indices_K2b(iK2, i0, ispin, iw, ivp, i_in, w, vp,
                                                                    i_mpi, n_omp, i_omp);
            trafo = 0; // compute integrals for all frequency components
            if (!KELDYSH and !ZERO_T and -vp + signFlipCorrection_MF(w)*0.5 < vertex1.avertex().K2b.frequencies.get_wlower_f()) {
                trafo = -1;
            }
            if (trafo == 0) {
                if (ispin == 0 or n_spin == 1) calculate_value<diag_class,0>(value, i0, i_in, 0, w, 0, vp);
                else                           calculate_value<diag_class,1>(value, i0, i_in, 0, w, 0, vp);
            }
            break;
#endif
        case k3:
            convert_external_MPI_OMP_indices_to_physical_indices_K3(iK2, i0, ispin, iw, iv, ivp, i_in, w, v, vp,
                                                                    i_mpi, n_omp, i_omp);
            trafo = get_trafo_K3(i0, w, v, vp);
            if (trafo == 0) {
                if (ispin == 0 or n_spin == 1) calculate_value<diag_class,0>(value, i0, i_in, channel=='a' ? iw : (channel=='p' ? iv : ivp), w, v, vp);  // for 2D interpolation of K3 we need to know the index of the constant bosonic frequency w_r (r = channel of the bubble)
                else                           calculate_value<diag_class,1>(value, i0, i_in, channel=='a' ? iw : (channel=='p' ? iv : ivp), w, v, vp);
            }
            break;
        default:;
    }
    return value;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2, k2b, k3, KELDYSH, n_spin, signFlipCorrection_MF(), and ZERO_T.
get_value() [2/2]
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > template<K_class diag_class> value_type BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::get_value (int i_mpi, int i_omp, int n_omp, int n_vectorization) private
perform_computation()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::perform_computation ()
Definition at line 227 of file bubble_function.hpp.
{
    double t_start = utils::get_time();
    if constexpr(MAX_DIAG_CLASS >= 0) {
        if (tobecomputed[0]) {
            calculate_bubble_function<k1>();
            tK1 = utils::get_time() - t_start;
            //utils::print("K1", channel, " done, ");
            //utils::get_time(t_start);
        }
    }
    if constexpr(MAX_DIAG_CLASS >= 2) {
        if (tobecomputed[1]) {
            t_start = utils::get_time();
            calculate_bubble_function<k2>();
            tK2 = utils::get_time() - t_start;
            //utils::print("K2", channel, " done, ");
            //utils::get_time(t_start);
#if DEBUG_SYMMETRIES
            t_start = utils::get_time();
            calculate_bubble_function<k2b>();
            tK2 = utils::get_time() - t_start;
            //utils::print("K2b", channel, " done, ");
            //utils::get_time(t_start);
#endif
        }
    }
    if constexpr(MAX_DIAG_CLASS >= 3) {
        if (tobecomputed[2]) {
            t_start = utils::get_time();
            calculate_bubble_function<k3>();
            tK3 = utils::get_time() - t_start;
            //utils::print("K3", channel, " done, ");
            //utils::get_time(t_start);
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), utils::get_time(), and MAX_DIAG_CLASS.
set_channel_specific_freq_ranges_and_prefactor()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::set_channel_specific_freq_ranges_and_prefactor () private
Definition at line 183 of file bubble_function.hpp.
{
// set channel-specific frequency ranges and prefactor (1, 1, -1 for a, p, t) for sum over spins.
    nw1_w = dgamma.get_rvertex(channel).K1.get_dims()[my_defs::K1::omega];
    nw2_w = dgamma.get_rvertex(channel).K2.get_dims()[my_defs::K2::omega];
    nw2_v = dgamma.get_rvertex(channel).K2.get_dims()[my_defs::K2::nu];
    nw3_w = dgamma.get_rvertex(channel).K3.get_dims()[my_defs::K3::omega];
    nw3_v = dgamma.get_rvertex(channel).K3.get_dims()[my_defs::K3::nu];
    nw3_v_p=dgamma.get_rvertex(channel).K3.get_dims()[my_defs::K3::nup];
    prefactor = channel == 't' ? -1. : 1.;
}
References my_defs::K2::nu, my_defs::K3::nu, my_defs::K3::nup, my_defs::K1::omega, my_defs::K2::omega, and my_defs::K3::omega.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
set_external_arguments_for_parallelization()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::set_external_arguments_for_parallelization (size_t & n_mpi, size_t & n_omp, size_t & n_vectorization, K_class diag_class) private
The computation of the vertex components of dgamma.Ki (i = 1, 2, 2', 3) can be parallelized parallelization is achieved via... ... MPI --> distribute over multiple nodes (n_mpi = maximal number of MPI processes) ... OMP --> distribute over multiple threads within the same node (n_omp = number of ... vectorization --> use efficient matrix routines If vectorization is used (*this)->get_value() returns a vector with the components over which we vectorize and in (*this)->calculate_bubble_function() we need to loop over the remaining dimensions (these are given in dimsK1, dimsK2 and dimsK3)
Definition at line 658 of file bubble_function.hpp.
{
    const size_t nK_K1 = dimsK1[my_defs::K1::keldysh];
    const size_t nK_K2 = dimsK2[my_defs::K2::keldysh];
    const size_t nK_K3 = dimsK3[my_defs::K3::keldysh];
    switch (diag_class) {
        case k1:
            // set external arguments for MPI-parallelization (# of tasks distributed via MPI)
            n_mpi = number_of_nodes;
            n_vectorization = n_vectorization_K1;
            // set external arguments for OMP-parallelization (# of tasks per MPI-task distributed via OMP)
            // below formula performs integer division with rounding up
            n_omp = (dims_flat_K1 + n_mpi - 1) / n_mpi;
            break;
        case k2:
        case k2b:
            n_mpi = number_of_nodes;        // set external arguments for MPI-parallelization (# of tasks distributed via MPI)
            n_vectorization = n_vectorization_K2;
            n_omp = (dims_flat_K2 + n_mpi - 1) / n_mpi;
            break;
        case k3:
            n_mpi = number_of_nodes;        // set external arguments for MPI-parallelization (# of tasks distributed via MPI)
            n_vectorization = n_vectorization_K3;
            n_omp = (dims_flat_K3 + n_mpi - 1) / n_mpi;
            break;
        default: ;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2, k2b, k3, my_defs::K1::keldysh, my_defs::K2::keldysh, and my_defs::K3::keldysh.
write_out_results()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results (const vec< Q > & Ordered_result, K_class diag_class) private
Definition at line 578 of file bubble_function.hpp.
{
    switch (diag_class) {
        case k1:
            write_out_results_K1(Ordered_result);
            break;
        case k2:
            write_out_results_K2(Ordered_result);
            break;
#if DEBUG_SYMMETRIES
        case k2b:
            write_out_results_K2b(Ordered_result);
            break;
#endif
        case k3:
            write_out_results_K3(Ordered_result);
            break;
        default: ;
    }
    dgamma.set_initializedInterpol(false);      // above initialization of the Interpolator is with the symmetry-reduced sector only (rest = zero)
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), k1, k2, k2b, and k3.
write_out_results_K1()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K1 (const vec< Q > & K1_ordered_result) private
Definition at line 603 of file bubble_function.hpp.
{
    dgamma.get_rvertex(channel).K1.set_vec(K1_ordered_result);
    if constexpr(not DEBUG_SYMMETRIES) {
        dgamma.initializeInterpol();     // initialize Interpolator with the symmetry-reduced sector of the vertex to retrieve all remaining entries
        dgamma.get_rvertex(channel).enforce_freqsymmetriesK1(dgamma.get_rvertex(channel));
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and DEBUG_SYMMETRIES.
write_out_results_K2()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K2 (const vec< Q > & K2_ordered_result) private
Definition at line 616 of file bubble_function.hpp.
{
    //assert( K2_ordered_result.size() == nK_K2*n_spin*nBOS2*nFER2*n_in);
    dgamma.get_rvertex(channel).K2.set_vec(K2_ordered_result);
    if constexpr(not DEBUG_SYMMETRIES) {
        dgamma.initializeInterpol();     // initialize Interpolator with the symmetry-reduced sector of the vertex to retrieve all remaining entries
        dgamma.get_rvertex(channel).enforce_freqsymmetriesK2(dgamma.get_rvertex(channel));
    }
#if defined(EQUILIBRIUM) and USE_FDT
    compute_components_through_FDTs(dgamma.half1(), dgamma.half1(), dgamma.half1(), channel);
#endif
}
References compute_components_through_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and DEBUG_SYMMETRIES.
write_out_results_K2b()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K2b (const vec< Q > & K2b_ordered_result) private
Definition at line 633 of file bubble_function.hpp.
{
    //assert( K2b_ordered_result.size() == nK_K2*n_spin*nBOS2*nFER2*n_in);
    dgamma.get_rvertex(channel).K2b.set_vec(K2b_ordered_result);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
write_out_results_K3()
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::write_out_results_K3 (const vec< Q > & K3_ordered_result) private
Definition at line 643 of file bubble_function.hpp.
{
    dgamma.get_rvertex(channel).K3.set_vec(K3_ordered_result);
    if constexpr(not DEBUG_SYMMETRIES) {
        dgamma.initializeInterpol();     // initialize Interpolator with the symmetry-reduced sector of the vertex to retrieve all remaining entries
        dgamma.get_rvertex(channel).enforce_freqsymmetriesK3(dgamma.get_rvertex(channel));
    }
#if defined(EQUILIBRIUM) and USE_FDT
    compute_components_through_FDTs(dgamma.half1(), dgamma.half1(), dgamma.half1(), channel);
#endif
}
References compute_components_through_FDTs(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and DEBUG_SYMMETRIES.
Member Data Documentation
Delta
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > const double BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::Delta = (Pi.g.Lambda + Pi.g.Gamma) / 2. private
Definition at line 43 of file bubble_function.hpp.
dgamma
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > vertexType_result& BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dgamma private
Definition at line 35 of file bubble_function.hpp.
diff
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > const bool BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::diff = Pi.diff private
Definition at line 41 of file bubble_function.hpp.
dims_flat_K1
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dims_flat_K1 private
Definition at line 55 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
dims_flat_K2
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dims_flat_K2 private
Definition at line 55 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
dims_flat_K3
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dims_flat_K3 private
Definition at line 55 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
dimsK1
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > std::array<std::size_t,my_defs::K1::rank> BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dimsK1 private
Definition at line 52 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
dimsK2
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > std::array<std::size_t,my_defs::K2::rank> BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dimsK2 private
Definition at line 53 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
dimsK3
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > std::array<std::size_t,my_defs::K3::rank> BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::dimsK3 private
Definition at line 54 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
mpi_rank
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::mpi_rank = mpi_world_rank() private
Definition at line 51 of file bubble_function.hpp.
mpi_size
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::mpi_size = mpi_world_size() private
Definition at line 50 of file bubble_function.hpp.
n_vectorization_K1
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::n_vectorization_K1 private
Definition at line 56 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
n_vectorization_K2
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::n_vectorization_K2 private
Definition at line 56 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
n_vectorization_K3
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::n_vectorization_K3 private
Definition at line 56 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
Nmax
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::Nmax private
Definition at line 62 of file bubble_function.hpp.
Nmin
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::Nmin private
Definition at line 62 of file bubble_function.hpp.
number_of_nodes
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > size_t BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::number_of_nodes private
Definition at line 49 of file bubble_function.hpp.
nw1_w
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::nw1_w = 0 private
Definition at line 46 of file bubble_function.hpp.
nw2_v
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::nw2_v = 0 private
Definition at line 46 of file bubble_function.hpp.
nw2_w
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::nw2_w = 0 private
Definition at line 46 of file bubble_function.hpp.
nw3_v
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::nw3_v = 0 private
Definition at line 46 of file bubble_function.hpp.
nw3_v_p
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::nw3_v_p = 0 private
Definition at line 46 of file bubble_function.hpp.
nw3_w
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > int BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::nw3_w = 0 private
Definition at line 46 of file bubble_function.hpp.
Pi
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > const Bubble_Object& BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::Pi private
THIS IS A COPY; needed for symmetry-expansion.
Definition at line 40 of file bubble_function.hpp.
prefactor
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > Q BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::prefactor = 1. private
Definition at line 47 of file bubble_function.hpp.
store_integrand_for_PT
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > const bool BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::store_integrand_for_PT = false private
Definition at line 104 of file bubble_function.hpp.
tK1
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > double BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::tK1 = 0 private
Definition at line 64 of file bubble_function.hpp.
tK2
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > double BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::tK2 = 0 private
Definition at line 64 of file bubble_function.hpp.
tK3
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > double BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::tK3 = 0 private
Definition at line 64 of file bubble_function.hpp.
tobecomputed
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > std::array<bool,3> BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::tobecomputed private
Definition at line 66 of file bubble_function.hpp.
vertex1
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > const vertexType_left BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::vertex1 private
Definition at line 37 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
vertex2
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > const vertexType_right BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::vertex2 private
THIS IS A COPY; needed for symmetry-expansion.
Definition at line 38 of file bubble_function.hpp.
Referenced by BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::BubbleFunctionCalculator().
vmax
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > freqType BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::vmax = 0 private
Definition at line 61 of file bubble_function.hpp.
vmin
template<char channel, typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > freqType BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >::vmin = 0 private
Definition at line 61 of file bubble_function.hpp.
The documentation for this class was generated from the following file:
bubble_function.hpp