SIAM-Keldysh-mfRG: multidimensional::multiarray< T, depth > Class Template Reference
multidimensional::multiarray< T, depth > Class Template Reference
#include <multiarray.hpp>
Public Types
using value_type = T
using size_type = std::size_t
using difference_type = std::ptrdiff_t
using reference = value_type &
using const_reference = const value_type &
using pointer = value_type *
using const_pointer = const value_type *
using index_type = std::array<my_index_t, depth>
using dimensions_type = std::array<size_type, depth>
using buffer_type = Eigen::Array<T, Eigen::Dynamic, 1>
using iterator = pointer
=== iterators ===
using const_iterator = const_pointer
Public Member Functions
constexpr multiarray () noexcept
=== constructors ===
multiarray (dimensions_type length, const T &value=T())
multiarray (dimensions_type length, const buffer_type &elements)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, value_type > &&!std::is_same_v< container, buffer_type >, bool > = true>
multiarray (dimensions_type length, const container &elements)
multiarray (dimensions_type length, buffer_type &&elements)
multiarray (const multiarray< T, depth > &)=default
Move & copy constructors and assignment operators.
multiarray (multiarray< T, depth > &&)=default
multiarray< T, depth > & operator= (const multiarray< T, depth > &)=default
multiarray< T, depth > & operator= (multiarray< T, depth > &&)=default
constexpr iterator begin () noexcept
constexpr iterator end () noexcept
constexpr const_iterator begin () const noexcept
constexpr const_iterator end () const noexcept
constexpr const_iterator cbegin () const noexcept
constexpr const_iterator cend () const noexcept
constexpr auto range (const index_type &start, const index_type &end)
constexpr auto range (const index_type &start, const index_type &end) const
constexpr auto eigen_segment (const index_type &start, const index_type &end)
return segment including start and end
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
bool is_same_length (const multiarray< value_type, depth > &other) const
template<std::size_t pos_first_freq_index, std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==depth) and(are_all_integral< size_t, Types... >::value) and(are_all_unsigned< size_t, Types... >::value) and(pos_first_freq_index+freqrank< depth), bool > = true>
constexpr auto at_vectorized (Types &...i) const -> Eigen::Matrix< T, vecsize, 1 >
template<std::size_t vecsize>
constexpr auto at_vectorized (const index_type &idx) const -> Eigen::Matrix< T, vecsize, 1 >
template<std::size_t vecsize>
constexpr auto at_vectorized (const std::size_t flat_idx) const -> Eigen::Matrix< T, vecsize, 1 >
template<std::size_t vecsize>
void set_vectorized (const Eigen::Matrix< T, vecsize, 1 > &value, const index_type &idx)
template<my_index_t num_first_dims>
size_t get_flatindex_ini (const index_type &index) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
auto get_values (const index_type &index) const -> Eigen::Matrix< T, vecsize, numberFrequencyDims==1 ? sample_size :(numberFrequencyDims==2 ? sample_size *sample_size :sample_size *sample_size *sample_size)>
T & at (const index_type &index)
=== public member functions ===
const T & at (const index_type &index) const
template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true>
T & at (const Types &...i)
template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true>
const T & at (const Types &...i) const
template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true>
T & operator() (const Types &...i)
template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true>
const T & operator() (const Types &...i) const
T * data () noexcept
const T * data () const noexcept
buffer_type get_elements () const
T & flat_at (size_type i)
flat access
const T & flat_at (size_type i) const
T & operator[] (size_type i)
const T & operator[] (size_type i) const
template<typename Q , typename R >
multiarray< T, depth > & elementwise_map_assign (Q op, const multiarray< R, depth > &rhs)
elementwise arithmetics-assignment op's
multiarray< T, depth > & operator+= (const multiarray< T, depth > &rhs)
multiarray< T, depth > & operator-= (const multiarray< T, depth > &rhs)
multiarray< T, depth > & operator*= (const multiarray< T, depth > &rhs)
multiarray< T, depth > & operator/= (const multiarray< T, depth > &rhs)
template<typename R >
multiarray< T, depth > & operator+= (const multiarray< R, depth > &rhs)
template<typename R >
multiarray< T, depth > & operator-= (const multiarray< R, depth > &rhs)
template<typename R >
multiarray< T, depth > & operator*= (const multiarray< R, depth > &rhs)
template<typename R >
multiarray< T, depth > & operator/= (const multiarray< R, depth > &rhs)
template<typename Q , typename R >
multiarray< T, depth > & scalar_map_assign (Q op, const R &rhs) noexcept(noexcept(op(T(), R())))
scalar arithmetic assignment
template<typename R >
multiarray< T, depth > & operator+= (const R &rhs) noexcept(noexcept(T()+R()))
template<typename R >
multiarray< T, depth > & operator-= (const R &rhs) noexcept(noexcept(T() - R()))
template<typename R >
multiarray< T, depth > & operator*= (const R &rhs) noexcept(noexcept(T() *R()))
template<typename R >
multiarray< T, depth > & operator/= (const R &rhs) noexcept(noexcept(T() - R()))
multiarray< T, depth > abs () const
other function related to arithmetic
T max () const
T min () const
T maxabs () const
T minabs () const
double max_norm () const
template<int p>
double lpNorm () const
bool isfinite () const
size_type size () const noexcept
constexpr const dimensions_type & length () const noexcept
constexpr const dimensions_type & length_cumul () const noexcept
Static Public Member Functions
static constexpr size_type get_depth () noexcept
Public Attributes
buffer_type elements
Private Member Functions
dimensions_type get_cumul_length (const dimensions_type &length) const
size_type _flat_size () const noexcept
void check_size () const
size_type flat_index (const index_type &index) const noexcept
bool check_bounds (const index_type &index) const noexcept
bool check_bounds_end (const index_type &index) const noexcept
Private Attributes
dimensions_type m_length
dimensions_type m_length_cumulative = get_cumul_length(m_length)
Friends
void swap (multiarray< value_type, depth > &lhs, multiarray< value_type, depth > &rhs) noexcept
bool operator== (const multiarray< T, depth > &, const multiarray< T, depth > &)
non-member op's
Detailed Description
template<typename T, size_t depth>
class multidimensional::multiarray< T, depth >
Definition at line 40 of file multiarray.hpp.
Member Typedef Documentation
buffer_type
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::buffer_type = Eigen::Array<T, Eigen::Dynamic, 1>
Definition at line 74 of file multiarray.hpp.
const_iterator
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::const_iterator = const_pointer
Definition at line 142 of file multiarray.hpp.
const_pointer
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::const_pointer = const value_type *
Definition at line 50 of file multiarray.hpp.
const_reference
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::const_reference = const value_type &
Definition at line 48 of file multiarray.hpp.
difference_type
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::difference_type = std::ptrdiff_t
Definition at line 46 of file multiarray.hpp.
dimensions_type
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::dimensions_type = std::array<size_type, depth>
Definition at line 52 of file multiarray.hpp.
index_type
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::index_type = std::array<my_index_t, depth>
Definition at line 51 of file multiarray.hpp.
iterator
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::iterator = pointer
=== iterators ===
Definition at line 141 of file multiarray.hpp.
pointer
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::pointer = value_type *
Definition at line 49 of file multiarray.hpp.
reference
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::reference = value_type &
Definition at line 47 of file multiarray.hpp.
size_type
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::size_type = std::size_t
Definition at line 45 of file multiarray.hpp.
value_type
template<typename T , size_t depth> using multidimensional::multiarray< T, depth >::value_type = T
Definition at line 44 of file multiarray.hpp.
Constructor & Destructor Documentation
multiarray() [1/7]
template<typename T , size_t depth> constexpr multidimensional::multiarray< T, depth >::multiarray () inline constexpr noexcept
=== constructors ===
Definition at line 88 of file multiarray.hpp.
                : m_length{}, elements()
        {
        }
multiarray() [2/7]
template<typename T , size_t depth> multidimensional::multiarray< T, depth >::multiarray (dimensions_type length, const T & value = T()) inline explicit
Definition at line 93 of file multiarray.hpp.
                : m_length(std::move(length)), elements(_flat_size())
        {
            elements.setConstant(value);
        }
References multidimensional::multiarray< T, depth >::elements.
multiarray() [3/7]
template<typename T , size_t depth> multidimensional::multiarray< T, depth >::multiarray (dimensions_type length, const buffer_type & elements) inline
Definition at line 99 of file multiarray.hpp.
                : m_length(std::move(length)), elements(elements)
        {
            check_size();
        }
References multidimensional::multiarray< T, depth >::check_size().
multiarray() [4/7]
template<typename T , size_t depth> template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, value_type > &&!std::is_same_v< container, buffer_type >, bool > = true> multidimensional::multiarray< T, depth >::multiarray (dimensions_type length, const container & elements) inline
Definition at line 111 of file multiarray.hpp.
                : m_length(std::move(length)),
                  elements(Eigen::Map<const buffer_type>(elements.data(), elements.size()))
        {
            if ((size_t)elements.size() != this->size())
            {
                throw std::invalid_argument(
                        "Incosistent size of length description and data in "
                        "multiarray::multiarray.");
            }
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
multiarray() [5/7]
template<typename T , size_t depth> multidimensional::multiarray< T, depth >::multiarray (dimensions_type length, buffer_type && elements) inline
Definition at line 123 of file multiarray.hpp.
                : m_length(std::move(length)), elements(std::move(elements))
        {
            check_size();
        }
References multidimensional::multiarray< T, depth >::check_size().
multiarray() [6/7]
template<typename T , size_t depth> multidimensional::multiarray< T, depth >::multiarray (const multiarray< T, depth > &) default
Move & copy constructors and assignment operators.
multiarray() [7/7]
template<typename T , size_t depth> multidimensional::multiarray< T, depth >::multiarray (multiarray< T, depth > &&) default
Member Function Documentation
_flat_size()
template<typename T , size_t depth> size_type multidimensional::multiarray< T, depth >::_flat_size () const inline private noexcept
Definition at line 582 of file multiarray.hpp.
        {
            size_type res = 1;
            for (auto &l : m_length)
            {
                res *= l;
            }
            return res;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::m_length.
Referenced by multidimensional::multiarray< T, depth >::check_size().
abs()
template<typename T , size_t depth> multiarray< T, depth > multidimensional::multiarray< T, depth >::abs () const inline
other function related to arithmetic
Definition at line 510 of file multiarray.hpp.
{
            return transform([] (const T& x) {return static_cast<T>(std::abs(x));}, *this);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::transform().
at() [1/4]
template<typename T , size_t depth> T & multidimensional::multiarray< T, depth >::at (const index_type & index)
=== public member functions ===
random element access
Definition at line 656 of file multiarray.hpp.
    {
        if (check_bounds(index))
        {
            return flat_at(flat_index(index));
        }
        else
        {
            assert(false);
            throw std::out_of_range("Attempted to access multiarray element at invalid index.");
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by dataContainerBase< Q, rank >::at(), multidimensional::multiarray< T, depth >::at(), multidimensional::multiarray< T, depth >::at(), multidimensional::multiarray< T, depth >::operator()(), multidimensional::multiarray< T, depth >::operator()(), dataContainerBase< Q, rank >::setvert(), dataContainerBase< Q, rank >::setvert(), and dataContainerBase< Q, rank >::val().
at() [2/4]
template<typename T , size_t depth> const T & multidimensional::multiarray< T, depth >::at (const index_type & index) const
Definition at line 670 of file multiarray.hpp.
    {
        if (check_bounds(index))
        {
            return flat_at(flat_index(index));
        }
        else
        {
            assert(false);
            throw std::out_of_range("Attempted to access multiarray element at invalid index.");
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
at() [3/4]
template<typename T , size_t depth> template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true> T & multidimensional::multiarray< T, depth >::at (const Types &... i) inline
Definition at line 324 of file multiarray.hpp.
        {
            return at(index_type({static_cast<size_type>(i)...}));
        }
References multidimensional::multiarray< T, depth >::at(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
at() [4/4]
template<typename T , size_t depth> template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true> const T & multidimensional::multiarray< T, depth >::at (const Types &... i) const inline
Definition at line 330 of file multiarray.hpp.
        {
            return at(index_type({static_cast<size_type>(i)...}));
        }
References multidimensional::multiarray< T, depth >::at(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
at_vectorized() [1/3]
template<typename T , size_t depth> template<std::size_t vecsize> constexpr auto multidimensional::multiarray< T, depth >::at_vectorized (const index_type & idx) const -> Eigen::Matrix<T,vecsize,1> inline constexpr
Definition at line 240 of file multiarray.hpp.
{
#ifndef NDEBUG
            for (size_t it = 0; it < depth; it++) {
                assert(idx[it] < m_length[it]);
            }
#endif
            const auto flat_start = flat_index(idx);
            return elements.template segment<vecsize>(flat_start);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, multidimensional::multiarray< T, depth >::flat_index(), and multidimensional::multiarray< T, depth >::m_length.
at_vectorized() [2/3]
template<typename T , size_t depth> template<std::size_t vecsize> constexpr auto multidimensional::multiarray< T, depth >::at_vectorized (const std::size_t flat_idx) const -> Eigen::Matrix<T,vecsize,1> inline constexpr
Definition at line 250 of file multiarray.hpp.
{
            assert(flat_idx+vecsize <= (size_t)elements.size());
            return elements.template segment<vecsize>(flat_idx);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
at_vectorized() [3/3]
template<typename T , size_t depth> template<std::size_t pos_first_freq_index, std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==depth) and(are_all_integral< size_t, Types... >::value) and(are_all_unsigned< size_t, Types... >::value) and(pos_first_freq_index+freqrank< depth), bool > = true> constexpr auto multidimensional::multiarray< T, depth >::at_vectorized (Types &... i) const -> Eigen::Matrix<T,vecsize,1> inline constexpr
Definition at line 231 of file multiarray.hpp.
{
#ifndef NDEBUG
            my_index_t it = 0;
            ((assert((my_index_t)i < m_length[it]), it ++),...);
#endif
            const auto flat_start = flat_index(index_type({static_cast<size_t>(i)...}));;
            return elements.template segment<vecsize>(flat_start);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, multidimensional::multiarray< T, depth >::flat_index(), and multidimensional::multiarray< T, depth >::m_length.
begin() [1/2]
template<typename T , size_t depth> constexpr const_iterator multidimensional::multiarray< T, depth >::begin () const inline constexpr noexcept
Definition at line 153 of file multiarray.hpp.
        {
            return elements.data();
        }
References multidimensional::multiarray< T, depth >::elements.
begin() [2/2]
template<typename T , size_t depth> constexpr iterator multidimensional::multiarray< T, depth >::begin () inline constexpr noexcept
Definition at line 144 of file multiarray.hpp.
        {
            return elements.data();
        }
References multidimensional::multiarray< T, depth >::elements.
Referenced by multidimensional::multiarray< T, depth >::maxabs(), maxabs(), multidimensional::multiarray< T, depth >::minabs(), and power2().
cbegin()
template<typename T , size_t depth> constexpr const_iterator multidimensional::multiarray< T, depth >::cbegin () const inline constexpr noexcept
Definition at line 162 of file multiarray.hpp.
        {
            return elements.data();
        }
References multidimensional::multiarray< T, depth >::elements.
cend()
template<typename T , size_t depth> constexpr const_iterator multidimensional::multiarray< T, depth >::cend () const inline constexpr noexcept
Definition at line 166 of file multiarray.hpp.
        {
            return elements.data() + elements.size();
        }
References multidimensional::multiarray< T, depth >::elements.
check_bounds()
template<typename T , size_t depth> bool multidimensional::multiarray< T, depth >::check_bounds (const index_type & index) const private noexcept
Definition at line 626 of file multiarray.hpp.
    {
#ifdef MULTIARRAY_CHECK_BOUNDS
        for (size_t i = 0; i < depth; i++)
        {
            if (index[i] >= m_length[i] || index[i] < 0)
            {
                return false;
            }
        }
#endif
        return true;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::get_values(), multidimensional::multiarray< T, depth >::range(), and multidimensional::multiarray< T, depth >::range().
check_bounds_end()
template<typename T , size_t depth> bool multidimensional::multiarray< T, depth >::check_bounds_end (const index_type & index) const private noexcept
Definition at line 641 of file multiarray.hpp.
    {
#ifdef MULTIARRAY_CHECK_BOUNDS
        for (size_t i = 0; i < depth; i++)
        {
            if (index[i] > m_length[i] || index[i] < 0)
            {
                return false;
            }
        }
#endif
        return true;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::range(), and multidimensional::multiarray< T, depth >::range().
check_size()
template<typename T , size_t depth> void multidimensional::multiarray< T, depth >::check_size () const inline private
Definition at line 592 of file multiarray.hpp.
        {
#if DEBUG
            if (_flat_size() != elements.size())
            {
                std::cerr << "Flat size: " << _flat_size() << std::endl
                          << "elements.size(): " << elements.size() << std::endl;
                throw std::logic_error("multiarrray::operator= got an invalid parameter and cannot construct a consistent object.");
            }
#endif
        }
References multidimensional::multiarray< T, depth >::_flat_size(), and multidimensional::multiarray< T, depth >::elements.
Referenced by multidimensional::multiarray< T, depth >::multiarray(), and multidimensional::multiarray< T, depth >::multiarray().
data() [1/2]
template<typename T , size_t depth> const T * multidimensional::multiarray< T, depth >::data () const inline noexcept
Definition at line 352 of file multiarray.hpp.
        {
            return elements.data();
        }
References multidimensional::multiarray< T, depth >::elements.
data() [2/2]
template<typename T , size_t depth> T * multidimensional::multiarray< T, depth >::data () inline noexcept
Definition at line 347 of file multiarray.hpp.
        {
            return elements.data();
        }
References multidimensional::multiarray< T, depth >::elements.
eigen_segment() [1/2]
template<typename T , size_t depth> constexpr auto multidimensional::multiarray< T, depth >::eigen_segment (const index_type & start, const index_type & end) inline constexpr
return segment including start and end
Definition at line 196 of file multiarray.hpp.
        {
            if (check_bounds(start) && check_bounds_end(end))
            {
                const auto flat_start = flat_index(start);
                const auto flat_end = flat_index(end);
                return elements.segment(flat_start, flat_end - flat_start);
            }
            else
            {
                throw std::invalid_argument("Passed invalid indices during creation of a multiarray range");
            }
        }
References multidimensional::multiarray< T, depth >::check_bounds(), multidimensional::multiarray< T, depth >::check_bounds_end(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, multidimensional::multiarray< T, depth >::end(), and multidimensional::multiarray< T, depth >::flat_index().
Referenced by dataContainerBase< Q, rank >::eigen_segment(), and dataContainerBase< Q, rank >::eigen_segment().
eigen_segment() [2/2]
template<typename T , size_t depth> constexpr auto multidimensional::multiarray< T, depth >::eigen_segment (const index_type & start, const index_type & end) const inline constexpr
Definition at line 210 of file multiarray.hpp.
        {
            if (check_bounds(start) && check_bounds_end(end))
            {
                const auto flat_start = flat_index(start);
                const auto flat_end = flat_index(end);
                return elements.segment(flat_start, flat_end - flat_start);
            }
            else
            {
                throw std::invalid_argument("Passed invalid indices during creation of a multiarray range");
            }
        }
References multidimensional::multiarray< T, depth >::check_bounds(), multidimensional::multiarray< T, depth >::check_bounds_end(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, multidimensional::multiarray< T, depth >::end(), and multidimensional::multiarray< T, depth >::flat_index().
elementwise_map_assign()
template<typename T , size_t depth> template<typename Q , typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::elementwise_map_assign (Q op, const multiarray< R, depth > & rhs) inline
elementwise arithmetics-assignment op's
Definition at line 385 of file multiarray.hpp.
        {
            if (rhs.length() != length())
            {
                throw std::length_error("Cannot perform pairwise operations on multiarrays of different length.");
            }
            for (size_type i = 0; i < elements.size(); i++)
            {
                elements[i] = op(elements[i], rhs.elements[i]);
            }
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::length().
end() [1/2]
template<typename T , size_t depth> constexpr const_iterator multidimensional::multiarray< T, depth >::end () const inline constexpr noexcept
Definition at line 157 of file multiarray.hpp.
        {
            return elements.data() + elements.size();
        }
References multidimensional::multiarray< T, depth >::elements.
end() [2/2]
template<typename T , size_t depth> constexpr iterator multidimensional::multiarray< T, depth >::end () inline constexpr noexcept
Definition at line 148 of file multiarray.hpp.
        {
            return elements.data() + elements.size();
        }
References multidimensional::multiarray< T, depth >::elements.
Referenced by multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::maxabs(), maxabs(), multidimensional::multiarray< T, depth >::minabs(), power2(), multidimensional::multiarray< T, depth >::range(), and multidimensional::multiarray< T, depth >::range().
flat_at() [1/2]
template<typename T , size_t depth> T & multidimensional::multiarray< T, depth >::flat_at (size_type i) inline
flat access
Definition at line 363 of file multiarray.hpp.
        {
            return elements.coeffRef(i);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
Referenced by dataContainerBase< Q, rank >::acc(), dataContainerBase< Q, rank >::direct_set(), multidimensional::multiarray< T, depth >::operator[](), and multidimensional::multiarray< T, depth >::operator[]().
flat_at() [2/2]
template<typename T , size_t depth> const T & multidimensional::multiarray< T, depth >::flat_at (size_type i) const inline
Definition at line 368 of file multiarray.hpp.
        {
            return elements.coeffRef(i);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
flat_index()
template<typename T , size_t depth> multiarray< T, depth >::size_type multidimensional::multiarray< T, depth >::flat_index (const index_type & index) const private noexcept
Definition at line 613 of file multiarray.hpp.
    {
        size_type res = index[0];
        for (size_t i = 1; i < depth; i++)
        {
            res *= m_length[i];
            res += index[i];
        }
        return res;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::range(), multidimensional::multiarray< T, depth >::range(), and multidimensional::multiarray< T, depth >::set_vectorized().
get_cumul_length()
template<typename T , size_t depth> dimensions_type multidimensional::multiarray< T, depth >::get_cumul_length (const dimensions_type & length) const inline private
Definition at line 57 of file multiarray.hpp.
{
            dimensions_type result;
            result[depth-1] = 1;
            for (int i = (int)depth-2; i >= 0; i--) {
                result[i] = result[i+1] * length[i+1];
            }
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::length().
get_depth()
template<typename T , size_t depth> static constexpr size_type multidimensional::multiarray< T, depth >::get_depth () inline static constexpr noexcept
Definition at line 573 of file multiarray.hpp.
        {
            return depth;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_elements()
template<typename T , size_t depth> buffer_type multidimensional::multiarray< T, depth >::get_elements () const inline
Definition at line 357 of file multiarray.hpp.
{
            return elements;
        }
References multidimensional::multiarray< T, depth >::elements.
Referenced by get_slice(), and partial_deriv().
get_flatindex_ini()
template<typename T , size_t depth> template<my_index_t num_first_dims> size_t multidimensional::multiarray< T, depth >::get_flatindex_ini (const index_type & index) const inline
Definition at line 267 of file multiarray.hpp.
{
            size_t result = 0;
            for (my_index_t i = 0; i <= num_first_dims; i++) {
                result += index[i] * m_length_cumulative[i];
            }
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::m_length_cumulative.
get_values()
template<typename T , size_t depth> template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size> auto multidimensional::multiarray< T, depth >::get_values (const index_type & index) const -> Eigen::Matrix<T, vecsize, numberFrequencyDims == 1 ? sample_size : (numberFrequencyDims == 2 ? sample_size*sample_size : sample_size*sample_size*sample_size)> inline
Definition at line 276 of file multiarray.hpp.
                                                                                                                         : (numberFrequencyDims == 2 ? sample_size*sample_size : sample_size*sample_size*sample_size)>
                {
#ifndef NDEBUG
            assert(check_bounds(index));
#endif
            Eigen::Matrix<T, vecsize, numberFrequencyDims == 1 ? sample_size : (numberFrequencyDims == 2 ? sample_size*sample_size : sample_size*sample_size*sample_size)> result;
            const size_t flat_ini = get_flatindex_ini<pos_first_freqpoint+numberFrequencyDims>(index);
            if constexpr (numberFrequencyDims == 1) {
                for (my_index_t i = 0; i < sample_size; i++) {
                    const auto res = at_vectorized<vecsize>(flat_ini + m_length_cumulative[pos_first_freqpoint]*i);
                    result.col(i) = res;
                }
            }
            else if constexpr(numberFrequencyDims == 2) {
                for (my_index_t i = 0; i < sample_size; i++) {
                    for (my_index_t j = 0; j < sample_size; j++) {
                        result.col(i * sample_size + j) = at_vectorized<vecsize>(flat_ini + m_length_cumulative[pos_first_freqpoint]*i + m_length_cumulative[pos_first_freqpoint+1]*j);
                    }
                }
            }
            else if constexpr (numberFrequencyDims == 3) {
                for (my_index_t i = 0; i < sample_size; i++) {
                    for (my_index_t j = 0; j < sample_size; j++) {
                        for (my_index_t l = 0; l < sample_size; l++) {
                            result.col(i * sample_size*sample_size + j * sample_size + l) = at_vectorized<vecsize>( flat_ini + m_length_cumulative[pos_first_freqpoint] * i + m_length_cumulative[pos_first_freqpoint + 1] * j + m_length_cumulative[pos_first_freqpoint + 2] * l);
                        }
                    }
                }
            }
            else {
                assert(false); // numberFrequencyDims > 3 not supported
            }
            return result;
        }
References multidimensional::multiarray< T, depth >::check_bounds(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::m_length_cumulative.
is_same_length()
template<typename T , size_t depth> bool multidimensional::multiarray< T, depth >::is_same_length (const multiarray< value_type, depth > & other) const inline
Definition at line 225 of file multiarray.hpp.
{
            return (m_length == other.m_length);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::m_length.
Referenced by dataContainerBase< Q, rank >::add_vec(), multidimensional::multiarray< T, depth >::operator*=(), multidimensional::multiarray< T, depth >::operator*=(), multidimensional::multiarray< T, depth >::operator+=(), multidimensional::multiarray< T, depth >::operator+=(), multidimensional::multiarray< T, depth >::operator-=(), multidimensional::multiarray< T, depth >::operator-=(), multidimensional::multiarray< T, depth >::operator/=(), multidimensional::multiarray< T, depth >::operator/=(), dataContainerBase< Q, rank >::set_vec(), and dataContainerBase< Q, rank >::set_vec().
isfinite()
template<typename T , size_t depth> bool multidimensional::multiarray< T, depth >::isfinite () const inline
Definition at line 543 of file multiarray.hpp.
        {
            for (const auto &c : *this)
            {
                if (!std::isfinite(c))
                {
                    return false;
                }
            }
            return true;
        }
length()
template<typename T , size_t depth> constexpr const dimensions_type & multidimensional::multiarray< T, depth >::length () const inline constexpr noexcept
Definition at line 563 of file multiarray.hpp.
        {
            return m_length;
        }
References multidimensional::multiarray< T, depth >::m_length.
Referenced by dataContainerBase< Q, rank >::add_vec(), multidimensional::BlockView< T, depth >::BlockView(), multidimensional::multiarray< T, depth >::elementwise_map_assign(), multidimensional::multiarray< T, depth >::get_cumul_length(), dataContainerBase< Q, rank >::get_dims(), get_slice(), maxabs(), partial_deriv(), dataContainerBase< Q, rank >::set_vec(), write_to_hdf(), and write_to_hdf_LambdaLayer().
length_cumul()
template<typename T , size_t depth> constexpr const dimensions_type & multidimensional::multiarray< T, depth >::length_cumul () const inline constexpr noexcept
Definition at line 568 of file multiarray.hpp.
        {
            return m_length_cumulative;
        }
References multidimensional::multiarray< T, depth >::m_length_cumulative.
Referenced by get_slice(), and partial_deriv().
lpNorm()
template<typename T , size_t depth> template<int p> double multidimensional::multiarray< T, depth >::lpNorm () const inline
Definition at line 538 of file multiarray.hpp.
{
            return elements.template lpNorm<p>();
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
max()
template<typename T , size_t depth> T multidimensional::multiarray< T, depth >::max () const inline
Definition at line 514 of file multiarray.hpp.
        {
            return elements.maxCoeff();
        }
References multidimensional::multiarray< T, depth >::elements.
max_norm()
template<typename T , size_t depth> double multidimensional::multiarray< T, depth >::max_norm () const inline
Definition at line 534 of file multiarray.hpp.
{
                return std::abs(maxabs());
            };
References multidimensional::multiarray< T, depth >::maxabs().
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::analyze_tails(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box().
maxabs()
template<typename T , size_t depth> T multidimensional::multiarray< T, depth >::maxabs () const inline
Definition at line 524 of file multiarray.hpp.
        {
            return std::abs(*std::max_element(begin(), end(), abs_compare<value_type>));
        }
References multidimensional::multiarray< T, depth >::begin(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::end().
Referenced by multidimensional::multiarray< T, depth >::max_norm().
min()
template<typename T , size_t depth> T multidimensional::multiarray< T, depth >::min () const inline
Definition at line 519 of file multiarray.hpp.
        {
            return elements.minCoeff();
        }
References multidimensional::multiarray< T, depth >::elements.
minabs()
template<typename T , size_t depth> T multidimensional::multiarray< T, depth >::minabs () const inline
Definition at line 529 of file multiarray.hpp.
        {
            return std::abs(*std::min_element(begin(), end(), abs_compare<value_type>));
        }
References multidimensional::multiarray< T, depth >::begin(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::end().
operator()() [1/2]
template<typename T , size_t depth> template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true> T & multidimensional::multiarray< T, depth >::operator() (const Types &... i) inline
Definition at line 336 of file multiarray.hpp.
        {
            return at(i...);
        }
References multidimensional::multiarray< T, depth >::at(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator()() [2/2]
template<typename T , size_t depth> template<typename... Types, typename std::enable_if_t< sizeof...(Types)==depth, bool > = true> const T & multidimensional::multiarray< T, depth >::operator() (const Types &... i) const inline
Definition at line 342 of file multiarray.hpp.
        {
            return at(i...);
        }
References multidimensional::multiarray< T, depth >::at(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
operator*=() [1/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator*= (const multiarray< R, depth > & rhs) inline
Definition at line 451 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements *= rhs.elements.template cast<T>();
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator*=() [2/3]
template<typename T , size_t depth> multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator*= (const multiarray< T, depth > & rhs) inline
Definition at line 416 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements *= rhs.elements;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator*=() [3/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator*= (const R & rhs) inline noexcept
Definition at line 495 of file multiarray.hpp.
        {
            elements *= rhs;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
operator+=() [1/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator+= (const multiarray< R, depth > & rhs) inline
Definition at line 433 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements += rhs.elements.template cast<T>();
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator+=() [2/3]
template<typename T , size_t depth> multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator+= (const multiarray< T, depth > & rhs) inline
Definition at line 400 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements += rhs.elements;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator+=() [3/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator+= (const R & rhs) inline noexcept
Definition at line 480 of file multiarray.hpp.
        {
            elements += rhs;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
operator-=() [1/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator-= (const multiarray< R, depth > & rhs) inline
Definition at line 442 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements -= rhs.elements.template cast<T>();
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator-=() [2/3]
template<typename T , size_t depth> multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator-= (const multiarray< T, depth > & rhs) inline
Definition at line 408 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements -= rhs.elements;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator-=() [3/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator-= (const R & rhs) inline noexcept
Definition at line 487 of file multiarray.hpp.
        {
            elements -= rhs;
            return *this;
            ;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
operator/=() [1/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator/= (const multiarray< R, depth > & rhs) inline
Definition at line 460 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements /= rhs.elements.template cast<T>();
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator/=() [2/3]
template<typename T , size_t depth> multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator/= (const multiarray< T, depth > & rhs) inline
Definition at line 424 of file multiarray.hpp.
        {
            assert(is_same_length(rhs));
            elements /= rhs.elements;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, and multidimensional::multiarray< T, depth >::is_same_length().
operator/=() [3/3]
template<typename T , size_t depth> template<typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator/= (const R & rhs) inline noexcept
Definition at line 502 of file multiarray.hpp.
        {
            elements /= rhs;
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
operator=() [1/2]
template<typename T , size_t depth> multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator= (const multiarray< T, depth > &) default
operator=() [2/2]
template<typename T , size_t depth> multiarray< T, depth > & multidimensional::multiarray< T, depth >::operator= (multiarray< T, depth > &&) default
operator[]() [1/2]
template<typename T , size_t depth> T & multidimensional::multiarray< T, depth >::operator[] (size_type i) inline
Definition at line 373 of file multiarray.hpp.
        {
            return flat_at(i);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::flat_at().
operator[]() [2/2]
template<typename T , size_t depth> const T & multidimensional::multiarray< T, depth >::operator[] (size_type i) const inline
Definition at line 378 of file multiarray.hpp.
        {
            return flat_at(i);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::flat_at().
range() [1/2]
template<typename T , size_t depth> constexpr auto multidimensional::multiarray< T, depth >::range (const index_type & start, const index_type & end) inline constexpr
Definition at line 171 of file multiarray.hpp.
        {
            if (check_bounds(start) && check_bounds_end(end))
            {
                return make_range(*this, flat_index(start), flat_index(end));
            }
            else
            {
                throw std::invalid_argument("Passed invalid indices during creation of a multiarray range");
            }
        }
References multidimensional::multiarray< T, depth >::check_bounds(), multidimensional::multiarray< T, depth >::check_bounds_end(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::end(), multidimensional::multiarray< T, depth >::flat_index(), and multidimensional::make_range().
range() [2/2]
template<typename T , size_t depth> constexpr auto multidimensional::multiarray< T, depth >::range (const index_type & start, const index_type & end) const inline constexpr
Definition at line 183 of file multiarray.hpp.
        {
            if (check_bounds(start) && check_bounds_end(end))
            {
                return make_const_range(*this, flat_index(start), flat_index(end));
            }
            else
            {
                throw std::invalid_argument("Passed invalid indices during creation of a multiarray range");
            }
        }
References multidimensional::multiarray< T, depth >::check_bounds(), multidimensional::multiarray< T, depth >::check_bounds_end(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::end(), and multidimensional::multiarray< T, depth >::flat_index().
scalar_map_assign()
template<typename T , size_t depth> template<typename Q , typename R > multiarray< T, depth > & multidimensional::multiarray< T, depth >::scalar_map_assign (Q op, const R & rhs) inline noexcept
scalar arithmetic assignment
Definition at line 470 of file multiarray.hpp.
        {
            for (auto &e : elements)
            {
                e = op(e, rhs);
            }
            return *this;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and multidimensional::multiarray< T, depth >::elements.
set_vectorized()
template<typename T , size_t depth> template<std::size_t vecsize> void multidimensional::multiarray< T, depth >::set_vectorized (const Eigen::Matrix< T, vecsize, 1 > & value, const index_type & idx) inline
Definition at line 256 of file multiarray.hpp.
{
#ifndef NDEBUG
            for (size_t it = 0; it < depth; it++) {
                assert(idx[it] < m_length[it]);
            }
#endif
            const auto flat_start = flat_index(idx);
            elements.template segment<vecsize>(flat_start) = value;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), multidimensional::multiarray< T, depth >::elements, multidimensional::multiarray< T, depth >::flat_index(), and multidimensional::multiarray< T, depth >::m_length.
size()
template<typename T , size_t depth> size_type multidimensional::multiarray< T, depth >::size () const inline noexcept
Definition at line 558 of file multiarray.hpp.
        {
            return elements.size();
        }
References multidimensional::multiarray< T, depth >::elements.
Referenced by dataContainerBase< Q, rank >::acc(), dataContainerBase< Q, rank >::add_vec(), dataContainerBase< Q, rank >::direct_set(), and dataContainerBase< Q, rank >::set_vec().
Friends And Related Symbol Documentation
operator==
template<typename T , size_t depth> bool operator== (const multiarray< T, depth > & lhs, const multiarray< T, depth > & rhs) friend
non-member op's
Definition at line 685 of file multiarray.hpp.
    {
        return (lhs.m_length == rhs.m_length) && (lhs.elements == rhs.elements).all();
    }
swap
template<typename T , size_t depth> void swap (multiarray< value_type, depth > & lhs, multiarray< value_type, depth > & rhs) friend
Definition at line 78 of file multiarray.hpp.
        {
            using std::swap;
            swap(lhs.m_length, rhs.m_length);
            swap(lhs.elements, rhs.elements);
        }
Member Data Documentation
elements
template<typename T , size_t depth> buffer_type multidimensional::multiarray< T, depth >::elements
Definition at line 75 of file multiarray.hpp.
Referenced by multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::begin(), multidimensional::multiarray< T, depth >::begin(), multidimensional::multiarray< T, depth >::cbegin(), multidimensional::multiarray< T, depth >::cend(), multidimensional::multiarray< T, depth >::check_size(), multidimensional::multiarray< T, depth >::data(), multidimensional::multiarray< T, depth >::data(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::multiarray< T, depth >::eigen_segment(), multidimensional::elementwise(), multidimensional::multiarray< T, depth >::elementwise_map_assign(), multidimensional::multiarray< T, depth >::end(), multidimensional::multiarray< T, depth >::end(), multidimensional::multiarray< T, depth >::flat_at(), multidimensional::multiarray< T, depth >::flat_at(), multidimensional::multiarray< T, depth >::get_elements(), multidimensional::multiarray< T, depth >::lpNorm(), multidimensional::multiarray< T, depth >::max(), multidimensional::multiarray< T, depth >::min(), multidimensional::multiarray< T, depth >::multiarray(), multidimensional::multiarray< T, depth >::multiarray(), multidimensional::multiarray< T, depth >::operator*=(), multidimensional::multiarray< T, depth >::operator*=(), multidimensional::multiarray< T, depth >::operator*=(), multidimensional::multiarray< T, depth >::operator+=(), multidimensional::multiarray< T, depth >::operator+=(), multidimensional::multiarray< T, depth >::operator+=(), multidimensional::multiarray< T, depth >::operator-=(), multidimensional::multiarray< T, depth >::operator-=(), multidimensional::multiarray< T, depth >::operator-=(), multidimensional::multiarray< T, depth >::operator/=(), multidimensional::multiarray< T, depth >::operator/=(), multidimensional::multiarray< T, depth >::operator/=(), multidimensional::scalar_map(), multidimensional::multiarray< T, depth >::scalar_map_assign(), multidimensional::multiarray< T, depth >::set_vectorized(), and multidimensional::multiarray< T, depth >::size().
m_length
template<typename T , size_t depth> dimensions_type multidimensional::multiarray< T, depth >::m_length private
Definition at line 56 of file multiarray.hpp.
Referenced by multidimensional::multiarray< T, depth >::_flat_size(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::at_vectorized(), multidimensional::multiarray< T, depth >::is_same_length(), multidimensional::multiarray< T, depth >::length(), and multidimensional::multiarray< T, depth >::set_vectorized().
m_length_cumulative
template<typename T , size_t depth> dimensions_type multidimensional::multiarray< T, depth >::m_length_cumulative = get_cumul_length(m_length) private
Definition at line 65 of file multiarray.hpp.
Referenced by multidimensional::multiarray< T, depth >::get_flatindex_ini(), multidimensional::multiarray< T, depth >::get_values(), and multidimensional::multiarray< T, depth >::length_cumul().
The documentation for this class was generated from the following file:
multiarray.hpp