SIAM-Keldysh-mfRG: ode_solver_impl Namespace Reference
ode_solver_impl Namespace Reference
Classes
struct butcher_tableau
Functions
template<typename Y , typename FlowGrid , size_t stages, typename System >
void rk_step (const butcher_tableau< stages > &tableau, const Y &y_init, const Y &dydx, Y &result, const double t_value, const double t_step, double &maxrel_error, const System &rhs, const ODE_solver_config &config)
template<typename Y , typename FlowGrid , size_t stages, typename System >
void rkqs (butcher_tableau< stages > tableau, Y &state_i, double &Lambda_i, double htry, double &hdid, double &hnext, double min_t_step, double max_t_step, const System &rhs, size_t iteration, const ODE_solver_config &config, const bool verbose)
Variables
const butcher_tableau< 6 > cash_carp
const butcher_tableau< 4 > RK4basic
const butcher_tableau< 4 > BogaSha
Function Documentation
rk_step()
template<typename Y , typename FlowGrid , size_t stages, typename System > void ode_solver_impl::rk_step (const butcher_tableau< stages > & tableau, const Y & y_init, const Y & dydx, Y & result, const double t_value, const double t_step, double & maxrel_error, const System & rhs, const ODE_solver_config & config)
Runge Kutta solver for methods that can be represented by a butcher tableau
Template Parameters
Y datatype of y, in fRG: State<Q>
FlowGrid used to determine Lambdas from t (where t is the x used by the (adaptive) ODE solver)
stages number of stages for the Runge-Kutta method specified in tableau
Parameters
tableau butcher tableau
y_init initial state
result (returned) result of Runge-Kutte step
t_value gives initial x via FlowGrid
t_step step size in x
maxrel_error (returned) maximal relative deviation between 5-point and 4-point rule
rhs function that computes the right-hand side of the flow equation
Definition at line 296 of file ODE_solvers.hpp.
    {
        Y state_stage=y_init; // temporary state
        //
        vec<Y> k; // stores the pure right-hand-sides ( without multiplication with an step size )
        k.reserve(stages);
        k.push_back( dydx
#ifdef REPARAMETRIZE_FLOWGRID
        * FlowGrid::dlambda_dt(t_value)
#endif
        );
        double Lambda_stage;
        double t_stage, stepsize;
        // Start at 1 because 0th stage is already contained in dydx parameter
        for (size_t stage = 1; stage < stages; stage++)
        {
#ifdef REPARAMETRIZE_FLOWGRID
            t_stage = t_value + t_step* tableau.get_node(stage);
            Lambda_stage = FlowGrid::lambda_from_t(t_stage);
            stepsize = t_step;
            //utils::print("\t current t_stage: ", t_stage, "\n" );
#else
            const double Lambda = FlowGrid::lambda_from_t(t_value);
            double dLambda = FlowGrid::lambda_from_t(t_value + t_step) - Lambda;
            Lambda_stage = Lambda + dLambda * tableau.get_node(stage);
            stepsize = dLambda;
#endif
            state_stage = y_init;
            for (size_t col_index = 0; col_index < stage; col_index++)
            {
                double factor = stepsize * tableau.get_a(stage, col_index);
                state_stage += k[col_index] * factor;
            }
            Y dydx_temp;
            rhs(state_stage, dydx_temp, Lambda_stage)
            ;
            k.push_back( dydx_temp
#ifdef REPARAMETRIZE_FLOWGRID
                    * FlowGrid::dlambda_dt(t_stage)
#endif
            );
        }
        result = y_init;
        for (size_t stage = 0; stage < stages; stage++)
        {
            result += k[stage] * stepsize * tableau.b_high[stage];
        }
        Y err = k[0] * stepsize * tableau.get_error_b(0);
        for (size_t stage = 1; stage < stages; stage++)
        {
            err += k[stage] * stepsize * tableau.get_error_b(stage);
        }
        Y y_scale = (abs(result) * config.a_State + abs(dydx*stepsize) * config.a_dState_dLambda) * config.relative_error + config.absolute_error;
        maxrel_error = max_rel_err(err, y_scale); // alternatively state yscal = abs_sum_tiny(integrated, h * dydx, tiny);
        if (VERBOSE) utils::print("ODE solver error estimate: ", maxrel_error, "\n");
        //assert(my_isfinite(result));
        //assert(my_isfinite(maxrel_error));
    }
References ODE_solver_config::a_dState_dLambda, ODE_solver_config::a_State, abs(), ODE_solver_config::absolute_error, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), max_rel_err(), utils::print(), ODE_solver_config::relative_error, REPARAMETRIZE_FLOWGRID, and VERBOSE.
rkqs()
template<typename Y , typename FlowGrid , size_t stages, typename System > void ode_solver_impl::rkqs (butcher_tableau< stages > tableau, Y & state_i, double & Lambda_i, double htry, double & hdid, double & hnext, double min_t_step, double max_t_step, const System & rhs, size_t iteration, const ODE_solver_config & config, const bool verbose)
Template Parameters
FlowGrid
Parameters
state_i
Lambda_i
htry
hdid
hnext
min_t_step
max_t_step
lambda_checkpoints
rhs
Definition at line 377 of file ODE_solvers.hpp.
    {
        // Safety intentionally chosen smaller than in Numerical recipes, because the step
        // size estimates were consistently too large and repeated steps are very expensive
        const double SAFETY = 0.8, PGROW = -0.2, PSHRINK = -0.25, MAXGROW = 2.;
        int world_rank = mpi_world_rank();
        const double t_value = FlowGrid::t_from_lambda(Lambda_i);
        double t_step = FlowGrid::t_from_lambda(Lambda_i + htry) - t_value;
        Y dydx;
        rhs(state_i, dydx, Lambda_i); // const State_t& state_in, State_t& dState_dt, double Lambda_in
        bool rejected = false;
        double errmax;
        unsigned int attempts = 0;
        //const auto &lattice = state_i.vertex.lattice;
        Y temporary = state_i;
        for (;;)    // infinite loop
        {
            // === Evaluation ===
            if (verbose and world_rank == 0)
            {
                utils::print("Try stepsize t ", t_step, " (from Lambda = ", Lambda_i
                          , " to ", FlowGrid::lambda_from_t(t_value + t_step)
                          , ").\n");
                utils::print("Current t: ", t_value, "\n");
            };
            ode_solver_impl::rk_step<Y, FlowGrid>(tableau, state_i, dydx, temporary, t_value, t_step, errmax, rhs, config);
            if constexpr(std::is_same<State<state_datatype>, Y>::value) {
                rhs.rk_step = 1;
                rhs.stats.RKattempts += 1;
            }
            if (not tableau.adaptive) break;
            if (verbose and world_rank == 0)
            {
                utils::print("Just finished ODE step attempt \t ---> \t errmax/tolerance (ODE): ", errmax, "\n");
                if (std::abs(t_step) <= min_t_step)
                {
                    std::cout << "Step was taken with minimal step size " << -min_t_step
                              << "(from Lambda / J = " << Lambda_i
                              << " to " << FlowGrid::lambda_from_t(t_value + t_step)
                              << ") and will be accepted regardless of the error." << std::endl;
                }
            }
            // accept result
            // if step was minimal step size, accept step in any case. This keeps program from crashing
            if (errmax <= 1. || std::abs(t_step) <= min_t_step)
            {
                break;
            }
            if (attempts > config.max_stepResizing_attempts and tableau.adaptive) {
                utils::print("ODE solver reached maximal number of stepResizing attempts.");
                break;
            }
            // === Resize t_step ===
            if (verbose and world_rank == 0)
            {
                utils::print("Stepsize too big. Readjust..\n");
            }
            rejected = true;
            const double t_step_resized = SAFETY * t_step * pow(errmax, PSHRINK);
            t_step = sgn(t_step) * std::max({std::abs(t_step_resized), 0.1 * std::abs(t_step), min_t_step});
            if (t_value + t_step == t_value)
            {
                // At this point, recovery is impossible. Emergency abort.
                std::stringstream s;
                s << "Fatal: Stepsize underflow in adaptive Runge-Kutta routine rkqs. Current value of t is "
                  << t_value << "and the desired step size is " << t_step
                  << ". It is likely that the chosen value of t_step_min is too small. Will now abort.";
                std::cout << s.str();
                throw std::runtime_error(s.str());
            }
        }
        double t_next_step;
        if (errmax > std::pow(MAXGROW/SAFETY, PGROW))
        {
            t_next_step = SAFETY * t_step * std::pow(errmax, PGROW);
            //assert(t_next_step>=0);
        }
        else
        {
            t_next_step = MAXGROW * t_step;
            //assert(t_next_step>=0);
        }
        // Don't increase step size immediately after rejecting a step; further shrinking is ok
        if (rejected)
        {
            t_next_step = sgn(t_step) * std::min(std::abs(t_next_step), std::abs(t_step));
            //assert(t_next_step>=0);
        }
        // clip to interval [min_t_step, max_t_step]
        t_next_step = sgn(t_next_step) * std::min(std::max(min_t_step, std::abs(t_next_step)), max_t_step);
        // === Update output ref's ===
        Lambda_i = FlowGrid::lambda_from_t(t_value + t_step);
        hdid = Lambda_i - FlowGrid::lambda_from_t(t_value);
        hnext = FlowGrid::lambda_from_t(t_value + t_step + t_next_step) - Lambda_i;
        state_i = temporary;
        //assert(t_next_step>=0);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), ODE_solver_config::max_stepResizing_attempts, mpi_world_rank(), utils::print(), and sgn().
Variable Documentation
BogaSha
const butcher_tableau<4> ode_solver_impl::BogaSha
Initial value:
{
            .a = {1. / 2.,     0.,     0.,
                  0.,          3. / 4.,0.,
                  2./9.,       1./3.,  4./9.},
            .b_high = {2./9., 1./3., 4./9., 0.},
            .b_low = {7./24., 1./4., 1./3., 1./8.},
            .c = {1./2., 3./4., 1.},
            .adaptive = true,
            .name = "BogackiShampine"
    }
Definition at line 265 of file ODE_solvers.hpp.
{
            // a (Runge-Kutta Matrix)
            .a = {1. / 2.,     0.,     0.,
                  0.,          3. / 4.,0.,
                  2./9.,       1./3.,  4./9.},
            // b (weights) for the 3rd order solution
            .b_high = {2./9., 1./3., 4./9., 0.},
            // b (weights) for the 2nd order solution
            .b_low = {7./24., 1./4., 1./3., 1./8.},
            // c (nodes)
            .c = {1./2., 3./4., 1.},
            .adaptive = true,
            .name = "BogackiShampine"
    };
cash_carp
const butcher_tableau<6> ode_solver_impl::cash_carp
Initial value:
{
            .a = {1. / 5.,           0.,             0.,             0.,                 0.,
                  3. / 40.,          9. / 40.,       0.,             0.,                 0.,
                  3. / 10.,          -9. / 10.,      6. / 5.,        0.,                 0.,
                  -11. / 54.,        5. / 2.,        -70. / 27.,     35. / 27.,          0.,
                  1631. / 55296.,    175. / 512.,    575. / 13824.,  44275. / 110592.,   253. / 4096.},
            .b_high = {37. / 378., 0., 250. / 621., 125. / 594., 0., 512. / 1771.},
            .b_low = {2825. / 27648., 0., 18575. / 48384., 13525. / 55296., 277. / 14336., 1. / 4.},
            .c = {1. / 5., 3. / 10., 3. / 5., 1., 7. / 8.},
            .adaptive = true,
            .name = "Cash-Carp"
    }
Definition at line 231 of file ODE_solvers.hpp.
{
            // a (Runge-Kutta Matrix)
            .a = {1. / 5.,           0.,             0.,             0.,                 0.,
                  3. / 40.,          9. / 40.,       0.,             0.,                 0.,
                  3. / 10.,          -9. / 10.,      6. / 5.,        0.,                 0.,
                  -11. / 54.,        5. / 2.,        -70. / 27.,     35. / 27.,          0.,
                  1631. / 55296.,    175. / 512.,    575. / 13824.,  44275. / 110592.,   253. / 4096.},
            // b (weights) for the 5th order solution
            .b_high = {37. / 378., 0., 250. / 621., 125. / 594., 0., 512. / 1771.},
            // b (weights) for the 4th order solution
            .b_low = {2825. / 27648., 0., 18575. / 48384., 13525. / 55296., 277. / 14336., 1. / 4.},
            // c (nodes)
            .c = {1. / 5., 3. / 10., 3. / 5., 1., 7. / 8.},
            .adaptive = true,
            .name = "Cash-Carp"
    };
Referenced by ode_solver().
RK4basic
const butcher_tableau<4> ode_solver_impl::RK4basic
Initial value:
{
            .a = {1. / 2.,     0.,          0.,
                  0.,          1. / 2.,     0.,
                  0.,          0.,          1.},
            .b_high = {1./6., 1./3., 1./3., 1./6.},
            .b_low = {1./6., 1./3., 1./3., 1./6.},
            .c = {1./2, 1./2., 1.},
            .adaptive = false,
            .name = "basic Runge-Kutta 4"
    }
Definition at line 248 of file ODE_solvers.hpp.
{
            // a (Runge-Kutta Matrix)
            .a = {1. / 2.,     0.,          0.,
                  0.,          1. / 2.,     0.,
                  0.,          0.,          1.},
            // b (weights) for the 4th order solution
            .b_high = {1./6., 1./3., 1./3., 1./6.},
            // b (weights) for the 4th order solution
            .b_low = {1./6., 1./3., 1./3., 1./6.},
            // c (nodes)
            .c = {1./2, 1./2., 1.},
            .adaptive = false,
            .name = "basic Runge-Kutta 4"
    };