SIAM-Keldysh-mfRG: FrequencyGrid< angularGrid > Class Reference
FrequencyGrid< angularGrid > Class Reference
#include <frequency_grid.hpp>
Public Member Functions
void guess_essential_parameters (double Lambda, const fRG_config &config)
guess essential parameters from value of Lambda
void derive_auxiliary_parameters ()
double frequency_from_t (double t) const
grid functions:
double t_from_frequency (double w) const
FrequencyGrid (const char type_in, const unsigned int diag_class_in, const double Lambda, const fRG_config &config, const bool purely_positive)
constructor:
double get_frequency (const int index) const
getter functions:
double get_auxiliary_gridpoint (const int index) const
const rvec & get_all_frequencies () const
const rvec & get_all_auxiliary_gridpoints () const
double get_spacing_auxiliary_gridpoints () const
char get_type () const
char get_diag_class () const
void set_essential_parameters (double wmax_in, double number_of_intervals_in)
setter functions:
void set_w_upper (double wmax)
void initialize_grid ()
void update_number_of_intervals (double number_of_intervals_in)
int get_grid_index (double frequency) const
core grid functionality (has to be super efficient)
int get_grid_index (double &t, double frequency) const
void update_power (double power_in)
Public Attributes
int number_of_gridpoints
essential grid parameters:
double w_upper
double w_lower
freqType w_center = 0
int number_of_intervals
double lin_fac = 1.e-4
double power
double recip_power
char type
grid identifier:
int diag_class
bool purely_positive
double t_upper
auxiliary grid parameters:
double t_lower
double spacing_auxiliary_gridpoint
double half_of_interval_length_for_t
double half_of_interval_length_for_w
double half_of_interval_length_for_w_recip
double interval_length_for_w_recip
double quad_fac_recip
double lin_fac_to_power
rvec all_frequencies
list of all frequencies:
rvec auxiliary_grid
Friends
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type >
class DataContainer
Detailed Description
Definition at line 280 of file frequency_grid.hpp.
Constructor & Destructor Documentation
FrequencyGrid()
FrequencyGrid< angularGrid >::FrequencyGrid (const char type_in, const unsigned int diag_class_in, const double Lambda, const fRG_config & config, const bool purely_positive) inline
constructor:
Definition at line 329 of file frequency_grid.hpp.
                                                                                                                                                   : type(type_in), diag_class(diag_class_in), purely_positive(purely_positive) {
#ifndef DENSEGRID
        assert(KELDYSH || ZERO_T);  // for Matsubara T>0 only allow dense grid
#else
        assert(false);
#endif
        guess_essential_parameters(Lambda, config);
        initialize_grid();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, and ZERO_T.
Member Function Documentation
derive_auxiliary_parameters()
void FrequencyGrid< angularGrid >::derive_auxiliary_parameters ()
Definition at line 613 of file frequency_grid.c++.
{
    recip_power = 1./power;
    lin_fac_to_power = pow(lin_fac, power);
    spacing_auxiliary_gridpoint = (t_upper - t_lower) / (number_of_gridpoints - 1);
    half_of_interval_length_for_t = (t_upper - t_lower) * 0.5 / number_of_intervals;
    half_of_interval_length_for_w = (w_upper - w_lower) * 0.5 / number_of_intervals;
    half_of_interval_length_for_w_recip = number_of_intervals / ((w_upper - w_lower) * 0.5);
    interval_length_for_w_recip = (double)number_of_intervals / (w_upper - w_lower);
    quad_fac_recip = (pow(1 + lin_fac, power) - lin_fac_to_power);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
frequency_from_t()
double FrequencyGrid< angularGrid >::frequency_from_t (double t) const
grid functions:
Definition at line 680 of file frequency_grid.c++.
{
    const double i_interval = floor( (t + half_of_interval_length_for_t) * number_of_intervals / (t_upper - t_lower) );
    const double remainder  = t / half_of_interval_length_for_t - i_interval * 2; // remainder in [-1, 1]
    //const double result = ( i_interval + 0.5 / quad_fac_recip * remainder * (std::abs(remainder) + 2.*lin_fac)) * half_of_interval_length_for_w * 2.;
    const double result = ( i_interval + 0.5 / quad_fac_recip * sgn(remainder) * (pow(std::abs(remainder) + lin_fac, power) - lin_fac_to_power)) * half_of_interval_length_for_w * 2.;
    assert(isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sgn().
get_all_auxiliary_gridpoints()
const rvec & FrequencyGrid< angularGrid >::get_all_auxiliary_gridpoints () const inline
Definition at line 343 of file frequency_grid.hpp.
{return auxiliary_grid;};
get_all_frequencies()
const rvec & FrequencyGrid< angularGrid >::get_all_frequencies () const inline
Definition at line 342 of file frequency_grid.hpp.
{return all_frequencies;};
get_auxiliary_gridpoint()
double FrequencyGrid< angularGrid >::get_auxiliary_gridpoint (const int index) const inline
Definition at line 341 of file frequency_grid.hpp.
{assert(index>=0); assert(index<number_of_gridpoints); return auxiliary_grid[index];};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_diag_class()
char FrequencyGrid< angularGrid >::get_diag_class () const inline
Definition at line 346 of file frequency_grid.hpp.
{return diag_class;};
get_frequency()
double FrequencyGrid< angularGrid >::get_frequency (const int index) const inline
getter functions:
Definition at line 340 of file frequency_grid.hpp.
{assert(index>=0); return all_frequencies[index];};
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_grid_index() [1/2]
int FrequencyGrid< angularGrid >::get_grid_index (double & t, double frequency) const
Definition at line 732 of file frequency_grid.c++.
{
    t = t_from_frequency(frequency);
#ifdef DENSEGRID
    assert(false);
    int index = 0;
    return index;
#else
    assert(std::abs(spacing_auxiliary_gridpoint - 1) < 1e-15);
    int index = int((t - t_lower) + 1e-12);
    index = std::max(0, index);
    index = std::min(number_of_gridpoints - 2, index);
    assert(auxiliary_grid[index] <= t + inter_tol);
    assert(auxiliary_grid[index+1] >= t - inter_tol or index == number_of_gridpoints-2);
    return index;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and inter_tol.
get_grid_index() [2/2]
int FrequencyGrid< angularGrid >::get_grid_index (double frequency) const
core grid functionality (has to be super efficient)
Do I need this? The next function basically does the same
Definition at line 711 of file frequency_grid.c++.
{
    const double t = t_from_frequency(frequency);
#ifdef DENSEGRID
    assert(false);
    int index = 0;
    return index;
#else
    assert(std::abs(spacing_auxiliary_gridpoint - 1.) < 1e-10); // By making sure that spacing_auxiliary_gridpoint = 1, there is no need to divide through spacing_auxiliary_gridpoint
    int index = int((t - t_lower) + 1e-12);
    index = std::max(0, index);
    index = std::min(number_of_gridpoints - 2, index);
    //assert(all_frequencies[index] <= frequency + (std::abs(frequency)+1)*1e-12);
    //assert(all_frequencies[index+1] >= frequency);
    assert(auxiliary_grid[index] <= t+inter_tol);
    assert(auxiliary_grid[index+1] >= t-inter_tol or index == number_of_gridpoints-2);
    return index;
#endif
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and inter_tol.
get_spacing_auxiliary_gridpoints()
double FrequencyGrid< angularGrid >::get_spacing_auxiliary_gridpoints () const inline
Definition at line 344 of file frequency_grid.hpp.
{return spacing_auxiliary_gridpoint;}
get_type()
char FrequencyGrid< angularGrid >::get_type () const inline
Definition at line 345 of file frequency_grid.hpp.
{return type;};
guess_essential_parameters()
void FrequencyGrid< angularGrid >::guess_essential_parameters (double Lambda, const fRG_config & config)
guess essential parameters from value of Lambda
TODO: investigate structure in K3 and implement suitable grid
Definition at line 624 of file frequency_grid.c++.
{
    switch (diag_class) {
        case 1:
            // nonsensical for 1D objects
            number_of_gridpoints = nBOS;
            w_upper = 2*M_PI;
            number_of_intervals = 1;
            break;
        case 2:
            if (type == 'b') {
                assert(false);
            }
            else {
                assert(type == 'f');
                number_of_gridpoints = nFER2;
                w_upper = M_PI;
                number_of_intervals = 8;
                assert( (number_of_gridpoints - 1) % number_of_intervals == 0);
            }
            break;
        case 3:
            if (type == 'b') {
                number_of_gridpoints = nBOS3;
                number_of_intervals = 8;
                w_upper = M_PI;
            }
            else {
                assert(type == 'f');
                number_of_gridpoints = K3_config.dims[purely_positive ? my_defs::K3::nup : my_defs::K3::nu];
                number_of_intervals = purely_positive ? 4 : 8;
                w_upper = M_PI;
                assert( (number_of_gridpoints - 1) % number_of_intervals == 0);
            }
            break;
        default:
            break;
    }
    t_upper = ((double) number_of_gridpoints - 1) * (purely_positive ? 1. : 0.5);
    if (purely_positive) {
        w_lower = 0;
        t_lower = 0;
    }
    else {
        w_lower = -w_upper;
        t_lower = -t_upper;
    }
    all_frequencies = rvec(number_of_gridpoints);
    auxiliary_grid = rvec(number_of_gridpoints);
    power = 2;
    initialize_grid();
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), K3_config, nBOS, nBOS3, nFER2, my_defs::K3::nu, and my_defs::K3::nup.
initialize_grid()
void FrequencyGrid< angularGrid >::initialize_grid ()
Definition at line 699 of file frequency_grid.c++.
{
    derive_auxiliary_parameters();
    for (int i = 0; i < number_of_gridpoints; i++) {
        const double t = t_lower + spacing_auxiliary_gridpoint * (double)i;
        auxiliary_grid[i] = t;
        all_frequencies[i] = frequency_from_t(t);
    }
    //all_frequencies[purely_positive ? 0 : (int) (number_of_gridpoints - 1) / 2] = 0.;
    //auxiliary_grid [purely_positive ? 0 : (int) (number_of_gridpoints - 1) / 2] = 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
set_essential_parameters()
void FrequencyGrid< angularGrid >::set_essential_parameters (double wmax_in, double number_of_intervals_in) inline
setter functions:
Definition at line 349 of file frequency_grid.hpp.
{
        w_upper = wmax_in;
        w_lower = 0.;
        number_of_intervals = number_of_intervals_in;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
set_w_upper()
void FrequencyGrid< angularGrid >::set_w_upper (double wmax) inline
Definition at line 354 of file frequency_grid.hpp.
{
        set_essential_parameters(wmax, number_of_intervals);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
t_from_frequency()
double FrequencyGrid< angularGrid >::t_from_frequency (double w) const
Definition at line 690 of file frequency_grid.c++.
{
    const double i_interval = floor( (w + half_of_interval_length_for_w) * interval_length_for_w_recip);
    const double remainder  = w / half_of_interval_length_for_w - i_interval * 2; // remainder in [-1, 1]
    //const double result = ( i_interval + 0.5 * (sqrt(std::abs(remainder)*quad_fac_recip + lin_fac*lin_fac) - lin_fac) * sgn(remainder)) * half_of_interval_length_for_t * 2.;
    const double result = ( i_interval + 0.5 * (pow(std::abs(remainder) * quad_fac_recip + lin_fac_to_power, recip_power) - lin_fac) * sgn(remainder)) * half_of_interval_length_for_t * 2.;
    assert(isfinite(result));
    return result;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and sgn().
update_number_of_intervals()
void FrequencyGrid< angularGrid >::update_number_of_intervals (double number_of_intervals_in) inline
Definition at line 358 of file frequency_grid.hpp.
{
        number_of_intervals = number_of_intervals_in;
        initialize_grid();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
update_power()
void FrequencyGrid< angularGrid >::update_power (double power_in) inline
Definition at line 367 of file frequency_grid.hpp.
{
        power = std::max(power_in, 1.); // don't go lower than 1
        initialize_grid();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Friends And Related Symbol Documentation
DataContainer
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > friend class DataContainer friend
Definition at line 282 of file frequency_grid.hpp.
Member Data Documentation
all_frequencies
rvec FrequencyGrid< angularGrid >::all_frequencies
list of all frequencies:
Definition at line 319 of file frequency_grid.hpp.
auxiliary_grid
rvec FrequencyGrid< angularGrid >::auxiliary_grid
Definition at line 320 of file frequency_grid.hpp.
diag_class
int FrequencyGrid< angularGrid >::diag_class
Definition at line 302 of file frequency_grid.hpp.
half_of_interval_length_for_t
double FrequencyGrid< angularGrid >::half_of_interval_length_for_t
Definition at line 310 of file frequency_grid.hpp.
half_of_interval_length_for_w
double FrequencyGrid< angularGrid >::half_of_interval_length_for_w
Definition at line 311 of file frequency_grid.hpp.
half_of_interval_length_for_w_recip
double FrequencyGrid< angularGrid >::half_of_interval_length_for_w_recip
Definition at line 312 of file frequency_grid.hpp.
interval_length_for_w_recip
double FrequencyGrid< angularGrid >::interval_length_for_w_recip
Definition at line 313 of file frequency_grid.hpp.
lin_fac
double FrequencyGrid< angularGrid >::lin_fac = 1.e-4
Definition at line 291 of file frequency_grid.hpp.
lin_fac_to_power
double FrequencyGrid< angularGrid >::lin_fac_to_power
Definition at line 315 of file frequency_grid.hpp.
number_of_gridpoints
int FrequencyGrid< angularGrid >::number_of_gridpoints
essential grid parameters:
Definition at line 286 of file frequency_grid.hpp.
number_of_intervals
int FrequencyGrid< angularGrid >::number_of_intervals
Definition at line 290 of file frequency_grid.hpp.
power
double FrequencyGrid< angularGrid >::power
Definition at line 292 of file frequency_grid.hpp.
purely_positive
bool FrequencyGrid< angularGrid >::purely_positive
Definition at line 303 of file frequency_grid.hpp.
quad_fac_recip
double FrequencyGrid< angularGrid >::quad_fac_recip
Definition at line 314 of file frequency_grid.hpp.
recip_power
double FrequencyGrid< angularGrid >::recip_power
Definition at line 293 of file frequency_grid.hpp.
spacing_auxiliary_gridpoint
double FrequencyGrid< angularGrid >::spacing_auxiliary_gridpoint
Definition at line 309 of file frequency_grid.hpp.
t_lower
double FrequencyGrid< angularGrid >::t_lower
Definition at line 307 of file frequency_grid.hpp.
t_upper
double FrequencyGrid< angularGrid >::t_upper
auxiliary grid parameters:
Definition at line 306 of file frequency_grid.hpp.
type
char FrequencyGrid< angularGrid >::type
grid identifier:
Definition at line 301 of file frequency_grid.hpp.
w_center
freqType FrequencyGrid< angularGrid >::w_center = 0
Definition at line 289 of file frequency_grid.hpp.
w_lower
double FrequencyGrid< angularGrid >::w_lower
Definition at line 288 of file frequency_grid.hpp.
w_upper
double FrequencyGrid< angularGrid >::w_upper
Definition at line 287 of file frequency_grid.hpp.
The documentation for this class was generated from the following files:
frequency_grid.hpp
frequency_grid.c++