SIAM-Keldysh-mfRG: minimizer.hpp File Reference
minimizer.hpp File Reference
#include <stdio.h>
#include <gsl/gsl_errno.h>
#include <gsl/gsl_math.h>
#include <gsl/gsl_min.h>
#include <gsl/gsl_multimin.h>
#include "mpi_setup.hpp"
#include "util.hpp"
Functions
template<typename CostFunction >
auto costval (double x, void *params) -> double
template<typename CostFunction >
auto costval_nD (const gsl_vector *v, void *params) -> double
template<typename CostFunction >
void minimizer (CostFunction &cost, double &a, double &m, double &b, int max_iter=10, const bool verbose=false, const bool superverbose=false, double epsabs=0.0, double epsrel=0.01)
template<typename CostFunction >
vec< double > minimizer_nD (CostFunction &cost, const vec< double > &start_params, const double ini_stepsize, int max_iter=100, const bool verbose=false, const bool superverbose=false, double epsabs=0.1, double epsrel=0.01)
Function Documentation
costval()
template<typename CostFunction > auto costval (double x, void * params) -> double
Definition at line 14 of file minimizer.hpp.
{
    CostFunction cost = *(CostFunction*) params;
    double costval = cost(x);
    return costval;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and costval().
Referenced by costval(), and costval_nD().
costval_nD()
template<typename CostFunction > auto costval_nD (const gsl_vector * v, void * params) -> double
Definition at line 20 of file minimizer.hpp.
{
    CostFunction cost = *(CostFunction*) params;
    size_t size = v->size;
    //std::vector<double> input(size);
    //for (size_t i = 0; i < v->size; i++) input[i] = gsl_vector_get(v, i);
    std::vector<double> input(v->data, v->data + size);
    double costval = cost(input);
    return costval;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and costval().
minimizer()
template<typename CostFunction > void minimizer (CostFunction & cost, double & a, double & m, double & b, int max_iter = 10, const bool verbose = false, const bool superverbose = false, double epsabs = 0.0, double epsrel = 0.01)
Wrapper for GSl minimizer (minimization in 1D)
Parameters
a left bound of interval
m initial guess of parameter
b right bound of interval
cost cost function (to be minimized)
max_iter maximal number iterations
Definition at line 39 of file minimizer.hpp.
{
    if (verbose and mpi_world_rank() == 0) std::cout << "-----   Starting minimizer   -----\n";
    int status;
    int iter = 0;
    const gsl_min_fminimizer_type *T;
    gsl_min_fminimizer *s;
    gsl_function F;
    // make sure that minimizer gets nice values
    if (verbose and mpi_world_rank() == 0) std::cout << "Make sure that minimizer gets nice intervals: \n";
    double costa, costb, costm;
    while (true) {
        costa = cost(a);
        costb = cost(b);
        costm = cost(m);
        if (verbose and mpi_world_rank() == 0) printf( "a: %.3f  --  m: %.3f  --  b: %.3f \t with costa: %.3e  --  costm: %.3e  --  costb: %.3e\n", a, m ,b, costa, costm, costb);
        //print("curvature for a\t m\t  b: \t: ", costa, "\t", costm, "\t", costb, "\n");
        if (costa > costm  and costb > costm) break; // If m gives smaller cost than left and right interval bound --> Ok. Minimizer can find a minimum.
        else if (costb > costa) {    // if left interval bound gives smaller cost than m, shift the interval to the left (shrinking parameter range)
            b = m; m = a; a /= 2.;
            //utils::print("shrink", true);
        }
        else if (costa > costb){    // if right interval bound gives smaller cost than m, shift the interval to the right (growing parameter range)
            a = m; m = b; b *= 1.5;
            //utils::print("grow", true);
        }
        else if (std::abs(costa - costm) < 1e-10) {
            utils::print("difference in costa and costm: ", std::abs(costb- costm), true);
            double temp = (a + m) / 2.;
            double cost_temp = cost(temp);
            if (cost_temp <costa)
            {b = m; m = temp;}
            else {
                utils::print("WARNING!: Minimum not unique!!!\n\n");
                return; // ignore the problem
                //throw std::runtime_error("Minimum not unique."); // else: there are local minima on the left AND the right of the interval --> non-trivial choice
            }
        }
        else if (std::abs(costb- costm) < 1e-10) {
            utils::print("difference in costb and costm: ", std::abs(costb- costm), true);
            double temp = (m + b) / 2.;
            double cost_temp = cost(temp);
            if (cost_temp <costb)
            {a = m; m = temp;}
            else {
                utils::print("WARNING!: Minimum not unique!!!");
                return;
                //throw std::runtime_error("Minimum not unique.");
            }
        }
        else throw std::runtime_error("Uncaught if-else case in minimizer");
        // if both left and right interval bounds give smaller cost than m, prefer shift to the left (shrinking parameter range)
    }
    F.function = &costval<CostFunction>;
    F.params = &cost;
    T = gsl_min_fminimizer_brent;       // best convergence: gsl_min_fminimizer_brent,  alternatively:  gsl_min_fminimizer_quad_golden
    s = gsl_min_fminimizer_alloc (T);
    gsl_min_fminimizer_set (s, &F, m, a, b);
    if (verbose and mpi_world_rank() == 0) {
        printf("using %s method\n",
               gsl_min_fminimizer_name(s));
    }
    if(superverbose and mpi_world_rank() == 0) {
        printf("%5s [%9s, %9s] %9s %10s %9s\n",
               "iter", "lower", "upper", "min",
               "err", "err(est)");
        printf("%5d [%.7f, %.7f] %.7f %.7f\n",
               iter, a, b,
               m, b - a);
    }
    do
    {
        iter++;
        status = gsl_min_fminimizer_iterate (s);
        m = gsl_min_fminimizer_x_minimum (s);
        a = gsl_min_fminimizer_x_lower (s);
        b = gsl_min_fminimizer_x_upper (s);
        status = gsl_min_test_interval (a, b, epsabs, epsrel);
        if (superverbose and mpi_world_rank() == 0) {
            printf("%5d [%.7f, %.7f] "
                   "%.7f %.7f\n",
                   iter, a, b,
                   m, b - a);
        }
        if (verbose and mpi_world_rank() == 0 and status == GSL_SUCCESS) {
            printf("Converged after %5d iterations:\n", iter);
            printf("interval: [%.7f, %.7f] "
                   "\t result: %.7f\n",
                   a, b,
                   m);
        }
    }
    while (status == GSL_CONTINUE && iter < max_iter);
    gsl_min_fminimizer_free (s);
    if (verbose and mpi_world_rank() == 0) std::cout << "-----   Exit minimizer   -----\n";
    //return status;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), mpi_world_rank(), and utils::print().
Referenced by dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::optimize_grid().
minimizer_nD()
template<typename CostFunction > vec< double > minimizer_nD (CostFunction & cost, const vec< double > & start_params, const double ini_stepsize, int max_iter = 100, const bool verbose = false, const bool superverbose = false, double epsabs = 0.1, double epsrel = 0.01)
Definition at line 170 of file minimizer.hpp.
{
    if (verbose and mpi_world_rank() == 0) std::cout << "-----   Starting minimizer   -----\n";
    const gsl_multimin_fminimizer_type *T = gsl_multimin_fminimizer_nmsimplex2; // options: gsl_multimin_fminimizer_nmsimplex, gsl_multimin_fminimizer_nmsimplex2
    gsl_multimin_fminimizer *s = NULL;
    gsl_vector *ss, *x; // ss: stepsize, x: starting point
    gsl_multimin_function minex_func;
    int iter = 0;
    int status;
    double size;
    size_t n_params = start_params.size();
    /* Starting point */
    x = gsl_vector_alloc (n_params);
    for (size_t i = 0; i < n_params; i++) { gsl_vector_set (x, i, start_params[i]);}
    /* Set initial step sizes to 1 */
    ss = gsl_vector_alloc (n_params);
    gsl_vector_set_all (ss, ini_stepsize);
    /* Initialize method and iterate */
    minex_func.n = n_params;   // number of optimization parameters
    minex_func.f = &costval_nD<CostFunction>;
    minex_func.params = &cost;
    s = gsl_multimin_fminimizer_alloc (T, n_params);
    gsl_multimin_fminimizer_set (s, &minex_func, x, ss);
    do
    {
        iter++;
        status = gsl_multimin_fminimizer_iterate(s);
        if (status)
            break;
        size = gsl_multimin_fminimizer_size (s);
        status = gsl_multimin_test_size (size, epsabs);
        if (status == GSL_SUCCESS and verbose and mpi_world_rank() == 0)
        {
            printf ("converged to minimum after iteration %5d: \n\t --> param0: %10.3e ,param1: %10.3e \t cost() = %7.3e simplex size = %.3f\n",
                    iter,
                    gsl_vector_get (s->x, 0),
                    gsl_vector_get (s->x, 1),
                    s->fval, size);
        }
        if (superverbose and mpi_world_rank() == 0) {
            // verbose output currently only for 2 parameters
            printf ("iteration %5d --> param0: %10.3e ,param1: %10.3e f() = %7.3e size = %.3f\n",
                    iter,
                    gsl_vector_get (s->x, 0),
                    gsl_vector_get (s->x, 1),
                    s->fval, size);
        }
    }
    while (status == GSL_CONTINUE && iter < max_iter);
    vec<double> result_params(n_params);
    for (size_t i = 0; i < n_params; i++) {result_params[i] = gsl_vector_get (s->x, i);}
    gsl_vector_free(x);
    gsl_vector_free(ss);
    gsl_multimin_fminimizer_free (s);
    //return status;
    return result_params;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and mpi_world_rank().
Referenced by dataBuffer< Q, k, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type, inter, >::optimize_grid().