SIAM-Keldysh-mfRG: flowgrid Namespace Reference
flowgrid Namespace Reference
Classes
class exp_parametrization
class linear_parametrization
class log_parametrization
class sqrt_parametrization
Functions
void add_points_to_Lambda_grid (std::vector< double > &grid, const std::vector< double > &lambda_checkpoints)
rvec get_Lambda_checkpoints (const std::vector< double > &Us, const fRG_config &config)
double log_substitution (double x)
double log_resubstitution (double x)
double sq_substitution (double x)
double sq_resubstitution (double x)
rvec construct_flow_grid (double x_fin, double x_ini, double subst(double x), double resubst(double x), unsigned int N_ODE, const std::vector< double > &lambda_checkpoints)
rvec flow_grid_step_sizes (const rvec &x_vals)
Function Documentation
add_points_to_Lambda_grid()
void flowgrid::add_points_to_Lambda_grid (std::vector< double > & grid, const std::vector< double > & lambda_checkpoints)
Definition at line 3 of file flow_grid.c++.
{
    for (auto y : lambda_checkpoints){
        if(y<0){
            break;
        }
        auto it = grid.begin();
        auto pos = std::find_if(it, grid.end(), [y](double x) {return x<y;});
        if (y<=grid[0])  grid.insert(pos, y);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by construct_flow_grid().
construct_flow_grid()
rvec flowgrid::construct_flow_grid (double x_fin, double x_ini, double substdouble x, double resubstdouble x, unsigned int N_ODE, const std::vector< double > & lambda_checkpoints)
Definition at line 52 of file flow_grid.c++.
{
    const double X_ini = subst(x_ini), X_fin = subst(x_fin); // substitute limits
    const double dX = (X_fin-X_ini)/((double)N_ODE);         // equidistant grid in substituted variable X
    // create non-linear integration grid using substitution
    rvec x_vals (N_ODE+1);                      // integration values
    x_vals[0] = x_ini;                          // start with initial value
    for (unsigned int i=1; i<=N_ODE; ++i) {
        x_vals[i] = resubst(X_ini + i*dX);      // value i
    }
    add_points_to_Lambda_grid(x_vals, lambda_checkpoints);      // add points at interesting values
    return x_vals;
}
References add_points_to_Lambda_grid(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by ode_solver().
flow_grid_step_sizes()
rvec flowgrid::flow_grid_step_sizes (const rvec & x_vals)
Definition at line 69 of file flow_grid.c++.
{
    rvec x_diffs (x_vals.size()-1);
    for (unsigned int i=1; i<=x_diffs.size(); i++){
        x_diffs[i-1] = x_vals[i] - x_vals[i-1]; // step size i
    }
    return x_diffs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_Lambda_checkpoints()
rvec flowgrid::get_Lambda_checkpoints (const std::vector< double > & Us, const fRG_config & config)
Definition at line 14 of file flow_grid.c++.
{
    rvec Lambda_CPs;
#if REG == 2
    size_t n = Us.size();
    for (unsigned int i = 0; i < n; i++){
        double y = 2.0 * config.U / Us[i] - config.Gamma;   //Value of Lambda for given Gamma, that ensures that energy scale U/Delta corresponds with available NRG data
        if(y<0){
            break;
        }
        if (y<=Lambda_ini) Lambda_CPs.push_back(y);
    }
#elif REG == 5
    Lambda_CPs = Us;
#endif
    return Lambda_CPs;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), fRG_config::Gamma, Lambda_ini, and fRG_config::U.
Referenced by run_parquet().
log_resubstitution()
double flowgrid::log_resubstitution (double x)
Definition at line 36 of file flow_grid.c++.
{
    return Lambda_scale*(pow(10, x) - 1);
    //return 5*x/sqrt(1-x*x);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and Lambda_scale.
log_substitution()
double flowgrid::log_substitution (double x)
Definition at line 32 of file flow_grid.c++.
{
    return log10(1 + x/Lambda_scale);
    //return x/sqrt(5*5+x*x);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and Lambda_scale.
sq_resubstitution()
double flowgrid::sq_resubstitution (double x)
Definition at line 46 of file flow_grid.c++.
{
    double a = 5.;
    return a*pow(x, 2) / sqrt(1. - pow(x, 2));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
sq_substitution()
double flowgrid::sq_substitution (double x)
Definition at line 41 of file flow_grid.c++.
{
    double a = 5.;
    return sqrt((sqrt(pow(x, 4) + 4.*pow(a*x, 2)) - pow(x, 2))/2.)/a;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().