SIAM-Keldysh-mfRG: Keldysh_symmetries.c++ File Reference
Keldysh_symmetries.c++ File Reference
#include "Keldysh_symmetries.hpp"
Functions
auto iK_to_alphas (int index) -> std::array< int, 4 >
auto alphas_to_iK (const std::array< int, 4 > &alphas) -> int
auto indices_sum (int i0, int i2, const char channel) -> std::vector< int >
Function Documentation
alphas_to_iK()
auto alphas_to_iK (const std::array< int, 4 > & alphas) -> int
Definition at line 20 of file Keldysh_symmetries.c++.
{
    int base = 1;
    int iK = 0;
    for (int i = 0; i < 4; i++) {
        iK += (alphas[3-i] - 1) * base;
        base *= 2;
    }
    //alphas[0] = (index % 16)/8 + 1;
    //alphas[1] = (index % 8)/4 + 1;
    //alphas[2] = (index % 4)/2 + 1;
    //alphas[3] = (index % 2) + 1;
    assert(iK>=0);
    return iK;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by T1(), T2(), and TC().
iK_to_alphas()
auto iK_to_alphas (int index) -> std::array<int,4>
Definition at line 4 of file Keldysh_symmetries.c++.
{
    std::array<int,4> alphas;
    int base = 8;
    for (int i = 0; i < 4; i++) {
        alphas[i] = index / base;
        index -= alphas[i]*base;
        base /=2;
        alphas[i]++;
    }
    //alphas[0] = (index % 16)/8 + 1;
    //alphas[1] = (index % 8)/4 + 1;
    //alphas[2] = (index % 4)/2 + 1;
    //alphas[3] = (index % 2) + 1;
    return alphas;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by indices_sum(), T1(), T2(), and TC().
indices_sum()
auto indices_sum (int i0, int i2, const char channel) -> std::vector< int >
Function that returns, for an input i0, i2 in 0...15, the two Keldysh indices of the left [0] and right [1] vertices of a bubble in a given channel.
Parameters
i0 : Keldysh index of the lhs of a derivative equation for the vertex
i2 : Keldysh index of the non-zero components of the bubble propagators (takes values in a set of size 9)
channel : channel of the bubble
Returns
: Vector of two Keldysh indices for the left [0] and right [1] vertex in a bubble
Definition at line 35 of file Keldysh_symmetries.c++.
{
    std::vector<int> indices ({0, 0});           // Return std::vector, already correct for Matsubara
    if (KELDYSH){
        std::array<int,4> alphas_i0 = iK_to_alphas(i0);   // Calculate the alphas of each input. Refer to these alphas as (1'2'|12)
        std::array<int,4> alphas_i2 = iK_to_alphas(i2);   // Calculate the alphas of each input. Refer to these alphas as (34|3'4')
        //Distribute the alphas of indices i0 and i2 into i1 and i3
        switch (channel) {
            case 'a':
                indices[0] = 8*(alphas_i0[0]-1) + 4*(alphas_i2[3]-1) + 2*(alphas_i2[0]-1) + 1*(alphas_i0[3]-1);  // i1 = (1'4'|32)
                indices[1] = 8*(alphas_i2[2]-1) + 4*(alphas_i0[1]-1) + 2*(alphas_i0[2]-1) + 1*(alphas_i2[1]-1);  // i3 = (3'2'|14)
                break;
            case 'p':
                indices[0] = 8*(alphas_i0[0]-1) + 4*(alphas_i0[1]-1) + 2*(alphas_i2[0]-1) + 1*(alphas_i2[1]-1);  // i1 = (1'2'|34)
                indices[1] = 8*(alphas_i2[2]-1) + 4*(alphas_i2[3]-1) + 2*(alphas_i0[2]-1) + 1*(alphas_i0[3]-1);  // i3 = (3'4'|12)
                break;
            case 't':
                indices[0] = 8*(alphas_i2[3]-1) + 4*(alphas_i0[1]-1) + 2*(alphas_i2[0]-1) + 1*(alphas_i0[3]-1);  // i1 = (4'2'|32)
                indices[1] = 8*(alphas_i0[0]-1) + 4*(alphas_i2[2]-1) + 2*(alphas_i0[2]-1) + 1*(alphas_i2[1]-1);  // i3 = (1'3'|14)
                break;
            default:;
        }
    }
    return indices;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), iK_to_alphas(), and KELDYSH.
Referenced by asymp_corrections_bubble(), Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::compute_vertices(), and Integrand< diag_class, channel, spin, Q, vertexType_left, vertexType_right, Bubble_Object, return_type >::precompute_vertices().