SIAM-Keldysh-mfRG: Adapt< Integrand, Q > Struct Template Reference
Adapt< Integrand, Q > Struct Template Reference
#include <integrator_NR.hpp>
Public Member Functions
Adapt (double tol_in, const Integrand &integrand_in)
auto integrate (double a, double b) -> Q
auto integrate (double a, double b, Q fa, Q fb, Q is) -> Q
Public Attributes
double TOL
double tolerance_rel
const double tolerance_abs = std::numeric_limits<double>::epsilon()
const Integrand & integrand
Static Public Attributes
static const double alpha = sqrt(2./3.)
static const double beta = 1./sqrt(5.)
static const double x1 = 0.942882415695480
static const double x2 = 0.641853342345781
static const double x3 = 0.236383199662150
static const double nodes [12] = {0, -x1, -alpha, -x2, -beta, -x3, 0.0, x3, beta, x2, alpha, x1}
Detailed Description
template<typename Integrand, typename Q = std::result_of_t<Integrand(double)>>
struct Adapt< Integrand, Q >
Adaptive integration using 4-point Gauss-Lobatto rule with 7-point Gauss-Kronrod extension, and 13-point Gauss-Kronrod as error estimate.
Definition at line 13 of file integrator_NR.hpp.
Constructor & Destructor Documentation
Adapt()
template<typename Integrand , typename Q = std::result_of_t<Integrand(double)>> Adapt< Integrand, Q >::Adapt (double tol_in, const Integrand & integrand_in) inline
Definition at line 20 of file integrator_NR.hpp.
                                                        : TOL(tol_in), integrand(integrand_in) {
        if (TOL < 10.*tolerance_abs)  // if absolute tolerance is smaller than 10 * machine precision,
            TOL = 10.*tolerance_abs;  // set it to 10 * machine precision
    }
References Adapt< Integrand, Q >::TOL, and Adapt< Integrand, Q >::tolerance_abs.
Member Function Documentation
integrate() [1/2]
template<typename Integrand , typename Q > auto Adapt< Integrand, Q >::integrate (double a, double b) -> Q
Integrate integrand from a to b.
Definition at line 59 of file integrator_NR.hpp.
{
    double m, h, err_i1, err_i2, r, x[13];
    Q i1, i2, is, f[13];
    m = 0.5*(b+a);  // center of the interval
    h = 0.5*(b-a);  // half width of the interval
    x[0]  = a;  // left boundary
    x[12] = b;  // right boundary
    f[0]  = integrand(x[0]);  // value at the left boundary
    f[12] = integrand(x[12]);  // value at the right boundary
    for (int i=1; i<12; i++) {
        x[i] = m + nodes[i] * h;  // positions of the 13 Gauss-Kronrod nodes
        f[i] = integrand(x[i]);   // integrand values at the 13 Gauss-Kronrod nodes
    }
    // use 4-point Gauss-Lobatto rule as a first estimate
    i1 = Gauss_Lobatto_4(h, f[0], f[4], f[8], f[12]);
    // use 7-point Gauss-Kronrod rule as a second estimate
    i2 = Gauss_Kronrod_7(h, f[0], f[2], f[4], f[6], f[8], f[10], f[12]);
    // use 13-point Gauss-Kronrod rule as error estimate
    is = Gauss_Kronrod_13(h, f[0], f[1], f[2], f[3], f[4], f[5], f[6], f[7], f[8], f[9], f[10], f[11], f[12]);
    err_i1 = myabs(i1 - is);  // error of first estimate compared to 13-point Gauss-Kronrod
    err_i2 = myabs(i2 - is);  // error of second estimate compared to 13-point Gauss-Kronrod
    // scale tolerance: if error of i2 is smaller than error of i1 (integral is converging), increase tolerance.
    r = (err_i1 != 0.0) ? err_i2/err_i1 : 1.0;          // scaling factor r
    tolerance_rel = (r > 0.0 && r < 1.0) ? TOL / r : TOL;   // if 0 < r < 1, increase relative tolerance by factor 1/r
    // if error estimate is zero, set to interval width to avoid infinite recursion
    if (myabs(is) < 1e-20 || b <= a)
        return myzero<Q>();
    // If difference between first and second estimate and second and 13-point estimate is already smaller than absolute
    // or relative tolerance, return second estimate, else subdivide interval.
    // Subdivide also if the integral value is exactly zero, to avoid accidental zero result due to the choice of
    // evaluation points.
    if ((myabs(i2 - i1) < std::max(tolerance_abs, tolerance_rel * myabs(is))
      && myabs(i2 - is) < std::max(tolerance_abs, tolerance_rel * myabs(is)))
        //&& i2 != 0. // shouldn't need this safety check any more if interval is split into subintervals
        || b-a < tolerance_abs) // do not split if the interval is very small
        return i2;
    else
        return integrate(x[0],  x[2],  f[0],  f[2],  is)  // subdivide interval
             + integrate(x[2],  x[4],  f[2],  f[4],  is)
             + integrate(x[4],  x[6],  f[4],  f[6],  is)
             + integrate(x[6],  x[8],  f[6],  f[8],  is)
             + integrate(x[8],  x[10], f[8],  f[10], is)
             + integrate(x[10], x[12], f[10], f[12], is);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Gauss_Kronrod_13(), Gauss_Kronrod_7(), Gauss_Lobatto_4(), and myabs().
Referenced by Adapt_semiInfinitUpper< Integrand >::integrate(), Adapt_semiInfinitLower< Integrand >::integrate(), integrator(), integrator(), integrator(), and integrator().
integrate() [2/2]
template<typename Integrand , typename Q > auto Adapt< Integrand, Q >::integrate (double a, double b, Q fa, Q fb, Q is) -> Q
Helper function for recursion: Integrate integrand in subinterval [a, b], reusing the boundary values fa, fb and given error estimate is.
Definition at line 115 of file integrator_NR.hpp.
{
    double m, h, x[5];
    Q i1, i2, f[5];
    //double m, h, mll, ml, mr, mrr;
    //Q fmll, fml, fm, fmr, fmrr, i2, i1;
    m = 0.5*(a+b);  // center of the interval
    h = 0.5*(b-a);  // half width of the interval
    // positions of the Gauss-Kronrod nodes
    x[0] = m - alpha * h;
    x[1] = m - beta * h;
    x[2] = m;
    x[3] = m + beta * h;
    x[4] = m + alpha * h;
    for (int i=0; i<5; ++i)
        f[i] = integrand(x[i]);  // integrand values at the Gauss-Kronrod nodes
    // first and second estimate using 4-point Gauss-Lobatto and 7-point Gauss-Kronrod
    i1 = Gauss_Lobatto_4(h, fa, f[1], f[3], fb);
    i2 = Gauss_Kronrod_7(h, fa, f[0], f[1], f[2], f[3], f[4], fb);
    // if difference between first and second estimate is smaller than absolute or relative tolerance_rel,
    // or nodes lie outside the interval, return second estimate, else subdivide interval
    if (myabs(i2 - i1) < std::max(tolerance_abs, tolerance_rel * myabs(is)) || x[0] < a || b < x[4])
        return i2;
    else
        return integrate(a,    x[0], fa,   f[0], is)  // subdivide interval
             + integrate(x[0], x[1], f[0], f[1], is)
             + integrate(x[1], x[2], f[1], f[2], is)
             + integrate(x[2], x[3], f[2], f[3], is)
             + integrate(x[3], x[4], f[3], f[4], is)
             + integrate(x[4], b,    f[4], fb,   is);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Gauss_Kronrod_7(), Gauss_Lobatto_4(), and myabs().
Member Data Documentation
alpha
template<typename Integrand , typename Q > const double Adapt< Integrand, Q >::alpha = sqrt(2./3.) static
Definition at line 17 of file integrator_NR.hpp.
beta
template<typename Integrand , typename Q > const double Adapt< Integrand, Q >::beta = 1./sqrt(5.) static
Definition at line 17 of file integrator_NR.hpp.
integrand
template<typename Integrand , typename Q = std::result_of_t<Integrand(double)>> const Integrand& Adapt< Integrand, Q >::integrand
Definition at line 18 of file integrator_NR.hpp.
nodes
template<typename Integrand , typename Q > const double Adapt< Integrand, Q >::nodes = {0, -x1, -alpha, -x2, -beta, -x3, 0.0, x3, beta, x2, alpha, x1} static
Definition at line 17 of file integrator_NR.hpp.
TOL
template<typename Integrand , typename Q = std::result_of_t<Integrand(double)>> double Adapt< Integrand, Q >::TOL
Definition at line 15 of file integrator_NR.hpp.
Referenced by Adapt< Integrand, Q >::Adapt().
tolerance_abs
template<typename Integrand , typename Q = std::result_of_t<Integrand(double)>> const double Adapt< Integrand, Q >::tolerance_abs = std::numeric_limits<double>::epsilon()
Definition at line 16 of file integrator_NR.hpp.
Referenced by Adapt< Integrand, Q >::Adapt().
tolerance_rel
template<typename Integrand , typename Q = std::result_of_t<Integrand(double)>> double Adapt< Integrand, Q >::tolerance_rel
Definition at line 15 of file integrator_NR.hpp.
x1
template<typename Integrand , typename Q > const double Adapt< Integrand, Q >::x1 = 0.942882415695480 static
Definition at line 17 of file integrator_NR.hpp.
x2
template<typename Integrand , typename Q > const double Adapt< Integrand, Q >::x2 = 0.641853342345781 static
Definition at line 17 of file integrator_NR.hpp.
x3
template<typename Integrand , typename Q > const double Adapt< Integrand, Q >::x3 = 0.236383199662150 static
Definition at line 17 of file integrator_NR.hpp.
The documentation for this struct was generated from the following file:
integrator_NR.hpp