SIAM-Keldysh-mfRG: bubble_corrections.c++ File Reference
bubble_corrections.c++ File Reference
#include "bubble_corrections.hpp"
Functions
template<>
auto correctionFunctionBubbleAT_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<>
auto correctionFunctionBubbleAT_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<>
auto correctionFunctionBubbleP_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
template<>
auto correctionFunctionBubbleP_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Function Documentation
correctionFunctionBubbleAT_REG2_Keldysh()
template<> auto correctionFunctionBubbleAT_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 4 of file bubble_corrections.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleAT_REG2_Matsubara_NoPHS()
template<> auto correctionFunctionBubbleAT_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 13 of file bubble_corrections.c++.
{
    utils::print("Error! Computations without particle hole symmetry require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleP_REG2_Keldysh()
template<> auto correctionFunctionBubbleP_REG2_Keldysh (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 22 of file bubble_corrections.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().
correctionFunctionBubbleP_REG2_Matsubara_NoPHS()
template<> auto correctionFunctionBubbleP_REG2_Matsubara_NoPHS (double w, double vmin, double vmax, double eps_p, double Delta, double Lambda, double eta_1, double eta_2, bool diff) -> double
Definition at line 31 of file bubble_corrections.c++.
{
    utils::print("Error! Computations without particle hole symmetry require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References utils::print().