SIAM-Keldysh-mfRG: GeneralVertex< Q, symmtype, differentiated > Class Template Reference
GeneralVertex< Q, symmtype, differentiated > Class Template Reference
#include <vertex.hpp>
Public Types
using base_type = Q
Public Member Functions
bool is_differentiated () const
GeneralVertex ()
GeneralVertex (const double Lambda_in, const fRG_config &config)
GeneralVertex (const double Lambda_in, const fRG_config &config, const vertex_nondiff_t &vertex_nondiff)
template<typename ... Types>
GeneralVertex (const double Lambda_in, const fRG_config &config, const Types &... t)
GeneralVertex (const fullvert< Q > &vertex_in)
GeneralVertex (const fullvert< Q > &vertex_in, const vertex_nondiff_t &vertex_nondiff)
GeneralVertex (const fullvert< Q > &half1, const fullvert< Q > &half2, const vertex_nondiff_t &vertex_nondiff)
void center_frequency_grids (const double hartree_plus_epsilon)
fullvert< Q > & half1 ()
fullvert< Q > & half2 ()
const fullvert< Q > & half1 () const
const fullvert< Q > & half2 () const
const vertex_nondiff_t & get_vertex_nondiff () const
irreducible< Q > & irred ()
rvert< Q > & avertex ()
rvert< Q > & pvertex ()
rvert< Q > & tvertex ()
const irreducible< Q > & irred () const
const rvert< Q > & avertex () const
const rvert< Q > & pvertex () const
const rvert< Q > & tvertex () const
const rvert< Q > & get_rvertex (const char r) const
rvert< Q > & get_rvertex (const char r)
template<char ch_bubble>
auto value (const VertexInput &input) const -> Q
template<char ch_bubble>
auto left_same_bare (const VertexInput &input) const -> Q
template<char ch_bubble>
auto right_same_bare (const VertexInput &input) const -> Q
template<char ch_bubble>
auto left_diff_bare (const VertexInput &input) const -> Q
template<char ch_bubble>
auto right_diff_bare (const VertexInput &input) const -> Q
template<int spin, char ch_bubble, typename result_type >
auto value_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, typename result_type >
auto value_symmetry_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, typename result_type >
auto value_minus_gamma0_symmetry_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, typename result_type >
auto left_same_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, typename result_type >
auto right_same_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, typename result_type >
auto left_diff_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, typename result_type >
auto right_diff_bare_symmetry_expanded (const VertexInput &input) const -> result_type
template<int spin, char ch_bubble, char channel_vertex, K_class k, typename result_type >
auto get_w_r_value_symmetry_expanded_nondiff (const VertexInput &input) const -> result_type
double norm ()
double sum_norm (int i)
double norm_K1 (int i)
double norm_K2 (int i)
double norm_K3 (int i)
void set_frequency_grid (const GeneralVertex< Q, symmetric_full, false > &vertex_in)
void update_grid (double Lambda, double hartree_plus_epsilon, const fRG_config &config)
void set_Ir (bool Ir)
void set_only_same_channel (bool only_same_channel)
void initialize (Q val)
void initializeInterpol () const
void set_initializedInterpol (const bool initialized) const
void check_symmetries (const std::string identifier) const
vec< bool > & get_vanishing_component_channel_r (const char channel) const
void swap_vanishing_component_channel_a_and_t () const
void set_to_zero_in_integrand (const char channel, const K_class kClass)
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void symmetry_expand () const
void save_expanded (const std::string &filename_prefix) const
auto operator+= (const GeneralVertex< Q, symmtype, differentiated > &vertex1) -> GeneralVertex< Q, symmtype, differentiated >
auto operator+= (const double alpha) -> GeneralVertex< Q, symmtype, differentiated >
auto operator*= (const GeneralVertex< Q, symmtype, differentiated > &vertex1) -> GeneralVertex< Q, symmtype, differentiated >
auto operator*= (const double &alpha) -> GeneralVertex< Q, symmtype, differentiated >
auto operator-= (const GeneralVertex< Q, symmtype, differentiated > &vertex1) -> GeneralVertex< Q, symmtype, differentiated >
auto operator/= (const GeneralVertex< Q, symmtype, differentiated > &vertex1) -> GeneralVertex< Q, symmtype, differentiated >
Public Attributes
std::vector< fullvert< Q > > vertices_bubbleintegrand
bool vanishing_component_gamma0 = false
vec< bool > vanishing_component_channel_a = {false, false, false, false, false}
vec< bool > vanishing_component_channel_p = {false, false, false, false, false}
vec< bool > vanishing_component_channel_t = {false, false, false, false, false}
Private Types
using vertex_half2_t = std::conditional_t<symmtype == non_symmetric_diffleft or symmtype == non_symmetric_diffright, fullvert<Q>, double>
using vertex_nondiff_t = std::conditional_t<differentiated, GeneralVertex<Q,symmetric_full,false>, double>
Private Member Functions
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void construct_SBE_nondiff_K2 (std::vector< fullvert< Q > > &vertices_expanded_target) const
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void construct_SBE_nondiff_K3_SBE (std::vector< fullvert< Q > > &vertices_expanded_target) const
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void construct_SBE_nondiff_K2b (std::vector< fullvert< Q > > &vertices_expanded_target) const
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void construct_SBE_diff_K2 (std::vector< fullvert< Q > > &vertices_expanded_target, const std::vector< fullvert< Q > > &vertices_expanded_nondiff) const
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void construct_SBE_diff_K3_SBE (std::vector< fullvert< Q > > &vertices_expanded_target, const std::vector< fullvert< Q > > &vertices_expanded_nondiff) const
template<char channel_bubble, bool is_left_vertex, bool need_full_vertex>
void construct_SBE_diff_K2b (std::vector< fullvert< Q > > &vertices_expanded_target, const std::vector< fullvert< Q > > &vertices_expanded_nondiff) const
template<char channel_bubble, bool is_left_vertex>
void symmetry_expand_impl (std::vector< fullvert< Q > > &vertices_expanded_target, const fullvert< Q > &vertex_symmetryreduced_half1, const fullvert< Q > &vertex_symmetryreduced_half2) const
Private Attributes
fullvert< Q > vertex
vertex_half2_t vertex_half2
vertex_nondiff_t vertex_nondifferentiated
Friends
GeneralVertex< Q, symmtype, differentiated > operator+ (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > &rhs)
GeneralVertex< Q, symmtype, differentiated > operator+ (GeneralVertex< Q, symmtype, differentiated > lhs, const double &rhs)
GeneralVertex< Q, symmtype, differentiated > operator* (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > &rhs)
GeneralVertex< Q, symmtype, differentiated > operator* (GeneralVertex< Q, symmtype, differentiated > lhs, const double &rhs)
GeneralVertex< Q, symmtype, differentiated > operator- (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > &rhs)
GeneralVertex< Q, symmtype, differentiated > operator/ (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > &rhs)
Detailed Description
template<typename Q, vertexType symmtype, bool differentiated>
class GeneralVertex< Q, symmtype, differentiated >
symmetric_full and symmetric_r_irred vertex container class (contains only half 1, since half 1 and 2 are related by symmetry) non_symmetric contains the actual vertex in "vertex" and the left-right-symmetry-related one in "vertex_half2" (the latter is needed for reading from the symmetry-reduced sector)
Definition at line 455 of file vertex.hpp.
Member Typedef Documentation
base_type
template<typename Q , vertexType symmtype, bool differentiated> using GeneralVertex< Q, symmtype, differentiated >::base_type = Q
Definition at line 828 of file vertex.hpp.
vertex_half2_t
template<typename Q , vertexType symmtype, bool differentiated> using GeneralVertex< Q, symmtype, differentiated >::vertex_half2_t = std::conditional_t<symmtype == non_symmetric_diffleft or symmtype == non_symmetric_diffright, fullvert<Q>, double> private
Definition at line 457 of file vertex.hpp.
vertex_nondiff_t
template<typename Q , vertexType symmtype, bool differentiated> using GeneralVertex< Q, symmtype, differentiated >::vertex_nondiff_t = std::conditional_t<differentiated, GeneralVertex<Q,symmetric_full,false>, double> private
Definition at line 460 of file vertex.hpp.
Constructor & Destructor Documentation
GeneralVertex() [1/7]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex () inline explicit
Definition at line 836 of file vertex.hpp.
: vertex(0, fRG_config()), vertex_half2(0), vertex_nondifferentiated(0) {}
GeneralVertex() [2/7]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex (const double Lambda_in, const fRG_config & config) inline explicit
Definition at line 837 of file vertex.hpp.
: vertex(fullvert<Q>(Lambda_in, config)), vertex_half2(Lambda_in) {assert(!differentiated);}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
GeneralVertex() [3/7]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex (const double Lambda_in, const fRG_config & config, const vertex_nondiff_t & vertex_nondiff) inline
Definition at line 838 of file vertex.hpp.
: vertex(Lambda_in, config), vertex_half2(Lambda_in), vertex_nondifferentiated(vertex_nondiff) {static_assert(differentiated);}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
GeneralVertex() [4/7]
template<typename Q , vertexType symmtype, bool differentiated> template<typename ... Types> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex (const double Lambda_in, const fRG_config & config, const Types &... t) inline explicit
Definition at line 840 of file vertex.hpp.
: vertex(Lambda_in, config), vertex_half2(Lambda_in), vertex_nondifferentiated(Lambda_in) {assert(false);}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
GeneralVertex() [5/7]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex (const fullvert< Q > & vertex_in) inline explicit
Definition at line 841 of file vertex.hpp.
    : vertex(vertex_in), vertex_half2(0), vertex_nondifferentiated(0) {
        static_assert((symmtype == symmetric_full or symmtype == symmetric_r_irred) and !differentiated , "Only use single-argument constructor for symmetric_full non-differentiated vertex!");}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, and symmetric_r_irred.
GeneralVertex() [6/7]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex (const fullvert< Q > & vertex_in, const vertex_nondiff_t & vertex_nondiff) inline explicit
Definition at line 845 of file vertex.hpp.
            : vertex(vertex_in), vertex_half2(0), vertex_nondifferentiated(vertex_nondiff) {
        static_assert((symmtype == symmetric_full or symmtype == symmetric_r_irred), "Only use two-argument constructor for symmetric_full vertex!");}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, and symmetric_r_irred.
GeneralVertex() [7/7]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated >::GeneralVertex (const fullvert< Q > & half1, const fullvert< Q > & half2, const vertex_nondiff_t & vertex_nondiff) inline
Definition at line 848 of file vertex.hpp.
    : vertex(half1), vertex_half2(half2), vertex_nondifferentiated(vertex_nondiff) {
        static_assert(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright, "Only use two-argument constructor for non_symmetric vertex!");}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
Member Function Documentation
avertex() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::avertex () inline
Definition at line 864 of file vertex.hpp.
{ return vertex.avertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
Referenced by susceptibilities_postprocessing().
avertex() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::avertex () const inline
Definition at line 868 of file vertex.hpp.
{ return vertex.avertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
center_frequency_grids()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::center_frequency_grids (const double hartree_plus_epsilon) inline
Definition at line 852 of file vertex.hpp.
{
        vertex.center_frequency_grids(hartree_plus_epsilon);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
check_symmetries()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::check_symmetries (const std::string identifier) const inline
Definition at line 1055 of file vertex.hpp.
{
        vertex.initializeInterpol();
        vertex.check_symmetries(identifier);
        vertex.set_initializedInterpol(false);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
construct_SBE_diff_K2()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K2 (std::vector< fullvert< Q > > & vertices_expanded_target, const std::vector< fullvert< Q > > & vertices_expanded_nondiff) const inline private
Definition at line 617 of file vertex.hpp.
{
        assert(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1);
        using buffer_type_K2 = typename rvert<Q>::buffer_type_K2;
        // construct K2 from SBE
        if constexpr(channel_bubble != 'a' or need_full_vertex) {
            buffer_type_K2 K2_new_spin0;
            buffer_type_K2 K2_new_spin1;
            // if ispin == 0
            K2_new_spin0 = vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[0]);
            K2_new_spin0+= vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[0]);
            // ispin == 1
            K2_new_spin1 = vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[2]);
            K2_new_spin1+= vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_nondiff[1]);
            K2_new_spin1+= vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[2]);
            K2_new_spin1+= vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[2], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'a'>().K2_symmetry_expanded = K2_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'a'>().K2_symmetry_expanded = K2_new_spin1;
        }
        if constexpr(channel_bubble != 'p' or need_full_vertex) {
            buffer_type_K2 K2_new_spin0;
            buffer_type_K2 K2_new_spin1;
            // ispin == 0
            K2_new_spin0 = vertex.template combine_SBE_to_K2<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[0]);
            K2_new_spin0+= vertex.template combine_SBE_to_K2<channel_bubble,'p',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[0]);
            // ispin == 1
            K2_new_spin1 = vertex.template combine_SBE_to_K2<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[1]);
            K2_new_spin1+= vertex.template combine_SBE_to_K2<channel_bubble,'p',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'p'>().K2_symmetry_expanded = K2_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'p'>().K2_symmetry_expanded = K2_new_spin1;
        }
        if constexpr(channel_bubble != 't' or need_full_vertex) {
            buffer_type_K2 K2_new_spin0;
            buffer_type_K2 K2_new_spin1;
            // ispin == 1
            K2_new_spin1 = vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[1]);
            K2_new_spin1+= vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[1]);
            // ispin == 0
            K2_new_spin0 = vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[2]);
            K2_new_spin0+= vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_nondiff[0]);
            K2_new_spin0+= vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[2]);
            K2_new_spin0+= vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[2], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'t'>().K2_symmetry_expanded = K2_new_spin0;//*(-1.);
            vertices_expanded_target[1].template get_rvertex<'t'>().K2_symmetry_expanded = K2_new_spin1;
        }
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K2_symmetry_expanded = vertices_expanded_target[0].get_rvertex(r).K2_symmetry_expanded;
            vertices_expanded_target[2].get_rvertex(r).K2_symmetry_expanded+= vertices_expanded_target[1].get_rvertex(r).K2_symmetry_expanded;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertex.
construct_SBE_diff_K2b()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K2b (std::vector< fullvert< Q > > & vertices_expanded_target, const std::vector< fullvert< Q > > & vertices_expanded_nondiff) const inline private
Definition at line 733 of file vertex.hpp.
{
        assert(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1);
        using buffer_type_K2b= typename rvert<Q>::buffer_type_K2b;
        // construct K2' from SBE
        if constexpr(channel_bubble != 'a' or need_full_vertex) {
            buffer_type_K2b K2b_new_spin0;
            buffer_type_K2b K2b_new_spin1;
            // ispin==0
            K2b_new_spin0 = vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[0]);
            K2b_new_spin0+= vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[0]);
            // ispin==1
            K2b_new_spin1 = vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[2]);
            K2b_new_spin1+= vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_nondiff[1]);
            K2b_new_spin1+= vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[2]);
            K2b_new_spin1+= vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[2], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'a'>().K2b_symmetry_expanded = K2b_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'a'>().K2b_symmetry_expanded = K2b_new_spin1;
        }
        if constexpr(channel_bubble != 'p' or need_full_vertex) {
            buffer_type_K2b K2b_new_spin0;
            buffer_type_K2b K2b_new_spin1;
            // ispin==0
            K2b_new_spin0 = vertex.template combine_SBE_to_K2b<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[0]);
            K2b_new_spin0+= vertex.template combine_SBE_to_K2b<channel_bubble,'p',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[0]);
            // ispin==1
            K2b_new_spin1 = vertex.template combine_SBE_to_K2b<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[1]);
            K2b_new_spin1+= vertex.template combine_SBE_to_K2b<channel_bubble,'p',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'p'>().K2b_symmetry_expanded = K2b_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'p'>().K2b_symmetry_expanded = K2b_new_spin1;
        }
        if constexpr(channel_bubble != 't' or need_full_vertex) {
            buffer_type_K2b K2b_new_spin0;
            buffer_type_K2b K2b_new_spin1;
            // ispin==1
            K2b_new_spin1 = vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[1]);
            K2b_new_spin1+= vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[1]);
            // ispin == 0
            K2b_new_spin0 = vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[2]);
            K2b_new_spin0+= vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_nondiff[0]);
            K2b_new_spin0+= vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[2]);
            K2b_new_spin0+= vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[2], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'t'>().K2b_symmetry_expanded = K2b_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'t'>().K2b_symmetry_expanded = K2b_new_spin1;
        }
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K2b_symmetry_expanded = vertices_expanded_target[0].get_rvertex(r).K2b_symmetry_expanded;
            vertices_expanded_target[2].get_rvertex(r).K2b_symmetry_expanded+= vertices_expanded_target[1].get_rvertex(r).K2b_symmetry_expanded;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertex.
construct_SBE_diff_K3_SBE()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K3_SBE (std::vector< fullvert< Q > > & vertices_expanded_target, const std::vector< fullvert< Q > > & vertices_expanded_nondiff) const inline private
Definition at line 674 of file vertex.hpp.
{
        assert(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1);
        using buffer_type_K3_SBE = typename rvert<Q>::buffer_type_K3_SBE;
        // construct K3_SBE from SBE
        if constexpr(channel_bubble != 'a' or need_full_vertex) {
            buffer_type_K3_SBE K3_SBE_new_spin0;
            buffer_type_K3_SBE K3_SBE_new_spin1;
            // ispin==0
            K3_SBE_new_spin0 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[0]);
            K3_SBE_new_spin0+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[0]);
            // ispin==1
            K3_SBE_new_spin1 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[2]);
            K3_SBE_new_spin1+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_nondiff[1]);
            K3_SBE_new_spin1+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[2]);
            K3_SBE_new_spin1+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_nondiff[2], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'a'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'a'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin1;
        }
        if constexpr(channel_bubble != 'p' or need_full_vertex) {
            buffer_type_K3_SBE K3_SBE_new_spin0;
            buffer_type_K3_SBE K3_SBE_new_spin1;
            // ispin==0
            K3_SBE_new_spin0 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[0]);
            K3_SBE_new_spin0+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'p',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[0]);
            // ispin==1
            K3_SBE_new_spin1 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[0]);
            K3_SBE_new_spin1+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'p',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'p'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'p'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin1;
        }
        if constexpr(channel_bubble != 't' or need_full_vertex) {
            buffer_type_K3_SBE K3_SBE_new_spin0;
            buffer_type_K3_SBE K3_SBE_new_spin1;
            // ispin==1
            K3_SBE_new_spin1 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_nondiff[1]);
            K3_SBE_new_spin1+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[1], vertices_expanded_target[1]);
            // ispin==0
            K3_SBE_new_spin0 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_nondiff[2]);
            K3_SBE_new_spin0+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_nondiff[0]);
            K3_SBE_new_spin0+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[0], vertices_expanded_target[2]);
            K3_SBE_new_spin0+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_nondiff[2], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'t'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'t'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin1;
        }
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K3_SBE_symmetry_expanded = vertices_expanded_target[0].get_rvertex(r).K3_SBE_symmetry_expanded + vertices_expanded_target[1].get_rvertex(r).K3_SBE_symmetry_expanded;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertex.
construct_SBE_nondiff_K2()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K2 (std::vector< fullvert< Q > > & vertices_expanded_target) const inline private
Definition at line 464 of file vertex.hpp.
{
        assert(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1);
        using buffer_type_K2 = typename rvert<Q>::buffer_type_K2;
        // construct K2 from SBE
        if constexpr(channel_bubble != 'a' or need_full_vertex) {
            buffer_type_K2 K2_new_spin0;
            buffer_type_K2 K2_new_spin1;
            // if ispin == 0
            K2_new_spin0 = vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[0]);
            // ispin == 1
            K2_new_spin1 = vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[2]);
            K2_new_spin1+= vertex.template combine_SBE_to_K2<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'a'>().K2_symmetry_expanded = K2_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'a'>().K2_symmetry_expanded = K2_new_spin1;
        }
        if constexpr(channel_bubble != 'p' or need_full_vertex) {
            buffer_type_K2 K2_new_spin0;
            buffer_type_K2 K2_new_spin1;
            // ispin == 0
            K2_new_spin0 = vertex.template combine_SBE_to_K2<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[0]);
            // ispin == 1
            K2_new_spin1 = vertex.template combine_SBE_to_K2<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'p'>().K2_symmetry_expanded = K2_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'p'>().K2_symmetry_expanded = K2_new_spin1;
        }
        if constexpr(channel_bubble != 't' or need_full_vertex) {
            buffer_type_K2 K2_new_spin0;
            buffer_type_K2 K2_new_spin1;
            // ispin == 1
            K2_new_spin1 = vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[1]);
            // ispin == 0
            K2_new_spin0 = vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[2]);
            K2_new_spin0+= vertex.template combine_SBE_to_K2<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'t'>().K2_symmetry_expanded = K2_new_spin0;//*(-1.);
            vertices_expanded_target[1].template get_rvertex<'t'>().K2_symmetry_expanded = K2_new_spin1;
        }
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K2_symmetry_expanded = vertices_expanded_target[0].get_rvertex(r).K2_symmetry_expanded;
            vertices_expanded_target[2].get_rvertex(r).K2_symmetry_expanded+= vertices_expanded_target[1].get_rvertex(r).K2_symmetry_expanded;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertex.
construct_SBE_nondiff_K2b()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K2b (std::vector< fullvert< Q > > & vertices_expanded_target) const inline private
Definition at line 564 of file vertex.hpp.
{
        assert(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1);
        using buffer_type_K2b= typename rvert<Q>::buffer_type_K2b;
        // construct K2' from SBE
        if constexpr(channel_bubble != 'a' or need_full_vertex) {
            buffer_type_K2b K2b_new_spin0;
            buffer_type_K2b K2b_new_spin1;
            // ispin==0
            K2b_new_spin0 = vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[0]);
            // ispin==1
            K2b_new_spin1 = vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[2]);
            K2b_new_spin1+= vertex.template combine_SBE_to_K2b<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'a'>().K2b_symmetry_expanded = K2b_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'a'>().K2b_symmetry_expanded = K2b_new_spin1;
        }
        if constexpr(channel_bubble != 'p' or need_full_vertex) {
            buffer_type_K2b K2b_new_spin0;
            buffer_type_K2b K2b_new_spin1;
            // ispin==0
            K2b_new_spin0 = vertex.template combine_SBE_to_K2b<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[0]);
            // ispin==1
            K2b_new_spin1 = vertex.template combine_SBE_to_K2b<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'p'>().K2b_symmetry_expanded = K2b_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'p'>().K2b_symmetry_expanded = K2b_new_spin1;
        }
        if constexpr(channel_bubble != 't' or need_full_vertex) {
            buffer_type_K2b K2b_new_spin0;
            buffer_type_K2b K2b_new_spin1;
            // ispin==1
            K2b_new_spin1 = vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[1]);
            // ispin==0
            K2b_new_spin0 = vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[2]);
            K2b_new_spin0+= vertex.template combine_SBE_to_K2b<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'t'>().K2b_symmetry_expanded = K2b_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'t'>().K2b_symmetry_expanded = K2b_new_spin1;
        }
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K2b_symmetry_expanded = vertices_expanded_target[0].get_rvertex(r).K2b_symmetry_expanded;
            vertices_expanded_target[2].get_rvertex(r).K2b_symmetry_expanded+= vertices_expanded_target[1].get_rvertex(r).K2b_symmetry_expanded;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertex.
construct_SBE_nondiff_K3_SBE()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K3_SBE (std::vector< fullvert< Q > > & vertices_expanded_target) const inline private
Definition at line 513 of file vertex.hpp.
{
        assert(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1);
        using buffer_type_K3_SBE = typename rvert<Q>::buffer_type_K3_SBE;
        // construct K3_SBE from SBE
        if constexpr(channel_bubble != 'a' or need_full_vertex) {
            buffer_type_K3_SBE K3_SBE_new_spin0;
            buffer_type_K3_SBE K3_SBE_new_spin1;
            // ispin==0
            K3_SBE_new_spin0 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[0]);
            // ispin==1
            K3_SBE_new_spin1 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[2]);
            K3_SBE_new_spin1+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'a',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_target[1]);
            vertices_expanded_target[0].template get_rvertex<'a'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'a'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin1;
        }
        if constexpr(channel_bubble != 'p' or need_full_vertex) {
            buffer_type_K3_SBE K3_SBE_new_spin0;
            buffer_type_K3_SBE K3_SBE_new_spin1;
            // ispin==0
            K3_SBE_new_spin0 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[0]);
            // ispin==1
            K3_SBE_new_spin1 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'p',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'p'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'p'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin1;
        }
        if constexpr(channel_bubble != 't' or need_full_vertex) {
            buffer_type_K3_SBE K3_SBE_new_spin0;
            buffer_type_K3_SBE K3_SBE_new_spin1;
            // ispin==1
            K3_SBE_new_spin1 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[1], vertices_expanded_target[1]);
            // ispin==0
            K3_SBE_new_spin0 = vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[0], vertices_expanded_target[2]);
            K3_SBE_new_spin0+= vertex.template combine_SBE_to_K3_SBE<channel_bubble,'t',is_left_vertex>(vertices_expanded_target[2], vertices_expanded_target[0]);
            vertices_expanded_target[0].template get_rvertex<'t'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin0;
            vertices_expanded_target[1].template get_rvertex<'t'>().K3_SBE_symmetry_expanded = K3_SBE_new_spin1;
        }
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K3_SBE_symmetry_expanded = vertices_expanded_target[0].get_rvertex(r).K3_SBE_symmetry_expanded + vertices_expanded_target[1].get_rvertex(r).K3_SBE_symmetry_expanded;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), MAX_DIAG_CLASS, SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertex.
get_rvertex() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::get_rvertex (const char r) inline
Definition at line 888 of file vertex.hpp.
{
        switch(r) {
            case 'a':
                return vertex.avertex;
                break;
            case 'p':
                return vertex.pvertex;
                break;
            case 't':
                return vertex.tvertex;
                break;
            default:
                assert(false);
                return vertex.tvertex;
                break;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
get_rvertex() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::get_rvertex (const char r) const inline
Definition at line 871 of file vertex.hpp.
{
        switch(r) {
            case 'a':
                return vertex.avertex;
                break;
            case 'p':
                return vertex.pvertex;
                break;
            case 't':
                return vertex.tvertex;
                break;
            default:
                assert(false);
                return vertex.tvertex;
                break;
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
Referenced by calculate_dGammaC_left_insertion(), calculate_dGammaC_right_insertion(), GeneralVertex< Q, symmtype, differentiated >::symmetry_expand(), and vertexOneLoopFlow().
get_vanishing_component_channel_r()
template<typename Q , vertexType symmtype, bool differentiated> vec< bool > & GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r (const char channel) const inline
Definition at line 1065 of file vertex.hpp.
{
        if (channel == 'a') { return vanishing_component_channel_a;}
        else if (channel == 'p') { return vanishing_component_channel_p;}
        else if (channel == 't') { return vanishing_component_channel_t;}
        else {assert(false);return vanishing_component_channel_a;}
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_a, GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_p, and GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_t.
Referenced by GeneralVertex< Q, symmtype, differentiated >::set_to_zero_in_integrand(), and GeneralVertex< Q, symmtype, differentiated >::symmetry_expand().
get_vertex_nondiff()
template<typename Q , vertexType symmtype, bool differentiated> const vertex_nondiff_t & GeneralVertex< Q, symmtype, differentiated >::get_vertex_nondiff () const inline
Definition at line 861 of file vertex.hpp.
{return vertex_nondifferentiated;}
References GeneralVertex< Q, symmtype, differentiated >::vertex_nondifferentiated.
Referenced by compute_SDE_impl_v3().
get_w_r_value_symmetry_expanded_nondiff()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, char channel_vertex, K_class k, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::get_w_r_value_symmetry_expanded_nondiff (const VertexInput & input) const -> result_type inline
Definition at line 981 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        if constexpr(((symmtype == non_symmetric_diffleft or symmtype == non_symmetric_diffright) and ch_bubble != channel_vertex))  {
            static_assert(differentiated);
            return vertex_nondifferentiated.template get_w_r_value_symmetry_expanded_nondiff<spin,ch_bubble,channel_vertex,k,result_type>(input);
        }
        else if constexpr ((symmtype == symmetric_r_irred and ch_bubble == channel_vertex)) {
            if constexpr (differentiated) {
                return myzero<result_type>();
            }
            else {
                return vertices_bubbleintegrand[spin].irred.template val<result_type>(input.iK, input.i_in, 0);
            }
        }
        else { // symmetric_full
            if constexpr(differentiated) {
                return vertex_nondifferentiated.template get_w_r_value_symmetry_expanded_nondiff<spin,ch_bubble,channel_vertex,k,result_type>(input);
            }
            else {
                assert(spin < vertices_bubbleintegrand.size());
                return vertices_bubbleintegrand[spin].template get_rvertex<channel_vertex>(). template valsmooth_symmetry_expanded<k,result_type>(input)
                    +  vertices_bubbleintegrand[spin].irred.template val<result_type>(input.iK, input.i_in, 0);
            }
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex_nondifferentiated, and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
half1() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> fullvert< Q > & GeneralVertex< Q, symmtype, differentiated >::half1 () inline
Definition at line 857 of file vertex.hpp.
{ return vertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
Referenced by compute_SDE_impl_v3(), State< Q, differentiated >::findBestFreqGrid(), and GeneralVertex< Q, symmtype, differentiated >::symmetry_expand().
half1() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const fullvert< Q > & GeneralVertex< Q, symmtype, differentiated >::half1 () const inline
Definition at line 859 of file vertex.hpp.
{ return vertex; }
References GeneralVertex< Q, symmtype, differentiated >::vertex.
half2() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> fullvert< Q > & GeneralVertex< Q, symmtype, differentiated >::half2 () inline
Definition at line 858 of file vertex.hpp.
{ if constexpr(symmtype==symmetric_full or symmtype==symmetric_r_irred) return vertex; else return vertex_half2;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
Referenced by GeneralVertex< Q, symmtype, differentiated >::symmetry_expand().
half2() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const fullvert< Q > & GeneralVertex< Q, symmtype, differentiated >::half2 () const inline
Definition at line 860 of file vertex.hpp.
{ if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred) return vertex; else return vertex_half2; }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
initialize()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::initialize (Q val) inline
Definition at line 1041 of file vertex.hpp.
{
        vertex.initialize(val);
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.initialize(val);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
Referenced by State< Q, differentiated >::initialize().
initializeInterpol()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::initializeInterpol () const inline
Definition at line 1046 of file vertex.hpp.
{
        vertex.initializeInterpol();
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.initializeInterpol();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
Referenced by GeneralVertex< Q, symmtype, differentiated >::symmetry_expand_impl().
irred() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> irreducible< Q > & GeneralVertex< Q, symmtype, differentiated >::irred () inline
Definition at line 863 of file vertex.hpp.
{ return vertex.irred;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
irred() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const irreducible< Q > & GeneralVertex< Q, symmtype, differentiated >::irred () const inline
Definition at line 867 of file vertex.hpp.
{ return vertex.irred;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
is_differentiated()
template<typename Q , vertexType symmtype, bool differentiated> bool GeneralVertex< Q, symmtype, differentiated >::is_differentiated () const inline
Definition at line 829 of file vertex.hpp.
{return differentiated;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
left_diff_bare()
template<typename Q , vertexType symmtype, bool differentiated> template<char ch_bubble> auto GeneralVertex< Q, symmtype, differentiated >::left_diff_bare (const VertexInput & input) const -> Q inline
Definition at line 919 of file vertex.hpp.
{
        if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred ) return vertex.template left_diff_bare<ch_bubble,symmtype==symmetric_r_irred,symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright>(input);
        else                              return vertex.template left_diff_bare<ch_bubble,symmtype==symmetric_r_irred,symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright>(input, vertex_half2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
left_diff_bare_symmetry_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::left_diff_bare_symmetry_expanded (const VertexInput & input) const -> result_type inline
Definition at line 968 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        return vertices_bubbleintegrand[spin].template left_diff_bare_symmetry_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred,symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright>(input);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
left_same_bare()
template<typename Q , vertexType symmtype, bool differentiated> template<char ch_bubble> auto GeneralVertex< Q, symmtype, differentiated >::left_same_bare (const VertexInput & input) const -> Q inline
Definition at line 911 of file vertex.hpp.
{
        if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred ) return vertex.template left_same_bare<ch_bubble,symmtype==symmetric_r_irred>(input);
        else                              return vertex.template left_same_bare<ch_bubble,symmtype==symmetric_r_irred>(input, vertex_half2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
left_same_bare_symmetry_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::left_same_bare_symmetry_expanded (const VertexInput & input) const -> result_type inline
Definition at line 946 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        if constexpr (SBE_DECOMPOSITION and ((spin == 0 and ch_bubble != 't') or (spin == 1 and ch_bubble != 'a') or spin == 2) and !differentiated) {
            return vertices_bubbleintegrand[spin].template left_same_bare_symmetry_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred>(input) + myIdentity<result_type>();
        }
        else {
            return vertices_bubbleintegrand[spin].template left_same_bare_symmetry_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred>(input);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
norm()
template<typename Q , vertexType symmtype, bool differentiated> double GeneralVertex< Q, symmtype, differentiated >::norm () inline
Definition at line 1009 of file vertex.hpp.
                 {
        if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred ) return vertex.sum_norm(2);
        else                              return vertex.sum_norm(2) + vertex_half2.sum_norm(2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
norm_K1()
template<typename Q , vertexType symmtype, bool differentiated> double GeneralVertex< Q, symmtype, differentiated >::norm_K1 (int i) inline
Definition at line 1014 of file vertex.hpp.
{ return vertex.norm_K1(i); }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
Referenced by compute_BSE().
norm_K2()
template<typename Q , vertexType symmtype, bool differentiated> double GeneralVertex< Q, symmtype, differentiated >::norm_K2 (int i) inline
Definition at line 1015 of file vertex.hpp.
{ return vertex.norm_K2(i); }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
norm_K3()
template<typename Q , vertexType symmtype, bool differentiated> double GeneralVertex< Q, symmtype, differentiated >::norm_K3 (int i) inline
Definition at line 1016 of file vertex.hpp.
{ return vertex.norm_K3(i); }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
operator*=() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> auto GeneralVertex< Q, symmtype, differentiated >::operator*= (const double & alpha) -> GeneralVertex<Q,symmtype,differentiated> inline
Definition at line 1149 of file vertex.hpp.
{
        this->vertex *= alpha;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) this->vertex_half2 += alpha;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
operator*=() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> auto GeneralVertex< Q, symmtype, differentiated >::operator*= (const GeneralVertex< Q, symmtype, differentiated > & vertex1) -> GeneralVertex<Q,symmtype,differentiated> inline
Definition at line 1140 of file vertex.hpp.
{
        this->vertex *= vertex1.vertex;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) this->vertex_half2 *= vertex1.vertex_half2;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
operator+=() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> auto GeneralVertex< Q, symmtype, differentiated >::operator+= (const double alpha) -> GeneralVertex<Q,symmtype,differentiated> inline
Definition at line 1131 of file vertex.hpp.
{
        this->vertex += alpha;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) this->vertex_half2 += alpha;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
operator+=() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> auto GeneralVertex< Q, symmtype, differentiated >::operator+= (const GeneralVertex< Q, symmtype, differentiated > & vertex1) -> GeneralVertex<Q,symmtype,differentiated> inline
Definition at line 1122 of file vertex.hpp.
{
        this->vertex += vertex1.vertex;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) this->vertex_half2 += vertex1.vertex_half2;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
operator-=()
template<typename Q , vertexType symmtype, bool differentiated> auto GeneralVertex< Q, symmtype, differentiated >::operator-= (const GeneralVertex< Q, symmtype, differentiated > & vertex1) -> GeneralVertex<Q,symmtype,differentiated> inline
Definition at line 1158 of file vertex.hpp.
{
        this->vertex -= vertex1.vertex;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) this->vertex_half2 -= vertex1.vertex_half2;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
operator/=()
template<typename Q , vertexType symmtype, bool differentiated> auto GeneralVertex< Q, symmtype, differentiated >::operator/= (const GeneralVertex< Q, symmtype, differentiated > & vertex1) -> GeneralVertex<Q,symmtype,differentiated> inline
Definition at line 1168 of file vertex.hpp.
{
        this->vertex /= vertex1.vertex;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) this->vertex_half2 /= vertex1.vertex_half2;
        return *this;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, and non_symmetric_diffright.
pvertex() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::pvertex () inline
Definition at line 865 of file vertex.hpp.
{ return vertex.pvertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
Referenced by susceptibilities_postprocessing().
pvertex() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::pvertex () const inline
Definition at line 869 of file vertex.hpp.
{ return vertex.pvertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
right_diff_bare()
template<typename Q , vertexType symmtype, bool differentiated> template<char ch_bubble> auto GeneralVertex< Q, symmtype, differentiated >::right_diff_bare (const VertexInput & input) const -> Q inline
Definition at line 923 of file vertex.hpp.
{
        if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred ) return vertex.template right_diff_bare<ch_bubble,symmtype==symmetric_r_irred,symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright>(input);
        else                              return vertex.template right_diff_bare<ch_bubble,symmtype==symmetric_r_irred,symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright>(input, vertex_half2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
right_diff_bare_symmetry_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::right_diff_bare_symmetry_expanded (const VertexInput & input) const -> result_type inline
Definition at line 974 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        return vertices_bubbleintegrand[spin].template right_diff_bare_symmetry_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred,symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright>(input);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
right_same_bare()
template<typename Q , vertexType symmtype, bool differentiated> template<char ch_bubble> auto GeneralVertex< Q, symmtype, differentiated >::right_same_bare (const VertexInput & input) const -> Q inline
Definition at line 915 of file vertex.hpp.
{
        if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred ) return vertex.template right_same_bare<ch_bubble,symmtype==symmetric_r_irred>(input);
        else                              return vertex.template right_same_bare<ch_bubble,symmtype==symmetric_r_irred>(input, vertex_half2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
right_same_bare_symmetry_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::right_same_bare_symmetry_expanded (const VertexInput & input) const -> result_type inline
Definition at line 957 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        if constexpr (SBE_DECOMPOSITION and ((spin == 0 and ch_bubble != 't') or (spin == 1 and ch_bubble != 'a') or spin == 2) and !differentiated) {
            return vertices_bubbleintegrand[spin].template right_same_bare_symmetry_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred>(input) + myIdentity<result_type>();
        }
        else {
            return vertices_bubbleintegrand[spin].template right_same_bare_symmetry_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred>(input);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), SBE_DECOMPOSITION, and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
save_expanded()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::save_expanded (const std::string & filename_prefix) const inline
Definition at line 1115 of file vertex.hpp.
{
        for (unsigned int i = 0; i < vertices_bubbleintegrand.size(); i++) {
            vertices_bubbleintegrand[i].save_expanded(filename_prefix + "spin" + std::to_string(i));
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
Referenced by parquet_solver().
set_frequency_grid()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::set_frequency_grid (const GeneralVertex< Q, symmetric_full, false > & vertex_in) inline
Definition at line 1019 of file vertex.hpp.
{
        vertex.set_frequency_grid(vertex_in.half1());
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.set_frequency_grid(vertex_in.vertex_half2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
Referenced by State< Q, differentiated >::set_frequency_grid().
set_initializedInterpol()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::set_initializedInterpol (const bool initialized) const inline
Definition at line 1050 of file vertex.hpp.
{
        vertex.set_initializedInterpol(initialized);
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.set_initializedInterpol(initialized);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
set_Ir()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::set_Ir (bool Ir) inline
Definition at line 1029 of file vertex.hpp.
                         {  // set the Ir flag (irreducible or full) for all spin components
        vertex.Ir = Ir;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.Ir=Ir;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
Referenced by compute_BSE().
set_only_same_channel()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::set_only_same_channel (bool only_same_channel) inline
Definition at line 1036 of file vertex.hpp.
{
        vertex.only_same_channel = only_same_channel;
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.only_same_channel = only_same_channel;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
set_to_zero_in_integrand()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::set_to_zero_in_integrand (const char channel, const K_class kClass) inline
Definition at line 1074 of file vertex.hpp.
{
        get_vanishing_component_channel_r(channel)[kClass] = true;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r().
sum_norm()
template<typename Q , vertexType symmtype, bool differentiated> double GeneralVertex< Q, symmtype, differentiated >::sum_norm (int i) inline
Definition at line 1013 of file vertex.hpp.
{ return vertex.sum_norm(i); }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertex.
swap_vanishing_component_channel_a_and_t()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::swap_vanishing_component_channel_a_and_t () const inline
Definition at line 1071 of file vertex.hpp.
{
        vanishing_component_channel_a.swap(vanishing_component_channel_t);
    }
References GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_a, and GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_t.
Referenced by check_selfconsistency_of_K1K2(), and compute_SDE_impl().
symmetry_expand()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex, bool need_full_vertex> void GeneralVertex< Q, symmtype, differentiated >::symmetry_expand () const inline
Definition at line 1077 of file vertex.hpp.
{
        double t_start = utils::get_time();
        symmetry_expand_impl<channel_bubble,is_left_vertex>(vertices_bubbleintegrand, half1(), half2());
        if constexpr(SBE_DECOMPOSITION and MAX_DIAG_CLASS > 1) { //
            if constexpr(!differentiated) {
                construct_SBE_nondiff_K2<channel_bubble,is_left_vertex,need_full_vertex>(vertices_bubbleintegrand);
                construct_SBE_nondiff_K3_SBE<channel_bubble,is_left_vertex,need_full_vertex>(vertices_bubbleintegrand);
                construct_SBE_nondiff_K2b<channel_bubble,is_left_vertex,need_full_vertex>(vertices_bubbleintegrand);
            }
            else {
                symmetry_expand_impl<channel_bubble,is_left_vertex>(vertex_nondifferentiated.vertices_bubbleintegrand, vertex_nondifferentiated.half1(), vertex_nondifferentiated.half2());
                construct_SBE_diff_K2<channel_bubble,is_left_vertex,need_full_vertex>(vertices_bubbleintegrand, vertex_nondifferentiated.vertices_bubbleintegrand);
                construct_SBE_nondiff_K2<channel_bubble,is_left_vertex,need_full_vertex>(vertex_nondifferentiated.vertices_bubbleintegrand);
                construct_SBE_diff_K3_SBE<channel_bubble,is_left_vertex,need_full_vertex>(vertices_bubbleintegrand, vertex_nondifferentiated.vertices_bubbleintegrand);
                construct_SBE_nondiff_K3_SBE<channel_bubble,is_left_vertex,need_full_vertex>(vertex_nondifferentiated.vertices_bubbleintegrand);
                construct_SBE_diff_K2b<channel_bubble,is_left_vertex,need_full_vertex>(vertices_bubbleintegrand, vertex_nondifferentiated.vertices_bubbleintegrand);
                //construct_SBE_nondiff_K2b<channel_bubble,is_left_vertex,need_full_vertex>(vertex_nondifferentiated.vertices_bubbleintegrand);
            }
        }
        for (int ispin = 0; ispin < vertices_bubbleintegrand.size(); ispin++) {
            if (vanishing_component_gamma0) vertices_bubbleintegrand[ispin].irred *= 0.;
            for (char r : {'a', 'p', 't'}) {
                for (K_class k : {k1, k2, k2b, k3, k3_sbe}) {
                    if (get_vanishing_component_channel_r(r)[k]) vertices_bubbleintegrand[ispin].get_rvertex(r).set_K_symmetryexpanded_to_zero(k);
                }
            }
        }
        //double t = utils::get_time() - t_start;
        //utils::print("symmetry expansion of vertex done, ");
        //utils::get_time(t_start);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), utils::get_time(), GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r(), GeneralVertex< Q, symmtype, differentiated >::half1(), GeneralVertex< Q, symmtype, differentiated >::half2(), k1, k2, k2b, k3, k3_sbe, MAX_DIAG_CLASS, SBE_DECOMPOSITION, GeneralVertex< Q, symmtype, differentiated >::vanishing_component_gamma0, GeneralVertex< Q, symmtype, differentiated >::vertex_nondifferentiated, and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
symmetry_expand_impl()
template<typename Q , vertexType symmtype, bool differentiated> template<char channel_bubble, bool is_left_vertex> void GeneralVertex< Q, symmtype, differentiated >::symmetry_expand_impl (std::vector< fullvert< Q > > & vertices_expanded_target, const fullvert< Q > & vertex_symmetryreduced_half1, const fullvert< Q > & vertex_symmetryreduced_half2) const inline private
construct up-up spin component:
Definition at line 794 of file vertex.hpp.
{
        vertices_expanded_target = std::vector<fullvert<Q>>(n_spin_expanded + 1, fullvert<Q>(0.));
        //utils::print("Start symmetry expansion\n");
        initializeInterpol();
        //utils::print("Initialized Interpolator \n");
        for (int ispin = 0; ispin < n_spin_expanded; ispin++) {
            vertices_expanded_target[ispin].template symmetry_expand<channel_bubble,is_left_vertex>(vertex_symmetryreduced_half1, vertex_symmetryreduced_half2, ispin);
            //utils::print("expanded spin component ", ispin, "\n");
        }
//#if SBE_DECOMPOSITION or not KELDYSH_FORMALISM  // for Keldysh runs in non-SBE decomposition we want to have adaptive frequency grids => adding up buffers with different grids is bogus.
        vertices_expanded_target[2] = vertices_expanded_target[0];
        vertices_expanded_target[2].irred *= 0. ;
        for (char r : {'a', 'p', 't'}) {
            vertices_expanded_target[2].get_rvertex(r).K1_symmetry_expanded += vertices_expanded_target[1].get_rvertex(r).K1_symmetry_expanded;
#ifdef ADAPTIVE_GRID
            assert(false);
#endif
            if (MAX_DIAG_CLASS > 1) {
                vertices_expanded_target[2].get_rvertex(r).K2_symmetry_expanded += vertices_expanded_target[1].get_rvertex(r).K2_symmetry_expanded;
                vertices_expanded_target[2].get_rvertex(r).K2b_symmetry_expanded += vertices_expanded_target[1].get_rvertex(r).K2b_symmetry_expanded;
            }
            if (MAX_DIAG_CLASS > 2) {
                vertices_expanded_target[2].get_rvertex(r).K3_symmetry_expanded += vertices_expanded_target[1].get_rvertex(r).K3_symmetry_expanded;
            }
        }
//#endif
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), GeneralVertex< Q, symmtype, differentiated >::initializeInterpol(), MAX_DIAG_CLASS, and n_spin_expanded.
tvertex() [1/2]
template<typename Q , vertexType symmtype, bool differentiated> rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::tvertex () inline
Definition at line 866 of file vertex.hpp.
{ return vertex.tvertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
Referenced by susceptibilities_postprocessing().
tvertex() [2/2]
template<typename Q , vertexType symmtype, bool differentiated> const rvert< Q > & GeneralVertex< Q, symmtype, differentiated >::tvertex () const inline
Definition at line 870 of file vertex.hpp.
{ return vertex.tvertex;}
References GeneralVertex< Q, symmtype, differentiated >::vertex.
update_grid()
template<typename Q , vertexType symmtype, bool differentiated> void GeneralVertex< Q, symmtype, differentiated >::update_grid (double Lambda, double hartree_plus_epsilon, const fRG_config & config) inline
Definition at line 1024 of file vertex.hpp.
                                                                                           {  // Interpolate vertex to updated grid
        vertex.update_grid(Lambda, hartree_plus_epsilon, config);
        if constexpr(symmtype==non_symmetric_diffleft or symmtype==non_symmetric_diffright) vertex_half2.update_grid(Lambda, config);
    };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), non_symmetric_diffleft, non_symmetric_diffright, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
Referenced by State< Q, differentiated >::update_grid().
value()
template<typename Q , vertexType symmtype, bool differentiated> template<char ch_bubble> auto GeneralVertex< Q, symmtype, differentiated >::value (const VertexInput & input) const -> Q inline
Definition at line 907 of file vertex.hpp.
{
        if constexpr(symmtype == symmetric_full or symmtype == symmetric_r_irred ) return vertex.template value<ch_bubble,symmtype==symmetric_r_irred>(input);
        else                              return vertex.template value<ch_bubble,symmtype==symmetric_r_irred>(input, vertex_half2);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), symmetric_full, symmetric_r_irred, GeneralVertex< Q, symmtype, differentiated >::vertex, and GeneralVertex< Q, symmtype, differentiated >::vertex_half2.
value_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::value_expanded (const VertexInput & input) const -> result_type inline
Definition at line 927 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        return vertices_bubbleintegrand[spin].template value_expanded<ch_bubble,result_type,symmtype==symmetric_r_irred>(input);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
value_minus_gamma0_symmetry_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::value_minus_gamma0_symmetry_expanded (const VertexInput & input) const -> result_type inline
Definition at line 940 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        return vertices_bubbleintegrand[spin].template value_minus_gamma0_symmetry_expanded<ch_bubble,result_type,symmtype!=symmetric_full>(input);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
value_symmetry_expanded()
template<typename Q , vertexType symmtype, bool differentiated> template<int spin, char ch_bubble, typename result_type > auto GeneralVertex< Q, symmtype, differentiated >::value_symmetry_expanded (const VertexInput & input) const -> result_type inline
Definition at line 934 of file vertex.hpp.
{
        static_assert(spin == 0 or spin == 1 or spin == 2, "Used unsupported spin index");
        assert(input.spin == 0);
        assert(spin < vertices_bubbleintegrand.size());
        return vertices_bubbleintegrand[spin].template value_symmetry_expanded<ch_bubble,result_type,symmtype!=symmetric_full>(input);
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand.
Friends And Related Symbol Documentation
operator* [1/2]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated > operator* (GeneralVertex< Q, symmtype, differentiated > lhs, const double & rhs) friend
Definition at line 1154 of file vertex.hpp.
{
        lhs *= rhs;
        return lhs;
    }
operator* [2/2]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated > operator* (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > & rhs) friend
Definition at line 1145 of file vertex.hpp.
{
        lhs *= rhs;
        return lhs;
    }
operator+ [1/2]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated > operator+ (GeneralVertex< Q, symmtype, differentiated > lhs, const double & rhs) friend
Definition at line 1136 of file vertex.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator+ [2/2]
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated > operator+ (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > & rhs) friend
Definition at line 1127 of file vertex.hpp.
{
        lhs += rhs;
        return lhs;
    }
operator-
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated > operator- (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > & rhs) friend
Definition at line 1163 of file vertex.hpp.
{
        lhs -= rhs;
        return lhs;
    }
operator/
template<typename Q , vertexType symmtype, bool differentiated> GeneralVertex< Q, symmtype, differentiated > operator/ (GeneralVertex< Q, symmtype, differentiated > lhs, const GeneralVertex< Q, symmtype, differentiated > & rhs) friend
Definition at line 1173 of file vertex.hpp.
{
        lhs /= rhs;
        return lhs;
    }
Member Data Documentation
vanishing_component_channel_a
template<typename Q , vertexType symmtype, bool differentiated> vec<bool> GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_a = {false, false, false, false, false} mutable
Definition at line 1062 of file vertex.hpp.
{false, false, false, false, false};
Referenced by GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r(), and GeneralVertex< Q, symmtype, differentiated >::swap_vanishing_component_channel_a_and_t().
vanishing_component_channel_p
template<typename Q , vertexType symmtype, bool differentiated> vec<bool> GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_p = {false, false, false, false, false} mutable
Definition at line 1063 of file vertex.hpp.
{false, false, false, false, false};
Referenced by GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r().
vanishing_component_channel_t
template<typename Q , vertexType symmtype, bool differentiated> vec<bool> GeneralVertex< Q, symmtype, differentiated >::vanishing_component_channel_t = {false, false, false, false, false} mutable
Definition at line 1064 of file vertex.hpp.
{false, false, false, false, false};
Referenced by GeneralVertex< Q, symmtype, differentiated >::get_vanishing_component_channel_r(), and GeneralVertex< Q, symmtype, differentiated >::swap_vanishing_component_channel_a_and_t().
vanishing_component_gamma0
template<typename Q , vertexType symmtype, bool differentiated> bool GeneralVertex< Q, symmtype, differentiated >::vanishing_component_gamma0 = false mutable
Definition at line 1061 of file vertex.hpp.
Referenced by compute_SDE_impl(), and GeneralVertex< Q, symmtype, differentiated >::symmetry_expand().
vertex
template<typename Q , vertexType symmtype, bool differentiated> fullvert<Q> GeneralVertex< Q, symmtype, differentiated >::vertex private
Definition at line 456 of file vertex.hpp.
Referenced by GeneralVertex< Q, symmtype, differentiated >::avertex(), GeneralVertex< Q, symmtype, differentiated >::avertex(), GeneralVertex< Q, symmtype, differentiated >::center_frequency_grids(), GeneralVertex< Q, symmtype, differentiated >::check_symmetries(), compute_BSE(), compute_SDE_impl_v1(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K2(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K2b(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_diff_K3_SBE(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K2(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K2b(), GeneralVertex< Q, symmtype, differentiated >::construct_SBE_nondiff_K3_SBE(), GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), GeneralVertex< Q, symmtype, differentiated >::get_rvertex(), GeneralVertex< Q, symmtype, differentiated >::half1(), GeneralVertex< Q, symmtype, differentiated >::half1(), GeneralVertex< Q, symmtype, differentiated >::half2(), GeneralVertex< Q, symmtype, differentiated >::half2(), GeneralVertex< Q, symmtype, differentiated >::initialize(), GeneralVertex< Q, symmtype, differentiated >::initializeInterpol(), GeneralVertex< Q, symmtype, differentiated >::irred(), GeneralVertex< Q, symmtype, differentiated >::irred(), GeneralVertex< Q, symmtype, differentiated >::left_diff_bare(), GeneralVertex< Q, symmtype, differentiated >::left_same_bare(), GeneralVertex< Q, symmtype, differentiated >::norm(), GeneralVertex< Q, symmtype, differentiated >::norm_K1(), GeneralVertex< Q, symmtype, differentiated >::norm_K2(), GeneralVertex< Q, symmtype, differentiated >::norm_K3(), State< Q, differentiated >::operator+=(), State< Q, differentiated >::operator-=(), State< Q, differentiated >::operator/=(), parquet_checks(), GeneralVertex< Q, symmtype, differentiated >::pvertex(), GeneralVertex< Q, symmtype, differentiated >::pvertex(), rhs_n_loop_flow(), GeneralVertex< Q, symmtype, differentiated >::right_diff_bare(), GeneralVertex< Q, symmtype, differentiated >::right_same_bare(), GeneralVertex< Q, symmtype, differentiated >::set_frequency_grid(), GeneralVertex< Q, symmtype, differentiated >::set_initializedInterpol(), GeneralVertex< Q, symmtype, differentiated >::set_Ir(), GeneralVertex< Q, symmtype, differentiated >::set_only_same_channel(), GeneralVertex< Q, symmtype, differentiated >::sum_norm(), susceptibilities_postprocessing(), GeneralVertex< Q, symmtype, differentiated >::tvertex(), GeneralVertex< Q, symmtype, differentiated >::tvertex(), GeneralVertex< Q, symmtype, differentiated >::update_grid(), and GeneralVertex< Q, symmtype, differentiated >::value().
vertex_half2
template<typename Q , vertexType symmtype, bool differentiated> vertex_half2_t GeneralVertex< Q, symmtype, differentiated >::vertex_half2 private
Definition at line 458 of file vertex.hpp.
Referenced by GeneralVertex< Q, symmtype, differentiated >::half2(), GeneralVertex< Q, symmtype, differentiated >::half2(), GeneralVertex< Q, symmtype, differentiated >::initialize(), GeneralVertex< Q, symmtype, differentiated >::initializeInterpol(), GeneralVertex< Q, symmtype, differentiated >::left_diff_bare(), GeneralVertex< Q, symmtype, differentiated >::left_same_bare(), GeneralVertex< Q, symmtype, differentiated >::norm(), GeneralVertex< Q, symmtype, differentiated >::right_diff_bare(), GeneralVertex< Q, symmtype, differentiated >::right_same_bare(), GeneralVertex< Q, symmtype, differentiated >::set_frequency_grid(), GeneralVertex< Q, symmtype, differentiated >::set_initializedInterpol(), GeneralVertex< Q, symmtype, differentiated >::set_Ir(), GeneralVertex< Q, symmtype, differentiated >::set_only_same_channel(), GeneralVertex< Q, symmtype, differentiated >::update_grid(), and GeneralVertex< Q, symmtype, differentiated >::value().
vertex_nondifferentiated
template<typename Q , vertexType symmtype, bool differentiated> vertex_nondiff_t GeneralVertex< Q, symmtype, differentiated >::vertex_nondifferentiated private
Definition at line 461 of file vertex.hpp.
Referenced by GeneralVertex< Q, symmtype, differentiated >::get_vertex_nondiff(), GeneralVertex< Q, symmtype, differentiated >::get_w_r_value_symmetry_expanded_nondiff(), and GeneralVertex< Q, symmtype, differentiated >::symmetry_expand().
vertices_bubbleintegrand
template<typename Q , vertexType symmtype, bool differentiated> std::vector<fullvert<Q> > GeneralVertex< Q, symmtype, differentiated >::vertices_bubbleintegrand mutable
Buffer for vectorized computation of an r-bubble Each entry contains exactly one spin component; all Keldysh components are present, they are ordered by GeneralVertex::symmetry_expand() such that they allow vectorized operations for the computation in channel r
Definition at line 834 of file vertex.hpp.
Referenced by GeneralVertex< Q, symmtype, differentiated >::get_w_r_value_symmetry_expanded_nondiff(), GeneralVertex< Q, symmtype, differentiated >::left_diff_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::left_same_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::right_diff_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::right_same_bare_symmetry_expanded(), GeneralVertex< Q, symmtype, differentiated >::save_expanded(), GeneralVertex< Q, symmtype, differentiated >::symmetry_expand(), GeneralVertex< Q, symmtype, differentiated >::value_expanded(), GeneralVertex< Q, symmtype, differentiated >::value_minus_gamma0_symmetry_expanded(), and GeneralVertex< Q, symmtype, differentiated >::value_symmetry_expanded().
The documentation for this class was generated from the following file:
vertex.hpp