#!/bin/bash
#SBATCH -o /home/hpc/uh3o1/ri26yad/LOG/LOG_HF_equations/myjob.%j.%N.out
#SBATCH -D /home/hpc/uh3o1/ri26yad/RUN
#SBATCH -J some_job
#SBATCH --get-user-env
#SBATCH --clusters=lmu_asc
#SBATCH --partition=lmu_asc_shm8
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=15000
#SBATCH --mail-type=end
#SBATCH --mail-user=lukas.weidinger@physik.lmu.de
#SBATCH --export=NONE
#SBATCH --time=20:00:00

export OMP_NUM_THREADS=8
export MKL_NUM_THREADS=1

. /etc/profile

#ulimit -c unlimited
cd /naslx/projects/uh3o1/ri26yad/DATA/Unit_tests/HF_equations
/home/hpc/uh3o1/ri26yad/bin/hf_equations
