SIAM-Keldysh-mfRG: irreducible< Q > Class Template Reference
irreducible< Q > Class Template Reference
#include <vertex.hpp>
Public Member Functions
irreducible ()=default
template<typename result_type = Q>
auto val (my_index_t iK, my_index_t i_in, my_index_t spin) const -> result_type
auto acc (int i) const -> Q
void direct_set (int i, Q value)
void setvert (int iK, int i_in, Q)
void initialize (Q val)
buffer_type get_vec () const
void set_vec (const buffer_type &bare_in)
auto operator+= (const irreducible< Q > &vertex) -> irreducible< Q >
auto operator-= (const irreducible< Q > &vertex) -> irreducible< Q >
auto operator+= (const double &alpha) -> irreducible< Q >
auto operator*= (const double &alpha) -> irreducible< Q >
auto operator*= (const irreducible< Q > &vertex) -> irreducible< Q >
auto operator/= (const irreducible< Q > &vertex) -> irreducible< Q >
Private Types
using buffer_type = multidimensional::multiarray<Q,2>
Private Member Functions
buffer_type empty_bare ()
Private Attributes
buffer_type bare = empty_bare()
Friends
State< state_datatype, false > read_state_from_hdf (const H5std_string &filename, const int Lambda_it)
irreducible< Q > operator+ (irreducible< Q > lhs, const irreducible< Q > &rhs)
irreducible< Q > operator- (irreducible< Q > lhs, const irreducible< Q > &rhs)
irreducible< Q > operator+ (irreducible< Q > lhs, const double &rhs)
irreducible< Q > operator* (irreducible< Q > lhs, const double &rhs)
irreducible< Q > operator* (irreducible< Q > lhs, const irreducible< Q > &rhs)
irreducible< Q > operator/ (irreducible< Q > lhs, const irreducible< Q > &rhs)
Detailed Description
template<class Q>
class irreducible< Q >
Reducible vertex in channel r, split into diagrammatic classes K1, K2, K2b, K3. Member functions allow for access of values at arbitrary frequencies and in each channel-specific frequency representation. Possible (unit-)tests: [IMPLEMENTED in test_symmetries.c++] check read-out from symmetry-reduced sector and correctness of symmetry tables [MISSING] check conversion of frequency conventions
Possible unit-tests Do the public functions return the correct vertex-contributions?
Definition at line 19 of file vertex.hpp.
Member Typedef Documentation
buffer_type
template<class Q > using irreducible< Q >::buffer_type = multidimensional::multiarray<Q,2> private
Definition at line 21 of file vertex.hpp.
Constructor & Destructor Documentation
irreducible()
template<class Q > irreducible< Q >::irreducible () default
Member Function Documentation
acc()
template<typename Q > auto irreducible< Q >::acc (int i) const -> Q
Definition at line 1153 of file vertex.hpp.
{
   assert(i>=0 && i<bare.size());
   return bare.flat_at(i);
   //else {utils::print("ERROR: Tried to access value outside of range in irreducible vertex. Abort."); assert(false);}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
direct_set()
template<typename Q > void irreducible< Q >::direct_set (int i, Q value)
Definition at line 1159 of file vertex.hpp.
{
    assert(i>=0 && i<bare.size());
    bare.flat_at(i)=value;
    //else {utils::print("ERROR: Tried to access value outside of range in irreducible vertex. Abort."); assert(false);}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
empty_bare()
template<class Q > buffer_type irreducible< Q >::empty_bare () inline private
Definition at line 22 of file vertex.hpp.
{
        if (KELDYSH) return buffer_type ({16,n_in});
        else return buffer_type ({1, n_in});
    }
References KELDYSH, and n_in.
get_vec()
template<class Q > buffer_type irreducible< Q >::get_vec () const inline
Definition at line 43 of file vertex.hpp.
{return bare;}
References irreducible< Q >::bare.
initialize()
template<typename Q > void irreducible< Q >::initialize (Q val)
Definition at line 1169 of file vertex.hpp.
{
    if (KELDYSH){
        if (CONTOUR_BASIS != 1) {
            // Keldysh basis:
            for (auto i:odd_Keldysh) {
                for (int i_in=0; i_in<n_in; ++i_in) {
                    this->setvert(i, i_in, val);
                }
            }
        }
        else {
            // Contour basis:
            for (int i_in=0; i_in<n_in; ++i_in) {
                this->setvert( 0, i_in, val); // for forward contour
                this->setvert(15, i_in,-val); // for backward contour
            }
        }
    }
    else{
        for (int i_in=0; i_in<n_in; ++i_in) {
            this->setvert(0, i_in, val);
        }
    }
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), KELDYSH, n_in, and odd_Keldysh().
operator*=() [1/2]
template<class Q > auto irreducible< Q >::operator*= (const double & alpha) -> irreducible<Q> inline
Definition at line 68 of file vertex.hpp.
{
        this->bare *=alpha;
        return *this;
    }
operator*=() [2/2]
template<class Q > auto irreducible< Q >::operator*= (const irreducible< Q > & vertex) -> irreducible<Q> inline
Definition at line 75 of file vertex.hpp.
{
        this->bare *= vertex.bare;
        return *this;
    }
operator+=() [1/2]
template<class Q > auto irreducible< Q >::operator+= (const double & alpha) -> irreducible<Q> inline
Definition at line 61 of file vertex.hpp.
{
        this->bare +=alpha;
        return *this;
    }
operator+=() [2/2]
template<class Q > auto irreducible< Q >::operator+= (const irreducible< Q > & vertex) -> irreducible<Q> inline
Definition at line 47 of file vertex.hpp.
{
        this->bare +=vertex.bare;
        return *this;
    }
operator-=()
template<class Q > auto irreducible< Q >::operator-= (const irreducible< Q > & vertex) -> irreducible<Q> inline
Definition at line 54 of file vertex.hpp.
{
        this->bare -=vertex.bare;
        return *this;
    }
operator/=()
template<class Q > auto irreducible< Q >::operator/= (const irreducible< Q > & vertex) -> irreducible<Q> inline
Definition at line 82 of file vertex.hpp.
{
        //his->bare /= vertex.bare;
        return *this;
    }
set_vec()
template<class Q > void irreducible< Q >::set_vec (const buffer_type & bare_in) inline
Definition at line 44 of file vertex.hpp.
{bare = bare_in;}
References irreducible< Q >::bare, and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
setvert()
template<typename Q > void irreducible< Q >::setvert (int iK, int i_in, Q value)
Definition at line 1165 of file vertex.hpp.
{
    bare.at(iK, i_in) = value;
}
val()
template<typename Q > template<typename result_type > auto irreducible< Q >::val (my_index_t iK, my_index_t i_in, my_index_t spin) const -> result_type
Definition at line 1114 of file vertex.hpp.
{
    if constexpr(std::is_same_v<result_type,Q>) {
        switch (spin) {
            case 0:
                return bare.at(iK, i_in);
                break;
            case 1:
                return -bare.at(iK, i_in);
                break;
            case 2:
                return 0.;
                break;
            default:
                utils::print("Problems in irred.val. Abort.");
                assert(false);
                return 0.;
        }
    }
    else {
        result_type result;
        constexpr int rows = result_type::RowsAtCompileTime;
        switch (spin) {
            case 0:
                result = bare.template at_vectorized<0,0,rows>(iK,i_in);
                break;
            case 1:
                result = -bare.template at_vectorized<0,0,rows>(iK,i_in);
                break;
            case 2:
                result = myzero<result_type>();
                break;
            default:
                utils::print("Problems in irred.val. Abort.");
                assert(false);
        }
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
Friends And Related Symbol Documentation
operator* [1/2]
template<class Q > irreducible< Q > operator* (irreducible< Q > lhs, const double & rhs) friend
Definition at line 72 of file vertex.hpp.
{
        lhs *= rhs; return lhs;
    }
operator* [2/2]
template<class Q > irreducible< Q > operator* (irreducible< Q > lhs, const irreducible< Q > & rhs) friend
Definition at line 79 of file vertex.hpp.
{
        lhs *= rhs; return lhs;
    }
operator+ [1/2]
template<class Q > irreducible< Q > operator+ (irreducible< Q > lhs, const double & rhs) friend
Definition at line 65 of file vertex.hpp.
{
        lhs += rhs; return lhs;
    }
operator+ [2/2]
template<class Q > irreducible< Q > operator+ (irreducible< Q > lhs, const irreducible< Q > & rhs) friend
Definition at line 51 of file vertex.hpp.
{
        lhs += rhs; return lhs;
    }
operator-
template<class Q > irreducible< Q > operator- (irreducible< Q > lhs, const irreducible< Q > & rhs) friend
Definition at line 58 of file vertex.hpp.
{
        lhs -= rhs; return lhs;
    }
operator/
template<class Q > irreducible< Q > operator/ (irreducible< Q > lhs, const irreducible< Q > & rhs) friend
Definition at line 86 of file vertex.hpp.
{
        //lhs /= rhs;
        return lhs;
    }
read_state_from_hdf
template<class Q > State< state_datatype, false > read_state_from_hdf (const H5std_string & filename, const int Lambda_it) friend
Read a state from a specified Lambda layer of a given hdf file.
Parameters
filename String of the filename.
Lambda_it Number of the layer from which the state shall be read.
Returns
State that has been read out.
check whether parameters in HDF file agree with parameters/master_parameters.hpp
Write used parameters for documentation purpose
Definition at line 61 of file hdf5_routines.c++.
{
    H5::H5File file_out = open_hdf_file_readOnly(filename);
    std::vector<double> Lambda;
    read_from_hdf_LambdaLayer<double>(file_out, LAMBDA_LIST, Lambda, Lambda_it);
    fRG_config config = read_config_from_hdf(filename);
    State<state_datatype,false> state(Lambda[0], config);
    std::vector<state_datatype> Sigma_H;
    read_from_hdf_LambdaLayer<state_datatype>(file_out, SELF_LIST, state.selfenergy.Sigma.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, HARTREE, Sigma_H, Lambda_it);
    state.selfenergy.asymp_val_R = Sigma_H[0];
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_irred, state.vertex.irred().bare, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_a, state.vertex.avertex().K1.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_p, state.vertex.pvertex().K1.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_t, state.vertex.tvertex().K1.data, Lambda_it);
#if MAX_DIAG_CLASS>1
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_a, state.vertex.avertex().K2.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_p, state.vertex.pvertex().K2.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_t, state.vertex.tvertex().K2.data, Lambda_it);
#if DEBUG_SYMMETRIES
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_a, state.vertex.avertex().K2b.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_p, state.vertex.pvertex().K2b.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_t, state.vertex.tvertex().K2b.data, Lambda_it);
#endif
#endif
#if MAX_DIAG_CLASS>2
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_a, state.vertex.avertex().K3.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_p, state.vertex.pvertex().K3.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_t, state.vertex.tvertex().K3.data, Lambda_it);
#endif
    H5::Group group_freqparams(file_out.openGroup(FREQ_PARAMS));
    H5::Group group_freqparams_ffreqs (group_freqparams.openGroup(FFREQS_LIST ));
    H5::Group group_freqparams_bfreqsa (group_freqparams.openGroup(BFREQS_LISTa ));
    H5::Group group_freqparams_bfreqsp (group_freqparams.openGroup(BFREQS_LISTp ));
    H5::Group group_freqparams_bfreqst (group_freqparams.openGroup(BFREQS_LISTt ));
    H5::Group group_freqparams_bfreqs2a(group_freqparams.openGroup(BFREQS2_LISTa));
    H5::Group group_freqparams_bfreqs2p(group_freqparams.openGroup(BFREQS2_LISTp));
    H5::Group group_freqparams_bfreqs2t(group_freqparams.openGroup(BFREQS2_LISTt));
    H5::Group group_freqparams_bfreqs2ba(group_freqparams.openGroup(BFREQS2b_LISTa));
    H5::Group group_freqparams_bfreqs2bp(group_freqparams.openGroup(BFREQS2b_LISTp));
    H5::Group group_freqparams_bfreqs2bt(group_freqparams.openGroup(BFREQS2b_LISTt));
    H5::Group group_freqparams_bfreqs3a(group_freqparams.openGroup(BFREQS3_LISTa));
    H5::Group group_freqparams_bfreqs3p(group_freqparams.openGroup(BFREQS3_LISTp));
    H5::Group group_freqparams_bfreqs3t(group_freqparams.openGroup(BFREQS3_LISTt));
    H5::Group group_freqparams_ffreqs2a(group_freqparams.openGroup(FFREQS2_LISTa));
    H5::Group group_freqparams_ffreqs2p(group_freqparams.openGroup(FFREQS2_LISTp));
    H5::Group group_freqparams_ffreqs2t(group_freqparams.openGroup(FFREQS2_LISTt));
    H5::Group group_freqparams_ffreqs2ba(group_freqparams.openGroup(FFREQS2b_LISTa));
    H5::Group group_freqparams_ffreqs2bp(group_freqparams.openGroup(FFREQS2b_LISTp));
    H5::Group group_freqparams_ffreqs2bt(group_freqparams.openGroup(FFREQS2b_LISTt));
    H5::Group group_freqparams_ffreqs3a(group_freqparams.openGroup(FFREQS3_LISTa));
    H5::Group group_freqparams_ffreqs3p(group_freqparams.openGroup(FFREQS3_LISTp));
    H5::Group group_freqparams_ffreqs3t(group_freqparams.openGroup(FFREQS3_LISTt));
    H5::Group group_freqparams_ffreqs3a2(group_freqparams.openGroup(FFREQS3_LISTa2));
    H5::Group group_freqparams_ffreqs3p2(group_freqparams.openGroup(FFREQS3_LISTp2));
    H5::Group group_freqparams_ffreqs3t2(group_freqparams.openGroup(FFREQS3_LISTt2));
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs , state.selfenergy.Sigma.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqsa, state.vertex.avertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqsp, state.vertex.pvertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqst, state.vertex.tvertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
#if MAX_DIAG_CLASS>1
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2a,state.vertex.avertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2p,state.vertex.pvertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2t,state.vertex.tvertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2a,state.vertex.avertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2p,state.vertex.pvertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2t,state.vertex.tvertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
#if DEBUG_SYMMETRIES
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2ba,state.vertex.avertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2bp,state.vertex.pvertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2bt,state.vertex.tvertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2ba,state.vertex.avertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2bp,state.vertex.pvertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2bt,state.vertex.tvertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
#endif
#endif
#if MAX_DIAG_CLASS>2
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3a, state.vertex.avertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3p, state.vertex.pvertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3t, state.vertex.tvertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3a, state.vertex.avertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3p, state.vertex.pvertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3t, state.vertex.tvertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3a2,state.vertex.avertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3p2,state.vertex.pvertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3t2,state.vertex.tvertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
#endif
        int REG_loaded, MAX_DIAG_CLASS_loaded, N_LOOPS_loaded, GRID_loaded;
        double glb_Gamma_loaded, glb_T_loaded, glb_mu_loaded, glb_U_loaded, glb_epsilon_loaded, glb_V_loaded;
    H5::Group group_params(file_out.openGroup(PARAM_LIST));
    read_from_hdf(group_params, "REG", REG_loaded);
    read_from_hdf(group_params, "MAX_DIAG_CLASS", MAX_DIAG_CLASS_loaded);
    read_from_hdf(group_params, "mu", glb_mu_loaded);
    read_from_hdf(group_params, "V", glb_V_loaded);
    read_from_hdf(group_params, "GRID", GRID_loaded);
    bool are_parameters_identical = REG == REG_loaded and
            MAX_DIAG_CLASS == MAX_DIAG_CLASS_loaded and
            glb_mu == glb_mu_loaded and
            glb_V == glb_V_loaded and
            GRID == GRID_loaded;
    if (!are_parameters_identical) {
        utils::print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        utils::print("\t Warning!: \t Parameters of executable do not agree with those in HDF file ", filename, "\n");
        const vec<bool> is_identical_parameter = {
                MAX_DIAG_CLASS == MAX_DIAG_CLASS_loaded
                ,glb_mu == glb_mu_loaded
                ,glb_V == glb_V_loaded
                ,GRID == GRID_loaded
        };
        const vec<std::string> parameter_names = {
                "MAX_DIAG_CLASS"
                ,"glb_mu"
                ,"glb_V"
                ,"GRID"
        };
        for (int i = 0; i < is_identical_parameter.size(); i++){
            if (!is_identical_parameter[i]) utils::print("\t parameter ", parameter_names[i], " is different.\n");
        }
        utils::print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
    }
    file_out.close();
    return state;
}
Member Data Documentation
bare
template<class Q > buffer_type irreducible< Q >::bare = empty_bare() mutable private
Definition at line 26 of file vertex.hpp.
Referenced by irreducible< Q >::get_vec(), and irreducible< Q >::set_vec().
The documentation for this class was generated from the following files:
r_vertex.hpp
vertex.hpp