SIAM-Keldysh-mfRG: boost::numeric::odeint::detail Namespace Reference
boost::numeric::odeint::detail Namespace Reference
Functions
template<class Stepper , typename State_t , typename FlowGrid , class System >
State_t integrate_nonadaptive (Stepper stepper, System system, State_t &start_state, double &t_now, double t_final, const vec< double > &lambdas_try, vec< double > &lambdas_did, const ODE_solver_config &config, const bool verbose)
template<class Stepper , typename State_t , typename FlowGrid , class System >
State_t integrate_adaptive_check (Stepper stepper, System system, State_t &start_state, double &t_now, double t_final, double &dt, const size_t MAXSTP, vec< double > &lambdas_did, const ODE_solver_config &config, const bool verbose)
Function Documentation
integrate_adaptive_check()
template<class Stepper , typename State_t , typename FlowGrid , class System > State_t boost::numeric::odeint::detail::integrate_adaptive_check (Stepper stepper, System system, State_t & start_state, double & t_now, double t_final, double & dt, const size_t MAXSTP, vec< double > & lambdas_did, const ODE_solver_config & config, const bool verbose)
step to lambda checkpoint if within reach
Definition at line 723 of file ODE_solvers.hpp.
                {
                    if (verbose and mpi_world_rank()==0) {
                        utils::print("Initial t_now: ", t_now, " -- t_final: ", t_final, " -- dt: ", dt, "\n");
                    }
                    const char *error_string = "Integrate adaptive : Maximal number of iterations reached. A step size could not be found.";
                    size_t integration_step_count = config.iter_start;
                    bool previously_hit_lambda_checkpoint = false;
                    double dt_temp;
                    while( less_with_sign( t_now, t_final, dt ))
                    {
                        if(previously_hit_lambda_checkpoint) dt = dt_temp;  // try the old step size if the step size of decreased due to hitting a Lambda checkpoint:
                        if( less_with_sign( t_final, t_now + dt, dt ) ) //
{
                            dt = t_final - t_now;
                        }
                        double Lambda_now = FlowGrid::lambda_from_t(t_now);
                        double Lambda_next= FlowGrid::lambda_from_t(t_now+dt);
#ifndef REPARAMETRIZE_FLOWGRID
                        double dLambda = Lambda_next - Lambda_now;
#endif
                        for (const double checkpoint : config.lambda_checkpoints)
{
                            // Guard against float arithmetic fails
                            if ((Lambda_now - checkpoint) * (Lambda_next - checkpoint) < -1e-14 ) // are we crossing a lambda checkpoint? If yes -> hit lambda checkpoint
{
                                previously_hit_lambda_checkpoint = true;
                                dt_temp = dt;
                                dt = FlowGrid::t_from_lambda(checkpoint) - FlowGrid::t_from_lambda(Lambda_now);
                                break;
                            }
                        }
                        if (verbose and mpi_world_rank()==0) {
                            utils::print("ODE iteration number: \t", integration_step_count, "\n");
                        }
                        unsigned int trials = 0;
                        controlled_step_result res = success;
                        do
{
                            #ifdef REPARAMETRIZE_FLOWGRID
                                double dt_old = dt;
                                if (verbose and mpi_world_rank()==0) { utils::print("current flow parameter t_now: ", t_now, " -- t_final: ", t_final, " -- try step size dt: ", dt, "\n"); }
                                auto rhs = [&system](const State_t& state_in, State_t& dState_dt, double t) -> void {system(state_in, dState_dt, FlowGrid::lambda_from_t(t)); dState_dt *= FlowGrid::dlambda_dt(t);};
                                res = stepper.try_step( rhs, start_state, t_now, dt);
                                if (verbose and mpi_world_rank()==0) utils::print( (res == fail ? "ODE step FAILED -- new dt: " + std::to_string(dt) : "ODE step PASSED with step size dt = " + std::to_string(dt_old)), "\n");
                            #else
                                double t_now_temp = t_now;
                                double dLambda_old = dLambda;
                                if (verbose and mpi_world_rank()==0) { utils::print("current flow parameter Lambda_now: ", Lambda_now, " -- Lambda_final: ", FlowGrid::lambda_from_t(t_final), " -- try step size dLambda: ", dLambda, "\n"); }
                                auto rhs = [&system](const State_t& state_in, State_t& dState_dt, double Lambda_in) -> void {system(state_in, dState_dt, Lambda_in);};
                                res = stepper.try_step( rhs, start_state, Lambda_now, dLambda);  // if successful: updates Lambda_now and dt; if failed: updates only dt
                                if (res == success) {
                                    // update t_now and dt for next step
                                    t_now = FlowGrid::t_from_lambda(Lambda_now);
                                    dt = FlowGrid::t_from_lambda(std::max(1e-15, Lambda_now + dLambda)) - t_now;
                                }
                                //Lambda_next = Lambda_now + dLambda;
                                if (verbose and mpi_world_rank()==0) utils::print( (res == fail ? "ODE step FAILED -- new dLambda: " + std::to_string(dLambda) : "ODE step PASSED with step size dLambda = " + std::to_string(dLambda_old)), "\n");
                            #endif
                            if constexpr(std::is_same<State<state_datatype>, State_t>::value) {
                                system.rk_step = 0;
                            }
                            ++trials;
                        }
                        while( ( res == fail ) && ( trials < config.max_stepResizing_attempts ) );
                        if( trials == config.max_stepResizing_attempts ) throw std::overflow_error(error_string );
                        lambdas_did[integration_step_count+1] = FlowGrid::lambda_from_t(t_now);
                        postRKstep_stuff<State_t>(start_state, FlowGrid::lambda_from_t(t_now), lambdas_did, integration_step_count, config.filename, config, verbose);
                        if constexpr(std::is_same<State<state_datatype>, State_t>::value) {
                            //utils::print("I'M A STATE!\n\n");
                            system.iteration = integration_step_count+1;
                        }
                        //else utils::print("I'M NOT A STATE!\n\n");
                        ++integration_step_count;
                        if(integration_step_count >= MAXSTP) {
                            if (mpi_world_rank()==0) utils::print("ODE solver reached maximal number of steps.");
                            break;
                        }
                    }
                    if (mpi_world_rank()==0) utils::print(" ODE solver finished with ", integration_step_count, " integration steps.\n\n");
                    return start_state;
                }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), ODE_solver_config::filename, ODE_solver_config::iter_start, ODE_solver_config::lambda_checkpoints, ODE_solver_config::max_stepResizing_attempts, mpi_world_rank(), and utils::print().
integrate_nonadaptive()
template<class Stepper , typename State_t , typename FlowGrid , class System > State_t boost::numeric::odeint::detail::integrate_nonadaptive (Stepper stepper, System system, State_t & start_state, double & t_now, double t_final, const vec< double > & lambdas_try, vec< double > & lambdas_did, const ODE_solver_config & config, const bool verbose)
Definition at line 663 of file ODE_solvers.hpp.
                {
                    size_t integration_step_count = config.iter_start;
                    double dt = 1e-10*sgn(t_final - t_now);
                    double dLambda;
                    while( less_with_sign( t_now, t_final, dt ) )
                    {
                        if( less_with_sign( t_final, t_now + dt, dt ) )
{
                            dt = t_final - t_now;
                        }
                        if (verbose and mpi_world_rank()==0) {
                            utils::print("ODE iteration number: \t", integration_step_count, "\n");
                        }
                        dt = FlowGrid::t_from_lambda(lambdas_try[integration_step_count + 1]) - t_now; // current step size
                        dLambda = lambdas_try[integration_step_count + 1] - lambdas_try[integration_step_count]; // current step size
                            //utils::print("t_now: ", t_now, " -- t_final: ", t_final, " -- dt: ", dt, "\n");
#ifdef REPARAMETRIZE_FLOWGRID
                        if (verbose and mpi_world_rank()==0) { utils::print("current flow parameter t_now: ", t_now, " -- t_final: ", t_final, " -- try step size dt: ", dt, "\n"); }
                        auto rhs = [&system](const State_t& state_in, State_t& dState_dt, double t) -> void {system(state_in, dState_dt, FlowGrid::lambda_from_t(t)); dState_dt *= FlowGrid::dlambda_dt(t);};
                        stepper.do_step( rhs, start_state, t_now, dt);
#else
                        double Lambda_now = FlowGrid::lambda_from_t(t_now);
                        double dLambda = FlowGrid::lambda_from_t(t_now+dt) -  Lambda_now;
                        if (verbose and mpi_world_rank()==0) { utils::print("current flow parameter Lambda_now: ", Lambda_now, " -- Lambda_final: ", FlowGrid::lambda_from_t(t_final), " -- try step size dLambda: ", dLambda, "\n"); }
                        //if (verbose and mpi_world_rank()==0) { utils::print("current flow parameter t_now: ", t_now, " -- t_final: ", t_final, " -- try step size dt: ", dt, "\n"); }
                        auto rhs = [&system](const State_t& state_in, State_t& dState_dt, double Lambda_in) -> void {system(state_in, dState_dt, Lambda_in);};
                        stepper.do_step( rhs, start_state, Lambda_now, dLambda);  // if successful: updates Lambda_now and dt; if failed: updates only dt
#endif
                        t_now = FlowGrid::t_from_lambda(lambdas_try[integration_step_count+1]);   // t in next step
                        lambdas_did[integration_step_count+1] = FlowGrid::lambda_from_t(t_now);
                        postRKstep_stuff<State_t>(start_state, FlowGrid::lambda_from_t(t_now), lambdas_did, integration_step_count, config.filename, config, verbose);
                        if constexpr(std::is_same<State<state_datatype>, State_t>::value) {
                            system.rk_step = 0;
                            system.iteration++;
                        }
                        ++integration_step_count;
                    }
                    if (verbose and mpi_world_rank()==0) {
                        utils::print(" ODE solver finished with ", integration_step_count, " integration steps.", "\n\n");
                    }
                    return start_state;
                }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), ODE_solver_config::filename, ODE_solver_config::iter_start, mpi_world_rank(), utils::print(), and sgn().