SIAM-Keldysh-mfRG: Spline< Q, rank, 1, pos_first_freq_index, DataContainer > Class Template Reference
Spline< Q, rank, 1, pos_first_freq_index, DataContainer > Class Template Reference
#include <InterpolatorSpline1D.hpp>
Public Types
using index_type = typename DataContainer::index_type
using frequencies_type = std::array<double, 1>
Public Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
using buffer_type = typename base_class::buffer_type
Public Member Functions
Spline ()
Spline (double Lambda, index_type dims)
void initInterpolator () const
void set_initializedInterpol (bool is_init) const
template<typename result_type >
result_type interpolate_spline (const frequencies_type &frequencies, const index_type &indices) const
Public Member Functions inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
DataContainer ()=default
DataContainer (double Lambda, dimensions_type dims, const fRG_config &config)
auto get_VertexFreqGrid () const -> const frequencyGrid_type &
Functions for getting and setting the frequency grid and its members.
void set_VertexFreqGrid (const frequencyGrid_type frequencyGrid)
template<unsigned int idim, typename std::enable_if_t<(idim< numberFrequencyDims), bool > = true>
double analyze_tails (const int index=0) const
buffer_type get_deriv_x (const buffer_type &dat) const
buffer_type get_deriv_y (const buffer_type &dat) const
buffer_type get_deriv_z (const buffer_type &dat) const
buffer_type get_deriv_xx () const
buffer_type get_deriv_yy () const
buffer_type get_deriv_zz () const
buffer_type get_deriv_xy () const
buffer_type get_deriv_xz () const
buffer_type get_deriv_yz () const
buffer_type get_deriv_xyz () const
auto get_deriv_max () const -> double
auto get_curvature_max () const -> double
template<typename gridType >
auto shrink_freq_box_impl (const gridType &freqGrid, const double rel_tail_threshold, const vec< double > &maxabs_along_x, const bool verbose) const -> gridType
auto shrink_freq_box (const double rel_tail_threshold, bool verbose=true, double constant=0.) const -> frequencyGrid_type
Public Member Functions inherited from dataContainerBase< Q, rank >
dataContainerBase ()=default
constructor:
dataContainerBase (const dimensions_type dims)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
dataContainerBase (const Types &... dims)
dataContainerBase (const buffer_type &data_in)
Q acc (const size_t flatIndex) const
Access data via flattened index.
void direct_set (const size_t flatIndex, Q value)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
Q val (const Types &... i) const
Returns value for a multiIndex.
Q val (const index_type &idx) const
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
const Q & at (const Types &... i) const
Returns reference to a value for a multiIndex.
template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true>
auto val_vectorized (const Types &... i) const -> Eigen::Matrix< Q, vecsize, 1 >
template<std::size_t freqrank, std::size_t vecsize>
auto val_vectorized (const index_type &idx) const -> Eigen::Matrix< Q, vecsize, 1 >
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
void setvert (const Q value, const Types &... i)
Sets a value at a multiIndex.
void setvert (const Q value, const index_type &idx)
template<std::size_t vecsize>
void setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > &value, const index_type &idx)
auto get_dims () const
const buffer_type & get_vec () const
Returns the buffer "data" containing the data.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void set_vec (const container &data_in)
Sets the the buffer "data".
void set_vec (const buffer_type &data_in)
void set_vec (const buffer_type &&data_in)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void add_vec (const container &summand)
Adds a vector to the data.
void add_vec (const buffer_type &summand)
constexpr auto eigen_segment (const index_type &start, const index_type &end)
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> get_values (const index_type &index) const
Public Attributes
bool initialized = false
Public Attributes inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
frequencyGrid_type frequencies
Protected Member Functions
void set_coeffs_from_b () const
known values of first or second derivative (corresponding to bd_type)
Protected Attributes
size_t n =0
size_t i_x = pos_first_freq_index
vec< Q > m_b = vec<Q>(n)
coeffs_type all_coefficients = coeffs_type(n, 4)
bd_type m_left = third_deriv
bd_type m_right = third_deriv
Q m_left_value = 0.0
set const?
Q m_right_value = 0.0
Protected Attributes inherited from dataContainerBase< Q, rank >
buffer_type data
Private Types
using weights_type = Eigen::Matrix<double, 4, 1>
using coeffs_type = Eigen::Matrix<Q, Eigen::Dynamic,4>
Private Member Functions
weights_type get_weights (int idx, double t) const
Additional Inherited Members
Protected Types inherited from DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
using base_class = dataContainerBase<Q, rank>
Protected Types inherited from dataContainerBase< Q, rank >
using buffer_type = multidimensional::multiarray<Q, rank>
using index_type = typename buffer_type::index_type
using dimensions_type = typename buffer_type::dimensions_type
Detailed Description
template<typename Q, size_t rank, my_index_t pos_first_freq_index, class DataContainer>
class Spline< Q, rank, 1, pos_first_freq_index, DataContainer >
Spline1D interpolation
Template Parameters
DataContainer contains vertex data and frequency grid frequencies. primary_grid computes derivative of data
Q double or comp
Definition at line 48 of file InterpolatorSpline1D.hpp.
Member Typedef Documentation
coeffs_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::coeffs_type = Eigen::Matrix<Q, Eigen::Dynamic,4> private
Definition at line 52 of file InterpolatorSpline1D.hpp.
frequencies_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::frequencies_type = std::array<double, 1>
Definition at line 73 of file InterpolatorSpline1D.hpp.
index_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::index_type = typename DataContainer::index_type
Definition at line 72 of file InterpolatorSpline1D.hpp.
weights_type
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > using Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::weights_type = Eigen::Matrix<double, 4, 1> private
Definition at line 50 of file InterpolatorSpline1D.hpp.
Constructor & Destructor Documentation
Spline() [1/2]
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::Spline () inline
Definition at line 75 of file InterpolatorSpline1D.hpp.
: initialized(false) {};
Spline() [2/2]
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::Spline (double Lambda, index_type dims) inline explicit
Definition at line 76 of file InterpolatorSpline1D.hpp.
            :   DataContainer(Lambda, dims), n(getFlatSize(DataContainer::get_dims()))//, i_x(1)
    {
        //this->initializeK1();
        //print("Size of all_coeffs:", all_coefficients.size(), "\n");
        //print("n::", n, "\n");
    }
Member Function Documentation
get_weights()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > auto Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::get_weights (int idx, double t) const private
Definition at line 262 of file InterpolatorSpline1D.hpp.
{
        double t_low = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(idx);
        //double t_high= DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(idx+1);
        double h = (t - t_low);
        //assert(h>-1e-10);
        //assert(t<t_high+1e-6);
        weights_type weights;
        weights << 1., h, h*h, h*h*h;
        return weights;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies.
initInterpolator()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::initInterpolator () const
Definition at line 143 of file InterpolatorSpline1D.hpp.
{
    // hermite cubic splines which are C^1 (cont. differentiable)
    // and derivatives are specified on each grid point
    // (here we use 3-point finite differences)
    // set b to match 1st order derivative finite difference
    /*
    for(int i=1; i<n-1; i++) {
        const double h  = m_x[i+1]-m_x[i];
        const double hl = m_x[i]-m_x[i-1];
        m_b[i] = -h / (hl*(hl+h)) * DataContainer::data[i - 1] + (h - hl) / (hl * h) * DataContainer::data[i]
                 + hl / (h*(hl+h)) * DataContainer::data[i + 1];
    }
    // boundary conditions determine b[0] and b[n-1]
    if(m_left==first_deriv) {
        m_b[0]=m_left_value;
    } else if(m_left==second_deriv) {
        const double h = m_x[1]-m_x[0];
        m_b[0]=0.5*(-m_b[1]-0.5*m_left_value*h+ 3.0 * (DataContainer::data[1] - DataContainer::data[0]) / h);  /// checked
    } else if (m_left==third_deriv) {
        const double h = m_x[1]-m_x[0];
        m_b[0]=-m_b[1]+m_left_value/6.*h*h+ 2.0 * (DataContainer::data[1] - DataContainer::data[0]) / h;  /// added by me
    } else {
        assert(false);
    }
    if(m_right==first_deriv) {
        m_b[n-1]=m_right_value;
        m_c[n-1]=0.0;
    } else if(m_right==second_deriv) {
        const double h = m_x[n-1]-m_x[n-2];
        m_b[n-1]=0.5*(-m_b[n-2]+0.5*m_right_value*h+ 3.0 * (DataContainer::data[n - 1] - DataContainer::data[n - 2]) / h); /// checked
        m_c[n-1]=0.5*m_right_value; /// m_d[n-1] is set to 0. Is this correct/necessary?
    } else if (m_right==third_deriv) {
        const double h = m_x[n-1]-m_x[n-2];
        m_b[n-1]=-m_b[n-2]-m_right_value/6.*h*h+ 2.0 * (DataContainer::data[n - 1] - DataContainer::data[n - 2]) / h;  /// added by me
        m_d[n-1]= DataContainer::data[n - 1] - DataContainer::data[n - 2] - m_b[n - 2]; /// ???
    } else {
        assert(false);
    }
    m_d[n-1]=0.0;
     */
    //n = DataContainer::data.size();
        m_b = vec<Q>(n);
        //m_c = vec<Q>(n);
        //m_d = vec<Q>(n);
        multidimensional::multiarray<Q,rank> temp = DataContainer::get_deriv_x();
    m_b = vec<Q>(temp.begin(), temp.end());
    // parameters c and d are determined by continuity and differentiability
    set_coeffs_from_b();
    //all_coefficients.col(0) = DataContainer::get_vec().get_elements();
    //for (int i = 0; i < n; i++) {
    //    all_coefficients(i,1) = m_b[i];
    //    all_coefficients(i,2) = m_c[i];
    //    all_coefficients(i,3) = m_d[i];
    //}
    initialized = true;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x().
interpolate_spline()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > template<typename result_type > result_type Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::interpolate_spline (const frequencies_type & frequencies, const index_type & indices) const
Definition at line 276 of file InterpolatorSpline1D.hpp.
{
    assert(initialized);
    double t;
    int idx=DataContainer::frequencies.  primary_grid.get_grid_index(t, frequencies[0]);
    index_type index_tmp = indices;
    index_tmp[pos_first_freq_index] = idx;
    int i_row = getFlatIndex<rank>(index_tmp, DataContainer::get_dims());
    weights_type weights = get_weights(idx, t);
    if constexpr(std::is_same_v<result_type,Q>) {
        Q result;
        Eigen::Matrix<Q, 1, 4> values = all_coefficients.row(i_row);
        result = (values * weights).eval()[0];
        //Q result_compare;
        //result_compare   =((m_d[::getFlatIndex<rank>(index_tmp, DataContainer::get_dims())]*h
        //                    + m_c[::getFlatIndex<rank>(index_tmp, DataContainer::get_dims())])*h
        //                    + m_b[::getFlatIndex<rank>(index_tmp, DataContainer::get_dims())])*h
        //    + DataContainer::data[::getFlatIndex<rank>(index_tmp, DataContainer::get_dims())];
        //assert(std::abs(result - result_compare) < 1e-10);
        assert(isfinite(result));
        //assert(std::abs(result) < 1e-10);
        return result;
    }
    else if constexpr(std::is_same_v<result_type,Eigen::Matrix<Q,result_type::RowsAtCompileTime,1>>){
        Eigen::Matrix<Q,result_type::RowsAtCompileTime,1> result;
        Eigen::Matrix<Q, result_type::RowsAtCompileTime, 4> values = all_coefficients.template block<result_type::RowsAtCompileTime,4>(i_row,0);
        result = (values * weights).eval();
        assert(result.allFinite());
        return result;
    }
    else {
        assert(false);
        result_type result;
        return result;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, and dataContainerBase< Q, rank >::get_dims().
set_coeffs_from_b()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_coeffs_from_b () const protected
known values of first or second derivative (corresponding to bd_type)
i=n_x-1 not treated (only used for extrapolation to the right)
spacing
Definition at line 106 of file InterpolatorSpline1D.hpp.
{
    size_t n_x = DataContainer::frequencies.  primary_grid.get_all_frequencies().size();
    size_t n_nonx = n/n_x;
    Eigen::Matrix<double,4,4> A;
    A << 1, 0, 0, 0,
         0, 0, 1, 0,
        -3, 3,-2,-1,
         2,-2, 1, 1;
    for(size_t i=0; i<n_nonx; i++) {
        for (size_t j=0; j<n_x-1; j++) {
            const double h  = DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(j+1)-DataContainer::frequencies.  primary_grid.get_auxiliary_gridpoint(j);
            int idx_base = ::rotateFlatIndex(i*n_x+j  , DataContainer::get_dims(), i_x);
            int idx_plus = ::rotateFlatIndex(i*n_x+j+1, DataContainer::get_dims(), i_x);
            Eigen::Matrix<Q,4,1> fs;
            fs << DataContainer::data[idx_base], DataContainer::data[idx_plus], m_b[idx_base]*h, m_b[idx_plus]*h;
            // from continuity and differentiability condition
            //m_c[idx_base] = (3.0 * (DataContainer::data[idx_plus] - DataContainer::data[idx_base]) / h - (2.0 * m_b[idx_base] + m_b[idx_plus]) ) / h;   /// checked
            // from differentiability condition
            //m_d[idx_base] = ( (m_b[idx_plus]-m_b[idx_base])/(3.0*h) - 2.0/3.0*m_c[idx_base] ) / h;
            all_coefficients.row(idx_base) = (A * fs).transpose();
            all_coefficients(idx_base,1) /= (h);
            all_coefficients(idx_base,2) /= (h*h);
            all_coefficients(idx_base,3) /= (h*h*h);
            //Q c_compare = all_coefficients(idx_base,2);
            //Q d_compare = all_coefficients(idx_base,3);
            //assert(std::abs(c_compare - m_c[idx_base]) < 1e-10 * (1. + std::abs(c_compare)));
            //assert(std::abs(d_compare - m_d[idx_base]) < 1e-10 * (1. + std::abs(d_compare)));
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, dataContainerBase< Q, rank >::get_dims(), and rotateFlatIndex().
set_initializedInterpol()
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > void Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_initializedInterpol (bool is_init) const inline
Definition at line 85 of file InterpolatorSpline1D.hpp.
{initialized = is_init;}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Member Data Documentation
all_coefficients
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > coeffs_type Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::all_coefficients = coeffs_type(n, 4) mutable protected
Definition at line 64 of file InterpolatorSpline1D.hpp.
i_x
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > size_t Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::i_x = pos_first_freq_index protected
Definition at line 62 of file InterpolatorSpline1D.hpp.
initialized
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bool Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::initialized = false mutable
Definition at line 57 of file InterpolatorSpline1D.hpp.
m_b
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > vec<Q> Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::m_b = vec<Q>(n) mutable protected
Definition at line 63 of file InterpolatorSpline1D.hpp.
m_left
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bd_type Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::m_left = third_deriv protected
Definition at line 66 of file InterpolatorSpline1D.hpp.
m_left_value
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Q Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::m_left_value = 0.0 protected
set const?
Definition at line 67 of file InterpolatorSpline1D.hpp.
m_right
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > bd_type Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::m_right = third_deriv protected
Definition at line 66 of file InterpolatorSpline1D.hpp.
m_right_value
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > Q Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::m_right_value = 0.0 protected
Definition at line 67 of file InterpolatorSpline1D.hpp.
n
template<typename Q , size_t rank, my_index_t pos_first_freq_index, class DataContainer > size_t Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::n =0 protected
Definition at line 61 of file InterpolatorSpline1D.hpp.
The documentation for this class was generated from the following file:
InterpolatorSpline1D.hpp