SIAM-Keldysh-mfRG: bubble_function.hpp File Reference
bubble_function.hpp File Reference
#include <cmath>
#include "../symmetries/Keldysh_symmetries.hpp"
#include "../correlation_functions/four_point/vertex.hpp"
#include "../correlation_functions/two_point/selfenergy.hpp"
#include "../correlation_functions/two_point/propagator.hpp"
#include "../integrator/integrator.hpp"
#include "../utilities/util.hpp"
#include "../utilities/mpi_setup.hpp"
#include "../asymptotic_corrections/correction_functions.hpp"
#include "../utilities/write_data2file.hpp"
#include "bubble.hpp"
#include "integrand.hpp"
Classes
class BubbleFunctionCalculator< channel, Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object >
Functions
template<typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object >
void bubble_function (vertexType_result &dgamma, const vertexType_left &vertex1, const vertexType_right &vertex2, const Bubble_Object &Pi, const char channel, const fRG_config &config, const std::array< bool, 3 > tobecomputed={true, true, true})
template<typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right >
void bubble_function (vertexType_result &dgamma, const vertexType_left &vertex1, const vertexType_right &vertex2, const Propagator< Q > &G, const Propagator< Q > &S, const char channel, const bool diff, const fRG_config &config, const std::array< bool, 3 > tobecomputed={true, true, true})
Function Documentation
bubble_function() [1/2]
template<typename vertexType_result , typename vertexType_left , typename vertexType_right , class Bubble_Object > void bubble_function (vertexType_result & dgamma, const vertexType_left & vertex1, const vertexType_right & vertex2, const Bubble_Object & Pi, const char channel, const fRG_config & config, const std::array< bool, 3 > tobecomputed = {true,true,true})
Function to connect two vertices with a Bubble, i.e. a propagator pair. Graphically in the a channel:
-->--|-----|--->---|-----|-->--
     | Γ_1 |   Π   | Γ_2 |
--<--|-----|---<---|-----|--<--
Template Parameters
vertexType_result Type of the vertex that results in the bubble computation.
vertexType_left Type of the vertex that enters as the left part of the computation.
vertexType_right Type of the vertex that enters as the right part of the computation.
Bubble_Object Type of the Bubble object to connect the two vertices
Parameters
dgamma Reference to the vertex that the result of the computation shall be added to.
vertex1 Reference to the left input vertex.
vertex2 Reference to the right input vertex.
Pi Reference to the Bubble.
channel Two-particle channel of the computation. Can be a, p, or t.
config Struct with essential parameters.
tobecomputed Array of three booleans, specifying what diagrammatic classes shall be computed.
Definition at line 1046 of file bubble_function.hpp.
                                                                       {true,true,true}){
    using Q = typename vertexType_result::base_type;
    if (channel == 'a') {
        BubbleFunctionCalculator<'a', Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object>
                BubbleComputer (dgamma, vertex1, vertex2, Pi, config.number_of_nodes,tobecomputed);
        BubbleComputer.perform_computation();
    }
    else if (channel == 'p') {
        BubbleFunctionCalculator<'p', Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object>
                BubbleComputer (dgamma, vertex1, vertex2, Pi, config.number_of_nodes,tobecomputed);
        BubbleComputer.perform_computation();
    }
    else if (channel == 't') {
        BubbleFunctionCalculator<'t', Q, vertexType_result, vertexType_left, vertexType_right, Bubble_Object>
                BubbleComputer (dgamma, vertex1, vertex2, Pi, config.number_of_nodes,tobecomputed);
        BubbleComputer.perform_computation();
    }
    //else {utils::print("Error! Incompatible channel given to bubble_function. Abort"); }
}
Referenced by calculate_dGammaC_left_insertion(), calculate_dGammaC_right_insertion(), calculate_dGammaL(), calculate_dGammaR(), calculate_dSigma_SOPT(), check_selfconsistency_of_K1K2(), compute_BSE(), compute_SDE_impl(), selfEnergyInSOPT(), susceptibilities_postprocessing(), vertexInFOPT(), vertexInSOPT(), vertexInTOPT(), and vertexOneLoopFlow().
bubble_function() [2/2]
template<typename Q , typename vertexType_result , typename vertexType_left , typename vertexType_right > void bubble_function (vertexType_result & dgamma, const vertexType_left & vertex1, const vertexType_right & vertex2, const Propagator< Q > & G, const Propagator< Q > & S, const char channel, const bool diff, const fRG_config & config, const std::array< bool, 3 > tobecomputed = {true,true,true})
Overload of the bubble_function in case no Bubble object has been initialized yet.
Template Parameters
Q Template parameter specifying the type of the data.
vertexType_result Type of the vertex that results in the bubble computation.
vertexType_left Type of the vertex that enters as the left part of the computation.
vertexType_right Type of the vertex that enters as the right part of the computation.
Parameters
dgamma Reference to the vertex that the result of the computation shall be added to.
vertex1 Reference to the left input vertex.
vertex2 Reference to the right input vertex.
G Propagator to be used for the Bubble.
S Single-scale propagator to be used for the Bubble. Only used if diff=true.
channel Two-particle channel of the computation. Can be a, p, or t.
diff Boolean specifying whether the Bubble is differentiated or not.
config Struct with essential parameters.
tobecomputed Array of three booleans, specifying what diagrammatic classes shall be computed.
Definition at line 1093 of file bubble_function.hpp.
                                                                                                                                                                          {true,true,true}){
    Bubble<Q> Pi(G, S, diff);
    bubble_function(dgamma, vertex1, vertex2, Pi, channel, config, tobecomputed);
}