SIAM-Keldysh-mfRG: DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type > Class Template Reference
DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type > Class Template Reference
#include <data_container.hpp>
Public Types
using index_type = typename base_class::index_type
using dimensions_type = typename base_class::dimensions_type
using buffer_type = typename base_class::buffer_type
Public Member Functions
DataContainer ()=default
DataContainer (double Lambda, dimensions_type dims, const fRG_config &config)
auto get_VertexFreqGrid () const -> const frequencyGrid_type &
Functions for getting and setting the frequency grid and its members.
void set_VertexFreqGrid (const frequencyGrid_type frequencyGrid)
template<unsigned int idim, typename std::enable_if_t<(idim< numberFrequencyDims), bool > = true>
double analyze_tails (const int index=0) const
buffer_type get_deriv_x (const buffer_type &dat) const
buffer_type get_deriv_y (const buffer_type &dat) const
buffer_type get_deriv_z (const buffer_type &dat) const
buffer_type get_deriv_xx () const
buffer_type get_deriv_yy () const
buffer_type get_deriv_zz () const
buffer_type get_deriv_xy () const
buffer_type get_deriv_xz () const
buffer_type get_deriv_yz () const
buffer_type get_deriv_xyz () const
auto get_deriv_max () const -> double
auto get_curvature_max () const -> double
template<typename gridType >
auto shrink_freq_box_impl (const gridType &freqGrid, const double rel_tail_threshold, const vec< double > &maxabs_along_x, const bool verbose) const -> gridType
auto shrink_freq_box (const double rel_tail_threshold, bool verbose=true, double constant=0.) const -> frequencyGrid_type
Public Member Functions inherited from dataContainerBase< Q, rank >
dataContainerBase ()=default
constructor:
dataContainerBase (const dimensions_type dims)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
dataContainerBase (const Types &... dims)
dataContainerBase (const buffer_type &data_in)
Q acc (const size_t flatIndex) const
Access data via flattened index.
void direct_set (const size_t flatIndex, Q value)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
Q val (const Types &... i) const
Returns value for a multiIndex.
Q val (const index_type &idx) const
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
const Q & at (const Types &... i) const
Returns reference to a value for a multiIndex.
template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true>
auto val_vectorized (const Types &... i) const -> Eigen::Matrix< Q, vecsize, 1 >
template<std::size_t freqrank, std::size_t vecsize>
auto val_vectorized (const index_type &idx) const -> Eigen::Matrix< Q, vecsize, 1 >
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
void setvert (const Q value, const Types &... i)
Sets a value at a multiIndex.
void setvert (const Q value, const index_type &idx)
template<std::size_t vecsize>
void setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > &value, const index_type &idx)
auto get_dims () const
const buffer_type & get_vec () const
Returns the buffer "data" containing the data.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void set_vec (const container &data_in)
Sets the the buffer "data".
void set_vec (const buffer_type &data_in)
void set_vec (const buffer_type &&data_in)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void add_vec (const container &summand)
Adds a vector to the data.
void add_vec (const buffer_type &summand)
constexpr auto eigen_segment (const index_type &start, const index_type &end)
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> get_values (const index_type &index) const
Public Attributes
frequencyGrid_type frequencies
Protected Types
using base_class = dataContainerBase<Q, rank>
Protected Types inherited from dataContainerBase< Q, rank >
using buffer_type = multidimensional::multiarray<Q, rank>
using index_type = typename buffer_type::index_type
using dimensions_type = typename buffer_type::dimensions_type
Friends
void test_PT4 (double Lambda, bool write_flag)
template<typename T >
void test_PT_state (std::string outputFileName, double Lambda, bool write_flag)
template<typename T >
void result_set_frequency_grids (State< T, false > &result, Buffer &buffer)
template<typename T >
void check_FDTs (const State< T, false > &state, bool verbose)
State< state_datatype, false > read_state_from_hdf (const H5std_string &filename, const int Lambda_it)
Read state from specified Lambda layer of hdf file.
Additional Inherited Members
Protected Attributes inherited from dataContainerBase< Q, rank >
buffer_type data
Detailed Description
template<typename Q, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type>
class DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >
Definition at line 174 of file data_container.hpp.
Member Typedef Documentation
base_class
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > using DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::base_class = dataContainerBase<Q, rank> protected
Definition at line 189 of file data_container.hpp.
buffer_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > using DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::buffer_type = typename base_class::buffer_type
Definition at line 193 of file data_container.hpp.
dimensions_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > using DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::dimensions_type = typename base_class::dimensions_type
Definition at line 192 of file data_container.hpp.
index_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > using DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::index_type = typename base_class::index_type
Definition at line 191 of file data_container.hpp.
Constructor & Destructor Documentation
DataContainer() [1/2]
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::DataContainer () default
DataContainer() [2/2]
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::DataContainer (double Lambda, dimensions_type dims, const fRG_config & config) inline explicit
Definition at line 198 of file data_container.hpp.
: base_class(dims), frequencies(Lambda, config) {};
Member Function Documentation
analyze_tails()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > template<unsigned int idim, typename std::enable_if_t<(idim< numberFrequencyDims), bool > = true> double DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::analyze_tails (const int index = 0) const inline
Definition at line 209 of file data_container.hpp.
{
            double maxabs_total = base_class::data.max_norm();
            vec<double> maxabs_along_w = maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint+idim);
            const size_t number_of_frequency_points_along_w = base_class::get_dims()[pos_first_freqpoint+idim];
            return maxabs_along_w[number_of_frequency_points_along_w - 1 - index] / maxabs_total;
        };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, dataContainerBase< Q, rank >::get_dims(), multidimensional::multiarray< T, depth >::max_norm(), and maxabs().
get_curvature_max()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > auto DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max () const -> double inline
Definition at line 296 of file data_container.hpp.
{
            if constexpr (numberFrequencyDims == 1) {
                double Kmax = base_class::get_vec().max_norm();
                buffer_type curvature = get_deriv_xx();
                double max = (     ::power2(curvature*(1/Kmax))
                ).max_norm();
                return max;
            }
            else if constexpr (numberFrequencyDims == 2) {
                const double Kmax = base_class::get_vec().max_norm();
                const buffer_type curvature_xx = get_deriv_xx();
                const buffer_type deriv_y = get_deriv_y(base_class::data);
                const buffer_type curvature_yy = get_deriv_y(deriv_y);
                const buffer_type curvature_xy = get_deriv_x(deriv_y);
                double max_K2 = (     ::power2(curvature_xx)
                                    + ::power2(curvature_yy)
                                    + ::power2(curvature_xy) * 2.
                ).max_norm() / (Kmax*Kmax);
                return max_K2;
            }
            else if constexpr (numberFrequencyDims == 3) {
                double Kmax = base_class::get_vec().max_norm();
                const buffer_type curvature_xx = get_deriv_xx();
                const buffer_type deriv_y = get_deriv_y(base_class::data);
                const buffer_type curvature_yy = get_deriv_y(deriv_y);
                const buffer_type curvature_xy = get_deriv_x(deriv_y);
                const buffer_type deriv_z = get_deriv_z(base_class::data);
                const buffer_type curvature_zz = get_deriv_z(deriv_z);
                const buffer_type curvature_xz = get_deriv_x(deriv_z);
                const buffer_type curvature_yz = get_deriv_y(deriv_z);
                double max_K3 = (     ::power2(curvature_xx)
                                    + ::power2(curvature_yy)
                                    + ::power2(curvature_zz)
                                    +(::power2(curvature_xy)
                                    + ::power2(curvature_xz)
                                    + ::power2(curvature_yz) )*2.
                ).max_norm() / (Kmax*Kmax);
                return max_K3;
            }
            else assert(false);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xx(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_y(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_z(), dataContainerBase< Q, rank >::get_vec(), multidimensional::multiarray< T, depth >::max_norm(), and power2().
get_deriv_max()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > auto DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max () const -> double inline
Definition at line 269 of file data_container.hpp.
{
            if constexpr (numberFrequencyDims == 1) {
                double Kmax = base_class::get_vec().max_norm();
                const buffer_type deriv = get_deriv_x(base_class::data);
                const vec<Q> deriv_vec = vec<Q>(deriv.begin(), deriv.end());
                double max = (::power2(deriv_vec * (1/Kmax))
                ).max_norm();
                return max;
            }
            else if constexpr (numberFrequencyDims == 2) {
                double Kmax = base_class::get_vec().max_norm();
                double max_K2 = (  ::power2(get_deriv_y(base_class::data) * (1/Kmax))
                                 + ::power2(get_deriv_x(base_class::data) * (1/Kmax))
                ).max_norm();
                return max_K2;
            }
            else if constexpr (numberFrequencyDims == 3) {
                double Kmax = base_class::get_vec().max_norm();
                double max_K3 = (  ::power2(get_deriv_z(base_class::data) * (1/Kmax))
                                 + ::power2(get_deriv_y(base_class::data) * (1/Kmax))
                                 + ::power2(get_deriv_x(base_class::data) * (1/Kmax))
                ).max_norm();
                return max_K3;
            }
            else assert(false);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_y(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_z(), dataContainerBase< Q, rank >::get_vec(), multidimensional::multiarray< T, depth >::max_norm(), and power2().
get_deriv_x()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_x (const buffer_type & dat) const inline
Definition at line 218 of file data_container.hpp.
{
            buffer_type result = ::partial_deriv<Q,rank>(dat, pos_first_freqpoint);
            return result;
        };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::initInterpolator(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::initInterpolator(), and Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_xx()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xx () const inline
Definition at line 231 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint  );
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint  );
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max().
get_deriv_xy()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xy () const inline
Definition at line 246 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint+1);
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint  );
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
Referenced by Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::initInterpolator(), and Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_xyz()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xyz () const inline
Definition at line 262 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint+2);
            buffer_type inter_result2= ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint+1);
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result2   , pos_first_freqpoint  );
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
Referenced by Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_xz()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xz () const inline
Definition at line 251 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint+2);
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint  );
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
Referenced by Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_y()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_y (const buffer_type & dat) const inline
Definition at line 222 of file data_container.hpp.
{
            buffer_type result = ::partial_deriv<Q,rank>(dat, pos_first_freqpoint+1);
            return result;
        };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::initInterpolator(), and Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_yy()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yy () const inline
Definition at line 236 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint+1);
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint+1);
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
get_deriv_yz()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yz () const inline
Definition at line 256 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint+1);
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint+2);
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
Referenced by Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_z()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_z (const buffer_type & dat) const inline
Definition at line 226 of file data_container.hpp.
{
            buffer_type result = ::partial_deriv<Q,rank>(dat, pos_first_freqpoint+2);
            return result;
        };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), and Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::initInterpolator().
get_deriv_zz()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > buffer_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_zz () const inline
Definition at line 241 of file data_container.hpp.
{
            buffer_type inter_result = ::partial_deriv<Q,rank>(base_class::data, pos_first_freqpoint+2);
            buffer_type result       = ::partial_deriv<Q,rank>(inter_result    , pos_first_freqpoint+2);
            return result;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
get_VertexFreqGrid()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > auto DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_VertexFreqGrid () const -> const frequencyGrid_type &
Functions for getting and setting the frequency grid and its members.
Definition at line 384 of file data_container.hpp.
{
        return frequencies;
    }
References DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies.
set_VertexFreqGrid()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > void DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::set_VertexFreqGrid (const frequencyGrid_type frequencyGrid)
Definition at line 390 of file data_container.hpp.
{
        frequencies = frequencyGrid;
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies.
shrink_freq_box()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > auto DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box (const double rel_tail_threshold, bool verbose = true, double constant = 0.) const -> frequencyGrid_type
Definition at line 399 of file data_container.hpp.
{
        if constexpr(numberFrequencyDims == 1) {
            frequencyGrid_type frequencies_new = frequencies;
            typename base_class::buffer_type data_tmp = base_class::data;
            double maxmax = (data_tmp - constant).max_norm();
            vec<double> maxabs_along_w = maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint) * (1 / maxmax);
            const double wmax_old = frequencies_new.  primary_grid.w_upper;
            //frequencies_new.  primary_grid = shrink_freq_box_impl(frequencies.  primary_grid, rel_tail_threshold, maxabs_along_w, verbose);
        if (verbose and mpi_world_rank() == 0)
            std::cout << "Shrinking frequency box in direction w from " << wmax_old << " to " << frequencies_new.  primary_grid.w_upper << std::endl;
        return frequencies_new;
        }
        else if constexpr(numberFrequencyDims == 2) {
            frequencyGrid_type frequencies_new = frequencies;
            double maxmax = base_class::data.max_norm();
            vec<double> maxabs_along_w = maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint  ) * (1 / maxmax);
            vec<double> maxabs_along_v = maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint+1) * (1 / maxmax);
            const double wmax_old = frequencies_new.  primary_grid.w_upper;
            const double vmax_old = frequencies_new.secondary_grid.w_upper;
            //frequencies_new.  primary_grid = shrink_freq_box_impl(frequencies.  primary_grid, rel_tail_threshold, maxabs_along_w, verbose);
            if (verbose and mpi_world_rank() == 0)
                std::cout << "Shrinking frequency box in direction w from " << wmax_old << " to " << frequencies_new.  primary_grid.w_upper << std::endl;
            if (GRID != 2) {
                //frequencies_new.secondary_grid = shrink_freq_box_impl(frequencies.secondary_grid, rel_tail_threshold, maxabs_along_v, verbose);
                if (verbose and mpi_world_rank() == 0)
                    std::cout << "Shrinking frequency box in direction v from " << vmax_old << " to " << frequencies_new.secondary_grid.w_upper << std::endl;
            }
            return frequencies_new;
        }
        else if constexpr(numberFrequencyDims == 3) {
            frequencyGrid_type frequencies_new = frequencies;
            double maxmax = base_class::data.max_norm();
            vec<double> maxabs_along_w = maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint  ) * (1 / maxmax);
            vec<double> maxabs_along_v = maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint+1) * (1 / maxmax);
            vec<double> maxabs_along_vp= maxabs(base_class::data, base_class::data.length(), pos_first_freqpoint+2) * (1 / maxmax);
            const double wmax_old = frequencies_new.  primary_grid.w_upper;
            const double vmax_old = frequencies_new.secondary_grid.w_upper;
            const double vpmax_old= frequencies_new. tertiary_grid.w_upper;
            //frequencies_new.  primary_grid = shrink_freq_box_impl(frequencies.  primary_grid, rel_tail_threshold, maxabs_along_w, verbose);
            if (verbose and mpi_world_rank() == 0)
                std::cout << "Shrinking frequency box in direction w from " << wmax_old << " to " << frequencies_new.  primary_grid.w_upper << std::endl;
            if (GRID != 2) {
                //frequencies_new.secondary_grid = shrink_freq_box_impl(frequencies.secondary_grid, rel_tail_threshold, maxabs_along_v, verbose);
                if (verbose and mpi_world_rank() == 0)
                    std::cout << "Shrinking frequency box in direction v from " << vmax_old << " to " << frequencies_new.secondary_grid.w_upper << std::endl;
                //frequencies_new.tertiary_grid = shrink_freq_box_impl(frequencies.tertiary_grid, rel_tail_threshold, maxabs_along_vp, verbose);
                if (verbose and mpi_world_rank() == 0)
                    std::cout << "Shrinking frequency box in direction v from " << vmax_old << " to " << frequencies_new.tertiary_grid.w_upper << std::endl;
            }
            return frequencies_new;
        }
        else {
            assert(false);
            return frequencyGrid_type(0);
        }
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies, GRID, multidimensional::multiarray< T, depth >::max_norm(), maxabs(), and mpi_world_rank().
shrink_freq_box_impl()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > template<typename gridType > auto DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box_impl (const gridType & freqGrid, const double rel_tail_threshold, const vec< double > & maxabs_along_x, const bool verbose) const -> gridType inline
Definition at line 341 of file data_container.hpp.
{
            const size_t number_of_frequency_points_along_w = maxabs_along_x.size();
            assert(freqGrid.get_all_frequencies().size() == maxabs_along_x.size());
            gridType frequencies_new = freqGrid;
            if (maxabs_along_x.max_norm() < 1e-20) return frequencies_new; // don't shrink if there is no data yet
            int index = -1;
            while (true) {
                if (maxabs_along_x[number_of_frequency_points_along_w - 1 - (index + 1)] >= rel_tail_threshold) break;
                index++;
            }
            if (index > -1) { // if the frequency box is too big, shrink to appropriate size
                double t_belowthresh = freqGrid.get_auxiliary_gridpoint(
                        index); // auxiliary frequency point before passing threshold
                double t_abovethresh = freqGrid.get_auxiliary_gridpoint(
                        index + 1); // auxiliary frequency point after  passing threshold
                double h = (rel_tail_threshold - maxabs_along_x[number_of_frequency_points_along_w - 1 - index]) * (t_abovethresh - t_belowthresh) /
                           (maxabs_along_x[number_of_frequency_points_along_w - 1 - (index + 1)] - maxabs_along_x[number_of_frequency_points_along_w - 1 - index]);
                const double safety = 0.9;
                frequencies_new.set_w_upper(std::abs(freqGrid.frequency_from_t(t_belowthresh + h * safety)));
            } else if (index == -1) { // if data on outermost grid point is too big, then enlarge the box OR print warning
                //double t_upper_new = 1 - maxmax*rel_tail_threshold * (1-freqGrid.t_upper) / (maxabs_along_x[maxabs_along_x.size() -1]);
                //double w_upper_new = frequencies_new.frequency_from_t(t_upper_new);
                //frequencies_new.set_w_upper(w_upper_new);
            }
            frequencies_new.initialize_grid();
            return frequencies_new;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Friends And Related Symbol Documentation
check_FDTs
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > template<typename T > void check_FDTs (const State< T, false > & state, bool verbose) friend
read_state_from_hdf
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > State< state_datatype, false > read_state_from_hdf (const H5std_string & filename, const int Lambda_it) friend
Read state from specified Lambda layer of hdf file.
check whether parameters in HDF file agree with parameters/master_parameters.hpp
Write used parameters for documentation purpose
check whether parameters in HDF file agree with parameters/master_parameters.hpp
Write used parameters for documentation purpose
Definition at line 61 of file hdf5_routines.c++.
{
    H5::H5File file_out = open_hdf_file_readOnly(filename);
    std::vector<double> Lambda;
    read_from_hdf_LambdaLayer<double>(file_out, LAMBDA_LIST, Lambda, Lambda_it);
    fRG_config config = read_config_from_hdf(filename);
    State<state_datatype,false> state(Lambda[0], config);
    std::vector<state_datatype> Sigma_H;
    read_from_hdf_LambdaLayer<state_datatype>(file_out, SELF_LIST, state.selfenergy.Sigma.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, HARTREE, Sigma_H, Lambda_it);
    state.selfenergy.asymp_val_R = Sigma_H[0];
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_irred, state.vertex.irred().bare, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_a, state.vertex.avertex().K1.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_p, state.vertex.pvertex().K1.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K1_t, state.vertex.tvertex().K1.data, Lambda_it);
#if MAX_DIAG_CLASS>1
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_a, state.vertex.avertex().K2.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_p, state.vertex.pvertex().K2.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2_t, state.vertex.tvertex().K2.data, Lambda_it);
#if DEBUG_SYMMETRIES
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_a, state.vertex.avertex().K2b.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_p, state.vertex.pvertex().K2b.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K2b_t, state.vertex.tvertex().K2b.data, Lambda_it);
#endif
#endif
#if MAX_DIAG_CLASS>2
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_a, state.vertex.avertex().K3.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_p, state.vertex.pvertex().K3.data, Lambda_it);
    read_from_hdf_LambdaLayer<state_datatype>(file_out, DATASET_K3_t, state.vertex.tvertex().K3.data, Lambda_it);
#endif
    H5::Group group_freqparams(file_out.openGroup(FREQ_PARAMS));
    H5::Group group_freqparams_ffreqs (group_freqparams.openGroup(FFREQS_LIST ));
    H5::Group group_freqparams_bfreqsa (group_freqparams.openGroup(BFREQS_LISTa ));
    H5::Group group_freqparams_bfreqsp (group_freqparams.openGroup(BFREQS_LISTp ));
    H5::Group group_freqparams_bfreqst (group_freqparams.openGroup(BFREQS_LISTt ));
    H5::Group group_freqparams_bfreqs2a(group_freqparams.openGroup(BFREQS2_LISTa));
    H5::Group group_freqparams_bfreqs2p(group_freqparams.openGroup(BFREQS2_LISTp));
    H5::Group group_freqparams_bfreqs2t(group_freqparams.openGroup(BFREQS2_LISTt));
    H5::Group group_freqparams_bfreqs2ba(group_freqparams.openGroup(BFREQS2b_LISTa));
    H5::Group group_freqparams_bfreqs2bp(group_freqparams.openGroup(BFREQS2b_LISTp));
    H5::Group group_freqparams_bfreqs2bt(group_freqparams.openGroup(BFREQS2b_LISTt));
    H5::Group group_freqparams_bfreqs3a(group_freqparams.openGroup(BFREQS3_LISTa));
    H5::Group group_freqparams_bfreqs3p(group_freqparams.openGroup(BFREQS3_LISTp));
    H5::Group group_freqparams_bfreqs3t(group_freqparams.openGroup(BFREQS3_LISTt));
    H5::Group group_freqparams_ffreqs2a(group_freqparams.openGroup(FFREQS2_LISTa));
    H5::Group group_freqparams_ffreqs2p(group_freqparams.openGroup(FFREQS2_LISTp));
    H5::Group group_freqparams_ffreqs2t(group_freqparams.openGroup(FFREQS2_LISTt));
    H5::Group group_freqparams_ffreqs2ba(group_freqparams.openGroup(FFREQS2b_LISTa));
    H5::Group group_freqparams_ffreqs2bp(group_freqparams.openGroup(FFREQS2b_LISTp));
    H5::Group group_freqparams_ffreqs2bt(group_freqparams.openGroup(FFREQS2b_LISTt));
    H5::Group group_freqparams_ffreqs3a(group_freqparams.openGroup(FFREQS3_LISTa));
    H5::Group group_freqparams_ffreqs3p(group_freqparams.openGroup(FFREQS3_LISTp));
    H5::Group group_freqparams_ffreqs3t(group_freqparams.openGroup(FFREQS3_LISTt));
    H5::Group group_freqparams_ffreqs3a2(group_freqparams.openGroup(FFREQS3_LISTa2));
    H5::Group group_freqparams_ffreqs3p2(group_freqparams.openGroup(FFREQS3_LISTp2));
    H5::Group group_freqparams_ffreqs3t2(group_freqparams.openGroup(FFREQS3_LISTt2));
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs , state.selfenergy.Sigma.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqsa, state.vertex.avertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqsp, state.vertex.pvertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqst, state.vertex.tvertex().K1.frequencies.  primary_grid, Lambda_it, Lambda[0]);
#if MAX_DIAG_CLASS>1
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2a,state.vertex.avertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2p,state.vertex.pvertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2t,state.vertex.tvertex().K2.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2a,state.vertex.avertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2p,state.vertex.pvertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2t,state.vertex.tvertex().K2.frequencies.secondary_grid, Lambda_it, Lambda[0]);
#if DEBUG_SYMMETRIES
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2ba,state.vertex.avertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2bp,state.vertex.pvertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs2bt,state.vertex.tvertex().K2b.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2ba,state.vertex.avertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2bp,state.vertex.pvertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs2bt,state.vertex.tvertex().K2b.frequencies.secondary_grid, Lambda_it, Lambda[0]);
#endif
#endif
#if MAX_DIAG_CLASS>2
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3a, state.vertex.avertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3p, state.vertex.pvertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_bfreqs3t, state.vertex.tvertex().K3.frequencies.  primary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3a, state.vertex.avertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3p, state.vertex.pvertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3t, state.vertex.tvertex().K3.frequencies.secondary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3a2,state.vertex.avertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3p2,state.vertex.pvertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
    hdf5_impl::init_freqgrid_from_hdf_LambdaLayer(group_freqparams_ffreqs3t2,state.vertex.tvertex().K3.frequencies. tertiary_grid, Lambda_it, Lambda[0]);
#endif
        int REG_loaded, MAX_DIAG_CLASS_loaded, N_LOOPS_loaded, GRID_loaded;
        double glb_Gamma_loaded, glb_T_loaded, glb_mu_loaded, glb_U_loaded, glb_epsilon_loaded, glb_V_loaded;
    H5::Group group_params(file_out.openGroup(PARAM_LIST));
    read_from_hdf(group_params, "REG", REG_loaded);
    read_from_hdf(group_params, "MAX_DIAG_CLASS", MAX_DIAG_CLASS_loaded);
    read_from_hdf(group_params, "mu", glb_mu_loaded);
    read_from_hdf(group_params, "V", glb_V_loaded);
    read_from_hdf(group_params, "GRID", GRID_loaded);
    bool are_parameters_identical = REG == REG_loaded and
            MAX_DIAG_CLASS == MAX_DIAG_CLASS_loaded and
            glb_mu == glb_mu_loaded and
            glb_V == glb_V_loaded and
            GRID == GRID_loaded;
    if (!are_parameters_identical) {
        utils::print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
        utils::print("\t Warning!: \t Parameters of executable do not agree with those in HDF file ", filename, "\n");
        const vec<bool> is_identical_parameter = {
                MAX_DIAG_CLASS == MAX_DIAG_CLASS_loaded
                ,glb_mu == glb_mu_loaded
                ,glb_V == glb_V_loaded
                ,GRID == GRID_loaded
        };
        const vec<std::string> parameter_names = {
                "MAX_DIAG_CLASS"
                ,"glb_mu"
                ,"glb_V"
                ,"GRID"
        };
        for (int i = 0; i < is_identical_parameter.size(); i++){
            if (!is_identical_parameter[i]) utils::print("\t parameter ", parameter_names[i], " is different.\n");
        }
        utils::print("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n");
    }
    file_out.close();
    return state;
}
result_set_frequency_grids
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > template<typename T > void result_set_frequency_grids (State< T, false > & result, Buffer & buffer) friend
test_PT4
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > void test_PT4 (double Lambda, bool write_flag) friend
test_PT_state
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > template<typename T > void test_PT_state (std::string outputFileName, double Lambda, bool write_flag) friend
Member Data Documentation
frequencies
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename frequencyGrid_type > frequencyGrid_type DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::frequencies
Definition at line 195 of file data_container.hpp.
Referenced by Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_VertexFreqGrid(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::get_weights(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_coeffs_from_b(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::set_VertexFreqGrid(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box().
The documentation for this class was generated from the following file:
data_container.hpp