SIAM-Keldysh-mfRG: getIntegrand Namespace Reference
getIntegrand Namespace Reference
Functions
plot_integrand (ax, filename, kwargs={})
plot_integrand_alli2 (ax, filename_pt1, filename_pt2, kwargs={})
For Keldysh bubble: Sum up all inner Keldysh indices.
compile_stuff (string cpp_target)
compile_get_integrand_Gamma1_Pi_Gamma2_Cpp ()
compile_get_integrand_dGamma_1loop_Cpp ()
compile_get_integrand_dGamma_1loop_fromFlow_Cpp ()
compile_get_integrand_dGammaL_Cpp ()
compile_get_integrand_dGammaC_Cpp ()
get_integrand_Gamma1_Pi_Gamma2 (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, filename, Gamma0_is_left)
get_integrand_dGamma_1loop_fromFlow (exe_dir, data_dir, filename, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in)
get_integrand_dGamma_1loop (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in)
get_integrand_dGammaL (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, i_loop)
get_integrand_dGammaC (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, i_loop)
get_integrand_filename_Gamma1_Pi_Gamma2 (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, Gamma0_is_left)
get_integrand_filename_dGamma_1loop (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in)
get_integrand_filename_dGammaL (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, i_loop)
get_integrand_filename_dGammaC (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, i_loop)
Variables
str exe_dir = "/tmp/tmp.0CYjLbB99I/tests/"
str data_dir = "/tmp/tmp.0CYjLbB99I/Data_KF/"
int it_Lambda = 10
int rkStep = 0
int k_class_int = 3
str channel = 'a'
int i0 = 1
int i2 = 0
int spin = 0
int w = 0
int v = 0
int vp = 0
int i_in = 0
str filename = "Psi_SDE_a_l"
int Gamma0_is_left = 0
integrandFilename = get_integrand_filename_Gamma1_Pi_Gamma2(data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, Gamma0_is_left)
fig0
axs0
num
nrows
ncols
Function Documentation
compile_get_integrand_dGamma_1loop_Cpp()
getIntegrand.compile_get_integrand_dGamma_1loop_Cpp ()
Definition at line 91 of file getIntegrand.py.
def compile_get_integrand_dGamma_1loop_Cpp():
    cpp_target = "get_integrand_dGamma_1loop"
    compile_stuff(cpp_target)
References compile_stuff().
compile_get_integrand_dGamma_1loop_fromFlow_Cpp()
getIntegrand.compile_get_integrand_dGamma_1loop_fromFlow_Cpp ()
Definition at line 95 of file getIntegrand.py.
def compile_get_integrand_dGamma_1loop_fromFlow_Cpp():
    text = """
#!/bin/bash
module load hdf5/1.10.5-gcc
export LANG=C
export LC_ALL=C
MPI="-I/usr/include/mpi/"
HDF5="-I/software/opt/bionic/x86_64/hdf5/1.10.5-gcc/include -L/software/opt/bionic/x86_64/hdf5/1.10.5-gcc/lib -lhdf5 -lhdf5_cpp"
FFTW="-lfftw3"
mpiCC --std=c++17  ../tests/get_integrand_dGamma_1loop_fromFlow.cpp -o ../tests/get_integrand_dGamma_1loop_fromFlow.o -fopenmp $MPI $HDF5 $FFTW -lgsl -lgslcblas
    """
    f = open("./compile_asc_saveIntegrand.sh", "w")
    f.write(text)
    close_hdf_file(f)
    print("Compiling get_integrand_dGamma_1loop_fromFlow")
    os.system("bash ./compile_asc_saveIntegrand.sh")
    os.system("rm ./compile_asc_saveIntegrand.sh")
References close_hdf_file(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
compile_get_integrand_dGammaC_Cpp()
getIntegrand.compile_get_integrand_dGammaC_Cpp ()
Definition at line 143 of file getIntegrand.py.
def compile_get_integrand_dGammaC_Cpp():
    text = """
#!/bin/bash
module load hdf5/1.10.5-gcc
export LANG=C
export LC_ALL=C
MPI="-I/usr/include/mpi/"
HDF5="-I/software/opt/bionic/x86_64/hdf5/1.10.5-gcc/include -L/software/opt/bionic/x86_64/hdf5/1.10.5-gcc/lib -lhdf5 -lhdf5_cpp"
FFTW="-lfftw3"
mpiCC --std=c++17  ../tests/get_integrand_dGammaC.cpp -o ../tests/get_integrand_dGammaC.o -fopenmp $MPI $HDF5 $FFTW
    """
    f = open("./compile_asc_saveIntegrand.sh", "w")
    f.write(text)
    close_hdf_file(f)
    print("Compiling get_integrand_dGammaC")
    os.system("bash ./compile_asc_saveIntegrand.sh")
    os.system("rm ./compile_asc_saveIntegrand.sh")
References close_hdf_file(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
compile_get_integrand_dGammaL_Cpp()
getIntegrand.compile_get_integrand_dGammaL_Cpp ()
Definition at line 119 of file getIntegrand.py.
def compile_get_integrand_dGammaL_Cpp():
    text = """
#!/bin/bash
module load hdf5/1.10.5-gcc
export LANG=C
export LC_ALL=C
MPI="-I/usr/include/mpi/"
HDF5="-I/software/opt/bionic/x86_64/hdf5/1.10.5-gcc/include -L/software/opt/bionic/x86_64/hdf5/1.10.5-gcc/lib -lhdf5 -lhdf5_cpp"
FFTW="-lfftw3"
mpiCC --std=c++17  ../tests/get_integrand_dGammaL.cpp -o ../tests/get_integrand_dGammaL.o -fopenmp $MPI $HDF5 $FFTW
    """
    f = open("./compile_asc_saveIntegrand.sh", "w")
    f.write(text)
    close_hdf_file(f)
    print("Compiling get_integrand_dGammaL")
    os.system("bash ./compile_asc_saveIntegrand.sh")
    os.system("rm ./compile_asc_saveIntegrand.sh")
References close_hdf_file(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
compile_get_integrand_Gamma1_Pi_Gamma2_Cpp()
getIntegrand.compile_get_integrand_Gamma1_Pi_Gamma2_Cpp ()
Definition at line 87 of file getIntegrand.py.
def compile_get_integrand_Gamma1_Pi_Gamma2_Cpp():
    cpp_target = "get_integrand_Gamma1_Pi_Gamma2"
    compile_stuff(cpp_target)
References compile_stuff().
compile_stuff()
getIntegrand.compile_stuff (string cpp_target)
Definition at line 43 of file getIntegrand.py.
def compile_stuff(cpp_target: string):
    text = """
#!/bin/bash
# load necessary modules
export CLUSTER=ASC
module load cmake
export LANG=C
export LC_ALL=C
dir_path=$(dirname "$(realpath "$0")")    # directory of this script
src_dir="$dir_path"/..                    # source directory
build_dir="$src_dir"/build                # build directory
mkdir "$build_dir"
# navigate to the directory with the CMakeLists.txt file
cd "$build_dir" || exit
# load cmake project
cmake -S$src_dir -B$build_dir
# build
TARGET=""" + cpp_target + """
cmake --build . --target $TARGET
mv ./$TARGET $src_dir
GREEN='\033[1;32m' # green
NC='\033[0m' # no color
echo -e "\n Moved executable ${GREEN}$TARGET ${NC}to Keldysh_mfRG source directory.\n"
    """
    f = open("./compile_asc_saveIntegrand.sh", "w")
    f.write(text)
    close_hdf_file(f)
    print("Compiling " + cpp_target)
    os.system("bash ./compile_asc_saveIntegrand.sh")
    os.system("rm ./compile_asc_saveIntegrand.sh")
References close_hdf_file(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Referenced by compile_get_integrand_dGamma_1loop_Cpp(), and compile_get_integrand_Gamma1_Pi_Gamma2_Cpp().
get_integrand_dGamma_1loop()
getIntegrand.get_integrand_dGamma_1loop (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in)
Definition at line 175 of file getIntegrand.py.
def get_integrand_dGamma_1loop(exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in):
    cmd = exe_dir + 'get_integrand_dGamma_1loop.o ' + data_dir + " " + str(it_Lambda) + " " + str(rkStep) + " " + str(k_class_int) + " " + str(channel) + " " + str(i0) + " " + str(i2)  + " " + str(spin) + " {}".format(w) + " {}".format(v) + " {}".format(vp) + " " + str(i_in)
    os.system(cmd)
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_dGamma_1loop_fromFlow()
getIntegrand.get_integrand_dGamma_1loop_fromFlow (exe_dir, data_dir, filename, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in)
Definition at line 171 of file getIntegrand.py.
def get_integrand_dGamma_1loop_fromFlow(exe_dir, data_dir, filename, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in):
    cmd = exe_dir + 'get_integrand_dGamma_1loop_fromFlow.o ' + data_dir + " " + filename + " " + str(it_Lambda) + " " + str(rkStep) + " " + str(k_class_int) + " " + str(channel) + " " + str(i0) + " " + str(i2)  + " " + str(spin) + " {}".format(w) + " {}".format(v) + " {}".format(vp) + " " + str(i_in)
    os.system(cmd)
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_dGammaC()
getIntegrand.get_integrand_dGammaC (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, i_loop)
Definition at line 183 of file getIntegrand.py.
def get_integrand_dGammaC(exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, i_loop):
    cmd = exe_dir + 'get_integrand_dGammaC.o ' + data_dir + " " + str(it_Lambda) + " " + str(rkStep) + " " + str(k_class_int) + " " + str(channel) + " " + str(i0) + " " + str(i2)  + " " + str(spin) + " {}".format(w) + " {}".format(v) + " {}".format(vp) + " " + str(i_in) + " " + str(i_loop)
    os.system(cmd)
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_dGammaL()
getIntegrand.get_integrand_dGammaL (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, i_loop)
Definition at line 179 of file getIntegrand.py.
def get_integrand_dGammaL(exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, i_loop):
    cmd = exe_dir + 'get_integrand_dGammaL.o ' + data_dir + " " + str(it_Lambda) + " " + str(rkStep) + " " + str(k_class_int) + " " + str(channel) + " " + str(i0) + " " + str(i2)  + " " + str(spin) + " {}".format(w) + " {}".format(v) + " {}".format(vp) + " " + str(i_in) + " " + str(i_loop)
    os.system(cmd)
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_filename_dGamma_1loop()
getIntegrand.get_integrand_filename_dGamma_1loop (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in)
Definition at line 206 of file getIntegrand.py.
def get_integrand_filename_dGamma_1loop(data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in):
    if k_class_int == 0:
        k_class = '1'
    elif k_class_int == 1:
        k_class = '2'
    elif k_class_int == 3:
        k_class = '3'
    else:
        raise Exception("k_class_int " + str(k_class_int) + "not allowed!")
    filename = data_dir + "integrands/dGamma1Loop_iLambda" + str(1) + "_RKstep" + str(rkStep) + "integrand_K" + k_class + channel + "_i0=" + str(i0) + "_i2=" + str(i2) + "_w={:.6f}".format(w)
    if k_class == '2':
        filename = filename + "_v={:.6f}".format(v)
    if k_class == '3':
        filename = filename + "_vp={:.6f}".format(v)
    filename = filename + ".h5"
    return filename
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_filename_dGammaC()
getIntegrand.get_integrand_filename_dGammaC (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, i_loop)
Definition at line 242 of file getIntegrand.py.
def get_integrand_filename_dGammaC(data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, i_loop):
    if k_class_int == 0:
        k_class = '1'
    elif k_class_int == 1:
        k_class = '2'
    elif k_class_int == 3:
        k_class = '3'
    else:
        raise Exception("k_class_int " + str(k_class_int) + "not allowed!")
    filename = data_dir + "integrands/dGammaC_left_insertion_iLambda" + str(1) + "_RKstep" + str(rkStep) + "_iLoop" + str(i_loop) + "integrand_K" + k_class + channel + "_i0=" + str(i0) + "_i2=" + str(i2) + "_w={:.6f}".format(w)
    if k_class == '2':
        filename = filename + "_v={:.6f}".format(v)
    if k_class == '3':
        filename = filename + "_vp={:.6f}".format(v)
    filename = filename + ".h5"
    return filename
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_filename_dGammaL()
getIntegrand.get_integrand_filename_dGammaL (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, i_loop)
Definition at line 224 of file getIntegrand.py.
def get_integrand_filename_dGammaL(data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, i_loop):
    if k_class_int == 0:
        k_class = '1'
    elif k_class_int == 1:
        k_class = '2'
    elif k_class_int == 3:
        k_class = '3'
    else:
        raise Exception("k_class_int " + str(k_class_int) + "not allowed!")
    filename = data_dir + "integrands/dGammaL_iLambda" + str(1) + "_RKstep" + str(rkStep) + "_iLoop" + str(i_loop) + "integrand_K" + k_class + channel + "_i0=" + str(i0) + "_i2=" + str(i2) + "_w={:.6f}".format(w)
    if k_class == '2':
        filename = filename + "_v={:.6f}".format(v)
    if k_class == '3':
        filename = filename + "_vp={:.6f}".format(v)
    filename = filename + ".h5"
    return filename
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_filename_Gamma1_Pi_Gamma2()
getIntegrand.get_integrand_filename_Gamma1_Pi_Gamma2 (data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, Gamma0_is_left)
Definition at line 188 of file getIntegrand.py.
def get_integrand_filename_Gamma1_Pi_Gamma2(data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, Gamma0_is_left):
    if k_class_int == 0:
        k_class = '1'
    elif k_class_int == 1:
        k_class = '2'
    elif k_class_int == 3:
        k_class = '3'
    else:
        raise Exception("k_class_int " + str(k_class_int) + "not allowed!")
    filename = data_dir + "integrands/Gamma1_Pi_Gamma2_" + "Gamm0left=" + str(Gamma0_is_left) + "integrand_K" + k_class + channel + "_i0=" + str(i0) + "_i2=" + str(i2) + "_w={:.6f}".format(w)
    if k_class == '2':
        filename = filename + "_v={:.6f}".format(v)
    if k_class == '3':
        filename = filename + "_vp={:.6f}".format(v)
    filename = filename + ".h5"
    return filename
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
get_integrand_Gamma1_Pi_Gamma2()
getIntegrand.get_integrand_Gamma1_Pi_Gamma2 (exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, filename, Gamma0_is_left)
Definition at line 167 of file getIntegrand.py.
def get_integrand_Gamma1_Pi_Gamma2(exe_dir, data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, spin, w, v, vp, i_in, filename, Gamma0_is_left):
    cmd = exe_dir + 'get_integrand_dGamma_1loop.o ' + data_dir + " " + str(it_Lambda) + " " + str(rkStep) + " " + str(k_class_int) + " " + str(channel) + " " + str(i0) + " " + str(i2)  + " " + str(spin) + " {}".format(w) + " {}".format(v) + " {}".format(vp) + " " + str(i_in) + " " + filename + " " + str(Gamma0_is_left)
    os.system(cmd)
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
plot_integrand()
getIntegrand.plot_integrand (ax, filename, kwargs = {})
Definition at line 19 of file getIntegrand.py.
def plot_integrand(ax, filename, kwargs={}):
    with h5py.File(filename, 'r') as f:
        freqs = np.array(f['v'])
        integrand_re = np.array(f['integrand_re'])
        integrand_im = np.array(f['integrand_im'])
    ax.plot(freqs, integrand_re, **kwargs)
    ax.plot(freqs, integrand_im, **kwargs)
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
plot_integrand_alli2()
getIntegrand.plot_integrand_alli2 (ax, filename_pt1, filename_pt2, kwargs = {})
For Keldysh bubble: Sum up all inner Keldysh indices.
Definition at line 28 of file getIntegrand.py.
def plot_integrand_alli2(ax, filename_pt1, filename_pt2, kwargs={}):
    with h5py.File(filename_pt1 + "i2=" + str(0) + filename_pt2, 'r') as f:
        freqs = np.array(f['v'])
        integrand_re = np.array(f['integrand_re'])
        integrand_im = np.array(f['integrand_im'])
    close_hdf_file(f)
    for i in range(1,10):
        with h5py.File(filename_pt1 + "i2=" + str(i) + filename_pt2, 'r') as f:
            freqs += np.array(f['v'])
            integrand_re += np.array(f['integrand_re'])
            integrand_im += np.array(f['integrand_im'])
        close_hdf_file(f)
    ax.plot(freqs, integrand_re, **kwargs)
    ax.plot(freqs, integrand_im, **kwargs)
References close_hdf_file(), and correctionFunctionBubble_REG3_Matsubara_PHS_diff().
Variable Documentation
axs0
getIntegrand.axs0
Definition at line 284 of file getIntegrand.py.
channel
str getIntegrand.channel = 'a'
Definition at line 267 of file getIntegrand.py.
data_dir
str getIntegrand.data_dir = "/tmp/tmp.0CYjLbB99I/Data_KF/"
Definition at line 263 of file getIntegrand.py.
exe_dir
str getIntegrand.exe_dir = "/tmp/tmp.0CYjLbB99I/tests/"
Definition at line 260 of file getIntegrand.py.
fig0
getIntegrand.fig0
Definition at line 284 of file getIntegrand.py.
filename
str getIntegrand.filename = "Psi_SDE_a_l"
Definition at line 279 of file getIntegrand.py.
Gamma0_is_left
int getIntegrand.Gamma0_is_left = 0
Definition at line 280 of file getIntegrand.py.
i0
int getIntegrand.i0 = 1
Definition at line 268 of file getIntegrand.py.
i2
int getIntegrand.i2 = 0
Definition at line 269 of file getIntegrand.py.
i_in
int getIntegrand.i_in = 0
Definition at line 274 of file getIntegrand.py.
integrandFilename
getIntegrand.integrandFilename = get_integrand_filename_Gamma1_Pi_Gamma2(data_dir, it_Lambda, rkStep, k_class_int, channel, i0, i2, w, v, vp, i_in, Gamma0_is_left)
Definition at line 283 of file getIntegrand.py.
it_Lambda
int getIntegrand.it_Lambda = 10
Definition at line 264 of file getIntegrand.py.
k_class_int
int getIntegrand.k_class_int = 3
Definition at line 266 of file getIntegrand.py.
ncols
getIntegrand.ncols
Definition at line 284 of file getIntegrand.py.
nrows
getIntegrand.nrows
Definition at line 284 of file getIntegrand.py.
num
getIntegrand.num
Definition at line 284 of file getIntegrand.py.
rkStep
int getIntegrand.rkStep = 0
Definition at line 265 of file getIntegrand.py.
spin
int getIntegrand.spin = 0
Definition at line 270 of file getIntegrand.py.
v
int getIntegrand.v = 0
Definition at line 272 of file getIntegrand.py.
vp
int getIntegrand.vp = 0
Definition at line 273 of file getIntegrand.py.
w
int getIntegrand.w = 0
Definition at line 271 of file getIntegrand.py.