SIAM-Keldysh-mfRG: Propagator< Q > Class Template Reference
Propagator< Q > Class Template Reference
#include <propagator.hpp>
Public Member Functions
Propagator (double Lambda_in, char type_in, const fRG_config &config)
Propagator (double Lambda_in, const SelfEnergy< Q > &self_in, char type_in, const fRG_config &config)
Propagator (double Lambda_in, const SelfEnergy< Q > &self_in, const SelfEnergy< Q > &diffSelf_in, char type_in, const fRG_config &config)
auto valsmooth (int iK, freqType v, int i_in) const -> Q
template<typename return_type >
auto valsmooth_vectorized (freqType v, int i_in) const -> return_type
void save_propagator_values (const std::string &filename, const rvec &frequencies) const
auto GR (double v, int i_in) const -> Q
auto GK (double v, int i_in) const -> Q
auto SR (double v, int i_in) const -> Q
auto SK (double v, int i_in) const -> Q
Q Katanin_R (double v, int i_in) const
Q Katanin_K (double v, int i_in) const
auto GM (freqType v, int i_in) const -> Q
auto SM (freqType v, int i_in) const -> Q
auto norm () const -> double
Q G0M_inv (freqType v, int i_in) const
Q G0M_inv_SIAM (freqType v, int i_in) const
Q G0R_inv (freqType v, int i_in) const
Q G0R_inv_SIAM (freqType v, int i_in) const
Q GR_REG1 (freqType v, int i_in) const
Q SR_REG1 (freqType v, int i_in) const
Q GM_REG1 (freqType v, int i_in) const
Q SM_REG1 (freqType v, int i_in) const
Q SM_REG1_FPP (double v, double ksquared, int i_in) const
Q GR_REG2 (freqType v, int i_in) const
Q SR_REG2 (freqType v, int i_in) const
Q GM_REG2 (freqType v, int i_in) const
Q SM_REG2 (freqType v, int i_in) const
Q GR_REG3 (freqType v, int i_in) const
Q SR_REG3 (freqType v, int i_in) const
Q GM_REG3 (freqType v, int i_in) const
Q SM_REG3 (freqType v, int i_in) const
Q GR_REG4 (freqType v, int i_in) const
Q SR_REG4 (freqType v, int i_in) const
Q GM_REG4 (freqType v, int i_in) const
Q SM_REG4 (freqType v, int i_in) const
Q GR_REG5 (freqType v, int i_in) const
Q SR_REG5 (freqType v, int i_in) const
Q diff_Sigma_K_REG5 (freqType v, int i_in) const
void initInterpolator () const
auto GK (const double v, const int i_in) const -> double
auto SK (const double v, const int i_in) const -> double
Public Attributes
const double Lambda
const SelfEnergy< Q > & selfenergy
const SelfEnergy< Q > & diff_selfenergy
const char type
const double epsilon
const double Gamma
const double T
Detailed Description
template<typename Q>
class Propagator< Q >
Propagator class used for G, S, and the Katanin extension.
Template Parameters
Q Type of the data.
Definition at line 35 of file propagator.hpp.
Constructor & Destructor Documentation
Propagator() [1/3]
template<typename Q > Propagator< Q >::Propagator (double Lambda_in, char type_in, const fRG_config & config) inline
Free Propagator object. SelfEnergy and differentiated SelfEnergy are zero.
Parameters
Lambda_in Value of the regulator Λ.
type_in Type of the propagator:
'g' for a normal propagator
's' for a single-scale propagator
'e' for the Katanin extension
'k' for a fully differentiated propagator 's' + 'e'.
config Set of parameters.
Definition at line 57 of file propagator.hpp.
            : Lambda(Lambda_in), selfenergy(SelfEnergy<Q> (Lambda_in, config)), diff_selfenergy(SelfEnergy<Q> (Lambda_in, config)), type(type_in),
              epsilon(config.epsilon), Gamma(config.Gamma), T(config.T) { }
Propagator() [2/3]
template<typename Q > Propagator< Q >::Propagator (double Lambda_in, const SelfEnergy< Q > & self_in, char type_in, const fRG_config & config) inline
Dressed propagator for non-flowing calculations, i,e, no differential SelfEnergy is needed and is set to the undifferentiated self-energy.
Parameters
Lambda_in Value of the regulator Λ.
self_in Input SelfEnergy.
type_in Type of the propagator: 'g', 's', 'e' or 'k'
config Set of parameters.
Definition at line 68 of file propagator.hpp.
            :Lambda(Lambda_in), selfenergy(self_in), diff_selfenergy(self_in), type(type_in),
            epsilon(config.epsilon), Gamma(config.Gamma), T(config.T) { }
Propagator() [3/3]
template<typename Q > Propagator< Q >::Propagator (double Lambda_in, const SelfEnergy< Q > & self_in, const SelfEnergy< Q > & diffSelf_in, char type_in, const fRG_config & config) inline
Dressed propagator for flows. Needs both a SelfEnergy and a Differential SelfEnergy
Parameters
Lambda_in Value of the regulator Λ.
self_in Input SelfEnergy.
diffSelf_in Input differentiated SelfEnergy.
type_in Type of the propagator: 'g', 's', 'e' or 'k'
config Set of parameters.
Definition at line 81 of file propagator.hpp.
            :Lambda(Lambda_in), selfenergy(self_in), diff_selfenergy(diffSelf_in), type(type_in),
             epsilon(config.epsilon), Gamma(config.Gamma), T(config.T) { }
Member Function Documentation
diff_Sigma_K_REG5()
template<typename Q > auto Propagator< Q >::diff_Sigma_K_REG5 (freqType v, int i_in) const
Definition at line 863 of file propagator.hpp.
{
    const double root_denominator = Lambda * cosh(v/(2.0*Lambda));
    const Q term1 = -glb_i * v * myimag(selfenergy.valsmooth(0, v, i_in)) / (root_denominator*root_denominator);
    const Q term2 = 2.0 * glb_i * tanh(v/(2.0*Lambda)) * myimag(diff_selfenergy.valsmooth(0, v, i_in));
    return term1 + term2; // special case of the temperature flow
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::diff_selfenergy, glb_i(), Propagator< Q >::Lambda, myimag(), and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::Katanin_K().
G0M_inv()
template<typename Q > auto Propagator< Q >::G0M_inv (freqType v, int i_in) const
Definition at line 663 of file propagator.hpp.
{
    assert(!KELDYSH);
    return G0M_inv_SIAM(v, i_in);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0M_inv_SIAM(), and KELDYSH.
Referenced by Propagator< Q >::GM_REG1(), Propagator< Q >::GM_REG2(), Propagator< Q >::GM_REG3(), Propagator< Q >::GM_REG4(), Propagator< Q >::SM_REG3(), and Propagator< Q >::SM_REG4().
G0M_inv_SIAM()
template<typename Q > auto Propagator< Q >::G0M_inv_SIAM (freqType v, int i_in) const
Definition at line 668 of file propagator.hpp.
{
    if constexpr (PARTICLE_HOLE_SYMMETRY) {
        const Q G0inv = v * ((!KELDYSH and !ZERO_T) ? M_PI*T : 1.) + Gamma * 0.5 * sign(v);
        assert(my_isfinite(G0inv));
        return G0inv;
    }
    else {
        const Q G0inv =(v * ((!KELDYSH and !ZERO_T) ? M_PI*T : 1.) + Gamma * 0.5 * sign(v)) * glb_i - epsilon ;
        assert(my_isfinite(G0inv));
        return G0inv;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::epsilon, Propagator< Q >::Gamma, glb_i(), KELDYSH, my_isfinite(), PARTICLE_HOLE_SYMMETRY, sign(), Propagator< Q >::T, and ZERO_T.
Referenced by Propagator< Q >::G0M_inv().
G0R_inv()
template<typename Q > auto Propagator< Q >::G0R_inv (freqType v, int i_in) const
Definition at line 682 of file propagator.hpp.
{
    return G0R_inv_SIAM(v, i_in);
}
References Propagator< Q >::G0R_inv_SIAM().
Referenced by Propagator< Q >::GR_REG1(), Propagator< Q >::GR_REG2(), Propagator< Q >::GR_REG3(), Propagator< Q >::GR_REG4(), Propagator< Q >::GR_REG5(), Propagator< Q >::SR_REG3(), and Propagator< Q >::SR_REG4().
G0R_inv_SIAM()
template<typename Q > auto Propagator< Q >::G0R_inv_SIAM (freqType v, int i_in) const
Definition at line 686 of file propagator.hpp.
{
    const Q G0inv_R = v - epsilon + glb_i * Gamma * 0.5;
    return G0inv_R;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::epsilon, Propagator< Q >::Gamma, and glb_i().
Referenced by Propagator< Q >::G0R_inv().
GK() [1/2]
auto Propagator< double >::GK (const double v, const int i_in) const -> double
Definition at line 38 of file propagator.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
GK() [2/2]
template<typename Q > auto Propagator< Q >::GK (double v, int i_in) const -> Q
Keldysh component of the propagator.
Definition at line 257 of file propagator.hpp.
{
    if constexpr (EQUILIBRIUM and not (REG==5)) {
        // FDT in equilibrium: (1-2*Eff_distr)*(GR-GA)
        //return (1.-2.*Eff_distr(v))*(GR(v, i_in) - GA(v, i_in));
        return glb_i * (Eff_fac(v,T) * 2. * myimag(GR(v, i_in))); // more efficient: only one interpolation instead of two
    }
    else if constexpr (EQUILIBRIUM and (REG==5)){
        // evaluate FDT with T=Lambda
        //return glb_i * (Eff_fac(v,Lambda) * 2. * myimag(GR(v, i_in)));    // explicitly uses FDT
        return (selfenergy.valsmooth(1, v, i_in) - glb_i * Gamma * Eff_fac(v, Lambda)) * std::norm(GR(v, i_in));
    }
    else {
        // General form (Dyson equation): GR*(SigmaK+SigmaK_res)*GA
        // Derivation of equilibrium form:
        // \Sigma^K = (1-2n_F)(\Sigma^R-\Sigma^A), accordingly for \Sigma^K_res
        // \Rightarrow G^K = (1-2n_F) G^R G^A [ (\Sigma+\Sigma_res)^R - (\Sigma+\Sigma_res)^A ]
        //                 = (1-2n_F) G^R G^A [ (G^A)^{-1} - (G^R)^{-1} ] = (1-2n_F) (G^R-G^A)
        // note that \Sigma_res^R = - i (Gamma+Lambda) / 2.
        // return GR(v, i_in) * (selfenergy.valsmooth(1, v, i_in) - glb_i*(Gamma+Lambda)*(1.-2.*Eff_distr(v))) * GA(v, i_in);
        // more efficient: only one interpolation instead of two; std::norm(c)=std::std::abs(c)^2
        return std::norm(GR(v, i_in)) * (selfenergy.valsmooth(1, v, i_in) - glb_i * ((Gamma + Lambda) * Eff_fac(v,T)));
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Eff_fac(), EQUILIBRIUM, Propagator< Q >::Gamma, glb_i(), Propagator< Q >::GR(), Propagator< Q >::Lambda, myimag(), REG, Propagator< Q >::selfenergy, and Propagator< Q >::T.
Referenced by Propagator< Q >::Katanin_K(), Propagator< Q >::valsmooth(), Propagator< Q >::valsmooth_vectorized(), and Hartree_Solver::write_out_propagators().
GM()
template<typename Q > auto Propagator< Q >::GM (freqType v, int i_in) const -> Q
Matsubara propagator.
Parameters
v fermionic Matsubara frequency
i_in internal structure index
Returns
Value of the Matsubara propagator at the given input.
Definition at line 349 of file propagator.hpp.
{
    if      constexpr (REG == 1) { return GM_REG1(v, i_in); }
    else if constexpr (REG == 2) { return GM_REG2(v, i_in); }
    else if constexpr (REG == 3) { return GM_REG3(v, i_in); }
    else if constexpr (REG == 4) { return GM_REG4(v, i_in); }
    else {utils::print("The Regulator " + std::to_string(REG) + "is not implemented. Abort."); assert(false);}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::GM_REG1(), Propagator< Q >::GM_REG2(), Propagator< Q >::GM_REG3(), Propagator< Q >::GM_REG4(), utils::print(), and REG.
Referenced by Propagator< Q >::GM_REG1(), Propagator< Q >::norm(), Hartree_Solver::operator()(), Propagator< Q >::SM_REG1(), Propagator< Q >::SM_REG2(), Propagator< Q >::SM_REG3(), and Propagator< Q >::valsmooth().
GM_REG1()
template<typename Q > auto Propagator< Q >::GM_REG1 (freqType v, int i_in) const
Definition at line 712 of file propagator.hpp.
{
    Q GM = 1. / (G0M_inv(v, i_in) - selfenergy.valsmooth(0, v, i_in));
    if (std::abs(v) < Lambda)       return GM;
    else if (std::abs(v) == Lambda) return GM/2.;
    else                            return 0.;
}
References Propagator< Q >::G0M_inv(), Propagator< Q >::GM(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GM().
GM_REG2()
template<typename Q > auto Propagator< Q >::GM_REG2 (freqType v, int i_in) const
Definition at line 749 of file propagator.hpp.
{
    if constexpr (PARTICLE_HOLE_SYMMETRY) {
        const Q G0inv = G0M_inv(v, i_in);
        const auto sin = sign(v);
        const Q res_inv = ( G0inv + Lambda*0.5*sign(v) - selfenergy.valsmooth(0, v, i_in) );
        const Q res = 1./( G0inv + Lambda*0.5*sign(v) - selfenergy.valsmooth(0, v, i_in) );
        assert(my_isfinite(res));
        return res;
    }
    else {
        const Q res = 1./( G0M_inv(v, i_in) + glb_i*Lambda*0.5*sign(v) - selfenergy.valsmooth(0, v, i_in) );
        return res;
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0M_inv(), glb_i(), Propagator< Q >::Lambda, my_isfinite(), PARTICLE_HOLE_SYMMETRY, Propagator< Q >::selfenergy, and sign().
Referenced by Propagator< Q >::GM().
GM_REG3()
template<typename Q > auto Propagator< Q >::GM_REG3 (freqType v, int i_in) const
Definition at line 800 of file propagator.hpp.
{
    const double reg = v*v / (v*v + Lambda*Lambda);
    const Q res = 1./( G0M_inv(v, i_in) / reg - selfenergy.valsmooth(0, v, i_in) );
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0M_inv(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GM().
GM_REG4()
template<typename Q > auto Propagator< Q >::GM_REG4 (freqType v, int i_in) const
Definition at line 833 of file propagator.hpp.
{
    const double reg = Lambda;
    const Q res = reg /( G0M_inv(v, i_in) - reg * selfenergy.valsmooth(0, v, i_in) );
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0M_inv(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GM().
GR()
template<typename Q > auto Propagator< Q >::GR (double v, int i_in) const -> Q
Retarded component of the propagator.
Parameters
v fermionic frequency
i_in internal structure index
Returns
Value of the retarded component at the given input.
Definition at line 244 of file propagator.hpp.
{
    if      constexpr (REG == 1) { return GR_REG1(v, i_in); }
    else if constexpr (REG == 2) { return GR_REG2(v, i_in); }
    else if constexpr (REG == 3) { return GR_REG3(v, i_in); }
    else if constexpr (REG == 4) { return GR_REG4(v, i_in); }
    else if constexpr (REG == 5) { return GR_REG5(v, i_in); }
    else {
        utils::print("The Regulator " + std::to_string(REG) + "is not implemented. Abort."); assert(false);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::GR_REG1(), Propagator< Q >::GR_REG2(), Propagator< Q >::GR_REG3(), Propagator< Q >::GR_REG4(), Propagator< Q >::GR_REG5(), utils::print(), and REG.
Referenced by Propagator< Q >::GK(), Propagator< Q >::GR_REG1(), Propagator< Q >::Katanin_K(), Propagator< Q >::Katanin_R(), Propagator< Q >::norm(), Hartree_Solver::operator()(), Propagator< Q >::SK(), Propagator< Q >::SR_REG1(), Propagator< Q >::SR_REG2(), Propagator< Q >::SR_REG3(), Propagator< Q >::valsmooth(), Propagator< Q >::valsmooth_vectorized(), and Hartree_Solver::write_out_propagators().
GR_REG1()
template<typename Q > auto Propagator< Q >::GR_REG1 (freqType v, int i_in) const
Definition at line 697 of file propagator.hpp.
{
    Q GR = 1. / (G0R_inv(v, i_in) - selfenergy.valsmooth(0, v, i_in));
    if (std::abs(v) < Lambda)       return GR;
    else if (std::abs(v) == Lambda) return GR/2.;
    else                            return 0.;
}
References Propagator< Q >::G0R_inv(), Propagator< Q >::GR(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GR().
GR_REG2()
template<typename Q > auto Propagator< Q >::GR_REG2 (freqType v, int i_in) const
Definition at line 736 of file propagator.hpp.
{
    const Q res = 1./( G0R_inv(v, i_in) + glb_i*Lambda*0.5 - selfenergy.valsmooth(0, v, i_in) );
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0R_inv(), glb_i(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GR().
GR_REG3()
template<typename Q > auto Propagator< Q >::GR_REG3 (freqType v, int i_in) const
Definition at line 781 of file propagator.hpp.
{
    const Q reg = v / (v + glb_i*Lambda);
    const Q res = reg / ( G0R_inv(v, i_in) - reg * selfenergy.valsmooth(0, v, i_in) );
    assert(my_isfinite(res));
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0R_inv(), glb_i(), Propagator< Q >::Lambda, my_isfinite(), and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GR().
GR_REG4()
template<typename Q > auto Propagator< Q >::GR_REG4 (freqType v, int i_in) const
Definition at line 818 of file propagator.hpp.
{
    const Q asymp_val = selfenergy.asymp_val_R;
    const Q res = Lambda / ( G0R_inv(v, i_in) - asymp_val - Lambda * (selfenergy.valsmooth(0, v, i_in) - asymp_val) );
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0R_inv(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GR().
GR_REG5()
template<typename Q > auto Propagator< Q >::GR_REG5 (freqType v, int i_in) const
Definition at line 854 of file propagator.hpp.
{
    const Q res = 1./( G0R_inv(v, i_in) - selfenergy.valsmooth(0, v, i_in) );
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0R_inv(), and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::GR().
initInterpolator()
template<typename Q > void Propagator< Q >::initInterpolator () const
Definition at line 872 of file propagator.hpp.
{
    selfenergy.Sigma.initInterpolator();
    if (type == 'k' or type == 'e') diff_selfenergy.Sigma.initInterpolator();
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::diff_selfenergy, Propagator< Q >::selfenergy, and Propagator< Q >::type.
Referenced by loop().
Katanin_K()
template<typename Q > Q Propagator< Q >::Katanin_K (double v, int i_in) const
Keldysh component of the Katanin extension G^R \dot{Σ}^R G^K + G^R \dot{Σ}^K G^A + G^K \dot{Σ}^A G^A.
Definition at line 337 of file propagator.hpp.
{
#ifdef USE_FDT_4_SELFENERGY
    const Q diff_Sigma_K = diff_Sigma_K_REG5(v, i_in);  // special form in the temperature flow
#else
    const Q diff_Sigma_K = diff_selfenergy.valsmooth(1, v, i_in);
#endif
    return GR(v, i_in) * diff_selfenergy.valsmooth(0, v, i_in) * GK(v, i_in)
            + GR(v, i_in) * diff_Sigma_K * conj(GR(v, i_in))
            + GK(v, i_in) * myconj(diff_selfenergy.valsmooth(0, v, i_in)) * conj(GR(v, i_in));
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::diff_selfenergy, Propagator< Q >::diff_Sigma_K_REG5(), Propagator< Q >::GK(), Propagator< Q >::GR(), and myconj().
Referenced by Propagator< Q >::valsmooth(), and Propagator< Q >::valsmooth_vectorized().
Katanin_R()
template<typename Q > Q Propagator< Q >::Katanin_R (double v, int i_in) const
Retarded component of the Katanin extension G^R \dot{Σ}^R G^R.
Definition at line 332 of file propagator.hpp.
{
    return GR(v, i_in) * diff_selfenergy.valsmooth(0, v, i_in) * GR(v, i_in);
}
References Propagator< Q >::diff_selfenergy, and Propagator< Q >::GR().
Referenced by Propagator< Q >::valsmooth(), and Propagator< Q >::valsmooth_vectorized().
norm()
template<typename Q > auto Propagator< Q >::norm () const -> double
Definition at line 652 of file propagator.hpp.
{
    double out = 0.;
    for (int i = 0; i < nPROP; i++) {
        if (KELDYSH) out += pow(std::abs(GR(selfenergy.Sigma.frequencies.primary_grid.get_frequency(i), 0)), 2.);
        else         out += pow(std::abs(GM(selfenergy.Sigma.frequencies.primary_grid.get_frequency(i), 0)), 2.);
    }
    return sqrt(out);
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::GM(), Propagator< Q >::GR(), KELDYSH, nPROP, and Propagator< Q >::selfenergy.
save_propagator_values()
template<typename Q > void Propagator< Q >::save_propagator_values (const std::string & filename, const rvec & frequencies) const inline
Definition at line 103 of file propagator.hpp.
{
        using buffer_type = multidimensional::multiarray<Q, 3>;
        const size_t number_of_frequencies = frequencies.size();
        H5::H5File file(filename, H5F_ACC_TRUNC);
        if constexpr(KELDYSH_FORMALISM) {
            std::array<size_t, 3> dims = {number_of_frequencies, 2, 2};
            buffer_type values(dims);
            selfenergy.Sigma.initInterpolator();
            if (type != 'g')diff_selfenergy.Sigma.initInterpolator();
            for (size_t i = 0; i < number_of_frequencies; i++) {
                const double v = frequencies[i];
                using buffertype_propagator = Eigen::Matrix<Q, 1, 4>;
                const buffertype_propagator value = valsmooth_vectorized<buffertype_propagator>(v, 0);
                values(i, 0, 0) = value(0);
                values(i, 0, 1) = value(1);
                values(i, 1, 0) = value(2);
                values(i, 1, 1) = value(3);
            }
            write_to_hdf(file, "propagator", values, false);
        }
        else {
            std::array<size_t, 3> dims = {number_of_frequencies, 1, 1};
            buffer_type values(dims);
            selfenergy.Sigma.initInterpolator();
            if (type != 'g')diff_selfenergy.Sigma.initInterpolator();
            for (size_t i = 0; i < number_of_frequencies; i++) {
                const double v = frequencies[i];
                using buffertype_propagator = Eigen::Matrix<Q, 1, 1>;
                const double value = valsmooth(0,v, 0);
                values(i, 0, 0) = value ;
            }
            write_to_hdf(file, "propagator", values, false);
            write_to_hdf<Q>(file, "frequencies", frequencies, false);
        }
        //std::string filename = data_dir + "";
        file.close();
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::diff_selfenergy, KELDYSH_FORMALISM, Propagator< Q >::selfenergy, Propagator< Q >::type, Propagator< Q >::valsmooth(), and write_to_hdf().
SK() [1/2]
auto Propagator< double >::SK (const double v, const int i_in) const -> double
Definition at line 45 of file propagator.c++.
{
    utils::print("Error! Keldysh computations require complex numbers! Abort.");
    assert(false);
    return 0.;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and utils::print().
SK() [2/2]
template<typename Q > auto Propagator< Q >::SK (double v, int i_in) const -> Q
Keldysh component of the single-scale propagator.
Definition at line 297 of file propagator.hpp.
{
    if constexpr (EQUILIBRIUM and not (REG==5)) {
        // FDT in equilibrium: (1-2*Eff_distr)*(SR-SA)
        //return (1.-2.*Eff_distr(v))*(SR(v, i_in) - myconj(SR(v, i_in)));
        return glb_i * (Eff_fac(v,T) * 2. * myimag(SR(v, i_in)));
    }
    else if constexpr (EQUILIBRIUM and (REG==5)){
        // special form of SK in the temperature flow
        const double root_denominator = Lambda * cosh(v/(2.0*Lambda));
        // return -glb_i * v * myimag(GR_REG5(v, i_in)) / (root_denominator*root_denominator);  //explicitly uses FDT
        return glb_i * 0.5 * Gamma * v * std::norm(GR(v, i_in)) / (root_denominator*root_denominator) ;
    }
    else {
        // Derivation of general matrix form:
        // S = - G * ( \partial_\Lambda G_0^{-1} ) * G
        // where G = (0, G^A; G^R, G^K), G_0^{-1} = (Ginv0K, G_0^{A,-1}; G_0^{R,-1}, 0), Ginv0K = - \Sigma^K_res, \dot{Ginv0K} = i (1-2n_F)
        // Thus, S^K = - G^R \dot{G_0^{R,-1}} G^K - G^K \dot{G_0^{A,-1}} G^A - G^R Ginv0K G^A
        // Upon inserting G^K = (1-2n_F) (G^R-G^A), one recovers the equilibrium formula
        //Q retarded = -0.5*glb_i*GR(v, i_in)*GK(v, i_in);
        //Q advanced = +0.5*glb_i*GK(v, i_in)*GA(v, i_in);
        //Q extra    = -glb_i*(1.-2.*Eff_distr(v))*GR(v, i_in)*GA(v, i_in);
        //return retarded + advanced + extra;
        //return GK(v, i_in)*imag(GR(v, i_in)) - glb_i*(1.-2.*Eff_distr(v))*GR(v, i_in)*GA(v, i_in); // more efficient
        //return GK(v, i_in)*imag(GR(v, i_in)) - glb_i*(Eff_fac(v)) * std::norm( GR(v, i_in) ); // more efficient
        // most efficient: insert GK, factor out, combine real factors
        Q gr = GR(v, i_in);
        double gri = myimag(gr);
        double grn = std::norm(gr);
        return selfenergy.valsmooth(1, v, i_in) * (grn * gri) -
               glb_i * (grn * Eff_fac(v,T) * (1. + (Gamma + Lambda) * gri));
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Eff_fac(), EQUILIBRIUM, Propagator< Q >::Gamma, glb_i(), Propagator< Q >::GR(), Propagator< Q >::Lambda, myimag(), REG, Propagator< Q >::selfenergy, Propagator< Q >::SR(), and Propagator< Q >::T.
Referenced by Hartree_Solver::operator()(), Propagator< Q >::valsmooth(), and Propagator< Q >::valsmooth_vectorized().
SM()
template<typename Q > auto Propagator< Q >::SM (freqType v, int i_in) const -> Q
Matsubara single-scale propagator.
Definition at line 359 of file propagator.hpp.
{
    if      constexpr (REG == 1) { return SM_REG1(v, i_in); }
    else if constexpr (REG == 2) { return SM_REG2(v, i_in); }
    else if constexpr (REG == 3) { return SM_REG3(v, i_in); }
    else if constexpr (REG == 4) { return SM_REG4(v, i_in); }
    else {utils::print("The Regulator " + std::to_string(REG) + "is not implemented. Abort."); assert(false);}
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), utils::print(), REG, Propagator< Q >::SM_REG1(), Propagator< Q >::SM_REG2(), Propagator< Q >::SM_REG3(), and Propagator< Q >::SM_REG4().
Referenced by Hartree_Solver::operator()(), and Propagator< Q >::valsmooth().
SM_REG1()
template<typename Q > auto Propagator< Q >::SM_REG1 (freqType v, int i_in) const
Definition at line 720 of file propagator.hpp.
{
    if (std::abs(v) == Lambda) return -GM(v, i_in);
    else                       return 0.;
}
References Propagator< Q >::GM(), and Propagator< Q >::Lambda.
Referenced by Propagator< Q >::SM().
SM_REG1_FPP()
template<typename Q > auto Propagator< Q >::SM_REG1_FPP (double v, double ksquared, int i_in) const
Definition at line 727 of file propagator.hpp.
{
    std::cout << "SM_REG1_FPP not yet implemented\n";
    return 0;
}
SM_REG2()
template<typename Q > auto Propagator< Q >::SM_REG2 (freqType v, int i_in) const
Definition at line 766 of file propagator.hpp.
{
    const Q G = GM(v, i_in);
    if constexpr (PARTICLE_HOLE_SYMMETRY) {
        return -0.5*G*G*sign(v);
    }
    else {
        return -0.5*glb_i*G*G*sign(v);
    }
}
References glb_i(), Propagator< Q >::GM(), PARTICLE_HOLE_SYMMETRY, and sign().
Referenced by Propagator< Q >::SM().
SM_REG3()
template<typename Q > auto Propagator< Q >::SM_REG3 (freqType v, int i_in) const
Definition at line 807 of file propagator.hpp.
{
    assert(v != 0.);
    const Q G = GM(v, i_in);
    const Q G0inv = G0M_inv(v, i_in);
    return -2 * Lambda / (v * v) * G * G0inv * G;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0M_inv(), Propagator< Q >::GM(), and Propagator< Q >::Lambda.
Referenced by Propagator< Q >::SM().
SM_REG4()
template<typename Q > auto Propagator< Q >::SM_REG4 (freqType v, int i_in) const
Definition at line 840 of file propagator.hpp.
{
    assert(v != 0.);
    const double reg = Lambda;
    const Q G0_inv = G0M_inv(v, i_in);
    const Q G = 1. /( G0_inv - reg * selfenergy.valsmooth(0, v, i_in) );
    const Q val = G0_inv * G * G;
    assert(my_isfinite(val));
    return val;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0M_inv(), Propagator< Q >::Lambda, my_isfinite(), and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::SM().
SR()
template<typename Q > auto Propagator< Q >::SR (double v, int i_in) const -> Q
Retarded component of the single-scale propagator.
Definition at line 284 of file propagator.hpp.
{
    if      constexpr (REG == 1) { return SR_REG1(v, i_in); }
    else if constexpr (REG == 2) { return SR_REG2(v, i_in); }
    else if constexpr (REG == 3) { return SR_REG3(v, i_in); }
    else if constexpr (REG == 4) { return SR_REG4(v, i_in); }
    else if constexpr (REG == 5) { return SR_REG5(v, i_in); }
    else {
        utils::print("The Regulator " + std::to_string(REG) + "is not implemented. Abort."); assert(false);
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), utils::print(), REG, Propagator< Q >::SR_REG1(), Propagator< Q >::SR_REG2(), Propagator< Q >::SR_REG3(), Propagator< Q >::SR_REG4(), and Propagator< Q >::SR_REG5().
Referenced by Hartree_Solver::operator()(), Propagator< Q >::SK(), Propagator< Q >::valsmooth(), and Propagator< Q >::valsmooth_vectorized().
SR_REG1()
template<typename Q > auto Propagator< Q >::SR_REG1 (freqType v, int i_in) const
Definition at line 705 of file propagator.hpp.
{
    if (std::abs(v) == Lambda) return -GR(v, i_in);
    else                       return 0.;
}
References Propagator< Q >::GR(), and Propagator< Q >::Lambda.
Referenced by Propagator< Q >::SR().
SR_REG2()
template<typename Q > auto Propagator< Q >::SR_REG2 (freqType v, int i_in) const
Definition at line 742 of file propagator.hpp.
{
    const Q G = GR(v, i_in);
    return -0.5*glb_i*G*G; // more efficient: only one interpolation instead of two, and G*G instead of pow(G, 2)
}
References glb_i(), and Propagator< Q >::GR().
Referenced by Propagator< Q >::SR().
SR_REG3()
template<typename Q > auto Propagator< Q >::SR_REG3 (freqType v, int i_in) const
Definition at line 789 of file propagator.hpp.
{
    if (std::abs(v)<1e-18) return 0.;
    const Q G = GR(v, i_in);
    const Q G0inv = G0R_inv(v, i_in);
    return (-glb_i / v) * G * G0inv * G;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0R_inv(), glb_i(), and Propagator< Q >::GR().
Referenced by Propagator< Q >::SR().
SR_REG4()
template<typename Q > auto Propagator< Q >::SR_REG4 (freqType v, int i_in) const
Definition at line 824 of file propagator.hpp.
{
    const Q asymp_val = selfenergy.asymp_val_R;
    const Q G0R = G0R_inv(v, i_in);
    const Q G = 1. /( G0R - asymp_val - Lambda * (selfenergy.valsmooth(0, v, i_in) - asymp_val) );
    const Q res = (G0R - asymp_val) * G * G;
    return res;
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::G0R_inv(), Propagator< Q >::Lambda, and Propagator< Q >::selfenergy.
Referenced by Propagator< Q >::SR().
SR_REG5()
template<typename Q > auto Propagator< Q >::SR_REG5 (freqType v, int i_in) const
Definition at line 859 of file propagator.hpp.
{
    return 0.0; // special case of the temperature flow
}
Referenced by Propagator< Q >::SR().
valsmooth()
template<typename Q > auto Propagator< Q >::valsmooth (int iK, freqType v, int i_in) const -> Q
Function to smoothly interpolate the propagator on the frequency grid of the underlying self-energy.
Parameters
iK Keldysh index
v fermionic frequency
i_in internal structure index
Returns
Value of the propagator at the given input.
Definition at line 370 of file propagator.hpp.
{
    switch (type){
        case 'g' :                              //Good ol' regular propagator
            if constexpr (KELDYSH){
                if constexpr(CONTOUR_BASIS != 1) {
                    switch (iK) {
                        case 0:
                            return GR(v, i_in);
                        case 1:
                            return GK(v, i_in);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
                else {
                    const Q GR_ = GR(v, i_in);
                    const Q GA_ = conj(GR_);
                    const Q GK_ = GK(v, i_in);
                    switch (iK){
                        case 0:
                            return 0.5*(GA_ + GR_ + GK_);
                        case 1:
                            return 0.5*(GA_ - GR_ + GK_);
                        case 2:
                            return 0.5*(-GA_ + GR_ + GK_);
                        case 3:
                            return 0.5*(-GA_ - GR_ + GK_);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
            }
            else{
                return GM(v, i_in);
            }
        break;
        case 's':
            if constexpr (KELDYSH){
                if constexpr(CONTOUR_BASIS != 1) {
                    // Keldysh basis:
                    switch (iK){
                        case 0:
                            return SR(v, i_in);
                        case 1:
                            return SK(v, i_in);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
                else {
                    // Contour basis:
                    const Q SR_ = SR(v, i_in);
                    const Q SA_ = conj(SR_);
                    const Q SK_ = SK(v, i_in);
                    switch (iK){
                        case 0:
                            return 0.5*(SA_ + SR_ + SK_);
                        case 1:
                            return 0.5*(SA_ - SR_ + SK_);
                        case 2:
                            return 0.5*(-SA_ + SR_ + SK_);
                        case 3:
                            return 0.5*(-SA_ - SR_ + SK_);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
            }
            else{
                return SM(v, i_in);
            }
        break;
        case 'k': // including the Katanin extension
            if constexpr (KELDYSH){
                if constexpr(CONTOUR_BASIS != 1) {
                    switch (iK) {
                        case 0:
                            return SR(v, i_in) + Katanin_R(v, i_in);
                        case 1:
                            return SK(v, i_in) + Katanin_K(v, i_in);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
                else {
                    const Q SR_ = SR(v, i_in) + Katanin_R(v, i_in);
                    const Q SA_ = conj(SR_);
                    const Q SK_ = SK(v, i_in) + Katanin_K(v, i_in);
                    switch (iK){
                        case 0: return 0.5*(SA_ + SR_ + SK_);
                        case 1: return 0.5*(SA_ - SR_ + SK_);
                        case 2: return 0.5*(-SA_ + SR_ + SK_);
                        case 3: return 0.5*(-SA_ - SR_ + SK_);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
            }
            else{
                return SM(v, i_in)
                       + GM(v, i_in) * diff_selfenergy.valsmooth(0, v, i_in) * GM(v, i_in);
            }
        break;
        case 'e': // purely the Katanin extension
            if constexpr (KELDYSH){
                if constexpr(CONTOUR_BASIS != 1) {
                    switch (iK) {
                        case 0: return Katanin_R(v, i_in);
                        case 1: return Katanin_K(v, i_in);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
                else {
                    const Q SR_ = Katanin_R(v, i_in);
                    const Q SA_ = conj(SR_);
                    const Q SK_ = Katanin_K(v, i_in);
                    switch (iK){
                        case 0: return 0.5*(SA_ + SR_ + SK_);
                        case 1: return 0.5*(SA_ - SR_ + SK_);
                        case 2: return 0.5*(-SA_ + SR_ + SK_);
                        case 3: return 0.5*(-SA_ - SR_ + SK_);
                        default:
                            utils::print("ERROR! Invalid Keldysh index. Abort.");
                            assert(false);
                    }
                }
            }
            else{
                return GM(v, i_in) * diff_selfenergy.valsmooth(0, v, i_in) * GM(v, i_in);
            }
        break;
        default:
            utils::print("ERROR! Invalid Keldysh index. Abort.");
            assert(false);
            exit(1); // Failure
    }
    assert(false);
    return 0.;
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), Propagator< Q >::diff_selfenergy, Propagator< Q >::GK(), Propagator< Q >::GM(), Propagator< Q >::GR(), Propagator< Q >::Katanin_K(), Propagator< Q >::Katanin_R(), KELDYSH, utils::print(), Propagator< Q >::SK(), Propagator< Q >::SM(), Propagator< Q >::SR(), and Propagator< Q >::type.
Referenced by Integrand_sum_rule_spectrum::operator()(), and Propagator< Q >::save_propagator_values().
valsmooth_vectorized()
template<typename Q > template<typename return_type > auto Propagator< Q >::valsmooth_vectorized (freqType v, int i_in) const -> return_type
Version of the valsmooth function when vectorization over Keldysh indices is used
Template Parameters
return_type Type of the result.
Parameters
v fermionic frequency
i_in internal structure index
Returns
Value of the propagator at the given input.
Definition at line 521 of file propagator.hpp.
{
    //using return_type = Eigen::Matrix<Q,1,4>;
    switch (type){
        case 'g' :                              //Good ol' regular propagator
            if constexpr (KELDYSH){
                const Q GR_ = GR(v, i_in);
                const Q GA_ = conj(GR_);
                const Q GK_ = GK(v, i_in);
                if constexpr(CONTOUR_BASIS != 1) {
                    if constexpr(!EQUILIBRIUM) assert(false); // not implemented for non-equilibrium yet
                    return_type result;
                    result << 0., GA_,
                             GR_, GK_;
                    return result;
                }
                else {
                    const Q G00 = 0.5*( GA_ + GR_ + GK_);
                    const Q G01 = 0.5*( GA_ - GR_ + GK_);
                    const Q G10 = 0.5*(-GA_ + GR_ + GK_);
                    const Q G11 = 0.5*(-GA_ - GR_ + GK_);
                    return_type result;
                    result << G00, G01,
                              G10, G11;
                    return result;
                    }
                }
            else{
                assert(false);
            }
        break;
        case 's':
            if constexpr (KELDYSH){
                const Q SR_ = SR(v, i_in);
                const Q SA_ = conj(SR_);
                const Q SK_ = SK(v, i_in);
                if constexpr(CONTOUR_BASIS != 1) {
                    if constexpr(!EQUILIBRIUM) assert(false); // not implemented for non-equilibrium yet
                    return_type result;
                    result << 0., SA_,
                             SR_, SK_;
                    return result;
                }
                else {
                    const Q S00 = 0.5*( SA_ + SR_ + SK_);
                    const Q S01 = 0.5*( SA_ - SR_ + SK_);
                    const Q S10 = 0.5*(-SA_ + SR_ + SK_);
                    const Q S11 = 0.5*(-SA_ - SR_ + SK_);
                    return_type result;
                    result << S00, S01,
                              S10, S11;
                    return result;
                }
            }
            else{
                assert(false);
            }
        break;
        case 'k': // including the Katanin extension
            if constexpr (KELDYSH){
                const Q SR_ = SR(v, i_in) + Katanin_R(v, i_in);
                const Q SA_ = conj(SR_);
                const Q SK_ = SK(v, i_in) + Katanin_K(v, i_in);
                if constexpr(CONTOUR_BASIS != 1) {
                    return_type result;
                    result << 0., SA_,
                             SR_, SK_;
                    return result;
                }
                else {
                    const Q S00 = 0.5*( SA_ + SR_ + SK_);
                    const Q S01 = 0.5*( SA_ - SR_ + SK_);
                    const Q S10 = 0.5*(-SA_ + SR_ + SK_);
                    const Q S11 = 0.5*(-SA_ - SR_ + SK_);
                    return_type result;
                    result << S00, S01,
                              S10, S11;
                    return result;
                }
            }
            else{
                assert(false);
            }
        break;
        case 'e': // purely the Katanin extension
            if constexpr (KELDYSH){
                const Q SR_ = Katanin_R(v, i_in);
                const Q SA_ = conj(SR_);
                const Q SK_ = Katanin_K(v, i_in);
                if constexpr(CONTOUR_BASIS != 1) {
                    return_type result;
                    result << 0., SA_,
                             SR_, SK_;
                    return result;
                }
                else {
                    const Q S00 = 0.5*( SA_ + SR_ + SK_);
                    const Q S01 = 0.5*( SA_ - SR_ + SK_);
                    const Q S10 = 0.5*(-SA_ + SR_ + SK_);
                    const Q S11 = 0.5*(-SA_ - SR_ + SK_);
                    return_type result;
                    result << S00, S01,
                              S10, S11;
                    return result;
                }
            }
            else{
                assert(false);
            }
        break;
        default:
            utils::print("ERROR! Invalid Keldysh index. Abort.");
            assert(false);
            exit(1); // Failure
            //return return_type::Zero();
    }
    assert(false);
    return myzero<return_type>();
}
References CONTOUR_BASIS, correctionFunctionBubble_REG3_Matsubara_PHS_diff(), EQUILIBRIUM, Propagator< Q >::GK(), Propagator< Q >::GR(), Propagator< Q >::Katanin_K(), Propagator< Q >::Katanin_R(), KELDYSH, utils::print(), Propagator< Q >::SK(), Propagator< Q >::SR(), and Propagator< Q >::type.
Member Data Documentation
diff_selfenergy
template<typename Q > const SelfEnergy<Q>& Propagator< Q >::diff_selfenergy
Definition at line 39 of file propagator.hpp.
Referenced by Propagator< Q >::diff_Sigma_K_REG5(), Propagator< Q >::initInterpolator(), Propagator< Q >::Katanin_K(), Propagator< Q >::Katanin_R(), Propagator< Q >::save_propagator_values(), and Propagator< Q >::valsmooth().
epsilon
template<typename Q > const double Propagator< Q >::epsilon
Definition at line 41 of file propagator.hpp.
Referenced by Propagator< Q >::G0M_inv_SIAM(), and Propagator< Q >::G0R_inv_SIAM().
Gamma
template<typename Q > const double Propagator< Q >::Gamma
Definition at line 42 of file propagator.hpp.
Referenced by Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::G0R_inv_SIAM(), Propagator< Q >::GK(), and Propagator< Q >::SK().
Lambda
template<typename Q > const double Propagator< Q >::Lambda
Definition at line 37 of file propagator.hpp.
Referenced by Propagator< Q >::diff_Sigma_K_REG5(), Propagator< Q >::GK(), Propagator< Q >::GM_REG1(), Propagator< Q >::GM_REG2(), Propagator< Q >::GM_REG3(), Propagator< Q >::GM_REG4(), Propagator< Q >::GR_REG1(), Propagator< Q >::GR_REG2(), Propagator< Q >::GR_REG3(), Propagator< Q >::GR_REG4(), selfEnergyFlowCorrections(), Propagator< Q >::SK(), Propagator< Q >::SM_REG1(), Propagator< Q >::SM_REG3(), Propagator< Q >::SM_REG4(), Propagator< Q >::SR_REG1(), and Propagator< Q >::SR_REG4().
selfenergy
template<typename Q > const SelfEnergy<Q>& Propagator< Q >::selfenergy
Definition at line 38 of file propagator.hpp.
Referenced by Propagator< Q >::diff_Sigma_K_REG5(), Propagator< Q >::GK(), Propagator< Q >::GM_REG1(), Propagator< Q >::GM_REG2(), Propagator< Q >::GM_REG3(), Propagator< Q >::GM_REG4(), Propagator< Q >::GR_REG1(), Propagator< Q >::GR_REG2(), Propagator< Q >::GR_REG3(), Propagator< Q >::GR_REG4(), Propagator< Q >::GR_REG5(), Propagator< Q >::initInterpolator(), Propagator< Q >::norm(), Propagator< Q >::save_propagator_values(), Propagator< Q >::SK(), Propagator< Q >::SM_REG4(), Propagator< Q >::SR_REG4(), and Hartree_Solver::write_out_propagators().
T
template<typename Q > const double Propagator< Q >::T
Definition at line 43 of file propagator.hpp.
Referenced by LoopCalculator< Q, vertType, all_spins, version >::compute_Matsubara_finiteT(), Propagator< Q >::G0M_inv_SIAM(), Propagator< Q >::GK(), LoopCalculator< Q, vertType, all_spins, version >::set_v_limits(), and Propagator< Q >::SK().
type
template<typename Q > const char Propagator< Q >::type
Definition at line 40 of file propagator.hpp.
Referenced by Propagator< Q >::initInterpolator(), Propagator< Q >::save_propagator_values(), Propagator< Q >::valsmooth(), and Propagator< Q >::valsmooth_vectorized().
The documentation for this class was generated from the following file:
propagator.hpp