SIAM-Keldysh-mfRG: dataContainerBase< Q, rank > Class Template Reference
dataContainerBase< Q, rank > Class Template Reference
#include <data_container.hpp>
Public Member Functions
dataContainerBase ()=default
constructor:
dataContainerBase (const dimensions_type dims)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
dataContainerBase (const Types &... dims)
dataContainerBase (const buffer_type &data_in)
Q acc (const size_t flatIndex) const
Access data via flattened index.
void direct_set (const size_t flatIndex, Q value)
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
Q val (const Types &... i) const
Returns value for a multiIndex.
Q val (const index_type &idx) const
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
const Q & at (const Types &... i) const
Returns reference to a value for a multiIndex.
template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true>
auto val_vectorized (const Types &... i) const -> Eigen::Matrix< Q, vecsize, 1 >
template<std::size_t freqrank, std::size_t vecsize>
auto val_vectorized (const index_type &idx) const -> Eigen::Matrix< Q, vecsize, 1 >
template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true>
void setvert (const Q value, const Types &... i)
Sets a value at a multiIndex.
void setvert (const Q value, const index_type &idx)
template<std::size_t vecsize>
void setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > &value, const index_type &idx)
auto get_dims () const
const buffer_type & get_vec () const
Returns the buffer "data" containing the data.
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void set_vec (const container &data_in)
Sets the the buffer "data".
void set_vec (const buffer_type &data_in)
void set_vec (const buffer_type &&data_in)
template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true>
void add_vec (const container &summand)
Adds a vector to the data.
void add_vec (const buffer_type &summand)
constexpr auto eigen_segment (const index_type &start, const index_type &end)
constexpr auto eigen_segment (const index_type &start, const index_type &end) const
template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size>
Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> get_values (const index_type &index) const
Protected Types
using buffer_type = multidimensional::multiarray<Q, rank>
using index_type = typename buffer_type::index_type
using dimensions_type = typename buffer_type::dimensions_type
Protected Attributes
buffer_type data
Friends
class State< Q, false >
class State< Q, true >
State< state_datatype, false > read_state_from_hdf (const H5std_string &filename, const unsigned int Lambda_it)
Detailed Description
template<typename Q, std::size_t rank>
class dataContainerBase< Q, rank >
Offers basic functionality that is identical for all K_classes
Template Parameters
Q data type of vertex data
rank rank of data tensor
Definition at line 35 of file data_container.hpp.
Member Typedef Documentation
buffer_type
template<typename Q , std::size_t rank> using dataContainerBase< Q, rank >::buffer_type = multidimensional::multiarray<Q, rank> protected
Definition at line 42 of file data_container.hpp.
dimensions_type
template<typename Q , std::size_t rank> using dataContainerBase< Q, rank >::dimensions_type = typename buffer_type::dimensions_type protected
Definition at line 44 of file data_container.hpp.
index_type
template<typename Q , std::size_t rank> using dataContainerBase< Q, rank >::index_type = typename buffer_type::index_type protected
Definition at line 43 of file data_container.hpp.
Constructor & Destructor Documentation
dataContainerBase() [1/4]
template<typename Q , std::size_t rank> dataContainerBase< Q, rank >::dataContainerBase () default
constructor:
dataContainerBase() [2/4]
template<typename Q , std::size_t rank> dataContainerBase< Q, rank >::dataContainerBase (const dimensions_type dims) inline explicit
Definition at line 52 of file data_container.hpp.
: data(dims) {};
dataContainerBase() [3/4]
template<typename Q , std::size_t rank> template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true> dataContainerBase< Q, rank >::dataContainerBase (const Types &... dims) inline explicit
Definition at line 58 of file data_container.hpp.
: dataContainerBase(index_type({static_cast<size_t>(dims)...})) {};
dataContainerBase() [4/4]
template<typename Q , std::size_t rank> dataContainerBase< Q, rank >::dataContainerBase (const buffer_type & data_in) inline explicit
Definition at line 60 of file data_container.hpp.
: buffer_type(data_in) {};
Member Function Documentation
acc()
template<typename Q , std::size_t rank> Q dataContainerBase< Q, rank >::acc (const size_t flatIndex) const inline
Access data via flattened index.
Definition at line 63 of file data_container.hpp.
{
            assert(flatIndex < data.size());
            return data.flat_at(flatIndex);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, multidimensional::multiarray< T, depth >::flat_at(), and multidimensional::multiarray< T, depth >::size().
add_vec() [1/2]
template<typename Q , std::size_t rank> void dataContainerBase< Q, rank >::add_vec (const buffer_type & summand) inline
Check that summand has the right length
Definition at line 148 of file data_container.hpp.
{
            assert(data.is_same_length(summand));
            data += summand;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, and multidimensional::multiarray< T, depth >::is_same_length().
add_vec() [2/2]
template<typename Q , std::size_t rank> template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true> void dataContainerBase< Q, rank >::add_vec (const container & summand) inline
Adds a vector to the data.
Check that summand has the right length
Definition at line 143 of file data_container.hpp.
{
            assert(data.size() == summand.size());
            data += buffer_type(data.length(), summand);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, multidimensional::multiarray< T, depth >::length(), and multidimensional::multiarray< T, depth >::size().
at()
template<typename Q , std::size_t rank> template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true> const Q & dataContainerBase< Q, rank >::at (const Types &... i) const inline
Returns reference to a value for a multiIndex.
Definition at line 85 of file data_container.hpp.
{ return data.at(i...); }
References multidimensional::multiarray< T, depth >::at(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
direct_set()
template<typename Q , std::size_t rank> void dataContainerBase< Q, rank >::direct_set (const size_t flatIndex, Q value) inline
Definition at line 68 of file data_container.hpp.
{
            assert(flatIndex < data.size());
            data.flat_at(flatIndex) = value;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, multidimensional::multiarray< T, depth >::flat_at(), and multidimensional::multiarray< T, depth >::size().
eigen_segment() [1/2]
template<typename Q , std::size_t rank> constexpr auto dataContainerBase< Q, rank >::eigen_segment (const index_type & start, const index_type & end) inline constexpr
Definition at line 153 of file data_container.hpp.
{
            return data.eigen_segment(start, end);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, and multidimensional::multiarray< T, depth >::eigen_segment().
eigen_segment() [2/2]
template<typename Q , std::size_t rank> constexpr auto dataContainerBase< Q, rank >::eigen_segment (const index_type & start, const index_type & end) const inline constexpr
Definition at line 157 of file data_container.hpp.
{
            return data.eigen_segment(start, end);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, and multidimensional::multiarray< T, depth >::eigen_segment().
get_dims()
template<typename Q , std::size_t rank> auto dataContainerBase< Q, rank >::get_dims () const inline
Definition at line 111 of file data_container.hpp.
{ return data.length(); }
References dataContainerBase< Q, rank >::data, and multidimensional::multiarray< T, depth >::length().
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::analyze_tails(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::interpolate_spline(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::interpolate_spline(), and Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_coeffs_from_b().
get_values()
template<typename Q , std::size_t rank> template<my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, my_index_t vecsize, my_index_t sample_size> Eigen::Matrix< Q, vecsize, my_integer_pow< numberFrequencyDims >(sample_size)> dataContainerBase< Q, rank >::get_values (const index_type & index) const inline
Definition at line 162 of file data_container.hpp.
{
            return data.template get_values<numberFrequencyDims, pos_first_freqpoint, vecsize, sample_size>(index);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
get_vec()
template<typename Q , std::size_t rank> const buffer_type & dataContainerBase< Q, rank >::get_vec () const inline
Returns the buffer "data" containing the data.
Definition at line 114 of file data_container.hpp.
{ return data; }
References dataContainerBase< Q, rank >::data.
Referenced by DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), and DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max().
set_vec() [1/3]
template<typename Q , std::size_t rank> void dataContainerBase< Q, rank >::set_vec (const buffer_type && data_in) inline
Definition at line 132 of file data_container.hpp.
{
            assert(data.is_same_length(data_in));
            data = data_in;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, and multidimensional::multiarray< T, depth >::is_same_length().
set_vec() [2/3]
template<typename Q , std::size_t rank> void dataContainerBase< Q, rank >::set_vec (const buffer_type & data_in) inline
Definition at line 127 of file data_container.hpp.
{
            assert(data.is_same_length(data_in));
            data = data_in;
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, and multidimensional::multiarray< T, depth >::is_same_length().
set_vec() [3/3]
template<typename Q , std::size_t rank> template<typename container , std::enable_if_t< std::is_same_v< typename container::value_type, Q > &&!std::is_same_v< container, buffer_type >, bool > = true> void dataContainerBase< Q, rank >::set_vec (const container & data_in) inline
Sets the the buffer "data".
Definition at line 122 of file data_container.hpp.
{
            assert(data.size() == data_in.size());
            data = buffer_type(data.length(), data_in);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), dataContainerBase< Q, rank >::data, multidimensional::multiarray< T, depth >::length(), and multidimensional::multiarray< T, depth >::size().
setvert() [1/2]
template<typename Q , std::size_t rank> void dataContainerBase< Q, rank >::setvert (const Q value, const index_type & idx) inline
Definition at line 104 of file data_container.hpp.
{ data.at(idx) = value; }
References multidimensional::multiarray< T, depth >::at(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
setvert() [2/2]
template<typename Q , std::size_t rank> template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true> void dataContainerBase< Q, rank >::setvert (const Q value, const Types &... i) inline
Sets a value at a multiIndex.
Definition at line 102 of file data_container.hpp.
{ data.at(i...) = value; }
References multidimensional::multiarray< T, depth >::at(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
setvert_vectorized()
template<typename Q , std::size_t rank> template<std::size_t vecsize> void dataContainerBase< Q, rank >::setvert_vectorized (const Eigen::Matrix< Q, vecsize, 1 > & value, const index_type & idx) inline
Definition at line 107 of file data_container.hpp.
{
            data.template set_vectorized<vecsize>(value, idx);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
val() [1/2]
template<typename Q , std::size_t rank> Q dataContainerBase< Q, rank >::val (const index_type & idx) const inline
Definition at line 79 of file data_container.hpp.
{ return data.at(idx); }
References multidimensional::multiarray< T, depth >::at(), correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
val() [2/2]
template<typename Q , std::size_t rank> template<typename... Types, typename std::enable_if_t<(sizeof...(Types)==rank) and(are_all_integral< size_t, Types... >::value), bool > = true> Q dataContainerBase< Q, rank >::val (const Types &... i) const inline
Returns value for a multiIndex.
Definition at line 77 of file data_container.hpp.
{ return data(i...); }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
val_vectorized() [1/2]
template<typename Q , std::size_t rank> template<std::size_t freqrank, std::size_t vecsize> auto dataContainerBase< Q, rank >::val_vectorized (const index_type & idx) const -> Eigen::Matrix<Q, vecsize, 1> inline
Definition at line 94 of file data_container.hpp.
{
            return data.template at_vectorized<vecsize>(idx);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
val_vectorized() [2/2]
template<typename Q , std::size_t rank> template<std::size_t freqrank, std::size_t vecsize, typename... Types, typename std::enable_if_t<(sizeof...(Types)==freqrank+pos_first_freq+1) and(are_all_integral< size_t, Types... >::value), bool > = true> auto dataContainerBase< Q, rank >::val_vectorized (const Types &... i) const -> Eigen::Matrix<Q, vecsize, 1> inline
Definition at line 90 of file data_container.hpp.
{
            return data.template at_vectorized<vecsize>(i...);
        }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and dataContainerBase< Q, rank >::data.
Friends And Related Symbol Documentation
read_state_from_hdf
template<typename Q , std::size_t rank> State< state_datatype, false > read_state_from_hdf (const H5std_string & filename, const unsigned int Lambda_it) friend
State< Q, false >
template<typename Q , std::size_t rank> friend class State< Q, false > friend
Definition at line 395 of file data_container.hpp.
State< Q, true >
template<typename Q , std::size_t rank> friend class State< Q, true > friend
Definition at line 395 of file data_container.hpp.
Member Data Documentation
data
template<typename Q , std::size_t rank> buffer_type dataContainerBase< Q, rank >::data protected
Definition at line 46 of file data_container.hpp.
Referenced by dataContainerBase< Q, rank >::acc(), dataContainerBase< Q, rank >::add_vec(), dataContainerBase< Q, rank >::add_vec(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::analyze_tails(), dataContainerBase< Q, rank >::at(), dataContainerBase< Q, rank >::direct_set(), dataContainerBase< Q, rank >::eigen_segment(), dataContainerBase< Q, rank >::eigen_segment(), Spline< Q, rank, 2, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), Spline< Q, rank, 3, pos_first_freq_index, DataContainer >::get_coeffs_from_derivs(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_curvature_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_max(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xx(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xy(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xyz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_xz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yy(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_yz(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::get_deriv_zz(), dataContainerBase< Q, rank >::get_dims(), dataContainerBase< Q, rank >::get_values(), dataContainerBase< Q, rank >::get_vec(), Spline< Q, rank, 1, pos_first_freq_index, DataContainer >::set_coeffs_from_b(), dataContainerBase< Q, rank >::set_vec(), dataContainerBase< Q, rank >::set_vec(), dataContainerBase< Q, rank >::set_vec(), dataContainerBase< Q, rank >::setvert(), dataContainerBase< Q, rank >::setvert(), dataContainerBase< Q, rank >::setvert_vectorized(), DataContainer< Q, rank, numberFrequencyDims, pos_first_freqpoint, frequencyGrid_type >::shrink_freq_box(), dataContainerBase< Q, rank >::val(), dataContainerBase< Q, rank >::val(), dataContainerBase< Q, rank >::val_vectorized(), and dataContainerBase< Q, rank >::val_vectorized().
The documentation for this class was generated from the following file:
data_container.hpp