SIAM-Keldysh-mfRG: Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic > Class Template Reference
Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic > Class Template Reference
#include <data_buffer.hpp>
Public Types
using index_type = typename dataContainer_type::index_type
using dimensions_type = typename dataContainer_type::dimensions_type
Public Member Functions
Interpolator ()=default
Interpolator (double Lambda, dimensions_type dims, const fRG_config &config)
template<typename result_type = Q, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true>
auto interpolate_impl (const frequencies_type &frequencies, index_type indices) const -> result_type
Private Types
using base_class = Spline<Q,rank,numberFrequencyDims,pos_first_freqpoint,dataContainer_type>
using this_class = Interpolator<Q, rank, numberFrequencyDims, pos_first_freq, dataContainer_type, cubic>
using frequencies_type = std::array<double, numberFrequencyDims>
Static Private Member Functions
static constexpr my_index_t numSamples ()
static constexpr my_index_t numSamples_half ()
template<typename result_type >
static constexpr my_index_t get_vecsize ()
Detailed Description
template<typename Q, size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type>
class Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >
Definition at line 497 of file data_buffer.hpp.
Member Typedef Documentation
base_class
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::base_class = Spline<Q,rank,numberFrequencyDims,pos_first_freqpoint,dataContainer_type> private
Definition at line 498 of file data_buffer.hpp.
dimensions_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::dimensions_type = typename dataContainer_type::dimensions_type
Definition at line 516 of file data_buffer.hpp.
frequencies_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::frequencies_type = std::array<double, numberFrequencyDims> private
Definition at line 501 of file data_buffer.hpp.
index_type
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::index_type = typename dataContainer_type::index_type
Definition at line 515 of file data_buffer.hpp.
this_class
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > using Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::this_class = Interpolator<Q, rank, numberFrequencyDims, pos_first_freq, dataContainer_type, cubic> private
Definition at line 499 of file data_buffer.hpp.
Constructor & Destructor Documentation
Interpolator() [1/2]
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::Interpolator () default
Interpolator() [2/2]
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::Interpolator (double Lambda, dimensions_type dims, const fRG_config & config) inline explicit
Definition at line 519 of file data_buffer.hpp.
: base_class(Lambda, dims, config) {};
Member Function Documentation
get_vecsize()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > template<typename result_type > static constexpr my_index_t Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::get_vecsize () inline static constexpr private
Definition at line 510 of file data_buffer.hpp.
{
        if constexpr(std::is_same_v<result_type, Q>) return 1;
        else { return result_type::RowsAtCompileTime; }
    }
interpolate_impl()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > template<typename result_type = Q, typename std::enable_if_t<(pos_first_freqpoint+numberFrequencyDims< rank) and(numberFrequencyDims<=3), bool > = true> auto Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::interpolate_impl (const frequencies_type & frequencies, index_type indices) const -> result_type inline
Definition at line 523 of file data_buffer.hpp.
{
#ifdef DENSEGRID
        assert(false); // Use "linear" interpolation for dense grid
#endif
        //constexpr my_index_t vecsize = get_vecsize<result_type>();
        // Check if the frequency runs out of the box; if yes: return asymptotic value
        if (base_class::frequencies.is_in_box(frequencies))
        {
            result_type result = base_class::template interpolate_spline<result_type>(frequencies, indices);
            return result;
        } else { //asymptotic value
            if constexpr (std::is_same_v<result_type,Q>) return result_type{};
            else if constexpr(std::is_same_v<result_type,Eigen::Matrix<Q,result_type::RowsAtCompileTime,1>>){return result_type::Zero();}
            else {
                assert(false);
                result_type result;
                return result;
            }
        }
    };
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
numSamples()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > static constexpr my_index_t Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::numSamples () inline static constexpr private
Definition at line 503 of file data_buffer.hpp.
{
        return my_integer_pow<numberFrequencyDims>(my_index_t(2));
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff().
numSamples_half()
template<typename Q , size_t rank, my_index_t numberFrequencyDims, my_index_t pos_first_freqpoint, typename dataContainer_type > static constexpr my_index_t Interpolator< Q, rank, numberFrequencyDims, pos_first_freqpoint, dataContainer_type, cubic >::numSamples_half () inline static constexpr private
Definition at line 506 of file data_buffer.hpp.
{
        return my_integer_pow<numberFrequencyDims-1>(my_index_t(2));
    }
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and my_integer_pow().
The documentation for this class was generated from the following file:
data_buffer.hpp