SIAM-Keldysh-mfRG: symmetry_transformations.c++ File Reference
symmetry_transformations.c++ File Reference
#include "symmetry_transformations.hpp"
Functions
void switch_channel (IndicesSymmetryTransformations &indices)
Function Documentation
switch_channel()
void switch_channel (IndicesSymmetryTransformations & indices)
Definition at line 3 of file symmetry_transformations.c++.
{
    switch (indices.channel_rvert) {
        case 'a':
            indices.channel_rvert = 't';
            break;
        case 't':
            indices.channel_rvert = 'a';
            break;
        default:;
    }
    if (INTERPOL2D_FOR_K3) {
        switch (indices.channel_bubble) {
            case 'a':
                indices.channel_bubble = 't';
                break;
            case 't':
                indices.channel_bubble = 'a';
                break;
            default: ;
        }
    }
}
References correctionFunctionBubble_REG3_Matsubara_PHS_diff(), and INTERPOL2D_FOR_K3.
Referenced by T1(), and T2().